import {runReviewFixChecks} from './review-fixes.mjs';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {LocalClient} from '../local-client.mjs';import {sha,assertNoSecrets,verifyToolManifest} from './evidence.mjs';
const require=createRequire('/Users/leo.cui/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'),{chromium}=require('playwright');
export async function runSettingsBrowserQa(ctx){
 const tools=JSON.parse(await fs.readFile(path.join(ctx.root,'docs/evidence/settings/tool-manifest.json')));await verifyToolManifest(ctx.root,tools);
 const {root,directory,endpoints:e}=ctx,output=path.join(root,'docs/evidence/settings/ui'),password=await fs.readFile(directory+'/password','utf8'),admin=new LocalClient(e.control_plane);await fs.mkdir(output,{recursive:true});await admin.login('e2e-admin',password);const browser=await chromium.launch({headless:true,executablePath:process.env.WEBAPI_BROWSER_EXECUTABLE||'/Users/leo.cui/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),screenshots=[],checks=[];let user;
 const check=name=>checks.push({name,pass:true}),go=async path=>{await page.goto(e.console+path);await page.waitForLoadState('networkidle');},save=async(group,values)=>{const current=await admin.request('/settings/system/'+group),headers={'If-Match':`"${current.revision}"`},preview=await admin.request('/settings/system/'+group+'/preview',{method:'POST',body:{values},headers});return admin.request('/settings/system/'+group,{method:'PUT',headers,body:{values,confirmationToken:preview.confirmationToken}});};
 async function login(name){await page.goto(e.console);await page.getByLabel('用户名').fill(name);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByLabel('当前组织').waitFor();}
 async function snap(name){await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});const b=await fs.readFile(path.join(output,name+'.png'));assert.equal(b.readUInt32BE(16),1440);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,name+' horizontal overflow');screenshots.push({name,file:'ui/'+name+'.png',width:1440,height:1100,sha256:sha(b)});}
 try{
 await save('security',{sessionTtlMinutes:480,passwordMinLength:16,passwordComplexity:'LengthOnly',allowedOrigins:[]});await save('audit',{auditRetentionDays:365,auditExportEnabled:true});await login('e2e-admin');await go('/settings/system');await page.getByLabel('Session TTL / 分钟',{exact:true}).waitFor();assert.equal(await page.getByLabel('Session TTL / 分钟',{exact:true}).inputValue(),'480');await snap('01-security');check('平台级来源与兼容默认');
 for(const [group,label,name,count]of [['release','发布设置','02-release',2],['gateway','Gateway 默认参数','03-gateway',3],['audit','审计设置','04-audit',2],['notification','通知配置','05-notification',6]]){await page.getByRole('button',{name:label,exact:false}).click();await page.getByRole('heading',{name:label,exact:true}).waitFor();await page.locator('.settings-field').first().waitFor();assert.equal(await page.locator('.settings-field').count(),count);if(group==='release')assert(await page.getByLabel('PROD 默认审批').isDisabled());if(group==='gateway')assert(await page.getByText('待部署配置；保存不会应用到运行实例',{exact:false}).count());await snap(name);}check('五组十七字段与未应用意向');
 assert.equal(await page.getByLabel('SMTP SecretRef 操作').inputValue(),'Keep');await page.getByLabel('SMTP SecretRef 操作').selectOption('Replace');await page.getByLabel('SMTP SecretRef 替换值').fill('vault://qa/browser-draft');await page.getByRole('button',{name:'测试配置结构',exact:true}).click();await page.getByText('结构校验通过；未解析 SecretRef，未连接 SMTP/Webhook，未发送通知。',{exact:false}).waitFor();await page.getByRole('link',{name:'审计日志',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/settings/system');assert.equal(await page.getByLabel('SMTP SecretRef 替换值').inputValue(),'vault://qa/browser-draft');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'放弃当前输入',exact:true}).click();check('引用操作与真实结构测试和离开保护');
 await page.getByRole('button',{name:'安全策略',exact:false}).click();await page.waitForLoadState('networkidle');await page.getByLabel('Session TTL / 分钟',{exact:true}).fill('15');const security=await admin.request('/settings/system/security');await save('security',{...security.values,sessionTtlMinutes:20});await page.getByRole('button',{name:'预览并保存',exact:true}).click();await page.getByText('配置修订冲突，输入已保留。',{exact:true}).waitFor();assert.equal(await page.getByLabel('Session TTL / 分钟',{exact:true}).inputValue(),'15');assert.equal(await page.getByRole('button',{name:'采用当前读取的修订并重新预览'}).count(),0);await snap('06-conflict');await page.getByRole('button',{name:'读取最新并重新核对',exact:true}).click();await page.getByRole('button',{name:'采用当前读取的修订并重新预览'}).click();assert.equal(await page.getByLabel('Session TTL / 分钟',{exact:true}).inputValue(),'15');await page.getByRole('button',{name:'预览并保存',exact:true}).click();await page.getByRole('dialog').waitFor();await snap('07-confirmation');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('[role=dialog]')!==null),true);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('button',{name:'预览并保存',exact:true}).click();await page.getByRole('button',{name:'确认保存',exact:true}).click();await page.getByText('保存成功。请按字段提示核对生效条件。').waitFor();assert.equal((await admin.request('/settings/system/security')).values.sessionTtlMinutes,15);check('真实412保留输入和显式复核保存与键盘弹窗');
 await go('/routes');await page.getByRole('button',{name:'＋ 新建路由',exact:true}).click();assert.equal(await page.getByLabel('基础超时 / 毫秒',{exact:false}).inputValue(),'12000');await snap('08-route-default');await page.getByRole('button',{name:'关闭',exact:true}).click();check('新路由读取平台默认且原路由不变');
 await go('/audit');const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 CSV',exact:true}).click();const file=await download,stream=await file.createReadStream(),chunks=[];for await(const b of stream)chunks.push(b);const csv=Buffer.concat(chunks).toString('utf8');assert(csv.startsWith('id,createdAt,actorId,'));assert(!csv.includes('vault://qa/'));const audit=(await admin.request('/settings/system/audit')).values;await save('audit',{...audit,auditExportEnabled:false});await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('平台已关闭审计导出；日志查询仍可用').waitFor();assert(await page.getByRole('button',{name:'导出 CSV',exact:true}).isDisabled());await snap('09-audit-disabled');await save('audit',{...audit,auditExportEnabled:true});check('真实CSV下载与关闭时保留查询');
 user=await admin.request('/users',{method:'POST',body:{username:'qa-settings-'+crypto.randomUUID().slice(0,8),displayName:'设置撤权验收',password}});const platform=(await admin.request('/roles')).find(r=>r.code==='PlatformAdmin'&&r.isSystem&&!r.organizationId);user=await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{roleIds:[platform.id]}});await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{scopes:[{scope:{organizationId:ctx.context.organizationId},accessMode:'read_write'}]}});await context.clearCookies();await login(user.username);await go('/settings/system');await page.getByRole('button',{name:'通知配置',exact:false}).click();await page.getByLabel('SMTP SecretRef 操作').selectOption('Replace');await page.getByLabel('SMTP SecretRef 替换值').fill('vault://qa/revoked-draft');let release,hit;const received=new Promise(r=>hit=r),held=new Promise(r=>release=r);let once=true;await page.route('**/api/v1/settings/system/notification',async route=>{if(!once||route.request().method()!=='GET')return route.continue();once=false;const response=await route.fetch();hit();await held;await route.fulfill({response});});await page.getByRole('button',{name:'读取最新配置',exact:true}).click();await received;const current=(await admin.request('/users')).items.find(u=>u.id===user.id);await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':`"${current.revision}"`},body:{roleIds:[]}});await page.getByLabel('刷新会话与权限').click();await page.getByRole('alert').filter({hasText:'已清空配置与引用草稿'}).first().waitFor();release();await page.waitForLoadState('networkidle');assert.equal(await page.locator('.settings-field').count(),0);assert.equal(await page.getByLabel('SMTP SecretRef 替换值').count(),0);await snap('10-revoked');check('真实撤权清空引用草稿与迟到响应隔离');
 checks.push(...await runReviewFixChecks(ctx));await verifyToolManifest(root,tools);const result={complete:true,toolManifestHash:tools.sha256,viewport:{width:1440,height:1100},classification:'real-isolated-server-browser-qa',project:ctx.project,sourceManifestHash:ctx.image.sourceManifestHash,screenshots,checks,defects:[],visualReviewComplete:false};assertNoSecrets(result,[password,await fs.readFile(directory+'/credential','utf8')]);await fs.writeFile(path.join(output,'qa.json'),JSON.stringify(result,null,2)+'\n');console.log('Settings browser checks passed; saved pixels require review.');return result;
 }catch(error){await page.screenshot({path:path.join(root,'.superpowers/sdd/2026-10-05-system-settings-implementation/ui-failure.png')});throw error;}finally{await browser.close();}
}
