import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {LocalClient} from '../local-client.mjs';
const require=createRequire('/Users/leo.cui/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'),{chromium}=require('playwright');
export async function runReviewFixChecks(ctx,mode='both'){
 const password=await fs.readFile(ctx.directory+'/password','utf8'),admin=new LocalClient(ctx.endpoints.control_plane);const identity=await admin.login('e2e-admin',password),browser=await chromium.launch({headless:true,executablePath:process.env.WEBAPI_BROWSER_EXECUTABLE||'/Users/leo.cui/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),checks=[];let originalScopes;
 try{
 await page.goto(ctx.endpoints.console+'/settings/system');await page.getByLabel('用户名').fill('e2e-admin');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByLabel('Session TTL / 分钟',{exact:true}).waitFor();
 if(mode!=='scope'){const field=page.getByLabel('Allowed Origins',{exact:true});await field.fill('https://one.example.com');await field.press('End');await field.press('Enter');await field.pressSequentially('https://two.example.com');assert.equal(await field.inputValue(),'https://one.example.com\nhttps://two.example.com');await page.getByRole('button',{name:'测试配置结构',exact:true}).click();await page.getByText('结构校验通过；未解析 SecretRef，未连接 SMTP/Webhook，未发送通知。',{exact:false}).waitFor();checks.push({name:'OriginsRealKeyboardNewline',pass:true});page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'放弃当前输入',exact:true}).click();}
 if(mode!=='origins'){originalScopes=await admin.request('/users/'+identity.id+'/scopes');await page.getByLabel('Session TTL / 分钟',{exact:true}).fill('17');const actor=(await admin.request('/users')).items.find(u=>u.id===identity.id);await admin.request('/users/'+identity.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${actor.revision}"`},body:{scopes:[{scope:{organizationId:ctx.context.organizationId,projectId:ctx.context.projectId},accessMode:'read_write'}]}});await page.getByLabel('刷新会话与权限').click();await page.waitForLoadState('networkidle');await page.getByLabel('Session TTL / 分钟',{exact:true}).waitFor();assert.equal(await page.getByLabel('Session TTL / 分钟',{exact:true}).inputValue(),'17');assert.equal(await page.getByText('未保存修改',{exact:true}).count(),1);checks.push({name:'UnrelatedScopeRefreshPreservesPlatformDraft',pass:true});}
 return checks;
 }finally{if(originalScopes){const current=(await admin.request('/users')).items.find(u=>u.id===identity.id);await admin.request('/users/'+identity.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${current.revision}"`},body:{scopes:originalScopes}});}await browser.close();}
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(import.meta.filename)){const root=path.resolve(import.meta.dirname,'../..'),info=JSON.parse(await fs.readFile(root+'/.runtime/settings-review.json')),ctx=JSON.parse(await fs.readFile(info.directory+'/review-context.json'));console.log(JSON.stringify(await runReviewFixChecks(ctx,process.argv[2]||'both')));}
