import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {LocalClient} from '../local-client.mjs';import {sha,assertNoSecrets} from './evidence.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(action,predicate){const until=Date.now()+90000;while(Date.now()<until){const value=await action();if(predicate(value))return value;await delay(400);}throw Error('Settings scenario did not converge');}
export async function runSettingsScenario(c){
 const {context:s,endpoints:e,directory,compose,image}=c,password=await fs.readFile(directory+'/password','utf8'),credential=await fs.readFile(directory+'/credential','utf8'),admin=new LocalClient(e.control_plane),reviewer=new LocalClient(e.control_plane),security=new LocalClient(e.control_plane);await admin.login('e2e-admin',password);await reviewer.login('e2e-approver',password);await security.login('e2e-security',password);
 const checks=[],requests=[],check=(name,evidence)=>{checks.push({name,pass:true,evidence});console.log('Verified '+name);},write=(url,body,revision,method='POST')=>admin.request(url,{method,body,headers:revision===undefined?undefined:{'If-Match':`"${revision}"`}}),sql=q=>compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',q);
 async function save(group,values){const before=await admin.request('/settings/system/'+group),preview=await write('/settings/system/'+group+'/preview',{values},before.revision);return write('/settings/system/'+group,{values,confirmationToken:preview.confirmationToken},before.revision,'PUT');}
 async function publish(versionIds){const env=await admin.request('/environments/'+s.environmentId),body={baseConfigVersion:env.desiredConfigVersion||0,versionIds},preview=await write(`/environments/${s.environmentId}/releases/preview`,body),draft=await write(`/environments/${s.environmentId}/releases`,{...body,resourceRevisions:preview.resourceRevisions});await write('/releases/'+draft.id+'/submit');await reviewer.request('/releases/'+draft.id+'/approve',{method:'POST',body:{comment:'系统设置路由独立审批'}});await security.request('/releases/'+draft.id+'/approve',{method:'POST',body:{comment:'系统设置安全独立复核'}});await write('/releases/'+draft.id+'/publish');return wait(()=>admin.request('/releases/'+draft.id),r=>{if(r.state==='Failed')throw Error('Release failed');return r.state==='Succeeded'&&r.targets.length===2&&r.targets.every(t=>t.acknowledged);});}
 async function payload(version){return Buffer.from((await sql(`SELECT encode(s.payload_bytes,'base64') FROM gateway_config_snapshots s JOIN gateway_config_versions v ON v.id=s.config_version_id WHERE v.environment_id='${s.environmentId}' AND v.version_no=${Number(version)}`)).replaceAll('\n',''),'base64');}
 const version=await write('/apis/'+s.apiId+'/versions',{version:'1.0.0'}),old=await write(`/environments/${s.environmentId}/routes`,{apiVersionId:version.id,routeName:'Orders',path:'/orders/{*rest}',methods:['GET'],clusterId:s.clusterId,priority:100,enabled:true,requireApiKey:true,timeoutMs:30000}),original=await publish([version.id]),snapshot=await payload(original.targetConfigVersion),beforeNodes=(await admin.request(`/environments/${s.environmentId}/gateway-nodes`)).items.map(n=>({id:n.id,configVersion:n.currentConfigVersion,deploymentSequence:n.currentDeploymentSequence}));await fs.writeFile(directory+'/original.snapshot',snapshot,{mode:0o600});
 const gateway=(await admin.request('/settings/system/gateway')).values,saved=await save('gateway',{...gateway,defaultRouteTimeoutMs:12000});assert.equal(saved.values.defaultRouteTimeoutMs,12000);await compose('restart','control-plane');e.control_plane='http://'+await compose('port','control-plane','8080');admin.base=e.control_plane;reviewer.base=e.control_plane;security.base=e.control_plane;await wait(async()=>{try{return (await fetch(e.control_plane+'/health/live')).status;}catch{return 0;}},v=>v===200);await admin.login('e2e-admin',password);await reviewer.login('e2e-approver',password);await security.login('e2e-security',password);assert.equal((await admin.request('/settings/system/gateway')).revision,saved.revision);check('settings-persistence',{revision:saved.revision,timeoutMs:12000,restartedControlPlane:true});
 assert.deepEqual(await payload(original.targetConfigVersion),snapshot);assert.deepEqual((await admin.request(`/environments/${s.environmentId}/gateway-nodes`)).items.map(n=>({id:n.id,configVersion:n.currentConfigVersion,deploymentSequence:n.currentDeploymentSequence})),beforeNodes);check('snapshot-unchanged-before-publish',{beforeSha256:sha(snapshot),afterSha256:sha(await payload(original.targetConfigVersion)),nodes:beforeNodes});
 const fresh=await write(`/environments/${s.environmentId}/routes`,{apiVersionId:version.id,routeName:'SettingsProbe',path:'/settings-probe/{*rest}',methods:['GET'],clusterId:s.clusterId,priority:110,enabled:true,requireApiKey:true});assert.equal(fresh.timeoutMs,12000);assert.equal((await admin.request('/routes/'+old.id)).timeoutMs,30000);const finalRelease=await publish([version.id]),active=JSON.parse(await payload(finalRelease.targetConfigVersion));assert.equal(active.routes.find(r=>r.routeId===fresh.id||r.id===fresh.id)?.timeoutMs,12000);assert.equal(active.routes.find(r=>r.routeId===old.id||r.id===old.id)?.timeoutMs,30000);check('both-gateways-ack',{version:finalRelease.targetConfigVersion,sequence:finalRelease.deploymentSequence,targets:finalRelease.targets.map(t=>({nodeId:t.gatewayNodeId,acknowledged:t.acknowledged})),oldTimeoutMs:30000,newTimeoutMs:12000});
 for(const node of ['gateway_a','gateway_b'])for(const path of ['/orders','/settings-probe']){const response=await fetch(e[node]+path,{headers:{'X-API-Key':credential},signal:AbortSignal.timeout(15000)});assert.equal(response.status,200);requests.push({node,path,status:response.status});}check('old-route-still-works',{requests});
 const audit=(await admin.request('/settings/system/audit')).values;await save('audit',{...audit,auditExportEnabled:false});const closed=await fetch(e.control_plane+'/api/v1/audit-logs/export',{headers:{Cookie:[...admin.cookies].map(([k,v])=>k+'='+v).join('; ')}});assert.equal(closed.status,403);assert.equal((await admin.request('/audit-logs')).exportAllowed,false);check('audit-export-disabled',{exportStatus:closed.status,listAvailable:true});await save('audit',{...audit,auditExportEnabled:true});
 const ref='vault://qa/'+randomUUID(),notification={smtpHost:'smtp.example.com',smtpPort:587,fromEmail:'api@example.com',smtpSecretRef:{operation:'Replace',reference:ref},webhookUrl:null,webhookSecretRef:{operation:'Keep'}},tested=await write('/settings/system/notification/validate',{values:notification});assert.equal(tested.testKind,'StructuralOnly');const configured=await save('notification',notification);assert(!JSON.stringify(configured).includes(ref));const kept=await save('notification',{...notification,smtpSecretRef:{operation:'Keep'}});assert.equal(kept.values.smtpSecretRef.hasConfiguredReference,true);check('references-and-structure-only',{testKind:tested.testKind,referenceReadBack:false,keepPreserved:true});
 const result={schemaVersion:1,complete:false,classification:'real-isolated-system-settings',project:c.project,sourceManifestHash:image.sourceManifestHash,image,scope:{organizationId:s.organizationId,projectId:s.projectId,environmentId:s.environmentId},apiId:s.apiId,oldRouteId:old.id,newRouteId:fresh.id,checks,finalRelease,requests,time:new Date().toISOString()};assertNoSecrets(result,[password,credential,ref]);return result;
}
