import fs from 'node:fs/promises';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const exec=promisify(execFile),root=path.resolve(import.meta.dirname,'../..'),evidence=path.join(root,'docs/evidence/settings'),reuse=process.argv.includes('--reuse-e2e'),suites={};await fs.mkdir(evidence+'/tests',{recursive:true});
async function command(binary,args){try{return await exec(binary,args,{cwd:root,env:process.env,maxBuffer:32*1024*1024});}catch(error){throw Object.assign(Error('Verification command failed: '+args.slice(0,3).join(' ')),{output:(error.stdout||'')+(error.stderr||'')});}}
try{
 for(const mode of ['domain','integration','gateway','console']){console.log('Verifying '+mode);let result;try{result=await command('bash',['scripts/check-settings.sh',mode]);}catch(error){await fs.writeFile(evidence+'/tests/'+mode+'.log',error.output);throw error;}const text=result.stdout+result.stderr;await fs.writeFile(evidence+'/tests/'+mode+'.log',text);const match=text.match(mode==='console'?/ℹ tests (\d+)/:/Passed!\s+- Failed:\s+0, Passed:\s+(\d+)/);if(!match)throw Error('Missing passing suite count: '+mode);suites[mode]={pass:true,total:Number(match[1])};}
 const runner=await command(process.execPath,['--test','tests/runtime/settings-runner.test.mjs']);await fs.writeFile(evidence+'/tests/runner.log',runner.stdout+runner.stderr);const count=runner.stdout.match(/ℹ tests (\d+)/);if(!count)throw Error('Missing runner result');suites.runner={pass:true,total:Number(count[1])};
 if(!reuse){try{await fs.access(root+'/.runtime/settings-review.json');console.log('Cleaning previous owned fixture');await command('bash',['scripts/check-settings.sh','cleanup']);}catch(error){if(error.code!=='ENOENT')throw error;}console.log('Freezing and running real double-gateway acceptance');const e2e=await command('bash',['scripts/check-settings.sh','e2e','--retain-for-review']);await fs.writeFile(evidence+'/tests/e2e.log',e2e.stdout+e2e.stderr);const ui=await command('bash',['scripts/check-settings.sh','browser']);await fs.writeFile(evidence+'/tests/browser.log',ui.stdout+ui.stderr);}
 const result=JSON.parse(await fs.readFile(evidence+'/verification.json'));await fs.writeFile(evidence+'/regression.json',JSON.stringify({complete:true,sourceManifestHash:result.sourceManifestHash,toolManifestHash:result.toolManifestHash,suites,time:new Date().toISOString()},null,2)+'\n');
 if(reuse){await command('python3',['scripts/package-settings.py','--root',root,'--evidence',evidence,'--check-only']);console.log('Verified current source and reviewed screenshots.');}else console.log('Regression and browser interactions passed; inspect saved pixels before delivery.');
}catch(error){await fs.writeFile(evidence+'/regression.json',JSON.stringify({complete:false,suites,message:error.message,time:new Date().toISOString()},null,2));console.error(error.message);process.exitCode=1;}
