import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {createElement} from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {createServer} from 'vite';import {fileURLToPath} from 'node:url';
let server,Jwt,Retry,Cache,Form,Actions,Review,Traffic,Provider;before(async()=>{server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});Jwt=(await server.ssrLoadModule('/src/policies/JwtPolicyFields.tsx')).JwtPolicyFields;Retry=(await server.ssrLoadModule('/src/policies/RetryPolicyFields.tsx')).RetryPolicyFields;Cache=(await server.ssrLoadModule('/src/policies/CachePolicyFields.tsx')).CachePolicyFields;({PolicyForm:Form,PolicyEditorActions:Actions}=await server.ssrLoadModule('/src/policies/PolicyForm.tsx'));Review=(await server.ssrLoadModule('/src/policies/PolicyReleaseReview.tsx')).AdvancedPolicyReview;Traffic=(await server.ssrLoadModule('/src/observability/ObservationDrawer.tsx')).AdvancedTrafficDetails;Provider=(await server.ssrLoadModule('/src/auth/SessionProvider.tsx')).SessionProvider;});after(async()=>server?.close());const render=(Component,props)=>renderToStaticMarkup(createElement(Provider,null,createElement(Component,props)));
const jwt={mode:'JWT',issuer:'https://issuer.invalid',audiences:['api'],allowedAlgorithms:['RS256'],allowedTokenTypes:['JWT'],clockSkewSeconds:30,maxTokenLifetimeSeconds:3600,applicationClaim:'azp',applicationMappings:[{claimValue:'client',applicationId:'app'}],jwks:{keys:[{kid:'public-first',kty:'RSA',alg:'RS256',use:'sig',n:'public',e:'AQAB'}]},forwardBearer:false};
test('JwtFieldsExposePublicLocalFileAndScopedMappingWithoutTokenOrPrivateKeyInput',()=>{const html=render(Jwt,{config:jwt,change(){},disabled:false,applications:[{id:'app',name:'可见应用'}]});for(const label of ['Issuer','Audience','公开 JWKS','应用映射','可见应用','转发 Bearer','固定公钥'])assert.match(html,new RegExp(label));assert.match(html,/type="file"/);assert.doesNotMatch(html,/密码|client.secret|access_token|localStorage|已发布/);assert.match(html,/public-first/);});
test('ReadonlyActionsHaveOnlyStructuralCheckAndNoSaveOrReleaseEntry',()=>{const html=render(Actions,{allowed:false,canRelease:false,validate(){},save(){},release(){}});assert.match(html,/检查结构/);assert.doesNotMatch(html,/保存工作配置|提交发布/);const editable=render(Actions,{allowed:true,canRelease:true,save(){},release(){},validate(){}});assert.match(editable,/<button[^>]*type="button"[^>]*>保存工作配置<\/button>/);});
test('SixTypeFormDisplaysJwtAndReadonlyFieldsAreDisabled',()=>{const html=render(Form,{draft:{name:'JWT',type:'authentication',config:jwt,enabled:true},disabled:true,change(){},applications:[]});assert.match(html,/<fieldset[^>]*disabled/);assert.match(html,/JWT/);assert.match(html,/公开 JWKS/);assert.doesNotMatch(html,/type="submit"/);});
test('RetryAndCacheUseDeploymentLimitsAndExplicitReplayConsistencyBoundaries',()=>{const retry=render(Retry,{config:{maxAttempts:3,perAttemptTimeoutMs:1000,baseDelayMs:100,maxDelayMs:1000,jitterPercent:20,retryStatusCodes:[502,503,504],retryConnectionFailures:true},change(){},disabled:false});assert.match(retry,/GET \/ HEAD/);assert.match(retry,/最多物理尝试/);assert.match(retry,/半开/);const cache=render(Cache,{config:{ttlSeconds:60,maxEntryBytes:4096,varyHeaders:['Accept'],identityPartition:'VerifiedIdentity',redisFailureMode:'Bypass'},limits:{maxEntryBytes:8192,allowedVaryHeaders:['Accept','X-Tenant']},change(){},disabled:false});assert.match(cache,/8192/);assert.match(cache,/X-Tenant/);assert.match(cache,/身份分区/);assert.match(cache,/即时一致/);assert.doesNotMatch(cache,/HMAC.*<input/);});
test('ReviewShowsColdStartFixedKeysBearerRiskAndActualMaximum',()=>{const html=render(Review,{policies:[{id:'a',type:'authentication',config:JSON.stringify({...jwt,forwardBearer:true})},{id:'r',type:'retry',config:'{"maxAttempts":3}'},{id:'c',type:'cache',config:'{"ttlSeconds":60}'}],baselinePolicies:[{id:'a',type:'authentication',config:JSON.stringify({...jwt,jwks:{keys:[{kid:'removed'}]}})}]});for(const label of ['public-first','removed','缓存冷启动','转发 Bearer','3 次','应用映射','审批'])assert.match(html,new RegExp(label));assert.doesNotMatch(html,/已发布|签名验证通过/);});
test('MissingTrafficDataIsNotInventedAsZeroAndCacheHitShowsNoUpstream',()=>{const missing=render(Traffic,{});assert.match(missing,/来源未提供/);assert.doesNotMatch(missing,/0 次上游/);const hit=render(Traffic,{attemptCount:0,cacheDisposition:'Hit',forwardAttempts:[]});assert.match(hit,/缓存命中/);assert.match(hit,/0 次上游/);const retries=render(Traffic,{attemptCount:3,cacheDisposition:'Stored',forwardAttempts:[{number:1,status:503,outcome:'Completed',durationSeconds:.01,destinationId:'visible'}]});assert.match(retries,/503/);assert.match(retries,/visible/);});
