import test from 'node:test';
import assert from 'node:assert/strict';
import {notificationSettingsInput,notificationTestLabel,mayTestNotification,createNotificationTestState,notificationTestState} from '../src/notifications/settings-state.mjs';
import {applySettingsFailure,toSettingsInput} from '../src/settings/state.mjs';
const saved={loaded:{revision:1},etag:'"1"',dirty:false,conflict:false,busy:false,authorized:true};
test('queuedTestIsNotSuccess',()=>{assert.equal(notificationTestLabel({status:'Queued'}),'已排队，等待实际回执');assert.match(notificationTestLabel({status:'Accepted'}),/服务已接受/);assert.doesNotMatch(notificationTestLabel({status:'Accepted'}),/阅读成功|业务完成/);});
test('unsavedOrStaleRevisionCannotBeTested',()=>{assert.equal(mayTestNotification(saved),true);for(const patch of [{dirty:true},{conflict:true},{busy:true},{authorized:false},{loaded:{revision:0}},{etag:null}])assert.equal(mayTestNotification({...saved,...patch}),false);assert.equal(mayTestNotification({...saved,values:{smtpEnabled:false,webhookEnabled:false}}),true);});
test('secretKeepNeverBecomesPlaceholderReplace',()=>{const response={group:'notification',values:{smtpSecretRef:{hasConfiguredReference:true,provider:'local'},webhookSecretRef:{hasConfiguredReference:false,provider:null}}};const values=notificationSettingsInput(response);assert.deepEqual(values.smtpSecretRef,{operation:'Keep'});assert.deepEqual(values.webhookSecretRef,{operation:'Keep'});assert.equal(values.smtpEnabled,false);assert.equal(values.smtpSecurity,'StartTlsRequired');assert.equal(values.webhookEnabled,false);assert.deepEqual(toSettingsInput(response),values);});
test('lateReceiptCannotOverwriteNewRevision',()=>{const old=createNotificationTestState('Email',1,'manager');const started=notificationTestState(old,{type:'begin',key:'original'});const current=notificationTestState(started,{type:'revision',revision:2});assert.equal(current.revision,2);assert.ok(current.epoch>started.epoch);assert.equal(notificationTestState(current,{type:'receipt',epoch:started.epoch,revision:1,receipt:{status:'Accepted'}}),current);});
test('deniedClearsTargetAndSecretDraft',()=>{const original={...createNotificationTestState('Email',1,'manager'),email:'private@example.test',key:'operation',receipt:{id:'private',status:'Queued'}};const denied=notificationTestState(original,{type:'failure',epoch:0,status:403,message:'denied'});assert.equal(denied.email,'');assert.equal(denied.receipt,null);assert.equal(denied.key,null);assert.equal(denied.invalid,true);assert.equal(applySettingsFailure({values:{smtpSecretRef:{operation:'Replace',reference:'vault://private/value'}},requestEpoch:0,group:'notification'},403).values,null);});
test('testErrorsPreserveTargetAndRetryKeyWhile412RequiresReload',()=>{const original={...createNotificationTestState('Email',1,'manager'),email:'private@example.test',key:'same',busy:true};const failed=notificationTestState(original,{type:'failure',epoch:0,status:412,message:'changed'});assert.equal(failed.email,original.email);assert.equal(failed.key,'same');assert.equal(failed.conflict,true);assert.equal(failed.busy,false);assert.equal(notificationTestState(failed,{type:'begin',key:'different'}),failed);});
test('closedOrChangedAuthorityDiscardsEveryLateResponse',()=>{const original={...createNotificationTestState('Email',1,'manager'),email:'private@example.test',receipt:{status:'Queued'}};for(const type of ['close','denied']){const cleared=notificationTestState(original,{type});assert.equal(cleared.email,'');assert.equal(cleared.receipt,null);assert.ok(cleared.epoch>original.epoch);assert.equal(notificationTestState(cleared,{type:'receipt',epoch:0,revision:1,receipt:{status:'Accepted'}}),cleared);}});

test('notificationConsoleLinkSelectsKnownSettingsGroup',async()=>{const {settingsGroupFromSearch}=await import('../src/settings/state.mjs');for(const group of ['security','release','gateway','audit','notification'])assert.equal(settingsGroupFromSearch('?tab='+group),group);for(const search of ['', '?tab=unknown','?tab=notification&tab=security','?tab=Notification'])assert.equal(settingsGroupFromSearch(search),'security');});
