import {test} from 'node:test';import assert from 'node:assert/strict';
import {pipelineStageActions,acceptPipelineResponse,pipelineAuthorityKey,pipelineStatusLabel,pipelineCountLabel,pipelineReturnTo} from '../src/delivery/pipeline-state.mjs';
const actor={id:'u',permissions:['pipeline.run','release.create','release.publish','release.test.record','release.verify','approval.act'],scopes:[]};
const stage=(patch={})=>({id:'s',runId:'r',status:'AwaitMapping',runStatus:'Active',actualReleaseStatus:null,profile:{isProduction:false},eligibility:{canPrepare:true,canMaterialize:false,canRecord:false,canRequestAcceptance:false,canReopen:false,canCancelRun:false},...patch});
test('delegate sees permitted current stage without chain controls',()=>{const actions=pipelineStageActions(stage(),actor);assert.ok(actions.includes('prepare-promotion'));assert.ok(!actions.includes('cancel-run'));});
test('paused and timed out stages cannot execute but may explicitly reopen eligible closed attempt',()=>{for(const state of ['Paused','TimedOut']){const s=stage({runStatus:state,eligibility:{canPrepare:true,canRecord:true,canReopen:true,canCancelRun:true}}),a=pipelineStageActions(s,actor);assert.ok(!a.includes('prepare-promotion'));assert.ok(!a.includes('record-verification'));assert.ok(a.includes('reopen-stage'));assert.ok(a.includes('cancel-run'));}});
test('actual publishing prevents reopen regardless of optimistic flag',()=>assert.ok(!pipelineStageActions(stage({actualReleaseStatus:'Publishing',eligibility:{canReopen:true}}),actor).includes('reopen-stage')));
test('evidence recording retains original permission and does not require pipeline.run',()=>{const s=stage({status:'AwaitEvidence',eligibility:{canRecord:true,canRequestAcceptance:true}}),a=pipelineStageActions(s,{id:'evidence',permissions:['release.test.record']});assert.ok(a.includes('record-verification'));assert.ok(a.includes('request-acceptance'));assert.deepEqual(pipelineStageActions(s,{permissions:[]}),[]);});
test('production cannot materialize source artifact and uses independent production verification',()=>{const s=stage({profile:{isProduction:true},status:'AwaitVerification',eligibility:{canMaterialize:true,canRecord:true,canVerifyProduction:true}}),a=pipelineStageActions(s,actor);assert.ok(a.includes('verify-production'));assert.ok(!a.includes('materialize-artifact'));assert.ok(!a.includes('record-verification'));});
test('mapping precheck approval publish only use current server eligibility',()=>{const s=stage({formalPromotionId:'p',promotion:{eligibility:{canEditMapping:true,canSubmit:true,canPublish:true},precheck:{canSubmit:true}},formal:{approvalEligibility:{canAct:true}}});const a=pipelineStageActions(s,actor);for(const x of ['mapping','precheck','submit','approve','publish'])assert.ok(a.includes(x),x);assert.deepEqual(pipelineStageActions({...s,runStatus:'Completed'},actor),[]);});
test('old attempt profile actor resource epoch responses are discarded',()=>{const key=pipelineAuthorityKey(actor,'s','a1','hash',1);assert.equal(acceptPipelineResponse(key,key,{}),true);for(const other of [pipelineAuthorityKey(actor,'s','a2','hash',1),pipelineAuthorityKey(actor,'s','a1','other',1),pipelineAuthorityKey({...actor,id:'other'},'s','a1','hash',1),pipelineAuthorityKey(actor,'s','a1','hash',2)])assert.equal(acceptPipelineResponse(key,other,{}),false);assert.equal(acceptPipelineResponse('', '',{}),false);});
test('historical completion never implies current node success',()=>{assert.match(pipelineStatusLabel('Completed'),/历史/);assert.match(pipelineStatusLabel('Deploying'),/节点/);});
test('restricted unknown counts cannot appear as zero',()=>{assert.equal(pipelineCountLabel(null,'active'),'受限');assert.equal(pipelineCountLabel({active:0},'active'),0);assert.equal(pipelineCountLabel({active:NaN},'active'),'受限');});
test('safe trace return preserves approval filters and stage path but rejects external and traversal',()=>{for(const path of ['/approvals?view=HandledMine&environmentId=e','/delivery/pipeline-stages/s','/delivery/pipeline-runs/r?status=Active'])assert.equal(pipelineReturnTo('?returnTo='+encodeURIComponent(path)),path);for(const path of ['https://evil','//evil','/delivery/pipeline-stages/../settings','/approvals#frag','/approvals\\evil'])assert.equal(pipelineReturnTo('?returnTo='+encodeURIComponent(path)),undefined);});

test('stage evidence submits attempt-bound context through stage endpoint while production keeps original endpoint',async()=>{const {pipelineVerificationCommand}=await import('../src/delivery/pipeline-state.mjs');const evidence={type:'Integration',result:'Passed'},source=pipelineVerificationCommand({stageId:'s',artifactId:'a',contextHash:'hash'},evidence);assert.equal(source.path,'/release-pipeline-run-stages/s/verifications');assert.deepEqual(source.body,{expectedContextHash:'hash',evidence});const production=pipelineVerificationCommand({promotionId:'p',artifactId:'a',contextHash:'prod'},evidence);assert.equal(production.path,'/release-promotions/p/verifications');assert.equal(production.body.expectedContextHash,'prod');});
test('stage summary changes expire an open promotion editor and verification context',async()=>{const {pipelineSummaryKey}=await import('../src/delivery/pipeline-state.mjs'),row={id:'s',currentAttemptId:'a',profileHash:'h',revision:2,runStatus:'Active',actualReleaseId:'r',actualConfigVersion:1,actualDeploymentSequence:2};for(const patch of [{currentAttemptId:'b'},{revision:3},{runStatus:'Paused'},{actualDeploymentSequence:3},{profileHash:'different'}])assert.notEqual(pipelineSummaryKey(row),pipelineSummaryKey({...row,...patch}));});

test('partial run and trace render only disclosed links with nullable counts',async()=>{const {createServer}=await import('vite'),{fileURLToPath}=await import('node:url'),{createElement}=await import('react'),{renderToStaticMarkup}=await import('react-dom/server');const server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});try{const {PipelineTrace}=await server.ssrLoadModule('/src/delivery/PipelineTrace.tsx'),{PipelineRunList}=await server.ssrLoadModule('/src/pages/ReleasePipelineRuns.tsx'),{PipelinePagination}=await server.ssrLoadModule('/src/pages/ReleasePipelines.tsx');const trace=renderToStaticMarkup(createElement(PipelineTrace,{trace:{stageId:'stage',runId:'run',pipelineId:null,order:3,visibility:'Partial'},returnTo:'/approvals?view=PendingMine'}));assert.match(trace,/pipeline-stages\/stage/);assert.match(trace,/returnTo=%2Fapprovals/);assert.doesNotMatch(trace,/pipelines\//);const data={items:[{id:'run',status:'Completed',currentStageOrder:2}],total:null,size:50,coverage:'Partial'},html=renderToStaticMarkup(createElement(PipelineRunList,{data}))+renderToStaticMarkup(createElement(PipelinePagination,{data,page:1,setPage(){},loading:false}));assert.match(html,/历史运行完成/);assert.match(html,/总数不可查看/);assert.doesNotMatch(html,/共 0 条|根制品/);}finally{await server.close();}});
