import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validatePipelineDefinition,pipelineAuthorityKey,reconcilePipelineDraft,pipelineCanManage} from '../src/delivery/pipeline-state.mjs';
import {deliveryPolicyLabel} from '../src/delivery/delivery-state.mjs';
const envs=[{id:'dev',projectId:'p',name:'DEV',active:true,isProduction:false},{id:'test',projectId:'p',name:'TEST',active:true,isProduction:false},{id:'prod',projectId:'p',name:'PROD',active:true,isProduction:true}];
const prod=['EntryConnectivity','AuthenticationAuthorization','CriticalBusinessCall'];
const stage=(id,order)=>({environmentId:id,order,requiredTestTypes:id==='prod'?[...prod]:['InterfaceFunction'],evidenceValidityMinutes:1440,waitTimeoutMinutes:1440,approvalFlowId:id==='prod'?'flow':null});
const definition=()=>({name:'标准交付',description:'',stages:[stage('dev',1),stage('prod',2)]});
test('valid definition follows actual production classification',()=>assert.deepEqual(validatePipelineDefinition(definition(),envs),[]));
test('production requirements cannot be removed',()=>{const d=definition();d.stages[1].requiredTestTypes=['EntryConnectivity'];assert.ok(validatePipelineDefinition(d,envs).length);});
test('environment chain requires 2 to 8 unique enabled same-project environments and production last',()=>{for(const stages of [[stage('dev',1)],Array.from({length:9},(_,i)=>stage('dev',i+1)),[stage('prod',1),stage('dev',2)],[stage('dev',1),stage('dev',2)]])assert.ok(validatePipelineDefinition({...definition(),stages},envs).length);for(const altered of [envs.map(e=>e.id==='prod'?{...e,active:false}:e),envs.map(e=>e.id==='prod'?{...e,projectId:'other'}:e)])assert.ok(validatePipelineDefinition(definition(),altered).length);});
test('independent stage bounds types approval and contiguous order are checked',()=>{for(const patch of [{waitTimeoutMinutes:0},{evidenceValidityMinutes:10081},{evidenceValidityMinutes:1.5},{order:5},{requiredTestTypes:[]},{requiredTestTypes:['Integration','Integration']},{approvalFlowId:'flow'}]){const d=definition();Object.assign(d.stages[0],patch);assert.ok(validatePipelineDefinition(d,envs).length,JSON.stringify(patch));}const d=definition();d.stages[1].approvalFlowId=null;assert.ok(validatePipelineDefinition(d,envs).length);});
test('authority binds actor scopes resource attempt profile and epoch',()=>{const actor={id:'u',permissions:['pipeline.read'],scopes:[]};const key=pipelineAuthorityKey(actor,'stage','a1','hash',1);for(const args of [[actor,'stage','a2','hash',1],[actor,'stage','a1','other',1],[actor,'stage','a1','hash',2],[{...actor,permissions:[]},'stage','a1','hash',1],[actor,'other','a1','hash',1]])assert.notEqual(key,pipelineAuthorityKey(...args));});
test('conflict preserves local draft but revocation clears private editor state',()=>{const draft=definition(),latest={revision:8};assert.deepEqual(reconcilePipelineDraft(draft,latest,412),{draft,latest,conflict:true});assert.deepEqual(reconcilePipelineDraft(draft,latest,403),{draft:undefined,latest:undefined,conflict:false});});
test('definition management needs both functional permissions and project write scope',()=>{const actor={permissions:['pipeline.manage','project.write'],scopes:[{scope:{organizationId:'o',projectId:'p'},accessMode:'read_write'}]};assert.equal(pipelineCanManage(actor,{organizationId:'o',projectId:'p'}),true);assert.equal(pipelineCanManage({...actor,permissions:['pipeline.read']},{organizationId:'o',projectId:'p'}),false);assert.equal(pipelineCanManage(actor,{organizationId:'o',projectId:'other'}),false);assert.equal(pipelineCanManage({...actor,scopes:[{scope:{organizationId:'o',projectId:'p'},accessMode:'read_only'}]},{organizationId:'o',projectId:'p'}),false);});
test('pipeline policy is distinct from legacy',()=>assert.match(deliveryPolicyLabel({mode:'PipelineRequired'}),/流水线/));

test('production checkboxes and immutable version controls are disabled in rendered editor',async()=>{
 const {createServer}=await import('vite'),{fileURLToPath}=await import('node:url'),{createElement}=await import('react'),{renderToStaticMarkup}=await import('react-dom/server');
 const server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,hmr:false,ws:false},appType:'custom'});
 try{const {PipelineDefinitionEditor}=await server.ssrLoadModule('/src/delivery/PipelineDefinitionEditor.tsx');const html=renderToStaticMarkup(createElement(PipelineDefinitionEditor,{value:definition(),environments:envs,readOnly:false,onChange(){}}));const prodSection=html.split('阶段 2')[1];assert.equal((prodSection.match(/type="checkbox" disabled=""/g)||[]).length,3);assert.match(html,/节点确认时限：120 秒/);assert.match(html,/阶段等待时限/);const frozen=renderToStaticMarkup(createElement(PipelineDefinitionEditor,{value:definition(),environments:envs,readOnly:true,onChange(){}}));assert.match(frozen,/<fieldset[^>]*disabled=""/);assert.doesNotMatch(frozen,/增加阶段|移除阶段/);}finally{await server.close();}
});
