import test from 'node:test';import assert from 'node:assert/strict';import {initialPolicyDraft,validatePolicyDraft,policyEditorReducer,refreshReview,copyDraft} from '../src/policies/policy-state.mjs';
test('AllFourDefaultsAndValidation',()=>{for(const type of ['authentication','timeout','rate_limit','circuit_breaker'])assert.equal(validatePolicyDraft({name:'策略',type,config:initialPolicyDraft(type)}),null);assert.equal(initialPolicyDraft('rate_limit').burst,1500);assert.ok(validatePolicyDraft({name:'策略',type:'rate_limit',config:{...initialPolicyDraft('rate_limit'),burst:1}}));assert.ok(validatePolicyDraft({name:'策略',type:'circuit_breaker',config:{...initialPolicyDraft('circuit_breaker'),failureRatio:0}}));});
test('ConflictRetainsDirtyInput',()=>{const before={scope:'a',draft:{name:'我的输入',config:{timeoutMs:200}},dirty:true};const after=policyEditorReducer(before,{type:'conflict'});assert.deepEqual(after.draft,before.draft);assert.equal(after.conflict,true);});
test('ScopeSwitchIgnoresLateResponse',()=>{const before={scope:'b',draft:{name:'新范围'}};assert.equal(policyEditorReducer(before,{type:'loaded',scope:'a',draft:{name:'旧响应'}}),before);});
test('CopyDoesNotReuseBindingOrEtag',()=>{const draft=copyDraft({id:'old',versionNo:3,etag:'3',bindings:[1],name:'源',type:'timeout',config:{timeoutMs:100}});assert.equal(draft.id,undefined);assert.equal(draft.etag,undefined);assert.equal(draft.bindings,undefined);assert.equal(draft.versionNo,undefined);});
test('LegacyDraftRefreshIsExplicit',()=>{const before={preconditionsCurrent:false,resourceRevisions:[{id:'old'}]};assert.equal(refreshReview(before,[{id:'new'}],false),before);assert.deepEqual(refreshReview(before,[{id:'new'}],true).resourceRevisions,[{id:'new'}]);});
test('DisabledTypesCannotSave',()=>{for(const type of ['retry','jwt','cache'])assert.ok(validatePolicyDraft({name:'策略',type,config:{}}));assert.ok(validatePolicyDraft({name:'RouteAuth-owned',type:'timeout',config:{timeoutMs:10}}));});
test('InvalidFieldsHaveSpecificFeedback',async()=>{const {policyFieldErrors}=await import('../src/policies/policy-state.mjs');assert.equal(typeof policyFieldErrors,'function');const rate=policyFieldErrors('rate_limit',{...initialPolicyDraft('rate_limit'),burst:1,windowMs:1});assert.ok(rate.burst);assert.ok(rate.windowMs);const circuit=policyFieldErrors('circuit_breaker',{...initialPolicyDraft('circuit_breaker'),failureStatusCodes:[200,200],failureRatio:2});assert.ok(circuit.failureStatusCodes);assert.ok(circuit.failureRatio);assert.deepEqual(policyFieldErrors('circuit_breaker',initialPolicyDraft('circuit_breaker')),{});});
test('UnselectedPolicyFiltersAreOmittedFromRequest',async()=>{const {policyListQuery}=await import('../src/policies/policy-state.mjs');assert.equal(typeof policyListQuery,'function');assert.equal(policyListQuery({type:'',search:'',enabled:''}).has('type'),false);assert.equal(policyListQuery({type:'rate_limit',search:'订单',enabled:'false'}).get('enabled'),'false');});

test('CircuitDefaultCountsEveryServerError',()=>assert.deepEqual(initialPolicyDraft('circuit_breaker').failureStatusCodes,Array.from({length:100},(_,i)=>500+i)));
