import test from 'node:test';import assert from 'node:assert/strict';
import {fetchLoginProviders,createSsoStartForm,completeSsoLogin,ssoErrorMessage,safeSsoReturnPath} from '../src/sso/login.mjs';
test('provider discovery is same origin and never automatically redirects',async()=>{const calls=[];globalThis.fetch=async(path,options)=>{calls.push({path,options});return new Response(JSON.stringify([{id:'a',name:'企业',isDefault:true}]),{status:200});};const rows=await fetchLoginProviders();assert.equal(rows[0].isDefault,true);assert.equal(calls.length,1);assert.equal(calls[0].path,'/api/v1/auth/sso/providers');assert.equal(calls[0].options.credentials,'same-origin');});
test('failed provider read exposes retry error independently of local login',async()=>{globalThis.fetch=async()=>new Response('{}',{status:503});await assert.rejects(fetchLoginProviders(),/企业登录/);});
test('start uses same origin native POST hidden CSRF and only controlled parameters',()=>{const document={createElement:tag=>({tag,children:[],appendChild(item){this.children.push(item);}})};const id='12345678-1234-1234-1234-123456789abc',form=createSsoStartForm(id,'/users','csrf',true,document);assert.equal(form.method,'post');assert.equal(form.action,'/api/v1/auth/sso/'+id+'/start');assert.deepEqual(form.children.map(x=>[x.name,x.value]),[['__RequestVerificationToken','csrf'],['returnPath','/users'],['reauthenticate','true']]);assert.equal(form.children.every(x=>x.type==='hidden'),true);assert.throws(()=>createSsoStartForm('//foreign','/users','csrf',false,document));});
test('completion restores identity then CSRF before navigation and does not navigate after failed restore',async()=>{const calls=[];await completeSsoLogin({refresh:async()=>calls.push('me'),csrf:async()=>calls.push('csrf'),navigate:()=>calls.push('navigate'),returnPath:'/users'});assert.deepEqual(calls,['me','csrf','navigate']);calls.length=0;await assert.rejects(completeSsoLogin({refresh:async()=>{throw Error('failed');},csrf:async()=>calls.push('csrf'),navigate:()=>calls.push('navigate'),returnPath:'/users'}));assert.deepEqual(calls,[]);});
test('error and return path accept only approved values',()=>{assert.equal(ssoErrorMessage('?ssoError=cancelled&traceId=%3Cscript%3E').includes('<script>'),false);assert.equal(ssoErrorMessage('?ssoError=untrusted'),null);for(const p of ['https://foreign','//foreign','/api/v1/users','/auth/sso/complete','/users%2f%2fother','/users\\evil'])assert.equal(safeSsoReturnPath(p),'/organizations');assert.equal(safeSsoReturnPath('/users'),'/users');});

test('loginPreservesNotificationAndEventDeepLinksWithoutAuthControlQuery',async()=>{const {loginReturnPath}=await import('../src/sso/login.mjs');assert.equal(loginReturnPath('/settings/system','?tab=notification'),'/settings/system?tab=notification');const eventId='12345678-1234-1234-1234-123456789abc';assert.equal(loginReturnPath('/observability/alerts','?eventId='+eventId),'/observability/alerts?eventId='+eventId);assert.equal(loginReturnPath('/settings/system','?tab=notification&ssoError=cancelled&traceId=unit'),'/settings/system?tab=notification');assert.equal(loginReturnPath('/users','?returnPath=%2Fapprovals%3FstepOrder%3D2'),'/approvals?stepOrder=2');assert.equal(loginReturnPath('/users','?returnPath=https%3A%2F%2Fforeign'),'/organizations');});
