import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {buildRelease} from '../runtime/build.mjs';import {safeFile,ownedDirectory} from '../runtime/state.mjs';import {createComparisonWorkspace,validateComparisonDirectory,validateComparisonResources,validateComparisonCleanupResources,validateComparisonArchive,finalizeComparisonEvidence,secretNames,sha,assertNoSecrets,toolManifest,verifyToolManifest,verifyComparisonUiProof} from './evidence.mjs';import {runComparisonScenario} from './scenario.mjs';
const exec=promisify(execFile),repository=path.resolve(import.meta.dirname,'../..');
const applicationNames={'control-plane':'ControlPlane',worker:'Worker','gateway-a':'Gateway','gateway-b':'Gateway','backend-a':'TestBackend','backend-b':'TestBackend',console:'ConsoleHost'};
function composeArguments(directory,project){return['compose','-p',project,'-f',path.join(directory,'source/deploy/compose.e2e.yml'),'-f',path.join(directory,'overlay.json'),'-f',path.join(directory,'volumes.yml')];}
async function runnerCommand(directory,env,binary,args,options={}){try{const r=await exec(binary,args,{cwd:directory,env,maxBuffer:32*1024*1024,...options});if(r.stdout||r.stderr)await fs.appendFile(path.join(directory,'operations.log'),r.stdout+r.stderr,{mode:0o600});return r.stdout.trim();}catch(e){await fs.appendFile(path.join(directory,'operations.log'),(e.stdout||'')+(e.stderr||''),{mode:0o600});throw Error('Isolated comparison command failed; see private operations.log');}}
async function guardedCleanup(context){
 const{directory,project,owner,environment}=context;validateComparisonDirectory(directory,{project,owner});await ownedDirectory(directory);await safeFile(path.join(directory,'owner.json'));const identity=JSON.parse(await fs.readFile(path.join(directory,'owner.json'),'utf8'));assert.deepEqual(identity,{project,owner});assert.equal(environment.WEBAPI_E2E_PROJECT,project);assert.equal(environment.WEBAPI_E2E_DIRECTORY,directory);
 const command=(...args)=>runnerCommand(directory,{...process.env,...environment},'docker',args);const resources=[];for(const kind of ['container','volume','network']){const args=kind==='container'?['ps','-aq']:[kind,'ls','-q'];const ids=(await command(...args,'--filter','label=com.docker.compose.project='+project)).split('\n').filter(Boolean);for(const id of ids){const labels=JSON.parse(await command(...(kind==='container'?['inspect','--format','{{json .Config.Labels}}',id]:[kind,'inspect','--format','{{json .Labels}}',id])));resources.push({kind,labels});if(kind==='volume')assert(['pg','nuget','lkg-a','lkg-b'].some(name=>id===project+'_'+name),'Unexpected volume');}}
 validateComparisonCleanupResources({project,owner},resources);
 await command(...composeArguments(directory,project),'down','--volumes','--remove-orphans');const containersRemaining=(await command('ps','-aq','--filter','label=com.docker.compose.project='+project)).split('\n').filter(Boolean).length,volumesRemaining=(await command('volume','ls','-q','--filter','label=com.docker.compose.project='+project)).split('\n').filter(Boolean).length;assert.equal(containersRemaining,0);assert.equal(volumesRemaining,0);const networksRemaining=(await command('network','ls','-q','--filter','label=com.docker.compose.project='+project)).split('\n').filter(Boolean).length;assert.equal(networksRemaining,0);
 for(const name of [...secretNames,'credential','context.json','review-context.json'])await fs.rm(path.join(directory,name),{force:true});const secretsRemaining=(await fs.readdir(directory)).filter(name=>[...secretNames,'credential','context.json','review-context.json'].includes(name)).length;return{containersRemaining,volumesRemaining,networksRemaining,secretsRemaining};
}
export async function cleanupComparisonAcceptance({root=repository,directory}){
 await ownedDirectory(directory);const contextFile=path.join(directory,'review-context.json');await safeFile(contextFile);const context=JSON.parse(await fs.readFile(contextFile,'utf8'));assert.equal(context.directory,path.resolve(directory));assert.equal(path.dirname(context.directory),path.join(path.resolve(root),'.runtime'));validateComparisonDirectory(directory,context);
 await verifyToolManifest(root,context.tools);const proof=JSON.parse(await fs.readFile(path.join(directory,'result.json'),'utf8'));let suppliedUi;try{await safeFile(path.join(directory,'ui-proof.json'));suppliedUi=JSON.parse(await fs.readFile(path.join(directory,'ui-proof.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
 if(suppliedUi)proof.ui=await verifyComparisonUiProof(root,suppliedUi);
 proof.cleanup=await guardedCleanup(context);const finalized=finalizeComparisonEvidence(proof);const publicDirectory=path.join(root,'docs/evidence/version-comparison');await fs.writeFile(path.join(publicDirectory,'verification.json'),JSON.stringify(finalized,null,2)+'\n');return finalized;
}
export async function runComparisonAcceptance({root=repository,revision,retainForReview=false}){
 root=path.resolve(root);assert(revision&&!revision.startsWith('-'),'Explicit immutable revision required');const sourceRevision=(await exec('git',['rev-parse',revision+'^{commit}'],{cwd:root})).stdout.trim();assert.match(sourceRevision,/^[a-f0-9]{40}$/);const entries=(await exec('git',['ls-tree','-r','--name-only',sourceRevision],{cwd:root})).stdout.trim().split('\n');validateComparisonArchive(entries);
 const {owner,project,directory}=await createComparisonWorkspace(root),publicDirectory=path.join(root,'docs/evidence/version-comparison');await fs.mkdir(publicDirectory,{recursive:true});const environment={WEBAPI_E2E_PROJECT:project,WEBAPI_E2E_DIRECTORY:directory,WEBAPI_E2E_RELATIVE_DIR:'.runtime/'+project,WEBAPI_ENVIRONMENT_ID:randomUUID()},env={...process.env,...environment};const command=(binary,args,options)=>runnerCommand(directory,env,binary,args,options);let context,started=false;
 try{
  const archive=path.join(directory,'source.tar'),source=path.join(directory,'source');await fs.mkdir(source,{mode:0o700});await command('git',['-C',root,'archive','--output',archive,sourceRevision]);const archiveHash=sha(await fs.readFile(archive));await command('tar',['-xf',archive,'-C',source]);const tools=await toolManifest(source);assert.deepEqual(await toolManifest(root),tools,'Runner tools differ from immutable source');const image=await buildRelease({root,revision:sourceRevision,directory:path.join(directory,'build'),nugetSeedVolume:'webapi-enterprise-core-test_nuget-test'});await fs.writeFile(path.join(publicDirectory,'source-manifest.json'),JSON.stringify({sourceRevision,archiveHash,image,toolManifestHash:tools.sha256},null,2)+'\n');
  const labels={'com.webapi.comparisons.owner':owner},overlay={services:{},volumes:{},networks:{default:{labels}},secrets:{password:{file:path.join(directory,'password')}}};for(const service of ['postgres','redis','sdk',...Object.keys(applicationNames)])overlay.services[service]={labels};for(const name of ['pg','nuget','lkg-a','lkg-b'])overlay.volumes[name]={labels};
  for(const[service,name]of Object.entries(applicationNames)){Object.assign(overlay.services[service],{image:image.imageId,user:'10001:10001',working_dir:'/app',command:['dotnet',`/app/${service.startsWith('gateway')?'gateway':service.startsWith('backend')?'demo-backend':service==='console'?'console-host':service}/WebApi.${name}.dll`]});if(['control-plane','gateway-a','gateway-b','console'].includes(service))overlay.services[service].ports=['127.0.0.1::8080'];}
  Object.assign(overlay.services['control-plane'],{secrets:['postgres-password','node-a','node-b','password'],environment:{WEBAPI_BOOTSTRAP_USERNAME:'e2e-admin',WEBAPI_BOOTSTRAP_PASSWORD_FILE:'/run/secrets/password',Authentication__CookieName:'WebApi.Comparisons.'+owner+'.Session',Antiforgery__CookieName:'WebApi.Comparisons.'+owner+'.Csrf'}});overlay.services.console.environment={Console__DistDirectory:'/app/console-dist'};
  await fs.writeFile(path.join(directory,'overlay.json'),JSON.stringify(overlay,null,2),{mode:0o600});const override='services:\n'+Object.keys(applicationNames).map(s=>`  ${s}:\n    volumes: !override ${s.startsWith('gateway')?'[lkg-'+s.at(-1)+':/lkg]':'[]'}\n`+(['control-plane','gateway-a','gateway-b','console'].includes(s)?'    ports: !override ["127.0.0.1::8080"]\n':'')).join('')+'  sdk:\n    volumes: !override []\n';await fs.writeFile(path.join(directory,'volumes.yml'),override,{mode:0o600});const args=composeArguments(directory,project),compose=(...parts)=>command('docker',[...args,...parts]);context={directory,owner,project,environment,tools,image};
  started=true;await compose('up','-d','--wait','postgres','redis');await compose('run','--rm','--entrypoint','dotnet','control-plane','/app/migrator/WebApi.Migrator.dll','--bootstrap','--seed-catalog');await compose('up','-d','control-plane');const endpoint=async service=>'http://'+await compose('port',service,'8080');env.WEBAPI_E2E_CONTROL_PLANE_URL=await endpoint('control-plane');await command(process.execPath,[path.join(source,'scripts/wait-http.mjs'),env.WEBAPI_E2E_CONTROL_PLANE_URL+'/health/live']);await command(process.execPath,[path.join(source,'scripts/prepare-e2e.mjs')]);const fixture=JSON.parse(await fs.readFile(path.join(directory,'context.json'),'utf8'));env.WEBAPI_ENVIRONMENT_ID=environment.WEBAPI_ENVIRONMENT_ID=fixture.environmentId;await compose('up','-d','--force-recreate','control-plane');env.WEBAPI_E2E_CONTROL_PLANE_URL=await endpoint('control-plane');await compose('create','gateway-a','gateway-b');const sdk=JSON.parse(await fs.readFile(path.join(source,'deploy/images.lock.json'))).sdk;for(const name of ['lkg-a','lkg-b']){const volume=project+'_'+name;validateComparisonResources({project,owner},[JSON.parse(await command('docker',['volume','inspect','--format','{{json .Labels}}',volume]))]);await command('docker',['run','--rm','--user','0:0','-v',volume+':/comparison-lkg',sdk,'bash','-c','chown 10001:10001 /comparison-lkg && chmod 700 /comparison-lkg']);}await compose('up','-d',...Object.keys(applicationNames));await command(process.execPath,[path.join(source,'scripts/wait-http.mjs'),env.WEBAPI_E2E_CONTROL_PLANE_URL+'/health/live']);await command(process.execPath,[path.join(source,'scripts/wait-nodes.mjs')]);const endpoints={control_plane:env.WEBAPI_E2E_CONTROL_PLANE_URL,console:await endpoint('console'),gateway_a:await endpoint('gateway-a'),gateway_b:await endpoint('gateway-b')};context={...context,endpoints,context:fixture};await fs.writeFile(path.join(directory,'review-context.json'),JSON.stringify(context,null,2),{mode:0o600});const result=await runComparisonScenario({...context,compose});result.toolManifestHash=tools.sha256;await verifyToolManifest(root,tools);assertNoSecrets(result,await Promise.all([...secretNames,'credential'].map(n=>fs.readFile(path.join(directory,n),'utf8'))));await fs.writeFile(path.join(directory,'result.json'),JSON.stringify(result,null,2),{mode:0o600});
  if(!retainForReview)result.cleanup=await guardedCleanup(context);const finalized=finalizeComparisonEvidence(result);await fs.writeFile(path.join(publicDirectory,'verification.json'),JSON.stringify(finalized,null,2)+'\n');console.log(retainForReview?'Comparison review: '+endpoints.console:'Comparison API scenario verified; UI proof pending');return{sourceRevision,image,resultPath:path.join(publicDirectory,'verification.json'),reviewContextPath:retainForReview?path.join(directory,'review-context.json'):null};
 }catch(e){let cleanup;try{if(started)cleanup=await guardedCleanup(context);}catch(error){cleanup={failed:true,reason:error.message};}if(!started)for(const name of secretNames)await fs.rm(path.join(directory,name),{force:true});await fs.writeFile(path.join(publicDirectory,'last-failure.json'),JSON.stringify({complete:false,sourceRevision,project,message:e.message,cleanup},null,2)+'\n');throw e;}
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(import.meta.filename)){const args=process.argv.slice(2),value=flag=>args[args.indexOf(flag)+1];if(args.includes('--cleanup'))console.log(JSON.stringify(await cleanupComparisonAcceptance({directory:path.resolve(value('--cleanup'))})));else if(args.includes('--revision'))console.log(JSON.stringify(await runComparisonAcceptance({revision:value('--revision'),retainForReview:args.includes('--review')})));else throw Error('Use --revision <commit> --review or --cleanup <owned-private-directory>');}
