import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs/promises';import {randomUUID,randomBytes} from 'node:crypto';
import {sha} from '../settings/evidence.mjs';
export {sha,assertNoSecrets,toolManifest,verifyToolManifest} from '../settings/evidence.mjs';
export const secretNames=['password','postgres-password','node-a','node-b'];
export const requiredUiActions=['version-selection','generate','risk-filter','fragment-details','json-export','csv-export','strong-confirmation','review-record','wizard-handoff','release-summary','keyboard-focus','workspace-switch'];
export const requiredScreenshots=['comparison','unknown','strong-confirmation','review-record','wizard-handoff','release-summary'];
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export function validateComparisonResources(context,labels){assert.match(context.owner,uuid);assert.equal(context.project,'webapi-enterprise-e2e-comparisons-'+context.owner);for(const label of labels){assert.equal(label['com.docker.compose.project'],context.project);assert.equal(label['com.webapi.comparisons.owner'],context.owner);}return true;}
export function validateComparisonCleanupResources(context,resources){for(const resource of resources){assert(['container','volume','network'].includes(resource.kind));validateComparisonResources(context,[resource.labels]);}return true;}
export function validateComparisonDirectory(directory,context){validateComparisonResources(context,[]);assert.equal(path.basename(path.resolve(directory)),context.project);assert.equal(path.basename(path.dirname(path.resolve(directory))),'.runtime');return true;}
export async function createComparisonWorkspace(root){const owner=randomUUID(),project='webapi-enterprise-e2e-comparisons-'+owner,directory=path.join(root,'.runtime',project);await fs.mkdir(path.dirname(directory),{recursive:true});assert.equal(await fs.realpath(path.dirname(directory)),path.dirname(directory),'Runtime parent cannot be a symlink');await fs.mkdir(directory,{mode:0o700});for(const name of secretNames)await fs.writeFile(path.join(directory,name),randomBytes(32).toString('base64url'),{mode:0o600,flag:'wx'});await fs.writeFile(path.join(directory,'owner.json'),JSON.stringify({owner,project}),{mode:0o600,flag:'wx'});return{owner,project,directory};}
export function validateComparisonArchive(entries){for(const name of entries){assert(!path.isAbsolute(name)&&!name.split('/').includes('..'),'Archive path escapes');assert(!/(^|\/)(node_modules|\.runtime|\.secrets|\.git)(\/|$)/.test(name),'Private or dependency archive entry');assert(!/(^|\/)(private-input\.json|review-context\.json|context\.json|inputBytes\.bin|password|credential)$/.test(name),'Private evidence entry');}return true;}
export async function verifyComparisonUiProof(root,proof){for(const screenshot of proof.screenshots||[]){assert(requiredScreenshots.includes(screenshot.name),'Unexpected screenshot');const file=path.resolve(root,'docs/evidence/version-comparison',screenshot.name+'.png');const bytes=await fs.readFile(file);assert.equal(sha(bytes),screenshot.sha256);assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(bytes.readUInt32BE(16),screenshot.width);assert.equal(bytes.readUInt32BE(20),screenshot.height);}return proof;}
export function finalizeComparisonEvidence(proof){try{assert.match(proof.sourceRevision,/^[a-f0-9]{40}$/);assert.equal(proof.image.sourceRevision,proof.sourceRevision);assert.match(proof.image.imageId,/^sha256:[a-f0-9]{64}$/);assert.match(proof.toolManifestHash,/^[a-f0-9]{64}$/);for(const key of ['api','permissions','publish'])assert.equal(proof[key]?.passed,true,'Missing actual '+key+' proof');assert.equal(proof.publish.targets?.length,2);assert(proof.publish.targets.every(t=>t.acknowledged===true));assert.equal(proof.ui?.verified,true,'Missing actual UI proof');assert.equal(proof.ui.horizontalOverflow,false);for(const name of requiredUiActions)assert(proof.ui.actions?.some(a=>a.name===name&&a.passed===true),'Missing UI action '+name);for(const name of requiredScreenshots)assert(proof.ui.screenshots?.some(s=>s.name===name&&/^[a-f0-9]{64}$/.test(s.sha256)&&s.width===1440&&s.height===1024),'Missing screenshot '+name);for(const key of ['containersRemaining','volumesRemaining','networksRemaining','secretsRemaining'])assert.equal(proof.cleanup?.[key],0,'Cleanup incomplete');return{...proof,complete:true};}catch(e){return{...proof,complete:false,incompleteReason:e.message};}}
