import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {LocalClient} from '../local-client.mjs';import {assertNoSecrets} from './evidence.mjs';
const wait=async(action,predicate)=>{const end=Date.now()+90000;while(Date.now()<end){const value=await action();if(predicate(value))return value;await new Promise(r=>setTimeout(r,400));}throw Error('Comparison scenario did not converge');};
export async function runComparisonScenario(c){
 const {context:s,endpoints:e,directory}=c,password=await fs.readFile(path.join(directory,'password'),'utf8'),clients={};for(const name of ['e2e-admin','e2e-approver','e2e-security']){clients[name]=new LocalClient(e.control_plane);await clients[name].login(name,password);}const admin=clients['e2e-admin'],checks=[];const record=(name,evidence)=>checks.push({name,passed:true,evidence});
 const role=await admin.request('/roles',{method:'POST',body:{code:'ComparisonReviewer',name:'隔离契约评审人',organizationId:s.organizationId}});const reviewedRole=await admin.request(`/roles/${role.id}/permissions`,{method:'PUT',body:{permissions:['api.read','api.version.read','api.schema.read','api.approve']},headers:{'If-Match':`"${role.revision}"`}});let user=await admin.request('/users',{method:'POST',body:{username:'e2e-risk',displayName:'隔离风险评审人',password}});user=await admin.request(`/users/${user.id}/roles`,{method:'PUT',body:{roleIds:[reviewedRole.id]},headers:{'If-Match':`"${user.revision}"`}});await admin.request(`/users/${user.id}/scopes`,{method:'PUT',body:{scopes:[{scope:{organizationId:s.organizationId,projectId:s.projectId},accessMode:'read_write'}]},headers:{'If-Match':`"${user.revision}"`}});const risk=new LocalClient(e.control_plane);await risk.login('e2e-risk',password);
 const document=required=>JSON.stringify({openapi:'3.0.3',paths:{'/orders':{get:{parameters:[{name:'name',in:'query',required,schema:{type:'string'}}],responses:{'200':{description:'OK'}}}}}}),from=await admin.request(`/apis/${s.apiId}/versions`,{method:'POST',body:{version:'1.0.0',changeType:'compatible',openapiDocument:document(false),sourceFormat:'json'}}),to=await admin.request(`/apis/${s.apiId}/versions`,{method:'POST',body:{version:'2.0.0',changeType:'compatible',openapiDocument:document(true),sourceFormat:'json'}});
 const compareBody={fromVersionId:from.id,toVersionId:to.id,expectedFromRevision:from.revision,expectedToRevision:to.revision},key=randomUUID(),comparison=await risk.request(`/apis/${s.apiId}/version-comparisons`,{method:'POST',body:compareBody,key});assert.equal(comparison.report.coverage,'Complete');assert(comparison.report.counts.breaking>0);assert.deepEqual(await risk.request(`/apis/${s.apiId}/version-comparisons`,{method:'POST',body:compareBody,key}),comparison);await assert.rejects(risk.request(`/version-comparisons/${comparison.id}/reviews`,{method:'POST',body:{expectedReportHash:comparison.reportHash,decision:'AcceptedRisk',comment:'不足十字',confirmRisk:true}}),e=>e.status===422);const review=await risk.request(`/version-comparisons/${comparison.id}/reviews`,{method:'POST',body:{expectedReportHash:comparison.reportHash,decision:'AcceptedRisk',comment:'已检查客户端迁移影响并确认接受风险',confirmRisk:true}});assert.equal(review.actorId,user.id);record('real-comparison-and-strong-review',{comparisonId:comparison.id,reviewId:review.id,counts:comparison.report.counts,coverage:comparison.report.coverage});
 const history=await risk.request(`/apis/${s.apiId}/version-comparisons?reviewId=${review.id}`);assert.equal(history.items[0].id,comparison.id);assert.equal((await risk.request(`/version-comparisons/${comparison.id}`)).to.id,to.id);record('server-target-handoff',{targetVersionId:to.id,reviewId:review.id});
 const roleBefore=(await admin.request('/roles')).find(r=>r.id===role.id);await admin.request(`/roles/${role.id}/permissions`,{method:'PUT',body:{permissions:roleBefore.permissions.filter(p=>p!=='api.approve')},headers:{'If-Match':`"${roleBefore.revision}"`}});await assert.rejects(risk.request(`/version-comparisons/${comparison.id}/reviews`,{method:'POST',body:{expectedReportHash:comparison.reportHash,decision:'AcceptedRisk',comment:'已检查客户端迁移影响并确认接受风险',confirmRisk:true}}),e=>e.status===403);const after=(await admin.request('/roles')).find(r=>r.id===role.id);await admin.request(`/roles/${role.id}/permissions`,{method:'PUT',body:{permissions:roleBefore.permissions},headers:{'If-Match':`"${after.revision}"`}});record('review-revocation-denies-protected-write',{deniedStatus:403});
 await admin.request(`/environments/${s.environmentId}/routes`,{method:'POST',body:{apiVersionId:to.id,routeName:'ComparisonOrders',path:'/orders',methods:['GET'],clusterId:s.clusterId,priority:100,enabled:true,requireApiKey:false,timeoutMs:30000}});
 async function publish(versionId,riskReviewIds){const env=await admin.request('/environments/'+s.environmentId),selection={baseConfigVersion:env.desiredConfigVersion||0,versionIds:[versionId]},preview=await admin.request(`/environments/${s.environmentId}/releases/preview`,{method:'POST',body:selection}),draft=await admin.request(`/environments/${s.environmentId}/releases`,{method:'POST',body:{...selection,resourceRevisions:preview.resourceRevisions,...(riskReviewIds?{riskReviewIds}:{})}});const submitted=await admin.request('/releases/'+draft.id+'/submit',{method:'POST'});assert.equal(submitted.state,'WaitingApproval');await assert.rejects(admin.request('/releases/'+draft.id+'/approve',{method:'POST',body:{comment:'self'}}),e=>e.status===403);await clients['e2e-approver'].request('/releases/'+draft.id+'/approve',{method:'POST',body:{comment:'独立 API 正式审批'}});await clients['e2e-security'].request('/releases/'+draft.id+'/approve',{method:'POST',body:{comment:'独立安全正式审批'}});await admin.request('/releases/'+draft.id+'/publish',{method:'POST'});return wait(()=>admin.request('/releases/'+draft.id),r=>{if(r.state==='Failed')throw Error('Release failed: '+r.errors.join(','));return r.state==='Succeeded'&&r.targets.length===2&&r.targets.every(t=>t.acknowledged);});}
 const release=await publish(to.id,[review.id]);assert.equal(release.frozenCandidate.riskReviews[0].reviewId,review.id);assert.equal((await risk.request(`/version-comparisons/${comparison.id}`)).freshness,'Current');record('independent-approval-and-dual-gateway-ack',{releaseId:release.id,targets:release.targets,configVersion:release.targetConfigVersion,deploymentSequence:release.deploymentSequence});
 const legacy=await admin.request(`/apis/${s.apiId}/versions`,{method:'POST',body:{version:'3.0.0'}});await admin.request(`/environments/${s.environmentId}/routes`,{method:'POST',body:{apiVersionId:legacy.id,routeName:'LegacyOrders',path:'/legacy-orders',methods:['GET'],clusterId:s.clusterId,priority:100,enabled:true,requireApiKey:false,timeoutMs:30000}});const oldClient=await publish(legacy.id);assert.equal(oldClient.frozenCandidate.riskReviews?.length||0,0);record('legacy-no-reference-publish',{releaseId:oldClient.id,targets:oldClient.targets});
 const result={schemaVersion:1,complete:false,sourceRevision:c.image.sourceRevision,image:c.image,api:{passed:true},permissions:{passed:true},publish:{passed:true,targets:release.targets},checks,ui:{verified:false},scope:{organizationId:s.organizationId,projectId:s.projectId,environmentId:s.environmentId},apiId:s.apiId,comparisonId:comparison.id,reviewId:review.id,releaseId:release.id,targetVersionId:to.id,time:new Date().toISOString()};assertNoSecrets(result,[password]);return result;
}
