import fs from 'node:fs/promises';
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import net from 'node:net';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {loadState,writePrivate} from '../runtime/state.mjs';
import {loadRelease} from '../runtime/lifecycle.mjs';
import {prepareContext} from '../runtime/context.mjs';
import {inspectResources,docker} from '../runtime/docker.mjs';
import {validateCloneOwnership,assertReleaseIdentity} from './evidence.mjs';
import {until} from '../runtime/acceptance-scenario.mjs';
const hash=text=>createHash('sha256').update(text).digest('hex');
// Unlike the maintenance client, retain structured problem codes for actual rejection assertions.
export class ContractClient {
 constructor(base){this.base=base;this.cookies=new Map();}
 async request(route,options={}){
  const headers={'Content-Type':'application/json',Origin:this.base,...options.headers};
  if(options.method&&options.method!=='GET'){headers['X-CSRF-Token']=(await this.request('/auth/csrf')).token;headers['Idempotency-Key']=options.key??randomUUID();}
  headers.Cookie=[...this.cookies].map(([key,value])=>key+'='+value).join('; ');
  const response=await fetch(this.base+'/api/v1'+route,{...options,headers,body:options.body===undefined?undefined:JSON.stringify(options.body),signal:options.signal??AbortSignal.timeout(30000)});
  for(const cookie of response.headers.getSetCookie()){const first=cookie.split(';')[0],at=first.indexOf('=');this.cookies.set(first.slice(0,at),first.slice(at+1));}
  const value=response.status===204?null:await response.json();
  if(!response.ok)throw Object.assign(new Error('HTTP '+response.status+' '+(value.code??'')),{status:response.status,code:value.code,issues:value.issues,traceId:value.traceId});return value;
 }
 login(username,password){return this.request('/auth/login',{method:'POST',body:{username,password}});}
}
export async function contractFixture(tag){
 let marker='preview-original';const requests=[],sockets=new Set(),route='/contracts-'+tag;
 const schemas='$defs:\n  Order:\n    type: object\n    required: [id, label]\n    properties:\n      id: {type: integer}\n      label: {type: string}\n    additionalProperties: false\n';
 const yaml=()=>`openapi: 3.1.0\ninfo:\n  title: Contract acceptance\n  version: '${marker}'\npaths:\n  ${route}:\n    get:\n      operationId: contractRead\n      summary: 契约验收接口\n      parameters:\n        - name: query\n          in: query\n          required: false\n          schema: {type: string}\n          examples:\n            empty: {value: ''}\n      responses:\n        '200':\n          description: OK\n          content:\n            application/json:\n              schema: {$ref: 'schemas.yaml#/$defs/Order'}\n              examples:\n                valid: {value: {id: 1, label: sample}}\n                false: {value: false}\n                zero: {value: 0}\n                empty: {value: ''}\n                nil: {value: null}\n                remote: {externalValue: 'https://example.invalid/unverified.json'}\n`;
 const json=()=>JSON.stringify({openapi:'3.1.0',info:{title:'Contract acceptance',version:marker},paths:{[route]:{get:{operationId:'contractRead',summary:'契约验收接口',parameters:[{name:'query',in:'query',required:false,schema:{type:'string'},examples:{empty:{value:''}}}],responses:{'200':{description:'OK',content:{'application/json':{schema:{$ref:'schemas.yaml#/$defs/Order'},examples:{valid:{value:{id:1,label:'sample'}},false:{value:false},zero:{value:0},empty:{value:''},nil:{value:null},remote:{externalValue:'https://example.invalid/unverified.json'}}}}}}}}}});
 const server=http.createServer(async(request,response)=>{requests.push({path:request.url,method:request.method,time:new Date().toISOString()});response.setHeader('Connection','close');if(request.url==='/contracts/redirect.yaml'){response.writeHead(302,{Location:'/contracts/openapi.yaml'});response.end();return;}if(request.url==='/contracts/slow.yaml'){await new Promise(resolve=>setTimeout(resolve,20000));if(response.destroyed)return;}if(request.url==='/contracts/oversized.yaml'){response.writeHead(200,{'Content-Type':'application/yaml'});response.end('x'.repeat(2*1024*1024+1));return;}if(!['/contracts/openapi.yaml','/contracts/schemas.yaml','/contracts/slow.yaml'].includes(request.url)){response.writeHead(404);response.end();return;}response.writeHead(200,{'Content-Type':'application/yaml'});response.end(request.url.endsWith('schemas.yaml')?schemas:yaml());});
 server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
 return {port:server.address().port,route,schemas,yaml,json,requests,change:()=>{marker='changed-after-preview';},close:async()=>{for(const socket of sockets)socket.destroy();await new Promise(resolve=>server.close(resolve));}};
}
async function isolateFixture(fixture,{state,release,privateDirectory}){
 const directory=path.join(privateDirectory,'http-fixture-'+randomUUID()),source=path.join(directory,'source'),output=path.join(directory,'output'),data=path.join(directory,'data');await fs.mkdir(source,{recursive:true,mode:0o700});await fs.mkdir(output,{mode:0o700});await fs.mkdir(data,{mode:0o700});await fs.writeFile(path.join(data,'openapi.yaml'),fixture.yaml());await fs.writeFile(path.join(data,'schemas.yaml'),fixture.schemas);await fs.writeFile(path.join(data,'requests.log'),'');
 await fs.writeFile(path.join(source,'Fixture.csproj'),'<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup></Project>');
 await fs.writeFile(path.join(source,'Program.cs'),`var b=WebApplication.CreateBuilder(args);b.WebHost.UseUrls("http://0.0.0.0:18080");var app=b.Build();app.MapGet("/{**path}",async(HttpContext context)=>{var path=context.Request.Path.Value!;await File.AppendAllTextAsync("/data/requests.log",path+"\\n");if(path=="/contracts/redirect.yaml"){context.Response.StatusCode=302;context.Response.Headers.Location="/contracts/openapi.yaml";return;}if(path=="/contracts/oversized.yaml"){await context.Response.WriteAsync(new string('x',2*1024*1024+1));return;}if(path=="/contracts/slow.yaml")await Task.Delay(20000,context.RequestAborted);var file=path switch {"/contracts/openapi.yaml" or "/contracts/slow.yaml"=>"openapi.yaml","/contracts/schemas.yaml"=>"schemas.yaml",_=>null};if(file is null){context.Response.StatusCode=404;return;}context.Response.ContentType="application/yaml";await context.Response.WriteAsync(await File.ReadAllTextAsync("/data/"+file));});await app.RunAsync();`);
 // Compilation has no package dependencies and occurs only inside a temporary owned SDK container.
 const labels=['--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId];await docker(['run','--rm',...labels,'--mount','type=bind,src='+source+',dst=/source','--mount','type=bind,src='+output+',dst=/output','--workdir','/source',release.dependencyImages.sdk,'dotnet','publish','Fixture.csproj','-o','/output','--ignore-failed-sources','--source','/source','--nologo']);
 const name=state.projectName+'-contract-fixture';const exists=await docker(['container','inspect',name],{allowFailure:true});assert.notEqual(exists.exitCode,0,'测试源名称已存在，拒绝采用。');
 const id=(await docker(['run','-d','--name',name,...labels,'--network',state.projectName+'_default','--network-alias','contract-fixture','--read-only','--tmpfs','/tmp:rw,size=64m','--mount','type=bind,src='+output+',dst=/fixture,readonly','--mount','type=bind,src='+data+',dst=/data',release.dependencyImages.sdk,'dotnet','/fixture/Fixture.dll'])).stdout.trim();
 const resource=JSON.parse((await docker(['container','inspect',id])).stdout)[0];validateCloneOwnership(state,[resource],path.join(privateDirectory,state.projectName));const addresses=Object.values(resource.NetworkSettings.Networks).flatMap(network=>[network.IPAddress,network.GlobalIPv6Address]).filter(value=>net.isIP(value));assert(addresses.length>0);
 const originalChange=fixture.change;fixture.change=()=>{originalChange();writeFileSync(path.join(data,'openapi.yaml'),fixture.yaml());};Object.defineProperty(fixture,'requests',{get:()=>readFileSync(path.join(data,'requests.log'),'utf8').trim().split('\n').filter(Boolean).map(value=>({path:value}))});
 const originalClose=fixture.close;fixture.close=async()=>{const current=JSON.parse((await docker(['container','inspect',id])).stdout)[0];validateCloneOwnership(state,[current],path.join(privateDirectory,state.projectName));await docker(['container','rm','-f',id]);await originalClose();};
 return {origin:'http://contract-fixture:18080',cidrs:addresses.map(address=>address+'/'+(net.isIP(address)===4?'32':'128'))};
}
export async function prepareContractScenario({directory,revision,privateDirectory}){
 const state=await loadState(directory),release=await loadRelease(path.join(directory,'release.json')),resources=await inspectResources(state);validateCloneOwnership(state,resources,directory);
 const apps=resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b'].includes(r.Config?.Labels?.['com.docker.compose.service']));assert.equal(apps.length,5);const actualImages=[];
 for(const app of apps){const image=JSON.parse((await docker(['image','inspect',app.Image])).stdout)[0];actualImages.push({imageId:image.Id,sourceRevision:image.Config.Labels['org.opencontainers.image.revision']});}assertReleaseIdentity({revision,release,actualImages});
 const tag=randomUUID().slice(0,8),fixture=await contractFixture(tag);let origin;
 try {
  const isolated=await isolateFixture(fixture,{state,release,privateDirectory}),cidrs=isolated.cidrs;origin=isolated.origin;
  const ctx=await prepareContext(directory,state,release),configFile=path.join(directory,'runtime-config.json'),config=JSON.parse(await fs.readFile(configFile,'utf8')),env=config.services['control-plane'].environment;
  for(const key of Object.keys(env))if(key.startsWith('ContractImport__AllowedPrivateCidrs__')||key.startsWith('ContractImport__FixtureOrigins__'))delete env[key];env.ContractImport__AllowHttp='true';env.ContractImport__FixtureEnabled='true';env.ContractImport__FixtureOrigins__0=origin;cidrs.forEach((cidr,index)=>env['ContractImport__AllowedPrivateCidrs__'+index]=cidr);await writePrivate(configFile,config);await ctx.compose('up','-d','--no-deps','control-plane');
  const endpoint='http://127.0.0.1:'+state.ports.console,admin=new ContractClient(endpoint),password=(await fs.readFile(path.join(directory,'secrets/bootstrap-password'),'utf8')).trimEnd();await until(()=>admin.login(state.bootstrapUsername,password),()=>true,60);
  const environment=await admin.request('/environments/'+state.binding.environmentId),project=await admin.request('/projects/'+environment.projectId),organization=await admin.request('/organizations/'+project.organizationId),scope={organizationId:organization.id,projectId:project.id,environmentId:environment.id};
  const flow=await admin.request('/organizations/'+organization.id+'/approval-flows',{method:'POST',body:{name:'契约两级独立审批 '+tag,enabled:true,steps:[{stepOrder:1,roleCode:'ApiApprover',requiredCount:1},{stepOrder:2,roleCode:'SecurityReviewer',requiredCount:1}]}});
  await admin.request('/environments/'+environment.id,{method:'PUT',headers:{'If-Match':`"${environment.revision}"`},body:{code:environment.code,name:environment.name,status:environment.status,isProduction:true,sortOrder:environment.sortOrder,releasePolicyId:flow.id}});
  const roles=await admin.request('/roles'),reviewers=[];const browserUsers=[];
  for(const [suffix,roleCode,accessMode]of [['approver','ApiApprover','read_write'],['security','SecurityReviewer','read_write'],['readonly','ApiApprover','read']]){
   const username='contract-'+tag+'-'+suffix,userPassword=randomBytes(24).toString('base64');let user=await admin.request('/users',{method:'POST',body:{username,displayName:'契约验收 '+suffix,password:userPassword}});
   user=await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{roleIds:[roles.find(role=>role.isSystem&&role.code===roleCode).id]}});
   await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{scopes:[{scope:{organizationId:organization.id},accessMode}]}});const client=new ContractClient(endpoint);await client.login(username,userPassword);reviewers.push(client);browserUsers.push({username,password:userPassword,id:user.id});
  }
  const cluster=await admin.request('/environments/'+environment.id+'/clusters',{method:'POST',body:{name:'ContractBackend-'+tag,loadBalancingPolicy:'RoundRobin',healthCheckEnabled:false}});await admin.request('/clusters/'+cluster.id+'/destinations',{method:'POST',body:{name:'backend-a',address:'http://backend-a:8080/',weight:1,enabled:true}});
  const policyPath='/projects/'+project.id+'/import-source-policy';let policy=await admin.request(policyPath);policy=await admin.request(policyPath,{method:'PUT',headers:{'If-Match':`"${policy.revision}"`},body:{allowances:[{origin,pathPrefix:'/contracts/',privateCidrs:cidrs}],limits:policy.limits}});
  const context={directory,revision,release,state,endpoint,admin,password,scope,environment,project,organization,cluster,flow,reviewers,browserUsers,fixture,origin,cidrs,policy};
  await writePrivate(path.join(privateDirectory,'browser-context.json'),{endpoint,sourceRevision:revision,scope,admin:{username:state.bootstrapUsername,password},users:browserUsers,clusterId:cluster.id,fixtureOrigin:origin,fixtureSource:fixture.yaml(),fixtureSchemas:fixture.schemas,tag});return context;
 }catch(error){await fixture.close();throw error;}
}
export async function exerciseContractScenario(s,{privateDirectory}){
 const {admin,scope,cluster,fixture,origin}=s,previewPath='/openapi/import-previews',versionPath=id=>'/versions/'+id;const input={projectId:scope.projectId,environmentId:scope.environmentId,clusterId:cluster.id};const evidence={sourceRevision:s.revision,imageId:s.release.imageId,actual:true,steps:[]};
 const note=(name,value={})=>{evidence.steps.push({name,...value,time:new Date().toISOString()});console.log(JSON.stringify({step:name,...value}));};
 const reject=async(action,status,code)=>{await assert.rejects(action,error=>error.status===status&&(!code||error.code===code));};
 const target=version=>({operationId:'contractRead',newApiCode:'CONTRACT_'+version+'_'+randomUUID().slice(0,8),newApiName:'契约验收 API',version:'1.0.0'});
 const previews=[];const preview=async(body,client=admin)=>{const result=await client.request(previewPath,{method:'POST',body:{...input,...body}});if(client===admin)previews.push(result.previewId);return result;};
 // Prove auth occurs before network access, using a real read-only scoped account.
 const beforeAuth=fixture.requests.length;await reject(()=>preview({sourceUrl:origin+'/contracts/openapi.yaml'},s.reviewers[2]),403);assert.equal(fixture.requests.length,beforeAuth);note('readonly-zero-network',{status:403,requests:0});
 const fixed=await preview({sourceUrl:origin+'/contracts/openapi.yaml'});assert.equal(fixed.sourceFormat,'yaml');assert.equal(fixed.sourceHash,hash(fixture.yaml()));assert.equal(fixed.operations.length,1);assert(fixed.operations[0].supported);
 const jsonPreview=await preview({sourceText:fixture.json(),format:'json',files:[{name:'schemas.yaml',content:fixture.schemas,format:'yaml'}]});assert.deepEqual(jsonPreview.operations,fixed.operations);await admin.request(previewPath+'/'+jsonPreview.previewId,{method:'DELETE'});note('url-yaml-json-semantics',{dialect:fixed.dialect,sourceHash:fixed.sourceHash,bundleHash:fixed.bundleHash,operations:1});
 const target1=target('V1'),commitBody={expectedBundleHash:fixed.bundleHash,targets:[target1]},commitKey=randomUUID();await reject(()=>admin.request(previewPath+'/'+fixed.previewId+'/commit',{method:'POST',body:{...commitBody,expectedBundleHash:'0'.repeat(64)}}),409,'import_preview_changed');
 fixture.change();const requestsBeforeCommit=fixture.requests.length,import1=await admin.request(previewPath+'/'+fixed.previewId+'/commit',{method:'POST',key:commitKey,body:commitBody});assert.equal(fixture.requests.length,requestsBeforeCommit);const replay=await admin.request(previewPath+'/'+fixed.previewId+'/commit',{method:'POST',key:commitKey,body:commitBody});assert.deepEqual(replay,import1);
 const first=import1.operations[0],v1=await admin.request(versionPath(first.versionId));assert(v1.openapiSource.includes('preview-original')&&!v1.openapiSource.includes('changed-after-preview'));assert.equal(v1.sourceFormat,'yaml');note('immutable-commit-and-receipt',{importId:import1.importId,noNetworkOnCommit:true,receiptReplay:true,apiId:first.apiId,versionId:first.versionId});
 for(const [route,status]of [['redirect.yaml',422],['oversized.yaml',413],['slow.yaml',504]]){const start=Date.now();await reject(()=>preview({sourceUrl:origin+'/contracts/'+route}),status);assert(Date.now()-start<25000);note('url-rejection-'+route,{status,bounded:true});}
 for(const source of ['openapi: 3.1.0\nopenapi: 3.0.3\n','---\nopenapi: 3.1.0\n---\nopenapi: 3.1.0\n','value: !evil payload\n'])await reject(()=>preview({sourceText:source,format:'yaml'}),422);note('yaml-invalid-rejections',{actualRequests:3});
 const stale=await preview({sourceText:fixture.json(),format:'json',files:[{name:'schemas.yaml',content:fixture.schemas}]});let policy=await admin.request('/projects/'+scope.projectId+'/import-source-policy');policy=await admin.request('/projects/'+scope.projectId+'/import-source-policy',{method:'PUT',headers:{'If-Match':`"${policy.revision}"`},body:{allowances:policy.allowances,limits:policy.limits}});await reject(()=>admin.request(previewPath+'/'+stale.previewId+'/commit',{method:'POST',body:{expectedBundleHash:stale.bundleHash,targets:[target('STALE')]}}),409,'import_preview_changed');await admin.request(previewPath+'/'+stale.previewId,{method:'DELETE'});note('policy-revision-invalidates-preview',{status:409});
 const schemas1=await admin.request(versionPath(v1.id)+'/schemas'),responseSchema=schemas1.find(schema=>schema.schemaType==='response');assert(responseSchema);const options=responseSchema.examples??[];for(const value of ['false','0','""','null'])assert(options.some(option=>option.json===value));assert(options.some(option=>option.externalValue&&option.unverifiedReason));
 const validate=(version,schema,exampleJson,extra={},client=admin)=>client.request(versionPath(version.id)+'/schema-validation',{method:'POST',body:{expectedVersionRevision:version.revision,schemaId:schema.id,exampleJson,direction:'response',formatMode:'Annotation',...extra}});
 const valid=await validate(v1,responseSchema,'{"id":1,"label":"sample"}');assert.equal(valid.result.status,'Valid');const invalid=await validate(v1,responseSchema,'{"id":"private-example-marker","label":"sample"}');assert.equal(invalid.result.status,'Invalid');assert(invalid.result.issues.length>0);assert(!JSON.stringify(invalid).includes('private-example-marker'));await reject(()=>validate(v1,responseSchema,'{}',{expectedVersionRevision:v1.revision+100}),412);assert.equal((await validate(v1,responseSchema,'{"id":1,"label":"sample"}',{},s.reviewers[2])).result.status,'Valid');note('example-validation',{valid:true,invalid:true,positioned:true,noSampleLeak:true,staleRevisionStatus:412,falsyAndExternalOptions:true,readOnlyValidation:true});
 const app=await admin.request('/applications',{method:'POST',body:{organizationId:scope.organizationId,projectId:scope.projectId,code:'CONTRACT_'+randomUUID().slice(0,8),name:'契约验收消费方',owner:'验收'}}),key=await admin.request('/applications/'+app.id+'/credentials',{method:'POST',body:{validFrom:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+24*3600000).toISOString()}});await writePrivate(path.join(privateDirectory,'scenario-credential.json'),{apiKey:key.apiKey});await admin.request('/applications/'+app.id+'/permissions',{method:'POST',body:{apiId:first.apiId,environmentId:scope.environmentId,validFrom:new Date(Date.now()-60000).toISOString()}});
 const initialRoutes=(await admin.request('/environments/'+scope.environmentId+'/routes?pageSize=100')).items.filter(route=>route.enabled&&route.apiVersionId!==first.versionId),initialVersions=[...new Set(initialRoutes.map(route=>route.apiVersionId))];
 async function completeRelease(release){await admin.request('/releases/'+release.id+'/submit',{method:'POST'});for(const client of s.reviewers.slice(0,2))await client.request('/releases/'+release.id+'/approve',{method:'POST',body:{comment:'契约真实恢复克隆的两级独立审核'}});await admin.request('/releases/'+release.id+'/publish',{method:'POST'});return until(()=>admin.request('/releases/'+release.id),value=>{assert.notEqual(value.state,'Failed');return value.state==='Succeeded'&&value.targets.length===2&&value.targets.every(target=>target.acknowledged);},120);}
 async function publish(versionId,reviewId){const env=await admin.request('/environments/'+scope.environmentId),selection={baseConfigVersion:env.desiredConfigVersion??0,versionIds:[...initialVersions,versionId]},candidate=await admin.request('/environments/'+scope.environmentId+'/releases/preview',{method:'POST',body:selection});const release=await admin.request('/environments/'+scope.environmentId+'/releases',{method:'POST',body:{...selection,resourceRevisions:candidate.resourceRevisions,...(reviewId?{riskReviewIds:[reviewId]}:{})}});return completeRelease(release);}
 async function gateway(route,status){for(const port of [s.state.ports.gatewayA,s.state.ports.gatewayB]){const response=await fetch('http://127.0.0.1:'+port+route,{headers:{'X-API-Key':key.apiKey},signal:AbortSignal.timeout(15000)});await response.arrayBuffer();assert.equal(response.status,status);}}
 const release1=await publish(v1.id);await gateway(fixture.route,200);const publishedVersion=await admin.request(versionPath(v1.id));assert.equal(publishedVersion.status,'Published');assert(publishedVersion.sealedAt);note('baseline-published',{releaseId:release1.id,twoIndependentApprovers:true,dualAck:true,dualGatewayStatus:200});
 const source2=JSON.parse(fixture.json());const path2=fixture.route+'-v2';source2.paths[path2]=source2.paths[fixture.route];delete source2.paths[fixture.route];const preview2=await preview({sourceText:JSON.stringify(source2),format:'json',files:[{name:'schemas.yaml',content:fixture.schemas,format:'yaml'}]});const import2=await admin.request(previewPath+'/'+preview2.previewId+'/commit',{method:'POST',body:{expectedBundleHash:preview2.bundleHash,targets:[{operationId:'contractRead',apiId:first.apiId,version:'2.0.0'}]}});let v2=await admin.request(versionPath(import2.operations[0].versionId));const schemas2=await admin.request(versionPath(v2.id)+'/schemas');
 await reject(()=>admin.request(versionPath(v2.id)+'/schemas',{method:'PUT',headers:{'If-Match':`"${v2.revision+10}"`},body:schemas2}),412);await reject(()=>s.reviewers[2].request(versionPath(v2.id)+'/schemas',{method:'PUT',headers:{'If-Match':`"${v2.revision}"`},body:schemas2}),403);
 const edited=schemas2.map(schema=>({id:schema.id,schemaType:schema.schemaType,name:schema.name,statusCode:schema.statusCode,contentType:schema.contentType,schemaJson:schema.schemaType==='response'?JSON.stringify({type:'object',required:['id','label'],properties:{id:{type:'string'},label:{type:'string'}},additionalProperties:false}):schema.schemaJson,exampleJson:schema.exampleJson}));await admin.request(versionPath(v2.id)+'/schemas',{method:'PUT',headers:{'If-Match':`"${v2.revision}"`},body:edited});v2=await admin.request(versionPath(v2.id));note('schema-draft-save',{staleRevisionStatus:412,readOnlyWriteStatus:403,versionId:v2.id});
 const sealed=await admin.request(versionPath(v1.id)),comparison=await admin.request('/apis/'+first.apiId+'/version-comparisons',{method:'POST',body:{fromVersionId:v1.id,toVersionId:v2.id,expectedFromRevision:sealed.revision,expectedToRevision:v2.revision,formatMode:'Annotation'}});assert.equal(comparison.report.engineVersion,'compatibility-v2');assert.notEqual(comparison.report.coverage,'Invalid');assert(comparison.report.counts.breaking+comparison.report.counts.unknown>0);assert(comparison.report.provenance?.inputHash);await reject(()=>admin.request('/version-comparisons/'+comparison.id+'/reviews',{method:'POST',body:{expectedReportHash:comparison.reportHash,decision:'Reviewed',comment:'未确认风险的拒绝检查'}}),422);const review=await admin.request('/version-comparisons/'+comparison.id+'/reviews',{method:'POST',body:{expectedReportHash:comparison.reportHash,decision:'AcceptedRisk',comment:'仅独立恢复克隆验证破坏性与未知契约风险，已明确确认接受。',confirmRisk:true}});
 note('comparison-risk-review',{comparisonId:comparison.id,reportHash:comparison.reportHash,inputHash:comparison.report.provenance.inputHash,coverage:comparison.report.coverage,counts:comparison.report.counts,reviewId:review.id});
 const release2=await publish(v2.id,review.id);assert(release2.frozenCandidate.riskReviews.some(item=>item.reviewId===review.id));await gateway(path2,200);await gateway(fixture.route,404);note('review-two-level-publish',{releaseId:release2.id,twoIndependentApprovers:true,frozenReview:true,dualAck:true,dualGatewayStatus:200});
 const rollback=await completeRelease(await admin.request('/releases/'+release2.id+'/rollback',{method:'POST',body:{targetConfigVersion:release1.targetConfigVersion}}));await gateway(fixture.route,200);await gateway(path2,404);note('rollback',{releaseId:rollback.id,targetConfigVersion:release1.targetConfigVersion,dualAck:true,dualGatewayStatus:200});
 const catalog=await admin.request('/comparisons/rules');assert.equal(catalog.engineVersion,'compatibility-v2');await writePrivate(path.join(privateDirectory,'actual-rule-catalog.json'),catalog);
 await writePrivate(path.join(privateDirectory,'scenario-result.json'),{...evidence,complete:true,apiId:first.apiId,v1Id:v1.id,v2Id:v2.id,comparisonId:comparison.id,reviewId:review.id,releaseIds:[release1.id,release2.id,rollback.id],httpRequestCount:fixture.requests.length});
 const browser=JSON.parse(await fs.readFile(path.join(privateDirectory,'browser-context.json'),'utf8'));await writePrivate(path.join(privateDirectory,'browser-context.json'),{...browser,apiId:first.apiId,v1Id:v1.id,v2Id:v2.id,comparisonId:comparison.id,reviewId:review.id,releaseIds:[release1.id,release2.id,rollback.id]});return evidence;
}
