import {copyLoginProtectionBackup,restoreLoginProtectionBackup,loginProtectionReceiptName} from '../security/runtime-secrets.mjs';
import {synchronizeConsoleProxyTrust} from '../security/proxy-trust.mjs';
import {notificationVolumes,copyNotificationBackup,restoreNotificationBackup} from '../notifications/runtime-secrets.mjs';
import {copyCacheBackup,restoreCacheBackup,cacheReceiptName} from '../gateway-policies/runtime-secrets.mjs';
import{copySsoBackup,restoreSsoBackup,ssoConfigName}from'./sso-deployment.mjs';
import fs from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{initializeState,saveState,writePrivate,loadState,withRuntimeLock}from'./state.mjs';import{docker,inspectResources,assertOwnership}from'./docker.mjs';
import{validateFixture}from'./fixture-guard.mjs';
import{runtimeServices,loadRelease,waitForRuntime}from'./lifecycle.mjs';import{prepareContext}from'./context.mjs';
export const deliveryVolumeNames=['delivery-secrets','delivery-lkg-a','delivery-lkg-b'];
export const deliveryServices=['prod-gateway-a','prod-gateway-b'];
export function validateDeliveryContext(ctx){if(!ctx.delivery)return [];if(JSON.stringify(ctx.delivery.volumes)!==JSON.stringify(deliveryVolumeNames)||JSON.stringify(ctx.delivery.services)!==JSON.stringify(deliveryServices))throw Error('Unexpected delivery backup scope');return deliveryVolumeNames;}
export function validatePipelineContext(ctx){
 if(!ctx.pipeline)return [];const groups=ctx.pipeline.stageGroups;if(!Array.isArray(groups)||groups.length<2||groups.length>8)throw Error('Unexpected pipeline stage scope');
 if(ctx.state&&ctx.pipeline.ownerId!==ctx.state.ownerId)throw Error('Pipeline owner mismatch');const ids=new Set();
 for(const [i,g]of groups.entries()){if(g.type!=='PipelineStageGroup'||g.order!==i+1||!g.environmentId||ids.has(g.environmentId))throw Error('Unexpected pipeline Stage group');ids.add(g.environmentId);const kind=i===0?'Source':i===groups.length-1?'Production':'Middle';if(g.kind!==kind)throw Error('Unexpected pipeline stage kind');const expected=kind==='Source'?{services:['gateway-a','gateway-b'],volumes:['lkg-a','lkg-b']}:kind==='Production'?{services:deliveryServices,volumes:deliveryVolumeNames}:{services:[`pipeline-stage-${g.order}-gateway-a`,`pipeline-stage-${g.order}-gateway-b`],volumes:[`pipeline-stage-${g.order}-secrets`,`pipeline-stage-${g.order}-lkg-a`,`pipeline-stage-${g.order}-lkg-b`]};if(JSON.stringify(g.services)!==JSON.stringify(expected.services)||JSON.stringify(g.volumes)!==JSON.stringify(expected.volumes))throw Error('Unexpected pipeline service/volume scope');}
 return [...new Set(groups.flatMap(g=>g.volumes))];
}
export const pipelineStageTopology=groups=>groups.map(({type,order,environmentId,kind,services,volumes})=>({type,order,environmentId,kind,services,volumes}));
export const pipelineServices=ctx=>{validatePipelineContext(ctx);return ctx.pipeline?ctx.pipeline.stageGroups.flatMap(g=>[...g.services,...(g.kind==='Middle'?[`pipeline-stage-${g.order}-backend`]:[])]):[];};
export const backupVolumeNames=ctx=>{if(ctx.pipeline&&ctx.reportsSupported!==true)throw Error('Pipeline backup requires protected report volume');return [...new Set([...validatePipelineContext(ctx),...validateDeliveryContext(ctx),...dataVolumes,...(ctx.reportsSupported?['verification-reports']:[]),...(ctx.cacheSupported?['secrets-cache']:[]),...(ctx.notification?notificationVolumes:[])])];};

export const dataVolumes=['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data'];
export const backupStopServices=(state,notification=null)=>runtimeServices(state,notification).filter(name=>!['postgres','redis'].includes(name));
export async function coldBackup(ctx,target,options={}){
 validateFixture(ctx.state.projectName,ctx.directory);return createBackup(ctx,target,options);
}
export async function createBackup(ctx,target,{contextFactory=prepareContext}={}){
 return withRuntimeLock(ctx.directory,async()=>{const current=await loadState(ctx.directory);if(current.ownerId!==ctx.state.ownerId||current.projectName!==ctx.state.projectName)throw Error('Backup runtime owner mismatch');if(!current.initialized||current.pendingConfiguration||current.bindingPhase==='Validated')throw Error('Backup requires initialized runtime with no pending configuration; complete configure retry first');const release=await loadRelease(path.join(ctx.directory,'release.json'));return writeBackup(await contextFactory(ctx.directory,current,release),target);});
}
async function writeBackup(ctx,target){
 const volumes=backupVolumeNames(ctx);const resources=await inspectResources(ctx.state);assertOwnership(ctx.state,resources);for(const name of volumes)if(!resources.some(r=>r.Kind==='volume'&&r.Name===ctx.state.projectName+'_'+name))throw Error('Backup requires every owned data volume to exist');await fs.mkdir(target,{mode:0o700});return withBackupServicesPaused(ctx,async()=>{await ctx.compose('up','-d','--wait','postgres');
 await ctx.compose('exec','-T','postgres','pg_dump','-U','webapi','-d','webapi','--format=custom','--file=/tmp/local-runtime.dump');const pg=(await inspectResources(ctx.state)).find(r=>r.Kind==='container'&&r.Config?.Labels?.['com.docker.compose.service']==='postgres');await docker(['cp',pg.Id+':/tmp/local-runtime.dump',path.join(target,'postgres.dump')]);await fs.chmod(path.join(target,'postgres.dump'),0o600);await ctx.compose('stop','postgres','redis');
 const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup`];for(const name of volumes)args.push('--mount',`type=volume,src=${ctx.state.projectName}_${name},dst=/volumes/${name},readonly`);args.push(ctx.release.dependencyImages.sdk,'bash','-c','set -e; umask 077; for name in '+volumes.join(' ')+'; do tar --numeric-owner -cf /backup/$name.tar -C /volumes/$name .; done');await docker(args);
 await fs.cp(path.join(ctx.directory,'secrets'),path.join(target,'secrets'),{recursive:true});await fs.copyFile(path.join(ctx.directory,'release.json'),path.join(target,'release.json'));await writePrivate(path.join(target,'runtime.json'),ctx.state);await copySsoBackup(ctx.directory,target,ctx.state);await copyCacheBackup(ctx.directory,target,ctx.state);await copyLoginProtectionBackup(ctx.directory,target,ctx.state);const notificationHashes=await copyNotificationBackup(ctx.directory,target,ctx.state);const hashes={...notificationHashes};if(ctx.pipeline){await fs.copyFile(path.join(ctx.directory,'pipeline-runtime.json'),path.join(target,'pipeline-runtime.json'));await fs.chmod(path.join(target,'pipeline-runtime.json'),0o600);hashes['pipeline-runtime.json']=createHash('sha256').update(await fs.readFile(path.join(target,'pipeline-runtime.json'))).digest('hex');}if(ctx.delivery){await fs.copyFile(path.join(ctx.directory,'delivery-runtime.json'),path.join(target,'delivery-runtime.json'));await fs.chmod(path.join(target,'delivery-runtime.json'),0o600);hashes['delivery-runtime.json']=createHash('sha256').update(await fs.readFile(path.join(target,'delivery-runtime.json'))).digest('hex');}for(const file of ['postgres.dump',...volumes.map(n=>n+'.tar'),'runtime.json','release.json']){await fs.chmod(path.join(target,file),0o600);hashes[file]=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');}for(const file of await fs.readdir(path.join(target,'secrets')))hashes['secrets/'+file]=createHash('sha256').update(await fs.readFile(path.join(target,'secrets',file))).digest('hex');for(const file of [ssoConfigName,cacheReceiptName,loginProtectionReceiptName,...['local-demo-api-approver.password','local-demo-security-reviewer.password','consumer-api-key'].map(n=>'demo/'+n)]){try{hashes[file]=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');}catch(e){if(e.code!=='ENOENT')throw e;}}await writePrivate(path.join(target,'backup-manifest.json'),{schemaVersion:1,sourceRevision:ctx.release.sourceRevision,files:hashes,...(ctx.delivery?{delivery:ctx.delivery}:{}),...(ctx.pipeline?{pipeline:ctx.pipeline}:{})});return hashes;});
}
export async function restoreColdBackup({target,projectName,directory,ports,notificationPorts,contextFactory}){
 validateFixture(projectName,directory);if(await fs.lstat(directory).catch(e=>{if(e.code==='ENOENT')return null;throw e;}))throw Error('Restore requires a fresh disposable directory');
 const manifest=JSON.parse(await fs.readFile(path.join(target,'backup-manifest.json'),'utf8'));for(const[file,hash]of Object.entries(manifest.files)){if(path.isAbsolute(file)||file.split('/').includes('..'))throw Error('Invalid backup path');const actual=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');if(actual!==hash)throw Error('Backup checksum mismatch');}
 const previous=JSON.parse(await fs.readFile(path.join(target,'runtime.json'),'utf8'));let state=await initializeState(directory,{projectName,ports,bootstrapUsername:previous.bootstrapUsername});state={...previous,ownerId:state.ownerId,projectName,ports};await saveState(directory,state);await fs.cp(path.join(target,'secrets'),path.join(directory,'secrets'),{recursive:true});await fs.copyFile(path.join(target,'release.json'),path.join(directory,'release.json'));const release=JSON.parse(await fs.readFile(path.join(directory,'release.json'),'utf8'));await restoreSsoBackup(target,directory,state);await restoreCacheBackup(target,directory,state);await restoreLoginProtectionBackup(target,directory,state);const notification=await restoreNotificationBackup(target,directory,state,notificationPorts);if(manifest.pipeline){if(!Object.hasOwn(manifest.files,'verification-reports.tar'))throw Error('Pipeline restore requires protected reports');if(manifest.pipeline.ownerId!==previous.ownerId)throw Error('Backup pipeline owner mismatch');validatePipelineContext({pipeline:manifest.pipeline});await fs.copyFile(path.join(target,'pipeline-runtime.json'),path.join(directory,'pipeline-runtime.json'));}if(manifest.delivery)await fs.copyFile(path.join(target,'delivery-runtime.json'),path.join(directory,'delivery-runtime.json'));const ctx=await contextFactory(directory,state,release);await initializeRestoreVolumes(ctx,manifest,notification);assertOwnership(state,await inspectResources(state));
 const volumes=[...new Set([...(manifest.pipeline?validatePipelineContext(ctx):[]),...(manifest.delivery?deliveryVolumeNames:[]),...dataVolumes,...(Object.hasOwn(manifest.files,'verification-reports.tar')?['verification-reports']:[]),...(Object.hasOwn(manifest.files,'secrets-cache.tar')?['secrets-cache']:[]),...(notification?notificationVolumes:[])])];const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup,readonly`];for(const name of volumes)args.push('--mount',`type=volume,src=${projectName}_${name},dst=/volumes/${name}`);args.push(release.dependencyImages.sdk,'bash','-c','set -e; for name in '+volumes.join(' ')+'; do if [ "$name" = secrets-cache ]; then tar -xOf /backup/$name.tar ./cache-hmac | sha256sum | cut -d " " -f1 > /tmp/cache-archive.sha; sha256sum /volumes/$name/cache-hmac | cut -d " " -f1 > /tmp/cache-seeded.sha; cmp /tmp/cache-archive.sha /tmp/cache-seeded.sha; elif [ "$name" = notification-secrets ] || [ "$name" = notification-fixture-secrets ]; then mkdir /tmp/check-$name; tar -xf /backup/$name.tar -C /tmp/check-$name; diff -r /tmp/check-$name /volumes/$name; else test -z "$(ls -A /volumes/$name)"; tar -xf /backup/$name.tar -C /volumes/$name; fi; done');await docker(args);if(notification){await docker(['run','--rm','--user','10001:10001','--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId,'--mount','type=volume,src='+projectName+'_notification-fixture-data,dst=/var/fixture',release.imageId,'dotnet','/app/notification-fixture/WebApi.NotificationFixtureHost.dll','rebind-journal','/var/fixture',previous.ownerId,previous.projectName,state.ownerId,state.projectName]);}return{state,ctx,hashesVerified:true};
}

export async function initializeRestoreVolumes(ctx,manifest,notification){
 if(manifest.pipeline){validatePipelineContext({pipeline:manifest.pipeline});validatePipelineContext(ctx);if(JSON.stringify(pipelineStageTopology(manifest.pipeline.stageGroups))!==JSON.stringify(pipelineStageTopology(ctx.pipeline.stageGroups)))throw Error('Restore pipeline context mismatch');}else if(ctx.pipeline)throw Error('Unexpected pipeline restore context');
 if(manifest.delivery){validateDeliveryContext({delivery:manifest.delivery});validateDeliveryContext(ctx);if(JSON.stringify(ctx.delivery)!==JSON.stringify(manifest.delivery))throw Error('Restore delivery context mismatch');}else if(ctx.delivery)throw Error('Unexpected delivery restore context');
 await ctx.compose('run','--rm','--no-deps','init-volumes');
 if(notification)await ctx.compose('run','--rm','--no-deps','init-notification-volumes');
 if(manifest.delivery)await ctx.compose('run','--rm','--no-deps','init-delivery-storage');
 if(manifest.pipeline)for(const group of ctx.pipeline.stageGroups.filter(g=>g.kind==='Middle'))await ctx.compose('run','--rm','--no-deps',`init-pipeline-stage-${group.order}-storage`);
}

export async function withBackupServicesPaused(ctx,action,{wait=waitForRuntime}={}){try{await ctx.compose('stop',...[...new Set([...backupStopServices(ctx.state,ctx.notification),...(validateDeliveryContext(ctx).length?deliveryServices:[]),...pipelineServices(ctx)])]);return await action();}finally{await ctx.compose('up','-d',...[...new Set([...runtimeServices(ctx.state,ctx.notification),...(ctx.delivery?deliveryServices:[]),...pipelineServices(ctx)])]);if(ctx.securitySupported)await synchronizeConsoleProxyTrust(ctx);await wait(ctx);}}
