import {copyLoginProtectionBackup,restoreLoginProtectionBackup,loginProtectionReceiptName} from '../security/runtime-secrets.mjs';
import {synchronizeConsoleProxyTrust} from '../security/proxy-trust.mjs';
import {notificationVolumes,copyNotificationBackup,restoreNotificationBackup} from '../notifications/runtime-secrets.mjs';
import {copyCacheBackup,restoreCacheBackup,cacheReceiptName} from '../gateway-policies/runtime-secrets.mjs';
import{copySsoBackup,restoreSsoBackup,ssoConfigName}from'./sso-deployment.mjs';
import fs from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{initializeState,saveState,writePrivate,loadState,withRuntimeLock}from'./state.mjs';import{docker,inspectResources,assertOwnership}from'./docker.mjs';
import{validateFixture}from'./fixture-guard.mjs';
import{runtimeServices,loadRelease,waitForRuntime}from'./lifecycle.mjs';import{prepareContext}from'./context.mjs';
export const backupVolumeNames=ctx=>[...dataVolumes,...(ctx.cacheSupported?['secrets-cache']:[]),...(ctx.notification?notificationVolumes:[])];
export const dataVolumes=['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data'];
export const backupStopServices=(state,notification=null)=>runtimeServices(state,notification).filter(name=>!['postgres','redis'].includes(name));
export async function coldBackup(ctx,target){
 validateFixture(ctx.state.projectName,ctx.directory);return createBackup(ctx,target);
}
export async function createBackup(ctx,target){
 return withRuntimeLock(ctx.directory,async()=>{const current=await loadState(ctx.directory);if(current.ownerId!==ctx.state.ownerId||current.projectName!==ctx.state.projectName)throw Error('Backup runtime owner mismatch');if(!current.initialized||current.pendingConfiguration||current.bindingPhase==='Validated')throw Error('Backup requires initialized runtime with no pending configuration; complete configure retry first');const release=await loadRelease(path.join(ctx.directory,'release.json'));return writeBackup(await prepareContext(ctx.directory,current,release),target);});
}
async function writeBackup(ctx,target){
 const volumes=backupVolumeNames(ctx);const resources=await inspectResources(ctx.state);assertOwnership(ctx.state,resources);for(const name of volumes)if(!resources.some(r=>r.Kind==='volume'&&r.Name===ctx.state.projectName+'_'+name))throw Error('Backup requires every owned data volume to exist');await fs.mkdir(target,{mode:0o700});return withBackupServicesPaused(ctx,async()=>{await ctx.compose('up','-d','--wait','postgres');
 await ctx.compose('exec','-T','postgres','pg_dump','-U','webapi','-d','webapi','--format=custom','--file=/tmp/local-runtime.dump');const pg=(await inspectResources(ctx.state)).find(r=>r.Kind==='container'&&r.Config?.Labels?.['com.docker.compose.service']==='postgres');await docker(['cp',pg.Id+':/tmp/local-runtime.dump',path.join(target,'postgres.dump')]);await fs.chmod(path.join(target,'postgres.dump'),0o600);await ctx.compose('stop','postgres','redis');
 const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup`];for(const name of volumes)args.push('--mount',`type=volume,src=${ctx.state.projectName}_${name},dst=/volumes/${name},readonly`);args.push(ctx.release.dependencyImages.sdk,'bash','-c','set -e; umask 077; for name in '+volumes.join(' ')+'; do tar --numeric-owner -cf /backup/$name.tar -C /volumes/$name .; done');await docker(args);
 await fs.cp(path.join(ctx.directory,'secrets'),path.join(target,'secrets'),{recursive:true});await fs.copyFile(path.join(ctx.directory,'release.json'),path.join(target,'release.json'));await writePrivate(path.join(target,'runtime.json'),ctx.state);await copySsoBackup(ctx.directory,target,ctx.state);await copyCacheBackup(ctx.directory,target,ctx.state);await copyLoginProtectionBackup(ctx.directory,target,ctx.state);const notificationHashes=await copyNotificationBackup(ctx.directory,target,ctx.state);const hashes={...notificationHashes};for(const file of ['postgres.dump',...volumes.map(n=>n+'.tar'),'runtime.json','release.json']){await fs.chmod(path.join(target,file),0o600);hashes[file]=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');}for(const file of await fs.readdir(path.join(target,'secrets')))hashes['secrets/'+file]=createHash('sha256').update(await fs.readFile(path.join(target,'secrets',file))).digest('hex');for(const file of [ssoConfigName,cacheReceiptName,loginProtectionReceiptName,...['local-demo-api-approver.password','local-demo-security-reviewer.password','consumer-api-key'].map(n=>'demo/'+n)]){try{hashes[file]=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');}catch(e){if(e.code!=='ENOENT')throw e;}}await writePrivate(path.join(target,'backup-manifest.json'),{schemaVersion:1,sourceRevision:ctx.release.sourceRevision,files:hashes});return hashes;});
}
export async function restoreColdBackup({target,projectName,directory,ports,notificationPorts,contextFactory}){
 validateFixture(projectName,directory);if(await fs.lstat(directory).catch(e=>{if(e.code==='ENOENT')return null;throw e;}))throw Error('Restore requires a fresh disposable directory');
 const manifest=JSON.parse(await fs.readFile(path.join(target,'backup-manifest.json'),'utf8'));for(const[file,hash]of Object.entries(manifest.files)){if(path.isAbsolute(file)||file.split('/').includes('..'))throw Error('Invalid backup path');const actual=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');if(actual!==hash)throw Error('Backup checksum mismatch');}
 const previous=JSON.parse(await fs.readFile(path.join(target,'runtime.json'),'utf8'));let state=await initializeState(directory,{projectName,ports,bootstrapUsername:previous.bootstrapUsername});state={...previous,ownerId:state.ownerId,projectName,ports};await saveState(directory,state);await fs.cp(path.join(target,'secrets'),path.join(directory,'secrets'),{recursive:true});await fs.copyFile(path.join(target,'release.json'),path.join(directory,'release.json'));const release=JSON.parse(await fs.readFile(path.join(directory,'release.json'),'utf8'));await restoreSsoBackup(target,directory,state);await restoreCacheBackup(target,directory,state);await restoreLoginProtectionBackup(target,directory,state);const notification=await restoreNotificationBackup(target,directory,state,notificationPorts);const ctx=await contextFactory(directory,state,release);await ctx.compose('run','--rm','--no-deps','init-volumes');if(notification)await ctx.compose('run','--rm','--no-deps','init-notification-volumes');assertOwnership(state,await inspectResources(state));
 const volumes=[...dataVolumes,...(Object.hasOwn(manifest.files,'secrets-cache.tar')?['secrets-cache']:[]),...(notification?notificationVolumes:[])];const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup,readonly`];for(const name of volumes)args.push('--mount',`type=volume,src=${projectName}_${name},dst=/volumes/${name}`);args.push(release.dependencyImages.sdk,'bash','-c','set -e; for name in '+volumes.join(' ')+'; do if [ "$name" = secrets-cache ]; then tar -xOf /backup/$name.tar ./cache-hmac | sha256sum | cut -d " " -f1 > /tmp/cache-archive.sha; sha256sum /volumes/$name/cache-hmac | cut -d " " -f1 > /tmp/cache-seeded.sha; cmp /tmp/cache-archive.sha /tmp/cache-seeded.sha; elif [ "$name" = notification-secrets ] || [ "$name" = notification-fixture-secrets ]; then mkdir /tmp/check-$name; tar -xf /backup/$name.tar -C /tmp/check-$name; diff -r /tmp/check-$name /volumes/$name; else test -z "$(ls -A /volumes/$name)"; tar -xf /backup/$name.tar -C /volumes/$name; fi; done');await docker(args);if(notification){await docker(['run','--rm','--user','10001:10001','--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId,'--mount','type=volume,src='+projectName+'_notification-fixture-data,dst=/var/fixture',release.imageId,'dotnet','/app/notification-fixture/WebApi.NotificationFixtureHost.dll','rebind-journal','/var/fixture',previous.ownerId,previous.projectName,state.ownerId,state.projectName]);}return{state,ctx,hashesVerified:true};
}

export async function withBackupServicesPaused(ctx,action,{wait=waitForRuntime}={}){try{await ctx.compose('stop',...backupStopServices(ctx.state,ctx.notification));return await action();}finally{await ctx.compose('up','-d',...runtimeServices(ctx.state,ctx.notification));if(ctx.securitySupported)await synchronizeConsoleProxyTrust(ctx);await wait(ctx);}}
