import fs from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{initializeState,saveState,writePrivate,loadState,withRuntimeLock}from'./state.mjs';import{docker,inspectResources,assertOwnership}from'./docker.mjs';
import{validateFixture}from'./fixture-guard.mjs';
export const dataVolumes=['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data'];
export async function coldBackup(ctx,target){
 validateFixture(ctx.state.projectName,ctx.directory);return createBackup(ctx,target);
}
export async function createBackup(ctx,target){
 const current=await loadState(ctx.directory);if(current.ownerId!==ctx.state.ownerId||current.projectName!==ctx.state.projectName)throw Error('Backup runtime owner mismatch');return withRuntimeLock(ctx.directory,()=>writeBackup(ctx,target));
}
async function writeBackup(ctx,target){
 await fs.mkdir(target,{mode:0o700});assertOwnership(ctx.state,await inspectResources(ctx.state));await ctx.compose('stop',...['control-plane','worker','console','gateway-a','gateway-b','collector','prometheus','loki','tempo','backend-a','backend-b']);
 await ctx.compose('exec','-T','postgres','pg_dump','-U','webapi','-d','webapi','--format=custom','--file=/tmp/local-runtime.dump');const pg=(await inspectResources(ctx.state)).find(r=>r.Kind==='container'&&r.Config?.Labels?.['com.docker.compose.service']==='postgres');await docker(['cp',pg.Id+':/tmp/local-runtime.dump',path.join(target,'postgres.dump')]);await fs.chmod(path.join(target,'postgres.dump'),0o600);await ctx.compose('stop','postgres','redis');
 const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup`];for(const name of dataVolumes)args.push('--mount',`type=volume,src=${ctx.state.projectName}_${name},dst=/volumes/${name},readonly`);args.push(ctx.release.dependencyImages.sdk,'bash','-c','set -e; umask 077; for name in pg lkg-a lkg-b dp-keys prometheus-data loki-data tempo-data; do tar --numeric-owner -cf /backup/$name.tar -C /volumes/$name .; done');await docker(args);
 await fs.cp(path.join(ctx.directory,'secrets'),path.join(target,'secrets'),{recursive:true});await fs.copyFile(path.join(ctx.directory,'release.json'),path.join(target,'release.json'));await writePrivate(path.join(target,'runtime.json'),ctx.state);const hashes={};for(const file of ['postgres.dump',...dataVolumes.map(n=>n+'.tar'),'runtime.json','release.json']){await fs.chmod(path.join(target,file),0o600);hashes[file]=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');}for(const file of await fs.readdir(path.join(target,'secrets')))hashes['secrets/'+file]=createHash('sha256').update(await fs.readFile(path.join(target,'secrets',file))).digest('hex');await writePrivate(path.join(target,'backup-manifest.json'),{schemaVersion:1,sourceRevision:ctx.release.sourceRevision,files:hashes});return hashes;
}
export async function restoreColdBackup({target,projectName,directory,ports,contextFactory}){
 validateFixture(projectName,directory);if(await fs.lstat(directory).catch(e=>{if(e.code==='ENOENT')return null;throw e;}))throw Error('Restore requires a fresh disposable directory');
 const manifest=JSON.parse(await fs.readFile(path.join(target,'backup-manifest.json'),'utf8'));for(const[file,hash]of Object.entries(manifest.files)){if(path.isAbsolute(file)||file.split('/').includes('..'))throw Error('Invalid backup path');const actual=createHash('sha256').update(await fs.readFile(path.join(target,file))).digest('hex');if(actual!==hash)throw Error('Backup checksum mismatch');}
 const previous=JSON.parse(await fs.readFile(path.join(target,'runtime.json'),'utf8'));let state=await initializeState(directory,{projectName,ports,bootstrapUsername:previous.bootstrapUsername});state={...previous,ownerId:state.ownerId,projectName,ports};await saveState(directory,state);await fs.cp(path.join(target,'secrets'),path.join(directory,'secrets'),{recursive:true});await fs.copyFile(path.join(target,'release.json'),path.join(directory,'release.json'));const release=JSON.parse(await fs.readFile(path.join(directory,'release.json'),'utf8'));const ctx=await contextFactory(directory,state,release);await ctx.compose('run','--rm','--no-deps','init-volumes');assertOwnership(state,await inspectResources(state));
 const args=['run','--rm','--user','0:0','--mount',`type=bind,src=${target},dst=/backup,readonly`];for(const name of dataVolumes)args.push('--mount',`type=volume,src=${projectName}_${name},dst=/volumes/${name}`);args.push(release.dependencyImages.sdk,'bash','-c','set -e; for name in pg lkg-a lkg-b dp-keys prometheus-data loki-data tempo-data; do test -z "$(ls -A /volumes/$name)"; tar -xf /backup/$name.tar -C /volumes/$name; done');await docker(args);return{state,ctx,hashesVerified:true};
}
