import fs from'node:fs/promises';import path from'node:path';import net from'node:net';import{randomUUID,createHash}from'node:crypto';import{fileURLToPath}from'node:url';import assert from'node:assert/strict';
import{RuntimeError,writePrivate,loadState}from'./state.mjs';import{initializeRuntime,operateRuntime,loadRelease}from'./lifecycle.mjs';import{prepareContext}from'./context.mjs';import{docker,inspectResources,assertOwnership}from'./docker.mjs';import{getRuntimeStatus}from'./status.mjs';import{prepareScenario,exerciseScenario,until,pause}from'./acceptance-scenario.mjs';import{coldBackup,restoreColdBackup,dataVolumes}from'./acceptance-backup.mjs';import{LocalClient}from'../local-client.mjs';
import{startSampling}from'./resource-sampling.mjs';import{validateFixture}from'./fixture-guard.mjs';export{validateFixture}from'./fixture-guard.mjs';
const volumeNames=[...dataVolumes,'verification-reports','bootstrap-password','secrets-cache',...['postgres','control-plane','worker','gateway-a','gateway-b','migrator'].map(n=>'secrets-'+n)];
export function validateCleanupResources(state,resources){validateFixture(state.projectName,state.projectName);assertOwnership(state,resources);for(const r of resources)if(r.Kind==='volume'&&!volumeNames.some(n=>r.Name===state.projectName+'_'+n))throw new RuntimeError('Unexpected volume; refuse cleanup.',3);}
export function validateAcceptance(p){for(const key of ['chain','restart','failure','backupRestore'])if(p[key]?.passed!==true)throw Error('Missing actual '+key+' proof');if(!p.ui?.verified)throw Error('Missing actual UI proof');if(!p.preservedOldEnvironment?.unchanged)throw Error('Old environment preservation not verified');if(!p.cleanup||['containersRemaining','volumesRemaining','secretFilesRemaining'].some(k=>p.cleanup[k]!==0))throw Error('Disposable cleanup incomplete');return true;}
export function finalizeAcceptance(proof){try{validateAcceptance(proof);return{...proof,complete:true};}catch(e){return{...proof,complete:false,incompleteReason:e.message};}}
export async function freePorts(){const servers=await Promise.all([0,1,2].map(async()=>{const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));return s;}));const[console,gatewayA,gatewayB]=servers.map(s=>s.address().port);await Promise.all(servers.map(s=>new Promise(r=>s.close(r))));return{console,gatewayA,gatewayB};}
async function oldSnapshot(){const ids=(await docker(['ps','-aq','--filter','label=com.docker.compose.project=webapi-enterprise-core-test'])).stdout.trim().split(/\s+/).filter(Boolean);const containers=ids.length?JSON.parse((await docker(['inspect',...ids])).stdout).map(r=>({id:r.Id,name:r.Name,image:r.Image,running:r.State.Running,mounts:r.Mounts.map(m=>({name:m.Name??null,source:m.Source,destination:m.Destination})).sort((a,b)=>a.destination.localeCompare(b.destination))})).sort((a,b)=>a.name.localeCompare(b.name)):[];const endpoints={};for(const port of[4180,4181,5090]){try{endpoints[port]=(await fetch('http://127.0.0.1:'+port,{signal:AbortSignal.timeout(3000)})).status;}catch{endpoints[port]=null;}}const archives={};for(const dir of ['deliverables','..']){for(const name of await fs.readdir(dir)){if(name.endsWith('.zip'))archives[path.join(dir,name)]=createHash('sha256').update(await fs.readFile(path.join(dir,name))).digest('hex');}}return{containers,endpoints,archives};}
export async function cleanupFixture(directory,fallbackRelease){const state=await loadState(directory);validateFixture(state.projectName,directory);const resources=await inspectResources(state);validateCleanupResources(state,resources);const release=await loadRelease(path.join(directory,'release.json')).catch(e=>{if(e.code==='ENOENT'&&fallbackRelease)return fallbackRelease;throw e;});const ctx=await prepareContext(directory,state,release);await ctx.compose('--profile','tools','down','--volumes','--remove-orphans');const remaining=await inspectResources(state);validateCleanupResources(state,remaining);if(remaining.length)throw Error('Disposable resources remain');await fs.rm(directory,{recursive:true,force:true});return{containersRemaining:0,volumesRemaining:0,secretFilesRemaining:0};}
export async function runAcceptance({releaseManifest,directory,projectName,browser=false}){
 validateFixture(projectName,directory);const started=Date.now(),before=await oldSnapshot(),proof={complete:false,projectName,sourceRevision:releaseManifest.sourceRevision,classification:'actual-persistent-runtime-http-three-source-restart-and-cold-restore',limitations:['Linux ARM64 only','Short windows in disposable acceptance','No seven-day elapsed retention','No enterprise upstream/production TLS/HA/SLA/external notifications'],cleanup:null};let state,scenario,restoreDirectory,sampler;
 const override=path.join(directory,'acceptance-override.json');const contextFactory=async(d,s,r)=>{const ctx=await prepareContext(d,s,r);await writePrivate(override,{services:{worker:{environment:{Alerts__IntervalSeconds:'2',Alerts__QueryDelaySeconds:'5'}},'control-plane':{environment:{Observability__TraceSampleRatio:'1'}},...(s.binding?{'gateway-a':{environment:{Observability__TraceSampleRatio:'1',Observability__MetricExportIntervalMs:'1000'}},'gateway-b':{environment:{Observability__TraceSampleRatio:'1',Observability__MetricExportIntervalMs:'1000'}}}:{})}});ctx.files.push('-f',override);return ctx;};
 try{
  await fs.mkdir(path.dirname(directory),{recursive:true});const releaseFile=path.join(path.dirname(directory),projectName+'-release.json');await writePrivate(releaseFile,releaseManifest);
  try{state=await initializeRuntime({directory,projectName,bootstrapUsername:'runtime-qa-admin',ports:await freePorts(),releaseFile},{prepareContext:contextFactory});}finally{await fs.rm(releaseFile,{force:true});}
  sampler=startSampling(state);scenario=await prepareScenario(directory,state,contextFactory);state=scenario.state;let ctx=await contextFactory(directory,state,releaseManifest);await writePrivate(path.join(directory,'browser-context.json'),{consoleUrl:scenario.endpoint,username:state.bootstrapUsername,passwordFile:scenario.passwordFile,scope:scenario.scope});console.log('Runtime fixture context: '+path.join(directory,'browser-context.json'));
  console.log('Acceptance: real HTTP, telemetry and alert lifecycle');const exercised=await exerciseScenario(scenario,ctx);Object.assign(proof,exercised);console.log('Acceptance: restart, sessions and persistent histories');const prior=await getRuntimeStatus(state,{directory});await operateRuntime('stop',state,{directory,prepareContext:contextFactory});await operateRuntime('start',state,{directory,prepareContext:contextFactory});assert.equal((await scenario.admin.request('/auth/me')).username,state.bootstrapUsername);await ctx.compose('up','-d','--force-recreate','control-plane');await until(()=>scenario.admin.request('/auth/me'),r=>r.username===state.bootstrapUsername,30);
  const cookie=[...scenario.admin.cookies].map(([k,v])=>k+'='+v).join('; ');const csrf=await scenario.admin.request('/auth/csrf');for(const headers of[{Cookie:cookie,Origin:scenario.endpoint},{Cookie:cookie,Origin:'https://foreign.invalid','X-CSRF-Token':csrf.token}]){const r=await fetch(scenario.endpoint+'/api/v1/auth/logout',{method:'POST',headers});assert.equal(r.status,403);}for(const node of[0,1])assert.equal((await scenario.request(node)).status,200);const current=await until(()=>getRuntimeStatus(state,{directory}),r=>r.nodes.length===2&&r.nodes.every(n=>n.fresh&&n.currentVersion>0),30);assert.ok(current.nodes.every(n=>prior.nodes.find(p=>p.name===n.name).instanceId!==n.instanceId));
  const historical=await scenario.admin.request('/observability/traces/'+proof.history.traceId+'?'+new URLSearchParams(proof.history.fixedRange));assert.ok(historical.data.spans.length>0);const logs=await scenario.admin.request('/observability/logs?'+new URLSearchParams({...proof.history.fixedRange,traceId:proof.history.traceId}));assert.ok(logs.data.items.some(i=>i.traceId===proof.history.traceId));assert.equal((await scenario.admin.request('/observability/alert-rules/'+proof.history.ruleId)).id,proof.history.ruleId);assert.equal((await scenario.admin.request('/observability/alerts/'+proof.history.eventId)).status,'Resolved');
  await ctx.compose('restart','redis');const nextRelease=await scenario.publish();assert.equal((await getRuntimeStatus(state,{directory})).phase,'Ready');proof.failure.redisPublishRecovered=true;proof.restart={passed:true,sameCookieAfterControlPlaneRecreate:true,csrfAndForeignOriginRejected:true,newInstances:true,currentAckAfterNewApprovedRelease:true,newReleaseId:nextRelease.id,sourceHistoryRetained:true,ruleEventRetained:true};
  console.log('Acceptance: cold backup and fresh-project restore');const backup=path.join(directory,'backup');await coldBackup(ctx,backup);const restoredProject='webapi-enterprise-local-test-'+randomUUID();restoreDirectory=path.resolve('.runtime/tests/'+restoredProject);validateFixture(restoredProject,restoreDirectory);const restored=await restoreColdBackup({target:backup,projectName:restoredProject,directory:restoreDirectory,ports:await freePorts(),contextFactory});await operateRuntime('start',restored.state,{directory:restoreDirectory,prepareContext:contextFactory});const restoredClient=new LocalClient('http://127.0.0.1:'+restored.state.ports.console);await restoredClient.login(state.bootstrapUsername,scenario.password);assert.equal((await restoredClient.request('/environments/'+scenario.scope.environmentId)).id,scenario.scope.environmentId);assert.equal((await restoredClient.request('/observability/alert-rules/'+proof.history.ruleId)).id,proof.history.ruleId);const restoredEvent=await restoredClient.request('/observability/alerts/'+proof.history.eventId);assert.equal(restoredEvent.status,'Resolved');assert.ok(restoredEvent.transitions.some(t=>t.toStatus==='Ack'));const restoredTrace=await restoredClient.request('/observability/traces/'+proof.history.traceId+'?'+new URLSearchParams(proof.history.fixedRange));assert.ok(restoredTrace.data.spans.length>0);const restoredLog=await restoredClient.request('/observability/logs?'+new URLSearchParams({...proof.history.fixedRange,traceId:proof.history.traceId}));assert.ok(restoredLog.data.items.length>0);const credential=await fs.readFile(path.join(directory,'credential'),'utf8');for(const port of[restored.state.ports.gatewayA,restored.state.ports.gatewayB]){await until(async()=>{const r=await fetch('http://127.0.0.1:'+port+'/orders',{headers:{'X-API-Key':credential},signal:AbortSignal.timeout(10000)});await r.arrayBuffer();return r.status;},s=>s===200,30);}proof.backupRestore={passed:true,hashesVerified:restored.hashesVerified,pgLogicalDumpPresent:true,coldVolumesRestored:7,configurationRestored:true,sourceHistoryRestored:true,alertEventRestored:true,dualLkgTrafficRestored:true};await cleanupFixture(restoreDirectory);restoreDirectory=null;
  await operateRuntime('start',state,{directory,prepareContext:contextFactory});await scenario.reauthenticate();if(browser){console.log('Browser QA ready: '+scenario.endpoint);await writePrivate(path.join(directory,'browser-ready.json'),{ready:true,...scenario.scope,consoleUrl:scenario.endpoint});const deadline=Date.now()+1800000;while(!(await fs.stat(path.join(directory,'browser.done')).catch(()=>null))){if(Date.now()>deadline)throw Error('Browser QA completion timed out');await pause(1000);}proof.ui=JSON.parse(await fs.readFile(path.join(directory,'ui-proof.json'),'utf8'));}else proof.ui={verified:false,reason:'CUA browser QA required'};
 }catch(e){proof.failureReason=e.message;throw Object.assign(e,{proof});}
 finally{
  if(sampler)proof.resources=await sampler.stop();let cleanupError;try{if(restoreDirectory&&await fs.lstat(restoreDirectory).catch(()=>null))await cleanupFixture(restoreDirectory,releaseManifest);if(await fs.lstat(directory).catch(()=>null)){proof.cleanup=await cleanupFixture(directory,releaseManifest);}else proof.cleanup={containersRemaining:0,volumesRemaining:0,secretFilesRemaining:0};}catch(e){cleanupError=e;proof.cleanup={containersRemaining:null,volumesRemaining:null,secretFilesRemaining:null,error:e.message};}
  const after=await oldSnapshot();proof.preservedOldEnvironment={unchanged:JSON.stringify(before)===JSON.stringify(after),before,after};proof.elapsedSeconds=Math.round((Date.now()-started)/1000);const result=finalizeAcceptance(proof);await fs.mkdir('docs/evidence/local-runtime',{recursive:true});await fs.writeFile('docs/evidence/local-runtime/verification.json',JSON.stringify(result,null,2)+'\n');if(cleanupError)throw cleanupError;
 }
 return finalizeAcceptance(proof);
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const projectName='webapi-enterprise-local-test-'+randomUUID(),directory=path.resolve('.runtime/tests/'+projectName);try{const proof=await runAcceptance({releaseManifest:await loadRelease(path.resolve('.runtime/local-build/release.json')),projectName,directory,browser:process.argv.includes('--browser')});console.log('Runtime acceptance complete='+proof.complete);if(!proof.complete)process.exitCode=1;}catch(e){console.error('Runtime acceptance failed: '+e.message);process.exitCode=1;}}
