import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFile}from'node:child_process';import {promisify}from'node:util';import {createHash}from'node:crypto';import {fileURLToPath}from'node:url';
import {docker}from'./docker.mjs';import {RuntimeError,writePrivate,ownedDirectory}from'./state.mjs';
const exec=promisify(execFile);export const repository=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const applications={'control-plane':'WebApi.ControlPlane','worker':'WebApi.Worker','gateway':'WebApi.Gateway','console-host':'WebApi.ConsoleHost','migrator':'WebApi.Migrator','runtime-tool':'WebApi.RuntimeTool','demo-backend':'WebApi.TestBackend','notification-fixture':'WebApi.NotificationFixtureHost'};
export async function assertFrozenDependencies(archived,installed){for(const name of ['package.json','pnpm-lock.yaml'])if(!((await fs.readFile(path.join(archived,name))).equals(await fs.readFile(path.join(installed,name)))))throw new RuntimeError('Installed console dependencies differ from frozen archived lock.',6);}
async function buildConsole(source,publish,{nodePath=process.execPath,root=repository}={}){const console=path.join(source,'console');await assertFrozenDependencies(console,path.join(root,'console'));await fs.symlink(path.join(root,'console/node_modules'),path.join(console,'node_modules'),'dir');const env={...process.env,PATH:path.dirname(nodePath)+path.delimiter+process.env.PATH};await exec(nodePath,[path.join(root,'console/node_modules/typescript/bin/tsc'),'--noEmit'],{cwd:console,env});await exec(nodePath,[path.join(root,'console/node_modules/vite/bin/vite.js'),'build'],{cwd:console,env});await fs.cp(path.join(console,'dist'),path.join(publish,'console-dist'),{recursive:true});}
async function buildApplications(source,publish,{sdk,nugetSeedVolume}={}){
 const script=['set -eu','export DOTNET_CLI_TELEMETRY_OPTOUT=1','export NUGET_PACKAGES=/build/.nuget'];
 if(nugetSeedVolume)script.push('mkdir -p /build/.nuget; cp -a /nuget-seed/. /build/.nuget/');
 for(const [target,project]of Object.entries(applications)){const csproj=`${target==='notification-fixture'?'tests':'src'}/${project}/${project}.csproj`;script.push(`dotnet restore ${csproj} --locked-mode`, `dotnet publish ${csproj} --configuration Release --no-restore --output /build/publish/${target}`);}
 const args=['run','--rm','--workdir','/build/source','--mount',`type=bind,src=${path.dirname(source)},dst=/build`];if(nugetSeedVolume){if(!/^[a-zA-Z0-9_.-]+$/.test(nugetSeedVolume))throw new RuntimeError('Invalid NuGet seed volume.');args.push('--mount',`type=volume,src=${nugetSeedVolume},dst=/nuget-seed,readonly`);}args.push(sdk,'bash','-c',script.join('\n'));await docker(args);
}
async function buildImage(source,publish,{sdk,revision}={}){await fs.copyFile(path.join(source,'deploy/runtime/Dockerfile'),path.join(path.dirname(publish),'Dockerfile'));const imageTag='webapi-enterprise-runtime:'+revision;await docker(['build','--build-arg','SDK_IMAGE='+sdk,'--build-arg','SOURCE_REVISION='+revision,'--tag',imageTag,path.dirname(publish)]);const data=JSON.parse((await docker(['image','inspect',imageTag])).stdout)[0];if(data.Config.User!=='10001:10001'||data.Config.Labels?.['org.opencontainers.image.revision']!==revision)throw new RuntimeError('Runtime image identity/user validation failed.',6);return{imageTag,imageId:data.Id};}
async function hashes(directory,prefix='console/dist/'){const result={};for(const entry of await fs.readdir(directory,{withFileTypes:true})){const full=path.join(directory,entry.name);if(entry.isDirectory())Object.assign(result,await hashes(full,prefix+entry.name+'/'));else if(entry.isFile())result[prefix+entry.name]=createHash('sha256').update(await fs.readFile(full)).digest('hex');}return result;}
export async function buildRelease({revision,directory,root=repository,nodePath=process.execPath,nugetSeedVolume},deps={}){
 if(!revision||revision.startsWith('-'))throw new RuntimeError('Explicit immutable source revision required.',6);
 const sourceRevision=(await exec('git',['rev-parse',revision+'^{commit}'],{cwd:root})).stdout.trim();if(!/^[a-f0-9]{40}$/.test(sourceRevision))throw new RuntimeError('Cannot resolve immutable commit.',6);
 await fs.mkdir(directory,{recursive:true,mode:0o700});await ownedDirectory(directory);const temporary=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-local-build-'));try{const source=path.join(temporary,'source'),publish=path.join(temporary,'publish');await fs.mkdir(source);await fs.mkdir(publish);const archive=path.join(temporary,'source.tar');await exec('git',['archive','--output',archive,sourceRevision],{cwd:root});await exec('tar',['-xf',archive,'-C',source]);const dependencyImages=JSON.parse(await fs.readFile(path.join(source,'deploy/images.lock.json'),'utf8'));const options={root,nodePath,sdk:dependencyImages.sdk,revision:sourceRevision,nugetSeedVolume};
 await (deps.buildConsole??buildConsole)(source,publish,options);await(deps.buildApplications??buildApplications)(source,publish,options);const staticFiles=await hashes(path.join(publish,'console-dist'));const applicationFiles=await hashes(publish,'');const binaryFiles=Object.fromEntries(Object.entries(applicationFiles).filter(([name])=>name.endsWith('.dll')));await fs.writeFile(path.join(publish,'build-identity.json'),JSON.stringify({schemaVersion:1,sourceRevision,applications:binaryFiles,staticFiles})+'\n',{mode:0o644});const image=await(deps.buildImage??buildImage)(source,publish,options);if(!staticFiles['console/dist/index.html'])throw new RuntimeError('Missing console static build.',6);
 const result={schemaVersion:1,sourceRevision,createdAt:new Date().toISOString(),...image,dependencyImages,staticFiles,applications:binaryFiles,configVersion:1};await writePrivate(path.join(directory,'release.json'),result);return result;
 }finally{await fs.rm(temporary,{recursive:true,force:true});}
}
