import fs from'node:fs/promises';import path from'node:path';import{configureRuntime}from'./configure.mjs';import{getRuntimeStatus}from'./status.mjs';import{parseArgs}from'node:util';import{buildRelease}from'./build.mjs';import{initializeRuntime,operateRuntime,completeBootstrap}from'./lifecycle.mjs';import{loadState,RuntimeError}from'./state.mjs';
try{
 if(Number(process.versions.node.split('.')[0])<22)throw new RuntimeError('Node 22+ required.',3);
 const{values,positionals}=parseArgs({allowPositionals:true,options:{directory:{type:'string'},environment:{type:'string'},'origins-file':{type:'string'},username:{type:'string'},demo:{type:'boolean'},revision:{type:'string'},admin:{type:'string'},'password-file':{type:'string'},'release-file':{type:'string'},'nuget-seed-volume':{type:'string'},'credentials-saved':{type:'boolean'},json:{type:'boolean'},'console-port':{type:'string'},'gateway-a-port':{type:'string'},'gateway-b-port':{type:'string'}}});const command=positionals[0];if(positionals.length!==1)throw new RuntimeError('Usage: local-runtime.sh build|init|up|start|stop|restart|status|complete-bootstrap');const directory=path.resolve(values.directory??'.runtime/local');let result;
 if(command==='build')result=await buildRelease({revision:values.revision,directory:path.resolve('.runtime/local-build'),nugetSeedVolume:values['nuget-seed-volume']});
 else if(command==='init')result=await initializeRuntime({directory,bootstrapUsername:values.admin,passwordFile:values['password-file'],releaseFile:values['release-file'],ports:Object.fromEntries([['console','console-port'],['gatewayA','gateway-a-port'],['gatewayB','gateway-b-port']].filter(([,key])=>values[key]!==undefined).map(([name,key])=>[name,Number(values[key])]))});
 else if(['up','start','stop','restart'].includes(command))result=await operateRuntime(command,await loadState(directory),{directory});
 else if(command==='complete-bootstrap'){await completeBootstrap(await loadState(directory),{directory,credentialsSaved:values['credentials-saved']});result={bootstrapFileRemoved:true};}
 else if(command==='status')result=await getRuntimeStatus(await loadState(directory),{directory});
 else if(command==='configure'){if(!values['origins-file'])throw new RuntimeError('Explicit origins JSON file required.');result=await configureRuntime(await loadState(directory),{environmentId:values.environment,allowedOrigins:JSON.parse(await fs.readFile(values['origins-file'],'utf8')),username:values.username,passwordFile:values['password-file'],demoEnabled:values.demo},{directory});}
 else throw new RuntimeError('Unsupported command.');
 console.log(JSON.stringify(result,null,2));if(command==='init')console.log('Bootstrap password file (content not printed): '+path.join(directory,'secrets/bootstrap-password'));
}catch(e){console.error(e instanceof RuntimeError?e.message:'Local runtime operation failed; owned state retained.');process.exitCode=e.exitCode??6;}
