import {synchronizeConsoleProxyTrust} from '../security/proxy-trust.mjs';
import fs from'node:fs/promises';import path from'node:path';import{LocalClient}from'../local-client.mjs';import{RuntimeError,validGuid,validateOrigins,loadState,saveState,withRuntimeLock,safeFile,deploymentState}from'./state.mjs';import{prepareContext}from'./context.mjs';import{loadRelease,waitForRuntime,runtimeServices}from'./lifecycle.mjs';import{getRuntimeStatus}from'./status.mjs';
async function authenticate(state,{username,passwordFile}){if(!username||!passwordFile)throw new RuntimeError('Explicit login username and private password file required.',5);await safeFile(passwordFile);const password=(await fs.readFile(passwordFile,'utf8')).replace(/[\r\n]+$/,'');const origin='http://127.0.0.1:'+state.ports.console;const client=new LocalClient(origin);const request=client.request.bind(client);client.request=(url,options={})=>request(url,{...options,headers:{...options.headers,Origin:origin}});try{await client.login(username,password);}catch{throw new RuntimeError('Runtime authentication failed; credentials not logged.',5);}return client;}
export async function configureRuntime(state,options,{directory,...deps}={}){
 if(!validGuid(options.environmentId))throw new RuntimeError('Explicit non-empty environment GUID required.');validateOrigins(options.allowedOrigins);if(options.demoEnabled&&!['http://backend-a:8080','http://backend-b:8080'].every(x=>options.allowedOrigins.includes(x)))throw new RuntimeError('Demo requires both explicit backend origins.');
 return withRuntimeLock(directory,async()=>{let current=await loadState(directory);if(current.ownerId!==state.ownerId||!current.initialized)throw new RuntimeError('Runtime must be initialized and owned.',3);if((current.binding??current.pendingConfiguration?.binding)&&(current.binding??current.pendingConfiguration.binding).environmentId!==options.environmentId)throw new RuntimeError('Already bound to another environment; explicit migration required.',3);
 const client=await(deps.authenticate??authenticate)(current,options);let environment;try{environment=await client.request('/environments/'+options.environmentId);}catch{throw new RuntimeError('Environment is unavailable or unauthorized.',5);}if(environment.status!=='Active')throw new RuntimeError('Environment must be Active.',5);
 const next={...current,pendingConfiguration:{binding:{environmentId:options.environmentId,nodeNames:['local-gateway-a','local-gateway-b'],allowedOrigins:options.allowedOrigins},demoEnabled:!!options.demoEnabled},bindingPhase:'Validated'};await saveState(directory,next);current=next;const release=await(deps.loadRelease??loadRelease)(path.join(directory,'release.json'));const ctx=await(deps.prepareContext??prepareContext)(directory,current,release);
 const startedAt=Date.now();await ctx.compose('up','-d',...runtimeServices(current));if(ctx.securitySupported)await(deps.synchronizeProxy??synchronizeConsoleProxyTrust)(ctx);await(deps.wait??waitForRuntime)(ctx);const deadline=Date.now()+45000;let status;
 while(true){status=await(deps.getStatus??getRuntimeStatus)(current,{directory});if(status.environmentStatus&&status.environmentStatus!=='Active')throw new RuntimeError('Environment became inactive during registration.',5);if(status.nodes.some(n=>n.enabled===false))throw new RuntimeError('Bound node is disabled; registration not completed.',4);if(deploymentState(current).binding.nodeNames.every(name=>status.nodes.some(n=>n.name===name&&n.instanceId&&n.enabled&&n.fresh&&Date.parse(n.lastHeartbeatAt)>=startedAt-2000)))break;if(Date.now()>deadline)throw new RuntimeError('Gateway registration timed out; validated binding retained for retry.',4);await new Promise(r=>setTimeout(r,1000));}
 current={...current,...current.pendingConfiguration,pendingConfiguration:null,bindingPhase:'Applied'};await saveState(directory,current);return current;
 });
}
