import{loadSsoDeployment,ssoOverlay,assertSsoSecretVolume}from'./sso-deployment.mjs';
import fs from'node:fs/promises';import path from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import{repository}from'./build.mjs';import{ownedDocker,docker}from'./docker.mjs';import{writePrivate,RuntimeError,ownedDirectory,deploymentState}from'./state.mjs';
const exec=promisify(execFile);
export async function prepareContext(directory,state,release){
 state=deploymentState(state);directory=await ownedDirectory(directory);if(!/^[a-f0-9]{40}$/.test(release.sourceRevision)||!/^sha256:[a-f0-9]{64}$/.test(release.imageId))throw new RuntimeError('Invalid immutable runtime release.',6);
 const snapshot=path.join(directory,'artifacts',release.sourceRevision);try{await fs.access(path.join(snapshot,'deploy/compose.runtime.yml'));}catch{await fs.mkdir(snapshot,{recursive:true});const archive=path.join(directory,'deployment.tar');await exec('git',['archive','--output',archive,release.sourceRevision,'deploy'],{cwd:repository});await exec('tar',['-xf',archive,'-C',snapshot]);await fs.unlink(archive);}
 const env={...process.env,WEBAPI_RUNTIME_PROJECT:state.projectName,WEBAPI_RUNTIME_OWNER:state.ownerId,WEBAPI_RUNTIME_IMAGE:release.imageId,WEBAPI_RUNTIME_SECRET_DIRECTORY:path.join(directory,'secrets'),WEBAPI_RUNTIME_CONSOLE_PORT:String(state.ports.console),WEBAPI_RUNTIME_GATEWAY_A_PORT:String(state.ports.gatewayA),WEBAPI_RUNTIME_GATEWAY_B_PORT:String(state.ports.gatewayB),...(state.binding?{WEBAPI_RUNTIME_ENVIRONMENT_ID:state.binding.environmentId}:{})};
 const services={};for(const name of ['control-plane','worker',...(state.binding?['gateway-a','gateway-b']:[])]){const environment={};for(const [i,origin]of(state.binding?.allowedOrigins??[]).entries())environment['Upstream__AllowedOrigins__'+i]=origin;services[name]={environment};}
 services['control-plane'].environment.Authentication__CookieName='WebApi.Local.'+state.ownerId+'.Session';services['control-plane'].environment.Antiforgery__CookieName='WebApi.Local.'+state.ownerId+'.Csrf';
 const sso=await loadSsoDeployment(directory,state),overlay=ssoOverlay(sso);if(sso?.enabled){const base=JSON.parse(await fs.readFile(path.join(snapshot,'deploy/compose.runtime.yml'),'utf8'));if(base.services?.['control-plane']?.environment?.ASPNETCORE_ENVIRONMENT!=='Development')throw new RuntimeError('Local SSO HTTP requires Development.');Object.assign(services['control-plane'].environment,overlay.environment);services['control-plane'].volumes=overlay.volumes;}
 const settings=path.join(directory,'runtime-config.json');await writePrivate(settings,{services,...(sso?.enabled?{volumes:{'sso-client-secret':{external:true,name:sso.idp.secretVolume}}}:{})});const files=['compose.runtime.yml',...(state.binding?['compose.runtime.gateways.yml']:[]),...(state.demoEnabled?['compose.runtime.demo.yml']:[])].flatMap(name=>['-f',path.join(snapshot,'deploy',name)]);files.push('-f',settings);
 return{directory,state,release,env,files,compose:async(...args)=>{if(!['stop','down','ps','logs','config'].includes(args.find(a=>['up','run','create','start','restart','exec','stop','down','ps','logs','config'].includes(a))))await assertSsoSecretVolume(sso);return ownedDocker(state,['compose','-p',state.projectName,...files,...args],{env});},raw:async(args,options={})=>{await assertSsoSecretVolume(sso);return docker(['compose','-p',state.projectName,...files,...args],{env,...options});}};
}
