import {prepareLoginProtectionSecret,assertLoginProtectionSecretVolume} from '../security/runtime-secrets.mjs';
import {consoleProxyReceiptName,verifyConsoleProxyTrust} from '../security/proxy-trust.mjs';
import {notificationContext,assertNotificationSecretVolumes} from '../notifications/fixture.mjs';
import {ensureCacheSecret,assertCacheSecretVolume} from '../gateway-policies/runtime-secrets.mjs';
import{loadSsoDeployment,ssoOverlay,assertSsoSecretVolume}from'./sso-deployment.mjs';
import fs from'node:fs/promises';import path from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import{repository}from'./build.mjs';import{ownedDocker,docker}from'./docker.mjs';import{writePrivate,RuntimeError,ownedDirectory,deploymentState}from'./state.mjs';
const exec=promisify(execFile);
export async function prepareContext(directory,state,release){
 state=deploymentState(state);directory=await ownedDirectory(directory);if(!/^[a-f0-9]{40}$/.test(release.sourceRevision)||!/^sha256:[a-f0-9]{64}$/.test(release.imageId))throw new RuntimeError('Invalid immutable runtime release.',6);
 const snapshot=path.join(directory,'artifacts',release.sourceRevision);try{await fs.access(path.join(snapshot,'deploy/compose.runtime.yml'));}catch{await fs.mkdir(snapshot,{recursive:true});const archive=path.join(directory,'deployment.tar');const gitRoot=(await exec('git',['rev-parse','--show-toplevel'],{cwd:repository})).stdout.trim();await exec('git',['archive','--output',archive,release.sourceRevision,'deploy'],{cwd:gitRoot});await exec('tar',['-xf',archive,'-C',snapshot]);await fs.unlink(archive);}
 const deployDefinition=JSON.parse(await fs.readFile(path.join(snapshot,'deploy/compose.runtime.yml'),'utf8')),reportsSupported=!!deployDefinition.volumes?.['verification-reports'],cacheSupported=!!deployDefinition.volumes?.['secrets-cache'],cache=cacheSupported?await ensureCacheSecret(directory,state):null;
 const securitySupported=deployDefinition.services?.['control-plane']?.environment?.Authentication__LoginProtection__HmacSecretFile==='/run/secrets/login-protection-hmac';
 const loginProtection=securitySupported?await prepareLoginProtectionSecret(directory,state,{allowCreate:!state.initialized}):null;
 const env={...process.env,WEBAPI_RUNTIME_PROJECT:state.projectName,WEBAPI_RUNTIME_OWNER:state.ownerId,WEBAPI_RUNTIME_IMAGE:release.imageId,WEBAPI_RUNTIME_SECRET_DIRECTORY:path.join(directory,'secrets'),WEBAPI_RUNTIME_CONSOLE_PORT:String(state.ports.console),WEBAPI_RUNTIME_GATEWAY_A_PORT:String(state.ports.gatewayA),WEBAPI_RUNTIME_GATEWAY_B_PORT:String(state.ports.gatewayB),...(state.binding?{WEBAPI_RUNTIME_ENVIRONMENT_ID:state.binding.environmentId}:{})};
 const nc=await notificationContext(directory,state,release);Object.assign(env,nc.env??{});
 const services={};for(const name of ['control-plane','worker',...(state.binding?['gateway-a','gateway-b']:[])]){const environment={};for(const [i,origin]of(state.binding?.allowedOrigins??[]).entries())environment['Upstream__AllowedOrigins__'+i]=origin;services[name]={environment};}
 services['control-plane'].environment.Authentication__CookieName='WebApi.Local.'+state.ownerId+'.Session';services['control-plane'].environment.Antiforgery__CookieName='WebApi.Local.'+state.ownerId+'.Csrf';
 if(securitySupported){services['control-plane'].environment.Authentication__LoginProtection__RedisPrefix='webapi:login:'+state.ownerId;try{const proxy=JSON.parse(await fs.readFile(path.join(directory,consoleProxyReceiptName),'utf8'));if(proxy.ownerId===state.ownerId&&proxy.projectName===state.projectName&&await verifyConsoleProxyTrust(state,proxy))services['control-plane'].environment.HttpSecurity__TrustedProxyIps__0=proxy.ipAddress;}catch(e){if(e.code!=='ENOENT')throw e;}}
 const sso=await loadSsoDeployment(directory,state),overlay=ssoOverlay(sso);if(sso?.enabled){const base=JSON.parse(await fs.readFile(path.join(snapshot,'deploy/compose.runtime.yml'),'utf8'));if(base.services?.['control-plane']?.environment?.ASPNETCORE_ENVIRONMENT!=='Development')throw new RuntimeError('Local SSO HTTP requires Development.');Object.assign(services['control-plane'].environment,overlay.environment);services['control-plane'].volumes=overlay.volumes;}
 if(nc.notification)for(const name of ['control-plane','worker'])Object.assign(services[name].environment,nc.environment);
 const settings=path.join(directory,'runtime-config.json');await writePrivate(settings,{services,...(sso?.enabled?{volumes:{'sso-client-secret':{external:true,name:sso.idp.secretVolume}}}:{})});const files=['compose.runtime.yml',...(state.binding?['compose.runtime.gateways.yml']:[]),...(state.demoEnabled?['compose.runtime.demo.yml']:[]),...(nc.notification?['compose.notifications-demo.yml']:[])].flatMap(name=>['-f',path.join(snapshot,'deploy',name)]);files.push('-f',settings);
 return{directory,state,release,env,files,reportsSupported,cacheSupported,securitySupported,loginProtection,notification:nc.notification,compose:async(...args)=>{if(!['stop','down','ps','logs','config'].includes(args.find(a=>['up','run','create','start','restart','exec','stop','down','ps','logs','config'].includes(a))))await assertSsoSecretVolume(sso);if(nc.notification&&!args.includes('init-notification-volumes')&&!args.includes('init-volumes')&&!['stop','down','ps','logs','config'].includes(args[0]))await assertNotificationSecretVolumes(state,nc.receipt,release.dependencyImages?.sdk);if(loginProtection&&!args.includes('init-volumes')&&!['stop','down','ps','logs','config'].includes(args[0]))await assertLoginProtectionSecretVolume(state,loginProtection.receipt,release.dependencyImages?.sdk);if(cache&&!args.includes('init-volumes')&&!['stop','down','ps','logs','config'].includes(args[0]))await assertCacheSecretVolume(state,cache.receipt,release.dependencyImages?.sdk);return ownedDocker(state,['compose','-p',state.projectName,...files,...args],{env});},raw:async(args,options={})=>{await assertSsoSecretVolume(sso);if(nc.notification)await assertNotificationSecretVolumes(state,nc.receipt,release.dependencyImages?.sdk);if(loginProtection)await assertLoginProtectionSecretVolume(state,loginProtection.receipt,release.dependencyImages?.sdk);if(cache)await assertCacheSecretVolume(state,cache.receipt,release.dependencyImages?.sdk);return docker(['compose','-p',state.projectName,...files,...args],{env,...options});}};
}
