import fs from'node:fs/promises';import path from'node:path';import net from'node:net';import{randomBytes}from'node:crypto';
import{RuntimeError,initializeState,loadState,saveState,withRuntimeLock,safeFile,writePrivate,ownedDirectory}from'./state.mjs';import{inspectResources,assertOwnership,docker}from'./docker.mjs';import{prepareContext}from'./context.mjs';
const secretNames=['postgres-password','node-a','node-b','ip-hmac','cursor-signing'];
export const runtimeServices=state=>['postgres','redis','collector','prometheus','loki','tempo','control-plane','worker','console',...(state.binding?['gateway-a','gateway-b']:[]),...(state.demoEnabled?['backend-a','backend-b']:[])];
export async function assertPorts(state,{inspect=inspectResources}={}){const resources=await inspect(state);assertOwnership(state,resources);const owned=new Set(resources.flatMap(r=>Object.values(r.NetworkSettings?.Ports??{}).flatMap(v=>v??[]).filter(p=>p.HostIp==='127.0.0.1').map(p=>Number(p.HostPort))));for(const port of Object.values(state.ports)){if(owned.has(port))continue;await new Promise((resolve,reject)=>{const socket=net.createServer();socket.once('error',()=>reject(new RuntimeError('Runtime port '+port+' is occupied or unavailable; no owner was stopped.',3)));socket.listen(port,'127.0.0.1',()=>socket.close(resolve));});}}
export async function loadRelease(file){await safeFile(file);const r=JSON.parse(await fs.readFile(file,'utf8'));if(r.schemaVersion!==1||r.configVersion!==1||!/^sha256:[a-f0-9]{64}$/.test(r.imageId)||!/^[a-f0-9]{40}$/.test(r.sourceRevision))throw new RuntimeError('Invalid release manifest.',6);return r;}
async function prepareSecrets(directory,state,passwordFile){
 const dir=path.join(directory,'secrets');let fresh=false;
 try{await fs.lstat(dir);}catch(e){if(e.code!=='ENOENT')throw e;fresh=true;}
 if(fresh){let password=randomBytes(32).toString('base64');if(passwordFile){await safeFile(passwordFile);password=(await fs.readFile(passwordFile,'utf8')).replace(/[\r\n]+$/,'');if(password.length<16||password.length>1024)throw new RuntimeError('Bootstrap password must contain 16–1024 characters.');}await fs.mkdir(dir,{mode:0o700});for(const name of secretNames)await fs.writeFile(path.join(dir,name),randomBytes(32).toString('base64')+'\n',{mode:0o600,flag:'wx'});await fs.writeFile(path.join(dir,'bootstrap-password'),password+'\n',{mode:0o600,flag:'wx'});}
 await ownedDirectory(dir);for(const name of secretNames)await safeFile(path.join(dir,name));if(!state.initialized)await safeFile(path.join(dir,'bootstrap-password'));
}
export async function removeBootstrapVolume(state){const name=state.projectName+'_bootstrap-password',resources=await inspectResources(state);assertOwnership(state,resources);const volume=resources.find(r=>r.Kind==='volume'&&r.Name===name);if(volume)await docker(['volume','rm',name]);}
export async function waitForRuntime(ctx){const end=Date.now()+180000;const pause=()=>new Promise(r=>setTimeout(r,1000));while(true){try{const response=await fetch('http://127.0.0.1:'+ctx.state.ports.console+'/api/v1/auth/csrf',{signal:AbortSignal.timeout(5000)});if(response.ok&&(await response.json()).token)break;}catch{}if(Date.now()>end)throw new RuntimeError('Console/management startup timed out.',4);await pause();}
 const urls=['http://collector:13133','http://prometheus:9090/-/ready','http://loki:3100/ready','http://tempo:3200/ready'];for(const url of urls){while(true){const probe=await ctx.raw(['run','--rm','--no-deps','--entrypoint','dotnet','console','/app/runtime-tool/WebApi.RuntimeTool.dll','probe',url],{allowFailure:true});if(probe.exitCode===0)break;if(Date.now()>end)throw new RuntimeError('Observation source startup timed out: '+new URL(url).hostname,4);await pause();}}
}
export async function initializeRuntime(options,deps={}){
 const directory=path.resolve(options.directory);let state;try{state=await loadState(directory);}catch(e){if(e.code!=='ENOENT')throw e;state=await initializeState(directory,options);}if(state.bootstrapUsername!==options.bootstrapUsername)throw new RuntimeError('Cannot change initialized administrator username.',3);
 return withRuntimeLock(directory,async()=>{state=await loadState(directory);await(deps.assertPorts??assertPorts)(state);const releaseFile=options.releaseFile??(state.initialized?path.join(directory,'release.json'):path.resolve('.runtime/local-build/release.json'));const release=await(deps.loadRelease??loadRelease)(releaseFile);await prepareSecrets(directory,state,options.passwordFile);const ctx=await(deps.prepareContext??prepareContext)(directory,state,release);
 await ctx.compose('run','--rm','--no-deps','init-volumes');await ctx.compose('up','-d','--wait','postgres','redis');const args=['run','--rm','--no-deps'];if(!state.initialized)args.push('-e','WEBAPI_BOOTSTRAP_USERNAME='+state.bootstrapUsername,'-e','WEBAPI_BOOTSTRAP_PASSWORD_FILE=/run/bootstrap/password','--volume',state.projectName+'_bootstrap-password:/run/bootstrap:ro');args.push('migrator');if(!state.initialized)args.push('dotnet','/app/migrator/WebApi.Migrator.dll','--bootstrap');await ctx.compose(...args);
 state={...state,initialized:true,releaseId:release.sourceRevision};await writePrivate(path.join(directory,'release.json'),release);await saveState(directory,state);await(deps.removeBootstrapVolume??removeBootstrapVolume)(state);await ctx.compose('up','-d',...runtimeServices(state));await(deps.wait??waitForRuntime)(ctx);return state;});
}
export async function operateRuntime(operation,state,{directory,...deps}={}){if(!['up','start','stop','restart'].includes(operation))throw new RuntimeError('Unsupported lifecycle operation.');directory=path.resolve(directory);return withRuntimeLock(directory,async()=>{const current=await loadState(directory);if(current.ownerId!==state.ownerId)throw new RuntimeError('Runtime owner changed.',3);if(!current.initialized)throw new RuntimeError('Initialize runtime before operating it.',3);if(operation!=='stop')await(deps.assertPorts??assertPorts)(current);const release=await(deps.loadRelease??loadRelease)(path.join(directory,'release.json'));const ctx=await(deps.prepareContext??prepareContext)(directory,current,release);if(operation==='stop'){await ctx.compose('stop');return{phase:'Stopped'};}await ctx.compose('up','-d',...runtimeServices(current));if(operation==='restart')await ctx.compose('restart',...runtimeServices(current));await(deps.wait??waitForRuntime)(ctx);return{phase:current.binding?'Registered':'Unconfigured'};});}
export async function completeBootstrap(state,{directory,credentialsSaved}={}){if(!credentialsSaved)throw new RuntimeError('Confirm credentials saved before removing bootstrap file.');return withRuntimeLock(directory,async()=>{const current=await loadState(directory);if(!current.initialized||current.ownerId!==state.ownerId)throw new RuntimeError('Runtime must be initialized and owned.',3);const file=path.join(directory,'secrets/bootstrap-password');try{await safeFile(file);await fs.unlink(file);}catch(e){if(e.code!=='ENOENT')throw e;}});}
