import {assertLoginProtectionSecret,loginProtectionReceiptName} from '../security/runtime-secrets.mjs';
import {verifyConsoleProxyTrust,consoleProxyReceiptName} from '../security/proxy-trust.mjs';
import {loadNotificationRuntime} from '../notifications/runtime-secrets.mjs';
import {deriveNotificationStatus,fixtureRequest} from '../notifications/fixture.mjs';
import fs from'node:fs/promises';import path from'node:path';import{inspectResources,assertOwnership,docker}from'./docker.mjs';import{runtimeServices,loadRelease}from'./lifecycle.mjs';import{validGuid,RuntimeError,deploymentState}from'./state.mjs';
export function deriveRuntimeStatus(state,{services,sources,nodes,storage=[],environmentStatus=null,errors=[],loginProtection={supported:false,state:'Legacy'}}){
 const base={schemaVersion:1,projectName:state.projectName,sourceRevision:state.releaseId,bindingPhase:state.bindingPhase??null,pendingConfiguration:state.pendingConfiguration??null,services,sources,nodes,storage,environmentStatus,errors,loginProtection};const running=services.every(s=>s.state==='Running'&&s.health!=='unhealthy');
 if(!services.some(s=>s.state==='Running'))return{...base,phase:'Stopped'};
 if(!running||sources.some(s=>s.state!=='Available'))return{...base,phase:'Degraded'};
 if(state.pendingConfiguration||state.bindingPhase==='Validated')return{...base,phase:'Degraded'};
 if(loginProtection.supported&&loginProtection.state!=='Ready')return{...base,phase:'Degraded'};
 if(!state.binding)return{...base,phase:'Unconfigured'};
 if(environmentStatus!=='Active')return{...base,phase:'Degraded'};
 if(nodes.length!==2)return{...base,phase:'Degraded'};
 if(nodes.every(n=>n.currentVersion===0&&n.enabled&&n.fresh))return{...base,phase:'Registered'};
 const ready=nodes.length===2&&nodes.every(n=>n.instanceId&&n.enabled&&n.fresh&&n.reportedStatus==='Ready'&&n.desiredVersion>0&&n.currentVersion===n.desiredVersion&&n.currentSequence===n.desiredSequence&&n.acknowledged);
 return{...base,phase:ready?'Ready':'Degraded'};
}
export async function getRuntimeStatus(state,{directory,inspect=inspectResources,run=docker}={}){
 state=deploymentState(state);const resources=await inspect(state,run);assertOwnership(state,resources);const containers=resources.filter(r=>r.Kind==='container'&&r.Config?.Labels?.['com.docker.compose.oneoff']!=='True');const get=name=>containers.find(r=>r.Config?.Labels?.['com.docker.compose.service']===name);
 const notification=directory?await loadNotificationRuntime(directory,state):null;const services=runtimeServices(state,notification).map(name=>{const r=get(name);return{name,state:r?.State?.Running?'Running':r?.State?.Status??'Missing',health:r?.State?.Health?.Status??null};});const console=get('console'),pg=get('postgres');const errors=[];
 const sources=await Promise.all([['collector','http://collector:13133'],['prometheus','http://prometheus:9090/-/ready'],['loki','http://loki:3100/ready'],['tempo','http://tempo:3200/ready']].map(async([name,url])=>{if(!console?.State?.Running)return{name,state:'Unknown',checkedAt:new Date().toISOString(),reason:'Console diagnostic process unavailable'};try{const result=await run(['exec',console.Id,'dotnet','/app/runtime-tool/WebApi.RuntimeTool.dll','probe',url],{allowFailure:true});return{name,state:result.exitCode===0?'Available':'Unavailable',checkedAt:new Date().toISOString()};}catch{return{name,state:'Unknown',checkedAt:new Date().toISOString(),reason:'Diagnostic request failed'};}}));
 let nodes=[],environmentStatus=null;
 if(state.binding&&pg?.State?.Running){if(!validGuid(state.binding.environmentId))throw new RuntimeError('Invalid bound environment.');const id=state.binding.environmentId;
 const publicationAck=`exists(select 1 from gateway_acks a where a.node_id=n.id and a.instance_id=n.instance_id and a.config_version=e.desired_config_version and a.deployment_sequence=e.deployment_sequence and a.success)`;
 // The independent receipt is useful only for this instance and the exact current successful snapshot.
 // Compare JSONB values without casts: malformed types/missing metadata fail closed, never break status.
 const receipt=`exists(select 1 from release_records r join gateway_config_versions v on v.environment_id=r.environment_id and v.version_no=r.to_config_version where r.environment_id=e.id and r.to_config_version=e.desired_config_version and r.deployment_sequence=e.deployment_sequence and r.status='Succeeded' and v.status='Published' and n.metadata->'runtimeApplication'->'schemaVersion'='1'::jsonb and n.metadata->'runtimeApplication'->'instanceId'=to_jsonb(n.instance_id) and n.metadata->'runtimeApplication'->'releaseId'=to_jsonb(r.id::text) and n.metadata->'runtimeApplication'->'configVersion'=to_jsonb(e.desired_config_version) and n.metadata->'runtimeApplication'->'deploymentSequence'=to_jsonb(e.deployment_sequence) and n.metadata->'runtimeApplication'->'payloadHash'=to_jsonb(v.snapshot_hash))`;
 const sql=`select json_build_object('environmentStatus',e.status,'nodes',coalesce((select json_agg(json_build_object('name',n.node_name,'instanceId',n.instance_id,'enabled',n.enabled,'reportedStatus',n.status,'lastHeartbeatAt',n.last_heartbeat_at,'fresh',coalesce(n.last_heartbeat_at>now()-interval '120 seconds',false),'currentVersion',n.current_config_version,'currentSequence',n.current_deployment_sequence,'desiredVersion',e.desired_config_version,'desiredSequence',e.deployment_sequence,'publicationAcknowledged',${publicationAck},'runtimeConfirmed',${receipt},'acknowledged',(${publicationAck} or ${receipt}))) from gateway_nodes n where n.environment_id=e.id and n.node_name in ('local-gateway-a','local-gateway-b')),'[]'::json)) from environments e where e.id='${id}'::uuid`;
 try{const result=await run(['exec',pg.Id,'psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',sql]);if(result.stdout.trim()){const body=JSON.parse(result.stdout.trim());nodes=body.nodes;environmentStatus=body.environmentStatus;}else errors.push('Bound environment is missing');}catch{errors.push('Node state unavailable; no readiness inferred');}}
 const storage=await Promise.all(resources.filter(r=>r.Kind==='volume'&&['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data'].some(v=>r.Name===state.projectName+'_'+v)).map(async r=>{const mounted=containers.find(c=>c.State?.Running&&c.Mounts?.some(m=>m.Name===r.Name));const mount=mounted?.Mounts.find(m=>m.Name===r.Name);let bytesUsed=null,reason=null;try{if(!mounted||!mount)throw Error();const result=await run(['exec',mounted.Id,'du','-sb',mount.Destination],{allowFailure:true});if(result.exitCode!==0)throw Error();bytesUsed=Number(result.stdout.trim().split(/\s+/)[0]);if(!Number.isFinite(bytesUsed))throw Error();}catch{reason='Volume usage unavailable for this service image/state';bytesUsed=null;}return{name:r.Name,volumeId:r.Name,bytesUsed,reason};}));
 let notificationStatus=deriveNotificationStatus(notification);if(notification){let fixture=null,channels=[];try{fixture=await fixtureRequest(directory,state,'/owner/observations');}catch{errors.push('Notification fixture identity unavailable; no send success inferred');}if(pg?.State?.Running)try{const rows=await run(['exec',pg.Id,'psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',"select coalesce(json_agg(json_build_object('channel',channel,'configured',profile_id is not null,'enabled',enabled)),'[]'::json) from notification_channel_states"]);channels=JSON.parse(rows.stdout.trim());}catch{errors.push('Notification channel configuration unavailable');}notificationStatus=deriveNotificationStatus(notification,{fixture,channels});}
 let loginProtection={supported:false,state:'Legacy'};
 if(directory){try{const release=await loadRelease(path.join(directory,'release.json'));const definition=JSON.parse(await fs.readFile(path.join(directory,'artifacts',release.sourceRevision,'deploy/compose.runtime.yml'),'utf8'));if(definition.services?.['control-plane']?.environment?.Authentication__LoginProtection__HmacSecretFile){loginProtection={supported:true,state:'Unknown'};const secret=await assertLoginProtectionSecret(directory,state),receipt=JSON.parse(await fs.readFile(path.join(directory,consoleProxyReceiptName),'utf8')),cp=get('control-plane');const trust=receipt.ownerId===state.ownerId&&receipt.projectName===state.projectName&&await verifyConsoleProxyTrust(state,receipt,{inspect:async()=>resources});let mounted=false;if(cp?.State?.Running){const result=await run(['exec',cp.Id,'sha256sum','/run/secrets/login-protection-hmac'],{allowFailure:true});mounted=result.exitCode===0&&result.stdout.trim().split(/\s+/)[0]===secret.receipt.sha256;}loginProtection={supported:true,state:trust&&mounted?'Ready':'Degraded',proxyTrusted:trust,secretMounted:mounted};}}catch{loginProtection={supported:true,state:'Unknown'};errors.push('Login protection state unavailable; no readiness inferred');}}
 return {...deriveRuntimeStatus(state,{services,sources,nodes,storage,environmentStatus,errors,loginProtection}),notifications:notificationStatus};
}
