// Synthetic unit vectors only: never saved as acceptance screenshots or real protocol proof.
import {randomUUID,createHash} from 'node:crypto';import {deflateSync} from 'node:zlib';
import {requiredNotificationChecks,requiredNotificationUiActions,notificationCheckExpectations} from '../../scripts/notifications/evidence.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function png(width,index){const height=600;const chunk=(name,data)=>{const out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);out.write(name,4);data.copy(out,8);let crc=0xffffffff;for(const b of out.subarray(4,-4)){crc^=b;for(let bit=0;bit<8;bit++)crc=crc>>>1^((crc&1)?0xedb88320:0);}out.writeUInt32BE((crc^0xffffffff)>>>0,out.length-4);return out;};const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=2;const pixels=Buffer.alloc(height*(width*3+1));pixels[1]=index+1;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
export function validVector(){
 const revision='a'.repeat(40),imageId='sha256:'+'b'.repeat(64),identity={sourceRevision:revision,imageId},ownerId=randomUUID(),projectName='webapi-enterprise-local-test-'+randomUUID(),staticFiles={'console/dist/assets/unit.js':'f'.repeat(64)};
 const proof={schemaVersion:1,...identity,clone:{actual:true,ownerVerified:true,projectName,ownerId,consolePort:57531},fixture:{actual:true,ownerVerified:true,...identity,host:'notification-fixture',tls:true,observation:'fixture.json'},checks:[],protocol:{smtp:[{deliveryId:randomUUID(),recipientCount:1,ccCount:0,bccCount:0,tls:true,authenticated:true,accepted:true,replyCode:250,bodyHash:'d'.repeat(64)}],webhook:[{deliveryId:randomUUID(),signatureValid:true,tls:true,remoteAccepted:true,replyCode:202,bodyHash:'d'.repeat(64)}]},runtime:{observation:'runtime.json',backupVolumes:['dp-keys','notification-secrets','notification-fixture-secrets','notification-fixture-data'],oldToolsUnchanged:true},backup:{observation:'cold-recovery.json',manifest:'cold-backup-manifest.json'},ui:{...identity,viewports:[1440,1280],actions:[]},manifest:[]};const files=[];
 const add=(path,value)=>{const content=Buffer.isBuffer(value)?value:Buffer.from(JSON.stringify(value));const file={path,content,sha256:sha(content)};files.push(file);proof.manifest.push({path,sha256:file.sha256});return file;};
 add('runtime.json',{...identity,ownerId,projectName,imageLabel:revision,originalConsolePort:4192,backupVolumes:proof.runtime.backupVolumes,staticFiles,historicalTools:Object.fromEntries(['manage.sh','tooling.json','manage-policies.sh','policy-tooling.json'].map(n=>[n,{before:'a'.repeat(64),after:'a'.repeat(64)}]))});
 add('fixture.json',{...identity,ownerId,projectName,binaryVerified:true,binaryHash:'e'.repeat(64),protocol:proof.protocol});
 const volumes=['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data','secrets-cache','notification-secrets','notification-fixture-secrets','notification-fixture-data'];const manifest={schemaVersion:1,sourceRevision:revision,files:Object.fromEntries(volumes.map(v=>[v+'.tar','a'.repeat(64)]))};const mf=add('cold-backup-manifest.json',manifest);const secretHashes=Object.fromEntries(['sender/smtp.json','sender/webhook.json','sender/ca.crt','fixture/smtp.json','fixture/webhook.json','fixture/server.crt','fixture/server.key','fixture/owner-token'].map(n=>[n,'b'.repeat(64)]));add('cold-recovery.json',{...identity,source:'actual-clone',ownerId,projectName,manifestSha256:mf.sha256,manifestFilesVerified:volumes.length,volumes,finallyReady:true,restore:{...identity,actual:true,ownerVerified:true,ownerId:randomUUID(),projectName:'webapi-enterprise-local-test-'+randomUUID(),consolePort:57541,fixtureBinaryVerified:true,fixtureProtocolBefore:'c'.repeat(64),fixtureProtocolAfter:'c'.repeat(64),dpKeysBefore:{'key-unit.xml':'d'.repeat(64)},dpKeysAfter:{'key-unit.xml':'d'.repeat(64)},secretHashesBefore:secretHashes,secretHashesAfter:secretHashes,finallyReady:true}});
 for(const id of requiredNotificationChecks){proof.checks.push({id,passed:true,...identity,observation:id+'.json'});add(id+'.json',{...identity,id,source:'actual-clone',serviceResponse:true,actual:notificationCheckExpectations[id],expected:notificationCheckExpectations[id]});}
 requiredNotificationUiActions.forEach((id,index)=>{const viewport=index===1?1280:1440,file=add(id+'.png',png(viewport,index));proof.ui.actions.push({id,passed:true,...identity,viewport,screenshot:file.path,observation:id+'-ui.json'});add(id+'-ui.json',{...identity,id,source:'cua',viewport,screenshotSha256:file.sha256,consolePort:57531,actual:true,staticFiles});});
 return {proof,files,options:{revision,imageId,privateValues:['private-credential-canary']}};
}
export function rewrite(v,name,change){const f=v.files.find(f=>f.path===name),o=JSON.parse(f.content.toString());change(o);f.content=Buffer.from(JSON.stringify(o));f.sha256=sha(f.content);v.proof.manifest.find(m=>m.path===name).sha256=f.sha256;}
