import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
import {assertNotificationEvidence,validateNotificationEvidence,requiredNotificationChecks,requiredNotificationUiActions} from '../../scripts/notifications/evidence.mjs';
const revision='a'.repeat(40),imageId='sha256:'+'b'.repeat(64),sha=b=>createHash('sha256').update(b).digest('hex');
function vector(){const proof={schemaVersion:1,sourceRevision:revision,imageId,clone:{actual:true,ownerVerified:true,projectName:'webapi-enterprise-local-test-'+randomUUID(),consolePort:57531},fixture:{actual:true,ownerVerified:true,sourceRevision:revision,imageId,host:'notification-fixture',tls:true},checks:requiredNotificationChecks.map(id=>({id,passed:true,sourceRevision:revision,imageId,evidence:{serviceResponse:true,actual:true,expected:true}})),protocol:{smtp:[{recipientCount:1,tls:true,authenticated:true,accepted:true,replyCode:250}],webhook:[{signatureValid:true,tls:true,remoteAccepted:true,replyCode:202}]},runtime:{backupVolumes:['dp-keys','notification-secrets','notification-fixture-secrets','notification-fixture-data'],oldToolsUnchanged:true},ui:{sourceRevision:revision,imageId,viewports:[1440,1280],actions:requiredNotificationUiActions.map((id,i)=>({id,passed:true,sourceRevision:revision,imageId,viewport:i===1?1280:1440,screenshot:id+'.jpg',observation:id+'.json'}))},manifest:[]};return {proof,files:[],options:{revision,imageId,privateValues:['private-credential-canary']}};}
test('emptyOrUnverifiableProtocolIsRejected',()=>{for(const patch of [{smtp:[],webhook:[]},{smtp:[{recipientCount:2,tls:false,authenticated:false,accepted:true}],webhook:[{signatureValid:false,tls:false,replyCode:202}]}]){const v=vector();v.proof.protocol=patch;assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));}});
test('wrongInternalRevisionAndRelabelledScreenshotsAreRejected',()=>{const v=vector();v.proof.fixture.sourceRevision='c'.repeat(40);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));v.proof.fixture.sourceRevision=revision;v.proof.ui.actions[0].sourceRevision='c'.repeat(40);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));});
test('original4192NonFixtureTargetAndMissingSilenceProofAreRejected',()=>{for(const mutate of [p=>p.clone.consolePort=4192,p=>p.fixture.host='enterprise.example.com',p=>p.checks=p.checks.filter(c=>c.id!=='silence-in-flight')]){const v=vector();mutate(v.proof);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));}});
test('missingColdBackupVolumeAndModifiedHistoricalToolAreRejected',()=>{for(const mutate of [p=>p.runtime.backupVolumes=p.runtime.backupVolumes.filter(n=>n!=='notification-fixture-data'),p=>p.runtime.oldToolsUnchanged=false]){const v=vector();mutate(v.proof);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));}});
test('privateCanaryAnywhereInEvidenceIsRejectedAndReturnShapeIsStable',()=>{const v=vector(),content=Buffer.from('private-credential-canary');v.files=[{path:'private.log',content,sha256:sha(content)}];v.proof.manifest=[{path:'private.log',sha256:sha(content)}];const result=validateNotificationEvidence(v.proof,v.files,v.options);assert.equal(result.passed,false);assert.ok(Array.isArray(result.errors)&&result.errors.length);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));});

import {validVector,rewrite} from './evidence-vector.mjs';
test('completeSyntheticVectorPassesAndEachInternalMutationFails',()=>{const base=validVector();assert.deepEqual(validateNotificationEvidence(base.proof,base.files,base.options),{passed:true,errors:[]});for(const [name,change]of [['fixture.json',o=>o.sourceRevision='c'.repeat(40)],['runtime.json',o=>o.ownerId=randomUUID()],['settings-1440-ui.json',o=>o.sourceRevision='c'.repeat(40)],['settings-1440-ui.json',o=>o.staticFiles['console/dist/assets/unit.js']='c'.repeat(64)],['silence-in-flight.json',o=>o.actual={different:true}]]){const v=validVector();rewrite(v,name,change);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));}});
test('privateCanaryInAnOtherwiseCompleteVectorFails',()=>{const v=validVector();rewrite(v,'saved-revision-conflict.json',o=>o.annotation='private-credential-canary');assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));});
test('equalButMeaninglessChecksAndUnverifiedHistoricalToolHashesFail',()=>{for(const [name,change]of [['silence-in-flight.json',o=>{o.actual={unit:true};o.expected={unit:true};}],['runtime.json',o=>{delete o.historicalTools;}],['runtime.json',o=>{o.historicalTools['manage.sh'].after='c'.repeat(64);}]]){const v=validVector();rewrite(v,name,change);assert.equal(validateNotificationEvidence(v.proof,v.files,v.options).passed,false);}});

test('plannedVolumeNamesCannotReplaceActualColdRestoreProof',()=>{for(const change of [o=>delete o.restore,o=>o.manifestFilesVerified=0,o=>o.restore.ownerId=o.ownerId,o=>o.restore.consolePort=4192,o=>o.restore.fixtureProtocolAfter='e'.repeat(64),o=>o.restore.dpKeysAfter={},o=>delete o.restore.secretHashesAfter['fixture/server.key']]){const v=validVector();rewrite(v,'cold-recovery.json',change);assert.throws(()=>assertNotificationEvidence(v.proof,v.files,v.options));}});
