import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {executeNotificationSql} from '../../scripts/notifications/scenario.mjs';
const state={projectName:'webapi-enterprise-local-test-'+randomUUID(),ownerId:randomUUID()};const pg={Id:'owned-pg',Config:{Labels:{'com.docker.compose.project':state.projectName,'com.webapi.runtime.owner':state.ownerId}}};
test('scenarioSqlActuallyAttachesInputToOwnedPostgres',async()=>{const text='SELECT 42;';let called=false;const result=await executeNotificationSql(state,pg,text,{run:async(args,options)=>{called=true;assert.equal(options.input,text);return {stdout:args.includes('-i')?'42\n':''};}});assert.equal(called,true);assert.equal(result,'42');});
test('scenarioSqlRejectsForeignContainerBeforeInvocation',async()=>{let called=false;await assert.rejects(executeNotificationSql(state,{...pg,Config:{Labels:{}}},'SELECT 42;',{run:async()=>{called=true;return {stdout:'42'};}}));assert.equal(called,false);});
test('scenarioSqlRejectsOriginalPersistentProject',async()=>{const original={...state,projectName:'webapi-enterprise-local'},container={...pg,Config:{Labels:{'com.docker.compose.project':original.projectName,'com.webapi.runtime.owner':original.ownerId}}};let called=false;await assert.rejects(executeNotificationSql(original,container,'SELECT 42;',{run:async()=>{called=true;return {stdout:'42'};}}));assert.equal(called,false);});
import {validateNotificationRecoveryTarget} from '../../scripts/notifications/recovery.mjs';
const core={schemaVersion:1,...state,ports:{console:57531,gatewayA:57532,gatewayB:57533},bootstrapUsername:'qa',binding:null,demoEnabled:false,releaseId:null,initialized:true,bindingPhase:null,pendingConfiguration:null};
const target=()=>{const projectName='webapi-enterprise-local-test-'+randomUUID();return {projectName,directory:'/private/tmp/'+projectName,ports:{console:57541,gatewayA:57542,gatewayB:57543},notificationPorts:{smtp:57544,https:57545,management:57546}};};
test('coldRestoreRequiresSeparateUUIDIdentityAndDistinctExplicitPorts',()=>{const t=target(),next=validateNotificationRecoveryTarget(core,t);assert.equal(next.projectName,t.projectName);assert.notEqual(next.ownerId,core.ownerId);assert.deepEqual(next.ports,t.ports);for(const bad of [{...t,projectName:'webapi-enterprise-local'},{...t,projectName:core.projectName,directory:'/private/tmp/'+core.projectName},{...t,directory:'/private/tmp/wrong'},{...t,ports:core.ports},{...t,notificationPorts:{...t.notificationPorts,management:57541}}])assert.throws(()=>validateNotificationRecoveryTarget(core,bad));assert.throws(()=>validateNotificationRecoveryTarget({...core,projectName:'webapi-enterprise-local'},t));});
