import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {loadState,writePrivate} from '../runtime/state.mjs';
import {loadRelease} from '../runtime/lifecycle.mjs';
import {inspectResources,docker} from '../runtime/docker.mjs';
import {validateCloneOwnership,assertReleaseIdentity} from '../contracts/evidence.mjs';
import {ContractClient} from '../contracts/scenario.mjs';

// All writes are confined to new UUID actors/resources in an owned disposable clone.
export async function runApprovalScenario({revision,imageId,cloneDirectory}){
 const state=await loadState(cloneDirectory),release=await loadRelease(path.join(cloneDirectory,'release.json')),resources=await inspectResources(state);validateCloneOwnership(state,resources,cloneDirectory);
 const apps=resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b'].includes(r.Config?.Labels?.['com.docker.compose.service']));assert.equal(apps.length,5);assert(apps.every(a=>a.State.Running));const actualImages=[];
 for(const app of apps){const image=JSON.parse((await docker(['image','inspect',app.Image])).stdout)[0];actualImages.push({imageId:image.Id,sourceRevision:image.Config.Labels['org.opencontainers.image.revision']});}assertReleaseIdentity({revision,release,actualImages});assert.equal(release.imageId,imageId);
 const endpoint='http://127.0.0.1:'+state.ports.console,admin=new ContractClient(endpoint),password=(await fs.readFile(path.join(cloneDirectory,'secrets/bootstrap-password'),'utf8')).trimEnd();await admin.login(state.bootstrapUsername,password);
 const tag=randomUUID().slice(0,8),organization=await admin.request('/organizations',{method:'POST',body:{code:'APPROVAL_'+tag,name:'跨环境审批验收 '+tag}}),project=await admin.request('/organizations/'+organization.id+'/projects',{method:'POST',body:{code:'APPROVAL_'+tag,name:'审批业务项目'}});
 const permissions=['release.read','approval.act','environment.read','project.read','organization.read','api.read','api.version.read','api.schema.read'];
 async function role(code){let r=await admin.request('/roles',{method:'POST',body:{code,name:'审批验收 '+code,organizationId:organization.id}});return admin.request('/roles/'+r.id+'/permissions',{method:'PUT',headers:{'If-Match':'"'+r.revision+'"'},body:{permissions}});}
 const reviewerRole=await role('ApprovalReviewer_'+tag),securityRole=await role('ApprovalSecurity_'+tag),platformRole=(await admin.request('/roles')).find(r=>r.isSystem&&r.code==='PlatformAdmin');assert(platformRole);
 let flow=await admin.request('/organizations/'+organization.id+'/approval-flows',{method:'POST',body:{name:'冻结两席位审批 '+tag,enabled:true,steps:[{stepOrder:1,roleCode:reviewerRole.code,requiredCount:2},{stepOrder:2,roleCode:securityRole.code,requiredCount:1}]}});
 const environments=[];for(const [code,name]of [['PROD_A','生产环境 A'],['PROD_B','生产环境 B']])environments.push(await admin.request('/projects/'+project.id+'/environments',{method:'POST',body:{code,name,isProduction:true,releasePolicyId:flow.id}}));
 const scopeOf=env=>({organizationId:organization.id,projectId:project.id,environmentId:env.id}),orgScope={organizationId:organization.id},actors={};
 async function actor(suffix,roleId,scopes){const username='approval-'+tag+'-'+suffix,userPassword=randomBytes(24).toString('base64');let user=await admin.request('/users',{method:'POST',body:{username,displayName:'审批验收 '+suffix,password:userPassword}});user=await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{roleIds:[roleId]}});await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{scopes}});const client=new ContractClient(endpoint);await client.login(username,userPassword);return actors[suffix]={id:user.id,username,password:userPassword,client,declaredScopes:scopes};}
 const write=[{scope:orgScope,accessMode:'read_write'}],read=[{scope:orgScope,accessMode:'read'}];await actor('applicant',platformRole.id,write);await actor('reviewer',reviewerRole.id,write);await actor('reviewer-two',reviewerRole.id,write);await actor('security',securityRole.id,write);await actor('reader',reviewerRole.id,read);await actor('mixed',reviewerRole.id,[...read,{scope:scopeOf(environments[0]),accessMode:'read_write'}]);
 const api=await admin.request('/projects/'+project.id+'/apis',{method:'POST',body:{code:'APPROVAL_'+tag,name:'审批冻结候选接口'}}),version=await admin.request('/apis/'+api.id+'/versions',{method:'POST',body:{version:'1.0.0'}});
 for(const env of environments){const cluster=await admin.request('/environments/'+env.id+'/clusters',{method:'POST',body:{name:'审批验收上游',loadBalancingPolicy:'RoundRobin',healthCheckEnabled:false}});await admin.request('/clusters/'+cluster.id+'/destinations',{method:'POST',body:{name:'backend-a',address:'http://backend-a:8080/',weight:1,enabled:true}});await admin.request('/environments/'+env.id+'/routes',{method:'POST',body:{apiVersionId:version.id,routeName:'Approval-'+tag+'-'+env.code,path:'/approval-'+tag,methods:['GET'],clusterId:cluster.id,priority:100,enabled:true,timeoutMs:10000,requireApiKey:true}});}
 const applicant=actors.applicant.client,reviewer=actors.reviewer.client,security=actors.security.client,reader=actors.reader.client,mixed=actors.mixed.client,checks=[];
 async function note(id,actual,expected,response){assert.deepEqual(actual,expected);checks.push({id,passed:true,sourceRevision:revision,imageId,evidence:{actual:JSON.stringify(actual),expected:JSON.stringify(expected),serviceResponse:response}});await writePrivate(path.join(cloneDirectory,'approval-scenario-checkpoint-'+tag+'.json'),{sourceRevision:revision,imageId,checks});console.log('Verified '+id);}
 async function reject(action,status){try{await action();assert.fail('Expected HTTP '+status);}catch(e){assert.equal(e.status,status);return {status:e.status,code:e.code,traceId:e.traceId};}}
 async function submit(env){const selection={baseConfigVersion:0,versionIds:[version.id]},candidate=await applicant.request('/environments/'+env.id+'/releases/preview',{method:'POST',body:selection});const r=await applicant.request('/environments/'+env.id+'/releases',{method:'POST',body:{...selection,resourceRevisions:candidate.resourceRevisions}});return applicant.request('/releases/'+r.id+'/submit',{method:'POST'});}
 const first=await submit(environments[0]),second=await submit(environments[1]),cross=await reviewer.request('/approvals');await note('cross-environment',cross.page.items.map(i=>i.environment.id).sort(),environments.map(e=>e.id).sort(),cross);
 const mixedInbox=await mixed.request('/approvals?view=AllVisible'),mixedPending=await mixed.request('/approvals');await note('mixed-scope',[mixedInbox.counts.allVisible,mixedPending.counts.pendingMine,mixedPending.page.items[0].environment.id],[2,1,environments[0].id],{mixedInbox,mixedPending});
 const readonly=await reader.request('/approvals?view=AllVisible'),readDenied=await reject(()=>reader.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'只读不得批准'}}),403);await note('read-only',[readonly.page.total,readonly.counts.pendingMine,readDenied.status],[2,0,403],{readonly,readDenied});
 const selfDenied=await reject(()=>applicant.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'不得自批'}}),403);await note('self-approval',selfDenied.status,403,selfDenied);
 flow=await admin.request('/approval-flows/'+flow.id,{method:'PUT',headers:{'If-Match':'"'+flow.revision+'"'},body:{name:flow.name,enabled:true,steps:[{stepOrder:1,roleCode:securityRole.code,requiredCount:1},{stepOrder:2,roleCode:reviewerRole.code,requiredCount:1}]}});
 for(let i=0;i<50;i++)await submit(environments[0]);
 const query='&environmentId='+environments[0].id,all=await reviewer.request('/approvals?view=AllVisible&page=1&pageSize=50'+query),last=await reviewer.request('/approvals?view=AllVisible&page=2&pageSize=50'+query),pending=await reviewer.request('/approvals?view=PendingMine'+query);assert(!all.page.items.some(i=>i.id===first.id));await note('second-page',[all.page.total,all.page.items.length,last.page.items.length,last.page.items[0].id,pending.counts.pendingMine],[51,50,1,first.id,1],{all,last,pending});
 const pagination={sourceRevision:revision,imageId,total:all.page.total,pageSize:all.page.pageSize,pendingMine:pending.counts.pendingMine,actionableId:first.id,secondPageId:last.page.items[0].id,countsFromService:true};
 await reviewer.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'第一独立席位'}});const duplicate=await reject(()=>reviewer.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'禁止重复占席'}}),403),early=await reject(()=>security.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'不得提前二级审批'}}),403);await actors['reviewer-two'].client.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'第二独立席位'}});const step=await security.request('/releases/'+first.id);await security.request('/releases/'+first.id+'/approve',{method:'POST',body:{comment:'独立二级审批'}});const ready=await applicant.request('/releases/'+first.id);await note('independent-seats',[duplicate.status,early.status,step.approvalEligibility.currentStepOrder,ready.state,new Set(ready.approvalSteps.filter(a=>a.status==='Approved').map(a=>a.actorId)).size],[403,403,2,'Ready',3],{duplicate,early,step,ready});
 // Revoke only a newly created actor. The reader remains read-only throughout.
 let user=(await admin.request('/users?pageSize=100')).items.find(u=>u.id===actors.mixed.id);assert(user);await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{scopes:[]}});const revoked=await mixed.request('/approvals?view=AllVisible');const noRead=await reject(()=>mixed.request('/releases/'+second.id),404);await note('revocation',[revoked.page.total,noRead.status],[0,404],{revoked,noRead});
 flow=await admin.request('/approval-flows/'+flow.id,{method:'PUT',headers:{'If-Match':'"'+flow.revision+'"'},body:{name:flow.name,enabled:true,steps:[{stepOrder:1,roleCode:reviewerRole.code,requiredCount:2},{stepOrder:2,roleCode:securityRole.code,requiredCount:1}]}});const uiReleaseA=await submit(environments[0]),uiReleaseB=await submit(environments[1]);
 const browserActors=Object.fromEntries(Object.entries(actors).map(([key,{client,...actor}])=>[key,actor]));await writePrivate(path.join(cloneDirectory,'approval-browser-context.json'),{sourceRevision:revision,imageId,endpoint,scope:scopeOf(environments[0]),organization,project,environments,actors:browserActors,firstReleaseId:first.id,secondReleaseId:second.id,uiReleaseA:uiReleaseA.id,uiReleaseB:uiReleaseB.id,admin:{username:state.bootstrapUsername,password}});
 const result={sourceRevision:revision,imageId,clone:{actual:true,ownerVerified:true,projectName:state.projectName,ownerId:state.ownerId,consolePort:state.ports.console,applicationImages:actualImages},environments:environments.map(e=>e.id),pagination,checks,originalInstallation:'not-upgraded'};await writePrivate(path.join(cloneDirectory,'approval-scenario-result.json'),result);return result;
}
