import {waitPipelineReadyForEvidence,waitPipelineStageOrder} from './pipeline-stage-wait.mjs';
import assert from 'node:assert/strict';import {currentStage,recordStageTests,acceptStageTests,prepareStagePromotion,publishStage} from './pipeline-scenario.mjs';import {until} from '../runtime/acceptance-scenario.mjs';
import {pipelineAttemptTimeoutSql} from './pipeline-fault-clock.mjs';
export async function runPipelineFaults(c,{stopAfterConcurrent=false}={}){
 const results=[],admin=c.s.admin,post=async(url,body)=>{const guarded=/\/(pause|resume|cancel|reopen)$/.test(url),row=guarded?await admin.request(url.slice(0,url.lastIndexOf('/'))):null;return admin.request(url,{method:'POST',body,...(guarded?{headers:{'If-Match':`"${row.revision}"`}}:{})});},start=()=>post('/release-pipeline-runs',{pipelineVersionId:c.version.id,rootArtifactId:c.artifact.id}),cancel=run=>post('/release-pipeline-runs/'+run.id+'/cancel',{comment:'结束受控故障验收'});
 c.pipelineProof.faults=results;
 const verify=async(name,action)=>{await c.checkpoint('pipeline_fault_'+name);const detail=await action();results.push({name,passed:true,actual:true,...detail});};
 const rejection=async(action,status)=>{let observed;await assert.rejects(action,e=>{observed=e.status;return (Array.isArray(status)?status:[status]).includes(e.status);});return observed;};
 const sql=async statement=>{assert(c.state.projectName.startsWith('webapi-enterprise-local-test-'),'fault injection is fixture only');return c.ctx.compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-v','ON_ERROR_STOP=1','-c',statement);};
 const expire=async stage=>{const result=await sql(pipelineAttemptTimeoutSql({attemptId:stage.currentAttemptId,stageId:stage.id,projectId:c.s.scope.projectId}));assert.match(result.stdout,/UPDATE 1\b/,'Exactly the current controlled attempt must expire');};
 let pausedGateway=null,run=await start(),stage=await currentStage(c,run.id);
 try{
 await verify('skipStage',async()=>({status:await rejection(post('/release-pipeline-run-stages/'+run.stages[2].id+'/prepare-promotion'),409)}));
 await verify('legacyBypass',async()=>{const before=await admin.request('/environments/'+c.target.id),status=await rejection(post('/environments/'+c.target.id+'/releases',{baseConfigVersion:before.configVersion,versionIds:[c.artifact.content.apis[0].versionId]}),[409,422]);return {status};});
 await verify('concurrentRun',async()=>{const attempts=await Promise.allSettled([start(),start()]);assert(attempts.every(r=>r.status==='rejected'&&r.reason.status===409));return {runId:run.id,rejections:2};});
 const context=await admin.request('/release-pipeline-run-stages/'+stage.id+'/verification-context'),now=new Date().toISOString(),evidence={type:'InterfaceFunction',result:'Passed',startedAt:now,finishedAt:now,comment:'实际隔离故障边界验证'};
 await verify('wrongProfile',async()=>{const facts=await recordStageTests(c,stage);await sql(`UPDATE release_verifications SET profile_hash=repeat('f',64) WHERE id='${facts.ids[0]}'`);try{return {status:await rejection(post('/release-pipeline-run-stages/'+stage.id+'/acceptance-requests',{expectedContextHash:facts.context.contextHash,verificationIds:facts.ids}),409)};}finally{await sql(`UPDATE release_verifications SET profile_hash='${stage.profileHash}' WHERE id='${facts.ids[0]}'`);}});
 await verify('predatesWindow',async()=>({status:await rejection(post('/release-pipeline-run-stages/'+stage.id+'/verifications',{expectedContextHash:context.contextHash,evidence:{...evidence,startedAt:'2000-01-01T00:00:00Z',finishedAt:'2000-01-01T00:00:00Z'}}),422)}));
 const facts=await recordStageTests(c,stage),requested=await post('/release-pipeline-run-stages/'+stage.id+'/acceptance-requests',{expectedContextHash:facts.context.contextHash,verificationIds:facts.ids});
 await verify('runApplicantIndependence',async()=>({status:await rejection(admin.request('/test-acceptances/'+requested.id+'/accept',{method:'POST',headers:{'If-Match':`"${requested.revision}"`},body:{comment:'申请人不得自验收'}}),[403,409])}));
 await c.pipelineAcceptor.client.request('/test-acceptances/'+requested.id+'/accept',{method:'POST',headers:{'If-Match':`"${requested.revision}"`},body:{comment:'真实独立验收后故障注入'}});stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);
 await verify('wrongRootHash',async()=>{await c.ctx.compose('stop','worker');await sql(`UPDATE release_pipeline_runs SET root_artifact_hash=repeat('f',64) WHERE id='${run.id}'`);try{return {status:await rejection(post('/release-pipeline-run-stages/'+stage.id+'/prepare-promotion'),409)};}finally{await sql(`UPDATE release_pipeline_runs SET root_artifact_hash='${run.rootArtifactHash}' WHERE id='${run.id}'`);await c.ctx.compose('up','-d','worker');}});
 await verify('explicitRevocation',async()=>{const a=await c.pipelineAcceptor.client.request('/test-acceptances/'+requested.id);await c.pipelineAcceptor.client.request('/test-acceptances/'+a.id+'/revoke',{method:'POST',headers:{'If-Match':`"${a.revision}"`},body:{comment:'真实独立撤销当前 Run 来源验收'}});const invalid=await until(()=>admin.request('/release-pipeline-runs/'+run.id),r=>r.status==='Invalidated');return {runId:invalid.id,status:invalid.status};});
 }finally{const state=await admin.request('/release-pipeline-runs/'+run.id);if(!['Completed','Cancelled','Invalidated'].includes(state.status))await cancel(run);}
 // Additional deployment and recovery faults continue in a separate current run; all injections target only its typed rows.
 run=await start();stage=await currentStage(c,run.id);
 try{
 await verify('expiredEvidence',async()=>{const facts=await recordStageTests(c,stage);await sql(`UPDATE release_verifications SET expires_at=now()-interval '1 second' WHERE id IN (${facts.ids.map(id=>`'${id}'`).join(',')})`);return {status:await rejection(post('/release-pipeline-run-stages/'+stage.id+'/acceptance-requests',{expectedContextHash:facts.context.contextHash,verificationIds:facts.ids}),409)};});
 await verify('reopenUnemitted',async()=>{await expire(stage);await until(()=>admin.request('/release-pipeline-runs/'+run.id),r=>r.status==='TimedOut');const reopened=await post('/release-pipeline-run-stages/'+stage.id+'/reopen',{comment:'人工开启新的未发出尝试'});assert.notEqual(reopened.currentAttemptId,stage.currentAttemptId);return {stageId:stage.id,previousAttemptId:stage.currentAttemptId,currentAttemptId:reopened.currentAttemptId};});
 stage=await currentStage(c,run.id);await acceptStageTests(c,stage);stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);
 await verify('concurrentAttempt',async()=>{const outcomes=await Promise.allSettled([post('/release-pipeline-run-stages/'+stage.id+'/prepare-promotion'),post('/release-pipeline-run-stages/'+stage.id+'/prepare-promotion')]);const observation=outcomes.map(x=>x.status==='fulfilled'?{status:200,promotionId:x.value.id}:{status:x.reason.status??null,code:x.reason.code??null,traceId:x.reason.traceId??null,message:x.reason.message});c.pipelineProof.concurrentPreparation=observation;const ids=outcomes.filter(x=>x.status==='fulfilled').map(x=>x.value.id);assert(ids.length&&new Set(ids).size===1,JSON.stringify(observation));assert(outcomes.filter(x=>x.status==='rejected').every(x=>x.reason.status===409),JSON.stringify(observation));return {promotionId:ids[0],oneFormalAttempt:true};});
 }finally{await cancel(run);}
 if(stopAfterConcurrent)return results;
 run=await start();stage=await currentStage(c,run.id);try{
 await acceptStageTests(c,stage);stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);
 await verify('mappingRevision',async()=>{const mapped=await prepareStagePromotion(c,stage,{submit:false}),p=mapped.promotion;await admin.request('/release-promotions/'+p.id+'/mapping',{method:'PUT',headers:{'If-Match':`"${p.revision}"`},body:p.mapping});return {status:await rejection(admin.request('/release-promotions/'+p.id+'/submit',{method:'POST',headers:{'If-Match':`"${p.revision}"`}}),[409,412])};});
 const resource=c.resources.get(stage.environmentId);await admin.request('/applications/'+resource.app.id+'/permissions',{method:'POST',body:{apiId:c.s.api.id,environmentId:c.source.id,validFrom:new Date(Date.now()-60000).toISOString()}});
 await verify('sharedCredential',async()=>{const mapped=await prepareStagePromotion(c,stage,{submit:false,confirmShared:false});assert.equal(mapped.precheck.canSubmit,false);assert(mapped.precheck.checks.some(x=>x.reasonCode==='shared_credential_confirmation_required'));return {promotionId:mapped.promotion.id};});
 const p=await prepareStagePromotion(c,stage);await c.ctx.compose('stop','worker');try{await post('/releases/'+p.targetReleaseId+'/publish');assert.equal((await admin.request('/releases/'+p.targetReleaseId)).state,'Building');const previous=await admin.request('/release-pipeline-run-stages/'+run.stages[0].id),a=await c.pipelineAcceptor.client.request('/test-acceptances/'+previous.acceptance.id);await c.pipelineAcceptor.client.request('/test-acceptances/'+a.id+'/revoke',{method:'POST',headers:{'If-Match':`"${a.revision}"`},body:{comment:'队列尚未下发时撤销真实来源验收'}});}finally{await c.ctx.compose('up','-d','worker');}
 await verify('queuedRevocation',async()=>{const invalid=await until(()=>admin.request('/release-pipeline-runs/'+run.id),r=>r.status==='Invalidated'),release=await admin.request('/releases/'+p.targetReleaseId);assert.equal(release.state,'Cancelled');return {runId:invalid.id,releaseId:release.id,status:release.state};});
 }finally{const row=await admin.request('/release-pipeline-runs/'+run.id);if(!['Cancelled','Invalidated'].includes(row.status))await cancel(run);}
 run=await start();stage=await currentStage(c,run.id);try{
 await acceptStageTests(c,stage);stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);let p=await prepareStagePromotion(c,stage);const publisher=await c.createActor('排队撤权发布人','PipelineFaultPublisher',['pipeline.run','release.publish'],{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId});
 await verify('queuedAuthority',async()=>{await c.ctx.compose('stop','worker');let role;try{await publisher.client.request('/releases/'+p.targetReleaseId+'/publish',{method:'POST'});role=await admin.request('/roles/'+publisher.role.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${publisher.role.revision}"`},body:{permissions:publisher.permissions.filter(x=>x!=='release.publish')}});}finally{await c.ctx.compose('up','-d','worker');}const failed=await until(()=>admin.request('/releases/'+p.targetReleaseId),r=>r.state==='Failed');await admin.request('/roles/'+role.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${role.revision}"`},body:{permissions:publisher.permissions}});return {releaseId:failed.id,publisherId:publisher.user.id};});
 // Reopen the unemitted queue failure before a real partial deployment.
 await post('/release-pipeline-run-stages/'+stage.id+'/reopen',{comment:'排队撤权故障处理后人工开启新尝试'});stage=await currentStage(c,run.id);p=await prepareStagePromotion(c,stage);const group=c.groups.find(g=>g.environmentId===stage.environmentId);await c.ctx.compose('pause',group.services[1]);pausedGateway=group.services[1];
 await post('/releases/'+p.targetReleaseId+'/publish');const partial=await until(()=>admin.request('/releases/'+p.targetReleaseId),r=>r.state==='Publishing'&&r.targets.filter(t=>t.acknowledged).length===1,90);const partialSnapshot=(await admin.request('/environments/'+stage.environmentId+'/snapshots')).items.find(x=>x.configVersion===partial.targetConfigVersion);assert.match(partialSnapshot?.payloadHash??'',/^[a-f0-9]{64}$/);
 await verify('workerRestart',async()=>{await c.ctx.compose('restart','worker');const same=await admin.request('/releases/'+partial.id);assert.equal(same.deploymentSequence,partial.deploymentSequence);return {releaseId:same.id,deploymentSequence:same.deploymentSequence};});
 await verify('stageTimeoutPartialAck',async()=>{stage=await currentStage(c,run.id);await expire(stage);await until(()=>admin.request('/release-pipeline-runs/'+run.id),r=>r.status==='TimedOut');const status=await rejection(post('/release-pipeline-run-stages/'+stage.id+'/reopen',{comment:'Publishing 不可重开'}),409),failed=await until(()=>admin.request('/releases/'+partial.id),r=>r.state==='Failed',180);assert.equal(failed.targets.filter(t=>t.acknowledged).length,1);return {releaseId:failed.id,status,partialAcknowledgments:1};});
 await verify('lateAck',async()=>{await c.ctx.compose('unpause',group.services[1]);pausedGateway=null;const late=await until(()=>admin.request('/releases/'+partial.id),r=>r.state==='Failed'&&r.targets.every(t=>t.acknowledged),90),nodes=(await admin.request('/environments/'+stage.environmentId+'/gateway-nodes')).items;assert(late.targets.every(t=>nodes.find(n=>n.id===t.nodeId)?.instanceId===t.instanceId));return {releaseId:late.id,status:late.state,acknowledgments:2,frozenInstancesPreserved:true};});
 await verify('exactRetry',async()=>{await post('/release-pipeline-run-stages/'+stage.id+'/reopen',{comment:'人工重开相同快照字节的恢复重试'});stage=await waitPipelineReadyForEvidence(()=>currentStage(c,run.id));const retry=await admin.request('/releases/'+stage.actualReleaseId);assert.equal(retry.recoveryOf,partial.id);assert.equal(retry.targetConfigVersion,partial.targetConfigVersion);assert(retry.deploymentSequence>partial.deploymentSequence&&retry.targets.every(t=>t.acknowledged));const hashes=(await admin.request('/environments/'+stage.environmentId+'/snapshots')).items;const snapshot=hashes.find(s=>s.configVersion===retry.targetConfigVersion);assert.equal(snapshot?.payloadHash,partialSnapshot.payloadHash);assert.equal(retry.candidateHash,partial.candidateHash);return {releaseId:retry.id,recoveryOf:partial.id,configVersion:retry.targetConfigVersion,sequence:retry.deploymentSequence,snapshotHash:snapshot.payloadHash,originalSnapshotHash:partialSnapshot.payloadHash,candidateHash:retry.candidateHash};});
 await post('/release-pipeline-run-stages/'+stage.id+'/materialize-artifact');const old=await admin.request('/release-pipeline-run-stages/'+stage.id+'/verification-context');
 await verify('reopenSucceeded',async()=>{stage=await currentStage(c,run.id);await expire(stage);await until(()=>admin.request('/release-pipeline-runs/'+run.id),r=>r.status==='TimedOut');await post('/release-pipeline-run-stages/'+stage.id+'/reopen',{comment:'相同成功部署重新开启独立证据窗口'});const fresh=await admin.request('/release-pipeline-run-stages/'+stage.id+'/verification-context');assert.notEqual(fresh.contextHash,old.contextHash);assert.equal(fresh.releaseId,old.releaseId);return {stageId:stage.id,previousAttemptId:old.currentAttemptId,currentAttemptId:fresh.currentAttemptId};});
 await verify('staleEditor',async()=>({status:await rejection(post('/release-pipeline-run-stages/'+stage.id+'/verifications',{expectedContextHash:old.contextHash,evidence:{type:'InterfaceFunction',result:'Passed',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),comment:'旧表单不可复用'}}),409)}));
 }finally{if(pausedGateway){await c.ctx.compose('unpause',pausedGateway);pausedGateway=null;}await c.ctx.compose('up','-d',...c.groups.filter(g=>g.kind==='Middle').flatMap(g=>g.services));await cancel(run);}
 run=await start();stage=await currentStage(c,run.id);try{
 await acceptStageTests(c,stage);stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);
 await verify('restrictedDelegate',async()=>{const actor=await c.createActor('仅当前阶段委托','PipelineDelegate',['pipeline.read','pipeline.run','release.test.record','release.create'],{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId});let user=(await admin.request('/users')).items.find(x=>x.id===actor.user.id);await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{scopes:[{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:c.source.id},accessMode:'read'},{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId},accessMode:'read_write'}]}});const view=await actor.client.request('/release-pipeline-runs/'+run.id);assert.equal(view.coverage,'Partial');assert(!view.stages.find(s=>s.environmentId===c.target.id)?.profile);assert.equal((await actor.client.request('/release-pipeline-run-stages/'+stage.id)).environmentId,stage.environmentId);const page=await actor.client.request('/release-pipeline-runs');assert.equal(page.total,null);await rejection(actor.client.request('/release-pipeline-run-stages/'+run.stages[2].id),404);c.pipelineDelegate=actor;return {actorId:actor.user.id,runId:run.id,stageId:stage.id,coverage:view.coverage,total:page.total};});
 // Middle TEST and UAT complete through actual independent deployments and their own manual evidence.
 for(const order of [2,3]){stage=await currentStage(c,run.id);assert.equal(stage.stageOrder,order);const p=await prepareStagePromotion(c,stage);await publishStage(c,p);stage=await waitPipelineReadyForEvidence(()=>currentStage(c,run.id));await post('/release-pipeline-run-stages/'+stage.id+'/materialize-artifact');stage=await currentStage(c,run.id);await acceptStageTests(c,stage);await waitPipelineStageOrder(()=>currentStage(c,run.id),order+1);}
 stage=await currentStage(c,run.id);const p=await prepareStagePromotion(c,stage),release=await publishStage(c,p);stage=await waitPipelineReadyForEvidence(()=>currentStage(c,run.id));
 await verify('approvedRollback',async()=>{const context=await c.pipelineVerifier.client.request('/release-promotions/'+p.id+'/verification-context'),now=new Date().toISOString();await c.pipelineVerifier.client.request('/release-promotions/'+p.id+'/verifications',{method:'POST',body:{type:'CriticalBusinessCall',result:'Failed',startedAt:now,finishedAt:now,expectedContextHash:context.hash,comment:'人工登记受控业务失败，必须经过审批恢复基线'}});const rollback=await post('/releases/'+release.id+'/rollback',{targetConfigVersion:c.baseline.targetConfigVersion});await post('/releases/'+rollback.id+'/submit');for(const actor of [c.first,c.second])await actor.client.request('/releases/'+rollback.id+'/approve',{method:'POST',body:{comment:'人工独立批准恢复此前真实生产基线'}});await post('/releases/'+rollback.id+'/publish');const rolled=await until(()=>admin.request('/releases/'+rollback.id),r=>r.state==='Succeeded'&&r.targets.every(t=>t.acknowledged));assert.equal(rolled.targetConfigVersion,c.baseline.targetConfigVersion);assert.equal(rolled.rollbackOf,release.id);assert.equal(rolled.approvalSteps.length,2);assert(rolled.approvalSteps.every(a=>a.status==='Approved'||a.state==='Approved'));assert(rolled.deploymentSequence>release.deploymentSequence);assert.equal((await c.fetchProduction()).status,200);return {releaseId:rolled.id,recoveryOf:release.id,sequence:rolled.deploymentSequence,approvals:rolled.approvalSteps.length};});
 }finally{const row=await admin.request('/release-pipeline-runs/'+run.id);if(!['Completed','Cancelled','Invalidated'].includes(row.status))await cancel(run);}
 return results;
}
