import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {freePorts} from '../runtime/acceptance.mjs';import {until} from '../runtime/acceptance-scenario.mjs';import {initializeIdp,idpContext,saveSsoConnection,cleanupRestoredIdp} from '../runtime/keycloak-demo.mjs';import {provisionSsoDemo} from '../runtime/sso-demo-platform.mjs';import {preparePipelineContext} from './pipeline-runtime.mjs';import {currentStage,acceptStageTests} from './pipeline-scenario.mjs';
export async function runPipelineBrowser(c,{nodeRuntime,chromiumExecutable}){
 const require=createRequire(path.join(nodeRuntime,'package.json')),{chromium}=require('playwright'),browser=await chromium.launch({headless:true,executablePath:chromiumExecutable}),result={actualSso:false,cases:[],screenshots:[],errors:[]},idpDirectory=path.join(c.directory,'pipeline-idp');let idpStarted=false;
 c.pipelineProof.browser=result;
 const shot=async(page,width,name)=>{await page.evaluate(()=>window.scrollTo(0,0));const file=name+'-'+width+'.png';await page.screenshot({path:path.join(c.evidenceDirectory,file),fullPage:await page.getByRole('dialog').count()===0});result.screenshots.push({path:file,width,sha256:createHash('sha256').update(await fs.readFile(path.join(c.evidenceDirectory,file))).digest('hex'),visuallyInspected:false});};
 async function pageFor(username,width,url){const context=await browser.newContext({viewport:{width,height:1000}});await context.addInitScript(scope=>{for(const[k,v]of Object.entries(scope))localStorage.setItem('core-'+k,v);},{organization:c.s.scope.organizationId,project:c.s.scope.projectId,environment:c.source.id});const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(c.s.endpoint+url);await page.locator('input[name=username]').fill(username);await page.locator('input[name=password]').fill(c.s.password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.waitForURL(c.s.endpoint+url);await page.locator('main h1').waitFor();return {page,context};}
 async function action(runId,kind){const row=await c.s.admin.request('/release-pipeline-runs/'+runId);return c.s.admin.request('/release-pipeline-runs/'+runId+'/'+kind,{method:'POST',headers:{'If-Match':`"${row.revision}"`},body:{comment:'浏览器验收的明确运行操作'}});}
 try{
 await c.checkpoint('pipeline_browser_actual_sso');await initializeIdp({runtimeDirectory:c.directory,directory:idpDirectory,port:(await freePorts()).console});idpStarted=true;const idp=await idpContext(c.directory,idpDirectory);await saveSsoConnection(idp,true);c.ctx=await preparePipelineContext(c.directory,c.state,c.release);await c.ctx.compose('up','-d','--force-recreate','control-plane');await until(()=>c.s.admin.request('/auth/me'),r=>r.id,45);const receipt=await provisionSsoDemo({runtimeDirectory:c.directory,directory:idpDirectory,passwordFile:path.join(c.directory,'secrets/bootstrap-password')});
 const ssoContext=await browser.newContext({viewport:{width:1440,height:1000}}),ssoPage=await ssoContext.newPage();await ssoPage.goto(c.s.endpoint+'/login');await ssoPage.getByRole('button',{name:/本机 SSO 演示/}).click();await ssoPage.locator('#username').fill('sso-demo-viewer');await ssoPage.locator('#password').fill((await fs.readFile(path.join(idpDirectory,'viewer-password'),'utf8')).trim());await ssoPage.locator('#kc-login').click();await ssoPage.waitForURL(c.s.endpoint+'/**');await ssoPage.locator('main h1').waitFor();const me=await ssoPage.evaluate(async()=>{const r=await fetch('/api/v1/auth/me',{cache:'no-store'});return r.json();});assert.equal(me.id,receipt.userId);assert(!me.permissions?.includes('pipeline.manage'));await shot(ssoPage,1440,'sso-viewer');result.actualSso=true;result.ssoUserId=receipt.userId;await ssoContext.close();
 for(const width of [1440,1280]){
 await c.checkpoint('pipeline_browser_'+width);const flags={width,keyboard:false,conflict412:false,conflict409:false,revocation:false,delegate:false,returnFilters:false};
 const a=await pageFor(c.state.bootstrapUsername,width,'/delivery/pipelines/'+c.version.pipelineId);await a.page.getByRole('button',{name:'编辑草稿',exact:true}).click();let dialog=a.page.getByRole('dialog');const nameInput=dialog.getByLabel('流水线名称',{exact:true});await nameInput.fill('浏览器保留的本地草稿 '+width);await nameInput.focus();await a.page.keyboard.press('Tab');assert.equal(await dialog.locator(':focus').count(),1);flags.keyboard=true;const old=await c.s.admin.request('/release-pipelines/'+c.version.pipelineId);await c.s.admin.request('/release-pipelines/'+old.id,{method:'PUT',headers:{'If-Match':`"${old.revision}"`},body:{...old.draft,name:'服务器新修订 '+width}});const conflict=a.page.waitForResponse(r=>r.url().includes('/api/v1/release-pipelines/')&&r.request().method()==='PUT'&&r.status()===412);await dialog.getByRole('button',{name:'保存',exact:true}).click();await conflict;assert.equal(await nameInput.inputValue(),'浏览器保留的本地草稿 '+width);flags.conflict412=true;await shot(a.page,width,'definition-412');await a.context.close();
 const run=await c.s.admin.request('/release-pipeline-runs',{method:'POST',body:{pipelineVersionId:c.version.id,rootArtifactId:c.artifact.id}});try{
 let stage=await currentStage(c,run.id);const current=await pageFor(c.state.bootstrapUsername,width,'/delivery/pipeline-stages/'+stage.id);await current.page.getByRole('button',{name:'登记本阶段测试',exact:true}).click();dialog=current.page.getByRole('dialog');await dialog.getByLabel('测试说明',{exact:true}).fill('浏览器人工登记实际两个 Gateway 的响应');const rejected=current.page.waitForResponse(r=>r.url().endsWith('/verifications')&&r.request().method()==='POST'&&r.status()===409);await action(run.id,'pause');await dialog.getByRole('button',{name:'保存',exact:true}).click();await rejected;flags.conflict409=true;await shot(current.page,width,'stage-409');await current.context.close();await action(run.id,'resume');await acceptStageTests(c,stage);stage=await until(()=>currentStage(c,run.id),s=>s.stageOrder===2);
 let actor=c.pipelineDelegate;if(!actor){actor=await c.createActor('浏览器当前阶段委托','PipelineBrowserDelegate',['pipeline.read','pipeline.run','release.test.record','release.create'],{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId});const user=(await c.s.admin.request('/users')).items.find(x=>x.id===actor.user.id);await c.s.admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{scopes:[{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:c.source.id},accessMode:'read_only'},{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId},accessMode:'read_write'}]}});c.pipelineDelegate=actor;}const d=await pageFor(actor.username,width,'/delivery/pipeline-stages/'+stage.id);const text=await d.page.locator('main').innerText();assert(text.includes('阶段 2'));assert(!text.includes(c.target.name));flags.delegate=true;await shot(d.page,width,'delegated-stage');const role=(await c.s.admin.request('/roles')).find(r=>r.id===actor.role.id),limited=await c.s.admin.request('/roles/'+role.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${role.revision}"`},body:{permissions:actor.permissions.filter(p=>p!=='pipeline.read')}});try{await d.page.reload();await until(()=>d.page.locator('main').innerText(),t=>!t.includes('实际 Gateway 节点'),20);assert(!(await d.page.locator('main').innerText()).includes('阶段 2'));flags.revocation=true;await shot(d.page,width,'revoked-stage');}finally{await c.s.admin.request('/roles/'+limited.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${limited.revision}"`},body:{permissions:actor.permissions}});await d.context.close();}
 }finally{const row=await c.s.admin.request('/release-pipeline-runs/'+run.id);if(!['Completed','Cancelled','Invalidated'].includes(row.status))await action(run.id,'cancel');}
 const release=c.pipelineProof.chains[1].stages.at(-1).actualReleaseId,returnPath='/approvals?environmentId='+c.target.id+'&view=AllVisible',back=await pageFor(c.state.bootstrapUsername,width,'/releases/'+release+'?returnTo='+encodeURIComponent(returnPath));await back.page.getByRole('link',{name:'晋级差异、执行与生产验证',exact:true}).click();await back.page.getByRole('link',{name:'返回审批筛选',exact:true}).click();await back.page.waitForURL(c.s.endpoint+returnPath);flags.returnFilters=true;await shot(back.page,width,'approval-return');await back.context.close();result.cases.push(flags);
 }
 assert.deepEqual(result.errors,[]);return result;
 }finally{await browser.close();if(idpStarted){await cleanupRestoredIdp({runtimeDirectory:c.directory,directory:idpDirectory});c.ctx=await preparePipelineContext(c.directory,c.state,c.release);await c.ctx.compose('up','-d','control-plane');await until(()=>c.s.admin.request('/auth/me'),r=>r.id,45);}}
}
