import {waitPipelineReadyForEvidence,waitPipelineStageOrder} from './pipeline-stage-wait.mjs';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {freePorts} from '../runtime/acceptance.mjs';import {until} from '../runtime/acceptance-scenario.mjs';import {initializeIdp,idpContext,saveSsoConnection,cleanupRestoredIdp} from '../runtime/keycloak-demo.mjs';import {provisionSsoDemo} from '../runtime/sso-demo-platform.mjs';import {preparePipelineContext} from './pipeline-runtime.mjs';import {currentStage,acceptStageTests,prepareStagePromotion,publishStage,actualStageCalls} from './pipeline-scenario.mjs';
export async function runPipelineBrowser(c,{nodeRuntime,chromiumExecutable}){
 const require=createRequire(path.join(nodeRuntime,'package.json')),{chromium}=require('playwright'),browser=await chromium.launch({headless:true,executablePath:chromiumExecutable}),result={actualSso:false,cases:[],screenshots:[],errors:[]},idpDirectory=path.join(c.directory,'pipeline-idp');let idpStarted=false;
 c.pipelineProof.browser=result;
 const shot=async(page,width,name)=>{await page.evaluate(()=>window.scrollTo(0,0));const file=name+'-'+width+'.png';await page.screenshot({path:path.join(c.evidenceDirectory,file),fullPage:await page.getByRole('dialog').count()===0});result.screenshots.push({path:file,width,sha256:createHash('sha256').update(await fs.readFile(path.join(c.evidenceDirectory,file))).digest('hex'),visuallyInspected:false});};
 async function pageFor(username,width,url){const context=await browser.newContext({viewport:{width,height:1000}});await context.addInitScript(scope=>{for(const[k,v]of Object.entries(scope))localStorage.setItem('core-'+k,v);},{organization:c.s.scope.organizationId,project:c.s.scope.projectId,environment:c.source.id});const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(c.s.endpoint+url);await page.locator('input[name=username]').fill(username);await page.locator('input[name=password]').fill(c.s.password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.waitForURL(c.s.endpoint+url);await page.locator('main h1').waitFor();return {page,context};}
 async function action(runId,kind){const row=await c.s.admin.request('/release-pipeline-runs/'+runId);return c.s.admin.request('/release-pipeline-runs/'+runId+'/'+kind,{method:'POST',headers:{'If-Match':`"${row.revision}"`},body:{comment:'浏览器验收的明确运行操作'}});}
 try{
 await c.checkpoint('pipeline_browser_actual_sso');await initializeIdp({runtimeDirectory:c.directory,directory:idpDirectory,port:(await freePorts()).console});idpStarted=true;const idp=await idpContext(c.directory,idpDirectory);await saveSsoConnection(idp,true);c.ctx=await preparePipelineContext(c.directory,c.state,c.release);await c.ctx.compose('up','-d','--force-recreate','control-plane');await until(()=>c.s.admin.request('/auth/me'),r=>r.id,45);const receipt=await provisionSsoDemo({runtimeDirectory:c.directory,directory:idpDirectory,passwordFile:path.join(c.directory,'secrets/bootstrap-password')});
 const ssoContext=await browser.newContext({viewport:{width:1440,height:1000}}),ssoPage=await ssoContext.newPage();await ssoPage.goto(c.s.endpoint+'/login');await ssoPage.getByRole('button',{name:/本机 SSO 演示/}).click();await ssoPage.locator('#username').fill('sso-demo-viewer');await ssoPage.locator('#password').fill((await fs.readFile(path.join(idpDirectory,'viewer-password'),'utf8')).trim());await ssoPage.locator('#kc-login').click();await ssoPage.waitForURL(c.s.endpoint+'/**');await ssoPage.locator('main h1').waitFor();const me=await ssoPage.evaluate(async()=>{const r=await fetch('/api/v1/auth/me',{cache:'no-store'});return r.json();});assert.equal(me.id,receipt.userId);assert(!me.permissions?.includes('pipeline.manage'));await shot(ssoPage,1440,'sso-viewer');result.actualSso=true;result.ssoUserId=receipt.userId;await ssoContext.close();
 for(const width of [1440,1280]){
 await c.checkpoint('pipeline_browser_'+width);const flags={width,keyboard:false,conflict412:false,conflict409:false,revocation:false,delegate:false,thirdStageDelegateMapping:false,returnFilters:false};
 const a=await pageFor(c.state.bootstrapUsername,width,'/delivery/pipelines/'+c.version.pipelineId);await a.page.getByRole('button',{name:'编辑草稿',exact:true}).click();let dialog=a.page.getByRole('dialog');const nameInput=dialog.getByLabel('流水线名称',{exact:true});await nameInput.fill('浏览器保留的本地草稿 '+width);await nameInput.focus();await a.page.keyboard.press('Tab');assert.equal(await dialog.locator(':focus').count(),1);flags.keyboard=true;const old=await c.s.admin.request('/release-pipelines/'+c.version.pipelineId);await c.s.admin.request('/release-pipelines/'+old.id,{method:'PUT',headers:{'If-Match':`"${old.revision}"`},body:{...old.draft,name:'服务器新修订 '+width}});const conflict=a.page.waitForResponse(r=>r.url().includes('/api/v1/release-pipelines/')&&r.request().method()==='PUT'&&r.status()===412);await dialog.getByRole('button',{name:'保存',exact:true}).click();await conflict;assert.equal(await nameInput.inputValue(),'浏览器保留的本地草稿 '+width);flags.conflict412=true;await shot(a.page,width,'definition-412');await a.context.close();
 const run=await c.s.admin.request('/release-pipeline-runs',{method:'POST',body:{pipelineVersionId:c.version.id,rootArtifactId:c.artifact.id}});try{
 let stage=await currentStage(c,run.id);const current=await pageFor(c.state.bootstrapUsername,width,'/delivery/pipeline-stages/'+stage.id);await current.page.getByRole('button',{name:'登记本阶段测试',exact:true}).click();dialog=current.page.getByRole('dialog');await dialog.getByLabel('测试说明',{exact:true}).fill('浏览器人工登记实际两个 Gateway 的响应');const endpoint='**/api/v1/release-pipeline-run-stages/'+stage.id+'/verifications';let releaseHeld;const held=new Promise(r=>releaseHeld=r);await current.page.route(endpoint,async route=>{if(route.request().method()==='POST')await held;await route.continue();});const outgoing=current.page.waitForRequest(r=>r.url().endsWith('/verifications')&&r.method()==='POST'),rejected=current.page.waitForResponse(r=>r.url().endsWith('/verifications')&&r.request().method()==='POST'&&r.status()===409);try{await dialog.getByRole('button',{name:'保存',exact:true}).click();await outgoing;await action(run.id,'pause');}finally{releaseHeld();}await rejected;await current.page.unroute(endpoint);flags.conflict409=true;flags.staleSubmissionTransport='held-real-request';await shot(current.page,width,'stage-409');await current.context.close();await action(run.id,'resume');await acceptStageTests(c,stage);stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),2);
 let actor=c.pipelineDelegate;if(!actor){actor=await c.createActor('浏览器当前阶段委托','PipelineBrowserDelegate',['pipeline.read','pipeline.run','release.test.record','release.create'],{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId});const user=(await c.s.admin.request('/users')).items.find(x=>x.id===actor.user.id);await c.s.admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${user.revision}"`},body:{scopes:[{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:c.source.id},accessMode:'read'},{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId},accessMode:'read_write'}]}});c.pipelineDelegate=actor;}const d=await pageFor(actor.username,width,'/delivery/pipeline-stages/'+stage.id);await d.page.getByRole('heading',{name:/^阶段 2 ·/}).waitFor();const text=await d.page.locator('main').innerText();assert(text.includes('阶段 2'));assert(!text.includes(c.target.name));flags.delegate=true;await shot(d.page,width,'delegated-stage');const denial=d.page.waitForResponse(r=>r.url().endsWith('/release-pipeline-run-stages/'+stage.id)&&r.request().method()==='GET'&&[403,404].includes(r.status()));const role=(await c.s.admin.request('/roles')).find(r=>r.id===actor.role.id),limited=await c.s.admin.request('/roles/'+role.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${role.revision}"`},body:{permissions:actor.permissions.filter(p=>p!=='pipeline.read')}});try{flags.revocationStatus=(await denial).status();await d.page.locator('main').getByRole('alert').first().waitFor();await until(()=>d.page.locator('main').innerText(),t=>!t.includes('实际 Gateway 节点')&&!t.includes('阶段 2'),20);flags.revocation=true;await shot(d.page,width,'revoked-stage');}finally{await c.s.admin.request('/roles/'+limited.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${limited.revision}"`},body:{permissions:actor.permissions}});await d.context.close();}

 // Complete the second environment with actual ACK/calls so this actor only needs its direct predecessor.
 const secondPromotion=await prepareStagePromotion(c,stage);await publishStage(c,secondPromotion);stage=await waitPipelineReadyForEvidence(()=>currentStage(c,run.id));await c.s.admin.request('/release-pipeline-run-stages/'+stage.id+'/materialize-artifact',{method:'POST'});stage=await currentStage(c,run.id);await actualStageCalls(c,stage);await acceptStageTests(c,stage);const predecessor=stage;stage=await waitPipelineStageOrder(()=>currentStage(c,run.id),3);
 const third=await c.createActor('第三阶段相邻环境委托 '+width,'PipelineThirdDelegate'+width,['pipeline.read','pipeline.run','release.create','route.write'],{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId});const thirdUser=(await c.s.admin.request('/users')).items.find(u=>u.id===third.user.id);await c.s.admin.request('/users/'+third.user.id+'/scopes',{method:'PUT',headers:{'If-Match':`"${thirdUser.revision}"`},body:{scopes:[{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:predecessor.environmentId},accessMode:'read'},{scope:{organizationId:c.s.scope.organizationId,projectId:c.s.scope.projectId,environmentId:stage.environmentId},accessMode:'read_write'}]}});
 await assert.rejects(third.client.request('/release-pipeline-run-stages/'+run.stages[0].id),e=>[403,404].includes(e.status));
 const thirdPage=await pageFor(third.username,width,'/delivery/pipeline-stages/'+stage.id);try{
 await thirdPage.page.getByRole('heading',{name:/^阶段 3 ·/}).waitFor();const preparedResponse=thirdPage.page.waitForResponse(r=>r.url().endsWith('/prepare-promotion')&&r.request().method()==='POST'&&r.status()===200);await thirdPage.page.getByRole('button',{name:'准备相邻环境晋级',exact:true}).click();const prepared=await (await preparedResponse).json();await thirdPage.page.waitForURL(c.s.endpoint+'/delivery/promotions/'+prepared.id+'**');await thirdPage.page.getByRole('heading',{name:'1. 来源制品与独立验收',exact:true}).waitFor();assert((await thirdPage.page.locator('main').innerText()).includes('Accepted'));assert(!(await thirdPage.page.locator('main').innerText()).includes(c.source.id));
 const options=await third.client.request('/release-promotions/'+prepared.id+'/mapping-options'),resource=c.resources.get(stage.environmentId),artifact=await third.client.request('/release-artifacts/'+prepared.artifactId),choice=options.applications.find(a=>a.id===resource.app.id);assert(choice);await thirdPage.page.getByRole('tab',{name:'3. 目标映射',exact:true}).click();for(const [index,route]of artifact.content.routes.entries()){const target=options.routes.find(r=>r.apiId===route.apiId&&r.path===route.path);if(target)await thirdPage.page.getByRole('combobox',{name:/^目标 Route/}).nth(index).selectOption(target.id);await thirdPage.page.getByRole('combobox',{name:/^目标 Cluster/}).nth(index).selectOption(resource.cluster.id);}await thirdPage.page.getByLabel(choice.name,{exact:true}).check();await thirdPage.page.getByLabel('尾号 '+choice.credentials.find(k=>k.id===resource.key.credential.id).last4,{exact:false}).check();for(const authorization of choice.authorizations)await thirdPage.page.getByLabel(authorization.apiId,{exact:false}).check();if(choice.sharedAcrossEnvironments||choice.requiredCredentialIds.length)await thirdPage.page.getByLabel('已核对共享影响，并完整保留未选 API 所需凭证',{exact:true}).check();
 const saved=thirdPage.page.waitForResponse(r=>r.url().endsWith('/release-promotions/'+prepared.id+'/mapping')&&r.request().method()==='PUT'&&r.status()===200);await thirdPage.page.getByRole('button',{name:'保存目标映射',exact:true}).click();await saved;await until(()=>third.client.request('/release-promotions/'+prepared.id),p=>p.mappingRevision>0,20);await thirdPage.page.getByRole('tab',{name:'4. 差异与证据',exact:true}).click();for(const port of [resource.ports.gatewayA,resource.ports.gatewayB]){const response=await fetch('http://127.0.0.1:'+port+'/orders',{headers:{'X-API-Key':resource.credential},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);assert.equal((await response.json()).backendId,resource.backendId);}await thirdPage.page.getByLabel('已实际核对目标后端健康与业务连通性（人工确认）',{exact:true}).check();await thirdPage.page.getByLabel('实际核对说明（至少 10 字）',{exact:true}).fill('实际调用本阶段两个独立 Gateway 的订单接口成功，核对目标后端与认证');await thirdPage.page.getByRole('tab',{name:'5. 发布预检',exact:true}).click();const prechecked=thirdPage.page.waitForResponse(r=>r.url().endsWith('/release-promotions/'+prepared.id+'/precheck')&&r.request().method()==='POST'&&r.status()===200);await thirdPage.page.getByRole('button',{name:'运行服务器预检',exact:true}).click();const precheck=await (await prechecked).json();assert.equal(precheck.canSubmit,true,JSON.stringify(precheck.checks));await thirdPage.page.getByText(/预检允许提交/).waitFor();flags.thirdStageDelegateMapping=true;flags.thirdStagePromotionId=prepared.id;await shot(thirdPage.page,width,'third-stage-delegate-precheck');
 }finally{await thirdPage.context.close();}
 }finally{const row=await c.s.admin.request('/release-pipeline-runs/'+run.id);if(!['Completed','Cancelled','Invalidated'].includes(row.status))await action(run.id,'cancel');}
 const release=c.pipelineProof.chains[1].stages.at(-1).actualReleaseId,returnPath='/approvals?environmentId='+c.target.id+'&view=AllVisible',back=await pageFor(c.state.bootstrapUsername,width,'/releases/'+release+'?returnTo='+encodeURIComponent(returnPath));await back.page.getByRole('link',{name:'晋级差异、执行与生产验证',exact:true}).click();await back.page.getByRole('link',{name:'返回审批筛选',exact:true}).click();await back.page.waitForURL(c.s.endpoint+returnPath);flags.returnFilters=true;await shot(back.page,width,'approval-return');await back.context.close();result.cases.push(flags);
 }
 assert.deepEqual(result.errors,[]);return result;
 }finally{await browser.close();if(idpStarted){await cleanupRestoredIdp({runtimeDirectory:c.directory,directory:idpDirectory});c.ctx=await preparePipelineContext(c.directory,c.state,c.release);await c.ctx.compose('up','-d','control-plane');await until(()=>c.s.admin.request('/auth/me'),r=>r.id,45);}}
}
