import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {coldBackup,restoreColdBackup} from '../runtime/acceptance-backup.mjs';import {initializeRuntime} from '../runtime/lifecycle.mjs';import {writePrivate} from '../runtime/state.mjs';import {freePorts} from '../runtime/acceptance.mjs';import {until} from '../runtime/acceptance-scenario.mjs';import {LocalClient} from '../local-client.mjs';import {preparePipelineContext,cleanupPipelineContext,pipelineRuntimeServices} from './pipeline-runtime.mjs';
const digest=b=>createHash('sha256').update(b).digest('hex');
export async function downloadPipelineReport(client,id){const response=await fetch(client.base+'/api/v1/verification-reports/'+id+'/download',{headers:{Cookie:[...client.cookies].map(([k,v])=>k+'='+v).join('; ')},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);assert.equal(response.headers.get('x-content-type-options'),'nosniff');return Buffer.from(await response.arrayBuffer());}
export async function runPipelineColdRestore(c){
 assert(c.report);const backup=path.join(c.directory,'pipeline-backup'),hashes=await coldBackup(c.ctx,backup,{contextFactory:preparePipelineContext});assert(hashes['verification-reports.tar']&&hashes['pipeline-runtime.json']);const projectName='webapi-enterprise-local-test-'+randomUUID(),directory=path.resolve('.runtime/tests',projectName),ports=await freePorts(),clonePorts=new Map();for(const g of c.groups)clonePorts.set(g.environmentId,g.kind==='Source'?ports:await freePorts());let cloneState;
 const factory=async(d,state,release)=>{if(d===directory){const file=path.join(d,'pipeline-runtime.json'),meta=JSON.parse(await fs.readFile(file,'utf8'));await writePrivate(file,{...meta,stageGroups:meta.stageGroups.map(g=>({...g,ports:clonePorts.get(g.environmentId)}))});const deliveryFile=path.join(d,'delivery-runtime.json'),delivery=JSON.parse(await fs.readFile(deliveryFile,'utf8'));await writePrivate(deliveryFile,{...delivery,ports:clonePorts.get(delivery.targetEnvironmentId)});}return preparePipelineContext(d,state,release);};
 try{const restored=await restoreColdBackup({target:backup,projectName,directory,ports,contextFactory:factory});cloneState=restored.state;await initializeRuntime({directory,projectName,ports,bootstrapUsername:c.state.bootstrapUsername,releaseFile:path.join(directory,'release.json')},{prepareContext:factory});await restored.ctx.compose('up','-d',...pipelineRuntimeServices(restored.ctx));const client=new LocalClient('http://127.0.0.1:'+ports.console);await client.login(c.state.bootstrapUsername,c.s.password);
 const restoredRuns=[];for(const original of c.pipelineProof.chains){const run=await client.request('/release-pipeline-runs/'+original.runId);assert.equal(run.status,'Completed');assert.equal(run.rootArtifactHash,original.rootArtifactHash);assert.equal(run.stages.length,original.stages.length);for(const expected of original.stages){const stage=await client.request('/release-pipeline-run-stages/'+expected.stageId);assert.equal(stage.status,'Passed');assert.equal(stage.actualReleaseId,expected.actualReleaseId);assert.equal(stage.actualConfigVersion,expected.configVersion);assert.equal(stage.actualDeploymentSequence,expected.deploymentSequence);}restoredRuns.push(run.id);}
 const stageGroups=[];for(const group of c.groups){const expected=c.resources.get(group.environmentId),allocated=clonePorts.get(group.environmentId);for(const port of [allocated.gatewayA,allocated.gatewayB])await until(async()=>{const response=await fetch('http://127.0.0.1:'+port+'/orders',{headers:{'X-API-Key':expected.credential},signal:AbortSignal.timeout(5000)});return response.ok?response.json():null;},body=>body?.backendId===expected.backendId&&body.receivedApiKey===false,90);stageGroups.push({order:group.order,environmentId:group.environmentId,ownerId:cloneState.ownerId,restored:true,gatewayCalls:2});}
 const originalBytes=await downloadPipelineReport(c.pipelineVerifier.client,c.report.id),restoredBytes=await downloadPipelineReport(client,c.report.id);assert.deepEqual(originalBytes,c.report.bytes);assert.deepEqual(restoredBytes,c.report.bytes);const metadata=await client.request('/release-promotions/'+c.report.promotionId+'/verifications');assert(metadata.filter(v=>v.reportId===c.report.id).length===3&&metadata.filter(v=>v.reportId===c.report.id).every(v=>v.reportHash===c.report.sha256));const reportPath='protected-restored-report.txt';await fs.writeFile(path.join(c.evidenceDirectory,reportPath),restoredBytes);
 const reports=[];for(const report of c.reports??[c.report]){const original=await downloadPipelineReport(c.pipelineVerifier.client,report.id),restored=await downloadPipelineReport(client,report.id);assert.deepEqual(original,report.bytes);assert.deepEqual(restored,report.bytes);const rows=await client.request('/release-promotions/'+report.promotionId+'/verifications'),bound=rows.filter(v=>v.reportId===report.id);assert.equal(bound.length,3);assert(bound.every(v=>v.reportHash===report.sha256));const file='protected-report-'+report.id+'.txt';await fs.writeFile(path.join(c.evidenceDirectory,file),restored);reports.push({reportId:report.id,promotionId:report.promotionId,metadataCount:bound.length,reportPath:file,reportSha256:report.sha256,originalReportSha256:digest(original),restoredReportSha256:digest(restored)});}
 return {passed:true,actual:true,freshOwner:cloneState.ownerId!==c.state.ownerId,ownerId:cloneState.ownerId,sourceOwnerId:c.state.ownerId,stageGroups,restoredRunIds:restoredRuns,metadataPreserved:true,reports,reportPath,reportId:c.report.id,reportSha256:c.report.sha256,originalReportSha256:digest(originalBytes),restoredReportSha256:digest(restoredBytes),databaseSha256:hashes['postgres.dump'],reportsArchiveSha256:hashes['verification-reports.tar'],manifestSha256:digest(await fs.readFile(path.join(backup,'backup-manifest.json')))};
 }finally{if(cloneState)await cleanupPipelineContext(directory,c.release,{expectedOwner:cloneState.ownerId});}
}
