import assert from 'node:assert/strict';
import {until,pause} from '../runtime/acceptance-scenario.mjs';

export async function mappedPromotion(c,{confirmShared=true}={}) {
 const {s,artifact,route,cluster,app,key,target}=c;
 let p=await s.admin.request('/release-promotions',{method:'POST',body:{artifactId:artifact.id}});
 const options=await s.admin.request('/release-promotions/'+p.id+'/mapping-options');
 const choice=options.applications.find(a=>a.id===app.id);
 assert(choice && !options.truncated);
 p=await s.admin.request('/release-promotions/'+p.id+'/mapping',{method:'PUT',headers:{'If-Match':`"${p.revision}"`},body:{routes:artifact.content.routes.map(r=>({artifactRouteKey:r.key,targetRouteId:route.id,clusterId:cluster.id,timeoutMs:30000,policies:[]})),applications:[{applicationId:app.id,credentialIds:[key.credential.id],authorizationIds:choice.authorizations.map(g=>g.id),confirmSharedCredentialImpact:confirmShared}]}});
 const precheck=await s.admin.request('/release-promotions/'+p.id+'/precheck',{method:'POST',body:{confirmUpstreamHealth:true,upstreamHealthComment:'实际调用独立目标上游，确认当前隔离业务响应'}});
 return {promotion:await s.admin.request('/release-promotions/'+p.id),precheck,options};
}
export async function readyPromotion(c) {
 const m=await mappedPromotion(c);assert.equal(m.precheck.canSubmit,true,JSON.stringify(m.precheck.checks));
 const p=await c.s.admin.request('/release-promotions/'+m.promotion.id+'/submit',{method:'POST',headers:{'If-Match':`"${m.promotion.revision}"`}});
 for(const actor of [c.first,c.second])await actor.client.request('/releases/'+p.targetReleaseId+'/approve',{method:'POST',body:{comment:'独立核对目标候选及恢复影响'}});
 return c.s.admin.request('/release-promotions/'+p.id);
}
export async function actualDeployment(c,p) {
 await c.s.admin.request('/releases/'+p.targetReleaseId+'/publish',{method:'POST'});
 const current=await until(()=>c.s.admin.request('/release-promotions/'+p.id),r=>{assert.notEqual(r.status,'DeploymentFailed');return r.status==='Verifying';});
 const release=await c.s.admin.request('/releases/'+current.deployment.releaseId);assert(release.targets.every(n=>n.acknowledged));return {promotion:current,release};
}
export async function recordProduction(c,p,{result='Passed',types=['EntryConnectivity','AuthenticationAuthorization','CriticalBusinessCall'],reportId=null}={}){
 const context=await c.verifier.client.request('/release-promotions/'+p.id+'/verification-context');c.lastVerificationContext=context;
 for(const type of types){const now=new Date().toISOString();await c.verifier.client.request('/release-promotions/'+p.id+'/verifications',{method:'POST',body:{type,result,startedAt:now,finishedAt:now,comment:'人工登记实际隔离环境的调用与业务核对结果',reportId,expectedContextHash:context.hash}});}
 return c.s.admin.request('/release-promotions/'+p.id);
}
export async function renewAcceptance(c){
 const ids=[];for(const type of ['InterfaceFunction','Integration','ContractCompatibility']){const now=new Date().toISOString(),v=await c.s.admin.request('/release-artifacts/'+c.artifact.id+'/verifications',{method:'POST',body:{type,result:'Passed',startedAt:now,finishedAt:now,comment:'独立测试来源真实调用仍通过，重新登记当前连接修订'}});ids.push(v.id);}
 const a=await c.s.admin.request('/release-artifacts/'+c.artifact.id+'/test-acceptances',{method:'POST',body:{verificationIds:ids}});
 c.acceptance=await c.acceptor.client.request('/test-acceptances/'+a.id+'/accept',{method:'POST',headers:{'If-Match':`"${a.revision}"`},body:{comment:'独立重验来源与当前连接'}});return c.acceptance;
}
export async function runPromotionFaults(c){
 const {ctx,s,target,proof,checkpoint}=c;const result={};const readEnv=()=>s.admin.request('/environments/'+target.id);
 await checkpoint('fault_partial_ack');const ready=await readyPromotion(c);await ctx.compose('stop','prod-gateway-b');
 await s.admin.request('/releases/'+ready.targetReleaseId+'/publish',{method:'POST'});
 const partial=await until(()=>s.admin.request('/releases/'+ready.targetReleaseId),r=>r.state==='Publishing'&&r.targets.length===2&&r.targets.filter(n=>n.acknowledged).length===1,60);
 assert.equal((await s.admin.request('/release-promotions/'+ready.id)).status,'Deploying');
 result.partialAck={passed:true,actual:true,releaseId:partial.id,sequence:partial.deploymentSequence,targets:partial.targets};
 await checkpoint('fault_worker_restart');await ctx.compose('restart','worker');await ctx.compose('up','-d','--force-recreate','control-plane');await until(()=>s.admin.request('/auth/me'),r=>r.id===proof.actors.applicant,30);
 const afterRestart=await s.admin.request('/releases/'+partial.id);assert.equal(afterRestart.deploymentSequence,partial.deploymentSequence);assert.equal((await readEnv()).deploymentSequence,partial.deploymentSequence);result.workerRestart={passed:true,actual:true,releaseId:partial.id,sequence:partial.deploymentSequence,persistedState:afterRestart.state};
 await checkpoint('fault_real_ack_timeout');const failed=await until(()=>s.admin.request('/releases/'+partial.id),r=>r.state==='Failed',180);assert.equal((await s.admin.request('/release-promotions/'+ready.id)).status,'DeploymentFailed');assert.equal(failed.targets.filter(n=>n.acknowledged).length,1);result.timeout={passed:true,actual:true,releaseId:failed.id,targets:failed.targets,errors:failed.errors};
 await ctx.compose('up','-d','prod-gateway-b');await until(()=>s.admin.request('/environments/'+target.id+'/gateway-nodes'),r=>r.items.every(n=>Date.now()-Date.parse(n.lastHeartbeatAt)<10000),30);const retry=await s.admin.request('/releases/'+failed.id+'/retry',{method:'POST'});const recovered=await until(()=>s.admin.request('/releases/'+retry.id),r=>r.state==='Succeeded'&&r.targets.every(n=>n.acknowledged));assert.equal(recovered.recoveryOf,failed.id);assert(recovered.deploymentSequence>failed.deploymentSequence);await until(()=>s.admin.request('/release-promotions/'+ready.id),p=>p.status==='Verifying');result.timeout.recovery={releaseId:recovered.id,sequence:recovered.deploymentSequence,targets:recovered.targets};
 await checkpoint('fault_business_validation_failure');await ctx.compose('stop','backend-b');const bad=await c.fetchProduction();assert(bad.status>=500);assert.equal((await s.request()).status,200);const envBefore=await readEnv(),failedVerification=await recordProduction(c,ready,{result:'Failed',types:['CriticalBusinessCall']});assert.equal(failedVerification.status,'VerificationFailed');assert.equal((await readEnv()).deploymentSequence,envBefore.deploymentSequence);result.verificationFailure={passed:true,actual:true,promotionId:ready.id,status:failedVerification.status,responseStatus:bad.status,noAutomaticRollbackSequence:envBefore.deploymentSequence};await ctx.compose('up','-d','backend-b');
 await checkpoint('fault_human_approved_rollback');const rollback=await s.admin.request('/releases/'+recovered.id+'/rollback',{method:'POST',body:{targetConfigVersion:c.completedRelease.targetConfigVersion}});await s.admin.request('/releases/'+rollback.id+'/submit',{method:'POST'});for(const actor of [c.first,c.second])await actor.client.request('/releases/'+rollback.id+'/approve',{method:'POST',body:{comment:'人工审批恢复此前已验证目标快照'}});await s.admin.request('/releases/'+rollback.id+'/publish',{method:'POST'});const rolled=await until(()=>s.admin.request('/releases/'+rollback.id),r=>r.state==='Succeeded'&&r.targets.every(n=>n.acknowledged));const rolledPromotion=await until(()=>s.admin.request('/release-promotions/'+ready.id),p=>p.status==='RolledBack');assert.equal(rolledPromotion.status,'RolledBack');assert(rolled.deploymentSequence>recovered.deploymentSequence);assert.equal((await readEnv()).gatewayPublicUrl,target.gatewayPublicUrl);assert.equal((await c.fetchProduction()).status,200);assert.equal((await s.admin.request('/release-promotions/'+c.completedPromotion.id)).status,'Completed');result.approvedRollback={passed:true,actual:true,promotionId:ready.id,releaseId:rolled.id,sequence:rolled.deploymentSequence,targetConfigVersion:rolled.targetConfigVersion,approvals:rolled.approvalSteps,targets:rolled.targets,addressPreserved:true,historicalCompletedPreserved:true};
 await checkpoint('fault_shared_application');await s.admin.request('/applications/'+c.app.id+'/permissions',{method:'POST',body:{apiId:s.api.id,environmentId:c.source.id,validFrom:new Date(Date.now()-60000).toISOString()}});const shared=await mappedPromotion(c,{confirmShared:false});assert.equal(shared.precheck.canSubmit,false);assert(shared.precheck.checks.some(x=>x.reasonCode==='shared_credential_confirmation_required'));const confirmed=await mappedPromotion(c,{confirmShared:true});assert.equal(confirmed.precheck.canSubmit,true);assert(confirmed.promotion.credentialImpact.some(i=>i.sharedAcrossEnvironments&&i.acknowledged));result.sharedApplication={passed:true,actual:true,blockedPromotionId:shared.promotion.id,confirmedPromotionId:confirmed.promotion.id,impact:confirmed.promotion.credentialImpact};
 await checkpoint('fault_queued_publisher_permission_withdrawal');const publisher=await c.createActor('可撤权的独立发布人','DeliveryPublisher',['release.publish'],{organizationId:s.scope.organizationId,projectId:s.scope.projectId});const queuedActor=await readyPromotion(c);await ctx.compose('stop','worker');const actorBefore=await readEnv();await publisher.client.request('/releases/'+queuedActor.targetReleaseId+'/publish',{method:'POST'});assert.equal((await s.admin.request('/releases/'+queuedActor.targetReleaseId)).state,'Building');let limited=await s.admin.request('/roles/'+publisher.role.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${publisher.role.revision}"`},body:{permissions:publisher.permissions.filter(p=>p!=='release.publish')}});try{await ctx.compose('up','-d','worker');const blocked=await until(()=>s.admin.request('/release-promotions/'+queuedActor.id),p=>p.status==='DeploymentFailed');assert.equal((await readEnv()).deploymentSequence,actorBefore.deploymentSequence);result.queuedAuthority={passed:true,actual:true,promotionId:blocked.id,publisherId:publisher.user.id,status:blocked.status,sequenceUnchanged:actorBefore.deploymentSequence};}finally{const roles=await s.admin.request('/roles');limited=roles.find(r=>r.id===publisher.role.id);await s.admin.request('/roles/'+limited.id+'/permissions',{method:'PUT',headers:{'If-Match':`"${limited.revision}"`},body:{permissions:publisher.permissions}});await ctx.compose('up','-d','worker');}
 await checkpoint('fault_queued_source_acceptance_revocation');const queued=await readyPromotion(c);await ctx.compose('stop','worker');const beforeQueue=await readEnv();await s.admin.request('/releases/'+queued.targetReleaseId+'/publish',{method:'POST'});assert.equal((await s.admin.request('/releases/'+queued.targetReleaseId)).state,'Building');const a=await c.acceptor.client.request('/test-acceptances/'+c.acceptance.id);await c.acceptor.client.request('/test-acceptances/'+a.id+'/revoke',{method:'POST',headers:{'If-Match':`"${a.revision}"`},body:{comment:'排队阶段独立撤销来源测试验收'}});await ctx.compose('up','-d','worker');const invalidated=await until(()=>s.admin.request('/release-promotions/'+queued.id),p=>p.status==='Invalidated');assert.equal((await s.admin.request('/releases/'+queued.targetReleaseId)).state,'Cancelled');await pause(2500);assert.equal((await readEnv()).deploymentSequence,beforeQueue.deploymentSequence);result.queuedRevocation={passed:true,actual:true,promotionId:invalidated.id,status:invalidated.status,releaseId:queued.targetReleaseId,sequenceUnchanged:beforeQueue.deploymentSequence};
 await renewAcceptance(c);await checkpoint('fault_delivery_connection_revision');const stale=await mappedPromotion(c);assert.equal(stale.precheck.canSubmit,true);const policy=await s.admin.request('/projects/'+s.scope.projectId+'/delivery-policy');await s.admin.request('/projects/'+s.scope.projectId+'/delivery-policy',{method:'PUT',headers:{'If-Match':`"${policy.revision}"`},body:{...policy,verificationValidityMinutes:1441}});await assert.rejects(s.admin.request('/release-promotions/'+stale.promotion.id+'/submit',{method:'POST',headers:{'If-Match':`"${stale.promotion.revision}"`}}),e=>e.status===409);assert.equal((await s.admin.request('/release-promotions/'+stale.promotion.id)).targetReleaseId,null);assert.equal((await readEnv()).deploymentSequence,beforeQueue.deploymentSequence);result.policyRevision={passed:true,actual:true,promotionId:stale.promotion.id,oldPolicyRevision:policy.revision,newPolicyRevision:policy.revision+1,noFormalRelease:true,sequenceUnchanged:beforeQueue.deploymentSequence};
 await renewAcceptance(c);const queuedPolicy=await readyPromotion(c);await ctx.compose('stop','worker');const policyBefore=await readEnv();await s.admin.request('/releases/'+queuedPolicy.targetReleaseId+'/publish',{method:'POST'});const currentPolicy=await s.admin.request('/projects/'+s.scope.projectId+'/delivery-policy');await s.admin.request('/projects/'+s.scope.projectId+'/delivery-policy',{method:'PUT',headers:{'If-Match':`"${currentPolicy.revision}"`},body:{...currentPolicy,verificationValidityMinutes:1442}});await ctx.compose('up','-d','worker');const queuedInvalid=await until(()=>s.admin.request('/release-promotions/'+queuedPolicy.id),p=>p.status==='DeploymentFailed');assert.equal((await readEnv()).deploymentSequence,policyBefore.deploymentSequence);result.policyRevision.queuedExecution={promotionId:queuedInvalid.id,status:queuedInvalid.status,sequenceUnchanged:policyBefore.deploymentSequence};
 return result;
}
