export const sourceTestTypes=[{value:'InterfaceFunction',label:'接口功能测试'},{value:'Integration',label:'集成测试'},{value:'ContractCompatibility',label:'契约兼容性测试'}];
export const productionTestTypes=[{value:'EntryConnectivity',label:'入口连通性'},{value:'AuthenticationAuthorization',label:'认证与授权'},{value:'CriticalBusinessCall',label:'关键业务调用'}];
export function deliveryAuthorityKey(user){return JSON.stringify([user?.id,[...(user?.permissions||[])].sort(),(user?.scopes||[]).map(x=>[x.scope.organizationId,x.scope.projectId??null,x.scope.environmentId??null,x.accessMode]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]);}
export function createDeliveryState(context={}){return {...context,epoch:0,data:undefined,draft:undefined,preview:undefined,conflict:false,error:''};}
const same=(s,t)=>t&&['actorAuthority','artifactId','sourceEnvironmentId','targetEnvironmentId','epoch'].every(k=>s[k]===t[k]);
export function deliveryReducer(state,event){if(event.type==='context'){const next=createDeliveryState(event.context);return {...next,epoch:state.epoch+1};}if(event.type==='draft'){if(state.authorized===false||(event.tag&&!same(state,event.tag)))return state;return {...state,draft:event.draft};}if(!same(state,event.tag))return state;if(event.type==='adopt'&&state.authorized!==false)return {...state,data:event.data,draft:event.draft,conflict:false,error:''};if(event.type==='loaded'&&state.authorized!==false)return {...state,data:event.data,error:'',conflict:false};if(event.type==='failed'){if([401,403,404].includes(event.status))return {...state,authorized:false,data:undefined,draft:undefined,preview:undefined,error:event.message||'访问已失效',conflict:false};return {...state,error:event.message||'操作失败',conflict:[409,412].includes(event.status)};}return state;}
export function manualEvidenceLabel(row){return row.isManual?'人工登记 · '+(row.result==='Passed'?'通过':'失败'):'来源未知 · 请核对证据';}
export function deliveryPolicyLabel(policy){return policy?.mode==='PipelineRequired'?'标准流水线交付门禁已启用':policy?.mode==='PromotionRequired'?'生产晋级门禁已启用':'生产晋级门禁未启用（Legacy）';}
export function verificationExpiryLabel(minutes){return `人工证据有效期：${minutes} 分钟，自测试结束时间起计算`;}
export function mayAcceptTest(row,userId){return row.status==='Requested'&&row.canAccept===true&&row.requestedBy!==userId;}

export function deliveryIsCurrent(state,context){return state.authorized!==false&&['actorAuthority','artifactId'].every(k=>state[k]===context[k]);}
export function promotionUrl(promotion,environment,side){const id=side==='source'?promotion.sourceEnvironmentId:promotion.targetEnvironmentId;if(environment?.id!==id||!environment.gatewayPublicUrl)return undefined;return environment.gatewayPublicUrl+(environment.basePath==='/'?'':environment.basePath||'');}
export function promotionMaySubmit(promotion,precheck){return promotion.status==='Draft'&&promotion.eligibility?.canSubmit===true&&precheck?.canSubmit===true&&precheck.mappingRevision===promotion.mappingRevision&&precheck.candidateHash===promotion.candidateHash&&precheck.revision===promotion.revision;}
export function mappingReady(mapping){return !!mapping?.routes?.length&&mapping.routes.every(r=>r.artifactRouteKey&&r.clusterId&&Number.isInteger(Number(r.timeoutMs))&&r.timeoutMs>=1&&r.timeoutMs<=300000&&Array.isArray(r.policies)&&r.policies.every(p=>p.type&&Number.isInteger(p.priority)));}
export function confirmationRequired(impact){return impact?.sharedAcrossEnvironments===true||(impact?.requiredCredentialIds?.length||0)>0;}
export function promotionExecutionLabel(p){return ({Draft:'晋级草稿',WaitingApproval:'等待生产审批',Ready:'审批完成 · 待执行',Deploying:'正在下发 · 核对实际节点',Verifying:'节点确认完成 · 待生产验证',Completed:'历史交付完成 · 当前节点另行核对',DeploymentFailed:'下发失败 · 核对部分已应用节点',VerificationFailed:'生产验证失败 · 需人工处置',RolledBack:'已按审批回滚',Invalidated:'条件失效 · 重新建立申请',Rejected:'生产审批拒绝',Cancelled:'晋级已取消'})[p?.status]||'状态待核对';}
export function mayRecordProduction(p,userId){return ['Verifying','VerificationFailed'].includes(p.status)&&p.eligibility?.canVerify===true&&p.requestedBy!==userId&&p.eligibility.publisherId!==userId;}
export function promotionReturnUrl(id,search=''){let returnTo=new URLSearchParams(search).get('returnTo');if(!returnTo||!/^\/approvals(?:\?|$)/.test(returnTo)||/[\\\x00-\x1f#]/.test(returnTo))returnTo=null;return '/delivery/promotions/'+id+(returnTo?'?returnTo='+encodeURIComponent(returnTo):'');}

export function promotionRiskLabel(risk){return risk?.visibility==='Restricted'?'风险资料受限':risk?.visibility==='Unavailable'?'风险资料不可用':risk?.counts?`破坏性 ${risk.counts.breaking} · 未知 ${risk.counts.unknown}`:'未关联风险评审';}
export function deliveryReasonLabel(code){return ({current_required_passed_evidence_incomplete:'当前必需测试证据不完整或未通过',source_acceptance_not_current:'来源验收已失效，需重新登记并验收',delivery_connection_changed:'交付连接已变化，需重新建立申请',target_baseline_changed:'目标运行基线已变化，需重新预检',target_entry_changed:'目标访问入口已变化，需重新预检',independent_test_acceptance_required:'需要独立测试验收人',independent_production_verification_required:'需要独立生产验证人',source_evidence_restricted:'来源证据受限',promotion_context_changed:'晋级条件已变化，需重新核对',source_acceptance_invalid:'来源验收已失效',target_baseline_missing:'目标缺少已确认运行基线',source_test_acceptance_required:'需要当前来源测试验收',current_source_deployment_required:'来源运行部署已变化',permission_required:'当前操作权限不足',current_required_evidence_incomplete:'当前必需证据不完整'})[code]||'当前资格条件未满足，请核对证据、修订和授权。';}

export function promotionCheckLabel(check){const known={current_accepted_source:'当前来源制品及独立验收已核对',target_resources_prepared:'目标资源映射已准备',snapshot_compiler_validated:'目标后端地址和环境策略已校验',public_entry_configured:'目标公开入口已配置（连通性另行验证）',public_entry_required:'目标需配置公开入口',configured_cohort_online:'完整目标节点组在线',gateway_cohort_unavailable:'完整目标节点组未在线或身份缺失',production_baseline_required:'目标必须先建立真实运行基线，未知基线阻止提交',current_production_snapshot_verified:'当前生产运行快照已核对',new_api_no_baseline_contract:'新增 API，无旧版契约',same_sealed_contract:'与目标基线采用同一冻结契约',baseline_comparison_required:'需保存目标基线到制品版本的契约比较',comparison_stale_or_invalid:'契约比较已失效，需重新比较',manual_risk_acceptance_required:'未知或破坏性契约需当前人工风险评审',risk_manually_accepted:'未知或破坏性契约已由人工接受风险',comparison_complete:'契约比较覆盖完整',manually_confirmed_not_automatically_executed:'目标后端由人工核对，系统未自动执行',manual_target_health_evidence_required:'需人工登记目标后端健康证据',two_level_independent_approval:'已配置两级独立生产审批',approval_policy_required:'需启用有效的两级独立审批规则',candidate_not_confirmed:'候选尚未确认，目标健康未知'};return known[check.reasonCode]||(check.status==='Passed'?'服务器检查通过':check.status==='Unknown'?'服务器检查结果未知，请补齐当前证据':deliveryReasonLabel(check.reasonCode));}
