import fs from 'node:fs/promises';import path from 'node:path';import net from 'node:net';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {assertOwnedSsoResources,validateSsoDirectory,sha256} from './evidence.mjs';
import {buildPolicySource,verifyPolicySource} from '../policies/build-source.mjs';
const execute=promisify(execFile),secret=()=>randomBytes(32).toString('base64url');
export function fixtureCookieNames(context){assertOwnedSsoResources(context,[]);return {session:'WebApi.Session.SsoFixture.'+context.owner,csrf:'WebApi.Csrf.SsoFixture.'+context.owner};}
export function validateFixtureConfiguration(context){assertOwnedSsoResources(context,[]);assert.match(context.image,/^quay\.io\/keycloak\/keycloak@sha256:[a-f0-9]{64}$/);const ports=Object.values(context.ports);assert.equal(ports.length,4);assert.equal(new Set(ports).size,4);for(const port of ports)assert.ok(Number.isInteger(port)&&port>=1024&&port<=65535&&![4192,4196,4197].includes(port),'Protected or invalid fixture port');return true;}
async function reservePorts(){const servers=[],ports={};try{for(const name of ['console','idp','controlPlane','controlPlaneB']){const server=net.createServer();await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});servers.push(server);ports[name]=server.address().port;}}finally{await Promise.all(servers.map(server=>new Promise(resolve=>server.close(resolve))));}return ports;}
export function commandFor(context){return async(binary,args,options={})=>{try{const result=await execute(binary,args,{cwd:context.root,maxBuffer:64*1024*1024,...options});await fs.appendFile(context.directory+'/operations.log',result.stdout+result.stderr,{mode:0o600});return result.stdout.trim();}catch(error){await fs.appendFile(context.directory+'/operations.log',(error.stdout||'')+(error.stderr||''),{mode:0o600});throw Error(binary+' '+args.slice(0,2).join(' ')+' failed; see private fixture operations log.');}};}
export const composeFor=context=>(...args)=>(context.run||commandFor(context))('docker',['compose','-p',context.project,'-f',context.directory+'/fixture-compose.json',...args]);
export async function waitFor(action,predicate,timeout=120000){const until=Date.now()+timeout;while(Date.now()<until){try{const result=await action();if(predicate(result))return result;}catch(error){if(error?.fatal)throw error;}await new Promise(resolve=>setTimeout(resolve,500));}throw Error('Isolated SSO fixture did not converge.');}
export async function createSsoFixture({root,retainForReview=false}){
 const owner=randomUUID(),project='webapi-sso-test-'+owner,directory=path.join(root,'.runtime',project),lock=JSON.parse(await fs.readFile(root+'/deploy/sso-images.lock.json')),images=JSON.parse(await fs.readFile(root+'/deploy/images.lock.json')),ports=await reservePorts(),context={root,owner,project,directory,ports,image:lock.keycloak,retainForReview};validateFixtureConfiguration(context);
 await fs.mkdir(directory,{recursive:true,mode:0o700});await fs.chmod(directory,0o700);await fs.writeFile(directory+'/owner.json',JSON.stringify({owner,project}),{mode:0o600});
 for(const name of ['postgres-password','admin-password','idp-password','idp-admin-password','client-secret'])await fs.writeFile(directory+'/'+name,secret(),{mode:0o600});await fs.mkdir(directory+'/keyring',{mode:0o700});
 await fs.mkdir(directory+'/observations',{mode:0o700});context.run=commandFor(context);const run=context.run,compose=composeFor(context);context.compose=compose;
 try{
  console.log('Freezing SSO source and building three isolated applications');const source=await buildPolicySource({root,outputDirectory:directory+'/build'});context.source=source;const publish=directory+'/build/publish';await fs.mkdir(publish);
  await fs.symlink(root+'/console/node_modules',source.sourceDirectory+'/console/node_modules');await run(process.execPath,[root+'/console/node_modules/typescript/bin/tsc','--noEmit'],{cwd:source.sourceDirectory+'/console'});await run(process.execPath,[root+'/console/node_modules/vite/bin/vite.js','build'],{cwd:source.sourceDirectory+'/console'});await fs.cp(source.sourceDirectory+'/console/dist',publish+'/console-dist',{recursive:true});
  const targets={'control-plane':'ControlPlane','console-host':'ConsoleHost',migrator:'Migrator','fixture-fault':'SsoFixtureHost'},script=['set -eu','export NUGET_PACKAGES=/build/.nuget','mkdir -p /build/.nuget; cp -a /nuget-seed/. /build/.nuget/'];for(const [target,name]of Object.entries(targets))script.push(`dotnet restore ${target==='fixture-fault'?'tests':'src'}/WebApi.${name}/WebApi.${name}.csproj ${target==='fixture-fault'?'':'--locked-mode'}`,`dotnet publish ${target==='fixture-fault'?'tests':'src'}/WebApi.${name}/WebApi.${name}.csproj -c Release --no-restore -o /build/publish/${target}`);
  await run('docker',['run','--rm','--workdir','/build/source','-v',directory+'/build:/build','-v','webapi-enterprise-core-test_nuget-test:/nuget-seed:ro',images.sdk,'bash','-c',script.join('\n')]);await verifyPolicySource(source);
  const tag='webapi-sso-fixture:'+source.sourceManifestHash.slice(0,20);await fs.writeFile(directory+'/build/Dockerfile',`ARG SDK_IMAGE\nFROM \${SDK_IMAGE}\nLABEL org.opencontainers.image.revision="${source.baseCommit}" com.webapi.sso.source-manifest="${source.sourceManifestHash}"\nWORKDIR /app\nCOPY publish/ /app/\nENV DOTNET_CLI_TELEMETRY_OPTOUT=1\n`);await run('docker',['build','--build-arg','SDK_IMAGE='+images.sdk,'-t',tag,directory+'/build']);const image=JSON.parse(await run('docker',['image','inspect',tag]))[0];assert.equal(image.Config.Labels['com.webapi.sso.source-manifest'],source.sourceManifestHash);context.runtimeImage={tag,digest:image.Id,baseCommit:source.baseCommit,sourceManifestHash:source.sourceManifestHash,classification:'actual-uncommitted-build-source'};
  const providerId=randomUUID(),subject=randomUUID(),unknownSubject=randomUUID(),consoleUrl='http://127.0.0.1:'+ports.console,idpUrl='http://localhost:'+ports.idp,issuer=idpUrl+'/realms/webapi-sso-fixture';Object.assign(context,{providerId,subject,unknownSubject,endpoints:{console:consoleUrl,idp:idpUrl,issuer,controlPlane:'http://127.0.0.1:'+ports.controlPlane,controlPlaneB:'http://127.0.0.1:'+ports.controlPlaneB}});
  const realm={realm:'webapi-sso-fixture',enabled:true,eventsEnabled:true,enabledEventTypes:['LOGIN','LOGIN_ERROR','CODE_TO_TOKEN','CODE_TO_TOKEN_ERROR'],registrationAllowed:false,resetPasswordAllowed:false,rememberMe:false,sslRequired:'none',clients:[{clientId:'webapi-console',enabled:true,publicClient:false,clientAuthenticatorType:'client-secret',secret:await fs.readFile(directory+'/client-secret','utf8'),standardFlowEnabled:true,directAccessGrantsEnabled:false,redirectUris:[consoleUrl+'/auth/oidc/callback/'+providerId],webOrigins:[],defaultClientScopes:['profile','email'],attributes:{'pkce.code.challenge.method':'S256'}}],users:[]};
  for(const [id,username]of [[subject,'fixture-sso'],[unknownSubject,'fixture-unknown']])realm.users.push({id,username,enabled:true,emailVerified:true,email:username+'@example.test',firstName:'验收',lastName:username,credentials:[{type:'password',value:await fs.readFile(directory+'/idp-password','utf8'),temporary:false}]});await fs.writeFile(directory+'/realm.json',JSON.stringify(realm),{mode:0o600});
  const cookies=fixtureCookieNames(context);const labels={'com.webapi.sso.owner':owner},volumes={'pg':{labels},'idp-data':{labels},'fault-flags':{labels}},common={image:tag,user:'0:0',working_dir:'/app',labels,volumes:[directory+'/postgres-password:/run/secrets/postgres-password:ro',directory+'/client-secret:/run/sso/enterprise:ro',directory+'/keyring:/fixture-keyring'],environment:{ASPNETCORE_ENVIRONMENT:'Development',ASPNETCORE_URLS:'http://0.0.0.0:8080',WEBAPI_DB_HOST:'postgres',WEBAPI_DB_NAME:'webapi',Authentication__CookieName:cookies.session,Antiforgery__CookieName:cookies.csrf,DataProtection__KeysDirectory:'/fixture-keyring',DataProtection__ApplicationName:'webapi-sso-'+owner,Sso__FixtureEnabled:'true',Sso__PublicBaseUrl:consoleUrl,Sso__AllowedOrigins__0:idpUrl,Sso__SecretFiles__enterprise:'/run/sso/enterprise',Sso__FixtureConnectOverridesJson:JSON.stringify({[idpUrl]:'oidc-fault'})},command:['dotnet','/app/control-plane/WebApi.ControlPlane.dll']};
  const configuration={services:{postgres:{image:images.postgres,labels,environment:{POSTGRES_USER:'webapi',POSTGRES_DB:'webapi',POSTGRES_PASSWORD_FILE:'/run/secrets/postgres-password'},volumes:['pg:/var/lib/postgresql/data',directory+'/postgres-password:/run/secrets/postgres-password:ro'],healthcheck:{test:['CMD-SHELL','pg_isready -U webapi -d webapi'],interval:'2s',timeout:'3s',retries:30}},keycloak:{image:lock.keycloak,user:'0:0',labels,command:['start-dev','--import-realm','--http-port='+ports.idp],environment:{KC_HOSTNAME:idpUrl,KC_HOSTNAME_STRICT:'true',KC_BOOTSTRAP_ADMIN_USERNAME:'fixture-idp-admin',KC_BOOTSTRAP_ADMIN_PASSWORD:await fs.readFile(directory+'/idp-admin-password','utf8')},volumes:['idp-data:/opt/keycloak/data',directory+'/realm.json:/opt/keycloak/data/import/realm.json:ro'],ports:['127.0.0.1:'+ports.idp+':'+ports.idp]},'oidc-fault':{image:tag,labels,command:['dotnet','/app/fixture-fault/WebApi.SsoFixtureHost.dll'],environment:{ASPNETCORE_URLS:'http://0.0.0.0:'+ports.idp,FixtureTarget:'http://keycloak:'+ports.idp},volumes:['fault-flags:/fixture-flags']},'control-plane':{...common,ports:['127.0.0.1:'+ports.controlPlane+':8080']},'control-plane-b':{...common,ports:['127.0.0.1:'+ports.controlPlaneB+':8080']},console:{image:tag,labels,command:['dotnet','/app/console-host/WebApi.ConsoleHost.dll'],environment:{ASPNETCORE_ENVIRONMENT:'Development',ASPNETCORE_URLS:'http://0.0.0.0:8080',Console__DistDirectory:'/app/console-dist',Console__ControlPlaneUrl:'http://control-plane:8080'}},'console-observer':{image:tag,labels,command:['dotnet','/app/fixture-fault/WebApi.SsoFixtureHost.dll'],environment:{ASPNETCORE_URLS:'http://0.0.0.0:8080',FixtureTarget:'http://console:8080',FixtureObserve:'true',FixtureSessionCookie:cookies.session,FixtureCsrfCookie:cookies.csrf},volumes:[directory+'/observations:/fixture-observations'],ports:['127.0.0.1:'+ports.console+':8080']}},volumes};
  await fs.writeFile(directory+'/fixture-compose.json',JSON.stringify(configuration,null,2),{mode:0o600});console.log('Starting owned Postgres and real Keycloak');await compose('up','-d','--wait','postgres');await compose('run','--rm','-v',directory+'/admin-password:/run/secrets/admin-password:ro','-e','WEBAPI_BOOTSTRAP_USERNAME=fixture-admin','-e','WEBAPI_BOOTSTRAP_PASSWORD_FILE=/run/secrets/admin-password','control-plane','dotnet','/app/migrator/WebApi.Migrator.dll','--bootstrap','--seed-catalog');await compose('up','-d','keycloak','oidc-fault','control-plane','control-plane-b','console','console-observer');await Promise.all([waitFor(()=>fetch(issuer+'/.well-known/openid-configuration'),r=>r.status===200),waitFor(()=>fetch(consoleUrl+'/health/live'),r=>r.status===200),waitFor(()=>fetch(context.endpoints.controlPlane+'/health/live'),r=>r.status===200)]);
  const stored={...context};delete stored.run;delete stored.compose;await fs.writeFile(directory+'/review-context.json',JSON.stringify(stored,null,2),{mode:0o600});return context;
 }catch(error){await cleanupSsoFixture(context).catch(()=>{});throw error;}
}
export async function cleanupSsoFixture(context){
 validateFixtureConfiguration(context);const real=await validateSsoDirectory(context),runtime=path.join(context.root,'.runtime');const parent=await fs.lstat(runtime);assert.ok(!parent.isSymbolicLink()&&parent.isDirectory());assert.equal(path.dirname(real),await fs.realpath(runtime),'Foreign fixture location');
 const run=context.run||commandFor(context),containers=(await run('docker',['ps','-aq','--filter','label=com.docker.compose.project='+context.project])).split('\n').filter(Boolean);for(const id of containers)assertOwnedSsoResources(context,[JSON.parse(await run('docker',['inspect','--format','{{json .Config.Labels}}',id]))]);
 const volumes=(await run('docker',['volume','ls','-q','--filter','label=com.docker.compose.project='+context.project])).split('\n').filter(Boolean);for(const name of volumes){assert.ok(name.startsWith(context.project+'_'),'Foreign volume');assertOwnedSsoResources(context,[JSON.parse(await run('docker',['volume','inspect','--format','{{json .Labels}}',name]))]);}
 if(containers.length||volumes.length)await composeFor({...context,run})('down','--volumes','--remove-orphans');assert.equal(await run('docker',['ps','-aq','--filter','label=com.docker.compose.project='+context.project]),'');assert.equal(await run('docker',['volume','ls','-q','--filter','label=com.docker.compose.project='+context.project]),'');
 const report={owner:context.owner,project:context.project,containersRemaining:0,volumesRemaining:0,secretsRemaining:0};await fs.rm(real,{recursive:true,force:true});return report;
}
