import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {setDefaultResultOrder} from 'node:dns';
import {LocalClient} from '../local-client.mjs';import {composeFor,waitFor} from './fixture.mjs';import {assertNoSecrets,sha256} from './evidence.mjs';
setDefaultResultOrder('ipv4first');
const decode=text=>text.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&#39;',"'");
export class SsoBrowser{
 constructor(){this.cookies=new Map();this.cookieEvidence=[];}
 async request(url,options={}){const uri=new URL(url),matching=[...this.cookies.values()].filter(c=>c.host===uri.hostname&&(uri.pathname===c.path||uri.pathname.startsWith(c.path.endsWith('/')?c.path:c.path+'/')));const response=await fetch(uri,{...options,redirect:'manual',headers:{...options.headers,Cookie:matching.map(c=>c.name+'='+c.value).join('; ')}});for(const header of response.headers.getSetCookie()){const parts=header.split(';').map(x=>x.trim()),at=parts[0].indexOf('='),name=parts[0].slice(0,at),value=parts[0].slice(at+1),cookiePath=parts.find(x=>x.toLowerCase().startsWith('path='))?.slice(5)||'/',key=uri.hostname+'|'+cookiePath+'|'+name;if(parts.some(x=>/^max-age=0$/i.test(x))||!value)this.cookies.delete(key);else this.cookies.set(key,{host:uri.hostname,path:cookiePath,name,value});this.cookieEvidence.push({name:name.startsWith('.WebApi.Oidc.Correlation.')?'correlation':name.startsWith('.WebApi.Oidc.Nonce.')?'nonce':name.startsWith('WebApi.Session')?'session':name.startsWith('WebApi.Csrf')?'csrf':'idp',httpOnly:parts.some(x=>x.toLowerCase()==='httponly'),sameSite:parts.find(x=>/^samesite=/i.test(x))?.slice(9)||null,path:cookiePath,secure:parts.some(x=>x.toLowerCase()==='secure')});}return response;}
 async me(base){return this.request(base+'/api/v1/auth/me');}
}
export async function prepareRealLogin(context,{username='fixture-sso',reauthenticate=false,browser=new SsoBrowser()}={}){
 const base=context.endpoints.console,csrfResponse=await browser.request(base+'/api/v1/auth/csrf');assert.equal(csrfResponse.status,200);const csrf=(await csrfResponse.json()).token,form=new URLSearchParams({__RequestVerificationToken:csrf,returnPath:'/organizations',reauthenticate:String(reauthenticate)}),start=await browser.request(base+'/api/v1/auth/sso/'+context.providerId+'/start',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:base},body:form});assert.equal(start.status,302,'SSO challenge');let location=start.headers.get('location');assert.equal(new URL(location).hostname,'localhost');let authorization;
 for(let i=0;i<8;i++){authorization=await browser.request(location);if(authorization.status===200)break;assert.ok([302,303].includes(authorization.status),'IdP authorization response');location=new URL(authorization.headers.get('location'),location).href;}
 assert.equal(authorization.status,200,'Keycloak login form');const html=await authorization.text(),action=/\bid="kc-form-login"[^>]*\baction="([^"]+)"/.exec(html)||/\baction="([^"]+)"[^>]*\bid="kc-form-login"/.exec(html);assert.ok(action,'Real Keycloak credential form');const target=decode(action[1]);assert.equal(new URL(target).origin,context.endpoints.idp);const login=await browser.request(target,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:context.endpoints.idp},body:new URLSearchParams({username,password:await fs.readFile(context.directory+'/idp-password','utf8'),credentialId:''})});assert.ok([302,303].includes(login.status),'Real IdP login redirects to callback');const callback=login.headers.get('location');assert.ok(callback.startsWith(base+'/auth/oidc/callback/'+context.providerId+'?'),'Exact registered callback');return {browser,callback};
}
export async function performRealLogin(context,options={}){const flow=await prepareRealLogin(context,options);const callbackResponse=await flow.browser.request(flow.callback);return {...flow,callbackResponse};}
export async function keycloakAdmin(context){const tokenResponse=await fetch(context.endpoints.idp+'/realms/master/protocol/openid-connect/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'password',client_id:'admin-cli',username:'fixture-idp-admin',password:await fs.readFile(context.directory+'/idp-admin-password','utf8')})});assert.equal(tokenResponse.status,200,'Isolated IdP provisioning authentication');const token=(await tokenResponse.json()).access_token;
 return async(path,options={})=>{const response=await fetch(context.endpoints.idp+'/admin/realms/webapi-sso-fixture'+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:options.body===undefined?undefined:JSON.stringify(options.body)});assert.ok(response.ok,'Isolated IdP provisioning response');return response.status===204?null:response.json();};
}
export async function runSsoScenario(context){const compose=composeFor(context),base=context.endpoints.console,password=await fs.readFile(context.directory+'/admin-password','utf8'),admin=new LocalClient(base);await admin.login('fixture-admin',password);const sql=query=>compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',query),check=(name,evidence)=>{checks.push({name,pass:true,evidence});console.log('Verified '+name);},checks=[],auditCount=async()=>Number(await sql("SELECT count(*) FROM audit_logs WHERE action='auth.sso.login'")),userCount=async()=>Number(await sql('SELECT count(*) FROM users')),write=(url,body,revision,method='POST')=>admin.request(url,{method,body,headers:revision===undefined?undefined:{'If-Match':'"'+revision+'"'}}),getProvider=()=>admin.request('/settings/sso/providers/'+context.providerId),operation=async name=>{const p=await getProvider();return write('/settings/sso/providers/'+p.id+'/'+name,{},p.revision);};
 const preserved=await sql("SELECT id::text||'|'||password_hash||'|'||security_stamp FROM users WHERE username='fixture-admin'");
 let provider=await write('/settings/sso/providers',{organizationId:null,name:'企业身份源 · Keycloak 验收',issuer:context.endpoints.issuer,clientId:'webapi-console',secretRef:'file://sso/enterprise',scopes:['openid','profile','email'],claimMapping:{displayName:'name',email:'email'}});context.providerId=provider.id;
 const idp=await keycloakAdmin(context),client=(await idp('/clients?clientId=webapi-console'))[0];await idp('/clients/'+client.id,{method:'PUT',body:{...client,redirectUris:[provider.callbackUrl]}});
 const ssoUser=await write('/users/sso',{username:'fixture-sso',displayName:'SSO 验收账号',email:'fixture-sso@example.test',providerId:provider.id,subject:context.subject});context.userId=ssoUser.id;
 const org=await write('/organizations',{code:'SSO',name:'身份验收组织'}),project=await write('/organizations/'+org.id+'/projects',{code:'SSO-CONSOLE',name:'控制台验收项目'}),env=await write('/projects/'+project.id+'/environments',{code:'QA',name:'身份验收环境',isProduction:false,sortOrder:0,releasePolicyId:null});context.scope={organizationId:org.id,projectId:project.id,environmentId:env.id};
 const role=(await admin.request('/roles')).find(r=>r.code==='Viewer');await write('/users/'+ssoUser.id+'/roles',{roleIds:[role.id]},ssoUser.revision,'PUT');let user=(await admin.request('/users')).items.find(u=>u.id===ssoUser.id);await write('/users/'+ssoUser.id+'/scopes',{scopes:[{scope:context.scope,accessMode:'read'}]},user.revision,'PUT');
 const tested=await operation('test');assert.equal(tested.status,'Passed');await operation('enable');await operation('default');
 const countBefore=await auditCount(),first=await performRealLogin(context);assert.equal(first.callbackResponse.status,303);assert.ok(first.callbackResponse.headers.get('location').startsWith('/auth/sso/complete'));const me=await first.browser.me(base);assert.equal(me.status,200);assert.equal((await me.json()).id,ssoUser.id);assert.equal(await auditCount(),countBefore+1);check('real-login',{meStatus:200,successAuditsAdded:1,explicitUser:true,issuerHost:'localhost',pkce:'S256',responseMode:'query'});
 const temporary=first.browser.cookieEvidence.filter(c=>['nonce','correlation'].includes(c.name));assert.ok(temporary.length>=2);for(const cookie of temporary){assert.equal(cookie.sameSite?.toLowerCase(),'lax');assert.equal(cookie.httpOnly,true);assert.equal(cookie.path,'/auth/oidc/callback/'+context.providerId);}assert.ok(first.browser.cookieEvidence.some(c=>c.name==='session'&&c.sameSite?.toLowerCase()==='strict'&&c.httpOnly));check('cross-site-cookies',{temporarySameSite:'Lax',platformSameSite:'Strict',temporaryHttpOnly:true,callbackPathLimited:true,verifiedOverHttp:true,browserSameSitePending:true});
 const beforeUnknown=await auditCount(),beforeUsers=await userCount(),unknown=await performRealLogin(context,{username:'fixture-unknown'});assert.equal(unknown.callbackResponse.status,303);assert.ok(unknown.callbackResponse.headers.get('location').startsWith('/login?ssoError='));assert.equal((await unknown.browser.me(base)).status,401);assert.equal(await auditCount(),beforeUnknown);assert.equal(await userCount(),beforeUsers);check('unknown-subject',{meStatus:401,successAuditsAdded:0,usersCreated:0});
 // A wrong secret passes structural preflight, but never establishes a platform session.
 const originalSecret=await fs.readFile(context.directory+'/client-secret','utf8');await fs.writeFile(context.directory+'/client-secret',randomBytes(32).toString('base64url'),{mode:0o600});await operation('rotate');const beforeWrong=await auditCount(),wrong=await performRealLogin(context);assert.equal(wrong.callbackResponse.status,303);assert.ok(wrong.callbackResponse.headers.get('location').startsWith('/login?ssoError='));assert.equal((await wrong.browser.me(base)).status,401);assert.equal(await auditCount(),beforeWrong);await fs.writeFile(context.directory+'/client-secret',originalSecret,{mode:0o600});await operation('rotate');check('wrong-secret',{meStatus:401,successAuditsAdded:0,structuralTestDoesNotProveClientAuthentication:true});
 const valid=await performRealLogin(context),cookieHeader=[...valid.browser.cookies.values()].filter(c=>c.host==='127.0.0.1'&&c.name.startsWith('WebApi.Session')).map(c=>c.name+'='+c.value).join('; ');assert.equal((await fetch(context.endpoints.controlPlaneB+'/api/v1/auth/me',{headers:{Cookie:cookieHeader}})).status,200);check('two-control-planes',{sharedDatabase:true,sharedPrivateKeyRing:true,secondInstanceMeStatus:200});
 const exchangeBefore=(await idp('/events?type=CODE_TO_TOKEN')).length,successBefore=await auditCount();await compose('restart','control-plane','keycloak');await waitFor(()=>fetch(base+'/health/live'),r=>r.status===200);await waitFor(()=>fetch(context.endpoints.issuer+'/.well-known/openid-configuration'),r=>r.status===200);await waitFor(()=>fetch(context.endpoints.controlPlane+'/health/live'),r=>r.status===200);assert.equal((await valid.browser.me(base)).status,200);const replay=await valid.browser.request(valid.callback);assert.equal(replay.status,303);assert.ok(replay.headers.get('location').startsWith('/login?ssoError='));assert.equal(await auditCount(),successBefore);const refreshedIdp=await keycloakAdmin(context);assert.equal((await refreshedIdp('/events?type=CODE_TO_TOKEN')).length,exchangeBefore);check('restart-replay',{meAfterRestart:200,successAuditsAdded:0,tokenExchangesAdded:0});
 await operation('disable');assert.equal((await valid.browser.me(base)).status,401);assert.equal((await fetch(context.endpoints.controlPlaneB+'/api/v1/auth/me',{headers:{Cookie:cookieHeader}})).status,401);await operation('test');await operation('enable');assert.equal((await valid.browser.me(base)).status,401);check('provider-revocation',{primaryMeStatus:401,secondaryMeStatus:401,reEnableRevivesOldSession:false});
 const beforeRotate=await performRealLogin(context);assert.equal((await beforeRotate.browser.me(base)).status,200);const newSecret=randomBytes(32).toString('base64url');await refreshedIdp('/clients/'+client.id,{method:'PUT',body:{...client,redirectUris:[provider.callbackUrl],secret:newSecret}});await fs.writeFile(context.directory+'/client-secret',newSecret,{mode:0o600});await operation('rotate');assert.equal((await beforeRotate.browser.me(base)).status,401);const afterRotate=await performRealLogin(context);assert.equal((await afterRotate.browser.me(base)).status,200);check('secret-rotation',{oldSessionMeStatus:401,newLoginMeStatus:200,explicitAuthRevision:true});
 const interrupted=await prepareRealLogin(context),beforeInterrupted=await auditCount(),exchangeBeforeInterrupted=(await refreshedIdp('/events?type=CODE_TO_TOKEN')).length;await compose('exec','-T','oidc-fault','sh','-c','touch /fixture-flags/block-token');const callback=interrupted.browser.request(interrupted.callback).catch(()=>null);await waitFor(()=>sql("SELECT count(*) FROM sso_login_attempts WHERE state='Processing'"),value=>Number(value)>0,10000);await compose('stop','-t','1','control-plane');await callback;await compose('exec','-T','oidc-fault','sh','-c','rm /fixture-flags/block-token');await compose('start','control-plane');await waitFor(()=>fetch(context.endpoints.controlPlane+'/health/live'),r=>r.status===200);const afterInterruption=await interrupted.browser.request(interrupted.callback);assert.equal(afterInterruption.status,303);assert.ok(afterInterruption.headers.get('location').startsWith('/login?ssoError='));assert.equal(await auditCount(),beforeInterrupted);assert.equal((await refreshedIdp('/events?type=CODE_TO_TOKEN')).length,exchangeBeforeInterrupted);check('interrupted-attempt',{durableProcessingObserved:true,replayAfterRestartRejected:true,successAuditsAdded:0,tokenExchangesAdded:0});
 await admin.login('fixture-admin',password);assert.equal((await admin.request('/auth/me')).username,'fixture-admin');assert.equal(await sql("SELECT id::text||'|'||password_hash||'|'||security_stamp FROM users WHERE username='fixture-admin'"),preserved);check('local-admin',{loginPassed:true,hashAndStampPreserved:true,username:'fixture-admin'});
 const result={schemaVersion:1,classification:'real-isolated-keycloak',complete:false,project:context.project,keycloakImage:context.image,image:context.runtimeImage,sameSiteEvidence:{platformHost:'127.0.0.1',idpHost:'localhost',browserVerified:false},checks,time:new Date().toISOString()};assertNoSecrets(result,await Promise.all(['postgres-password','admin-password','idp-password','idp-admin-password','client-secret'].map(name=>fs.readFile(context.directory+'/'+name,'utf8'))));return result;
}
