import {createContext,useContext,useEffect,useState,useRef,type ReactNode} from 'react';import {apiRequest,ApiError} from '../api/client';import type {Identity,Scope} from '../api/types';
type Session={user:Identity|null;loading:boolean;error:string;refresh:()=>Promise<void>;login:(u:string,p:string)=>Promise<void>;logout:()=>Promise<void>;can:(code:string,scope?:Scope,write?:boolean)=>boolean};
const Context=createContext<Session>(null!);
export function SessionProvider({children}:{children:ReactNode}){const[user,setUser]=useState<Identity|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const pending=useRef<Promise<void>|null>(null);
 function refresh():Promise<void>{if(pending.current)return pending.current;const run=(async()=>{try{setUser(await apiRequest<Identity>('/auth/me'));setError('');}catch(e){if(e instanceof ApiError&&[401,403,404].includes(e.status))setUser(null);else setError('会话与权限刷新失败：'+(e as Error).message);}finally{setLoading(false);pending.current=null;}})();pending.current=run;return run;}
 useEffect(()=>{void refresh();const expired=()=>setUser(null),denied=()=>{void refresh();};window.addEventListener('session-expired',expired);window.addEventListener('permission-refresh',denied);return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('permission-refresh',denied);};},[]);
 const can=(code:string,scope?:Scope,write=false)=>!error&&!!user?.permissions.includes(code)&&(!scope||user.scopes.some(g=>g.scope.organizationId===scope.organizationId&&(!g.scope.projectId||g.scope.projectId===scope.projectId)&&(!g.scope.environmentId||g.scope.environmentId===scope.environmentId)&&(!write||g.accessMode==='read_write')));
 return <Context.Provider value={{user,loading,error,refresh,can,login:async(username,password)=>{setUser(await apiRequest<Identity>('/auth/login',{method:'POST',body:{username,password}}));setError('');},logout:async()=>{await apiRequest('/auth/logout',{method:'POST'});setUser(null);}}}>{children}</Context.Provider>;
}export const useSession=()=>useContext(Context);
