<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../WebApi.NotificationFixtureHost/WebApi.NotificationFixtureHost.csproj"/><FrameworkReference Include="Microsoft.AspNetCore.App"/><ProjectReference Include="../../src/WebApi.ControlPlane/WebApi.ControlPlane.csproj"/><ProjectReference Include="../../src/WebApi.ConsoleHost/WebApi.ConsoleHost.csproj"/></ItemGroup></Project>
