using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Common;
using WebApi.Contracts.Applications;
using WebApi.Contracts.Security;
using WebApi.Infrastructure.Governance;
using WebApi.Infrastructure.Persistence;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Infrastructure.Security;
namespace WebApi.Infrastructure.Applications;
public sealed class ApplicationService(WebApiDbContext db,AuthorizationService auth,ScopeResolver scopes,AuditedCommandExecutor commands)
{
    public static ApplicationDto Dto(ApplicationRecord a)=>new(a.Id,a.OrganizationId,a.ProjectId,a.Code,a.Name,a.Owner,a.Status,a.Revision);
    public static CredentialDto Dto(ApplicationCredential c)=>new(c.Id,c.ApplicationId,c.AccessKey,c.SecretLast4,c.Status,c.ValidFrom,c.ExpiresAt,c.LastUsedAt,c.RevokedAt,c.Revision);
    public static ApplicationPermissionDto Dto(ApplicationApiPermission p)=>new(p.Id,p.ApplicationId,p.ApiId,p.EnvironmentId,p.ValidFrom,p.ExpiresAt,p.Revision);
    private async Task<ScopeRef> InputScopeAsync(SaveApplicationRequest request,CancellationToken ct)
    {if(request.ProjectId is Guid id) {var actual=await scopes.ProjectAsync(id,ct);if(actual.OrganizationId!=request.OrganizationId) throw new ApiException(422,"foreign_project","应用项目不属于组织。");return actual;}if(!await db.Set<Organization>().AnyAsync(o=>o.Id==request.OrganizationId,ct)) throw new ApiException(422,"invalid_organization","组织不存在。");return new(request.OrganizationId);}
    private static void Validate(SaveApplicationRequest r) {GovernanceService.Validate(r.Code,r.Name,r.Status);if(string.IsNullOrWhiteSpace(r.Owner)||r.Owner.Length>128) throw new ApiException(422,"invalid_owner","应用Owner不合法。");}
    public async Task<PageResult<ApplicationDto>> ListAsync(ActorContext actor,int page,int size,CancellationToken ct=default)
    {var apps=await db.Set<ApplicationRecord>().AsNoTracking().OrderBy(a=>a.Code).ToArrayAsync(ct);var result=new List<ApplicationDto>();foreach(var a in apps) if(await auth.CanAsync(actor,"app.read",new("application",a.Id,new(a.OrganizationId,a.ProjectId)),ct)) result.Add(Dto(a));return Pagination.Slice(result,page,size);}
    public async Task<ApplicationDetailDto> DetailAsync(Guid id,ActorContext actor,CancellationToken ct=default)
    {
        var scope=await scopes.ApplicationAsync(id,ct);if(!await auth.CanAsync(actor,"app.read",new("application",id,scope),ct)) throw ScopeResolver.Missing();var app=await db.Set<ApplicationRecord>().AsNoTracking().SingleAsync(a=>a.Id==id,ct);
        var credentials=await db.Set<ApplicationCredential>().AsNoTracking().Where(c=>c.ApplicationId==id).Select(c=>Dto(c)).ToArrayAsync(ct);var grants=await db.Set<ApplicationApiPermission>().AsNoTracking().Where(p=>p.ApplicationId==id).Select(p=>Dto(p)).ToArrayAsync(ct);
        var allowedGrants=new List<ApplicationPermissionDto>();var runtime=new Dictionary<Guid,long?>();foreach(var p in grants) {var envScope=await scopes.EnvironmentAsync(p.EnvironmentId,ct);if(!await auth.CanAsync(actor,"app.read",new("environment",p.EnvironmentId,envScope),ct)) continue;allowedGrants.Add(p);if(runtime.ContainsKey(p.EnvironmentId)) continue;var nodes=await db.Set<GatewayNode>().AsNoTracking().Where(n=>n.EnvironmentId==p.EnvironmentId&&n.Enabled).ToArrayAsync(ct);runtime[p.EnvironmentId]=nodes.Length>0&&nodes.All(n=>n.LastHeartbeatAt>DateTimeOffset.UtcNow.AddSeconds(-30))&&nodes.Select(n=>n.CurrentConfigVersion).Distinct().Count()==1?nodes[0].CurrentConfigVersion:null;}
        return new(Dto(app),credentials,allowedGrants,runtime);
    }
    public async Task<CommandResult<ApplicationDto>> CreateAsync(SaveApplicationRequest request,ActorContext actor,CancellationToken ct=default)
    {var scope=await InputScopeAsync(request,ct);return await commands.ExecuteAsync(actor,scope,"app.create",async(_,token)=>{await auth.RequireAsync(actor,"app.write",new("scope",request.ProjectId??request.OrganizationId,scope),token);Validate(request);var app=new ApplicationRecord {OrganizationId=request.OrganizationId,ProjectId=request.ProjectId,Code=request.Code,Name=request.Name,Owner=request.Owner,Status=request.Status};db.Add(app);return new CommandResult<ApplicationDto>(Dto(app),RevisionTag.Format(app.Revision));},ct);}
    public async Task<CommandResult<ApplicationDto>> SaveAsync(Guid id,SaveApplicationRequest request,string? tag,ActorContext actor,CancellationToken ct=default)
    {var scope=await scopes.ApplicationAsync(id,ct);return await commands.ExecuteAsync(actor,scope,"app.update",async(_,token)=>{await auth.RequireAsync(actor,"app.write",new("application",id,scope),token);var a=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==id,token);RevisionTag.Require(tag,a.Revision);if(a.OrganizationId!=request.OrganizationId||a.ProjectId!=request.ProjectId) throw new ApiException(422,"application_scope_immutable","应用不能直接移动到其他组织或项目。");Validate(request);a.Code=request.Code;a.Name=request.Name;a.Owner=request.Owner;a.Status=request.Status;a.Revision++;a.UpdatedAt=DateTimeOffset.UtcNow;return new CommandResult<ApplicationDto>(Dto(a),RevisionTag.Format(a.Revision));},ct);}
    public async Task DeleteAsync(Guid id,string? tag,ActorContext actor,CancellationToken ct=default)
    {var scope=await scopes.ApplicationAsync(id,ct);await commands.ExecuteAsync(actor,scope,"app.delete",async(_,token)=>{await auth.RequireAsync(actor,"app.write",new("application",id,scope),token);var a=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==id,token);RevisionTag.Require(tag,a.Revision);if(await db.Set<ApplicationCredential>().AnyAsync(c=>c.ApplicationId==id,token)||await db.Set<ApplicationApiPermission>().AnyAsync(p=>p.ApplicationId==id,token)) throw new ApiException(409,"application_in_use","应用存在凭证或授权，请先停用。");db.Remove(a);return true;},ct);}
    private static void ValidateWindow(DateTimeOffset from,DateTimeOffset? expires) {if(from==DateTimeOffset.MinValue||expires<=from) throw new ApiException(422,"invalid_validity_window","有效期结束必须晚于开始时间。");}
    public async Task<CredentialCreateResponse> CreateCredentialAsync(Guid applicationId,CredentialCreateRequest request,ActorContext actor,CancellationToken ct=default)
    {var scope=await scopes.ApplicationAsync(applicationId,ct);return await commands.ExecuteAsync(actor,scope,"credential.create",async(_,token)=>{await auth.RequireAsync(actor,"credential.manage",new("application",applicationId,scope),token);ValidateWindow(request.ValidFrom,request.ExpiresAt);var app=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==applicationId,token);if(app.Status!="Active") throw new ApiException(409,"application_disabled","停用应用不能创建凭证。");var material=ApiKeySecret.Create();var c=new ApplicationCredential {ApplicationId=applicationId,AccessKey=material.AccessKey,SecretHash=material.Hash,SecretLast4=material.Last4,Status="Active",ValidFrom=request.ValidFrom.ToUniversalTime(),ExpiresAt=request.ExpiresAt.ToUniversalTime()};db.Add(c);app.Revision++;app.UpdatedAt=DateTimeOffset.UtcNow;return new CredentialCreateResponse(Dto(c),material.Secret,material.AccessKey+"."+material.Secret);},ct);}
    public async Task<CredentialDto> CredentialAsync(Guid id,ActorContext actor,CancellationToken ct=default)
    {var c=await db.Set<ApplicationCredential>().AsNoTracking().SingleOrDefaultAsync(c=>c.Id==id,ct)??throw ScopeResolver.Missing();var scope=await scopes.ApplicationAsync(c.ApplicationId,ct);if(!await auth.CanAsync(actor,"app.read",new("credential",id,scope),ct)) throw ScopeResolver.Missing();return Dto(c);}
    public async Task<CommandResult<CredentialDto>> SaveCredentialAsync(Guid id,CredentialUpdateRequest request,string? tag,ActorContext actor,CancellationToken ct=default)
    {var existing=await db.Set<ApplicationCredential>().AsNoTracking().SingleOrDefaultAsync(c=>c.Id==id,ct)??throw ScopeResolver.Missing();var scope=await scopes.ApplicationAsync(existing.ApplicationId,ct);return await commands.ExecuteAsync(actor,scope,"credential.update",async(_,token)=>{await auth.RequireAsync(actor,"credential.manage",new("credential",id,scope),token);var c=await db.Set<ApplicationCredential>().SingleAsync(c=>c.Id==id,token);RevisionTag.Require(tag,c.Revision);ValidateWindow(request.ValidFrom,request.ExpiresAt);if(request.Status is not ("Active" or "Revoked")||c.Status=="Revoked"&&request.Status!="Revoked") throw new ApiException(409,"credential_revoked","已撤销凭证不能重新激活。");c.ValidFrom=request.ValidFrom.ToUniversalTime();c.ExpiresAt=request.ExpiresAt.ToUniversalTime();c.Status=request.Status;if(c.Status=="Revoked") c.RevokedAt??=DateTimeOffset.UtcNow;c.Revision++;var app=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==c.ApplicationId,token);app.Revision++;app.UpdatedAt=DateTimeOffset.UtcNow;return new CommandResult<CredentialDto>(Dto(c),RevisionTag.Format(c.Revision));},ct);}
    public async Task<CommandResult<ApplicationPermissionDto>> SavePermissionAsync(Guid applicationId,Guid? id,PermissionSaveRequest request,string? tag,ActorContext actor,CancellationToken ct=default)
    {
        var appScope=await scopes.ApplicationAsync(applicationId,ct);var envScope=await scopes.EnvironmentAsync(request.EnvironmentId,ct);return await commands.ExecuteAsync(actor,envScope,"app.permission.save",async(_,token)=>{
            await auth.RequireAsync(actor,"app.permission.manage",new("application",applicationId,appScope),token);await auth.RequireAsync(actor,"app.permission.manage",new("environment",request.EnvironmentId,envScope),token);var apiScope=await scopes.ApiAsync(request.ApiId,token);
            if(apiScope.OrganizationId!=appScope.OrganizationId||apiScope.OrganizationId!=envScope.OrganizationId||apiScope.ProjectId!=envScope.ProjectId||appScope.ProjectId is Guid project&&project!=apiScope.ProjectId) throw new ApiException(422,"foreign_authorization","应用、API与环境范围不一致。");ValidateWindow(request.ValidFrom,request.ExpiresAt);
            var p=id is Guid existing?await db.Set<ApplicationApiPermission>().SingleOrDefaultAsync(p=>p.Id==existing&&p.ApplicationId==applicationId,token)??throw ScopeResolver.Missing():new ApplicationApiPermission {ApplicationId=applicationId,CreatedBy=actor.UserId};if(id is null) db.Add(p);else {RevisionTag.Require(tag,p.Revision);p.Revision++;}
            p.ApiId=request.ApiId;p.EnvironmentId=request.EnvironmentId;p.ValidFrom=request.ValidFrom.ToUniversalTime();p.ExpiresAt=request.ExpiresAt?.ToUniversalTime();var app=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==applicationId,token);app.Revision++;app.UpdatedAt=DateTimeOffset.UtcNow;return new CommandResult<ApplicationPermissionDto>(Dto(p),RevisionTag.Format(p.Revision));
        },ct);
    }
    public async Task DeletePermissionAsync(Guid id,string? tag,ActorContext actor,CancellationToken ct=default)
    {var existing=await db.Set<ApplicationApiPermission>().AsNoTracking().SingleOrDefaultAsync(p=>p.Id==id,ct)??throw ScopeResolver.Missing();var scope=await scopes.EnvironmentAsync(existing.EnvironmentId,ct);var appScope=await scopes.ApplicationAsync(existing.ApplicationId,ct);await commands.ExecuteAsync(actor,scope,"app.permission.delete",async(_,token)=>{await auth.RequireAsync(actor,"app.permission.manage",new("application",existing.ApplicationId,appScope),token);await auth.RequireAsync(actor,"app.permission.manage",new("environment",existing.EnvironmentId,scope),token);var p=await db.Set<ApplicationApiPermission>().SingleAsync(p=>p.Id==id,token);RevisionTag.Require(tag,p.Revision);db.Remove(p);var a=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==p.ApplicationId,token);a.Revision++;a.UpdatedAt=DateTimeOffset.UtcNow;return true;},ct);}
}
