using WebApi.Contracts.Comparisons;
namespace WebApi.Infrastructure.Comparisons.Rules;
public static class OpenApiRuleCatalog
{
    public static IReadOnlyList<CompatibilityRuleDescriptor> All {get;}=[
        new("openapi.operations","operations",["oas-3.0","oas-3.1"],["operation.add","operation.remove","path.template_ambiguity","OperationMetadataChangesRemainVisibleWithoutContractRisk"],"新增操作保留已有域；删除已声明操作是明确破坏证据；元数据单独标注","模板匹配歧义或对象无法解析"),
        new("openapi.parameters","parameters",["oas-3.0","oas-3.1"],["parameter.path_inheritance","parameter.defaults","parameter.serialization","parameter.header_case","parameter.required","parameter.content","MaintainedRequestParametersAreProvedTogetherAndRemovalStaysUnknown","UndefinedComplexParameterWireCannotClaimComplete","ContradictoryMaintainedParameterSourceRemainsVisible"],"继承/覆盖及默认编码一致后证明完整请求父域","参数移除、来源冲突或 wire 编码不明；复杂 query 编码保守评审"),
        new("openapi.request","request",["oas-3.0","oas-3.1"],["request.required","request.media_remove","request.media_add","request.encoding","schema.cross_dialect_nullable","FullHttpParentEmptinessPreventsParameterAndStatusFalsePositives"],"认证、参数和请求体合成完整域，使用充分证明或实际反例","媒体范围、编码或父约束未证明"),
        new("openapi.responses","responses",["oas-3.0","oas-3.1"],["response.range_narrow","response.new_status","response.explicit_priority","response.default_priority","response.media_narrow","response.new_media","response.header_schema","response.required_header_remove","MaintainedResponsesUseExactStatusBeforeDefault","MaintainedDefaultResponseCoversStatusesBeyondTwoHundred","UnmappedMaintainedResponseChangesAreIncludedInOperationParent","UnknownResponseHeaderStyleCannotClaimComplete"],"有限状态码精确/范围/default 优先选择；维护响应纳入完整目标域包含于旧域","来源冲突、头、媒体或父约束未证明"),
        new("openapi.security","security",["oas-3.0","oas-3.1"],["security.inheritance","security.anonymous","security.tighten","security.or_and","security.and_or","security.scope_tighten","security.scope_relax","security.implementation_change","OrAndAndScopesArePositiveFullPredicates","NonOAuthRolesRespectTheSelectedOpenApiDialect","OAuthFlowStructureAndUnknownFieldsAreNotSilentlyIgnored","ReferencedOperationResolvesAuthenticationInItsOwnSourceDocument"],"相同认证实现的匿名/OR/AND/scope 或3.1角色可用域包含，整体请求复核","认证实现缺失、未登记字段或改变；不证明实际签名/token 接入"),
        new("openapi.coverage","coverage",["oas-3.0","oas-3.1"],["callback.visible_coverage","extension.visible_coverage","ImportedVersionComparesOnlyItsSelectedOperationWhileKeepingTheWholeSourcePackage","ComparisonUsesImmutableExternalSourcesRatherThanFetchingOrDroppingThem","MappedMaintenanceDoesNotEraseOriginalSourceConflict","UnusedSchemasHaveStructuralReferenceAndDynamicCoverage","StrictModeCoversUnusedUnregisteredFormats","PreviouslySavedIndependentMaintenanceSourceCanBeReconstructed","V2AdmitsLegalDocumentAndSourcePairAboveTheOldTwoMiBLimit","PrivateMaintenanceDocumentMayExceedOneSourceDocumentButNotSideBudget","ReferenceChainCannotExceedThePrivateTraversalBudget","OpenApiFindingPointersDoNotConcatenateTwoDocumentRoots","CurrentRulesRecordTheParameterAndSecurityFamiliesActuallyApplied"],"固定来源完整且登记字段已纳入父约束；预算、来源与规则摘要可核对","callbacks/webhooks/自定义扩展、动态/递归、未知来源行为或模式")
    ];
}
