using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Xunit;
namespace WebApi.EndToEnd.Tests;
public sealed class ExternalScenario : IAsyncDisposable
{
    private readonly HttpClient api=new(new HttpClientHandler{CookieContainer=new CookieContainer(),AllowAutoRedirect=false});private readonly List<HttpClient> reviewers=[];private HttpClient[] gateways=[];private JsonElement context;private string credential="";private int version;
    public static async Task<ExternalScenario> ConnectAsync()
    {
        var file=System.Environment.GetEnvironmentVariable("WEBAPI_E2E_CONTEXT_FILE");Assert.True(file is not null&&File.Exists(file),"E2E requires dedicated Compose and context; run scripts/e2e.sh.");var s=new ExternalScenario{context=JsonDocument.Parse(await File.ReadAllTextAsync(file!)).RootElement.Clone()};s.api.BaseAddress=new Uri("http://control-plane:8080");s.gateways=[new(){BaseAddress=new Uri("http://gateway-a:8080")},new(){BaseAddress=new Uri("http://gateway-b:8080")}];await s.LoginAsync(s.api,"e2e-admin");foreach(var username in new[]{"e2e-approver","e2e-security"}){var client=new HttpClient(new HttpClientHandler{CookieContainer=new CookieContainer()}){BaseAddress=s.api.BaseAddress};await s.LoginAsync(client,username);s.reviewers.Add(client);}var versions=await s.GetAsync($"/apis/{s.Id("apiId")}/versions");s.version=versions.EnumerateArray().Select(v=>int.TryParse(v.GetProperty("version").GetString()!.Split('.')[0],out var n)?n:0).DefaultIfEmpty().Max();s.credential=await File.ReadAllTextAsync(s.context.GetProperty("credentialFile").GetString()!);return s;
    }
    public async Task LoginAsync(HttpClient client,string username)=>await WriteAsync(client,"/auth/login",new{username,password=await File.ReadAllTextAsync(context.GetProperty("passwordFile").GetString()!)});
    public static async Task<JsonElement> WriteAsync(HttpClient client,string path,object? body=null,string? etag=null,string method="POST")
    {using var csrf=await client.GetAsync("/api/v1/auth/csrf");csrf.EnsureSuccessStatusCode();var token=(await csrf.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("token").GetString();using var request=new HttpRequestMessage(new(method),"/api/v1"+path){Content=body is null?null:JsonContent.Create(body)};request.Headers.Add("X-CSRF-Token",token);request.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString("N"));if(etag is not null)request.Headers.Add("If-Match",etag);using var response=await client.SendAsync(request);Assert.True(response.IsSuccessStatusCode,$"{path} failed HTTP {(int)response.StatusCode}");return response.StatusCode==HttpStatusCode.NoContent?default:await response.Content.ReadFromJsonAsync<JsonElement>();}
    private string Id(string name)=>context.GetProperty(name).GetString()!;
    public async Task<JsonElement> GetAsync(string path){using var r=await api.GetAsync("/api/v1"+path);r.EnsureSuccessStatusCode();return await r.Content.ReadFromJsonAsync<JsonElement>();}
    public async Task<JsonElement> PublishAsync(string backend,string routePath="/orders")
    {
        version++;var v=await WriteAsync(api,$"/apis/{Id("apiId")}/versions",new{version=$"{version}.0.0"});var cluster=await GetAsync($"/clusters/{Id("clusterId")}");var dst=cluster.GetProperty("destinations")[0];await WriteAsync(api,$"/destinations/{dst.GetProperty("id").GetString()}",new{name="test-backend",address=$"http://backend-{backend.ToLowerInvariant()}:8080/",weight=1,enabled=true},$"\"{dst.GetProperty("revision").GetInt64()}\"","PUT");var routes=await GetAsync($"/environments/{Id("environmentId")}/routes");var existing=routes.GetProperty("items").EnumerateArray().FirstOrDefault();var routeBody=new{apiVersionId=v.GetProperty("id").GetString(),routeName="Orders",path=routePath,methods=new[]{"GET"},clusterId=Id("clusterId"),priority=100,enabled=true,timeoutMs=30000};if(existing.ValueKind==JsonValueKind.Undefined)await WriteAsync(api,$"/environments/{Id("environmentId")}/routes",routeBody);else await WriteAsync(api,$"/routes/{existing.GetProperty("id").GetString()}",routeBody,$"\"{existing.GetProperty("revision").GetInt64()}\"","PUT");
        var env=await GetAsync($"/environments/{Id("environmentId")}");var current=env.GetProperty("desiredConfigVersion");var r=await WriteAsync(api,$"/environments/{Id("environmentId")}/releases",new{baseConfigVersion=current.ValueKind==JsonValueKind.Null?0:current.GetInt64(),versionIds=new[]{v.GetProperty("id").GetString()},resourceRevisions=new[]{new{type="version",id=v.GetProperty("id").GetString(),revision=v.GetProperty("revision").GetInt64()}}});var id=r.GetProperty("id").GetString()!;await ApproveAndPublishAsync(id);return await WaitAsync(id);
    }
    private async Task ApproveAndPublishAsync(string id)
    {await WriteAsync(api,$"/releases/{id}/submit");await WriteAsync(reviewers[0],$"/releases/{id}/approve",new{comment="独立 API 验收审核"});await WriteAsync(reviewers[1],$"/releases/{id}/approve",new{comment="独立安全验收审核"});await WriteAsync(api,$"/releases/{id}/publish");}
    private async Task<JsonElement> WaitAsync(string id)
    {var until=DateTimeOffset.UtcNow.AddSeconds(30);while(DateTimeOffset.UtcNow<until){var r=await GetAsync($"/releases/{id}");var state=r.GetProperty("state").GetString();var targets=r.GetProperty("targets").EnumerateArray().ToArray();if(state=="Succeeded"){Assert.Equal(2,targets.Length);Assert.All(targets,t=>Assert.True(t.GetProperty("acknowledged").GetBoolean()));return r;}if(targets.Count(t=>t.GetProperty("acknowledged").GetBoolean())<targets.Length)Assert.NotEqual("Succeeded",state);Assert.NotEqual("Failed",state);await Task.Delay(200);}Assert.Fail("Real node ACKs did not converge.");return default;}
    public async Task AssertBothAsync(string backend,long seq)
    {foreach(var client in gateways){using var req=new HttpRequestMessage(HttpMethod.Get,"/orders");req.Headers.Add("X-API-Key",credential);using var response=await client.SendAsync(req);Assert.Equal(HttpStatusCode.OK,response.StatusCode);var value=await response.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal(backend,value.GetProperty("backendId").GetString());Assert.Equal("GET",value.GetProperty("method").GetString());Assert.Equal("/orders",value.GetProperty("path").GetString());Assert.Equal(seq,value.GetProperty("deploymentSequence").GetInt64());Assert.False(value.GetProperty("receivedApiKey").GetBoolean());Assert.False(string.IsNullOrEmpty(value.GetProperty("traceId").GetString()));}}
    public async Task<JsonElement> RollbackRestoresAWithHigherSequence(JsonElement original,JsonElement first)
    {var rollback=await WriteAsync(api,$"/releases/{original.GetProperty("id").GetString()}/rollback",new{targetConfigVersion=first.GetProperty("targetConfigVersion").GetInt64()});var id=rollback.GetProperty("id").GetString()!;await ApproveAndPublishAsync(id);var done=await WaitAsync(id);Assert.True(done.GetProperty("deploymentSequence").GetInt64()>original.GetProperty("deploymentSequence").GetInt64());Assert.Equal(first.GetProperty("targetConfigVersion").GetInt64(),done.GetProperty("targetConfigVersion").GetInt64());await AssertBothAsync("A",done.GetProperty("deploymentSequence").GetInt64());return done;}
    public async Task<JsonElement> OldRequestCompletesDuringSwap()
    {using var backend=new HttpClient{BaseAddress=new Uri("http://backend-a:8080")};using var hold=await backend.PostAsync("/__test/hold-next",null);hold.EnsureSuccessStatusCode();using var req=new HttpRequestMessage(HttpMethod.Get,"/orders");req.Headers.Add("X-API-Key",credential);var pending=gateways[0].SendAsync(req);var started=false;var until=DateTimeOffset.UtcNow.AddSeconds(5);while(DateTimeOffset.UtcNow<until){using var check=await backend.GetAsync("/__test/hold-state");var state=await check.Content.ReadFromJsonAsync<JsonElement>();if(state.GetProperty("started").GetBoolean()){started=true;break;}await Task.Delay(100);}Assert.True(started,"Old real request must have entered backend A before starting the swap.");var target=await PublishAsync("B");await AssertBothAsync("B",target.GetProperty("deploymentSequence").GetInt64());using var release=await backend.PostAsync("/__test/release",null);release.EnsureSuccessStatusCode();using var old=await pending;var response=await old.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("A",response.GetProperty("backendId").GetString());Assert.True(response.GetProperty("deploymentSequence").GetInt64()<target.GetProperty("deploymentSequence").GetInt64());return target;}
    public ValueTask DisposeAsync(){api.Dispose();foreach(var c in reviewers.Concat(gateways))c.Dispose();return ValueTask.CompletedTask;}
}
