using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Gateway;
using WebApi.Infrastructure.Releases;
using WebApi.Infrastructure.Gateway;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class AckTests
{
    private sealed class Scenario : IAsyncDisposable
    {
        public ApiFixture Api {get;}=new();public Guid ReleaseId;public Guid[] Instances=[Guid.NewGuid(),Guid.NewGuid()];public Guid[] NodeIds=new Guid[2];public string[] Secrets=[Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)),Convert.ToBase64String(RandomNumberGenerator.GetBytes(32))];private string[] files=[Path.GetTempFileName(),Path.GetTempFileName()];public string Hash="";public long Sequence,Version;
        public async Task InitializeAsync()
        {
            for(var i=0;i<2;i++) {await File.WriteAllTextAsync(files[i],Secrets[i]);if(!OperatingSystem.IsWindows()) File.SetUnixFileMode(files[i],UnixFileMode.UserRead|UnixFileMode.UserWrite);}
            await Api.InitializeAsync(builder=>{for(var i=0;i<2;i++) {builder.Configuration[$"Nodes:Enrollments:{i}:EnvironmentId"]=Api.Environment.Id.ToString();builder.Configuration[$"Nodes:Enrollments:{i}:NodeName"]="node-"+i;builder.Configuration[$"Nodes:Enrollments:{i}:SecretFile"]=files[i];}});await Api.SeedReleaseAsync();using var login=await Api.LoginAsync();login.EnsureSuccessStatusCode();
            for(var i=0;i<2;i++) {using var registered=await SendAsync("/internal/v1/nodes/register",new RegisterNodeRequest(Api.Environment.Id,"node-"+i,Instances[i],"test"),Secrets[i]);registered.EnsureSuccessStatusCode();NodeIds[i]=(await registered.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("nodeId").GetGuid();}
            using var route=await Api.WriteAsync(HttpMethod.Post,$"/api/v1/environments/{Api.Environment.Id}/routes",Api.RouteBody("/orders"));route.EnsureSuccessStatusCode();ReleaseId=await Api.CreateSubmittedReleaseAsync();foreach(var role in new[]{"ApiApprover","SecurityReviewer"}) {var r=await Api.NewReviewerAsync(role);using var approved=await ApiFixture.CommandAsync(r.Client,$"/api/v1/releases/{ReleaseId}/approve",new {comment="审核"});approved.EnsureSuccessStatusCode();}
            using var published=await ApiFixture.CommandAsync(Api.Client,$"/api/v1/releases/{ReleaseId}/publish");published.EnsureSuccessStatusCode();using var scope=Api.Services();Assert.True(await scope.ServiceProvider.GetRequiredService<PublishCoordinator>().BuildNextAsync());await using var db=Api.Context();var release=await db.Set<ReleaseRecord>().SingleAsync();Sequence=release.DeploymentSequence!.Value;Version=release.ToConfigVersion;Hash=(await db.Set<GatewayConfigVersion>().SingleAsync()).SnapshotHash!;
        }
        public async Task<HttpResponseMessage> SendAsync(string path,object body,string secret)
        {using var request=new HttpRequestMessage(HttpMethod.Post,path) {Content=JsonContent.Create(body)};request.Headers.Authorization=new("Bearer",secret);return await Api.Client.SendAsync(request);}
        public NodeAck Ack(int i)=>new(Instances[i],ReleaseId,Version,Sequence,Hash,DateTimeOffset.UtcNow,true,null);
        public Task<HttpResponseMessage> SendAckAsync(int i,NodeAck? ack=null)=>SendAsync($"/internal/v1/nodes/{NodeIds[i]}/ack",ack??Ack(i),Secrets[i]);
        public async ValueTask DisposeAsync() {await Api.DisposeAsync();foreach(var file in files) File.Delete(file);}
    }
    private static async Task CompleteAsync(Scenario s)
    {for(var i=0;i<2;i++) {using var ack=await s.SendAckAsync(i);ack.EnsureSuccessStatusCode();}}
    private static async Task<Guid> RestartAsync(Scenario s,int i,IReadOnlyList<string>? schemas=null)
    {var fresh=Guid.NewGuid();using var response=await s.SendAsync("/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-"+i,fresh,"test",schemas),s.Secrets[i]);response.EnsureSuccessStatusCode();return fresh;}
    // Catches conflating runtime activation with the immutable publication target ACK.
    [Fact] public async Task SucceededReleaseRestartRecordsRuntimeReceiptWithoutChangingPublication()
    {
        await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);
        string before;await using(var db=s.Api.Context()) before=JsonSerializer.Serialize(new {release=await db.Set<ReleaseRecord>().SingleAsync(),targets=await db.Set<ReleaseTarget>().OrderBy(t=>t.NodeId).ToArrayAsync(),acks=await db.Set<GatewayAck>().OrderBy(a=>a.NodeId).ToArrayAsync(),audit=await db.Set<AuditLog>().Where(a=>a.Action=="release.succeeded").ToArrayAsync()});
        for(var i=0;i<2;i++) {var fresh=await RestartAsync(s,i);var ack=s.Ack(i) with {InstanceId=fresh};using var response=await s.SendAckAsync(i,ack);Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.False((await response.Content.ReadFromJsonAsync<AckResult>())!.Duplicate);using var duplicate=await s.SendAckAsync(i,ack);duplicate.EnsureSuccessStatusCode();Assert.True((await duplicate.Content.ReadFromJsonAsync<AckResult>())!.Duplicate);}
        await using var check=s.Api.Context();Assert.Equal(before,JsonSerializer.Serialize(new {release=await check.Set<ReleaseRecord>().SingleAsync(),targets=await check.Set<ReleaseTarget>().OrderBy(t=>t.NodeId).ToArrayAsync(),acks=await check.Set<GatewayAck>().OrderBy(a=>a.NodeId).ToArrayAsync(),audit=await check.Set<AuditLog>().Where(a=>a.Action=="release.succeeded").ToArrayAsync()}));
        Assert.Equal(2,await check.Set<GatewayNodeEvent>().CountAsync(e=>e.EventType=="runtime_applied"));
        foreach(var node in await check.Set<GatewayNode>().ToArrayAsync()) {Assert.Equal("Ready",node.Status);Assert.Equal(s.Version,node.CurrentConfigVersion);using var json=JsonDocument.Parse(node.Metadata!);var receipt=json.RootElement.GetProperty("runtimeApplication");Assert.Equal(node.InstanceId,receipt.GetProperty("instanceId").GetString());Assert.Equal(s.Hash,receipt.GetProperty("payloadHash").GetString());Assert.Equal(s.Sequence,receipt.GetProperty("deploymentSequence").GetInt64());}
    }
    [Fact] public async Task AnotherRestartInvalidatesPriorRuntimeReceipt()
    {await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var first=await RestartAsync(s,0);using var ack=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=first});ack.EnsureSuccessStatusCode();var next=await RestartAsync(s,0);using var stale=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=first});Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);await using var db=s.Api.Context();var node=await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0]);Assert.Equal(next.ToString(),node.InstanceId);Assert.Equal("NotReady",node.Status);using var metadata=JsonDocument.Parse(node.Metadata!);Assert.False(metadata.RootElement.TryGetProperty("runtimeApplication",out _));}
    [Fact] public async Task ConcurrentRuntimeReceiptsProduceOneEventAndPreserveOtherMetadata()
    {
        await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var fresh=await RestartAsync(s,0);
        await using(var db=s.Api.Context()) {var node=await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0]);var metadata=System.Text.Json.Nodes.JsonNode.Parse(node.Metadata!)!.AsObject();metadata["operatorTag"]="preserve";node.Metadata=metadata.ToJsonString();await db.SaveChangesAsync();}
        var ack=s.Ack(0) with {InstanceId=fresh};var results=await Task.WhenAll(Enumerable.Range(0,3).Select(_=>s.SendAckAsync(0,ack)));var duplicates=0;
        foreach(var response in results) {using(response) {response.EnsureSuccessStatusCode();if((await response.Content.ReadFromJsonAsync<AckResult>())!.Duplicate) duplicates++;}}
        Assert.Equal(2,duplicates);await using var check=s.Api.Context();Assert.Equal(1,await check.Set<GatewayNodeEvent>().CountAsync(e=>e.EventType=="runtime_applied"));Assert.Equal(2,await check.Set<GatewayAck>().CountAsync());var current=await check.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0]);using var json=JsonDocument.Parse(current.Metadata!);Assert.Equal("preserve",json.RootElement.GetProperty("operatorTag").GetString());Assert.True(json.RootElement.TryGetProperty("supportedSnapshotSchemas",out _));
    }
    [Theory]
    [InlineData("hash",409)] [InlineData("sequence",409)] [InlineData("version",409)] [InlineData("release",409)]
    [InlineData("old-time",422)] [InlineData("future-time",422)] [InlineData("offset",422)] [InlineData("error",422)] [InlineData("negative",409)]
    public async Task RuntimeReceiptRejectsInvalidApplicationEvidence(string mutation,int expected)
    {
        await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var fresh=await RestartAsync(s,0);var ack=s.Ack(0) with {InstanceId=fresh};ack=mutation switch {"hash"=>ack with {PayloadHash=new string('0',64)},"sequence"=>ack with {DeploymentSequence=s.Sequence+1},"version"=>ack with {ConfigVersion=s.Version+1},"release"=>ack with {ReleaseId=Guid.NewGuid()},"old-time"=>ack with {AppliedAt=DateTimeOffset.UtcNow.AddMinutes(-10)},"future-time"=>ack with {AppliedAt=DateTimeOffset.UtcNow.AddMinutes(10)},"offset"=>ack with {AppliedAt=DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(8))},"error"=>ack with {ErrorCode="invalid_snapshot"},_=>ack with {Success=false,ErrorCode="invalid_snapshot"}};
        using var response=await s.SendAckAsync(0,ack);Assert.Equal(expected,(int)response.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<GatewayNodeEvent>().AnyAsync(e=>e.EventType=="runtime_applied"));Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());Assert.Equal("NotReady",(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0])).Status);
    }
    [Theory] [InlineData("Failed")] [InlineData("RolledBack")]
    public async Task RuntimeReceiptCannotReviveAnUnsuccessfulOrSupersededRelease(string status)
    {await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var fresh=await RestartAsync(s,0);await using(var db=s.Api.Context()) await db.Set<ReleaseRecord>().ExecuteUpdateAsync(x=>x.SetProperty(r=>r.Status,status));using var response=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=fresh});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var check=s.Api.Context();Assert.False(await check.Set<GatewayNodeEvent>().AnyAsync(e=>e.EventType=="runtime_applied"));Assert.Equal(status,(await check.Set<ReleaseRecord>().SingleAsync()).Status);}
    [Fact] public async Task RuntimeReceiptRequiresCurrentDesiredSequence()
    {await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var fresh=await RestartAsync(s,0);await using(var db=s.Api.Context()) await db.Set<EnvironmentRecord>().ExecuteUpdateAsync(x=>x.SetProperty(e=>e.DeploymentSequence,s.Sequence+1));using var response=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=fresh});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
    [Fact] public async Task RuntimeReceiptRequiresEnabledCurrentInstanceAndSupportedSchema()
    {await using var s=new Scenario();await s.InitializeAsync();await CompleteAsync(s);var fresh=await RestartAsync(s,0,["2.1"]);using var incompatible=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=fresh});Assert.Equal(HttpStatusCode.Conflict,incompatible.StatusCode);await using(var db=s.Api.Context()) await db.Set<GatewayNode>().Where(n=>n.Id==s.NodeIds[0]).ExecuteUpdateAsync(x=>x.SetProperty(n=>n.Enabled,false));using var disabled=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=fresh});Assert.Equal(HttpStatusCode.Unauthorized,disabled.StatusCode);}
    [Fact] public async Task OneOfTwoAcksKeepsPublishing()
    {await using var s=new Scenario();await s.InitializeAsync();using var ack=await s.SendAckAsync(0);Assert.Equal(HttpStatusCode.OK,ack.StatusCode);await using var db=s.Api.Context();Assert.Equal("Publishing",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(1,await db.Set<GatewayAck>().CountAsync());Assert.Equal(s.Version,(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0])).CurrentConfigVersion);}
    [Fact] public async Task SecondValidAckCompletesOnce()
    {await using var s=new Scenario();await s.InitializeAsync();using var a=await s.SendAckAsync(0);a.EnsureSuccessStatusCode();using var b=await s.SendAckAsync(1);b.EnsureSuccessStatusCode();using var duplicate=await s.SendAckAsync(1);duplicate.EnsureSuccessStatusCode();await using var db=s.Api.Context();Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());Assert.Equal(1,await db.Set<AuditLog>().CountAsync(a=>a.Action=="release.succeeded"));Assert.Equal("Published",(await db.Set<ApiVersion>().SingleAsync()).Status);}
    [Fact] public async Task WrongInstanceHashOrSequenceRejected()
    {await using var s=new Scenario();await s.InitializeAsync();foreach(var wrong in new[]{s.Ack(0) with {InstanceId=Guid.NewGuid()},s.Ack(0) with {PayloadHash=new string('0',64)},s.Ack(0) with {DeploymentSequence=s.Sequence+1}}) {using var response=await s.SendAckAsync(0,wrong);Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}using var unknown=await s.SendAsync($"/internal/v1/nodes/{Guid.NewGuid()}/ack",s.Ack(0),s.Secrets[0]);Assert.Equal(HttpStatusCode.Unauthorized,unknown.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync());}
    [Fact] public async Task LateAckDoesNotCompleteFailedRelease()
    {await using var s=new Scenario();await s.InitializeAsync();using var a=await s.SendAckAsync(0);a.EnsureSuccessStatusCode();await using(var db=s.Api.Context()) {await db.Set<ReleaseRecord>().ExecuteUpdateAsync(set=>set.SetProperty(r=>r.DeadlineAt,DateTimeOffset.UtcNow.AddSeconds(-1)));}using(var scope=s.Api.Services()) Assert.Equal(1,await scope.ServiceProvider.GetRequiredService<ReleaseTimeoutService>().ExpireAsync());using var late=await s.SendAckAsync(1);Assert.Equal(HttpStatusCode.Conflict,late.StatusCode);await using var check=s.Api.Context();Assert.Equal("Failed",(await check.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(s.Version,(await check.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0])).CurrentConfigVersion);Assert.Equal(s.Version,(await check.Set<EnvironmentRecord>().SingleAsync()).DesiredConfigVersion);Assert.Equal(1,await check.Set<GatewayAck>().CountAsync());Assert.NotNull((await check.Set<ApiVersion>().SingleAsync()).SealedAt);}
    [Fact] public async Task DuplicateAckAfterWorkerRestartIsHarmless()
    {await using var s=new Scenario();await s.InitializeAsync();using var a=await s.SendAckAsync(0);a.EnsureSuccessStatusCode();using(var scope=s.Api.Services()) Assert.Equal(0,await scope.ServiceProvider.GetRequiredService<ReleaseTimeoutService>().ExpireAsync());using var duplicate=await s.SendAckAsync(0);duplicate.EnsureSuccessStatusCode();await using var db=s.Api.Context();Assert.Equal(1,await db.Set<GatewayAck>().CountAsync());Assert.Equal(1,await db.Set<GatewayNodeEvent>().CountAsync(e=>e.EventType=="applied"));Assert.Equal("Publishing",(await db.Set<ReleaseRecord>().SingleAsync()).Status);}
    [Fact] public async Task DisabledIdentityRejectsOldRequests()
    {await using var s=new Scenario();await s.InitializeAsync();await using(var db=s.Api.Context()) {await db.Set<GatewayNode>().Where(n=>n.Id==s.NodeIds[0]).ExecuteUpdateAsync(set=>set.SetProperty(n=>n.Enabled,false));}using var ack=await s.SendAckAsync(0);Assert.Equal(HttpStatusCode.Unauthorized,ack.StatusCode);using var heartbeat=await s.SendAsync($"/internal/v1/nodes/{s.NodeIds[0]}/heartbeat",new NodeHeartbeat(s.Instances[0],0,0,"NotReady"),s.Secrets[0]);Assert.Equal(HttpStatusCode.Unauthorized,heartbeat.StatusCode);using var register=await s.SendAsync("/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",Guid.NewGuid(),"test"),s.Secrets[0]);Assert.Equal(HttpStatusCode.Unauthorized,register.StatusCode);}
    [Fact] public async Task NodeSecretCannotEnrollIntoDifferentEnvironment()
    {await using var s=new Scenario();await s.InitializeAsync();using var wrong=await s.SendAsync("/internal/v1/nodes/register",new RegisterNodeRequest(Guid.NewGuid(),"node-0",Guid.NewGuid(),"test"),s.Secrets[0]);Assert.Equal(HttpStatusCode.Unauthorized,wrong.StatusCode);using var otherSecret=await s.SendAsync($"/internal/v1/nodes/{s.NodeIds[0]}/heartbeat",new NodeHeartbeat(s.Instances[0],0,0,"NotReady"),s.Secrets[1]);Assert.Equal(HttpStatusCode.Unauthorized,otherSecret.StatusCode);using var noSecret=await s.Api.Client.GetAsync($"/internal/v1/nodes/{s.NodeIds[0]}/desired");Assert.Equal(HttpStatusCode.Unauthorized,noSecret.StatusCode);}
    [Fact] public async Task RestartedInstanceCannotFillOldFrozenTarget()
    {await using var s=new Scenario();await s.InitializeAsync();var fresh=Guid.NewGuid();using var register=await s.SendAsync("/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",fresh,"test"),s.Secrets[0]);register.EnsureSuccessStatusCode();using var old=await s.SendAckAsync(0);Assert.Equal(HttpStatusCode.Conflict,old.StatusCode);using var changed=await s.SendAckAsync(0,s.Ack(0) with {InstanceId=fresh});Assert.Equal(HttpStatusCode.Conflict,changed.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync());Assert.Equal(2,await db.Set<ReleaseTarget>().CountAsync());}
    [Fact] public async Task NegativeAckFailsReleaseWithoutInventingRunningState()
    {await using var s=new Scenario();await s.InitializeAsync();using var failure=await s.SendAckAsync(0,s.Ack(0) with {Success=false,ErrorCode="lkg_write_denied"});failure.EnsureSuccessStatusCode();await using var db=s.Api.Context();Assert.Equal("Failed",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(0,(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0])).CurrentConfigVersion);Assert.NotNull((await db.Set<ApiVersion>().SingleAsync()).SealedAt);Assert.Equal(2,await db.Set<ReleaseTarget>().CountAsync());}
    [Fact] public async Task HeartbeatCannotCompleteReleaseOrInventVersion()
    {await using var s=new Scenario();await s.InitializeAsync();using var heartbeat=await s.SendAsync($"/internal/v1/nodes/{s.NodeIds[0]}/heartbeat",new NodeHeartbeat(s.Instances[0],s.Version,s.Sequence,"Ready"),s.Secrets[0]);heartbeat.EnsureSuccessStatusCode();using var invented=await s.SendAsync($"/internal/v1/nodes/{s.NodeIds[1]}/heartbeat",new NodeHeartbeat(s.Instances[1],99,99,"Ready"),s.Secrets[1]);Assert.Equal(HttpStatusCode.Conflict,invented.StatusCode);await using var db=s.Api.Context();Assert.Equal("Publishing",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.False(await db.Set<GatewayAck>().AnyAsync());}
    [Fact] public async Task DispatchedVersionStaysImmutableAfterPartialFailure()
    {await using var s=new Scenario();await s.InitializeAsync();using var applied=await s.SendAckAsync(0);applied.EnsureSuccessStatusCode();using var failed=await s.SendAckAsync(1,s.Ack(1) with {Success=false,ErrorCode="invalid_snapshot"});failed.EnsureSuccessStatusCode();using var edit=await s.Api.WriteAsync(HttpMethod.Put,$"/api/v1/versions/{s.Api.Version.Id}",new {version="2.0.0",changeType="breaking"},"\"1\"");Assert.Equal(HttpStatusCode.Conflict,edit.StatusCode);await using var db=s.Api.Context();Assert.Equal("1.0.0",(await db.Set<ApiVersion>().SingleAsync()).Version);Assert.Equal("Failed",(await db.Set<ReleaseRecord>().SingleAsync()).Status);}
    [Fact] public async Task DeadlineCheckedEvenBeforeTimeoutWorkerRuns()
    {await using var s=new Scenario();await s.InitializeAsync();using var a=await s.SendAckAsync(0);a.EnsureSuccessStatusCode();await using(var db=s.Api.Context()) await db.Set<ReleaseRecord>().ExecuteUpdateAsync(set=>set.SetProperty(r=>r.DeadlineAt,DateTimeOffset.UtcNow.AddSeconds(-1)));using var late=await s.SendAckAsync(1);Assert.Equal(HttpStatusCode.Conflict,late.StatusCode);await using var check=s.Api.Context();Assert.Equal("Failed",(await check.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(1,await check.Set<GatewayAck>().CountAsync());}
    [Fact] public async Task ConcurrentAcksFinishExactlyOnce()
    {await using var s=new Scenario();await s.InitializeAsync();var responses=await Task.WhenAll(s.SendAckAsync(0),s.SendAckAsync(1),s.SendAckAsync(1));foreach(var response in responses) {using(response) response.EnsureSuccessStatusCode();}await using var db=s.Api.Context();Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());Assert.Equal(1,await db.Set<AuditLog>().CountAsync(a=>a.Action=="release.succeeded"));}
}
