using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Common;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class ComparisonReleaseTests
{
    private static async Task<(ComparisonFixture F,Guid Review)> PrepareAsync(bool production=false)
    {var f=new ComparisonFixture();await f.InitializeAsync(true);var (id,hash)=await f.ComparisonAsync();using var r=await f.ReviewAsync(id,hash);r.EnsureSuccessStatusCode();var review=(await r.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();await using(var db=f.Api.Context()){(await db.Set<EnvironmentRecord>().SingleAsync()).IsProduction=production;for(var i=0;i<2;i++)db.Add(new GatewayNode{EnvironmentId=f.Api.Environment.Id,NodeName="node-"+i,InstanceId=Guid.NewGuid().ToString(),AppVersion="test",IdentityHash=Convert.ToHexStringLower(SHA256.HashData(RandomNumberGenerator.GetBytes(32))),LastHeartbeatAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}return(f,review);}
    private static async Task<HttpResponseMessage> CreateAsync(ComparisonFixture f,Guid review,Guid? target=null)
    {var preview=await f.Api.PreviewReleaseRequestAsync(versionId:target??f.Target.Id);return await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/environments/{f.Api.Environment.Id}/releases",new{preview.BaseConfigVersion,preview.VersionIds,preview.ResourceRevisions,riskReviewIds=new[]{review},riskReviewReferences=new[]{new{reportHash="CLIENT_FAKE_HASH"}}});}
    private static async Task<Guid> SubmitAsync(ComparisonFixture f,Guid review)
    {using var c=await CreateAsync(f,review);c.EnsureSuccessStatusCode();var id=(await c.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();using var s=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/submit");s.EnsureSuccessStatusCode();return id;}
    [Fact] public async Task CreateChecksTargetScopeAndReviewFreshness()
    {var (f,review)=await PrepareAsync();await using var owned=f;using var mismatch=await CreateAsync(f,review,f.Api.Version.Id);Assert.Equal(HttpStatusCode.UnprocessableEntity,mismatch.StatusCode);await using(var db=f.Api.Context()){(await db.Set<ApiVersion>().SingleAsync(x=>x.Id==f.Api.Version.Id)).Revision++;await db.SaveChangesAsync();}using var stale=await CreateAsync(f,review);Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);}
    [Fact] public async Task RefreshCannotDropReviewIdsAndSubmitFreezesServerEvidence()
    {var(f,review)=await PrepareAsync(true);await using var owned=f;using var c=await CreateAsync(f,review);c.EnsureSuccessStatusCode();var id=(await c.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();var preview=await f.Api.PreviewReleaseRequestAsync(versionId:f.Target.Id);using var refreshed=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/refresh-preconditions",new{preview.ResourceRevisions});refreshed.EnsureSuccessStatusCode();await using(var db=f.Api.Context()){using var bytes=JsonDocument.Parse((await db.Set<ReleaseRecord>().SingleAsync()).CandidateBytes!);Assert.Equal(review,bytes.RootElement.GetProperty("riskReviewIds")[0].GetGuid());}using var submitted=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/submit");submitted.EnsureSuccessStatusCode();var value=await submitted.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("WaitingApproval",value.GetProperty("state").GetString());await using(var db=f.Api.Context()){var raw=(await db.Set<ReleaseRecord>().SingleAsync()).CandidateBytes!;using var d=JsonDocument.Parse(raw);var reference=d.RootElement.GetProperty("riskReviewReferences")[0];Assert.Equal(review,reference.GetProperty("reviewId").GetGuid());Assert.Equal(f.Target.Id,reference.GetProperty("targetVersionId").GetGuid());Assert.DoesNotContain("CLIENT_FAKE_HASH",System.Text.Encoding.UTF8.GetString(raw));Assert.Equal(2,await db.Set<ApprovalTask>().CountAsync());}using var self=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/approve",new{comment="self"});Assert.Equal(HttpStatusCode.Forbidden,self.StatusCode);}
    [Theory][InlineData(false)][InlineData(true)] public async Task FromOrToChangesBeforePublishAreRejected(bool target)
    {var(f,review)=await PrepareAsync();await using var owned=f;var id=await SubmitAsync(f,review);await using(var db=f.Api.Context()){(await db.Set<ApiVersion>().SingleAsync(x=>x.Id==(target?f.Target.Id:f.Api.Version.Id))).Revision++;await db.SaveChangesAsync();}using var p=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,p.StatusCode);await using var check=f.Api.Context();Assert.Equal("Ready",(await check.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(0,await check.Set<GatewayConfigSnapshot>().CountAsync());}
    [Fact] public async Task BaselineEditAfterStartFailsBuildWithoutDesiredVersionAdvance()
    {var(f,review)=await PrepareAsync();await using var owned=f;var id=await SubmitAsync(f,review);using var p=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/publish");p.EnsureSuccessStatusCode();await using(var db=f.Api.Context()){(await db.Set<ApiVersion>().SingleAsync(x=>x.Id==f.Api.Version.Id)).Revision++;await db.SaveChangesAsync();}using(var scope=f.Api.Services())Assert.True(await scope.ServiceProvider.GetRequiredService<PublishCoordinator>().BuildNextAsync());await using var check=f.Api.Context();var env=await check.Set<EnvironmentRecord>().SingleAsync();Assert.Equal("Failed",(await check.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal("risk_review_stale",(await check.Set<ReleaseRecord>().SingleAsync()).FailureCode);Assert.Null(env.DesiredConfigVersion);Assert.Equal(0,env.DeploymentSequence);Assert.Equal(0,await check.Set<GatewayConfigSnapshot>().CountAsync());}
    [Fact] public async Task PublishSealingAloneDoesNotInvalidateAndEvidenceNeverEntersRuntime()
    {var(f,review)=await PrepareAsync();await using var owned=f;var id=await SubmitAsync(f,review);using var p=await ApiFixture.CommandAsync(f.Api.Client,$"/api/v1/releases/{id}/publish");p.EnsureSuccessStatusCode();using(var scope=f.Api.Services())Assert.True(await scope.ServiceProvider.GetRequiredService<PublishCoordinator>().BuildNextAsync());await using var check=f.Api.Context();var r=await check.Set<ApiVersionRiskReview>().SingleAsync();using var get=await f.Api.Client.GetAsync($"/api/v1/version-comparisons/{r.ComparisonId}");get.EnsureSuccessStatusCode();Assert.Equal("Current",(await get.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("freshness").GetString());var snapshot=System.Text.Encoding.UTF8.GetString((await check.Set<GatewayConfigSnapshot>().SingleAsync()).PayloadBytes);Assert.DoesNotContain("riskReview",snapshot);Assert.DoesNotContain("已评估风险",snapshot);Assert.Equal(2,await check.Set<ReleaseTarget>().CountAsync());}
    [Fact] public async Task ReleaseOnlyReaderCannotReadReviewCommentAndLegacyBytesKeepHash()
    {var(f,review)=await PrepareAsync();await using var owned=f;var id=await SubmitAsync(f,review);var reader=await f.Api.NewReviewerAsync("ReleaseReader");foreach(var suffix in new[]{"","/preview"}){using var r=await reader.Client.GetAsync($"/api/v1/releases/{id}"+suffix);r.EnsureSuccessStatusCode();Assert.DoesNotContain("已评估风险",await r.Content.ReadAsStringAsync());}await using(var db=f.Api.Context()){var record=await db.Set<ReleaseRecord>().SingleAsync();var node=System.Text.Json.Nodes.JsonNode.Parse(record.CandidateBytes!)!;node.AsObject().Remove("riskReviewReferences");record.CandidateBytes=System.Text.Encoding.UTF8.GetBytes(node.ToJsonString()+"\n");await db.SaveChangesAsync();}await using var check=f.Api.Context();var raw=(await check.Set<ReleaseRecord>().SingleAsync()).CandidateBytes!;using var get=await f.Api.Client.GetAsync($"/api/v1/releases/{id}");get.EnsureSuccessStatusCode();Assert.Equal(Convert.ToHexStringLower(SHA256.HashData(raw)),(await get.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("candidateHash").GetString());Assert.Equal(raw,(await check.Set<ReleaseRecord>().AsNoTracking().SingleAsync()).CandidateBytes);}
}
