using System.Net;using System.Net.Http.Json;using System.Text.Json.Nodes;using Microsoft.EntityFrameworkCore;using WebApi.Contracts.Releases;using WebApi.Infrastructure.Persistence.Entities;using WebApi.Integration.Tests.Support;using Xunit;
namespace WebApi.Integration.Tests;
public sealed class DeliveryOverviewTests
{
 [Fact] public async Task OverviewPaginates51AuthorizedPromotionsAndKeepsActualNodeFactsSeparateFromDesired()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){for(var i=0;i<50;i++)db.Add(new ReleasePromotion{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,ArtifactId=s.Source.Artifact.Id,SourceReleaseId=s.Source.ReleaseId,SourceEnvironmentId=s.Api.Environment.Id,TargetEnvironmentId=s.TargetEnvironmentId,RequestedBy=s.Api.User.Id,Status=i%2==0?"Verifying":"DeploymentFailed"});await db.SaveChangesAsync();}var path=$"/api/v1/delivery/overview?projectId={s.Api.Project.Id}";var p=await s.Api.Client.GetFromJsonAsync<JsonObject>(path);Assert.Equal(51,p!["promotions"]!["total"]!.GetValue<int>());Assert.Equal(50,p["promotions"]!["items"]!.AsArray().Count);Assert.Equal(25,p["counts"]!["awaitingVerification"]!.GetValue<int>());Assert.Equal(25,p["counts"]!["deploymentFailed"]!.GetValue<int>());Assert.Equal(2,p["environments"]!.AsArray().Count);var next=await s.Api.Client.GetFromJsonAsync<JsonObject>(path+"&page=2&pageSize=50");Assert.Single(next!["promotions"]!["items"]!.AsArray());var capped=await s.Api.Client.GetFromJsonAsync<JsonObject>(path+"&pageSize=101");Assert.Equal(100,capped!["promotions"]!["pageSize"]!.GetValue<int>());Assert.DoesNotContain("canonicalContent",p.ToJsonString());Assert.DoesNotContain("secretHash",p.ToJsonString());}
 [Fact] public async Task UnknownOrForeignProjectCannotReadCounts()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using var response=await s.Api.Client.GetAsync($"/api/v1/delivery/overview?projectId={Guid.NewGuid()}");Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);Assert.DoesNotContain("awaitingVerification",await response.Content.ReadAsStringAsync());}
 [Fact] public async Task SourceOnlyScopeDoesNotRevealTargetEnvironmentOrDeliveryTotals()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context())await db.Set<UserProjectScope>().Where(g=>g.UserId==s.Api.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.ProjectId,s.Api.Project.Id).SetProperty(g=>g.EnvironmentId,s.Api.Environment.Id));var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/delivery/overview?projectId={s.Api.Project.Id}");Assert.Single(p!["environments"]!.AsArray());Assert.DoesNotContain(s.TargetEnvironmentId.ToString(),p.ToJsonString());Assert.Equal("Partial",p["coverage"]!.GetValue<string>());}
 [Fact] public async Task MissingContractVisibilityMeansRestrictedRatherThanInventedZeroCounts()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="api.schema.read");await db.Set<RolePermission>().Where(p=>p.PermissionId==permission.Id).ExecuteDeleteAsync();}var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/delivery/overview?projectId={s.Api.Project.Id}");Assert.Equal("Restricted",p!["promotionsVisibility"]!.GetValue<string>());Assert.Null(p["promotions"]);Assert.Null(p["counts"]);Assert.DoesNotContain(s.Source.Artifact.ArtifactHash,p.ToJsonString());}
 [Fact] public async Task MappingOptionsAreActualTargetResourcesAndNeverExposeCredentialSecretsOrOtherEnvironmentGrants()
 {await using var s=new PromotionScenario();await s.InitializeAsync(timeout:true);var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-promotions/{s.PromotionId}/mapping-options");Assert.Equal(s.TargetEnvironmentId.ToString(),p!["targetEnvironmentId"]!.GetValue<string>());Assert.Contains(s.TargetClusterId.ToString(),p.ToJsonString());Assert.Contains(s.TargetCredentialId.ToString(),p.ToJsonString());Assert.DoesNotContain("secretHash",p.ToJsonString());Assert.DoesNotContain("secret",p.ToJsonString().ToLowerInvariant());Assert.DoesNotContain(s.Api.Environment.Id.ToString(),p["applications"]!.ToJsonString());}
 [Fact] public async Task PromotionReadExposesServerActionAuthorityAndRetainsPrecheckResult()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-promotions/{s.PromotionId}");Assert.True(p!["eligibility"]!["canEditMapping"]!.GetValue<bool>());Assert.False(p["eligibility"]!["canSubmit"]!.GetValue<bool>());Assert.False(p["eligibility"]!["canVerify"]!.GetValue<bool>());using var saved=await s.SaveAsync(s.Mapping());saved.EnsureSuccessStatusCode();using var precheck=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/release-promotions/{s.PromotionId}/precheck",new PromotionPrecheckRequest());precheck.EnsureSuccessStatusCode();var blocked=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-promotions/{s.PromotionId}");Assert.False(blocked!["precheck"]!["canSubmit"]!.GetValue<bool>());Assert.False(blocked["eligibility"]!["canSubmit"]!.GetValue<bool>());}
 [Fact] public async Task PromotionApprovalsExposeSourceOnlyWhenItsScopeAndContractAreVisible()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await PromotionSubmissionTests.Prepared(s);var p=await s.Api.Client.GetFromJsonAsync<PromotionDto>($"/api/v1/release-promotions/{s.PromotionId}");using(var submitted=await s.Api.WriteAsync(HttpMethod.Post,$"/api/v1/release-promotions/{s.PromotionId}/submit",new{},$"\"{p!.Revision}\""))submitted.EnsureSuccessStatusCode();var inbox=await s.Api.Client.GetFromJsonAsync<JsonObject>("/api/v1/approvals?view=AllVisible");await using var readDb=s.Api.Context();var releaseId=(await readDb.Set<ReleasePromotion>().SingleAsync(r=>r.Id==s.PromotionId)).TargetReleaseId!.Value.ToString();var row=inbox!["page"]!["items"]!.AsArray().Single(r=>r!["id"]!.GetValue<string>()==releaseId);Assert.Equal("Promotion",row!["applicationKind"]!.GetValue<string>());Assert.Equal("Visible",row["delivery"]!["visibility"]!.GetValue<string>());Assert.Contains(s.Source.Artifact.ArtifactHash,row["delivery"]!.ToJsonString());await using(var db=s.Api.Context())await db.Set<UserProjectScope>().Where(g=>g.UserId==s.Api.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.ProjectId,s.Api.Project.Id).SetProperty(g=>g.EnvironmentId,s.TargetEnvironmentId));var restricted=await s.Api.Client.GetFromJsonAsync<JsonObject>("/api/v1/approvals?view=AllVisible");var hidden=restricted!["page"]!["items"]!.AsArray().Single(r=>r!["applicationKind"]?.GetValue<string>()=="Promotion");Assert.Equal("Restricted",hidden!["delivery"]!["visibility"]!.GetValue<string>());Assert.Null(hidden["delivery"]!["artifactHash"]);Assert.Null(hidden["delivery"]!["sourceEnvironment"]);}
 [Fact] public async Task ProductionReviewerWithoutSourceVisibilityHasNoActionablePromotionCount()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await PromotionSubmissionTests.Prepared(s);using(var submit=await PromotionSubmissionTests.Send(s,"submit",etag:$"\"{prepared.Revision}\""))submit.EnsureSuccessStatusCode();var reviewer=await s.NewProductionApproverAsync("ApiApprover");await using(var db=s.Api.Context())await db.Set<UserProjectScope>().Where(g=>g.UserId==reviewer.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.ProjectId,s.Api.Project.Id).SetProperty(g=>g.EnvironmentId,s.TargetEnvironmentId));var inbox=await reviewer.Client.GetFromJsonAsync<JsonObject>("/api/v1/approvals?view=AllVisible");var row=inbox!["page"]!["items"]!.AsArray().Single(r=>r!["id"]!.GetValue<string>()!=(s.Source.ReleaseId.ToString()));Assert.Equal("Restricted",row!["delivery"]!["visibility"]!.GetValue<string>());Assert.False(row["approvalEligibility"]!["canAct"]!.GetValue<bool>());Assert.Equal(0,inbox["counts"]!["pendingMine"]!.GetValue<int>());}
 [Fact] public async Task ArtifactCreationEligibilityRequiresCurrentAcceptedEvidenceAndBothEnvironmentWriteScopes()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await PromotionSubmissionTests.Prepared(s);var eligibility=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-artifacts/{s.Source.Artifact.Id}/eligibility");Assert.True(eligibility!["canCreatePromotion"]!.GetValue<bool>());await using(var db=s.Api.Context())await db.Set<UserProjectScope>().Where(g=>g.UserId==s.Api.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.ProjectId,s.Api.Project.Id).SetProperty(g=>g.EnvironmentId,s.Api.Environment.Id));var restricted=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-artifacts/{s.Source.Artifact.Id}/eligibility");Assert.False(restricted!["canCreatePromotion"]!.GetValue<bool>());}
 [Fact] public async Task PrecheckReadRetainsCredentialImpactAndMatchesTheCurrentRevision()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await PromotionSubmissionTests.Prepared(s);var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-promotions/{s.PromotionId}");Assert.Equal(p!["revision"]!.GetValue<long>(),p["precheck"]!["revision"]!.GetValue<long>());Assert.NotNull(p["credentialImpact"]);}
 [Fact] public async Task RevokedTargetAppReadClearsPrivateMappingAndBlocksItsEditor()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await PromotionSubmissionTests.Prepared(s);await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="app.read");await db.Set<RolePermission>().Where(r=>r.PermissionId==permission.Id).ExecuteDeleteAsync();}var p=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-promotions/{s.PromotionId}");Assert.Null(p!["mapping"]);Assert.Null(p["credentialImpact"]);Assert.False(p["eligibility"]!["canEditMapping"]!.GetValue<bool>());Assert.DoesNotContain(s.TargetCredentialId.ToString(),p.ToJsonString());}
 [Fact] public async Task FormalReleaseTracePreservesPromotionAndHidesRestrictedSource()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await PromotionSubmissionTests.Prepared(s);using(var submit=await PromotionSubmissionTests.Send(s,"submit",etag:$"\"{prepared.Revision}\""))submit.EnsureSuccessStatusCode();var promotion=await s.Api.Client.GetFromJsonAsync<PromotionDto>($"/api/v1/release-promotions/{s.PromotionId}");var release=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/releases/{promotion!.TargetReleaseId}");Assert.Equal(s.PromotionId.ToString(),release!["delivery"]!["promotionId"]!.GetValue<string>());await using(var db=s.Api.Context())await db.Set<UserProjectScope>().Where(g=>g.UserId==s.Api.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.ProjectId,s.Api.Project.Id).SetProperty(g=>g.EnvironmentId,s.TargetEnvironmentId));var restricted=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/releases/{promotion.TargetReleaseId}");Assert.Equal("Restricted",restricted!["delivery"]!["visibility"]!.GetValue<string>());Assert.Null(restricted["delivery"]!["promotionId"]);Assert.Null(restricted["delivery"]!["artifactHash"]);}
}
