using System.Net;
using System.Net.Http.Json;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class DeliveryConsoleTests
{
    [Fact] public async Task WorkflowUsesRealSourceAndDefaultManualTypesWithoutInsertingLegacyPolicy()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var value=await s.Api.Client.GetFromJsonAsync<JsonObject>($"/api/v1/release-artifacts/{s.Artifact.Id}/eligibility");Assert.Equal(s.Artifact.SourceEnvironmentId.ToString(),value!["sourceEnvironmentId"]!.GetValue<string>());Assert.Equal("Legacy",value["mode"]!.GetValue<string>());Assert.Equal(1440,value["verificationValidityMinutes"]!.GetValue<int>());Assert.Equal(3,value["requiredTestTypes"]!.AsArray().Count);Assert.True(value["canRecord"]!.GetValue<bool>());Assert.False(value["canRequestAcceptance"]!.GetValue<bool>());await using var db=s.Api.Context();Assert.Empty(await db.Set<ProjectDeliveryPolicy>().ToArrayAsync());}
    [Fact] public async Task EligibilityUsesLatestPassedEvidenceAndStopsAfterSourceEntryChange()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();foreach(var type in new[]{"InterfaceFunction","Integration","ContractCompatibility"}){using var r=await s.RecordAsync(type:type);r.EnsureSuccessStatusCode();}var path=$"/api/v1/release-artifacts/{s.Artifact.Id}/eligibility";var before=await s.Api.Client.GetFromJsonAsync<JsonObject>(path);Assert.True(before!["canRequestAcceptance"]!.GetValue<bool>());using(var failed=await s.RecordAsync("Failed"))failed.EnsureSuccessStatusCode();var latest=await s.Api.Client.GetFromJsonAsync<JsonObject>(path);Assert.False(latest!["canRequestAcceptance"]!.GetValue<bool>());await using(var db=s.Api.Context())await db.Set<EnvironmentRecord>().ExecuteUpdateAsync(x=>x.SetProperty(e=>e.AccessAddressRevision,2));var changed=await s.Api.Client.GetFromJsonAsync<JsonObject>(path);Assert.False(changed!["canRequestAcceptance"]!.GetValue<bool>());}
    [Fact] public async Task AcceptanceActionsExposeServerAuthorityAndIndependence()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var ids=new List<Guid>();foreach(var type in new[]{"InterfaceFunction","Integration","ContractCompatibility"}){using var r=await s.RecordAsync(type:type);ids.Add((await r.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!.Id);}using var request=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/release-artifacts/{s.Artifact.Id}/test-acceptances",new RequestTestAcceptanceRequest(ids));request.EnsureSuccessStatusCode();var a=(await request.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;var path=$"/api/v1/test-acceptances/{a.Id}";var applicant=await s.Api.Client.GetFromJsonAsync<JsonObject>(path);Assert.False(applicant!["canAccept"]!.GetValue<bool>());var actor=await s.Api.NewReviewerAsync("IndependentAcceptor");await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(x=>x.UserId==actor.User.Id).Select(x=>x.RoleId).SingleAsync();foreach(var code in new[]{"environment.read","route.read","api.read","api.version.read","api.schema.read","release.test.accept"}){var p=await db.Set<Permission>().SingleOrDefaultAsync(x=>x.Code==code);if(p is null){p=new(){Code=code,Module="release",Name=code};db.Add(p);}db.Add(new RolePermission{RoleId=role,PermissionId=p.Id});}await db.SaveChangesAsync();}var independent=await actor.Client.GetFromJsonAsync<JsonObject>(path);Assert.True(independent!["canAccept"]!.GetValue<bool>());Assert.True(independent["canReject"]!.GetValue<bool>());await using(var db=s.Api.Context())await db.Set<ReleaseVerification>().ExecuteUpdateAsync(x=>x.SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddMinutes(-1)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddHours(-2)).SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddHours(-3)));var expired=await actor.Client.GetFromJsonAsync<JsonObject>(path);Assert.False(expired!["canAccept"]!.GetValue<bool>());Assert.True(expired["canReject"]!.GetValue<bool>());}
    [Fact] public async Task ArtifactListPaginatesMetadataAndNeverExposesFrozenBodies()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){for(var i=0;i<50;i++){var release=new ReleaseRecord{EnvironmentId=s.Api.Environment.Id,ReleaseNo="FIXTURE-"+Guid.NewGuid().ToString("N"),RequestedBy=s.Api.User.Id,Status="Succeeded"};db.Add(release);db.Add(new ReleaseArtifact{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,SourceEnvironmentId=s.Api.Environment.Id,SourceReleaseId=release.Id,ArtifactHash=new string('a',64),SourceSnapshotHash=new string('b',64),CanonicalContent="{\"apis\":[],\"routes\":[]}",CreatedBy=s.Api.User.Id});}await db.SaveChangesAsync();}using var response=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/release-artifacts");response.EnsureSuccessStatusCode();var text=await response.Content.ReadAsStringAsync();var page=JsonNode.Parse(text)!;Assert.Equal(51,page["total"]!.GetValue<int>());Assert.Equal(50,page["items"]!.AsArray().Count);Assert.DoesNotContain("canonicalContent",text);Assert.DoesNotContain("source-gateway.example",text);using var next=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/release-artifacts?page=2&pageSize=50");next.EnsureSuccessStatusCode();Assert.Single(JsonNode.Parse(await next.Content.ReadAsStringAsync())!["items"]!.AsArray());}
    [Fact] public async Task MissingSchemaPermissionCannotReadArtifactCounts()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){var p=await db.Set<Permission>().SingleAsync(x=>x.Code=="api.schema.read");await db.Set<RolePermission>().Where(x=>x.PermissionId==p.Id).ExecuteDeleteAsync();}using var response=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/release-artifacts");Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);Assert.DoesNotContain("total",await response.Content.ReadAsStringAsync());}
}
