using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineStageEvidenceTests
{
 internal static async Task<Guid> VersionAsync(PipelineScenario s,int validity=1440,string[]? types=null)
 {var definition=s.Definition with{Stages=s.Definition.Stages.Select((stage,i)=>i==0?stage with{EvidenceValidityMinutes=validity,RequiredTestTypes=types??stage.RequiredTestTypes}:stage).ToArray()};using var draft=await s.Api.WriteAsync(HttpMethod.Post,$"/api/v1/projects/{s.Api.Project.Id}/release-pipelines",definition);draft.EnsureSuccessStatusCode();var id=(await draft.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();var version=(await PipelineDefinitionTests.PublishAsync(s,id)).GetProperty("id").GetGuid();await PipelineActivationTests.SeedBaselineAsync(s);using var activated=await PipelineActivationTests.ActivateAsync(s,version);activated.EnsureSuccessStatusCode();return version;}
 internal static async Task<(UserRecord User,HttpClient Client)> DelegateAsync(PipelineScenario s)
 {var user=await s.Api.NewReviewerAsync("PipelineEvidence_"+Guid.NewGuid().ToString("N"));await s.GrantAsync(user.User.Id,"environment.read","release.read","route.read","api.read","api.version.read","api.schema.read","policy.read","release.create","pipeline.read","pipeline.run","release.test.record","release.test.accept");return user;}
 internal static async Task<PipelineVerificationContextDto> ContextAsync(HttpClient client,Guid stage)
 {using var response=await client.GetAsync($"/api/v1/release-pipeline-run-stages/{stage}/verification-context");Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Equal("no-store",response.Headers.CacheControl!.ToString());return (await response.Content.ReadFromJsonAsync<PipelineVerificationContextDto>())!;}
 internal static Task<HttpResponseMessage> RecordAsync(HttpClient client,Guid stage,PipelineVerificationContextDto context,string type="InterfaceFunction",DateTimeOffset? finished=null,Guid? report=null,string? nested=null,string? hash=null,string? key=null)=>ApiFixture.CommandAsync(client,$"/api/v1/release-pipeline-run-stages/{stage}/verifications",new PipelineStageVerificationRequest(hash??context.ContextHash,new(type,"Passed",finished??DateTimeOffset.UtcNow,finished??DateTimeOffset.UtcNow,report,"阶段人工登记",nested)),key);
 internal static async Task<Guid[]> EvidenceAsync(HttpClient client,Guid stage,PipelineVerificationContextDto context)
 {var ids=new List<Guid>();foreach(var type in context.RequiredTypes){using var response=await RecordAsync(client,stage,context,type);Assert.Equal(HttpStatusCode.OK,response.StatusCode);ids.Add((await response.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!.Id);}return ids.ToArray();}
 [Fact] public async Task FirstSourceMayRegisterBeforeRunStartedButAfterActualDeployment()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await VersionAsync(s);var run=await s.StartAsync(version);var stage=run.Stages[0];var context=await ContextAsync(s.Creator,stage.Id);await using var db=s.Api.Context();var completed=(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==s.Source.ReleaseId)).CompletedAt!.Value;Assert.True(completed<run.CreatedAt);using var valid=await RecordAsync(s.Creator,stage.Id,context,finished:completed);Assert.Equal(HttpStatusCode.OK,valid.StatusCode);using var before=await RecordAsync(s.Creator,stage.Id,context,finished:completed.AddTicks(-1));Assert.Equal(HttpStatusCode.UnprocessableEntity,before.StatusCode);var row=await db.Set<ReleaseVerification>().SingleAsync(v=>v.PipelineRunStageId==stage.Id);Assert.Equal(stage.CurrentAttemptId,row.StageAttemptId);Assert.Equal(stage.ProfileHash,row.ProfileHash);Assert.Equal(s.RootArtifactId,row.ArtifactId);}
 [Fact] public async Task FrozenOwnTypesAndValidityReplaceProjectSummaryDefaults()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var version=await VersionAsync(s,30,["InterfaceFunction"]);var stage=(await s.StartAsync(version)).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);Assert.Equal(30,context.EvidenceValidityMinutes);Assert.Equal(new[]{"InterfaceFunction"},context.RequiredTypes);using var rejected=await RecordAsync(s.Creator,stage.Id,context,"Integration");Assert.Equal(HttpStatusCode.UnprocessableEntity,rejected.StatusCode);using var valid=await RecordAsync(s.Creator,stage.Id,context);Assert.Equal(HttpStatusCode.OK,valid.StatusCode);var fact=(await valid.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!;Assert.Equal(TimeSpan.FromMinutes(30),fact.ExpiresAt-fact.FinishedAt);using var old=await s.Source.RecordAsync();Assert.Equal(HttpStatusCode.Conflict,old.StatusCode);}
 [Theory][InlineData("stale")][InlineData("missing")][InlineData("nested")]
 public async Task RequestMustUseExactlyTheCurrentWrapperContext(string kind)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);if(kind=="stale"){await using var db=s.Api.Context();var env=await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==stage.EnvironmentId);env.BasePath="/changed";env.AccessAddressRevision++;await db.SaveChangesAsync();}using var response=await RecordAsync(s.Creator,stage.Id,context,nested:kind=="nested"?new string('f',64):null,hash:kind=="missing"?"":null);Assert.Equal(kind=="stale"?HttpStatusCode.Conflict:HttpStatusCode.UnprocessableEntity,response.StatusCode);}
 [Fact] public async Task NewAttemptChangesContextAndRaisesEvidenceTimeFloor()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await VersionAsync(s));var stage=run.Stages[0];var old=await ContextAsync(s.Creator,stage.Id);DateTimeOffset activated;await using(var db=s.Api.Context()){var prior=await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==stage.CurrentAttemptId);prior.Status="TimedOut";await db.SaveChangesAsync();var next=new ReleasePipelineStageAttempt{RunStageId=stage.Id,RunId=run.Id,ProjectId=run.ProjectId,EnvironmentId=stage.EnvironmentId,AttemptNo=2,OriginAttemptId=prior.Id,ActualReleaseId=s.Source.ReleaseId,ArtifactId=s.RootArtifactId,DeadlineAt=DateTimeOffset.UtcNow.AddHours(1)};activated=next.ActivatedAt;db.Add(next);await db.SaveChangesAsync();(await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==stage.Id)).CurrentAttemptId=next.Id;await db.SaveChangesAsync();}var context=await ContextAsync(s.Creator,stage.Id);Assert.NotEqual(old.ContextHash,context.ContextHash);using var stale=await RecordAsync(s.Creator,stage.Id,old);Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);using var early=await RecordAsync(s.Creator,stage.Id,context,finished:activated.AddMilliseconds(-1));Assert.Equal(HttpStatusCode.UnprocessableEntity,early.StatusCode);using var fresh=await RecordAsync(s.Creator,stage.Id,context);Assert.Equal(HttpStatusCode.OK,fresh.StatusCode);}
 [Fact] public async Task CurrentStageWithoutBoundArtifactCannotRegisterEvidence()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var run=await s.StartAsync(await VersionAsync(s));var stage=run.Stages[1];await using(var db=s.Api.Context()){var root=await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==run.Stages[0].Id);root.Status="Passed";(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==root.CurrentAttemptId)).Status="Passed";(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).CurrentStageOrder=2;var target=await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==stage.Id);target.Status="AwaitingVerification";var attempt=new ReleasePipelineStageAttempt{RunStageId=stage.Id,RunId=run.Id,ProjectId=run.ProjectId,EnvironmentId=stage.EnvironmentId,AttemptNo=1,DeadlineAt=DateTimeOffset.UtcNow.AddHours(1)};db.Add(attempt);await db.SaveChangesAsync();target.CurrentAttemptId=attempt.Id;await db.SaveChangesAsync();}using var rejected=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/verifications",new PipelineStageVerificationRequest(new string('f',64),new("InterfaceFunction","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow)));Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);Assert.Contains("pipeline_stage_artifact_required",await rejected.Content.ReadAsStringAsync());}
 [Fact] public async Task ReportMustBelongToTheActualStageArtifact()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);using var upload=await s.Source.UploadAsync(System.Text.Encoding.UTF8.GetBytes("真实归属的人工测试说明"));upload.EnsureSuccessStatusCode();var id=(await upload.Content.ReadFromJsonAsync<VerificationReportDto>())!.Id;using var valid=await RecordAsync(s.Creator,stage.Id,context,report:id);Assert.Equal(HttpStatusCode.OK,valid.StatusCode);Guid other;await using(var db=s.Api.Context()){var root=await db.Set<ReleaseArtifact>().SingleAsync(a=>a.Id==s.RootArtifactId);var content=s.Source.Artifact.Content with{Routes=[s.Source.Artifact.Content.Routes[0] with{Path="/another-owned-artifact",Key=""}]};content=WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Normalize(content);var artifact=new ReleaseArtifact{OrganizationId=root.OrganizationId,ProjectId=root.ProjectId,SourceEnvironmentId=root.SourceEnvironmentId,SourceReleaseId=root.SourceReleaseId,CanonicalContent=System.Text.Encoding.UTF8.GetString(WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Serialize(content)),ArtifactHash=WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Hash(content),SourceSnapshotHash=root.SourceSnapshotHash,CreatedBy=s.Api.User.Id};db.Add(artifact);await db.SaveChangesAsync();other=artifact.Id;}using var foreign=await s.Source.UploadAsync([65,66],artifact:other);foreign.EnsureSuccessStatusCode();var foreignId=(await foreign.Content.ReadFromJsonAsync<VerificationReportDto>())!.Id;using var rejected=await RecordAsync(s.Creator,stage.Id,context,report:foreignId);Assert.Equal(HttpStatusCode.NotFound,rejected.StatusCode);Assert.Contains("resource_not_found",await rejected.Content.ReadAsStringAsync());}
 [Fact] public async Task RunCreatorCannotAcceptDelegatesRequestAndIndependentUserCan()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await VersionAsync(s);var creator=await DelegateAsync(s);var requester=await DelegateAsync(s);var acceptor=await DelegateAsync(s);using var start=await ApiFixture.CommandAsync(creator.Client,"/api/v1/release-pipeline-runs",new CreatePipelineRunRequest(version,s.RootArtifactId));Assert.Equal(HttpStatusCode.OK,start.StatusCode);var run=(await start.Content.ReadFromJsonAsync<PipelineRunDto>())!;var stage=run.Stages[0];var context=await ContextAsync(requester.Client,stage.Id);var ids=await EvidenceAsync(requester.Client,stage.Id,context);using var request=await ApiFixture.CommandAsync(requester.Client,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));Assert.True(request.StatusCode==HttpStatusCode.OK,await request.Content.ReadAsStringAsync());var acceptance=(await request.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;using var denied=await ActAsync(creator.Client,acceptance.Id,"accept");Assert.Equal(HttpStatusCode.Forbidden,denied.StatusCode);using var self=await ActAsync(requester.Client,acceptance.Id,"accept");Assert.Equal(HttpStatusCode.Forbidden,self.StatusCode);using var sourceApplicant=await ActAsync(s.Creator,acceptance.Id,"accept");Assert.Equal(HttpStatusCode.Forbidden,sourceApplicant.StatusCode);using var valid=await ActAsync(acceptor.Client,acceptance.Id,"accept");Assert.Equal(HttpStatusCode.OK,valid.StatusCode);await using var db=s.Api.Context();var row=await db.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==acceptance.Id);Assert.Equal("Accepted",row.Status);Assert.Equal(stage.Id,row.PipelineRunStageId);Assert.Equal(context.CurrentAttemptId,row.StageAttemptId);Assert.Equal(context.ProfileHash,row.ProfileHash);}
 internal static async Task<HttpResponseMessage> ActAsync(HttpClient client,Guid acceptance,string action)
 {using var get=await client.GetAsync($"/api/v1/test-acceptances/{acceptance}");get.EnsureSuccessStatusCode();using var request=new HttpRequestMessage(HttpMethod.Post,$"/api/v1/test-acceptances/{acceptance}/{action}"){Content=JsonContent.Create(new TestAcceptanceActionRequest("阶段独立验收"))};request.Headers.Add("X-CSRF-Token",(await client.GetFromJsonAsync<Dictionary<string,string>>("/api/v1/auth/csrf"))!["token"]);request.Headers.Add("If-Match",get.Headers.ETag!.Tag);request.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString("N"));return await client.SendAsync(request);}
 [Fact] public async Task ExpiredEvidenceCannotRequestAcceptance()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await VersionAsync(s,1);await using(var db=s.Api.Context()){(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==s.Source.ReleaseId)).CompletedAt=DateTimeOffset.UtcNow.AddMinutes(-10);await db.SaveChangesAsync();}var stage=(await s.StartAsync(version)).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);var ids=new List<Guid>();foreach(var type in context.RequiredTypes){using var record=await RecordAsync(s.Creator,stage.Id,context,type,finished:DateTimeOffset.UtcNow.AddMinutes(-2));Assert.Equal(HttpStatusCode.OK,record.StatusCode);ids.Add((await record.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!.Id);}using var rejected=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);}
 [Fact] public async Task MaterializationDoesNotPublishAndRootMismatchPersistsInvalidation()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await VersionAsync(s));var stage=run.Stages[0];using var one=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/materialize-artifact");Assert.Equal(HttpStatusCode.OK,one.StatusCode);Assert.Equal(s.RootArtifactId,(await one.Content.ReadFromJsonAsync<ReleaseArtifactDto>())!.Id);await using(var db=s.Api.Context()){(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).RootArtifactHash=new string('f',64);await db.SaveChangesAsync();}using var mismatch=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/materialize-artifact");Assert.Equal(HttpStatusCode.Conflict,mismatch.StatusCode);await using var context=s.Api.Context();Assert.Equal("Invalidated",(await context.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);Assert.Equal("Invalidated",(await context.Set<ReleasePipelineRunStage>().SingleAsync(r=>r.Id==stage.Id)).Status);}
 [Theory][InlineData("profile")][InlineData("attempt")]
 public async Task WrongBindingCannotBeUsedAsCurrentEvidence(string change)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await VersionAsync(s));var stage=run.Stages[0];var context=await ContextAsync(s.Creator,stage.Id);var ids=await EvidenceAsync(s.Creator,stage.Id,context);await using(var db=s.Api.Context()){var fact=await db.Set<ReleaseVerification>().SingleAsync(v=>v.Id==ids[0]);if(change=="profile")fact.ProfileHash=new string('f',64);else{var other=new ReleasePipelineStageAttempt{RunStageId=stage.Id,RunId=run.Id,ProjectId=run.ProjectId,EnvironmentId=stage.EnvironmentId,AttemptNo=2,OriginAttemptId=stage.CurrentAttemptId,Status="Rejected",DeadlineAt=DateTimeOffset.UtcNow.AddHours(1)};db.Add(other);await db.SaveChangesAsync();fact.StageAttemptId=other.Id;}await db.SaveChangesAsync();}using var rejected=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);}
 [Fact] public async Task StageEvidenceUsesOriginalPermissionAndReplaysExactlyOneFact()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var tester=await DelegateAsync(s);await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==tester.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="pipeline.run");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}var context=await ContextAsync(tester.Client,stage.Id);var key=Guid.NewGuid().ToString("N");var finished=DateTimeOffset.UtcNow;using var one=await RecordAsync(tester.Client,stage.Id,context,finished:finished,key:key);Assert.Equal(HttpStatusCode.OK,one.StatusCode);using var replay=await RecordAsync(tester.Client,stage.Id,context,finished:finished,key:key);Assert.Equal(HttpStatusCode.OK,replay.StatusCode);Assert.Equal(await one.Content.ReadAsStringAsync(),await replay.Content.ReadAsStringAsync());using var different=await RecordAsync(tester.Client,stage.Id,context,finished:finished.AddTicks(1),key:key);Assert.Equal(HttpStatusCode.Conflict,different.StatusCode);await using var check=s.Api.Context();Assert.Equal(1,await check.Set<ReleaseVerification>().CountAsync(v=>v.PipelineRunStageId==stage.Id));}
 [Fact] public async Task SupersededAcceptanceCannotBecomeTheCurrentStageProof()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);var ids=await EvidenceAsync(s.Creator,stage.Id,context);var body=new PipelineAcceptanceRequest(context.ContextHash,ids);using var first=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",body);Assert.Equal(HttpStatusCode.OK,first.StatusCode);var old=(await first.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;using var second=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",body);Assert.Equal(HttpStatusCode.OK,second.StatusCode);var current=(await second.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;var acceptor=await DelegateAsync(s);using var stale=await ActAsync(acceptor.Client,old.Id,"accept");Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);using var valid=await ActAsync(acceptor.Client,current.Id,"accept");Assert.Equal(HttpStatusCode.OK,valid.StatusCode);}
 [Fact] public async Task RecorderWhosePermissionWasRevokedCannotSupplyCurrentStageEvidence()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var tester=await DelegateAsync(s);var context=await ContextAsync(tester.Client,stage.Id);var ids=await EvidenceAsync(tester.Client,stage.Id,context);await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==tester.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="release.test.record");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}using var rejected=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);}
 [Fact] public async Task RepeatedMaterializationCannotResetPendingAcceptance()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await VersionAsync(s));var stage=run.Stages[0];var context=await ContextAsync(s.Creator,stage.Id);var ids=await EvidenceAsync(s.Creator,stage.Id,context);using var requested=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));Assert.Equal(HttpStatusCode.OK,requested.StatusCode);using var materialized=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/materialize-artifact");Assert.Equal(HttpStatusCode.OK,materialized.StatusCode);Assert.Equal("AwaitingAcceptance",(await s.CurrentStageAsync(run.Id)).Status);}
 [Fact] public async Task AuditCarriesStageBindingWithoutAccessContextBody()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await VersionAsync(s))).Stages[0];var context=await ContextAsync(s.Creator,stage.Id);using var response=await RecordAsync(s.Creator,stage.Id,context);Assert.Equal(HttpStatusCode.OK,response.StatusCode);var verification=(await response.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!;await using var db=s.Api.Context();var audit=await db.Set<AuditLog>().SingleAsync(a=>a.Action=="pipeline.stage.verification");Assert.NotNull(audit.AfterJson);using var json=JsonDocument.Parse(audit.AfterJson!);var fact=json.RootElement.EnumerateArray().Single(e=>e.GetProperty("Type").GetString()=="ReleaseVerification").GetProperty("Fields");Assert.Equal(verification.Id,fact.GetProperty("Id").GetGuid());Assert.True(fact.TryGetProperty("PipelineRunStageId",out var stageId));Assert.Equal(stage.Id,stageId.GetGuid());Assert.Equal(context.CurrentAttemptId,fact.GetProperty("StageAttemptId").GetGuid());Assert.Equal(context.ProfileHash,fact.GetProperty("ProfileHash").GetString());var related=json.RootElement.EnumerateArray().Single(e=>e.GetProperty("Type").GetString()=="ReleasePipelineEvent").GetProperty("Fields");Assert.Equal(context.CurrentAttemptId,related.GetProperty("AttemptId").GetGuid());Assert.DoesNotContain("AccessContextJson",audit.AfterJson);Assert.DoesNotContain("source-gateway.example",audit.AfterJson);}
}
