using System.Net.Http.Json;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineOverviewTests
{
 [Fact] public async Task OverviewSeparatesStandalonePromotionsFromPipelineRunsAndActualNodeFacts()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var pipeline=await PipelineExecutionTests.SubmittedAsync(f);await using(var db=f.Scenario.Api.Context()){db.Add(new ReleasePromotion{OrganizationId=f.Scenario.Api.Organization.Id,ProjectId=f.Run.ProjectId,ArtifactId=f.Scenario.RootArtifactId,SourceReleaseId=f.Scenario.Source.ReleaseId,SourceEnvironmentId=f.Scenario.Environments[0],TargetEnvironmentId=f.TargetEnvironmentId,RequestedBy=f.Scenario.Api.User.Id,Status="WaitingApproval"});await db.SaveChangesAsync();}var view=await PipelineReadTests.JsonAsync(f.Scenario.Creator,$"/api/v1/delivery/overview?projectId={f.Run.ProjectId}");Assert.Equal(1,view["promotions"]!["total"]!.GetValue<int>());Assert.Equal(1,view["counts"]!["awaitingApproval"]!.GetValue<int>());Assert.Equal("Full",view["pipelineVisibility"]!.GetValue<string>());Assert.Equal(1,view["pipelineCounts"]!["total"]!.GetValue<int>());Assert.Equal(1,view["pipelineCounts"]!["active"]!.GetValue<int>());Assert.Single(view["pipelineRuns"]!["items"]!.AsArray());Assert.Equal(2,view["environments"]!.AsArray().Count);Assert.DoesNotContain(pipeline.Id.ToString(),view["promotions"]!.ToJsonString());}
 [Fact] public async Task RestrictedPipelineOverviewKeepsRealEnvironmentsAndNullCounts()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="pipeline.read");await db.Set<RolePermission>().Where(r=>r.PermissionId==permission.Id).ExecuteDeleteAsync();}var view=await PipelineReadTests.JsonAsync(s.Creator,$"/api/v1/delivery/overview?projectId={s.Api.Project.Id}");Assert.Equal("Restricted",view["pipelineVisibility"]!.GetValue<string>());Assert.Null(view["pipelineRuns"]);Assert.Null(view["pipelineCounts"]);Assert.Equal(2,view["environments"]!.AsArray().Count);}
 [Fact] public async Task FormalReleaseAndApprovalInboxExposeOnlyAuthorizedStageTrace()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.SubmittedAsync(f);var full=await PipelineReadTests.JsonAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}");Assert.Equal(f.TargetStageId.ToString(),full["delivery"]!["pipeline"]!["stageId"]!.GetValue<string>());var user=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await PipelineReadTests.ScopeAsync(f.Scenario,user.User.Id,(f.TargetEnvironmentId,"read_only"));var restricted=await PipelineReadTests.JsonAsync(user.Client,$"/api/v1/releases/{p.TargetReleaseId}");Assert.Equal("Restricted",restricted["delivery"]!["visibility"]!.GetValue<string>());Assert.Null(restricted["delivery"]!["pipeline"]);var inbox=await PipelineReadTests.JsonAsync(f.Scenario.Creator,"/api/v1/approvals?view=AllVisible");var row=inbox["page"]!["items"]!.AsArray().Single(x=>x!["id"]!.GetValue<string>()==p.TargetReleaseId.ToString());Assert.Equal("PipelineStage",row!["applicationKind"]!.GetValue<string>());Assert.Equal(f.TargetStageId.ToString(),row["delivery"]!["pipeline"]!["stageId"]!.GetValue<string>());}
}
