using System.Net;
using System.Net.Http.Json;
using System.Text.Json.Nodes;
using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Common;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Delivery.Pipelines;
using WebApi.Infrastructure.Governance;
using WebApi.Infrastructure.Persistence;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Infrastructure.Security;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineReadTests
{
 internal static async Task ScopeAsync(PipelineScenario s,Guid user,params (Guid Environment,string Mode)[] environments)
 {await using var db=s.Api.Context();await db.Set<UserProjectScope>().Where(g=>g.UserId==user).ExecuteDeleteAsync();foreach(var env in environments)db.Add(new UserProjectScope{UserId=user,OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,EnvironmentId=env.Environment,AccessMode=env.Mode});await db.SaveChangesAsync();}
 internal static async Task<JsonObject> JsonAsync(HttpClient client,string path)
 {using var response=await client.GetAsync(path);Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());Assert.Equal("no-store",response.Headers.CacheControl!.ToString());return (await response.Content.ReadFromJsonAsync<JsonObject>())!;}
 internal static async Task SeedHistoricalRunsAsync(PipelineScenario s,PipelineRunDto run,int extra)
 {await using var db=s.Api.Context();for(var i=0;i<extra;i++){var row=new ReleasePipelineRun{OrganizationId=s.Api.Organization.Id,ProjectId=run.ProjectId,PipelineVersionId=run.PipelineVersionId,DefinitionHash=run.DefinitionHash,RootArtifactId=s.RootArtifactId,RootArtifactHash=s.Source.Artifact.ArtifactHash,SourceEnvironmentId=s.Environments[0],SourceReleaseId=s.Source.ReleaseId,SourceConfigVersion=1,SourceDeploymentSequence=1,PolicyRevision=run.PolicyRevision,CreatedBy=s.Api.User.Id,Status="Cancelled",CompletedAt=DateTimeOffset.UtcNow};db.Add(row);Guid? previous=null;foreach(var stage in run.Stages){var next=new ReleasePipelineRunStage{RunId=row.Id,ProjectId=row.ProjectId,StageOrder=stage.StageOrder,EnvironmentId=stage.EnvironmentId,SourceStageId=previous,ProfileJson=System.Text.Encoding.UTF8.GetString(CanonicalJson.Serialize(stage.Profile!)),ProfileHash=stage.ProfileHash,Status="Cancelled"};db.Add(next);previous=next.Id;}}await db.SaveChangesAsync();}
 [Fact] public async Task FullRunAndStageAreNoStoreAndExposeOnlyTheirCurrentAttemptFacts()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));var view=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs/{run.Id}");Assert.Equal("Full",view["coverage"]!.GetValue<string>());Assert.Equal(s.RootArtifactId.ToString(),view["rootArtifactId"]!.GetValue<string>());var stage=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{run.Stages[0].Id}");Assert.True(stage["eligibility"]!["canRecord"]!.GetValue<bool>());Assert.Equal(s.Source.ReleaseId.ToString(),stage["actualReleaseId"]!.GetValue<string>());Assert.Single(stage["attempts"]!.AsArray());Assert.DoesNotContain("secretHash",stage.ToJsonString(),StringComparison.OrdinalIgnoreCase);}
 [Fact] public async Task FourEnvironmentDelegateCanActWithoutEarlierChainDisclosure()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(4);await PipelineExecutionTests.SubmittedAsync(f);await f.Scenario.DeployCurrentAsync(f.Run.Id,f.Scenario.Creator);var independent=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await f.Scenario.PassCurrentAsync(f.Run.Id,f.Scenario.Creator,independent.Client);var current=await f.Scenario.CurrentStageAsync(f.Run.Id);Assert.Equal(3,current.StageOrder);var delegated=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await ScopeAsync(f.Scenario,delegated.User.Id,(f.TargetEnvironmentId,"read_only"),(current.EnvironmentId,"read_write"));var stage=await JsonAsync(delegated.Client,$"/api/v1/release-pipeline-run-stages/{current.Id}");Assert.True(stage["eligibility"]!["canPrepare"]!.GetValue<bool>());Assert.False(stage["eligibility"]!["canCancelRun"]!.GetValue<bool>());var run=await JsonAsync(delegated.Client,$"/api/v1/release-pipeline-runs/{f.Run.Id}");Assert.Equal("Partial",run["coverage"]!.GetValue<string>());Assert.Null(run["rootArtifactId"]);Assert.Null(run["rootArtifactHash"]);Assert.Null(run["sourceEnvironmentId"]);Assert.DoesNotContain(f.Scenario.Environments[0].ToString(),run.ToJsonString());Assert.DoesNotContain(f.Scenario.Environments[3].ToString(),run.ToJsonString());var page=await JsonAsync(delegated.Client,"/api/v1/release-pipeline-runs");Assert.Null(page["total"]);using var hidden=await delegated.Client.GetAsync($"/api/v1/release-pipeline-run-stages/{f.Run.Stages[0].Id}");Assert.Equal(HttpStatusCode.NotFound,hidden.StatusCode);}
 [Theory][InlineData("scope")][InlineData("contract")][InlineData("permission")]
 public async Task DirectStageReadRequiresItsActualScopeDirectSourceContractAndPipelineRead(string fault)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(4);var user=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);if(fault=="scope")await ScopeAsync(f.Scenario,user.User.Id,(f.TargetEnvironmentId,"read_write"));else{await using var db=f.Scenario.Api.Context();var role=await db.Set<UserRole>().Where(r=>r.UserId==user.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code==(fault=="contract"?"api.schema.read":"pipeline.read"));await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}using var response=await user.Client.GetAsync($"/api/v1/release-pipeline-run-stages/{f.TargetStageId}");Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);Assert.DoesNotContain(f.Scenario.Source.Artifact.ArtifactHash,await response.Content.ReadAsStringAsync());}
 [Fact] public async Task MissingContractProjectsRestrictedMetadataAndNullCountsInsteadOfZero()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="api.schema.read");await db.Set<RolePermission>().Where(r=>r.PermissionId==permission.Id).ExecuteDeleteAsync();}var view=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs/{run.Id}");Assert.Equal("Restricted",view["coverage"]!.GetValue<string>());Assert.Null(view["rootArtifactId"]);Assert.All(view["stages"]!.AsArray(),stage=>{Assert.Null(stage!["profile"]);Assert.Null(stage["stageArtifactId"]);});var page=await JsonAsync(s.Creator,"/api/v1/release-pipeline-runs");Assert.Equal("Restricted",page["coverage"]!.GetValue<string>());Assert.Null(page["total"]);Assert.Single(page["items"]!.AsArray());}
 [Fact] public async Task RunPaginationCountsAuthorizedRowsBeforePagingAndCapsAt100()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await SeedHistoricalRunsAsync(s,run,50);var page=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs?projectId={run.ProjectId}");Assert.Equal(51,page["total"]!.GetValue<int>());Assert.Equal(50,page["size"]!.GetValue<int>());Assert.Equal(50,page["items"]!.AsArray().Count);var next=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs?projectId={run.ProjectId}&page=2&size=50");Assert.Single(next["items"]!.AsArray());var capped=await JsonAsync(s.Creator,"/api/v1/release-pipeline-runs?size=101");Assert.Equal(100,capped["size"]!.GetValue<int>());}
 [Fact] public async Task EnvironmentOnlyRunListingIsPartialAndProjectScopeCanReadFullProjection()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));var user=await PipelineStageEvidenceTests.DelegateAsync(s);await ScopeAsync(s,user.User.Id,(s.Environments[0],"read_only"));var partial=await JsonAsync(user.Client,$"/api/v1/release-pipeline-runs?projectId={run.ProjectId}");Assert.Equal("Partial",partial["coverage"]!.GetValue<string>());Assert.Null(partial["total"]);Assert.Single(partial["items"]!.AsArray());await using(var db=s.Api.Context()){await db.Set<UserProjectScope>().Where(g=>g.UserId==user.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.EnvironmentId,(Guid?)null));}var full=await JsonAsync(user.Client,$"/api/v1/release-pipeline-runs/{run.Id}");Assert.Equal("Full",full["coverage"]!.GetValue<string>());}
 [Fact] public async Task UnknownRunStageAndForeignProjectNeverRevealCounts()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();foreach(var path in new[]{"/api/v1/release-pipeline-runs/"+Guid.NewGuid(),"/api/v1/release-pipeline-run-stages/"+Guid.NewGuid(),"/api/v1/release-pipeline-runs?projectId="+Guid.NewGuid()}){using var response=await s.Creator.GetAsync(path);Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);Assert.DoesNotContain("rootArtifactHash",await response.Content.ReadAsStringAsync());}}
 [Fact] public async Task ArtifactTraceIsPaginatedManyToManyAndRechecksSourcePermission()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await SeedHistoricalRunsAsync(s,run,2);await using(var db=s.Api.Context()){foreach(var stage in await db.Set<ReleasePipelineRunStage>().Where(t=>t.StageOrder==1).ToArrayAsync())stage.StageArtifactId=s.RootArtifactId;await db.SaveChangesAsync();}var page=await JsonAsync(s.Creator,$"/api/v1/release-artifacts/{s.RootArtifactId}/pipeline-traces?size=2");Assert.Equal(3,page["total"]!.GetValue<int>());Assert.Equal(2,page["items"]!.AsArray().Count);var next=await JsonAsync(s.Creator,$"/api/v1/release-artifacts/{s.RootArtifactId}/pipeline-traces?size=2&page=2");Assert.Single(next["items"]!.AsArray());await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="api.schema.read");await db.Set<RolePermission>().Where(r=>r.PermissionId==permission.Id).ExecuteDeleteAsync();}using var denied=await s.Creator.GetAsync($"/api/v1/release-artifacts/{s.RootArtifactId}/pipeline-traces");Assert.Equal(HttpStatusCode.NotFound,denied.StatusCode);}
 [Fact] public async Task StageReportDownloadRechecksActualOwnerAfterPermissionRevocation()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await s.GrantAsync(s.Api.User.Id,"release.verification.report.upload");using var uploaded=await s.Source.UploadAsync(System.Text.Encoding.UTF8.GetBytes("本阶段测试报告"));uploaded.EnsureSuccessStatusCode();var report=(await uploaded.Content.ReadFromJsonAsync<VerificationReportDto>())!;var ctx=await PipelineStageEvidenceTests.ContextAsync(s.Creator,run.Stages[0].Id);using(var recorded=await PipelineStageEvidenceTests.RecordAsync(s.Creator,run.Stages[0].Id,ctx,report:report.Id))recorded.EnsureSuccessStatusCode();using(var first=await s.Creator.GetAsync($"/api/v1/verification-reports/{report.Id}/download"))first.EnsureSuccessStatusCode();await using(var db=s.Api.Context()){var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="api.schema.read");await db.Set<RolePermission>().Where(r=>r.PermissionId==permission.Id).ExecuteDeleteAsync();}using var denied=await s.Creator.GetAsync($"/api/v1/verification-reports/{report.Id}/download");Assert.Equal(HttpStatusCode.NotFound,denied.StatusCode);}
 [Fact] public async Task DefinitionPageIsFilteredAndBoundedInDatabaseBeforeCounting()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await using(var seed=s.Api.Context()){for(var i=0;i<50;i++)seed.Add(new ReleasePipeline{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,Name="分页定义"+i,DraftJson=System.Text.Encoding.UTF8.GetString(CanonicalJson.Serialize(s.Definition)),CreatedBy=s.Api.User.Id,UpdatedBy=s.Api.User.Id});await seed.SaveChangesAsync();}var capture=new PageCapture();await using var db=new WebApiDbContext(new DbContextOptionsBuilder<WebApiDbContext>().UseNpgsql(s.Api.Database.ConnectionString).AddInterceptors(capture).Options);var service=new PipelineReadService(db,new ScopeResolver(db),new AuthorizationService(db));var full=await service.ListPipelinesAsync(s.Api.Project.Id,1,50,new(s.Api.User.Id,"page"),default);Assert.Equal(51,full.Total);Assert.Equal(50,full.Items.Count);Assert.Contains("LIMIT",capture.Command,StringComparison.OrdinalIgnoreCase);var user=await PipelineStageEvidenceTests.DelegateAsync(s);await s.GrantAsync(user.User.Id,"project.read");await using(var scope=s.Api.Context()){await scope.Set<UserProjectScope>().Where(g=>g.UserId==user.User.Id).ExecuteDeleteAsync();scope.Add(new UserProjectScope{UserId=user.User.Id,OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,AccessMode="read_only"});var permission=await scope.Set<Permission>().SingleAsync(p=>p.Code=="environment.read");var role=await scope.Set<UserRole>().Where(r=>r.UserId==user.User.Id).Select(r=>r.RoleId).SingleAsync();await scope.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();await scope.SaveChangesAsync();}var restricted=await service.ListPipelinesAsync(s.Api.Project.Id,1,50,new(user.User.Id,"restricted"),default);Assert.Empty(restricted.Items);Assert.Null(restricted.Total);Assert.Equal("Restricted",restricted.Coverage);}
 private sealed class PageCapture:DbCommandInterceptor
 {public string Command{get;private set;}="";public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command,CommandEventData data,InterceptionResult<DbDataReader> result,CancellationToken ct=default){if(command.CommandText.Contains("pipeline-definition-bounded-page",StringComparison.Ordinal))Command=command.CommandText;return ValueTask.FromResult(result);}}
 [Fact] public async Task StageAcceptanceEligibilityUsesQualifiedLatestEvidenceAndRechecksRecorderAuthority()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var stage=(await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s))).Stages[0];var empty=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}");Assert.False(empty["eligibility"]!["canRequestAcceptance"]!.GetValue<bool>());var tester=await PipelineStageEvidenceTests.DelegateAsync(s);var ctx=await PipelineStageEvidenceTests.ContextAsync(tester.Client,stage.Id);await PipelineStageEvidenceTests.EvidenceAsync(tester.Client,stage.Id,ctx);var ready=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}");Assert.True(ready["eligibility"]!["canRequestAcceptance"]!.GetValue<bool>());await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==tester.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="release.test.record");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}var stale=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}");Assert.False(stale["eligibility"]!["canRequestAcceptance"]!.GetValue<bool>());}
 [Fact] public async Task ManualPauseWithExpiredWindowDoesNotOfferResumeAndCannotReopenWhileAnyReleasePublishes()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));using(var pause=await PipelineRecoveryTests.ActionAsync(s,run.Id,"pause"))pause.EnsureSuccessStatusCode();await using(var db=s.Api.Context()){var attempt=await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.RunId==run.Id);attempt.ActivatedAt=DateTimeOffset.UtcNow.AddMinutes(-2);attempt.DeadlineAt=DateTimeOffset.UtcNow.AddMinutes(-1);db.Add(new ReleaseRecord{EnvironmentId=s.Environments[0],ReleaseNo="other-inflight-read-fixture",ReleaseType="publish",Status="Publishing",RequestedBy=s.Api.User.Id,ToConfigVersion=2,DeploymentSequence=2});await db.SaveChangesAsync();}var stage=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{run.Stages[0].Id}");Assert.False(stage["eligibility"]!["canReopen"]!.GetValue<bool>());var view=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs/{run.Id}");Assert.False(view["eligibility"]!["canResume"]!.GetValue<bool>());}
 [Fact] public async Task PausedRunDoesNotOfferResumeAfterActualSourceDeploymentWasReplaced()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));using(var pause=await PipelineRecoveryTests.ActionAsync(s,run.Id,"pause"))pause.EnsureSuccessStatusCode();await s.Source.Deployment.PublishAsync();var view=await JsonAsync(s.Creator,$"/api/v1/release-pipeline-runs/{run.Id}");Assert.False(view["eligibility"]!["canResume"]!.GetValue<bool>());}
 [Fact] public async Task QueryBudgetCoversInitialAuthorizationAndReturns503()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await using var db=new WebApiDbContext(new DbContextOptionsBuilder<WebApiDbContext>().UseNpgsql(s.Api.Database.ConnectionString).AddInterceptors(new SlowRead()).Options);var watch=System.Diagnostics.Stopwatch.StartNew();var service=new PipelineReadService(db,new ScopeResolver(db),new AuthorizationService(db));var error=await Assert.ThrowsAsync<ApiException>(()=>service.ListRunsAsync(null,1,50,new(s.Api.User.Id,"budget"),default));Assert.Equal(503,error.Status);Assert.Equal("pipeline_query_timeout",error.Code);Assert.InRange(watch.Elapsed.TotalSeconds,9,13);}
 private sealed class SlowRead:DbCommandInterceptor
 {public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command,CommandEventData data,InterceptionResult<DbDataReader> result,CancellationToken ct=default){await Task.Delay(TimeSpan.FromSeconds(20),ct);return result;}}
}
