using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Common;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Infrastructure.Delivery.Pipelines;
using WebApi.Worker;
using Microsoft.Extensions.Logging;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineProjectionTests
{
 internal static async Task ProjectAsync(ApiFixture api,Guid runId,TimeProvider? clock=null)
 {using var services=api.Services();var projector=clock is null?services.ServiceProvider.GetRequiredService<PipelineProjectionService>():ActivatorUtilities.CreateInstance<PipelineProjectionService>(services.ServiceProvider,clock);await projector.ProjectRunAsync(runId,CancellationToken.None);}
 internal static async Task<(PipelineRunDto Run,Guid Acceptance)> AcceptSourceAsync(PipelineScenario s)
 {var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));var stage=run.Stages[0];var context=await PipelineStageEvidenceTests.ContextAsync(s.Creator,stage.Id);var ids=await PipelineStageEvidenceTests.EvidenceAsync(s.Creator,stage.Id,context);using var requested=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids));requested.EnsureSuccessStatusCode();var acceptance=(await requested.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;var acceptor=await PipelineStageEvidenceTests.DelegateAsync(s);using var accepted=await PipelineStageEvidenceTests.ActAsync(acceptor.Client,acceptance.Id,"accept");accepted.EnsureSuccessStatusCode();return(run,acceptance.Id);}
 [Fact] public async Task IndependentAcceptancePassesSourceAndStartsOnlyTheNextWindow()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var (run,_)=await AcceptSourceAsync(s);await ProjectAsync(s.Api,run.Id);await using var db=s.Api.Context();Assert.Equal("Passed",(await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==run.Stages[0].Id)).Status);Assert.Equal(2,(await db.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==run.Id)).CurrentStageOrder);var next=await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==run.Stages[1].Id);Assert.Equal("AwaitingMapping",next.Status);var attempt=await db.Set<ReleasePipelineStageAttempt>().SingleAsync(x=>x.Id==next.CurrentAttemptId);Assert.True(attempt.ActivatedAt>=run.CreatedAt);Assert.Equal(TimeSpan.FromMinutes(1440),attempt.DeadlineAt-attempt.ActivatedAt);Assert.False(await db.Set<ReleasePipelineStageAttempt>().AnyAsync(x=>x.RunStageId==run.Stages[2].Id||x.RunStageId==run.Stages[3].Id));}
 [Fact] public async Task ConcurrentProjectionAndControlPlaneRestartDoNotDuplicateTransitions()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var (run,_)=await AcceptSourceAsync(s);await Task.WhenAll(ProjectAsync(s.Api,run.Id),ProjectAsync(s.Api,run.Id));await s.Api.RestartServerAsync();await ProjectAsync(s.Api,run.Id);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleasePipelineEvent>().CountAsync(e=>e.RunId==run.Id&&e.ReasonCode=="stage_passed"));Assert.Equal(2,await db.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));}
 [Theory][InlineData("Paused")][InlineData("TimedOut")]
 public async Task InactiveRunDoesNotActivateFutureStage(string state)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var (run,_)=await AcceptSourceAsync(s);await using(var db=s.Api.Context()){(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status=state;await db.SaveChangesAsync();}await ProjectAsync(s.Api,run.Id);await using var verify=s.Api.Context();Assert.Equal(1,await verify.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));}
 [Theory][InlineData("Requested")][InlineData("Rejected")]
 public async Task AckAndEvidenceWithoutAcceptedProofCannotPass(string status)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var (run,id)=await AcceptSourceAsync(s);await using(var db=s.Api.Context()){var acceptance=await db.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==id);acceptance.Status=status;acceptance.Revision++;await db.SaveChangesAsync();}await ProjectAsync(s.Api,run.Id);await using var verify=s.Api.Context();Assert.NotEqual("Passed",(await verify.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==run.Stages[0].Id)).Status);Assert.Equal(status=="Rejected"?"Paused":"Active",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);}
 [Fact] public async Task RevokedEarlierAcceptanceCancelsQueuedCandidateInTheSameCommand()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);using(var publish=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))publish.EnsureSuccessStatusCode();await using(var db=f.Scenario.Api.Context()){var acceptance=await db.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==f.AcceptanceId);var acceptor=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);using var revoked=await PipelineStageEvidenceTests.ActAsync(acceptor.Client,f.AcceptanceId,"revoke");revoked.EnsureSuccessStatusCode();}await using var verify=f.Scenario.Api.Context();Assert.Equal("Cancelled",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.Equal("Cancelled",(await verify.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal("Invalidated",(await verify.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==f.Run.Id)).Status);}
 [Fact] public async Task RevocationPreservesPublishingConfigurationAndNodeFacts()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);using(var publish=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))publish.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();string hash;await using(var db=f.Scenario.Api.Context()){hash=(await db.Set<GatewayConfigVersion>().SingleAsync(c=>c.EnvironmentId==f.TargetEnvironmentId&&c.VersionNo==2)).SnapshotHash!;var acceptance=await db.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==f.AcceptanceId);acceptance.Status="Revoked";acceptance.Revision++;await db.SaveChangesAsync();}await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();Assert.Equal("Publishing",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.Equal(hash,(await verify.Set<GatewayConfigVersion>().SingleAsync(c=>c.EnvironmentId==f.TargetEnvironmentId&&c.VersionNo==2)).SnapshotHash);Assert.Equal("Invalidated",(await verify.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==f.Run.Id)).Status);}
 [Theory][InlineData(2)][InlineData(4)]
 public async Task SucceededAckWaitsForOwnStageProof(int count)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(count);var p=count==2?await PipelineExecutionTests.ReadyAsync(f):await PipelineExecutionTests.SubmittedAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var db=f.Scenario.Api.Context();Assert.Equal("AwaitingVerification",(await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId)).Status);Assert.Equal("Active",(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status);Assert.False(await db.Set<ReleasePipelineStageAttempt>().AnyAsync(a=>a.RunStageId==f.Run.Stages.Last().Id&&count>2));}
 [Fact] public async Task EarlierPassedEvidenceExpiryOrEnvironmentChangeDoesNotRewriteHistory()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(4);await using(var db=f.Scenario.Api.Context()){(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.Run.SourceEnvironmentId)).DeploymentSequence=999;foreach(var row in await db.Set<ReleaseVerification>().Where(v=>v.PipelineRunStageId==f.Run.Stages[0].Id).ToArrayAsync()){row.StartedAt=DateTimeOffset.UtcNow.AddHours(-2);row.FinishedAt=row.StartedAt;row.ExpiresAt=DateTimeOffset.UtcNow.AddHours(-1);}await db.SaveChangesAsync();}await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();Assert.Equal("Passed",(await verify.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.Run.Stages[0].Id)).Status);Assert.Equal("Active",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status);}
 [Fact] public async Task FailedCurrentSourceTestPausesWithoutStartingNextStage()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));var stage=run.Stages[0];var context=await PipelineStageEvidenceTests.ContextAsync(s.Creator,stage.Id);using var evidence=await ApiFixture.CommandAsync(s.Creator,$"/api/v1/release-pipeline-run-stages/{stage.Id}/verifications",new PipelineStageVerificationRequest(context.ContextHash,new("InterfaceFunction","Failed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow)));evidence.EnsureSuccessStatusCode();await ProjectAsync(s.Api,run.Id);await using var db=s.Api.Context();Assert.Equal("VerificationFailed",(await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==stage.Id)).Status);Assert.Equal("Paused",(await db.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==run.Id)).Status);Assert.Equal(1,await db.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));}
 [Theory][InlineData("Passed", "Completed")][InlineData("Failed", "Paused")]
 public async Task ProductionRequiresThreeCurrentIndependentChecks(string result,string expected)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"PipelineProductionVerifier");var context=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;foreach(var type in new[]{"EntryConnectivity","AuthenticationAuthorization","CriticalBusinessCall"}){using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest(type,type=="CriticalBusinessCall"?result:"Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:context.Hash));Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());if(type!="CriticalBusinessCall"){await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var incomplete=f.Scenario.Api.Context();Assert.Equal("Active",(await incomplete.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==f.Run.Id)).Status);}}await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var db=f.Scenario.Api.Context();Assert.Equal(expected,(await db.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==f.Run.Id)).Status);Assert.Equal(result=="Passed"?"Passed":"VerificationFailed",(await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==f.TargetStageId)).Status);Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync(x=>x.Id==p.TargetReleaseId)).Status);}
 [Fact] public async Task CompletedRunRevocationAddsOneEventWithoutRewritingCompletion()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);DateTimeOffset completed=DateTimeOffset.UtcNow;await using(var db=f.Scenario.Api.Context()){var run=await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id);run.Status="Completed";run.CompletedAt=completed;await db.SaveChangesAsync();}var acceptor=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);using(var revoke=await PipelineStageEvidenceTests.ActAsync(acceptor.Client,f.AcceptanceId,"revoke"))revoke.EnsureSuccessStatusCode();await ProjectAsync(f.Scenario.Api,f.Run.Id);await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();var actual=await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id);Assert.Equal("Completed",actual.Status);Assert.Equal(completed.ToUnixTimeMilliseconds(),actual.CompletedAt!.Value.ToUnixTimeMilliseconds());Assert.Equal(1,await verify.Set<ReleasePipelineEvent>().CountAsync(e=>e.RunId==f.Run.Id&&e.ReasonCode=="pipeline_acceptance_revoked"));}
 [Fact] public async Task NewWorkerHostsRecoverStageProjectionFromPersistedFacts()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var (run,_)=await AcceptSourceAsync(s);for(var i=0;i<2;i++){using var host=WorkerApp.Build(["--environment","Development"],b=>{b.Configuration["ConnectionStrings:WebApi"]=s.Api.Database.ConnectionString;b.Configuration["Redis:Prefix"]="pipeline-worker-test:"+Guid.NewGuid();b.Logging.ClearProviders();});await host.StartAsync();try{var until=DateTimeOffset.UtcNow.AddSeconds(12);while(true){await using var db=s.Api.Context();if((await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).CurrentStageOrder==2)break;Assert.True(DateTimeOffset.UtcNow<until,"Worker did not recover persistent stage facts");await Task.Delay(100);}}finally{await host.StopAsync();}}await using var verify=s.Api.Context();Assert.Equal(2,await verify.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));Assert.Equal(1,await verify.Set<ReleasePipelineEvent>().CountAsync(e=>e.RunId==run.Id&&e.ReasonCode=="stage_passed"));}
 [Theory][InlineData(0)][InlineData(101)]
 public async Task ScanRejectsUnboundedBatchSizes(int size)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();using var services=s.Api.Services();await Assert.ThrowsAsync<ArgumentOutOfRangeException>(()=>services.ServiceProvider.GetRequiredService<PipelineProjectionService>().ScanAsync(size));}

 [Fact] public async Task ScanDurablyClaimsDueRunWithoutWritingPollEvents()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));using var first=s.Api.Services();using var second=s.Api.Services();Assert.Equal(1,await first.ServiceProvider.GetRequiredService<PipelineProjectionService>().ScanAsync());Assert.Equal(0,await second.ServiceProvider.GetRequiredService<PipelineProjectionService>().ScanAsync());await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleasePipelineEvent>().CountAsync(e=>e.RunId==run.Id));}

 [Fact] public async Task QualifiedDelegateFailureDoesNotDependOnRunCreatorCurrentReadRights()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));var stage=run.Stages[0];var tester=await PipelineStageEvidenceTests.DelegateAsync(s);var context=await PipelineStageEvidenceTests.ContextAsync(tester.Client,stage.Id);using var response=await ApiFixture.CommandAsync(tester.Client,$"/api/v1/release-pipeline-run-stages/{stage.Id}/verifications",new PipelineStageVerificationRequest(context.ContextHash,new("InterfaceFunction","Failed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow)));response.EnsureSuccessStatusCode();await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==s.Api.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="release.read");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}await ProjectAsync(s.Api,run.Id);await using var verify=s.Api.Context();Assert.Equal("Paused",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);}
 [Fact] public async Task FailedDeploymentPausesAndPreservesItsSequence()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);using(var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))response.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();long? sequence;await using(var db=f.Scenario.Api.Context()){var release=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);sequence=release.DeploymentSequence;release.Status="Failed";release.FailureCode="ack_timeout";release.CompletedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();}await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();Assert.Equal("Paused",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status);Assert.Equal("DeploymentFailed",(await verify.Set<ReleasePipelineRunStage>().SingleAsync(r=>r.Id==f.TargetStageId)).Status);Assert.Equal(sequence,(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).DeploymentSequence);}

 [Fact] public async Task ProductionCannotPassWithVerifierRevokedBeforeStageProjection()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"PipelineCurrentVerifier");var context=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;foreach(var type in new[]{"EntryConnectivity","AuthenticationAuthorization","CriticalBusinessCall"}){using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest(type,"Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:context.Hash));response.EnsureSuccessStatusCode();}await using(var db=f.Scenario.Api.Context()){Assert.Equal("Completed",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);var role=await db.Set<UserRole>().Where(r=>r.UserId==verifier.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(x=>x.Code=="release.verify");await db.Set<RolePermission>().Where(x=>x.RoleId==role&&x.PermissionId==permission.Id).ExecuteDeleteAsync();}await ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();Assert.Equal("Active",(await verify.Set<ReleasePipelineRun>().SingleAsync(x=>x.Id==f.Run.Id)).Status);Assert.Equal("AwaitingVerification",(await verify.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==f.TargetStageId)).Status);Assert.Equal("Completed",(await verify.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);}

 [Fact] public async Task MiddleStageMaterializesOwnRootBehaviorAndPassesIndependentAcceptance()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(4);var p=await PipelineExecutionTests.SubmittedAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var acceptor=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await f.Scenario.PassCurrentAsync(f.Run.Id,f.Scenario.Creator,acceptor.Client);await using var db=f.Scenario.Api.Context();var stage=await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId);Assert.Equal("Passed",stage.Status);Assert.NotEqual(f.Scenario.RootArtifactId,stage.StageArtifactId);var own=await db.Set<ReleaseArtifact>().SingleAsync(a=>a.Id==stage.StageArtifactId);Assert.Equal(f.TargetEnvironmentId,own.SourceEnvironmentId);Assert.Equal(f.Run.RootArtifactHash,own.ArtifactHash);Assert.Equal(3,(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).CurrentStageOrder);Assert.Equal(3,await db.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==f.Run.Id));Assert.Null((await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.Run.Stages[3].Id)).CurrentAttemptId);}

 [Fact] public async Task ChangedActualClassificationCannotPassFrozenNonProductionProfile()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var (run,_)=await AcceptSourceAsync(s);await using(var db=s.Api.Context()){(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==run.SourceEnvironmentId)).IsProduction=true;await db.SaveChangesAsync();}await ProjectAsync(s.Api,run.Id);await using var verify=s.Api.Context();Assert.Equal(1,(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).CurrentStageOrder);Assert.Equal("AwaitingAcceptance",(await verify.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==run.Stages[0].Id)).Status);Assert.Equal(1,await verify.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));}

}
