using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Contracts.Common;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineRunTests
{
 internal static async Task<Guid> ActivateVersionAsync(PipelineScenario s)
 {var version=await PipelineActivationTests.VersionAsync(s);await PipelineActivationTests.SeedBaselineAsync(s);using var activated=await PipelineActivationTests.ActivateAsync(s,version);Assert.Equal(HttpStatusCode.OK,activated.StatusCode);return version;}
 [Theory][InlineData("Completed",false,false,true)][InlineData("Cancelled",false,false,true)][InlineData("Invalidated",false,false,true)][InlineData("Completed",true,false,false)][InlineData("Cancelled",false,true,false)]
 public async Task TerminalPipelinePromotionHistoryDoesNotOccupyIndependentDeliveryQueue(string terminal,bool independent,bool publishing,bool canStart)
 {
  // Persisted lifecycle fixture; actual multi-Gateway acceptance is recorded separately in P13.
  await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var version=await ActivateVersionAsync(s);var run=await s.StartAsync(version);
  await using(var db=s.Api.Context()){
   var old=await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id);old.Status=terminal;old.CompletedAt=DateTimeOffset.UtcNow;
   var stage=await db.Set<ReleasePipelineRunStage>().SingleAsync(r=>r.Id==run.Stages[1].Id);stage.Status=terminal=="Completed"?"Passed":terminal;
   var attempt=new ReleasePipelineStageAttempt{RunId=run.Id,ProjectId=run.ProjectId,RunStageId=stage.Id,EnvironmentId=stage.EnvironmentId,AttemptNo=1,ActivatedAt=DateTimeOffset.UtcNow,DeadlineAt=DateTimeOffset.UtcNow.AddHours(1),Status=terminal=="Completed"?"Passed":terminal};db.Add(attempt);await db.SaveChangesAsync();
   var p=new ReleasePromotion{OrganizationId=s.Api.Organization.Id,ProjectId=run.ProjectId,ArtifactId=s.RootArtifactId,SourceEnvironmentId=run.SourceEnvironmentId!.Value,TargetEnvironmentId=stage.EnvironmentId,SourceReleaseId=s.Source.ReleaseId,RequestedBy=s.Api.User.Id,Status="Verifying",GateOrigin=independent?"ProjectConnection":"PipelineRunStage",PipelineRunStageId=independent?null:stage.Id,StageAttemptId=independent?null:attempt.Id};db.Add(p);await db.SaveChangesAsync();
   if(publishing){db.Add(new ReleaseRecord{EnvironmentId=stage.EnvironmentId,ReleaseNo="terminal-history-publishing-guard",ReleaseType="publish",Status="Publishing",RequestedBy=s.Api.User.Id,ToConfigVersion=1,DeploymentSequence=2});await db.SaveChangesAsync();}
  }
  using var next=await s.TryStartAsync(version);Assert.Equal(canStart?HttpStatusCode.OK:HttpStatusCode.Conflict,next.StatusCode);
  await using var verify=s.Api.Context();Assert.Equal("Verifying",(await verify.Set<ReleasePromotion>().SingleAsync()).Status);Assert.Equal(terminal,(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);
 }
 [Theory][InlineData(2)][InlineData(4)] public async Task StartImportsCurrentSourceWithoutAnotherRelease(int count)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(count);var version=await ActivateVersionAsync(s);await using var db=s.Api.Context();var before=await db.Set<ReleaseRecord>().CountAsync();var run=await s.StartAsync(version);Assert.Equal(before,await db.Set<ReleaseRecord>().CountAsync());Assert.Equal(s.RootArtifactId,run.RootArtifactId);Assert.Equal(s.Source.Artifact.ArtifactHash,run.RootArtifactHash);Assert.Equal("Active",run.Status);Assert.Equal(count,run.Stages.Count);Assert.Equal("AwaitingEvidence",run.Stages[0].Status);Assert.Equal(s.RootArtifactId,run.Stages[0].StageArtifactId);Assert.NotNull(run.Stages[0].CurrentAttemptId);Assert.InRange((run.Stages[0].DeadlineAt!-run.Stages[0].ActivatedAt!).Value.TotalMinutes,1439.99,1440.01);Assert.All(run.Stages.Skip(1),stage=>{Assert.Equal("Pending",stage.Status);Assert.Null(stage.CurrentAttemptId);Assert.Null(stage.DeadlineAt);Assert.Null(stage.StageArtifactId);});for(var i=1;i<count;i++){Assert.Equal(run.Stages[i-1].Id,run.Stages[i].SourceStageId);Assert.Equal(run.Id,run.Stages[i].RunId);}Assert.Equal(1,await db.Set<ReleasePipelineStageAttempt>().CountAsync());Assert.Equal(run.Stages[0].Id,(await s.CurrentStageAsync(run.Id)).Id);}
 [Fact] public async Task SameKeyReplaysAndDifferentBodyConflicts()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await ActivateVersionAsync(s);var key=Guid.NewGuid().ToString("N");var run=await s.StartAsync(version,key);var replay=await s.StartAsync(version,key);Assert.Equal(run.Id,replay.Id);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleasePipelineRun>().CountAsync());var pipeline=(await db.Set<ReleasePipelineVersion>().SingleAsync(v=>v.Id==version)).PipelineId;var newer=await PipelineDefinitionTests.PublishAsync(s,pipeline,2);using var conflict=await s.TryStartAsync(newer.GetProperty("id").GetGuid(),key);Assert.Equal(HttpStatusCode.Conflict,conflict.StatusCode);}
 [Fact] public async Task DifferentKeysCannotStartTwoConcurrentRuns()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await ActivateVersionAsync(s);var responses=await Task.WhenAll(s.TryStartAsync(version),s.TryStartAsync(version));try{Assert.Single(responses,r=>r.IsSuccessStatusCode);Assert.Single(responses,r=>r.StatusCode==HttpStatusCode.Conflict);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleasePipelineRun>().CountAsync());}finally{foreach(var response in responses)response.Dispose();}}
 [Theory][InlineData("outdated")][InlineData("failed")][InlineData("partial_ack")][InlineData("artifact_hash")]
 public async Task InvalidRootActualFactsCannotStart(string change)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await ActivateVersionAsync(s);await using(var db=s.Api.Context()){if(change=="outdated")(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.Environments[0])).DeploymentSequence++;if(change=="failed")(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==s.Source.ReleaseId)).Status="Failed";if(change=="partial_ack")await db.Set<GatewayAck>().Where(a=>a.ReleaseId==s.Source.ReleaseId).Take(1).ExecuteDeleteAsync();if(change=="artifact_hash")(await db.Set<ReleaseArtifact>().SingleAsync(a=>a.Id==s.RootArtifactId)).ArtifactHash=new string('f',64);await db.SaveChangesAsync();}using var rejected=await s.TryStartAsync(version);Assert.Contains(rejected.StatusCode,new[]{HttpStatusCode.Conflict,HttpStatusCode.UnprocessableEntity});await using var context=s.Api.Context();Assert.False(await context.Set<ReleasePipelineRun>().AnyAsync());}
 [Theory][InlineData("pipeline.run")][InlineData("release.create")][InlineData("api.schema.read")][InlineData("target_scope")]
 public async Task StartRequiresRootVisibilitySourceCreateAndAllChainReads(string missing)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var version=await ActivateVersionAsync(s);await using(var db=s.Api.Context()){if(missing=="target_scope"){await db.Set<UserProjectScope>().Where(g=>g.UserId==s.Api.User.Id).ExecuteDeleteAsync();db.Add(new UserProjectScope{UserId=s.Api.User.Id,OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,EnvironmentId=s.Environments[0],AccessMode="read_write"});await db.SaveChangesAsync();}else{var permission=await db.Set<Permission>().SingleAsync(p=>p.Code==missing);await db.Set<RolePermission>().Where(g=>g.PermissionId==permission.Id).ExecuteDeleteAsync();}}using var denied=await s.TryStartAsync(version);if(missing=="api.schema.read"){Assert.Equal(HttpStatusCode.NotFound,denied.StatusCode);Assert.Contains("resource_not_found",await denied.Content.ReadAsStringAsync());}else Assert.Equal(HttpStatusCode.Forbidden,denied.StatusCode);}
 [Fact] public async Task CancelledRunWithPublishingStillBlocksNewRunAndActivation()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await ActivateVersionAsync(s);var run=await s.StartAsync(version);await using(var db=s.Api.Context()){var row=await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id);row.Status="Cancelled";row.CompletedAt=DateTimeOffset.UtcNow;db.Add(new ReleaseRecord{EnvironmentId=s.Environments[1],ReleaseNo="cancelled-run-publishing-fault-fixture",ReleaseType="publish",Status="Publishing",RequestedBy=s.Api.User.Id,ToConfigVersion=1,DeploymentSequence=2});await db.SaveChangesAsync();}using var start=await s.TryStartAsync(version);Assert.Equal(HttpStatusCode.Conflict,start.StatusCode);using var activate=await PipelineActivationTests.ActivateAsync(s,version);Assert.Equal(HttpStatusCode.Conflict,activate.StatusCode);}
 [Fact] public async Task UnactivatedVersionCannotStart()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var version=await PipelineActivationTests.VersionAsync(s);using var rejected=await s.TryStartAsync(version);Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);}
 [Fact] public async Task RootCannotComeFromAnotherChainEnvironment()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var version=await ActivateVersionAsync(s);Guid artifactId;await using(var db=s.Api.Context()){var release=new ReleaseRecord{EnvironmentId=s.Environments[1],ReleaseNo="wrong-root-env-fixture",Status="Succeeded",RequestedBy=s.Api.User.Id};var artifact=new ReleaseArtifact{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,SourceEnvironmentId=s.Environments[1],SourceReleaseId=release.Id,CanonicalContent=System.Text.Encoding.UTF8.GetString(WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Serialize(s.Source.Artifact.Content)),ArtifactHash=s.Source.Artifact.ArtifactHash,SourceSnapshotHash=s.Source.Artifact.SourceSnapshotHash,CreatedBy=s.Api.User.Id};db.AddRange(release,artifact);await db.SaveChangesAsync();artifactId=artifact.Id;}using var rejected=await ApiFixture.CommandAsync(s.Creator,"/api/v1/release-pipeline-runs",new CreatePipelineRunRequest(version,artifactId));Assert.Equal(HttpStatusCode.UnprocessableEntity,rejected.StatusCode);}
 [Theory][InlineData("Passed")][InlineData("Deploying")][InlineData("VerificationFailed")]
 public async Task ClosedCurrentStageCannotBecomeWritable(string status)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var seed=await PipelineGateContextTests.SeedPipelineFactsAsync(s);await using var db=s.Api.Context();var stage=await db.Set<ReleasePipelineRunStage>().SingleAsync(x=>x.Id==seed.StageId);stage.Status=status;await db.SaveChangesAsync();using var services=s.Api.Services();var resolver=PipelineGateContextTests.Resolver(db,services.ServiceProvider);var actor=new WebApi.Contracts.Security.ActorContext(s.Api.User.Id,"state-test");var context=await resolver.ResolveStageAsync(seed.StageId,actor,default);Assert.Equal(409,(await Assert.ThrowsAsync<ApiException>(()=>resolver.RequireStageWritableAsync(context,actor,default))).Status);}
}
