using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Common;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineExecutionTests
{
 internal static async Task<(UserRecord User,HttpClient Client)> ActorAsync(PipelinePromotionFixture f)
 {var user=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await f.Scenario.GrantAsync(user.User.Id,"release.publish","release.rollback","release.verify","route.write","cluster.read","app.read","policy.write");return user;}
 internal static async Task<(UserRecord User,HttpClient Client)> ApproverAsync(PipelinePromotionFixture f,string role)
 {var user=await f.Scenario.Api.NewReviewerAsync(role);await f.Scenario.GrantAsync(user.User.Id,"environment.read","release.read","route.read","api.read","api.version.read","api.schema.read","policy.read","cluster.read","app.read","release.verify");return user;}
 internal static async Task<PromotionDto> SubmittedAsync(PipelinePromotionFixture f,HttpClient? requester=null)
 {using var prepared=await f.PrepareAsync(client:requester);Assert.True(prepared.IsSuccessStatusCode,await prepared.Content.ReadAsStringAsync());var p=(await prepared.Content.ReadFromJsonAsync<PromotionDto>())!;var precheck=await f.PrecheckAsync(p);Assert.True(precheck.CanSubmit,JsonSerializer.Serialize(precheck));var client=requester??f.Scenario.Creator;using var request=new HttpRequestMessage(HttpMethod.Post,$"/api/v1/release-promotions/{p.Id}/submit"){Content=JsonContent.Create(new{})};request.Headers.Add("If-Match",RevisionTag.Format(precheck.Revision));request.Headers.Add("X-CSRF-Token",(await client.GetFromJsonAsync<Dictionary<string,string>>("/api/v1/auth/csrf"))!["token"]);request.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString("N"));using var response=await client.SendAsync(request);Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());return (await response.Content.ReadFromJsonAsync<PromotionDto>())!;}
 internal static async Task<PromotionDto> ReadyAsync(PipelinePromotionFixture f,HttpClient? requester=null)
 {var p=await SubmittedAsync(f,requester);foreach(var role in new[]{"ApiApprover","SecurityReviewer"}){var reviewer=await ApproverAsync(f,role);using var approval=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="独立阶段审批"});Assert.True(approval.IsSuccessStatusCode,await approval.Content.ReadAsStringAsync());}return p;}
 internal static async Task SeedSucceededAfterRealBuildAsync(PipelinePromotionFixture f,PromotionDto p,HttpClient? publisher=null)
 {await f.Scenario.DeployCurrentAsync(f.Run.Id,publisher??f.Scenario.Creator);}

 [Fact] public async Task PipelineRequiredRejectsOrdinaryProductionCreateAndForgedAssociation()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await f.PreparedAsync();await f.PrecheckAsync(p);var request=await f.Scenario.Api.PreviewReleaseRequestAsync(1,f.Scenario.Api.Version.Id,f.TargetEnvironmentId);using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/environments/{f.TargetEnvironmentId}/releases",new{request.BaseConfigVersion,request.VersionIds,request.ResourceRevisions,promotionId=p.Id,pipelineRunStageId=f.TargetStageId});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var db=f.Scenario.Api.Context();Assert.False(await db.Set<ReleaseRecord>().AnyAsync(r=>r.EnvironmentId==f.TargetEnvironmentId&&r.Status=="Draft"));}
 [Fact] public async Task OldOrdinaryDraftCannotSubmitThroughTheReleaseEndpoint()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await f.PreparedAsync();await f.PrecheckAsync(p);var request=await f.Scenario.Api.PreviewReleaseRequestAsync(1,f.Scenario.Api.Version.Id,f.TargetEnvironmentId);Guid id;await using(var db=f.Scenario.Api.Context()){var stale=new ReleaseRecord{EnvironmentId=f.TargetEnvironmentId,ReleaseNo="old-independent-draft-fixture",ReleaseType="publish",Status="Draft",RequestedBy=f.Scenario.Api.User.Id,BaselineConfigVersion=1,FromConfigVersion=1,CandidateBytes=CanonicalJson.Serialize(request)};id=stale.Id;db.Add(stale);await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{id}/submit");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Theory][InlineData("paused")][InlineData("future")][InlineData("template")][InlineData("binding")]
 public async Task ReadyCannotPublishWhenStageOrFrozenApprovalChanged(string fault)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await ReadyAsync(f);await using(var db=f.Scenario.Api.Context()){if(fault=="paused")(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Paused";if(fault=="future")(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).CurrentStageOrder=1;if(fault=="template")(await db.Set<ApprovalFlow>().SingleAsync()).Revision++;if(fault=="binding")(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.RunStageId==f.TargetStageId)).ActualReleaseId=null;await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var verify=f.Scenario.Api.Context();Assert.Equal("Ready",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.Equal(1L,(await verify.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.TargetEnvironmentId)).DeploymentSequence);}
 [Fact] public async Task PassedPredecessorCannotBeReplacedByAnUnpassedProjection()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await ReadyAsync(f);await using(var db=f.Scenario.Api.Context()){(await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.Run.Stages[0].Id)).Status="AwaitingAcceptance";await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Fact] public async Task QueuedBuildMayProceedInDeployingProjectionButHumanCommandsCannot()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await ReadyAsync(f);using(var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))response.EnsureSuccessStatusCode();await using(var db=f.Scenario.Api.Context()){(await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId)).Status="Deploying";await db.SaveChangesAsync();}using(var prepare=await f.PrepareAsync())Assert.Equal(HttpStatusCode.Conflict,prepare.StatusCode);await f.Scenario.Source.Deployment.BuildQueuedAsync();await using var verify=f.Scenario.Api.Context();Assert.Equal("Publishing",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);}
 [Theory][InlineData("paused")][InlineData("template")][InlineData("pipeline_permission")]
 public async Task WorkerRechecksQueuedStageWithoutEmittingAnotherConfiguration(string fault)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await ReadyAsync(f);using(var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))response.EnsureSuccessStatusCode();await using(var db=f.Scenario.Api.Context()){if(fault=="paused")(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Paused";if(fault=="template")(await db.Set<ApprovalFlow>().SingleAsync()).Revision++;if(fault=="pipeline_permission"){var role=await db.Set<UserRole>().Where(r=>r.UserId==f.Scenario.Api.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="pipeline.run");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}await db.SaveChangesAsync();}await f.Scenario.Source.Deployment.BuildQueuedAsync();await using var verify=f.Scenario.Api.Context();Assert.Equal("Failed",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.Equal(1L,(await verify.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.TargetEnvironmentId)).DesiredConfigVersion);Assert.Equal(1,await verify.Set<GatewayConfigVersion>().CountAsync(c=>c.EnvironmentId==f.TargetEnvironmentId));Assert.False(await verify.Set<OutboxMessage>().AnyAsync(m=>m.ReleaseId==p.TargetReleaseId));}
 [Fact] public async Task DelegatedRequesterCanPublishWithSourceReadAndTargetWriteOnly()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var requester=await ActorAsync(f);await using(var db=f.Scenario.Api.Context()){await db.Set<UserProjectScope>().Where(s=>s.UserId==requester.User.Id).ExecuteDeleteAsync();db.Add(new UserProjectScope{UserId=requester.User.Id,OrganizationId=f.Scenario.Api.Organization.Id,ProjectId=f.Run.ProjectId,EnvironmentId=f.Run.Stages[0].EnvironmentId,AccessMode="read_only"});db.Add(new UserProjectScope{UserId=requester.User.Id,OrganizationId=f.Scenario.Api.Organization.Id,ProjectId=f.Run.ProjectId,EnvironmentId=f.TargetEnvironmentId,AccessMode="read_write"});await db.SaveChangesAsync();}var p=await ReadyAsync(f,requester.Client);using var response=await ApiFixture.CommandAsync(requester.Client,$"/api/v1/releases/{p.TargetReleaseId}/publish");Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());await f.Scenario.Source.Deployment.BuildQueuedAsync();await using var verify=f.Scenario.Api.Context();Assert.Equal("Publishing",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);}
 [Fact] public async Task ExactSnapshotRetrySurvivesSourceReplacementAndTerminalRun()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await ReadyAsync(f);using(var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))response.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();byte[] candidate;string hash;await using(var db=f.Scenario.Api.Context()){var release=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);candidate=release.CandidateBytes!;release.Status="Failed";release.FailureCode="activation_timeout";release.CompletedAt=DateTimeOffset.UtcNow;hash=(await db.Set<GatewayConfigVersion>().SingleAsync(c=>c.EnvironmentId==f.TargetEnvironmentId&&c.VersionNo==release.ToConfigVersion)).SnapshotHash!;(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.Run.Stages[0].EnvironmentId)).DeploymentSequence=99;(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Cancelled";await db.SaveChangesAsync();}using var retry=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/retry");Assert.True(retry.IsSuccessStatusCode,await retry.Content.ReadAsStringAsync());var recovery=(await retry.Content.ReadFromJsonAsync<ReleaseDto>())!;await f.Scenario.Source.Deployment.BuildQueuedAsync();await using var verify=f.Scenario.Api.Context();var record=await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==recovery.Id);Assert.Equal("Publishing",record.Status);Assert.Equal(candidate,record.CandidateBytes);Assert.Equal(3L,record.DeploymentSequence);Assert.Equal(hash,(await verify.Set<GatewayConfigVersion>().SingleAsync(c=>c.EnvironmentId==f.TargetEnvironmentId&&c.VersionNo==record.ToConfigVersion)).SnapshotHash);Assert.Equal(1,await verify.Set<ReleaseRecord>().CountAsync(r=>r.PromotionId==p.Id));using var advance=await f.PrepareAsync();Assert.Equal(HttpStatusCode.Conflict,advance.StatusCode);}
}
