using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PipelineApprovalTests
{
 [Fact] public async Task ProductionAuditBindsEvidenceAfterIntermediateSaves()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"StageVerifier");var context=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,Comment:"不要把这个人工说明写入审计",ExpectedContextHash:context.Hash));Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());await using var db=f.Scenario.Api.Context();var fact=await db.Set<ReleaseVerification>().SingleAsync(v=>v.PromotionId==p.Id);var audit=await db.Set<AuditLog>().SingleOrDefaultAsync(a=>a.Action=="pipeline.stage.production-evidence");Assert.NotNull(audit);using var json=JsonDocument.Parse(audit!.AfterJson!);Assert.Equal(f.TargetStageId,json.RootElement.GetProperty("stageId").GetGuid());Assert.Equal(fact.StageAttemptId,json.RootElement.GetProperty("attemptId").GetGuid());Assert.Equal(fact.ProfileHash,json.RootElement.GetProperty("profileHash").GetString());Assert.Equal(fact.Id,json.RootElement.GetProperty("verificationId").GetGuid());Assert.DoesNotContain("不要把这个人工说明",audit.AfterJson);Assert.DoesNotContain("gateway-2.example",audit.AfterJson);Assert.DoesNotContain("AccessContextJson",audit.AfterJson);Assert.Equal(1,await db.Set<ReleasePipelineEvent>().CountAsync(e=>e.StageId==f.TargetStageId&&e.AttemptId==fact.StageAttemptId&&e.RelatedId==fact.Id));}
 [Fact] public async Task PausedRunBlocksOldRejectionEndpointToo()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.SubmittedAsync(f);var reviewer=await PipelineExecutionTests.ApproverAsync(f,"ApiApprover");await using(var db=f.Scenario.Api.Context()){(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Paused";await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/reject",new{comment="暂停期间也不能处理新的审批决策"});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Theory][InlineData("ApiApprover")][InlineData("PlatformAdmin")]
 public async Task DelegatedRequesterCannotHideRunCreatorForApproval(string role)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var requester=await PipelineExecutionTests.ActorAsync(f);var p=await PipelineExecutionTests.SubmittedAsync(f,requester.Client);await using(var db=f.Scenario.Api.Context()){var actualRole=await db.Set<Role>().SingleAsync(r=>r.Code==role&&(role=="PlatformAdmin"?r.OrganizationId==null:r.OrganizationId==f.Scenario.Api.Organization.Id));db.Add(new UserRole{UserId=f.Scenario.Api.User.Id,RoleId=actualRole.Id});await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="运行创建人不能通过委托自批"});Assert.Equal(HttpStatusCode.Forbidden,response.StatusCode);Assert.Contains("pipeline_run_creator_approval",await response.Content.ReadAsStringAsync());await using var verify=f.Scenario.Api.Context();Assert.False(await verify.Set<ApprovalTask>().AnyAsync(t=>t.ReleaseId==p.TargetReleaseId&&t.Status=="Approved"));}
 [Theory][InlineData("paused")][InlineData("template")]
 public async Task ExistingApprovalEndpointStillRechecksCurrentPipeline(string fault)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.SubmittedAsync(f);var reviewer=await PipelineExecutionTests.ApproverAsync(f,"ApiApprover");await using(var db=f.Scenario.Api.Context()){if(fault=="paused")(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Paused";else(await db.Set<ApprovalFlow>().SingleAsync()).Revision++;await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="阶段当前门禁"});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Fact] public async Task OriginalApproverNeedsNoPipelineRunPermissionAndCannotUseTwoSeats()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.SubmittedAsync(f);var reviewer=await PipelineExecutionTests.ApproverAsync(f,"ApiApprover");using(var response=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="保留原审批权限"}))Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());await using(var db=f.Scenario.Api.Context()){var role=await db.Set<Role>().SingleAsync(r=>r.Code=="SecurityReviewer"&&r.OrganizationId==f.Scenario.Api.Organization.Id);db.Add(new UserRole{UserId=reviewer.User.Id,RoleId=role.Id});await db.SaveChangesAsync();}using var second=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="第二级仍须不同人员"});Assert.Equal(HttpStatusCode.Forbidden,second.StatusCode);Assert.Contains("independent_approval_required",await second.Content.ReadAsStringAsync());}
 [Fact] public async Task RunCreatorCannotVerifyDelegatesActualProductionPublish()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var requester=await PipelineExecutionTests.ActorAsync(f);var publisher=await PipelineExecutionTests.ActorAsync(f);var p=await PipelineExecutionTests.ReadyAsync(f,requester.Client);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p,publisher.Client);using var get=await f.Scenario.Creator.GetAsync($"/api/v1/release-promotions/{p.Id}/verification-context");Assert.Equal(HttpStatusCode.OK,get.StatusCode);var context=(await get.Content.ReadFromJsonAsync<ProductionVerificationContextDto>())!;using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:context.Hash));Assert.Equal(HttpStatusCode.Forbidden,response.StatusCode);Assert.Contains("independent_production_verifier_required",await response.Content.ReadAsStringAsync());}
 [Fact] public async Task NonProductionStageCannotUseProductionEvidenceEndpoint()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();var p=await PipelineExecutionTests.SubmittedAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);using var context=await f.Scenario.Creator.GetAsync($"/api/v1/release-promotions/{p.Id}/verification-context");Assert.Equal(HttpStatusCode.UnprocessableEntity,context.StatusCode);}
 [Fact] public async Task PausedRunCannotAppendNewProductionEvidence()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"StageVerifier");var context=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;await using(var db=f.Scenario.Api.Context()){(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status="Paused";await db.SaveChangesAsync();}using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:context.Hash));Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Fact] public async Task ProductionContextAndEvidenceBindCurrentAttemptAndFrozenProfile()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"StageVerifier");using var get=await verifier.Client.GetAsync($"/api/v1/release-promotions/{p.Id}/verification-context");Assert.Equal(HttpStatusCode.OK,get.StatusCode);var json=(await get.Content.ReadFromJsonAsync<JsonElement>());Assert.True(json.TryGetProperty("stageAttemptId",out var attempt));Assert.True(json.TryGetProperty("profileHash",out var profile));await using var db=f.Scenario.Api.Context();var stage=await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId);Assert.Equal(stage.CurrentAttemptId,attempt.GetGuid());Assert.Equal(stage.ProfileHash,profile.GetString());var hash=json.GetProperty("hash").GetString()!;using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:hash));Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());var fact=await db.Set<ReleaseVerification>().SingleAsync(v=>v.PromotionId==p.Id);Assert.Equal(stage.Id,fact.PipelineRunStageId);Assert.Equal(stage.CurrentAttemptId,fact.StageAttemptId);Assert.Equal(stage.ProfileHash,fact.ProfileHash);}
 [Fact] public async Task ReopenedAttemptCannotReuseOldProductionContextOrEarlyEvidence()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);await PipelineExecutionTests.SeedSucceededAfterRealBuildAsync(f,p);var verifier=await PipelineExecutionTests.ApproverAsync(f,"StageVerifier");var old=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;DateTimeOffset activated;await using(var db=f.Scenario.Api.Context()){var stage=await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId);var prior=await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==stage.CurrentAttemptId);prior.Status="TimedOut";await db.SaveChangesAsync();var next=new ReleasePipelineStageAttempt{RunStageId=stage.Id,RunId=stage.RunId,ProjectId=stage.ProjectId,EnvironmentId=stage.EnvironmentId,AttemptNo=2,OriginAttemptId=prior.Id,ActualReleaseId=prior.ActualReleaseId,DeadlineAt=DateTimeOffset.UtcNow.AddDays(1)};activated=next.ActivatedAt;db.Add(next);await db.SaveChangesAsync();stage.CurrentAttemptId=next.Id;await db.SaveChangesAsync();}var current=(await verifier.Client.GetFromJsonAsync<ProductionVerificationContextDto>($"/api/v1/release-promotions/{p.Id}/verification-context"))!;Assert.NotEqual(old.Hash,current.Hash);using var stale=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,ExpectedContextHash:old.Hash));Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);using var early=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{p.Id}/verifications",new RecordVerificationRequest("EntryConnectivity","Passed",activated.AddMilliseconds(-1),activated.AddMilliseconds(-1),ExpectedContextHash:current.Hash));Assert.Equal(HttpStatusCode.UnprocessableEntity,early.StatusCode);}
}
