using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Contracts.Common;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
internal sealed class PipelinePromotionFixture : IAsyncDisposable
{
 public PipelineScenario Scenario {get;}=new();
 public PipelineRunDto Run=null!;
 public Guid TargetStageId=>Run.Stages[1].Id;
 public Guid TargetEnvironmentId=>Run.Stages[1].EnvironmentId;
 public Guid ClusterId,ApplicationId,CredentialId,AuthorizationId,TargetPolicyId,AcceptanceId;
 public async Task InitializeAsync(int count=4,bool approval=false,bool jwt=false)
 {
  await Scenario.InitializeEnvironmentsAsync(count,approval,beforePublish:jwt?async api=>{
   await using var db=api.Context();var route=await db.Set<ApiRoute>().SingleAsync();var policy=new Policy{OrganizationId=api.Organization.Id,ProjectId=api.Project.Id,Name="Pipeline JWT",Type="authentication",Config=JwtApplicationBindingTests.Jwt(api.Application.Id)};db.Add(policy);db.Add(new RoutePolicyBinding{RouteId=route.Id,PolicyId=policy.Id,Priority=0});foreach(var node in await db.Set<GatewayNode>().ToArrayAsync())node.Metadata=WebApi.Infrastructure.Gateway.SnapshotSchemaCapabilities.Merge(null,Guid.Parse(node.InstanceId),["2.0","2.1","2.2"]);await db.SaveChangesAsync();}:null);
  Run=await Scenario.StartAsync(await PipelineStageEvidenceTests.VersionAsync(Scenario));
  var source=Run.Stages[0];var context=await PipelineStageEvidenceTests.ContextAsync(Scenario.Creator,source.Id);var ids=await PipelineStageEvidenceTests.EvidenceAsync(Scenario.Creator,source.Id,context);
  using(var response=await ApiFixture.CommandAsync(Scenario.Creator,$"/api/v1/release-pipeline-run-stages/{source.Id}/acceptance-requests",new PipelineAcceptanceRequest(context.ContextHash,ids))){response.EnsureSuccessStatusCode();AcceptanceId=(await response.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Id;}
  var acceptor=await PipelineStageEvidenceTests.DelegateAsync(Scenario);using(var response=await PipelineStageEvidenceTests.ActAsync(acceptor.Client,AcceptanceId,"accept"))response.EnsureSuccessStatusCode();
  // Explicit persisted projection fixture while P8 is not implemented. Synthetic ACKs are not live Gateway proof.
  await using(var db=Scenario.Api.Context()){
   var first=await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==source.Id);first.Status="Passed";(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==first.CurrentAttemptId)).Status="Passed";
   (await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==Run.Id)).CurrentStageOrder=2;var target=await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==TargetStageId);target.Status="AwaitingMapping";
   var attempt=new ReleasePipelineStageAttempt{RunId=Run.Id,RunStageId=target.Id,ProjectId=Run.ProjectId,EnvironmentId=target.EnvironmentId,AttemptNo=1,DeadlineAt=DateTimeOffset.UtcNow.AddDays(1)};db.Add(attempt);await db.SaveChangesAsync();target.CurrentAttemptId=attempt.Id;
   var cluster=new UpstreamCluster{ProjectId=Run.ProjectId,EnvironmentId=target.EnvironmentId,Name="Target backend",LoadBalancingPolicy="RoundRobin",HealthCheckPath="/health",HealthCheckIntervalSec=30};ClusterId=cluster.Id;db.Add(cluster);db.Add(new UpstreamDestination{ClusterId=cluster.Id,Name="Target destination",Address="http://test-backend:8080/target/",Weight=1});
   if(count>2)for(var i=0;i<2;i++){var instance=Guid.NewGuid();db.Add(new GatewayNode{EnvironmentId=target.EnvironmentId,NodeName="pipeline-middle-"+i,InstanceId=instance.ToString(),IdentityHash=new string('f',64),LastHeartbeatAt=DateTimeOffset.UtcNow,Metadata=WebApi.Infrastructure.Gateway.SnapshotSchemaCapabilities.Merge(null,instance,["2.0","2.1","2.2"])});}await db.SaveChangesAsync();
  }
  using(var response=await Scenario.Api.WriteAsync(HttpMethod.Post,"/api/v1/applications",new{organizationId=Scenario.Api.Organization.Id,projectId=Run.ProjectId,code="TARGET_PIPELINE",name="阶段消费方",owner="阶段负责人"})){response.EnsureSuccessStatusCode();ApplicationId=(await response.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();}
  if(!jwt)using(var response=await Scenario.Api.WriteAsync(HttpMethod.Post,$"/api/v1/applications/{ApplicationId}/credentials",new{validFrom=DateTimeOffset.UtcNow.AddMinutes(-1),expiresAt=DateTimeOffset.UtcNow.AddDays(1)})){response.EnsureSuccessStatusCode();CredentialId=(await response.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("credential").GetProperty("id").GetGuid();}
  using(var response=await Scenario.Api.WriteAsync(HttpMethod.Post,$"/api/v1/applications/{ApplicationId}/permissions",new{apiId=Scenario.Api.Api.Id,environmentId=TargetEnvironmentId,validFrom=DateTimeOffset.UtcNow.AddMinutes(-1)})){response.EnsureSuccessStatusCode();AuthorizationId=(await response.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();}
  if(jwt){await using var db=Scenario.Api.Context();var policy=new Policy{OrganizationId=Scenario.Api.Organization.Id,ProjectId=Run.ProjectId,Name="Target JWT",Type="authentication",Config=JwtApplicationBindingTests.Jwt(ApplicationId,"https://target-issuer.example/realm")};TargetPolicyId=policy.Id;db.Add(policy);await db.SaveChangesAsync();}
 }
 public Task<HttpResponseMessage> PrepareAsync(Guid? stage=null,string? key=null,HttpClient? client=null)=>ApiFixture.CommandAsync(client??Scenario.Creator,$"/api/v1/release-pipeline-run-stages/{stage??TargetStageId}/prepare-promotion",key:key);
 public async Task<PromotionDto> PreparedAsync(){using var response=await PrepareAsync();Assert.True(response.StatusCode==HttpStatusCode.OK,await response.Content.ReadAsStringAsync());return (await response.Content.ReadFromJsonAsync<PromotionDto>())!;}
 public PromotionMappingRequest Mapping(bool shared=false)=>new(Scenario.Source.Artifact.Content.Routes.Select(r=>new PromotionRouteMapping(r.Key,null,ClusterId,30000,r.Policies.Select(p=>new PromotionPolicyMapping(p.Type,p.Priority,p.EnvironmentFields.Count>0?TargetPolicyId:null,p.EnvironmentFields.Count>0?1:null)).ToArray())).ToArray(),[new(ApplicationId,CredentialId==Guid.Empty?[]:[CredentialId],[AuthorizationId],shared)]);
 public async Task<PromotionPrecheckDto> PrecheckAsync(PromotionDto promotion,PromotionMappingRequest? mapping=null){using(var response=await Scenario.Api.WriteAsync(HttpMethod.Put,$"/api/v1/release-promotions/{promotion.Id}/mapping",mapping??Mapping(),RevisionTag.Format(promotion.Revision)))response.EnsureSuccessStatusCode();using var precheck=await ApiFixture.CommandAsync(Scenario.Creator,$"/api/v1/release-promotions/{promotion.Id}/precheck",new PromotionPrecheckRequest(ConfirmUpstreamHealth:true,UpstreamHealthComment:"人工确认目标后端与依赖已准备就绪，待正式独立审核"));precheck.EnsureSuccessStatusCode();return (await precheck.Content.ReadFromJsonAsync<PromotionPrecheckDto>())!;}
 public Task<HttpResponseMessage> SubmitAsync(Guid promotion,long revision)=>Scenario.Api.WriteAsync(HttpMethod.Post,$"/api/v1/release-promotions/{promotion}/submit",new{},RevisionTag.Format(revision));
 public ValueTask DisposeAsync()=>Scenario.DisposeAsync();
}
public sealed class PipelinePromotionTests
{
 [Fact] public async Task DelegateNeedsOnlyDirectSourceReadAndCurrentTargetWrite()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();var user=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await f.Scenario.GrantAsync(user.User.Id,"route.write","cluster.read","app.read");await using(var db=f.Scenario.Api.Context()){await db.Set<UserProjectScope>().Where(s=>s.UserId==user.User.Id).ExecuteDeleteAsync();db.Add(new UserProjectScope{UserId=user.User.Id,OrganizationId=f.Scenario.Api.Organization.Id,ProjectId=f.Run.ProjectId,EnvironmentId=f.Run.Stages[0].EnvironmentId,AccessMode="read_only"});db.Add(new UserProjectScope{UserId=user.User.Id,OrganizationId=f.Scenario.Api.Organization.Id,ProjectId=f.Run.ProjectId,EnvironmentId=f.TargetEnvironmentId,AccessMode="read_write"});await db.SaveChangesAsync();}using var response=await f.PrepareAsync(client:user.Client);Assert.True(response.StatusCode==HttpStatusCode.OK,await response.Content.ReadAsStringAsync());var p=(await response.Content.ReadFromJsonAsync<PromotionDto>())!;Assert.Equal(user.User.Id,p.RequestedBy);using var mapping=new HttpRequestMessage(HttpMethod.Put,$"/api/v1/release-promotions/{p.Id}/mapping"){Content=JsonContent.Create(f.Mapping())};mapping.Headers.Add("If-Match",RevisionTag.Format(p.Revision));mapping.Headers.Add("X-CSRF-Token",(await user.Client.GetFromJsonAsync<Dictionary<string,string>>("/api/v1/auth/csrf"))!["token"]);mapping.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString("N"));using var saved=await user.Client.SendAsync(mapping);Assert.True(saved.IsSuccessStatusCode,await saved.Content.ReadAsStringAsync());using var precheck=await ApiFixture.CommandAsync(user.Client,$"/api/v1/release-promotions/{p.Id}/precheck",new PromotionPrecheckRequest(ConfirmUpstreamHealth:true,UpstreamHealthComment:"人工确认目标依赖已具备，来源仅有读取授权"));Assert.True(precheck.IsSuccessStatusCode,await precheck.Content.ReadAsStringAsync());Assert.True((await precheck.Content.ReadFromJsonAsync<PromotionPrecheckDto>())!.CanSubmit);}
 [Fact] public async Task OnlyAdjacentCurrentStageCreatesOneFormalAttemptBinding()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();var p=await f.PreparedAsync();Assert.Equal(f.Run.Stages[0].EnvironmentId,p.SourceEnvironmentId);Assert.Equal(f.TargetEnvironmentId,p.TargetEnvironmentId);Assert.Equal(f.Scenario.RootArtifactId,p.ArtifactId);Assert.Equal(0,p.BaselineConfigVersion);using var retry=await f.PrepareAsync();Assert.Equal(HttpStatusCode.OK,retry.StatusCode);Assert.Equal(p.Id,(await retry.Content.ReadFromJsonAsync<PromotionDto>())!.Id);using var future=await f.PrepareAsync(f.Run.Stages[2].Id);Assert.Equal(HttpStatusCode.Conflict,future.StatusCode);await using var db=f.Scenario.Api.Context();var row=await db.Set<ReleasePromotion>().SingleAsync();Assert.Equal("PipelineRunStage",row.GateOrigin);Assert.Equal(f.TargetStageId,row.PipelineRunStageId);Assert.Equal(row.Id,(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==row.StageAttemptId)).PromotionId);}
 [Theory][InlineData("not_passed")][InlineData("revoked")][InlineData("root_hash")][InlineData("skipped")]
 public async Task InvalidPredecessorCannotPrepare(string fault)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();await using(var db=f.Scenario.Api.Context()){if(fault=="not_passed")(await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.Run.Stages[0].Id)).Status="AwaitingAcceptance";if(fault=="revoked")(await db.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==f.AcceptanceId)).Status="Revoked";if(fault=="root_hash")(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).RootArtifactHash=new string('f',64);if(fault=="skipped")(await db.Set<ReleasePipelineRunStage>().SingleAsync(s=>s.Id==f.TargetStageId)).SourceStageId=f.Run.Stages[2].Id;await db.SaveChangesAsync();}using var response=await f.PrepareAsync();Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var verify=f.Scenario.Api.Context();Assert.False(await verify.Set<ReleasePromotion>().AnyAsync());}
 [Theory][InlineData(4,true)][InlineData(2,false)]
 public async Task ZeroBaselineIsOnlyAnExplicitNonProductionInitialization(int count,bool allowed)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(count);if(!allowed){await using var db=f.Scenario.Api.Context();(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.TargetEnvironmentId)).DesiredConfigVersion=null;await db.SaveChangesAsync();}var p=await f.PreparedAsync();var precheck=await f.PrecheckAsync(p);Assert.Equal(allowed,precheck.CanSubmit);Assert.Contains(precheck.Checks,c=>c.Key=="rollback_snapshot"&&c.ReasonCode==(allowed?"nonproduction_initialization":"production_baseline_required")&&c.Blocking==!allowed);}
 [Fact] public async Task StandaloneCreateCannotForgeStageOriginOrNonProductionTarget()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();using var response=await ApiFixture.CommandAsync(f.Scenario.Creator,"/api/v1/release-promotions",new{artifactId=f.Scenario.RootArtifactId,gateOrigin="PipelineRunStage",pipelineRunStageId=f.TargetStageId,targetEnvironmentId=f.TargetEnvironmentId});Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);Assert.Contains("pipeline_stage_required",await response.Content.ReadAsStringAsync());}
 [Theory][InlineData(false)][InlineData(true)]
 public async Task SharedTargetApplicationRequiresExplicitConfirmation(bool confirmed)
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();var p=await f.PreparedAsync();await using(var db=f.Scenario.Api.Context()){db.Add(new ApplicationApiPermission{ApplicationId=f.ApplicationId,ApiId=f.Scenario.Api.Api.Id,EnvironmentId=f.Run.Stages[0].EnvironmentId,CreatedBy=f.Scenario.Api.User.Id,ValidFrom=DateTimeOffset.UtcNow.AddMinutes(-1)});await db.SaveChangesAsync();}var result=await f.PrecheckAsync(p,f.Mapping(confirmed));Assert.Equal(confirmed,result.CanSubmit);if(!confirmed)Assert.Contains(result.Checks,c=>c.ReasonCode=="shared_credential_confirmation_required");}
 [Fact] public async Task PureJwtNonProductionCandidateSelectsAuthorizationWithoutApiKey()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(jwt:true);var p=await f.PreparedAsync();var result=await f.PrecheckAsync(p);Assert.True(result.CanSubmit);using var response=await f.SubmitAsync(p.Id,result.Revision);Assert.True(response.IsSuccessStatusCode,await response.Content.ReadAsStringAsync());var submitted=(await response.Content.ReadFromJsonAsync<PromotionDto>())!;await using var db=f.Scenario.Api.Context();var release=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==submitted.TargetReleaseId);var candidate=JsonSerializer.Deserialize<FrozenReleaseCandidate>(release.CandidateBytes!,CanonicalJson.Options)!;Assert.Empty(Assert.Single(candidate.Applications).Credentials);Assert.Equal(f.AuthorizationId,Assert.Single(Assert.Single(candidate.Applications).Permissions).Id);Assert.Equal("JWT",Assert.Single(candidate.Routes).EffectiveAuthenticationMode);}
 [Fact] public async Task StagePreparationRequiresAdvancementPermission()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync();var user=await PipelineStageEvidenceTests.DelegateAsync(f.Scenario);await using(var db=f.Scenario.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==user.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="pipeline.run");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}using var response=await f.PrepareAsync(client:user.Client);Assert.Equal(HttpStatusCode.Forbidden,response.StatusCode);}
}
