using Microsoft.EntityFrameworkCore;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Gateway;
using WebApi.Infrastructure.Gateway;
namespace WebApi.Integration.Tests;
public sealed class PipelineTimeoutTests
{
 private sealed class Clock(DateTimeOffset now):TimeProvider {public override DateTimeOffset GetUtcNow()=>now;}
 [Theory][InlineData("Active")][InlineData("Paused")]
 public async Task StageWindowExpiresWithoutCreatingFutureAttempts(string status)
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync(4);var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));DateTimeOffset deadline;await using(var db=s.Api.Context()){var attempt=await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==run.Stages[0].CurrentAttemptId);deadline=attempt.DeadlineAt;(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status=status;await db.SaveChangesAsync();}await PipelineProjectionTests.ProjectAsync(s.Api,run.Id,new Clock(deadline));await using var verify=s.Api.Context();Assert.Equal("TimedOut",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);Assert.Equal("TimedOut",(await verify.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.Id==run.Stages[0].CurrentAttemptId)).Status);Assert.Equal(1,await verify.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==run.Id));}
 [Fact] public async Task StageTimeoutDoesNotErasePublishingOrExtendAckDeadline()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);using(var published=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))published.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();DateTimeOffset stageDeadline;DateTimeOffset? ackDeadline;long sequence;await using(var db=f.Scenario.Api.Context()){stageDeadline=(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.RunStageId==f.TargetStageId)).DeadlineAt;ackDeadline=(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).DeadlineAt;sequence=(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.TargetEnvironmentId)).DeploymentSequence;}await PipelineProjectionTests.ProjectAsync(f.Scenario.Api,f.Run.Id,new Clock(stageDeadline));await using var verify=f.Scenario.Api.Context();Assert.Equal("TimedOut",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status);var release=await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);Assert.Equal("Publishing",release.Status);Assert.Equal(ackDeadline,release.DeadlineAt);Assert.Equal(sequence,(await verify.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==f.TargetEnvironmentId)).DeploymentSequence);}
 [Fact] public async Task OneInstantBeforeDeadlineKeepsCurrentWindowActive()
 {await using var s=new PipelineScenario();await s.InitializeEnvironmentsAsync();var run=await s.StartAsync(await PipelineStageEvidenceTests.VersionAsync(s));await using var db=s.Api.Context();var deadline=(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.RunId==run.Id)).DeadlineAt;await PipelineProjectionTests.ProjectAsync(s.Api,run.Id,new Clock(deadline.AddMilliseconds(-1)));db.ChangeTracker.Clear();Assert.Equal("Active",(await db.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==run.Id)).Status);}
 [Fact] public async Task LatePipelineAckPersistsActualNodeReceiptWithoutCompletingFailedDeployment()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(2);var p=await PipelineExecutionTests.ReadyAsync(f);using(var published=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))published.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();Guid nodeId;string identity;Guid instance;long version,sequence;string hash;await using(var db=f.Scenario.Api.Context()){var release=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);release.DeadlineAt=DateTimeOffset.UtcNow.AddSeconds(-1);version=release.ToConfigVersion;sequence=release.DeploymentSequence!.Value;hash=(await db.Set<GatewayConfigVersion>().SingleAsync(c=>c.EnvironmentId==release.EnvironmentId&&c.VersionNo==version)).SnapshotHash!;var node=await db.Set<GatewayNode>().FirstAsync(n=>n.EnvironmentId==f.TargetEnvironmentId);nodeId=node.Id;identity=node.IdentityHash;instance=Guid.Parse(node.InstanceId);await db.SaveChangesAsync();}using(var services=f.Scenario.Api.Services())Assert.Equal(1,await services.ServiceProvider.GetRequiredService<ReleaseTimeoutService>().ExpireAsync());using(var services=f.Scenario.Api.Services()){var result=await services.ServiceProvider.GetRequiredService<AckService>().RecordAsync(nodeId,new NodeAck(instance,p.TargetReleaseId!.Value,version,sequence,hash,DateTimeOffset.UtcNow,true,null),new NodeIdentity(nodeId,f.TargetEnvironmentId,identity));Assert.Equal("Failed",result.ReleaseState);}await using var verify=f.Scenario.Api.Context();Assert.Equal(1,await verify.Set<GatewayAck>().CountAsync(a=>a.ReleaseId==p.TargetReleaseId&&a.NodeId==nodeId));Assert.Equal(sequence,(await verify.Set<GatewayNode>().SingleAsync(n=>n.Id==nodeId)).CurrentDeploymentSequence);Assert.Equal("Failed",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);}

 [Fact] public async Task RealAckFactsContinueAfterStageTimeoutWithoutAdvancingAnotherEnvironment()
 {await using var f=new PipelinePromotionFixture();await f.InitializeAsync(4);var p=await PipelineExecutionTests.SubmittedAsync(f);using(var published=await ApiFixture.CommandAsync(f.Scenario.Creator,$"/api/v1/releases/{p.TargetReleaseId}/publish"))published.EnsureSuccessStatusCode();await f.Scenario.Source.Deployment.BuildQueuedAsync();DateTimeOffset deadline;await using(var db=f.Scenario.Api.Context())deadline=(await db.Set<ReleasePipelineStageAttempt>().SingleAsync(a=>a.RunStageId==f.TargetStageId)).DeadlineAt;await PipelineProjectionTests.ProjectAsync(f.Scenario.Api,f.Run.Id,new Clock(deadline));await f.Scenario.AcknowledgeAsync(p.TargetReleaseId!.Value);await PipelineProjectionTests.ProjectAsync(f.Scenario.Api,f.Run.Id);await using var verify=f.Scenario.Api.Context();Assert.Equal("Succeeded",(await verify.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.Equal("TimedOut",(await verify.Set<ReleasePipelineRun>().SingleAsync(r=>r.Id==f.Run.Id)).Status);Assert.Equal(2,await verify.Set<GatewayAck>().CountAsync(a=>a.ReleaseId==p.TargetReleaseId&&a.Success));Assert.Equal(2,await verify.Set<ReleasePipelineStageAttempt>().CountAsync(a=>a.RunId==f.Run.Id));}

}
