using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http;
using WebApi.Contracts.Observability;
using WebApi.Contracts.Policies;
using WebApi.Infrastructure.Observability;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PolicyObservationTests
{
    private static readonly Guid Env=Guid.NewGuid(),Policy=Guid.NewGuid();
    private static TrustedObservationScope Scope()=>new(Guid.NewGuid(),Guid.NewGuid(),[Env],[],new Dictionary<Guid,string>(),new Dictionary<Guid,string>(),new Dictionary<Guid,ObservationDestination>(),new Dictionary<Guid,IReadOnlySet<Guid>> {{Env,new HashSet<Guid>{Policy}}});
    private static Dictionary<string,string> Attributes()=>new() {{"webapi.policy.rate_limit.id",Policy.ToString()},{"webapi.policy.rate_limit.type","rate_limit"},{"webapi.policy.rate_limit.revision","1"},{"webapi.policy.rate_limit.decision","Exceeded"},{"webapi.policy.rate_limit.rejection_reason","rate_limit_exceeded"},{"raw_api_key","do-not-return"}};
    [Fact] public void TwoDecisionsBoundedAndOldLogsReadable()
    {var old=PolicyObservationProjection.Read(new Dictionary<string,string>(),Scope(),Env);Assert.Empty(old.Decisions);Assert.False(old.Rejected);var attrs=Attributes();attrs["webapi.policy.circuit_breaker.id"]=Policy.ToString();attrs["webapi.policy.circuit_breaker.type"]="circuit_breaker";attrs["webapi.policy.circuit_breaker.revision"]="1";attrs["webapi.policy.circuit_breaker.decision"]="Allowed";attrs["webapi.policy.retry.id"]=Policy.ToString();var result=PolicyObservationProjection.Read(attrs,Scope(),Env);Assert.Equal(2,result.Decisions.Count);Assert.DoesNotContain("do-not-return",JsonSerializer.Serialize(result.Decisions));}
    [Fact] public void ForeignPolicyAndUnknownDecisionRejectedWithoutLosingOldTraceSpan()
    {var attrs=Attributes();attrs["webapi.policy.rate_limit.id"]=Guid.NewGuid().ToString();var projection=TraceProjection.Project("0123456789abcdef0123456789abcdef",[new(Env,"0123456789abcdef",null,"gateway.request",DateTimeOffset.UtcNow,12,"Server","Error",attrs)],Scope());Assert.True(projection.PartialTrace);Assert.Empty(Assert.Single(projection.Spans).PolicyDecisions);Assert.DoesNotContain(attrs["webapi.policy.rate_limit.id"],JsonSerializer.Serialize(projection));attrs=Attributes();attrs["webapi.policy.rate_limit.decision"]="secret-marker";Assert.True(PolicyObservationProjection.Read(attrs,Scope(),Env).Rejected);}
    [Fact] public async Task PartialSourceKeepsNullPolicyKpi()
    {var source=new MetricProtocolHandler {MissingSecondNode=true};await using var api=new ApiFixture();await api.InitializeAsync(b=>{b.Configuration["Observability:Enabled"]="true";b.Services.PostConfigure<HttpClientFactoryOptions>("observability",o=>o.HttpMessageHandlerBuilderActions.Add(builder=>builder.PrimaryHandler=source));});await api.SeedConsumerAsync();await ObservationTestSupport.GrantAsync(api,["metrics.read"]);using var login=await api.LoginAsync();login.EnsureSuccessStatusCode();await using(var db=api.Context()) {for(var i=0;i<2;i++) db.Add(new GatewayNode {EnvironmentId=api.Environment.Id,NodeName="node-"+i});await db.SaveChangesAsync();}source.EnvironmentId=api.Environment.Id;source.ApiId=api.Api.Id;source.ApplicationId=api.Application.Id;source.DestinationId=api.Destination.Id;source.ClusterId=api.Cluster.Id;var url=$"/api/v1/observability/metrics?organizationId={api.Organization.Id}&projectId={api.Project.Id}&environmentId={api.Environment.Id}&start={Uri.EscapeDataString(source.Start.ToString("O"))}&end={Uri.EscapeDataString(source.End.ToString("O"))}";var envelope=(await api.Client.GetFromJsonAsync<ObservationEnvelope<MetricsDto>>(url))!;Assert.Equal(SourceState.Partial,envelope.SourceState);foreach(var key in new[]{"circuit_rejected_count","rate_limit_store_unavailable_count"}) Assert.Null(Assert.Single(envelope.Data!.Kpis,x=>x.Metric==key).Value);}
    [Fact] public async Task LokiAndCsvReturnScopedPolicyDecisions()
    {
        await using var f=new LogFixture();await File.WriteAllTextAsync(f.Secret,Convert.ToBase64String(System.Security.Cryptography.RandomNumberGenerator.GetBytes(32)));if(!OperatingSystem.IsWindows()) File.SetUnixFileMode(f.Secret,UnixFileMode.UserRead|UnixFileMode.UserWrite);
        await f.Api.InitializeAsync(b=>{b.Configuration["Observability:Enabled"]="true";b.Configuration["Observability:CursorSigningSecretFile"]=f.Secret;b.Configuration["Observability:IpHmacSecretFile"]=f.Secret;b.Services.PostConfigure<HttpClientFactoryOptions>("observability",o=>o.HttpMessageHandlerBuilderActions.Add(builder=>builder.PrimaryHandler=f.Source));});await f.Api.SeedConsumerAsync();await ObservationTestSupport.GrantAsync(f.Api,["log.read"]);using var login=await f.Api.LoginAsync();login.EnsureSuccessStatusCode();await using(var db=f.Api.Context()) {db.Add(new GatewayNode {EnvironmentId=f.Api.Environment.Id,NodeName="logs-node"});db.Add(new Policy {Id=Policy,OrganizationId=f.Api.Organization.Id,ProjectId=f.Api.Project.Id,Name="日志策略",Type="rate_limit"});await db.SaveChangesAsync();}
        f.Source.EnvironmentId=f.Api.Environment.Id;f.Source.ApiId=f.Api.Api.Id;f.Source.ApplicationId=f.Api.Application.Id;f.Source.DestinationId=f.Api.Destination.Id;f.Source.Rows.Add(new(Guid.NewGuid(),f.Source.Nano,"GET","/orders","logs-node"));foreach(var (key,value) in Attributes()) f.Source.ExtraMetadata[key.Replace('.','_')]=value;
        var url=$"/api/v1/observability/logs?organizationId={f.Api.Organization.Id}&projectId={f.Api.Project.Id}&environmentId={f.Api.Environment.Id}&start={Uri.EscapeDataString(f.Source.Start.ToString("O"))}&end={Uri.EscapeDataString(f.Source.End.ToString("O"))}";var page=(await f.Api.Client.GetFromJsonAsync<ObservationEnvelope<CursorPage<AccessLogDto>>>(url))!;Assert.Equal(Policy,Assert.Single(Assert.Single(page.Data!.Items).PolicyDecisions).PolicyId);using var csv=await f.Api.Client.GetAsync(url.Replace("/logs?","/logs/export?"));csv.EnsureSuccessStatusCode();Assert.Contains(Policy.ToString(),await csv.Content.ReadAsStringAsync());
        var foreign=Guid.NewGuid();f.Source.ExtraMetadata["webapi_policy_rate_limit_id"]=foreign.ToString();var rejected=(await f.Api.Client.GetFromJsonAsync<ObservationEnvelope<CursorPage<AccessLogDto>>>(url))!;Assert.Equal(SourceState.Partial,rejected.SourceState);Assert.Empty(Assert.Single(rejected.Data!.Items).PolicyDecisions);Assert.DoesNotContain(foreign.ToString(),JsonSerializer.Serialize(rejected));
    }
    [Fact] public async Task PolicyMetricsRequireRealSeriesAndStayEnvironmentScoped()
    {
        var source=new MetricProtocolHandler {PolicyId=Policy};await using var api=new ApiFixture();await api.InitializeAsync(b=>{b.Configuration["Observability:Enabled"]="true";b.Services.PostConfigure<HttpClientFactoryOptions>("observability",o=>o.HttpMessageHandlerBuilderActions.Add(builder=>builder.PrimaryHandler=source));});await api.SeedConsumerAsync();await ObservationTestSupport.GrantAsync(api,["metrics.read"]);using var login=await api.LoginAsync();login.EnsureSuccessStatusCode();await using(var db=api.Context()) {db.Add(new GatewayNode {EnvironmentId=api.Environment.Id,NodeName="node-0"});db.Add(new Policy {Id=Policy,OrganizationId=api.Organization.Id,ProjectId=api.Project.Id,Name="metrics",Type="rate_limit"});await db.SaveChangesAsync();}source.EnvironmentId=api.Environment.Id;source.ApiId=api.Api.Id;source.ApplicationId=api.Application.Id;source.DestinationId=api.Destination.Id;
        var url=$"/api/v1/observability/metrics?organizationId={api.Organization.Id}&projectId={api.Project.Id}&environmentId={api.Environment.Id}&start={Uri.EscapeDataString(source.Start.ToString("O"))}&end={Uri.EscapeDataString(source.End.ToString("O"))}";
        async Task<ObservationEnvelope<MetricsDto>> Query(string suffix="")=>(await api.Client.GetFromJsonAsync<ObservationEnvelope<MetricsDto>>(url+suffix))!;
        var all=await Query();Assert.Equal(7,Assert.Single(all.Data!.Kpis,x=>x.Metric=="rate_limit_store_unavailable_count").Value);Assert.Equal(3,Assert.Single(all.Data.Kpis,x=>x.Metric=="circuit_rejected_count").Value);Assert.NotEmpty(all.Data.Trends["circuit_rejected_count"]);
        var apiOnly=await Query($"&apiId={api.Api.Id}&groupBy=Api&sortBy=circuit_rejected_count");Assert.Equal(SourceState.NotApplicable,Assert.Single(apiOnly.Data!.Kpis,x=>x.Metric=="circuit_rejected_count").State);Assert.Null(Assert.Single(apiOnly.Data.Kpis,x=>x.Metric=="circuit_rejected_count").Value);Assert.All(apiOnly.Data.Trends["circuit_rejected_count"],x=>Assert.Null(x.Value));
        source.PolicyId=Guid.NewGuid();var foreign=await Query();Assert.Equal(SourceState.NoData,Assert.Single(foreign.Data!.Kpis,x=>x.Metric=="circuit_rejected_count").State);Assert.Null(Assert.Single(foreign.Data.Kpis,x=>x.Metric=="circuit_rejected_count").Value);source.PolicyId=null;var empty=await Query();Assert.Null(Assert.Single(empty.Data!.Kpis,x=>x.Metric=="rate_limit_store_unavailable_count").Value);
    }

}
