using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Gateway;
using WebApi.Infrastructure.Gateway;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PolicyNodeCapabilityTests
{
    private static async Task Advanced(DeploymentScenario s)
    {await using var db=s.Api.Context();var route=await db.Set<ApiRoute>().SingleAsync();var p=new Policy {OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,Name="共享限流",Type="rate_limit",Config="{\"algorithm\":\"TokenBucket\",\"keyBy\":\"Route\",\"refillTokens\":1,\"windowMs\":1000,\"burst\":3,\"redisFailureMode\":\"Reject\"}"};db.Add(p);db.Add(new RoutePolicyBinding {RouteId=route.Id,PolicyId=p.Id});route.Revision++;await db.SaveChangesAsync();}
    private static async Task Capable(DeploymentScenario s)
    {for(var i=0;i<2;i++) {using var response=await s.NodeAsync(i,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-"+i,s.Instances[i],"untrusted-version",["2.0","2.1"]));response.EnsureSuccessStatusCode();}}
    [Fact] public void MissingCapabilityMeansOnlyTwoPointZero()
    {Assert.Equal(new[]{"2.0"},SnapshotSchemaCapabilities.Read(new GatewayNode {InstanceId=Guid.NewGuid().ToString()}));}
    [Fact] public async Task ReregisterDoesNotInheritOldInstanceCapability()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Capable(s);var replacement=Guid.NewGuid();using var response=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",replacement,"test"));response.EnsureSuccessStatusCode();await using var db=s.Api.Context();var node=await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0]);Assert.Equal(new[]{"2.0"},SnapshotSchemaCapabilities.Read(node));Assert.Equal(replacement.ToString(),node.InstanceId);}
    [Fact] public async Task OldNodeBlocksAdvancedBeforeDesiredOrSequenceChanges()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Advanced(s);var id=await s.ReadyAsync();using var response=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);Assert.Contains("gateway_schema_unsupported",await response.Content.ReadAsStringAsync());await CheckUnchanged(s,"Ready");}
    [Fact] public async Task WorkerRechecksCapability()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Advanced(s);await Capable(s);var id=await s.ReadyAsync();using var accepted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");accepted.EnsureSuccessStatusCode();using var replacement=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",Guid.NewGuid(),"test"));replacement.EnsureSuccessStatusCode();await s.BuildQueuedAsync();await CheckUnchanged(s,"Failed");await using var db=s.Api.Context();Assert.Equal("gateway_schema_unsupported",(await db.Set<ReleaseRecord>().SingleAsync()).FailureCode);}
    private static async Task CheckUnchanged(DeploymentScenario s,string status)
    {await using var db=s.Api.Context();var env=await db.Set<EnvironmentRecord>().SingleAsync();Assert.Null(env.DesiredConfigVersion);Assert.Equal(0,env.DeploymentSequence);Assert.Equal(status,(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.False(await db.Set<GatewayConfigVersion>().AnyAsync());Assert.False(await db.Set<OutboxMessage>().AnyAsync());}
    [Fact] public void MetadataFieldsPreserved()
    {var instance=Guid.NewGuid();var metadata=SnapshotSchemaCapabilities.Merge("{\"zone\":\"east\",\"nested\":{\"a\":1}}",instance,["2.1","2.0","2.1"]);using var json=JsonDocument.Parse(metadata);Assert.Equal("east",json.RootElement.GetProperty("zone").GetString());Assert.Equal(1,json.RootElement.GetProperty("nested").GetProperty("a").GetInt32());Assert.Equal(new[]{"2.0","2.1"},SnapshotSchemaCapabilities.Read(new GatewayNode {InstanceId=instance.ToString(),Metadata=metadata}));Assert.Equal(new[]{"2.0"},SnapshotSchemaCapabilities.Read(new GatewayNode {InstanceId=Guid.NewGuid().ToString(),Metadata=metadata}));}
    [Theory] [InlineData("9.0")] [InlineData("")] public async Task FutureSchemasRejected(string schema)
    {await using var s=new DeploymentScenario();await s.InitializeAsync();using var response=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",s.Instances[0],"test",[schema]));Assert.Equal(HttpStatusCode.UnprocessableEntity,response.StatusCode);}
    [Fact] public async Task RollbackAndRetryUseTargetSchema()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Capable(s);await Advanced(s);await s.PublishAsync();await using(var db=s.Api.Context()) await db.Set<RoutePolicyBinding>().ExecuteDeleteAsync();var latest=await s.PublishAsync();using var old=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",Guid.NewGuid(),"test"));old.EnsureSuccessStatusCode();using var rollback=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{latest}/rollback",new {targetConfigVersion=1L});rollback.EnsureSuccessStatusCode();var id=(await rollback.Content.ReadFromJsonAsync<WebApi.Contracts.Releases.ReleaseDto>())!.Id;using var submit=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit");submit.EnsureSuccessStatusCode();await s.ApproveAsync(id);using var denied=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,denied.StatusCode);await using var check=s.Api.Context();Assert.Equal(2,(await check.Set<EnvironmentRecord>().SingleAsync()).DesiredConfigVersion);}
    [Fact] public async Task UnsupportedCurrentInstanceCannotAcknowledgeAdvancedSuccess()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Capable(s);await Advanced(s);var id=await s.PublishAsync(false);var artifact=await s.DesiredAsync(id);using var old=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",s.Instances[0],"test"));old.EnsureSuccessStatusCode();using var ack=await s.NodeAsync(0,$"/internal/v1/nodes/{s.NodeIds[0]}/ack",new NodeAck(s.Instances[0],id,artifact.Envelope.ConfigVersion,artifact.Envelope.DeploymentSequence,artifact.Envelope.PayloadHash,DateTimeOffset.UtcNow,true,null));Assert.Equal(HttpStatusCode.Conflict,ack.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync());}
    [Fact] public async Task RetryOfAdvancedArtifactRequiresCapabilities()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await Capable(s);await Advanced(s);var id=await s.PublishAsync(false);await using(var db=s.Api.Context()) {(await db.Set<ReleaseRecord>().SingleAsync()).Status="Failed";await db.SaveChangesAsync();}using var old=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",Guid.NewGuid(),"test"));old.EnsureSuccessStatusCode();using var retry=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/retry");Assert.Equal(HttpStatusCode.Conflict,retry.StatusCode);Assert.Contains("gateway_schema_unsupported",await retry.Content.ReadAsStringAsync());await using var check=s.Api.Context();Assert.Equal(1,await check.Set<ReleaseRecord>().CountAsync());Assert.Equal(1,(await check.Set<EnvironmentRecord>().SingleAsync()).DeploymentSequence);}
    [Fact] public async Task ExcessiveSchemasRejectedAndHeartbeatRefreshesCurrentInstance()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();using var invalid=await s.NodeAsync(0,"/internal/v1/nodes/register",new RegisterNodeRequest(s.Api.Environment.Id,"node-0",s.Instances[0],"test",["2.0","2.0","2.0","2.0","2.0"]));Assert.Equal(HttpStatusCode.UnprocessableEntity,invalid.StatusCode);using var heartbeat=await s.NodeAsync(0,$"/internal/v1/nodes/{s.NodeIds[0]}/heartbeat",new NodeHeartbeat(s.Instances[0],0,0,"NotReady",["2.0","2.1"]));heartbeat.EnsureSuccessStatusCode();await using var db=s.Api.Context();Assert.Contains("2.1",SnapshotSchemaCapabilities.Read(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.NodeIds[0])));}

}
