using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class ProductionVerificationTests
{
 internal static readonly string[] Types=["EntryConnectivity","AuthenticationAuthorization","CriticalBusinessCall"];
 internal static async Task<PromotionDto> Deployed(PromotionScenario s,HttpClient? publisher=null)
 {var p=await PromotionExecutionTests.Ready(s);using(var start=await ApiFixture.CommandAsync(publisher??s.Api.Client,$"/api/v1/releases/{p.TargetReleaseId}/publish"))start.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(p.TargetReleaseId!.Value);return p;}
 internal static async Task<(UserRecord User,HttpClient Client)> Verifier(PromotionScenario s,string role="ProductionVerifier",bool permission=true)
 {var user=await s.NewProductionApproverAsync(role);if(permission)await s.GrantAsync(user.User.Id,"release.verify");return user;}
 internal static async Task<string> ContextHash(PromotionScenario s,HttpClient client)
 {using var response=await client.GetAsync($"/api/v1/release-promotions/{s.PromotionId}/verification-context");response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>()).GetProperty("hash").GetString()!;}
 internal static async Task<HttpResponseMessage> Record(PromotionScenario s,HttpClient client,string type="EntryConnectivity",string result="Passed",Guid? report=null,string? key=null,string? expected=null)
 {var hash=expected??await ContextHash(s,client);return await ApiFixture.CommandAsync(client,$"/api/v1/release-promotions/{s.PromotionId}/verifications",new{type,result,startedAt=DateTimeOffset.UtcNow.AddSeconds(-1),finishedAt=DateTimeOffset.UtcNow,reportId=report,comment="人工验证实际生产入口与业务",expectedContextHash=hash},key);}
 internal static async Task<PromotionDto> PassAll(PromotionScenario s,HttpClient verifier)
 {PromotionDto? dto=null;foreach(var type in Types){using var recorded=await Record(s,verifier,type);recorded.EnsureSuccessStatusCode();dto=await recorded.Content.ReadFromJsonAsync<PromotionDto>();}return dto!;}
 [Fact] public async Task ThreeIndependentPassedFactsCompleteDeliveryAndBindActualDeployment()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);using(var first=await Record(s,verifier.Client)){first.EnsureSuccessStatusCode();Assert.Equal("Verifying",(await first.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}using(var second=await Record(s,verifier.Client,Types[1]))second.EnsureSuccessStatusCode();using var final=await Record(s,verifier.Client,Types[2]);final.EnsureSuccessStatusCode();Assert.Equal("Completed",(await final.Content.ReadFromJsonAsync<PromotionDto>())!.Status);await using var db=s.Api.Context();var rows=await db.Set<ReleaseVerification>().Where(v=>v.PromotionId==p.Id).ToArrayAsync();Assert.Equal(3,rows.Length);var desired=await s.Source.Deployment.DesiredAsync(p.TargetReleaseId!.Value);Assert.All(rows,v=>{Assert.Equal("Production",v.Phase);Assert.Equal(p.TargetReleaseId,v.ReleaseId);Assert.Equal(2,v.ConfigVersion);Assert.Equal(2,v.DeploymentSequence);Assert.Equal(desired.Envelope.PayloadHash,v.SnapshotHash);Assert.True(v.IsManual);Assert.Equal(verifier.User.Id,v.CreatedBy);});Assert.NotNull((await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).CompletedAt);}
 [Theory][InlineData(false)][InlineData(true)]
 public async Task ApplicantCannotVerifyEvenWithPlatformAdminRole(bool admin)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);await s.GrantAsync(s.Api.User.Id,"release.verify");if(admin){await using var db=s.Api.Context();var role=await db.Set<Role>().SingleAsync(r=>db.Set<UserRole>().Any(u=>u.UserId==s.Api.User.Id&&u.RoleId==r.Id));role.Code="PlatformAdmin";role.IsSystem=true;role.OrganizationId=null;await db.SaveChangesAsync();}using var recorded=await Record(s,s.Api.Client);Assert.Equal(HttpStatusCode.Forbidden,recorded.StatusCode);await using var context=s.Api.Context();Assert.False(await context.Set<ReleaseVerification>().AnyAsync(v=>v.PromotionId==s.PromotionId));}
 [Fact] public async Task ActualPublisherCannotVerifyEvenWhenDifferentFromApplicant()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var publisher=await s.NewProductionApproverAsync("ProductionPublisher");await s.GrantAsync(publisher.User.Id,"release.publish","release.verify");await Deployed(s,publisher.Client);using var recorded=await Record(s,publisher.Client);Assert.Equal(HttpStatusCode.Forbidden,recorded.StatusCode);}
 [Theory][InlineData(false)][InlineData(true)]
 public async Task DedicatedPermissionAndWritableScopeAreRequired(bool readOnly)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s,permission:readOnly);if(readOnly){await using var db=s.Api.Context();await db.Set<UserProjectScope>().Where(p=>p.UserId==verifier.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.AccessMode,"read_only"));}using var recorded=await Record(s,verifier.Client);Assert.Equal(HttpStatusCode.Forbidden,recorded.StatusCode);}
 [Fact] public async Task ExpiredEarlierFactsCannotCompleteWithOnlyLastType()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);foreach(var type in Types.Take(2)){using var response=await Record(s,verifier.Client,type);response.EnsureSuccessStatusCode();}await using(var db=s.Api.Context())await db.Set<ReleaseVerification>().Where(v=>v.PromotionId==s.PromotionId).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));using var final=await Record(s,verifier.Client,Types[2]);final.EnsureSuccessStatusCode();Assert.Equal("Verifying",(await final.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}
 [Fact] public async Task FailedEvidenceDoesNotRollbackAndLatestPassedAllowsReverification()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);using(var failed=await Record(s,verifier.Client,Types[0],"Failed")){failed.EnsureSuccessStatusCode();Assert.Equal("VerificationFailed",(await failed.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}await using(var db=s.Api.Context()){Assert.False(await db.Set<ReleaseRecord>().AnyAsync(r=>r.ReleaseType=="rollback"));Assert.Equal(1,await db.Set<OutboxMessage>().CountAsync(m=>m.ReleaseId!=s.Source.ReleaseId&&db.Set<ReleaseRecord>().Any(r=>r.Id==m.ReleaseId&&r.PromotionId==s.PromotionId)));}Assert.Equal("Completed",(await PassAll(s,verifier.Client)).Status);await using var context=s.Api.Context();Assert.Equal(4,await context.Set<ReleaseVerification>().CountAsync(v=>v.PromotionId==s.PromotionId));}
 [Fact] public async Task EntryChangeRequiresCompleteNewContextWithoutReusingOldPassed()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);foreach(var type in Types.Take(2)){using var old=await Record(s,verifier.Client,type);old.EnsureSuccessStatusCode();}await using(var db=s.Api.Context())await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.GatewayPublicUrl,"https://new-prod-entry.example").SetProperty(e=>e.BasePath,"/v2").SetProperty(e=>e.AccessAddressRevision,2));using(var last=await Record(s,verifier.Client,Types[2])){last.EnsureSuccessStatusCode();Assert.Equal("Verifying",(await last.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}foreach(var type in Types.Take(2)){using var fresh=await Record(s,verifier.Client,type);fresh.EnsureSuccessStatusCode();}await using var context=s.Api.Context();Assert.Equal("Completed",(await context.Set<ReleasePromotion>().SingleAsync(p=>p.Id==s.PromotionId)).Status);Assert.Equal(5,await context.Set<ReleaseVerification>().CountAsync(v=>v.PromotionId==s.PromotionId));Assert.Equal(3,await context.Set<ReleaseVerification>().CountAsync(v=>v.PromotionId==s.PromotionId&&v.AccessAddressRevision==2));}
 [Theory][InlineData("sequence")][InlineData("snapshot")][InlineData("node")]
 public async Task ChangedActualRuntimeCannotCompleteOriginalDelivery(string changed)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);foreach(var type in Types.Take(2)){using var first=await Record(s,verifier.Client,type);first.EnsureSuccessStatusCode();}var expected=await ContextHash(s,verifier.Client);await using(var db=s.Api.Context()){if(changed=="sequence")await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.DeploymentSequence,99));if(changed=="snapshot")await db.Set<GatewayConfigVersion>().Where(v=>v.EnvironmentId==s.TargetEnvironmentId&&v.VersionNo==2).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.SnapshotHash,new string('f',64)));if(changed=="node")await db.Set<GatewayNode>().Where(n=>n.Id==s.TargetNodeIds[1]).ExecuteUpdateAsync(x=>x.SetProperty(n=>n.CurrentConfigVersion,1));}using var final=await Record(s,verifier.Client,Types[2],expected:expected);Assert.False(final.IsSuccessStatusCode);await using var context=s.Api.Context();Assert.NotEqual("Completed",(await context.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);}
 [Fact] public async Task PreviouslyOpenedEntryContextCannotSilentlyBindOldEvidenceToNewEntry()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);var old=await ContextHash(s,verifier.Client);await using(var db=s.Api.Context())await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.GatewayPublicUrl,"https://new-entry.example").SetProperty(e=>e.AccessAddressRevision,2));using var rejected=await Record(s,verifier.Client,expected:old);Assert.Equal(HttpStatusCode.Conflict,rejected.StatusCode);await using var context=s.Api.Context();Assert.False(await context.Set<ReleaseVerification>().AnyAsync(v=>v.PromotionId==s.PromotionId));}
 [Fact] public async Task ManualProductionFactRequiresReviewedContextToken()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);using var response=await ApiFixture.CommandAsync(verifier.Client,$"/api/v1/release-promotions/{s.PromotionId}/verifications",new RecordVerificationRequest(Types[0],"Passed",DateTimeOffset.UtcNow.AddSeconds(-1),DateTimeOffset.UtcNow));Assert.Equal(HttpStatusCode.UnprocessableEntity,response.StatusCode);}
 internal static async Task<Guid> ReadyRollback(PromotionScenario s,Guid original)
 {using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{original}/rollback",new{targetConfigVersion=1L});created.EnsureSuccessStatusCode();var id=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;using(var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit"))submitted.EnsureSuccessStatusCode();await s.Source.Deployment.ApproveAsync(id);return id;}
 [Fact] public async Task QueuedApprovedRollbackBlocksLastVerificationBeforeSnapshotSwitch()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);foreach(var type in Types.Take(2)){using var response=await Record(s,verifier.Client,type);response.EnsureSuccessStatusCode();}var hash=await ContextHash(s,verifier.Client);var rollback=await ReadyRollback(s,p.TargetReleaseId!.Value);using(var started=await PromotionExecutionTests.Start(s,rollback))started.EnsureSuccessStatusCode();using var final=await Record(s,verifier.Client,Types[2],expected:hash);Assert.Equal(HttpStatusCode.Conflict,final.StatusCode);await using var db=s.Api.Context();Assert.NotEqual("Completed",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);}
 [Fact] public async Task StableContextDoesNotManufactureRepeatedEntryChangeEvents()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);await PassAll(s,verifier.Client);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleasePromotionEvent>().CountAsync(e=>e.PromotionId==p.Id&&e.ReasonCode=="production_context_bound"));Assert.False(await db.Set<ReleasePromotionEvent>().AnyAsync(e=>e.PromotionId==p.Id&&e.ReasonCode=="production_context_changed"));}
 [Fact] public async Task FailedVerificationCanUseApprovedRollbackWithoutRestoringEntryMetadata()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);using(var failed=await Record(s,verifier.Client,result:"Failed"))failed.EnsureSuccessStatusCode();await using(var db=s.Api.Context())await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.GatewayPublicUrl,"https://changed-entry.example").SetProperty(e=>e.AccessAddressRevision,2));var rollback=await ReadyRollback(s,p.TargetReleaseId!.Value);using(var started=await PromotionExecutionTests.Start(s,rollback))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(rollback);await using var context=s.Api.Context();Assert.Equal("RolledBack",(await context.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal("https://changed-entry.example",(await context.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).GatewayPublicUrl);Assert.Equal(1L,(await context.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).DesiredConfigVersion);Assert.Equal("Failed",(await context.Set<ReleaseVerification>().SingleAsync(v=>v.PromotionId==p.Id)).Result);}
 [Fact] public async Task CompletedDeliveryAndEvidenceStayHistoricalAfterOrdinaryLaterDeployment()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);await PassAll(s,verifier.Client);string before;await using(var db=s.Api.Context())before=System.Text.Json.JsonSerializer.Serialize(await db.Set<ReleaseVerification>().Where(v=>v.PromotionId==p.Id).OrderBy(v=>v.Id).ToArrayAsync());using(var legacy=await s.Api.WriteAsync(HttpMethod.Put,$"/api/v1/projects/{s.Api.Project.Id}/delivery-policy",new SaveDeliveryPolicyRequest(s.Api.Environment.Id,s.TargetEnvironmentId,"Legacy",["InterfaceFunction","Integration","ContractCompatibility"],1440),"\"1\""))legacy.EnsureSuccessStatusCode();var preview=await s.Api.PreviewReleaseRequestAsync(2,s.Api.Version.Id,s.TargetEnvironmentId);using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",preview);created.EnsureSuccessStatusCode();var release=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;using(var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{release}/submit"))submitted.EnsureSuccessStatusCode();await s.Source.Deployment.ApproveAsync(release);using(var started=await PromotionExecutionTests.Start(s,release))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(release);await using var context=s.Api.Context();Assert.Equal("Completed",(await context.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal(before,System.Text.Json.JsonSerializer.Serialize(await context.Set<ReleaseVerification>().Where(v=>v.PromotionId==p.Id).OrderBy(v=>v.Id).ToArrayAsync()));}
 [Fact] public async Task RevokedEarlierVerifierAuthorityCannotCompleteWithAnotherPersonsLastFact()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var first=await Verifier(s);foreach(var type in Types.Take(2)){using var response=await Record(s,first.Client,type);response.EnsureSuccessStatusCode();}await using(var db=s.Api.Context())await db.Set<RolePermission>().Where(r=>db.Set<UserRole>().Any(u=>u.UserId==first.User.Id&&u.RoleId==r.RoleId)&&db.Set<Permission>().Any(p=>p.Id==r.PermissionId&&p.Code=="release.verify")).ExecuteDeleteAsync();var second=await Verifier(s,"ReplacementVerifier");using(var last=await Record(s,second.Client,Types[2])){last.EnsureSuccessStatusCode();Assert.Equal("Verifying",(await last.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}PromotionDto? completed=null;foreach(var type in Types.Take(2)){using var fresh=await Record(s,second.Client,type);fresh.EnsureSuccessStatusCode();completed=await fresh.Content.ReadFromJsonAsync<PromotionDto>();}Assert.Equal("Completed",completed!.Status);}
 [Fact] public async Task SourceOwnedReportCannotBeReusedAsProductionFact()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);await Deployed(s);var verifier=await Verifier(s);using var upload=await s.Source.UploadAsync(System.Text.Encoding.UTF8.GetBytes("来源测试报告，不能替代目标生产验证"));upload.EnsureSuccessStatusCode();var report=(await upload.Content.ReadFromJsonAsync<VerificationReportDto>())!;using var response=await Record(s,verifier.Client,report:report.Id);Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<ReleaseVerification>().AnyAsync(v=>v.PromotionId==s.PromotionId));}
 [Fact] public async Task CompletedHistoricalDeliveryStillShowsItsNewApprovedRollbackExecution()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);await PassAll(s,verifier.Client);var rollback=await ReadyRollback(s,p.TargetReleaseId!.Value);using(var started=await PromotionExecutionTests.Start(s,rollback))started.EnsureSuccessStatusCode();using var view=await s.Api.Client.GetAsync($"/api/v1/release-promotions/{p.Id}");view.EnsureSuccessStatusCode();var dto=(await view.Content.ReadFromJsonAsync<PromotionDto>())!;Assert.Equal("Completed",dto.Status);Assert.Equal(rollback,dto.Deployment!.ReleaseId);}
 [Fact] public async Task LastVerificationAndApprovedRollbackSerializeWithoutCompletingAfterSnapshotSwitch()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Deployed(s);var verifier=await Verifier(s);foreach(var type in Types.Take(2)){using var response=await Record(s,verifier.Client,type);response.EnsureSuccessStatusCode();}var hash=await ContextHash(s,verifier.Client);var rollback=await ReadyRollback(s,p.TargetReleaseId!.Value);
 var change=Task.Run(async()=>{using var started=await PromotionExecutionTests.Start(s,rollback);started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();});using var last=await Record(s,verifier.Client,Types[2],expected:hash);await change;Assert.True(last.IsSuccessStatusCode||last.StatusCode==HttpStatusCode.Conflict);await using(var db=s.Api.Context()){var transition=await db.Set<OutboxMessage>().SingleAsync(m=>m.ReleaseId==rollback);Assert.False(await db.Set<ReleasePromotionEvent>().AnyAsync(e=>e.PromotionId==p.Id&&e.ToStatus=="Completed"&&e.OccurredAt>transition.CreatedAt));}await s.TargetAckAllAsync(rollback);await using var context=s.Api.Context();Assert.Equal("RolledBack",(await context.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);}
}
