using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PromotionCredentialTests
{
 [Fact] public async Task OnlyExplicitTargetCredentialsAndAuthorizationsEnterCandidate()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using(var extra=await s.Api.WriteAsync(HttpMethod.Post,$"/api/v1/applications/{s.TargetApplicationId}/credentials",new{validFrom=DateTimeOffset.UtcNow.AddMinutes(-1),expiresAt=DateTimeOffset.UtcNow.AddDays(1)}))extra.EnsureSuccessStatusCode();using var saved=await s.SaveAsync(s.Mapping());saved.EnsureSuccessStatusCode();var candidate=await s.PrepareAsync();var application=Assert.Single(candidate.Applications);Assert.Equal(s.TargetApplicationId,application.Application.Id);Assert.Equal(s.TargetCredentialId,Assert.Single(application.Credentials).Id);Assert.Equal(s.TargetAuthorizationId,Assert.Single(application.Permissions).Id);await using var db=s.Api.Context();var sourceIds=await db.Set<ApplicationCredential>().Where(c=>c.ApplicationId!=s.TargetApplicationId).Select(c=>c.Id).ToArrayAsync();Assert.DoesNotContain(candidate.Applications.SelectMany(a=>a.Credentials),c=>sourceIds.Contains(c.Id));}
 [Theory][InlineData("credential")][InlineData("authorization")][InlineData("application")]
 public async Task ForeignTargetCredentialSelectionIsRejected(string change)
 {await using var s=new PromotionScenario();await s.InitializeAsync();var request=s.Mapping();var app=request.Applications[0];app=change switch{"credential"=>app with{CredentialIds=[Guid.NewGuid()]},"authorization"=>app with{AuthorizationIds=[Guid.NewGuid()]},_=>app with{ApplicationId=Guid.NewGuid()}};using var response=await s.SaveAsync(request with{Applications=[app]});Assert.Equal(HttpStatusCode.UnprocessableEntity,response.StatusCode);}
 [Theory][InlineData(false,false)][InlineData(true,false)]
 public async Task SharedApplicationRequiresAllBaselineCredentialsAndExplicitAcknowledgement(bool allCredentials,bool confirmed)
 {await using var s=new PromotionScenario();await s.InitializeAsync();var retained=await s.SeedRetainedBusinessAsync();var request=s.Mapping();request=request with{Applications=[request.Applications[0] with{CredentialIds=allCredentials?[s.TargetCredentialId,retained.CredentialId]:[s.TargetCredentialId],ConfirmSharedCredentialImpact=confirmed}]};using var saved=await s.SaveAsync(request);saved.EnsureSuccessStatusCode();var error=await Assert.ThrowsAsync<WebApi.Contracts.Common.ApiException>(()=>s.PrepareAsync());Assert.Equal(409,error.Status);}
 [Fact] public async Task ExplicitSharedSelectionPreservesUnselectedRouteAndAuthorization()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var retained=await s.SeedRetainedBusinessAsync();var request=s.Mapping();using var saved=await s.SaveAsync(request with{Applications=[request.Applications[0] with{CredentialIds=[s.TargetCredentialId,retained.CredentialId],ConfirmSharedCredentialImpact=true}]});saved.EnsureSuccessStatusCode();var candidate=await s.PrepareAsync();var app=Assert.Single(candidate.Applications);Assert.Contains(app.Permissions,p=>p.ApiId==retained.ApiId);Assert.Equal(2,app.Credentials.Count);using var services=s.Api.Services();var baseline=await services.ServiceProvider.GetRequiredService<WebApi.Infrastructure.Releases.HistoricalSnapshotService>().ReadAsync(s.TargetEnvironmentId,1);var compiled=services.ServiceProvider.GetRequiredService<WebApi.Infrastructure.Releases.SnapshotCompiler>().Compile(candidate,baseline.Snapshot,2,DateTimeOffset.UtcNow);var runtime=WebApi.Domain.Runtime.SnapshotValidator.ParsePayload(compiled.Payload.Span,s.TargetEnvironmentId);Assert.Contains(runtime.Routes,r=>r.ApiId==retained.ApiId&&r.Path=="/retained");Assert.Contains(Assert.Single(runtime.Applications).Permissions,p=>p.ApiId==retained.ApiId);}
 [Theory][InlineData(false)][InlineData(true)]
 public async Task CrossEnvironmentSharedApplicationRequiresExplicitConfirmation(bool confirmed)
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){db.Add(new ApplicationApiPermission{ApplicationId=s.TargetApplicationId,ApiId=s.Api.Api.Id,EnvironmentId=s.Api.Environment.Id,CreatedBy=s.Api.User.Id,ValidFrom=DateTimeOffset.UtcNow.AddMinutes(-1)});await db.SaveChangesAsync();}var request=s.Mapping();using var saved=await s.SaveAsync(request with{Applications=[request.Applications[0] with{ConfirmSharedCredentialImpact=confirmed}]});saved.EnsureSuccessStatusCode();if(confirmed){var candidate=await s.PrepareAsync();Assert.Single(candidate.Applications);var json=System.Text.Json.JsonSerializer.SerializeToElement(candidate,WebApi.Contracts.Common.CanonicalJson.Options);Assert.True(json.TryGetProperty("sharedCredentialImpact",out var impacts));Assert.Contains(impacts.EnumerateArray(),impact=>impact.GetProperty("applicationId").GetGuid()==s.TargetApplicationId&&impact.GetProperty("sharedAcrossEnvironments").GetBoolean()&&impact.GetProperty("acknowledged").GetBoolean());}else Assert.Equal(409,(await Assert.ThrowsAsync<WebApi.Contracts.Common.ApiException>(()=>s.PrepareAsync())).Status);}
 [Theory][InlineData(true)][InlineData(false)]
 public async Task OrganizationWideApplicationIsEligibleButAnotherProjectIsNot(bool organizationWide)
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){Guid? project=null;if(!organizationWide){var other=new Project{OrganizationId=s.Api.Organization.Id,Code="OTHER",Name="其他项目"};db.Add(other);project=other.Id;}var app=await db.Set<ApplicationRecord>().SingleAsync(a=>a.Id==s.TargetApplicationId);app.ProjectId=project;await db.SaveChangesAsync();}using var saved=await s.SaveAsync(s.Mapping());if(organizationWide){saved.EnsureSuccessStatusCode();var candidate=await s.PrepareAsync();Assert.Null(Assert.Single(candidate.Applications).Application.ProjectId);}else Assert.Equal(HttpStatusCode.UnprocessableEntity,saved.StatusCode);}
 [Fact] public async Task PureJwtTargetApplicationWithNoApiKeyCanMapAndCompile()
 {await using var s=new PromotionScenario();await s.InitializeAsync(configureSourceAuthentication:async api=>{await using var db=api.Context();var route=await db.Set<ApiRoute>().SingleAsync();var policy=new Policy{OrganizationId=api.Organization.Id,ProjectId=api.Project.Id,Name="Source JWT",Type="authentication",Config=JwtApplicationBindingTests.Jwt(api.Application.Id)};foreach(var node in await db.Set<GatewayNode>().ToArrayAsync())node.Metadata=WebApi.Infrastructure.Gateway.SnapshotSchemaCapabilities.Merge(null,Guid.Parse(node.InstanceId),["2.0","2.1","2.2"]);db.Add(policy);db.Add(new RoutePolicyBinding{RouteId=route.Id,PolicyId=policy.Id,Priority=0});await db.SaveChangesAsync();});await using(var db=s.Api.Context()){await db.Set<ApplicationCredential>().Where(c=>c.ApplicationId==s.TargetApplicationId).ExecuteDeleteAsync();var policy=new Policy{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,Name="Target JWT",Type="authentication",Config=JwtApplicationBindingTests.Jwt(s.TargetApplicationId,"https://prod-issuer.example/realm")};db.Add(policy);s.TargetPolicyId=policy.Id;await db.SaveChangesAsync();}var request=s.Mapping();using var saved=await s.SaveAsync(request with{Applications=[request.Applications[0] with{CredentialIds=[]}]});saved.EnsureSuccessStatusCode();var candidate=await s.PrepareAsync();var app=Assert.Single(candidate.Applications);Assert.Empty(app.Credentials);Assert.Equal(s.TargetAuthorizationId,Assert.Single(app.Permissions).Id);Assert.Equal("JWT",Assert.Single(candidate.Routes).EffectiveAuthenticationMode);using var services=s.Api.Services();var compiled=services.ServiceProvider.GetRequiredService<WebApi.Infrastructure.Releases.SnapshotCompiler>().Compile(candidate,new WebApi.Contracts.Runtime.RuntimeSnapshot("2.0",s.TargetEnvironmentId,0,DateTimeOffset.UtcNow,[],[],[],[]),1,DateTimeOffset.UtcNow);var runtime=WebApi.Domain.Runtime.SnapshotValidator.ParsePayload(compiled.Payload.Span,s.TargetEnvironmentId);Assert.Empty(Assert.Single(runtime.Applications).Credentials);Assert.Equal(WebApi.Contracts.Policies.AuthenticationMode.JWT,Assert.Single(runtime.Routes).AuthenticationMode);}
 [Fact] public async Task ApiKeyTargetRouteStillRequiresAnExplicitValidCredential()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var request=s.Mapping();using var saved=await s.SaveAsync(request with{Applications=[request.Applications[0] with{CredentialIds=[]}]});Assert.Equal(HttpStatusCode.UnprocessableEntity,saved.StatusCode);}

}
