using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Gateway;
using WebApi.Infrastructure.Delivery;
using WebApi.Contracts.Common;
using WebApi.Worker;
using Microsoft.Extensions.Logging;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PromotionExecutionTests
{
 internal static async Task<PromotionDto> Ready(PromotionScenario s)
 {var p=await PromotionSubmissionTests.Submitted(s);foreach(var role in new[]{"ApiApprover","SecurityReviewer"}){var reviewer=await s.NewProductionApproverAsync(role);using var approved=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{p.TargetReleaseId}/approve",new{comment="生产独立审批"});approved.EnsureSuccessStatusCode();}return p;}
 internal static Task<HttpResponseMessage> Start(PromotionScenario s,Guid release)=>ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{release}/publish");
 internal static async Task Change(PromotionScenario s,string change)
 {await using var db=s.Api.Context();switch(change){case "private-share":var policy=await db.Set<RoutePolicyBinding>().Where(b=>db.Set<ApiRoute>().Any(r=>r.Id==b.RouteId&&r.EnvironmentId==s.TargetEnvironmentId)).Select(b=>b.PolicyId).FirstAsync();var other=new ApiRoute{EnvironmentId=s.TargetEnvironmentId,ApiVersionId=s.Api.Version.Id,Path="/other-working-route",NormalizedPath="/other-working-route",Methods=["GET"],ClusterId=s.TargetClusterId,TimeoutMs=30000};db.Add(other);db.Add(new RoutePolicyBinding{RouteId=other.Id,PolicyId=policy,Priority=7});await db.SaveChangesAsync();break;case "cluster":await db.Set<UpstreamCluster>().Where(c=>c.Id==s.TargetClusterId).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Revision,2));break;case "destination":await db.Set<UpstreamDestination>().Where(d=>d.ClusterId==s.TargetClusterId).ExecuteUpdateAsync(x=>x.SetProperty(d=>d.Address,"http://different-backend:8080/").SetProperty(d=>d.Revision,2));break;case "credential":await db.Set<ApplicationCredential>().Where(c=>c.Id==s.TargetCredentialId).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Status,"Revoked").SetProperty(c=>c.Revision,2));break;case "binding":await db.Set<RoutePolicyBinding>().Where(b=>db.Set<ApiRoute>().Any(r=>r.Id==b.RouteId&&r.EnvironmentId==s.TargetEnvironmentId)).ExecuteDeleteAsync();break;case "entry":await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.AccessAddressRevision,2));break;case "identity":await db.Set<UserRole>().Where(r=>r.UserId==s.Api.User.Id).ExecuteDeleteAsync();break;case "expired":await db.Set<ReleaseVerification>().ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));break;case "revoked":await db.Set<ReleaseTestAcceptance>().ExecuteUpdateAsync(x=>x.SetProperty(a=>a.Status,"Revoked"));break;}}
 [Theory][InlineData("cluster")][InlineData("destination")][InlineData("credential")][InlineData("binding")][InlineData("entry")][InlineData("identity")][InlineData("private-share")]
 public async Task ReadyCannotStartAfterFrozenPreconditionsChange(string change)
 {await using var s=new PromotionScenario();await s.InitializeAsync(timeout:true,authenticatedTargetReceipts:true);var p=await Ready(s);await Change(s,change);using var started=await Start(s,p.TargetReleaseId!.Value);Assert.False(started.IsSuccessStatusCode);await using var db=s.Api.Context();Assert.Equal("Ready",(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);Assert.False(await db.Set<OutboxMessage>().AnyAsync(m=>m.ReleaseId==p.TargetReleaseId));}
 [Theory][InlineData("revoked")][InlineData("expired")][InlineData("credential")][InlineData("entry")][InlineData("identity")]
 public async Task QueuedBuildRechecksAfterFreshServiceScope(string change)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);using(var started=await Start(s,p.TargetReleaseId!.Value))started.EnsureSuccessStatusCode();await Change(s,change);await s.Source.Deployment.BuildQueuedAsync();await using var db=s.Api.Context();var r=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);Assert.Equal("Failed",r.Status);Assert.Equal("DeploymentFailed",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal(1L,(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).DesiredConfigVersion);Assert.False(await db.Set<OutboxMessage>().AnyAsync(m=>m.ReleaseId==r.Id));}
 [Fact] public async Task AllAuthenticatedReceiptsMeanVerifyingAndNotBusinessCompletion()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);using(var started=await Start(s,p.TargetReleaseId!.Value))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(p.TargetReleaseId.Value);await using var db=s.Api.Context();Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status);var current=await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id);Assert.Equal("Verifying",current.Status);Assert.Null(current.CompletedAt);Assert.Contains(await db.Set<ReleasePromotionEvent>().Where(e=>e.PromotionId==p.Id).ToArrayAsync(),e=>e.Phase=="Deployment"&&e.ToStatus=="Verifying");}
 [Theory][InlineData(false)][InlineData(true)]
 public async Task PartialReceiptsAndFailurePersistAndRetryUsesSameSnapshot(bool timeout)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);using(var started=await Start(s,p.TargetReleaseId!.Value))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();using(var first=await s.TargetAckAsync(p.TargetReleaseId.Value,0))first.EnsureSuccessStatusCode();if(timeout){await using(var db=s.Api.Context())await db.Set<ReleaseRecord>().Where(r=>r.Id==p.TargetReleaseId).ExecuteUpdateAsync(x=>x.SetProperty(r=>r.DeadlineAt,DateTimeOffset.UtcNow.AddSeconds(-1)));using var scope=s.Api.Services();Assert.Equal(1,await scope.ServiceProvider.GetRequiredService<ReleaseTimeoutService>().ExpireAsync());}else{using var failed=await s.TargetAckAsync(p.TargetReleaseId.Value,1,false);failed.EnsureSuccessStatusCode();}
 using(var view=await s.Api.Client.GetAsync($"/api/v1/release-promotions/{p.Id}")){view.EnsureSuccessStatusCode();var dto=(await view.Content.ReadFromJsonAsync<PromotionDto>())!;Assert.NotNull(dto.Deployment);Assert.Contains(dto.Deployment.Nodes,n=>n.NodeId==s.TargetNodeIds[0]&&n.ConfigVersion==2);Assert.Contains(dto.Deployment.Nodes,n=>n.NodeId==s.TargetNodeIds[1]&&n.ConfigVersion==1);}
 await using(var db=s.Api.Context()){Assert.Equal("DeploymentFailed",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal(2L,(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.TargetNodeIds[0])).CurrentConfigVersion);Assert.Equal(1L,(await db.Set<GatewayNode>().SingleAsync(n=>n.Id==s.TargetNodeIds[1])).CurrentConfigVersion);}
 using var retried=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{p.TargetReleaseId}/retry");retried.EnsureSuccessStatusCode();var recovery=(await retried.Content.ReadFromJsonAsync<ReleaseDto>())!;await s.Source.Deployment.BuildQueuedAsync();await using(var db=s.Api.Context()){var retry=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==recovery.Id);var original=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId);Assert.Null(retry.PromotionId);Assert.Equal(original.Id,retry.RecoveryOf);Assert.Equal(original.ArtifactId,retry.ArtifactId);Assert.Equal(original.SourceReleaseId,retry.SourceReleaseId);Assert.Equal(original.ToConfigVersion,retry.ToConfigVersion);Assert.True(retry.DeploymentSequence>original.DeploymentSequence);Assert.Equal(original.CandidateBytes,retry.CandidateBytes);}
 using(var late=await s.TargetAckAsync(p.TargetReleaseId.Value,0))Assert.Equal(HttpStatusCode.Conflict,late.StatusCode);await s.TargetAckAllAsync(recovery.Id);await using(var db=s.Api.Context()){Assert.Equal("Verifying",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);Assert.Equal(p.TargetReleaseId,(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).TargetReleaseId);Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync(r=>r.PromotionId==p.Id));}}

 [Theory][InlineData(false)][InlineData(true)]
 public async Task NewWorkerHostAndControlPlaneRestartUsePersistedQueue(bool revoke)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);using(var stopped=WorkerApp.Build(["--environment","Development"],b=>{b.Configuration["ConnectionStrings:WebApi"]=s.Api.Database.ConnectionString;b.Configuration["Redis:Prefix"]="stopped-promotion:"+Guid.NewGuid();b.Logging.ClearProviders();})){await stopped.StartAsync();await stopped.StopAsync();}using(var started=await Start(s,p.TargetReleaseId!.Value))started.EnsureSuccessStatusCode();await s.Api.RestartServerAsync();if(revoke)await Change(s,"revoked");using var worker=WorkerApp.Build(["--environment","Development"],b=>{b.Configuration["ConnectionStrings:WebApi"]=s.Api.Database.ConnectionString;b.Configuration["Redis:Prefix"]="promotion-restart:"+Guid.NewGuid();b.Logging.ClearProviders();});await worker.StartAsync();try{var until=DateTimeOffset.UtcNow.AddSeconds(12);var state="Building";while(DateTimeOffset.UtcNow<until&&state=="Building"){await using var db=s.Api.Context();state=(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==p.TargetReleaseId)).Status;if(state=="Building")await Task.Delay(100);}Assert.Equal(revoke?"Failed":"Publishing",state);}finally{await worker.StopAsync();}if(!revoke)await s.TargetAckAllAsync(p.TargetReleaseId.Value);await s.Api.RestartServerAsync();using var view=await s.Api.Client.GetAsync($"/api/v1/release-promotions/{p.Id}");view.EnsureSuccessStatusCode();Assert.Equal(revoke?"DeploymentFailed":"Verifying",(await view.Content.ReadFromJsonAsync<PromotionDto>())!.Status);}
 [Theory][InlineData("cycle")][InlineData("foreign")]
 public async Task RecoveryResolverRejectsCyclesAndCrossEnvironmentLinks(string invalid)
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);Guid id;await using(var db=s.Api.Context()){var record=new ReleaseRecord{EnvironmentId=invalid=="foreign"?s.Api.Environment.Id:s.TargetEnvironmentId,ReleaseNo="invalid-chain",ReleaseType="retry",Status="Failed",RequestedBy=s.Api.User.Id};id=record.Id;record.RecoveryOf=invalid=="cycle"?record.Id:p.TargetReleaseId;db.Add(record);await db.SaveChangesAsync();}using var scope=s.Api.Services();var error=await Assert.ThrowsAsync<ApiException>(()=>scope.ServiceProvider.GetRequiredService<PromotionReadService>().ResolvePromotionAsync(id,CancellationToken.None));Assert.Equal("invalid_delivery_recovery_chain",error.Code);}
 [Fact] public async Task FailedRollbackRetryStaysRollbackRatherThanVerifyingOriginalDelivery()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);using(var started=await Start(s,p.TargetReleaseId!.Value))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(p.TargetReleaseId.Value);using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{p.TargetReleaseId}/rollback",new{targetConfigVersion=1L});created.EnsureSuccessStatusCode();var rollback=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;using(var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{rollback}/submit"))submitted.EnsureSuccessStatusCode();await s.Source.Deployment.ApproveAsync(rollback);using(var started=await Start(s,rollback))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();using(var first=await s.TargetAckAsync(rollback,0))first.EnsureSuccessStatusCode();using(var failure=await s.TargetAckAsync(rollback,1,false))failure.EnsureSuccessStatusCode();using var retryResponse=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{rollback}/retry");retryResponse.EnsureSuccessStatusCode();var retry=(await retryResponse.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(retry);await using var db=s.Api.Context();Assert.Equal("RolledBack",(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Status);}
 [Fact] public async Task SamePublishCommandReplaysAfterDeploymentWithoutNewSequence()
 {await using var s=new PromotionScenario();await s.InitializeAsync(authenticatedTargetReceipts:true);var p=await Ready(s);var key=Guid.NewGuid().ToString("N");using(var started=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{p.TargetReleaseId}/publish",key:key))started.EnsureSuccessStatusCode();await s.Source.Deployment.BuildQueuedAsync();await s.TargetAckAllAsync(p.TargetReleaseId!.Value);long revision;await using(var db=s.Api.Context())revision=(await db.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Revision;using var replay=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{p.TargetReleaseId}/publish",key:key);replay.EnsureSuccessStatusCode();await using var current=s.Api.Context();Assert.Equal(2L,(await current.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).DeploymentSequence);Assert.Equal(revision,(await current.Set<ReleasePromotion>().SingleAsync(x=>x.Id==p.Id)).Revision);Assert.Equal(1,await current.Set<OutboxMessage>().CountAsync(m=>m.ReleaseId==p.TargetReleaseId));}
}
