using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PromotionSubmissionTests
{
 internal static async Task<HttpResponseMessage> Send(PromotionScenario s,string action,object? body=null,string? etag=null,string? key=null)
 {using var request=new HttpRequestMessage(HttpMethod.Post,$"/api/v1/release-promotions/{s.PromotionId}/{action}"){Content=JsonContent.Create(body??new{})};request.Headers.Add("X-CSRF-Token",await s.Api.CsrfAsync());request.Headers.Add("Idempotency-Key",key??Guid.NewGuid().ToString("N"));if(etag is not null)request.Headers.Add("If-Match",etag);return await s.Api.Client.SendAsync(request);}
 internal static async Task<PromotionDto> Create(PromotionScenario s,string? key=null)
 {using var response=await ApiFixture.CommandAsync(s.Api.Client,"/api/v1/release-promotions",new CreatePromotionRequest(s.Source.Artifact.Id),key);response.EnsureSuccessStatusCode();var dto=(await response.Content.ReadFromJsonAsync<PromotionDto>())!;s.PromotionId=dto.Id;return dto;}
 internal static async Task<PromotionPrecheckDto> Prepared(PromotionScenario s)
 {await s.SeedProductionBaselineAsync();await Create(s);await using(var db=s.Api.Context()){var route=await db.Set<ApiRoute>().SingleAsync(r=>r.EnvironmentId==s.TargetEnvironmentId);using var saved=await s.SaveAsync(s.Mapping(route.Id));saved.EnsureSuccessStatusCode();}using var response=await Send(s,"precheck",new PromotionPrecheckRequest(ConfirmUpstreamHealth:true,UpstreamHealthComment:"人工确认目标后端与依赖已准备就绪，等待独立生产审批"));response.EnsureSuccessStatusCode();var result=(await response.Content.ReadFromJsonAsync<PromotionPrecheckDto>())!;Assert.True(result.CanSubmit);return result;}
 [Fact] public async Task CreateUsesConfiguredFixedTargetAndAcceptedArtifact()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var dto=await Create(s);Assert.Equal("Draft",dto.Status);Assert.Equal(s.Source.Artifact.Id,dto.ArtifactId);Assert.Equal(s.TargetEnvironmentId,dto.TargetEnvironmentId);Assert.NotNull(dto.AcceptanceId);Assert.Null(dto.TargetReleaseId);}
 [Theory][InlineData("missing")][InlineData("revoked")][InlineData("expired")][InlineData("sequence")]
 public async Task InvalidAcceptanceOrSourceCannotCreatePromotion(string invalid)
 {await using var s=new PromotionScenario();await s.InitializeAsync();await using(var db=s.Api.Context()){if(invalid=="missing")await db.Set<ReleaseTestAcceptance>().ExecuteUpdateAsync(x=>x.SetProperty(a=>a.Status,"Rejected"));if(invalid=="revoked")await db.Set<ReleaseTestAcceptance>().ExecuteUpdateAsync(x=>x.SetProperty(a=>a.Status,"Revoked"));if(invalid=="expired")await db.Set<ReleaseVerification>().ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));if(invalid=="sequence")await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.Api.Environment.Id).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.DeploymentSequence,99));}using var response=await ApiFixture.CommandAsync(s.Api.Client,"/api/v1/release-promotions",new CreatePromotionRequest(s.Source.Artifact.Id));Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
 [Fact] public async Task PrecheckStoresTypedUnknownInsteadOfPretendingUpstreamHealthPassed()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await Create(s);using(var saved=await s.SaveAsync(s.Mapping()))saved.EnsureSuccessStatusCode();using var response=await Send(s,"precheck",new PromotionPrecheckRequest());response.EnsureSuccessStatusCode();var result=(await response.Content.ReadFromJsonAsync<PromotionPrecheckDto>())!;Assert.False(result.CanSubmit);Assert.Contains(result.Checks,c=>c.Key=="upstream_health"&&c.Status=="Unknown"&&c.Blocking);await using var db=s.Api.Context();Assert.NotNull((await db.Set<ReleasePromotion>().SingleAsync(p=>p.Id==s.PromotionId)).PrecheckJson);Assert.Null((await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).DesiredConfigVersion);}
 [Fact] public async Task SubmitFreezesOneFormalReleaseAndExistingTwoLevelApproval()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await Prepared(s);using var response=await Send(s,"submit",etag:$"\"{prepared.Revision}\"");response.EnsureSuccessStatusCode();var dto=(await response.Content.ReadFromJsonAsync<PromotionDto>())!;Assert.Equal("WaitingApproval",dto.Status);Assert.NotNull(dto.TargetReleaseId);await using var db=s.Api.Context();var release=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==dto.TargetReleaseId);Assert.Equal(dto.Id,release.PromotionId);Assert.Equal(dto.ArtifactId,release.ArtifactId);Assert.Equal(dto.SourceReleaseId,release.SourceReleaseId);Assert.Equal("WaitingApproval",release.Status);Assert.NotNull(release.ApprovalPolicy);Assert.Equal(2,await db.Set<ApprovalTask>().CountAsync(t=>t.ReleaseId==release.Id));Assert.Equal(1L,(await db.Set<EnvironmentRecord>().SingleAsync(e=>e.Id==s.TargetEnvironmentId)).DesiredConfigVersion);Assert.DoesNotContain(await db.Set<OutboxMessage>().ToArrayAsync(),m=>m.ReleaseId==release.Id);}
 [Theory][InlineData("entry")][InlineData("baseline")][InlineData("policy")][InlineData("mapping")][InlineData("cluster")][InlineData("acceptance")]
 public async Task ChangedPreconditionsCannotReuseOldPrecheck(string changed)
 {await using var s=new PromotionScenario();await s.InitializeAsync();var prepared=await Prepared(s);await using(var db=s.Api.Context()){if(changed=="baseline")await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.DesiredConfigVersion,2));if(changed=="entry")await db.Set<EnvironmentRecord>().Where(e=>e.Id==s.TargetEnvironmentId).ExecuteUpdateAsync(x=>x.SetProperty(e=>e.AccessAddressRevision,2));if(changed=="policy")await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Revision,2));if(changed=="mapping")await db.Set<ReleasePromotion>().Where(p=>p.Id==s.PromotionId).ExecuteUpdateAsync(x=>x.SetProperty(p=>p.MappingRevision,9));if(changed=="cluster")await db.Set<UpstreamCluster>().Where(c=>c.Id==s.TargetClusterId).ExecuteUpdateAsync(x=>x.SetProperty(c=>c.Revision,2));if(changed=="acceptance")await db.Set<ReleaseTestAcceptance>().ExecuteUpdateAsync(x=>x.SetProperty(a=>a.Status,"Revoked"));}using var response=await Send(s,"submit",etag:$"\"{prepared.Revision}\"");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var context=s.Api.Context();Assert.False(await context.Set<ReleaseRecord>().AnyAsync(r=>r.PromotionId==s.PromotionId));}
 [Fact] public async Task PromotionRequiredRejectsProductionDirectCreateIncludingForgedLink()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using(var mapped=await s.SaveAsync(s.Mapping()))mapped.EnsureSuccessStatusCode();await s.PrepareAsync();var request=await s.Api.PreviewReleaseRequestAsync(0,s.Api.Version.Id,s.TargetEnvironmentId);using var response=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",request);Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);using var forged=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",new{request.BaseConfigVersion,request.VersionIds,request.ResourceRevisions,promotionId=s.PromotionId});Assert.Equal(HttpStatusCode.Conflict,forged.StatusCode);}
 [Fact] public async Task LegacyProjectStillAllowsNormalProductionRelease()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using(var mapped=await s.SaveAsync(s.Mapping()))mapped.EnsureSuccessStatusCode();await s.PrepareAsync();await using(var db=s.Api.Context())await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Mode,"Legacy"));var request=await s.Api.PreviewReleaseRequestAsync(0,s.Api.Version.Id,s.TargetEnvironmentId);using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",request);created.EnsureSuccessStatusCode();var id=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;using var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit");submitted.EnsureSuccessStatusCode();Assert.Equal("WaitingApproval",(await submitted.Content.ReadFromJsonAsync<ReleaseDto>())!.State);}
 [Fact] public async Task OrdinaryDraftCannotSubmitAfterPromotionModeEnabled()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using(var mapped=await s.SaveAsync(s.Mapping()))mapped.EnsureSuccessStatusCode();await s.PrepareAsync();await using(var db=s.Api.Context())await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Mode,"Legacy"));var request=await s.Api.PreviewReleaseRequestAsync(0,s.Api.Version.Id,s.TargetEnvironmentId);using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",request);created.EnsureSuccessStatusCode();var id=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;await using(var db=s.Api.Context())await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Mode,"PromotionRequired"));using var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit");Assert.Equal(HttpStatusCode.Conflict,submitted.StatusCode);}
 [Fact] public async Task OrdinaryReadyReleaseCannotExecuteAfterPromotionModeEnabled()
 {await using var s=new PromotionScenario();await s.InitializeAsync();using(var mapped=await s.SaveAsync(s.Mapping()))mapped.EnsureSuccessStatusCode();await s.PrepareAsync();await using(var db=s.Api.Context())await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Mode,"Legacy"));var request=await s.Api.PreviewReleaseRequestAsync(0,s.Api.Version.Id,s.TargetEnvironmentId);using var created=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/environments/{s.TargetEnvironmentId}/releases",request);created.EnsureSuccessStatusCode();var id=(await created.Content.ReadFromJsonAsync<ReleaseDto>())!.Id;using(var submitted=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit"))submitted.EnsureSuccessStatusCode();await s.Source.Deployment.ApproveAsync(id);await using(var db=s.Api.Context())await db.Set<ProjectDeliveryPolicy>().ExecuteUpdateAsync(x=>x.SetProperty(p=>p.Mode,"PromotionRequired"));using var publish=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,publish.StatusCode);await using var context=s.Api.Context();Assert.Equal("Ready",(await context.Set<ReleaseRecord>().SingleAsync(r=>r.Id==id)).Status);Assert.DoesNotContain(await context.Set<OutboxMessage>().ToArrayAsync(),m=>m.ReleaseId==id);}
 internal static async Task<PromotionDto> Submitted(PromotionScenario s)
 {var precheck=await Prepared(s);using var response=await Send(s,"submit",etag:$"\"{precheck.Revision}\"");response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<PromotionDto>())!;}
 [Fact] public async Task ApprovalCannotProceedAfterAcceptedSourceEvidenceExpires()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var promotion=await Submitted(s);var reviewer=await s.NewProductionApproverAsync("ApiApprover");await using(var db=s.Api.Context())await db.Set<ReleaseVerification>().ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));using var approval=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{promotion.TargetReleaseId}/approve",new{comment="验收失效不应批准"});Assert.Equal(HttpStatusCode.Conflict,approval.StatusCode);await using var context=s.Api.Context();Assert.False(await context.Set<ApprovalTask>().AnyAsync(t=>t.ReleaseId==promotion.TargetReleaseId&&t.Status=="Approved"));}
 [Fact] public async Task ExistingApprovalProjectsPromotionReadyWithoutParallelApprovalSeats()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var promotion=await Submitted(s);foreach(var role in new[]{"ApiApprover","SecurityReviewer"}){var reviewer=await s.NewProductionApproverAsync(role);using var approved=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{promotion.TargetReleaseId}/approve",new{comment="独立生产审批"});approved.EnsureSuccessStatusCode();}using var current=await s.Api.Client.GetAsync($"/api/v1/release-promotions/{promotion.Id}");current.EnsureSuccessStatusCode();Assert.Equal("Ready",(await current.Content.ReadFromJsonAsync<PromotionDto>())!.Status);await using var db=s.Api.Context();Assert.Equal(2,await db.Set<ApprovalTask>().CountAsync(t=>t.ReleaseId==promotion.TargetReleaseId));}
 [Fact] public async Task ProductionApprovalRequiresSourceContractVisibility()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var promotion=await Submitted(s);var reviewer=await s.NewProductionApproverAsync("ApiApprover",false);using var approval=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{promotion.TargetReleaseId}/approve",new{comment="不可见测试制品不能批准"});Assert.Equal(HttpStatusCode.NotFound,approval.StatusCode);}
 [Fact] public async Task ExpiredAcceptedEvidenceStillAllowsIndependentRejection()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var promotion=await Submitted(s);var reviewer=await s.NewProductionApproverAsync("ApiApprover");await using(var db=s.Api.Context())await db.Set<ReleaseVerification>().ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));using var rejected=await ApiFixture.CommandAsync(reviewer.Client,$"/api/v1/releases/{promotion.TargetReleaseId}/reject",new{comment="来源验收已过期，拒绝该生产申请"});rejected.EnsureSuccessStatusCode();await using var context=s.Api.Context();Assert.Equal("Rejected",(await context.Set<ReleasePromotion>().SingleAsync(p=>p.Id==promotion.Id)).Status);Assert.All(await context.Set<ReleaseVerification>().ToArrayAsync(),v=>Assert.Equal("Passed",v.Result));}
 [Fact] public async Task PrecheckAuditContainsSafeCandidateHashWithoutManualCommentOrCredential()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var precheck=await Prepared(s);await using var db=s.Api.Context();var audit=await db.Set<AuditLog>().SingleAsync(a=>a.Action=="promotion.precheck");Assert.Contains(precheck.CandidateHash!,audit.AfterJson);Assert.DoesNotContain("人工确认目标后端",audit.AfterJson);var credential=await db.Set<ApplicationCredential>().SingleAsync(c=>c.Id==s.TargetCredentialId);Assert.DoesNotContain(credential.SecretHash,audit.AfterJson);Assert.DoesNotContain(credential.AccessKey,audit.AfterJson);}
 [Fact] public async Task MissingExactBaselineComparisonStaysBlockingUnknown()
 {await using var s=new PromotionScenario();await s.InitializeAsync();Guid old;await using(var db=s.Api.Context()){var version=new ApiVersion{ApiId=s.Api.Api.Id,Version="0.9.0",Status="Published",CreatedBy=s.Api.User.Id,SealedAt=DateTimeOffset.UtcNow};old=version.Id;db.Add(version);await db.SaveChangesAsync();}await s.SeedProductionBaselineAsync(old);await Create(s);Guid route;await using(var db=s.Api.Context())route=(await db.Set<ApiRoute>().SingleAsync(r=>r.EnvironmentId==s.TargetEnvironmentId)).Id;using(var mapped=await s.SaveAsync(s.Mapping(route)))mapped.EnsureSuccessStatusCode();using var response=await Send(s,"precheck",new PromotionPrecheckRequest(ConfirmUpstreamHealth:true,UpstreamHealthComment:"人工確認目标后端及依赖已准备就绪，兼容性报告尚待补齐"));response.EnsureSuccessStatusCode();var result=(await response.Content.ReadFromJsonAsync<PromotionPrecheckDto>())!;Assert.False(result.CanSubmit);Assert.Contains(result.Checks,c=>c.Key.StartsWith("contract:")&&c.Status=="Unknown"&&c.Blocking&&c.ReasonCode=="baseline_comparison_required");using var submit=await Send(s,"submit",etag:$"\"{result.Revision}\"");Assert.Equal(HttpStatusCode.Conflict,submit.StatusCode);}
}
