using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class PromotionConcurrencyTests
{
 [Fact] public async Task ConcurrentSameKeySubmitCreatesExactlyOneReleaseAndApprovalCohort()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var precheck=await PromotionSubmissionTests.Prepared(s);var key=Guid.NewGuid().ToString("N");var results=await Task.WhenAll(Enumerable.Range(0,2).Select(_=>PromotionSubmissionTests.Send(s,"submit",etag:$"\"{precheck.Revision}\"",key:key)));try{foreach(var response in results)response.EnsureSuccessStatusCode();var ids=new List<Guid?>();foreach(var response in results)ids.Add((await response.Content.ReadFromJsonAsync<PromotionDto>())!.TargetReleaseId);Assert.Single(ids.Distinct());await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync(r=>r.PromotionId==s.PromotionId));Assert.Equal(2,await db.Set<ApprovalTask>().CountAsync(t=>t.ReleaseId==ids[0]));}finally{foreach(var r in results)r.Dispose();}}
 [Fact] public async Task DifferentKeysCompetingForSameDraftCannotCreateTwoFormalReleases()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var precheck=await PromotionSubmissionTests.Prepared(s);var results=await Task.WhenAll(Enumerable.Range(0,2).Select(_=>PromotionSubmissionTests.Send(s,"submit",etag:$"\"{precheck.Revision}\"")));try{Assert.Single(results,r=>r.IsSuccessStatusCode);Assert.Single(results,r=>r.StatusCode is HttpStatusCode.Conflict or HttpStatusCode.PreconditionFailed);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync(r=>r.PromotionId==s.PromotionId));}finally{foreach(var r in results)r.Dispose();}}
 [Fact] public async Task CreateIdempotencyReturnsOriginalIdButRejectsChangedArtifact()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var key=Guid.NewGuid().ToString("N");var first=await PromotionSubmissionTests.Create(s,key);var again=await PromotionSubmissionTests.Create(s,key);Assert.Equal(first.Id,again.Id);Guid alternateId;await using(var db=s.Api.Context()){var content=s.Source.Artifact.Content;content=content with{Routes=[content.Routes[0] with{Key="",Path="/alternate"}]};content=WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Normalize(content);var row=new ReleaseArtifact{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,SourceEnvironmentId=s.Api.Environment.Id,SourceReleaseId=s.Source.ReleaseId,CanonicalContent=System.Text.Encoding.UTF8.GetString(WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Serialize(content)),ArtifactHash=WebApi.Domain.Delivery.ReleaseArtifactCanonicalizer.Hash(content),SourceSnapshotHash=s.Source.Artifact.SourceSnapshotHash,CreatedBy=s.Api.User.Id};alternateId=row.Id;db.Add(row);await db.SaveChangesAsync();}using var changed=await ApiFixture.CommandAsync(s.Api.Client,"/api/v1/release-promotions",new CreatePromotionRequest(alternateId),key);Assert.Equal(HttpStatusCode.Conflict,changed.StatusCode);}
 [Fact] public async Task SubmitRevisionConflictDoesNotCreateReleaseOrApprovalTasks()
 {await using var s=new PromotionScenario();await s.InitializeAsync();await PromotionSubmissionTests.Prepared(s);using var result=await PromotionSubmissionTests.Send(s,"submit",etag:"\"0\"");Assert.Equal(HttpStatusCode.PreconditionFailed,result.StatusCode);await using var db=s.Api.Context();Assert.False(await db.Set<ReleaseRecord>().AnyAsync(r=>r.PromotionId==s.PromotionId));}
 [Fact] public async Task ConcurrentRevocationAndSubmitFinishWithoutDeadlockAndCannotLeaveUsableApproval()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var precheck=await PromotionSubmissionTests.Prepared(s);Guid acceptance;await using(var db=s.Api.Context())acceptance=(await db.Set<ReleasePromotion>().SingleAsync(p=>p.Id==s.PromotionId)).AcceptanceId!.Value;var csrf=await s.TestAcceptor.Client.GetFromJsonAsync<Dictionary<string,string>>("/api/v1/auth/csrf");using var request=new HttpRequestMessage(HttpMethod.Post,$"/api/v1/test-acceptances/{acceptance}/revoke"){Content=JsonContent.Create(new TestAcceptanceActionRequest("并发撤销测试验收"))};request.Headers.Add("X-CSRF-Token",csrf!["token"]);request.Headers.Add("If-Match","\"2\"");request.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString("N"));var submit=PromotionSubmissionTests.Send(s,"submit",etag:$"\"{precheck.Revision}\"");var revoke=s.TestAcceptor.Client.SendAsync(request);await Task.WhenAll(submit,revoke).WaitAsync(TimeSpan.FromSeconds(30));using var submitted=await submit;using var revoked=await revoke;revoked.EnsureSuccessStatusCode();Assert.True(submitted.IsSuccessStatusCode||submitted.StatusCode is HttpStatusCode.Conflict or HttpStatusCode.PreconditionFailed);await using var context=s.Api.Context();Assert.Equal("Revoked",(await context.Set<ReleaseTestAcceptance>().SingleAsync(a=>a.Id==acceptance)).Status);var p=await context.Set<ReleasePromotion>().SingleAsync(p=>p.Id==s.PromotionId);Assert.Equal("Invalidated",p.Status);if(p.TargetReleaseId is Guid release)Assert.Equal("Cancelled",(await context.Set<ReleaseRecord>().SingleAsync(r=>r.Id==release)).Status);Assert.DoesNotContain(await context.Set<OutboxMessage>().ToArrayAsync(),m=>m.ReleaseId==p.TargetReleaseId);}
 [Fact] public async Task ConcurrentPreparationAndSubmitSerializeWithoutDuplicatingRelease()
 {await using var s=new PromotionScenario();await s.InitializeAsync();var precheck=await PromotionSubmissionTests.Prepared(s);var preparing=PromotionSubmissionTests.Send(s,"precheck",new PromotionPrecheckRequest(ConfirmUpstreamHealth:true,UpstreamHealthComment:"人工确认目标后端与依赖已准备就绪，等待独立生产审批"));var submitting=PromotionSubmissionTests.Send(s,"submit",etag:$"\"{precheck.Revision}\"");await Task.WhenAll(preparing,submitting).WaitAsync(TimeSpan.FromSeconds(30));using var prepared=await preparing;using var submitted=await submitting;Assert.True(prepared.IsSuccessStatusCode||prepared.StatusCode==HttpStatusCode.Conflict);Assert.True(submitted.IsSuccessStatusCode||submitted.StatusCode is HttpStatusCode.PreconditionFailed or HttpStatusCode.Conflict);Assert.True(prepared.IsSuccessStatusCode||submitted.IsSuccessStatusCode);await using var db=s.Api.Context();var count=await db.Set<ReleaseRecord>().CountAsync(r=>r.PromotionId==s.PromotionId);Assert.Equal(submitted.IsSuccessStatusCode?1:0,count);Assert.DoesNotContain(await db.Set<OutboxMessage>().ToArrayAsync(),m=>m.EnvironmentId==s.TargetEnvironmentId);}
}
