using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Infrastructure.Runtime;
using WebApi.Infrastructure.Messaging;
using WebApi.Worker;
using WebApi.Contracts.Gateway;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Infrastructure.Gateway;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class RollbackTests
{
    private static async Task<Guid> CreateAsync(DeploymentScenario s,Guid original,long target=1,string? key=null)
    {using var result=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{original}/rollback",new {targetConfigVersion=target},key);result.EnsureSuccessStatusCode();return (await result.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();}
    [Fact] public async Task RollbackReusesExactHistoricalPayloadWithHigherSequence()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();var first=await s.PublishAsync();var old=await s.DesiredAsync(first);var second=await s.PublishAsync();var rollback=await CreateAsync(s,second);using var submit=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{rollback}/submit");submit.EnsureSuccessStatusCode();await s.ApproveAsync(rollback);await s.BuildAsync(rollback);var restored=await s.DesiredAsync(rollback);Assert.Equal(old.Payload,restored.Payload);Assert.Equal(old.Envelope.PayloadHash,restored.Envelope.PayloadHash);Assert.Equal(1,restored.Envelope.ConfigVersion);Assert.Equal(3,restored.Envelope.DeploymentSequence);await s.AckAllAsync(rollback);await using var db=s.Api.Context();Assert.Equal("RolledBack",(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==second)).Status);Assert.Equal(2,await db.Set<GatewayConfigVersion>().CountAsync());Assert.Equal(rollback,(await db.Set<ReleaseRecord>().SingleAsync(r=>r.ReleaseType=="rollback")).Id);}
    [Fact] public async Task RollbackRequiresIndependentApproval()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var second=await s.PublishAsync();var id=await CreateAsync(s,second);using var early=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,early.StatusCode);using var submit=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit");submit.EnsureSuccessStatusCode();using var self=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/approve",new {comment="自批"});Assert.Equal(HttpStatusCode.Forbidden,self.StatusCode);using var unapproved=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");Assert.Equal(HttpStatusCode.Conflict,unapproved.StatusCode);await using var db=s.Api.Context();Assert.Equal(2,(await db.Set<EnvironmentRecord>().SingleAsync()).DeploymentSequence);}
    [Fact] public async Task DuplicateRollbackIsIdempotent()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var second=await s.PublishAsync();var key=Guid.NewGuid().ToString("N");var first=await CreateAsync(s,second,key:key);var duplicate=await CreateAsync(s,second,key:key);Assert.Equal(first,duplicate);using var changed=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{second}/rollback",new {targetConfigVersion=2L},key);Assert.Equal(HttpStatusCode.Conflict,changed.StatusCode);await using var db=s.Api.Context();Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync(r=>r.ReleaseType=="rollback"));Assert.Equal(1,await db.Set<AuditLog>().CountAsync(a=>a.Action=="release.rollback.create"));}
    [Fact] public async Task OldNormalPublishEventCannotUndoRollback()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var second=await s.PublishAsync();var id=await CreateAsync(s,second);using var submit=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/submit");submit.EnsureSuccessStatusCode();await s.ApproveAsync(id);await s.BuildAsync(id);using var redis=new RedisSnapshotStore("redis:6379","test:"+Guid.NewGuid());await using var db=s.Api.Context();var dispatcher=new OutboxDispatcher(db,redis);await dispatcher.ReconcileDesiredAsync();for(var i=0;i<3;i++) Assert.True(await dispatcher.DispatchNextAsync());var desired=(await redis.GetDesiredAsync(s.Api.Environment.Id))!;Assert.Equal(id,desired.Envelope.ReleaseId);Assert.Equal(1,desired.Envelope.ConfigVersion);Assert.Equal(3,desired.Envelope.DeploymentSequence);}
    [Fact] public async Task RevokedScopeBlocksRollback()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var second=await s.PublishAsync();await using(var db=s.Api.Context()) await db.Set<UserProjectScope>().Where(x=>x.UserId==s.Api.User.Id).ExecuteDeleteAsync();using var result=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{second}/rollback",new {targetConfigVersion=1L});Assert.Equal(HttpStatusCode.Forbidden,result.StatusCode);await using var check=s.Api.Context();Assert.False(await check.Set<ReleaseRecord>().AnyAsync(r=>r.ReleaseType=="rollback"));}
    [Fact] public async Task ConcurrentRetryAndNewPublishCannotOverwriteDesired()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var failed=await s.PublishAsync(false);await using(var db=s.Api.Context()) {var r=await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==failed);r.Status="Failed";r.FailureCode="ack_timeout";await db.SaveChangesAsync();}var next=await s.ReadyAsync();var responses=await Task.WhenAll(ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{failed}/retry"),ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{next}/publish"));try {Assert.Single(responses,r=>r.StatusCode==HttpStatusCode.OK);Assert.Single(responses,r=>r.StatusCode==HttpStatusCode.Conflict);}finally {foreach(var response in responses) response.Dispose();}await using var check=s.Api.Context();Assert.Equal(1,await check.Set<ReleaseRecord>().CountAsync(r=>r.Status=="Building"));Assert.Equal(2,(await check.Set<EnvironmentRecord>().SingleAsync()).DeploymentSequence);Assert.Equal("Failed",(await check.Set<ReleaseRecord>().SingleAsync(r=>r.Id==failed)).Status);}
    [Fact] public async Task RetryKeepsFailedRecordAndOriginalBytes()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();var failed=await s.PublishAsync(false);var old=await s.DesiredAsync(failed);await using(var db=s.Api.Context()) {var r=await db.Set<ReleaseRecord>().SingleAsync();r.Status="Failed";r.FailureCode="ack_timeout";await db.SaveChangesAsync();}using var retried=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{failed}/retry");retried.EnsureSuccessStatusCode();var body=await retried.Content.ReadFromJsonAsync<JsonElement>();var id=body.GetProperty("id").GetGuid();Assert.Equal(failed,body.GetProperty("recoveryOf").GetGuid());await s.BuildQueuedAsync();var next=await s.DesiredAsync(id);Assert.Equal(old.Payload,next.Payload);Assert.Equal(2,next.Envelope.DeploymentSequence);await s.AckAllAsync(id);await using var check=s.Api.Context();Assert.Equal("Failed",(await check.Set<ReleaseRecord>().SingleAsync(r=>r.Id==failed)).Status);Assert.Equal("Succeeded",(await check.Set<ReleaseRecord>().SingleAsync(r=>r.Id==id)).Status);Assert.Equal(1,await check.Set<GatewayConfigVersion>().CountAsync());}
    [Fact] public async Task PublicSnapshotDownloadNeverReturnsCredentialHashes()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();string hash;await using(var db=s.Api.Context()) hash=(await db.Set<ApplicationCredential>().SingleAsync()).SecretHash;using var download=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/snapshots/1/download");download.EnsureSuccessStatusCode();var text=await download.Content.ReadAsStringAsync();Assert.DoesNotContain(hash,text);Assert.DoesNotContain("secretHash",text,StringComparison.OrdinalIgnoreCase);using var nodes=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/gateway-nodes");nodes.EnsureSuccessStatusCode();Assert.DoesNotContain("identityHash",await nodes.Content.ReadAsStringAsync(),StringComparison.OrdinalIgnoreCase);}
    [Fact] public async Task RealWorkerBuildsQueuedRecordOutsideControlPlaneScope()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();var id=await s.ReadyAsync();using var publish=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{id}/publish");publish.EnsureSuccessStatusCode();using var worker=WorkerApp.Build(["--environment","Development"],b=>{b.Configuration["ConnectionStrings:WebApi"]=s.Api.Database.ConnectionString;b.Configuration["Redis:Prefix"]="worker-test:"+Guid.NewGuid();b.Logging.ClearProviders();});await worker.StartAsync();try {var until=DateTimeOffset.UtcNow.AddSeconds(8);while(DateTimeOffset.UtcNow<until) {await using var check=s.Api.Context();if(await check.Set<ReleaseRecord>().AnyAsync(r=>r.Id==id&&r.Status=="Publishing")) {Assert.Equal(1,await check.Set<GatewayConfigVersion>().CountAsync());return;}await Task.Delay(100);}throw new TimeoutException("Standalone Worker did not build queued release.");}finally {await worker.StopAsync();}}
    [Fact] public async Task ErrorCodeCannotEchoCredentialVerifier()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();var id=await s.PublishAsync(false);var desired=await s.DesiredAsync(id);string hash;await using(var db=s.Api.Context()) hash=(await db.Set<ApplicationCredential>().SingleAsync()).SecretHash;using var ack=await s.NodeAsync(0,$"/internal/v1/nodes/{s.NodeIds[0]}/ack",new NodeAck(s.Instances[0],id,desired.Envelope.ConfigVersion,desired.Envelope.DeploymentSequence,desired.Envelope.PayloadHash,DateTimeOffset.UtcNow,false,hash));Assert.Equal(HttpStatusCode.UnprocessableEntity,ack.StatusCode);await using var check=s.Api.Context();Assert.False(await check.Set<GatewayAck>().AnyAsync());}
    [Fact] public async Task NodeReadModelDistinguishesSameVersionDifferentDeployment()
    {await using var s=new DeploymentScenario();await s.InitializeAsync();await s.PublishAsync();var second=await s.PublishAsync(false);var cfg=await s.DesiredAsync(second);using var ack=await s.NodeAsync(0,$"/internal/v1/nodes/{s.NodeIds[0]}/ack",new NodeAck(s.Instances[0],second,2,2,cfg.Envelope.PayloadHash,DateTimeOffset.UtcNow,true,null));ack.EnsureSuccessStatusCode();await using(var db=s.Api.Context()) await db.Set<ReleaseRecord>().Where(r=>r.Id==second).ExecuteUpdateAsync(set=>set.SetProperty(r=>r.DeadlineAt,DateTimeOffset.UtcNow.AddSeconds(-1)));using(var scope=s.Api.Services()) await scope.ServiceProvider.GetRequiredService<ReleaseTimeoutService>().ExpireAsync();var rollback=await CreateAsync(s,second);using var submit=await ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/releases/{rollback}/submit");submit.EnsureSuccessStatusCode();await s.ApproveAsync(rollback);await s.BuildAsync(rollback);var desired=await s.DesiredAsync(rollback);using var applied=await s.NodeAsync(0,$"/internal/v1/nodes/{s.NodeIds[0]}/ack",new NodeAck(s.Instances[0],rollback,1,3,desired.Envelope.PayloadHash,DateTimeOffset.UtcNow,true,null));applied.EnsureSuccessStatusCode();using var response=await s.Api.Client.GetAsync($"/api/v1/environments/{s.Api.Environment.Id}/gateway-nodes");response.EnsureSuccessStatusCode();var body=await response.Content.ReadFromJsonAsync<JsonElement>();var nodes=body.GetProperty("items").EnumerateArray().ToArray();var stale=nodes.Single(n=>n.GetProperty("id").GetGuid()==s.NodeIds[1]);Assert.Equal(1,stale.GetProperty("currentConfigVersion").GetInt64());Assert.Equal(1,stale.GetProperty("currentDeploymentSequence").GetInt64());Assert.Equal(1,stale.GetProperty("desiredConfigVersion").GetInt64());Assert.Equal(3,stale.GetProperty("desiredDeploymentSequence").GetInt64());}
}
