using Xunit;
using Microsoft.EntityFrameworkCore;
using WebApi.Integration.Tests.Support;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Infrastructure.Settings;
namespace WebApi.Integration.Tests;
public sealed class SystemSettingsPersistenceTests
{
    [Fact]public async Task DefaultsDoNotCreateRows(){await using var f=new ApiFixture();await f.InitializeAsync();await using var db=f.Context();var reader=new SystemSettingsReader(db);Assert.Equal(480,(await reader.SecurityAsync()).SessionTtlMinutes);Assert.Equal(16,(await reader.SecurityAsync()).PasswordMinLength);Assert.Equal("LengthOnly",(await reader.SecurityAsync()).PasswordComplexity);Assert.Equal(30000,(await reader.GatewayAsync()).DefaultRouteTimeoutMs);Assert.True((await reader.AuditAsync()).AuditExportEnabled);Assert.Equal(0,await db.Set<SystemSetting>().CountAsync());Assert.Equal(0,(await reader.ReadAsync("security")).Revision);}
    [Fact]public async Task MigrationCreatesEmptyConstrainedTable(){await using var f=new ApiFixture();await f.InitializeAsync();await using var db=f.Context();Assert.False(db.Database.HasPendingModelChanges());Assert.Empty(await db.Set<SystemSetting>().ToArrayAsync());var type=await db.Database.SqlQueryRaw<string>("SELECT data_type AS \"Value\" FROM information_schema.columns WHERE table_name='system_settings' AND column_name='value'").SingleAsync();Assert.Equal("jsonb",type);db.Add(new SystemSetting{Key="system.security",ScopeType="org",Value="{}",UpdatedBy=f.User.Id});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}
    [Fact]public async Task SavedValuesSurviveNewServiceScope(){await using var f=new ApiFixture();await f.InitializeAsync();await using(var db=f.Context()){db.Add(new SystemSetting{Key="system.security",Value="{\"sessionTtlMinutes\":15,\"passwordMinLength\":32,\"passwordComplexity\":\"LettersAndDigits\",\"allowedOrigins\":[]}",UpdatedBy=f.User.Id});await db.SaveChangesAsync();}await using(var db=f.Context()){var value=await new SystemSettingsReader(db).ReadAsync("security");Assert.True(value.IsSaved);Assert.Equal(1,value.Revision);Assert.Equal(15,((SecuritySettings)value.Value).SessionTtlMinutes);Assert.Equal(60,((SecuritySettings)value.Value).LoginIpMaxAttempts);Assert.Equal(300,((SecuritySettings)value.Value).LoginAccountWindowSeconds);Assert.DoesNotContain("loginIpMaxAttempts",(await db.Set<SystemSetting>().SingleAsync()).Value);}}
    [Theory][InlineData("system.other",1)][InlineData("system.security",0)]public async Task InvalidKeyAndRevisionRejected(string key,long revision){await using var f=new ApiFixture();await f.InitializeAsync();await using var db=f.Context();var value="{}";await Assert.ThrowsAsync<Npgsql.PostgresException>(()=>db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO system_settings(key,scope_type,value,updated_by,updated_at,revision) VALUES ({key}, 'system', {value}::jsonb, {f.User.Id}, now(), {revision})"));}
    [Fact]public async Task ForeignKeyRejectsUnknownActor(){await using var f=new ApiFixture();await f.InitializeAsync();await using var db=f.Context();db.Add(new SystemSetting{Key="system.audit",Value="{}",UpdatedBy=Guid.NewGuid()});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}
    [Fact]public async Task DatabaseFailureDoesNotBecomeDefaults(){await using var f=new ApiFixture();await f.InitializeAsync();await using var db=f.Context();db.Database.GetDbConnection().ConnectionString="Host=127.0.0.1;Port=1;Database=missing;Username=missing;Password=test;Timeout=1";await Assert.ThrowsAnyAsync<Exception>(()=>new SystemSettingsReader(db).ReadAsync("security"));}
}
