using Xunit;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Integration.Tests.Support;
using WebApi.Infrastructure.Persistence.Entities;
namespace WebApi.Integration.Tests;
public sealed class SystemSettingsCommandTests
{
    private sealed class Clock:TimeProvider{public DateTimeOffset Now=DateTimeOffset.UtcNow;public override DateTimeOffset GetUtcNow()=>Now;}
    private static object Security(int ttl=480)=>new {sessionTtlMinutes=ttl,passwordMinLength=16,passwordComplexity="LengthOnly",allowedOrigins=Array.Empty<string>(),loginIpMaxAttempts=60,loginIpWindowSeconds=60,loginAccountMaxAttempts=10,loginAccountWindowSeconds=300};
    private static async Task<ApiFixture> Setup(Clock? clock=null){var f=new ApiFixture();await f.InitializeAsync(b=>{if(clock is not null)b.Services.AddSingleton<TimeProvider>(clock);});await f.SeedScopeAsync(platformAdmin:true);await SystemSettingsFixture.PromoteAsync(f);(await f.LoginAsync()).EnsureSuccessStatusCode();return f;}
    [Fact]public async Task AllEndpointsRequireRealPlatformPermission(){await using var f=new ApiFixture();await f.InitializeAsync();Assert.Equal(HttpStatusCode.Unauthorized,(await f.Client.GetAsync("/api/v1/settings/system")).StatusCode);await f.SeedScopeAsync();(await f.LoginAsync()).EnsureSuccessStatusCode();Assert.Equal(HttpStatusCode.Forbidden,(await f.Client.GetAsync("/api/v1/settings/system/security")).StatusCode);await SystemSettingsFixture.PromoteAsync(f);await using(var db=f.Context()){var role=await db.Set<Role>().SingleAsync();role.IsSystem=false;await db.SaveChangesAsync();}Assert.Equal(HttpStatusCode.Forbidden,(await f.Client.GetAsync("/api/v1/settings/system/security")).StatusCode);}
    [Fact]public async Task PreviewAndValidateDoNotWriteOrConnect(){await using var f=await Setup();using var validated=await SystemSettingsFixture.SendAsync(f,HttpMethod.Post,"security","/validate",new {values=Security()});validated.EnsureSuccessStatusCode();Assert.Equal("StructuralOnly",(await validated.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("testKind").GetString());await SystemSettingsFixture.PreviewAsync(f,"security",Security());await using var db=f.Context();Assert.Empty(await db.Set<SystemSetting>().ToArrayAsync());Assert.Equal(0,await db.Set<AuditLog>().CountAsync(x=>x.Action.StartsWith("settings.")));}
    [Fact]public async Task FirstSaveRaceHasOneWinner(){await using var f=await Setup();var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security(15));var body=new {values=Security(15),confirmationToken=preview.GetProperty("confirmationToken").GetString()};var responses=await Task.WhenAll(SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag),SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag));Assert.Single(responses,r=>r.StatusCode==HttpStatusCode.OK);Assert.Single(responses,r=>r.StatusCode==HttpStatusCode.PreconditionFailed);await using var db=f.Context();Assert.Equal(1,(await db.Set<SystemSetting>().SingleAsync()).Revision);Assert.Equal(1,await db.Set<AuditLog>().CountAsync(x=>x.Action.StartsWith("settings.")));}
    [Fact]public async Task GroupsAreAtomicAndIndependent(){await using var f=await Setup();(await SystemSettingsFixture.SaveAsync(f,"security",Security(15))).EnsureSuccessStatusCode();(await SystemSettingsFixture.SaveAsync(f,"gateway",new {defaultRouteTimeoutMs=12000,maxRequestBodyMb=20,configRefreshIntervalSeconds=2})).EnsureSuccessStatusCode();var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security(25));using var invalid=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",new {values=Security(0),confirmationToken=preview.GetProperty("confirmationToken").GetString()},tag);Assert.Equal(HttpStatusCode.UnprocessableEntity,invalid.StatusCode);await using var db=f.Context();Assert.Equal(2,await db.Set<SystemSetting>().CountAsync());Assert.Equal(1,(await db.Set<SystemSetting>().SingleAsync(x=>x.Key=="system.security")).Revision);}
    [Fact]public async Task ConfirmationIsBoundAndExpires(){var clock=new Clock();await using var f=await Setup(clock);var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security(15));var token=preview.GetProperty("confirmationToken").GetString();using var changed=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",new {values=Security(16),confirmationToken=token},tag);Assert.Equal(HttpStatusCode.UnprocessableEntity,changed.StatusCode);clock.Now+=TimeSpan.FromMinutes(6);using var expired=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",new {values=Security(15),confirmationToken=token},tag);Assert.Equal(HttpStatusCode.UnprocessableEntity,expired.StatusCode);}
    [Fact]public async Task CommittedReplayAfterTokenExpiryReturnsOriginalWithoutAudit(){var clock=new Clock();await using var f=await Setup(clock);var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security(15));var body=new {values=Security(15),confirmationToken=preview.GetProperty("confirmationToken").GetString()};var key=Guid.NewGuid().ToString("N");using var first=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag,key);first.EnsureSuccessStatusCode();var original=await first.Content.ReadAsStringAsync();clock.Now+=TimeSpan.FromMinutes(6);using var replay=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag,key);replay.EnsureSuccessStatusCode();Assert.Equal(original,await replay.Content.ReadAsStringAsync());await using var db=f.Context();Assert.Equal(1,(await db.Set<SystemSetting>().SingleAsync()).Revision);Assert.Equal(1,await db.Set<AuditLog>().CountAsync(x=>x.Action.StartsWith("settings.")));}
    [Fact]public async Task SemanticChangeWithSameKeyIs409(){await using var f=await Setup();var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security(15));var key=Guid.NewGuid().ToString("N");var token=preview.GetProperty("confirmationToken").GetString();(await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",new {values=Security(15),confirmationToken=token},tag,key)).EnsureSuccessStatusCode();using var second=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",new {values=Security(16),confirmationToken=token},tag,key);Assert.Equal(HttpStatusCode.Conflict,second.StatusCode);}
    [Fact]public async Task RevokedActorCannotReplay(){await using var f=await Setup();var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"security",Security());var body=new {values=Security(),confirmationToken=preview.GetProperty("confirmationToken").GetString()};var key=Guid.NewGuid().ToString("N");(await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag,key)).EnsureSuccessStatusCode();await using(var db=f.Context()){var p=await db.Set<Permission>().SingleAsync(x=>x.Code=="system.manage");db.RemoveRange(await db.Set<RolePermission>().Where(x=>x.PermissionId==p.Id).ToArrayAsync());await db.SaveChangesAsync();}using var replay=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"security","",body,tag,key);Assert.Equal(HttpStatusCode.Forbidden,replay.StatusCode);}
    [Fact]public async Task MissingTagIs428AndCsrfRequired(){await using var f=await Setup();using var missing=await SystemSettingsFixture.SendAsync(f,HttpMethod.Post,"security","/preview",new {values=Security()});Assert.Equal((HttpStatusCode)428,missing.StatusCode);using var csrf=await f.Client.PutAsJsonAsync("/api/v1/settings/system/security",new {values=Security(),confirmationToken="x"});Assert.Equal(HttpStatusCode.Forbidden,csrf.StatusCode);}
    [Fact]public async Task ReferencesNeverLeaveReadPreviewProblemsOrAudit(){await using var f=await Setup();const string secret="vault://test/fixture-generated-reference-123";var values=new {smtpHost="mail.example.com",smtpPort=587,fromEmail="sender@example.com",smtpSecretRef=new {operation="Replace",reference=secret},webhookUrl=(string?)null,webhookSecretRef=new {operation="Keep"}};var (preview,tag)=await SystemSettingsFixture.PreviewAsync(f,"notification",values);Assert.DoesNotContain(secret,preview.GetRawText());using var saved=await SystemSettingsFixture.SendAsync(f,HttpMethod.Put,"notification","",new {values,confirmationToken=preview.GetProperty("confirmationToken").GetString()},tag);saved.EnsureSuccessStatusCode();Assert.DoesNotContain(secret,await saved.Content.ReadAsStringAsync());var read=await f.Client.GetStringAsync("/api/v1/settings/system/notification");Assert.DoesNotContain(secret,read);Assert.Contains("hasConfiguredReference",read);await using var db=f.Context();var audits=await db.Set<AuditLog>().Where(x=>x.Action.StartsWith("settings.")).ToArrayAsync();Assert.Single(audits);Assert.DoesNotContain(secret,audits[0].AfterJson!);}
}
