using Xunit;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using WebApi.Integration.Tests.Support;
using WebApi.Infrastructure.Persistence.Entities;
namespace WebApi.Integration.Tests;
public sealed class SystemSettingsConsumerTests
{
    private static async Task<ApiFixture> Setup(){var f=new ApiFixture();await f.InitializeAsync();await f.SeedCatalogAsync();await SystemSettingsFixture.PromoteAsync(f);(await f.LoginAsync()).EnsureSuccessStatusCode();return f;}
    private static object Gateway(int timeout=12000)=>new{defaultRouteTimeoutMs=timeout,maxRequestBodyMb=20,configRefreshIntervalSeconds=2};
    private static object Security(int ttl=480,int length=16,string complexity="LengthOnly")=>new{sessionTtlMinutes=ttl,passwordMinLength=length,passwordComplexity=complexity,allowedOrigins=Array.Empty<string>(),loginIpMaxAttempts=60,loginIpWindowSeconds=60,loginAccountMaxAttempts=10,loginAccountWindowSeconds=300};
    private static AuthenticationTicket Ticket(ApiFixture f,HttpResponseMessage response){using var scope=f.Services();var options=scope.ServiceProvider.GetRequiredService<IOptionsMonitor<CookieAuthenticationOptions>>().Get(CookieAuthenticationDefaults.AuthenticationScheme);var cookie=response.Headers.GetValues("Set-Cookie").Single(x=>x.StartsWith("WebApi.Session="));return options.TicketDataFormat.Unprotect(cookie.Split(';')[0].Split('=',2)[1])!;}
    [Fact]public async Task NewLoginUsesTtlButExistingTicketKeepsExpiry(){await using var f=await Setup();using var oldLogin=await f.LoginAsync();var old=Ticket(f,oldLogin);(await SystemSettingsFixture.SaveAsync(f,"security",Security(5))).EnsureSuccessStatusCode();using var freshLogin=await f.LoginAsync();var fresh=Ticket(f,freshLogin);Assert.Equal(TimeSpan.FromMinutes(480),old.Properties.ExpiresUtc-old.Properties.IssuedUtc);Assert.Equal(TimeSpan.FromMinutes(5),fresh.Properties.ExpiresUtc-fresh.Properties.IssuedUtc);Assert.False(fresh.Properties.IsPersistent);}
    [Theory][InlineData("LettersAndDigits")][InlineData("UpperLowerDigitSpecial")]
    public async Task NewUserUsesPolicyAndOldLoginStillWorks(string complexity){await using var f=await Setup();const string legacy="abcdefghijklmnop";await using(var db=f.Context()){var u=await db.Set<UserRecord>().SingleAsync(x=>x.Id==f.User.Id);u.PasswordHash=new PasswordHasher<UserRecord>().HashPassword(u,legacy);await db.SaveChangesAsync();}(await SystemSettingsFixture.SaveAsync(f,"security",Security(length:32,complexity:complexity))).EnsureSuccessStatusCode();using var rejected=await f.WriteAsync(HttpMethod.Post,"/api/v1/users",new{username="weak-user",displayName="弱密码",password=legacy});Assert.Equal(HttpStatusCode.UnprocessableEntity,rejected.StatusCode);using var simple=await f.WriteAsync(HttpMethod.Post,"/api/v1/users",new{username="plain-user",displayName="无复杂度",password=new string('a',32)});Assert.Equal(HttpStatusCode.UnprocessableEntity,simple.StatusCode);using var accepted=await f.WriteAsync(HttpMethod.Post,"/api/v1/users",new{username="strong-user",displayName="符合策略",password="Abc123!"+new string('x',25)});accepted.EnsureSuccessStatusCode();(await f.LoginAsync(legacy)).EnsureSuccessStatusCode();}
    [Fact]public async Task NewRouteOmittedUsesDefaultAndExplicitWins(){await using var f=await Setup();(await SystemSettingsFixture.SaveAsync(f,"gateway",Gateway())).EnsureSuccessStatusCode();using var create=await f.WriteAsync(HttpMethod.Post,$"/api/v1/environments/{f.Environment.Id}/routes",new{apiVersionId=f.Version.Id,routeName="Default",path="/new-default",methods=new[]{"GET"},clusterId=f.Cluster.Id});create.EnsureSuccessStatusCode();Assert.Equal(12000,(await create.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("timeoutMs").GetInt32());using var explicitRoute=await f.WriteAsync(HttpMethod.Post,$"/api/v1/environments/{f.Environment.Id}/routes",new{apiVersionId=f.Version.Id,routeName="Explicit",path="/new-explicit",methods=new[]{"GET"},clusterId=f.Cluster.Id,timeoutMs=9000});explicitRoute.EnsureSuccessStatusCode();Assert.Equal(9000,(await explicitRoute.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("timeoutMs").GetInt32());await using var db=f.Context();Assert.Empty(await db.Set<GatewayConfigSnapshot>().ToArrayAsync());}
    [Fact]public async Task EditOmittedTimeoutIsRejected(){await using var f=await Setup();using var create=await f.WriteAsync(HttpMethod.Post,$"/api/v1/environments/{f.Environment.Id}/routes",f.RouteBody("/old"));create.EnsureSuccessStatusCode();var row=await create.Content.ReadFromJsonAsync<JsonElement>();using var edit=await f.WriteAsync(HttpMethod.Put,$"/api/v1/routes/{row.GetProperty("id").GetGuid()}",new{id=row.GetProperty("id").GetGuid(),apiVersionId=f.Version.Id,routeName="Edit",path="/old",methods=new[]{"GET"},clusterId=f.Cluster.Id},create.Headers.ETag!.Tag);Assert.Equal(HttpStatusCode.UnprocessableEntity,edit.StatusCode);await using var db=f.Context();Assert.Equal(30000,(await db.Set<ApiRoute>().SingleAsync()).TimeoutMs);}
    [Fact]public async Task ImportUsesDefaultOnlyForNewRoutes(){await using var f=await Setup();(await SystemSettingsFixture.SaveAsync(f,"gateway",Gateway())).EnsureSuccessStatusCode();var input=new{projectId=f.Project.Id,environmentId=f.Environment.Id,clusterId=f.Cluster.Id,source=ImportAndCredentialTests.Source};using var created=await f.WriteAsync(HttpMethod.Post,"/api/v1/openapi/import-commit",new{input,targets=new[]{new{operationId="readOne",newApiCode="IMPORTED",newApiName="导入",version="1.0.0"}}});created.EnsureSuccessStatusCode();ApiRoute route;ApiVersion version;await using(var db=f.Context()){route=await db.Set<ApiRoute>().SingleAsync();version=await db.Set<ApiVersion>().SingleAsync(x=>x.Id==route.ApiVersionId);Assert.Equal(12000,route.TimeoutMs);}using var overwrite=await f.WriteAsync(HttpMethod.Post,"/api/v1/openapi/import-commit",new{input,targets=new[]{new{operationId="readOne",existingVersionId=version.Id,expectedRevision=version.Revision,existingRouteId=route.Id,expectedRouteRevision=route.Revision}}});overwrite.EnsureSuccessStatusCode();await using var check=f.Context();Assert.Equal(30000,(await check.Set<ApiRoute>().SingleAsync()).TimeoutMs);}
    [Fact]public async Task RouteDefaultsDoesNotExposePlatformSettings(){await using var f=await Setup();using var defaults=await f.Client.GetAsync($"/api/v1/environments/{f.Environment.Id}/route-defaults");defaults.EnsureSuccessStatusCode();var body=await defaults.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal(2,body.EnumerateObject().Count());Assert.Equal(30000,body.GetProperty("timeoutMs").GetInt32());Assert.Equal(HttpStatusCode.NotFound,(await f.Client.GetAsync($"/api/v1/environments/{Guid.NewGuid()}/route-defaults")).StatusCode);await using(var db=f.Context()){await db.Set<UserProjectScope>().ExecuteDeleteAsync();}Assert.Equal(HttpStatusCode.Forbidden,(await f.Client.GetAsync($"/api/v1/environments/{f.Environment.Id}/route-defaults")).StatusCode);}
    [Fact]public async Task LoginAndDisableShareConsistentLockOrder(){await using var f=await Setup();var second=await f.NewReviewerAsync("ApiApprover");await using(var db=f.Context()){var role=await db.Set<Role>().SingleAsync(x=>x.Code=="PlatformAdmin");db.Add(new UserRole{UserId=second.User.Id,RoleId=role.Id});await db.SaveChangesAsync();}var both=Task.WhenAll(f.LoginAsync(),f.WriteAsync(HttpMethod.Put,$"/api/v1/users/{f.User.Id}",new{displayName="停用",status="Disabled"},"\"1\""));var result=await both.WaitAsync(TimeSpan.FromSeconds(15));Assert.Equal(HttpStatusCode.OK,result[1].StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await f.Client.GetAsync("/api/v1/auth/me")).StatusCode);}
}
