using Xunit;
using System.Net;
using System.Text;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Integration.Tests.Support;
using WebApi.Infrastructure.Persistence.Entities;
namespace WebApi.Integration.Tests;
public sealed class SystemSettingsAuditExportTests
{
    private static async Task<ApiFixture> Setup(bool platform=true){var f=new ApiFixture();await f.InitializeAsync();await f.SeedScopeAsync(platformAdmin:platform);if(platform)await SystemSettingsFixture.PromoteAsync(f);(await f.LoginAsync()).EnsureSuccessStatusCode();return f;}
    private static AuditLog Log(ApiFixture f,string resource,Guid? project=null,Guid? env=null)=>new(){OrganizationId=f.Organization.Id,ProjectId=project,EnvironmentId=env,UserId=f.User.Id,Action="export-test",ResourceType="fixture",ResourceId=resource,TraceId="fixture-trace",Ip=System.Net.IPAddress.Parse("127.0.0.1"),BeforeJson="{\"fixtureSecret\":true}"};
    [Fact]public async Task ExportMatchesListScopeUnion(){await using var f=await Setup(false);await using(var db=f.Context()){var grant=await db.Set<UserProjectScope>().SingleAsync();grant.ProjectId=f.Project.Id;db.AddRange(Log(f,"org-only"),Log(f,"project-visible",f.Project.Id),new AuditLog{Action="foreign",ResourceType="fixture",ResourceId="foreign-private"});await db.SaveChangesAsync();}using var export=await f.Client.GetAsync("/api/v1/audit-logs/export");export.EnsureSuccessStatusCode();var text=await export.Content.ReadAsStringAsync();Assert.Contains("project-visible",text);Assert.DoesNotContain("org-only",text);Assert.DoesNotContain("foreign-private",text);Assert.DoesNotContain("fixtureSecret",text);Assert.DoesNotContain("127.0.0.1",text);}
    [Fact]public async Task ExportRequiresPermissionAndEnabledFlag(){await using var f=await Setup();(await SystemSettingsFixture.SaveAsync(f,"audit",new{auditRetentionDays=365,auditExportEnabled=false})).EnsureSuccessStatusCode();using var disabled=await f.Client.GetAsync("/api/v1/audit-logs/export");Assert.Equal(HttpStatusCode.Forbidden,disabled.StatusCode);using var list=await f.Client.GetAsync("/api/v1/audit-logs");list.EnsureSuccessStatusCode();Assert.False((await list.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("exportAllowed").GetBoolean());(await SystemSettingsFixture.SaveAsync(f,"audit",new{auditRetentionDays=365,auditExportEnabled=true})).EnsureSuccessStatusCode();await using(var db=f.Context()){var p=await db.Set<Permission>().SingleAsync(x=>x.Code=="audit.read");await db.Set<RolePermission>().Where(x=>x.PermissionId==p.Id).ExecuteDeleteAsync();}Assert.Equal(HttpStatusCode.Forbidden,(await f.Client.GetAsync("/api/v1/audit-logs/export")).StatusCode);}
    [Fact]public async Task ExportHasStableUpperIdAndLimits(){await using var f=await Setup();await using(var db=f.Context()){db.AddRange(Enumerable.Range(0,10001).Select(i=>Log(f,"r"+i)));await db.SaveChangesAsync();}using var response=await f.Client.GetAsync("/api/v1/audit-logs/export");response.EnsureSuccessStatusCode();Assert.Equal("10000",response.Headers.GetValues("X-Export-Row-Count").Single());Assert.Equal("true",response.Headers.GetValues("X-Export-Truncated").Single());Assert.True((await response.Content.ReadAsByteArrayAsync()).Length<=8*1024*1024);}
    [Fact]public async Task ExportByteLimitDoesNotCutRows(){await using var f=await Setup();await using(var db=f.Context()){db.AddRange(Enumerable.Range(0,10000).Select(i=>new AuditLog{UserId=f.User.Id,OrganizationId=f.Organization.Id,ProjectId=f.Project.Id,EnvironmentId=f.Environment.Id,Action=new string('\u4e2d',128),ResourceType=new string('\u4e2d',64),ResourceId=new string('\u4e2d',128),TraceId=new string('\u4e2d',64)}));await db.SaveChangesAsync();}using var response=await f.Client.GetAsync("/api/v1/audit-logs/export");response.EnsureSuccessStatusCode();var bytes=await response.Content.ReadAsByteArrayAsync();Assert.True(bytes.Length<=8*1024*1024);Assert.EndsWith("\r\n",Encoding.UTF8.GetString(bytes));Assert.Equal("true",response.Headers.GetValues("X-Export-Truncated").Single());Assert.True(int.Parse(response.Headers.GetValues("X-Export-Row-Count").Single())<10000);}
    [Theory][InlineData(false)][InlineData(true)]public async Task ExportRevocationOrDisableBeforeAdmissionDropsBuffer(bool revoke){await using var f=await Setup();(await SystemSettingsFixture.SaveAsync(f,"audit",new{auditRetentionDays=365,auditExportEnabled=true})).EnsureSuccessStatusCode();await using var db=f.Context();await using var tx=await db.Database.BeginTransactionAsync();await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(8901202)");var pending=f.Client.GetAsync("/api/v1/audit-logs/export");var waiting=false;for(var i=0;i<100;i++){if(pending.IsCompleted)break;await db.Database.ExecuteSqlRawAsync("SELECT pg_stat_clear_snapshot()");waiting=await db.Database.SqlQueryRaw<bool>("SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND wait_event='advisory') AS \"Value\"").SingleAsync();if(waiting)break;await Task.Delay(50);}Assert.True(waiting,$"Export must wait on final admission lock; completed={pending.IsCompleted}, status={(pending.IsCompleted?(int)(await pending).StatusCode:0)}");if(revoke)await db.Database.ExecuteSqlRawAsync("DELETE FROM role_permissions WHERE permission_id IN(SELECT id FROM permissions WHERE code='audit.read')");else await db.Database.ExecuteSqlRawAsync("UPDATE system_settings SET value=jsonb_set(value,ARRAY['auditExportEnabled'],'false') WHERE key='system.audit'");await tx.CommitAsync();using var result=await pending.WaitAsync(TimeSpan.FromSeconds(10));Assert.Equal(HttpStatusCode.Forbidden,result.StatusCode);Assert.DoesNotContain("text/csv",result.Content.Headers.ContentType?.ToString()??"");}
}
