using Microsoft.Extensions.DependencyInjection;
using WebApi.Contracts.Common;
using WebApi.Contracts.Security;
using WebApi.Infrastructure.Delivery;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using Microsoft.EntityFrameworkCore;
using WebApi.Contracts.Releases;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class TestAcceptanceTests
{
    private static async Task<Guid[]> Evidence(DeliveryScenario s)
    {var ids=new List<Guid>();foreach(var type in new[]{"InterfaceFunction","Integration","ContractCompatibility"}){using var response=await s.RecordAsync(type:type);response.EnsureSuccessStatusCode();ids.Add((await response.Content.ReadFromJsonAsync<ReleaseVerificationDto>())!.Id);}return ids.ToArray();}
    private static Task<HttpResponseMessage> Request(DeliveryScenario s,Guid[] ids,string? key=null)=>ApiFixture.CommandAsync(s.Api.Client,$"/api/v1/release-artifacts/{s.Artifact.Id}/test-acceptances",new RequestTestAcceptanceRequest(ids),key);
    private static async Task<TestAcceptanceDto> Requested(DeliveryScenario s)
    {using var response=await Request(s,await Evidence(s));response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;}
    private static async Task Grant(DeliveryScenario s,Guid user,params string[] codes)
    {await using var db=s.Api.Context();var roleId=await db.Set<UserRole>().Where(x=>x.UserId==user).Select(x=>x.RoleId).FirstAsync();foreach(var code in codes){var permission=await db.Set<Permission>().SingleOrDefaultAsync(p=>p.Code==code);if(permission is null){permission=new(){Code=code,Module=code.Split('.')[0],Name=code};db.Add(permission);}if(!await db.Set<RolePermission>().AnyAsync(r=>r.RoleId==roleId&&r.PermissionId==permission.Id))db.Add(new RolePermission{RoleId=roleId,PermissionId=permission.Id});}await db.SaveChangesAsync();}
    private static async Task<(UserRecord User,HttpClient Client)> Acceptor(DeliveryScenario s,bool permission=true)
    {var user=await s.Api.NewReviewerAsync("IndependentTestAcceptor");await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==user.User.Id).Select(r=>r.RoleId).SingleAsync();var production=await db.Set<Permission>().Where(p=>p.Code=="approval.act"||p.Code=="api.approve").Select(p=>p.Id).ToArrayAsync();await db.Set<RolePermission>().Where(r=>r.RoleId==role&&production.Contains(r.PermissionId)).ExecuteDeleteAsync();}await Grant(s,user.User.Id,["environment.read","api.read","api.version.read","api.schema.read","route.read",..(permission?new[]{"release.test.accept"}:Array.Empty<string>())]);return user;}
    private static async Task<HttpResponseMessage> Act(HttpClient client,TestAcceptanceDto a,string action,string? etag=null,string? key=null)
    {var csrf=await client.GetFromJsonAsync<Dictionary<string,string>>("/api/v1/auth/csrf");using var request=new HttpRequestMessage(HttpMethod.Post,$"/api/v1/test-acceptances/{a.Id}/{action}"){Content=JsonContent.Create(new TestAcceptanceActionRequest("独立验收操作"))};request.Headers.Add("X-CSRF-Token",csrf!["token"]);request.Headers.Add("Idempotency-Key",key??Guid.NewGuid().ToString("N"));request.Headers.Add("If-Match",etag??$"\"{a.Revision}\"");return await client.SendAsync(request);}
    [Fact] public async Task EvidenceRequestRemainsRequestedUntilIndependentAcceptance()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);Assert.Equal("Requested",a.Status);Assert.Equal(64,a.EvidenceHash.Length);Assert.Equal(s.Artifact.ArtifactHash,a.ArtifactHash);var actor=await Acceptor(s);using var accepted=await Act(actor.Client,a,"accept");accepted.EnsureSuccessStatusCode();var b=(await accepted.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;Assert.Equal("Accepted",b.Status);Assert.Equal(actor.User.Id,b.ActedBy);Assert.Equal(s.Api.User.Id,b.RequestedBy);Assert.Equal(a.EvidenceHash,b.EvidenceHash);await using var db=s.Api.Context();Assert.Equal(2,await db.Set<ApprovalTask>().CountAsync());Assert.Equal(3,await db.Set<ReleaseVerification>().CountAsync());}
    [Fact] public async Task PlatformAdministratorCannotAcceptOwnRequest()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);await Grant(s,s.Api.User.Id,"release.test.accept");await using(var db=s.Api.Context()){var role=new Role{Code="PlatformAdmin",Name="平台管理员",IsSystem=true};db.Add(role);db.Add(new UserRole{UserId=s.Api.User.Id,RoleId=role.Id});await db.SaveChangesAsync();}using var response=await Act(s.Api.Client,a,"accept");Assert.Equal(HttpStatusCode.Forbidden,response.StatusCode);}
    [Theory] [InlineData("missing",HttpStatusCode.UnprocessableEntity)] [InlineData("failed",HttpStatusCode.Conflict)] [InlineData("expired",HttpStatusCode.Conflict)] [InlineData("superseded",HttpStatusCode.Conflict)] [InlineData("foreign",HttpStatusCode.NotFound)] [InlineData("entry",HttpStatusCode.Conflict)] [InlineData("sequence",HttpStatusCode.Conflict)] [InlineData("policy",HttpStatusCode.Conflict)]
    public async Task IncompleteOrChangedEvidenceCannotBeAccepted(string change,HttpStatusCode expected)
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var ids=await Evidence(s);await using(var db=s.Api.Context()){
        if(change=="missing")ids=ids[..2];
        if(change=="failed")await db.Set<ReleaseVerification>().Where(v=>v.Id==ids[0]).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.Result,"Failed"));
        if(change=="expired")await db.Set<ReleaseVerification>().Where(v=>v.Id==ids[0]).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,DateTimeOffset.UtcNow.AddDays(-3)).SetProperty(v=>v.FinishedAt,DateTimeOffset.UtcNow.AddDays(-2)).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddDays(-1)));
        if(change=="foreign")ids[0]=Guid.NewGuid();
        if(change=="entry")await db.Set<EnvironmentRecord>().ExecuteUpdateAsync(x=>x.SetProperty(e=>e.AccessAddressRevision,2));
        if(change=="sequence")await db.Set<EnvironmentRecord>().ExecuteUpdateAsync(x=>x.SetProperty(e=>e.DeploymentSequence,50));
        if(change=="policy"){var target=new EnvironmentRecord{ProjectId=s.Api.Project.Id,Code="PROD",Name="生产",IsProduction=true};db.Add(target);db.Add(new ProjectDeliveryPolicy{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,SourceEnvironmentId=s.Api.Environment.Id,TargetEnvironmentId=target.Id,RequiredTestTypes=["InterfaceFunction","Integration","ContractCompatibility"],UpdatedBy=s.Api.User.Id});await db.SaveChangesAsync();}
        }if(change=="superseded"){using var newer=await s.RecordAsync("Failed");newer.EnsureSuccessStatusCode();}using var response=await Request(s,ids);Assert.Equal(expected,response.StatusCode);}
    [Theory] [InlineData("permission",HttpStatusCode.Forbidden)] [InlineData("scope",HttpStatusCode.Forbidden)] [InlineData("visibility",HttpStatusCode.NotFound)]
    public async Task AcceptanceRequiresFunctionalPermissionWriteScopeAndContractVisibility(string denied,HttpStatusCode expected)
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s,denied!="permission");await using(var db=s.Api.Context()){if(denied=="scope")await db.Set<UserProjectScope>().Where(g=>g.UserId==actor.User.Id).ExecuteUpdateAsync(x=>x.SetProperty(g=>g.AccessMode,"read_only"));if(denied=="visibility"){var role=await db.Set<UserRole>().Where(r=>r.UserId==actor.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="api.schema.read");await db.Set<RolePermission>().Where(p=>p.RoleId==role&&p.PermissionId==permission.Id).ExecuteDeleteAsync();}}using var response=await Act(actor.Client,a,"accept");Assert.Equal(expected,response.StatusCode);}
    [Fact] public async Task ChangedRulesAfterRequestRequireANewTestAndApplication()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s);await using(var db=s.Api.Context()){var target=new EnvironmentRecord{ProjectId=s.Api.Project.Id,Code="PROD",Name="生产",IsProduction=true};db.Add(target);db.Add(new ProjectDeliveryPolicy{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,SourceEnvironmentId=s.Api.Environment.Id,TargetEnvironmentId=target.Id,UpdatedBy=s.Api.User.Id,RequiredTestTypes=["InterfaceFunction","Integration","ContractCompatibility"]});await db.SaveChangesAsync();}using var response=await Act(actor.Client,a,"accept");Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
    [Fact] public async Task RejectionAndRevocationAppendEventsWithoutRewritingEvidence()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s);using var reject=await Act(actor.Client,a,"reject");reject.EnsureSuccessStatusCode();Assert.Equal("Rejected",(await reject.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Status);using var requestedAgain=await Request(s,a.VerificationIds.ToArray());requestedAgain.EnsureSuccessStatusCode();var next=(await requestedAgain.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;using var accept=await Act(actor.Client,next,"accept");accept.EnsureSuccessStatusCode();var accepted=(await accept.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;var key=Guid.NewGuid().ToString("N");using var revoke=await Act(actor.Client,accepted,"revoke",key:key);revoke.EnsureSuccessStatusCode();using var replay=await Act(actor.Client,accepted,"revoke",key:key);replay.EnsureSuccessStatusCode();Assert.Equal("Revoked",(await replay.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Status);await using var db=s.Api.Context();Assert.Equal(3,await db.Set<ReleaseVerification>().CountAsync());Assert.All(await db.Set<ReleaseVerification>().ToArrayAsync(),v=>Assert.Equal("Passed",v.Result));Assert.Equal(1,await db.Set<ReleasePromotionEvent>().CountAsync(e=>e.AcceptanceId==accepted.Id&&e.ToStatus=="Revoked"));}
    [Fact] public async Task SameRequestKeyReturnsSameAcceptanceButChangedEvidenceConflicts()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var ids=await Evidence(s);var key=Guid.NewGuid().ToString("N");using var first=await Request(s,ids,key);first.EnsureSuccessStatusCode();using var replay=await Request(s,ids.Reverse().ToArray(),key);replay.EnsureSuccessStatusCode();Assert.Equal((await first.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Id,(await replay.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Id);using var changed=await Request(s,ids[..2],key);Assert.Equal(HttpStatusCode.Conflict,changed.StatusCode);}
    [Fact] public async Task RevisionConflictDoesNotConsumeTheTestDecision()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s);using var response=await Act(actor.Client,a,"accept","\"0\"");Assert.Equal(HttpStatusCode.PreconditionFailed,response.StatusCode);using var unchanged=await s.Api.Client.GetAsync($"/api/v1/test-acceptances/{a.Id}");unchanged.EnsureSuccessStatusCode();Assert.Equal("Requested",(await unchanged.Content.ReadFromJsonAsync<TestAcceptanceDto>())!.Status);}
    [Fact] public async Task TestAcceptancePermissionDoesNotGrantProductionApprovalOrPublish()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var actor=await Acceptor(s);using var approve=await ApiFixture.CommandAsync(actor.Client,$"/api/v1/releases/{s.ReleaseId}/approve",new{comment="不能替代生产审批"});Assert.Equal(HttpStatusCode.Forbidden,approve.StatusCode);using var publish=await ApiFixture.CommandAsync(actor.Client,$"/api/v1/releases/{s.ReleaseId}/publish");Assert.Equal(HttpStatusCode.Forbidden,publish.StatusCode);}
    [Fact] public async Task CurrentAcceptedGateRechecksTheOriginalAcceptorAuthority()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s);using var response=await Act(actor.Client,a,"accept");response.EnsureSuccessStatusCode();using var services=s.Api.Services();var gate=services.ServiceProvider.GetRequiredService<TestAcceptanceService>();var requester=new ActorContext(s.Api.User.Id,"acceptance-live-authority-test");await gate.RequireAcceptedCurrentAsync(a.Id,s.Artifact.Id,requester,CancellationToken.None);await using(var db=s.Api.Context()){var role=await db.Set<UserRole>().Where(r=>r.UserId==actor.User.Id).Select(r=>r.RoleId).SingleAsync();var permission=await db.Set<Permission>().SingleAsync(p=>p.Code=="release.test.accept");await db.Set<RolePermission>().Where(r=>r.RoleId==role&&r.PermissionId==permission.Id).ExecuteDeleteAsync();}Assert.Equal(403,(await Assert.ThrowsAsync<ApiException>(()=>gate.RequireAcceptedCurrentAsync(a.Id,s.Artifact.Id,requester,CancellationToken.None))).Status);}
    [Fact] public async Task AcceptanceAuditContainsOnlySafeEvidenceSummary()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);await using var db=s.Api.Context();var audit=await db.Set<AuditLog>().SingleAsync(x=>x.Action=="test_acceptance.request");Assert.Contains(a.EvidenceHash,audit.AfterJson);Assert.Contains(a.ArtifactId.ToString(),audit.AfterJson);Assert.DoesNotContain("source-gateway.example",audit.AfterJson);Assert.DoesNotContain("CanonicalContent",audit.AfterJson);}
    [Fact] public async Task RevocationInvalidatesLinkedUnexecutedPromotionWithoutNewOutbox()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var a=await Requested(s);var actor=await Acceptor(s);using var response=await Act(actor.Client,a,"accept");response.EnsureSuccessStatusCode();var accepted=(await response.Content.ReadFromJsonAsync<TestAcceptanceDto>())!;Guid promotionId;int before;await using(var db=s.Api.Context()){var target=new EnvironmentRecord{ProjectId=s.Api.Project.Id,Code="PROD",Name="生产",IsProduction=true};db.Add(target);var promotion=new ReleasePromotion{OrganizationId=s.Api.Organization.Id,ProjectId=s.Api.Project.Id,ArtifactId=s.Artifact.Id,SourceEnvironmentId=s.Api.Environment.Id,TargetEnvironmentId=target.Id,SourceReleaseId=s.ReleaseId,AcceptanceId=accepted.Id,RequestedBy=s.Api.User.Id};promotionId=promotion.Id;db.Add(promotion);await db.SaveChangesAsync();before=await db.Set<OutboxMessage>().CountAsync();}using var revoked=await Act(actor.Client,accepted,"revoke");revoked.EnsureSuccessStatusCode();await using var context=s.Api.Context();Assert.Equal("Invalidated",(await context.Set<ReleasePromotion>().SingleAsync(p=>p.Id==promotionId)).Status);Assert.Equal(before,await context.Set<OutboxMessage>().CountAsync());Assert.Single(await context.Set<ReleasePromotionEvent>().Where(e=>e.PromotionId==promotionId&&e.ToStatus=="Invalidated").ToArrayAsync());}
    [Fact] public async Task HistoricalStoredEvidencePredatingActualDeploymentCannotRequestAcceptance()
    {await using var s=new DeliveryScenario();await s.InitializeAsync();var ids=await Evidence(s);await using(var db=s.Api.Context()){var finished=(await db.Set<ReleaseRecord>().SingleAsync(r=>r.Id==s.ReleaseId)).CreatedAt.AddMinutes(-1);await db.Set<ReleaseVerification>().Where(v=>ids.Contains(v.Id)).ExecuteUpdateAsync(x=>x.SetProperty(v=>v.StartedAt,finished.AddMinutes(-1)).SetProperty(v=>v.FinishedAt,finished).SetProperty(v=>v.ExpiresAt,DateTimeOffset.UtcNow.AddHours(1)));}using var response=await Request(s,ids);Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);await using var check=s.Api.Context();Assert.Empty(await check.Set<ReleaseTestAcceptance>().ToArrayAsync());Assert.Equal(3,await check.Set<ReleaseVerification>().CountAsync());}

}
