using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.Integration.Tests.Support;
using Xunit;
namespace WebApi.Integration.Tests;
public sealed class VersionRiskReviewTests
{
    [Fact] public async Task ReviewedRequiresCompleteAndNoRisk()
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();using var bad=await f.ReviewAsync(id,hash,"Reviewed",null,false);Assert.Equal(HttpStatusCode.UnprocessableEntity,bad.StatusCode);await f.SetNoRiskAsync();var (safe,safeHash)=await f.ComparisonAsync();using var good=await f.ReviewAsync(safe,safeHash,"Reviewed",null,false);Assert.Equal(HttpStatusCode.OK,good.StatusCode);await using var db=f.Api.Context();Assert.Equal(1,await db.Set<AuditLog>().CountAsync(x=>x.Action=="comparison.reviewed"));}
    [Theory][InlineData(9,true,false)][InlineData(10,true,true)][InlineData(2000,true,true)][InlineData(2001,true,false)][InlineData(10,false,false)]
    public async Task RiskAcceptanceRequiresStrongConfirmationAndCommentBounds(int count,bool confirm,bool success)
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();using var r=await f.ReviewAsync(id,hash,comment:"  "+string.Concat(Enumerable.Repeat("😀",count))+"  ",confirm:confirm);Assert.Equal(success?HttpStatusCode.OK:HttpStatusCode.UnprocessableEntity,r.StatusCode);}
    [Fact] public async Task InvalidCannotBeReviewed()
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();await using(var db=f.Api.Context()){(await db.Set<ApiVersion>().SingleAsync(x=>x.Id==f.Target.Id)).OpenapiDocument="{\"openapi\":\"3.0.3\",\"paths\":[]}";await db.SaveChangesAsync();}var (id,hash)=await f.ComparisonAsync();using var r=await f.ReviewAsync(id,hash);Assert.Equal(HttpStatusCode.UnprocessableEntity,r.StatusCode);}
    [Theory][InlineData("approve",403)][InlineData("readonly",403)][InlineData("environment",404)][InlineData("schema",404)]
    public async Task ApproveRequiresProjectWriteScopeAndAllReadPermissions(string mode,int status)
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();if(mode=="approve")await f.RevokeAsync("api.approve");if(mode=="schema")await f.RevokeAsync("api.schema.read");if(mode is "readonly" or "environment"){await using var db=f.Api.Context();var grant=await db.Set<UserProjectScope>().SingleAsync(x=>x.UserId==f.Api.User.Id);if(mode=="readonly")grant.AccessMode="read_only";else{grant.ProjectId=f.Api.Project.Id;grant.EnvironmentId=f.Api.Environment.Id;}await db.SaveChangesAsync();}using var r=await f.ReviewAsync(id,hash);Assert.Equal(status,(int)r.StatusCode);}
    [Fact] public async Task ReviewAppendsWithoutApprovalTaskAndReplaysHistoricalAfterEdit()
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();var key=Guid.NewGuid().ToString("N");using var first=await f.ReviewAsync(id,hash,key:key);first.EnsureSuccessStatusCode();var original=await first.Content.ReadAsStringAsync();await using(var db=f.Api.Context()){(await db.Set<ApiVersion>().SingleAsync(x=>x.Id==f.Target.Id)).Revision++;await db.SaveChangesAsync();}using var again=await f.ReviewAsync(id,hash,key:key);Assert.Equal(original,await again.Content.ReadAsStringAsync());using var stale=await f.ReviewAsync(id,hash);Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);await using(var db=f.Api.Context()){Assert.Equal(1,await db.Set<ApiVersionRiskReview>().CountAsync());Assert.Equal(0,await db.Set<ApprovalTask>().CountAsync());Assert.Equal(1,await db.Set<AuditLog>().CountAsync(x=>x.Action=="comparison.risk_accepted"));Assert.DoesNotContain("已评估风险",(await db.Set<AuditLog>().SingleAsync(x=>x.Action=="comparison.risk_accepted")).AfterJson);}await f.RevokeAsync("api.approve");using var denied=await f.ReviewAsync(id,hash,key:key);Assert.Equal(HttpStatusCode.Forbidden,denied.StatusCode);}
    [Theory][InlineData("from")][InlineData("to")][InlineData("delete")][InlineData("scope")]
    public async Task EitherVersionEditDeleteOrScopeMoveInvalidatesReview(string change)
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();await using(var db=f.Api.Context()){if(change=="scope"){var project=new Project {OrganizationId=f.Api.Organization.Id,Code="MOVE",Name="Move"};db.Add(project);(await db.Set<Api>().SingleAsync(x=>x.Id==f.Api.Api.Id)).ProjectId=project.Id;}else{var v=await db.Set<ApiVersion>().SingleAsync(x=>x.Id==(change=="from"?f.Api.Version.Id:f.Target.Id));if(change=="delete"){db.RemoveRange(await db.Set<ApiParameter>().Where(x=>x.ApiVersionId==v.Id).ToArrayAsync());db.Remove(v);}else v.Revision++;}await db.SaveChangesAsync();}using var r=await f.ReviewAsync(id,hash);Assert.Equal(change=="scope"?HttpStatusCode.NotFound:HttpStatusCode.Conflict,r.StatusCode);}
    [Fact] public async Task AuthorizationChangeAndReviewShareTransactionLock()
    {await using var f=new ComparisonFixture();await f.InitializeAsync();await f.GrantReviewAsync();var (id,hash)=await f.ComparisonAsync();await using var db=f.Api.Context();await using var tx=await db.Database.BeginTransactionAsync();await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(8901202)");var permission=await db.Set<Permission>().SingleAsync(x=>x.Code=="api.approve");db.RemoveRange(await db.Set<RolePermission>().Where(x=>x.PermissionId==permission.Id).ToArrayAsync());await db.SaveChangesAsync();var pending=f.ReviewAsync(id,hash);await Task.Delay(200);Assert.False(pending.IsCompleted);await tx.CommitAsync();using var r=await pending;Assert.Equal(HttpStatusCode.Forbidden,r.StatusCode);Assert.Equal(0,await db.Set<ApiVersionRiskReview>().CountAsync());}
}
