<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk"/><PackageReference Include="xunit"/><PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference><ProjectReference Include="../../src/WebApi.Infrastructure/WebApi.Infrastructure.csproj"/><ProjectReference Include="../../src/WebApi.ControlPlane/WebApi.ControlPlane.csproj"/><ProjectReference Include="../../src/WebApi.Migrator/WebApi.Migrator.csproj"/><None Include="../../deploy/initial-core.sql" Link="initial-core.sql" CopyToOutputDirectory="PreserveNewest"/></ItemGroup></Project>
