import {useEffect,useReducer,useRef} from 'react';
import {apiRequest,ApiError} from '../api/client';
import {useSession} from '../auth/SessionProvider';
import {useWorkspace} from '../Shell';
import {Editor,type Field} from '../ui';
import type {Resource} from '../api/types';
import {normalizeAccessSettings,buildAddressTemplate} from './access-address.mjs';
import {createAccessState,accessReducer} from './access-state.mjs';
const fields:Field[]=[{key:'code',label:'环境编码',required:true},{key:'name',label:'环境名称',required:true},{key:'status',label:'状态',options:[{value:'Active',label:'启用'},{value:'Disabled',label:'停用'}]},{key:'isProduction',label:'生产环境',type:'checkbox'},{key:'sortOrder',label:'排序',type:'number'},{key:'releasePolicyId',label:'审批模板 ID',help:'生产发布使用组织内已启用的审批模板'},{key:'gatewayPublicUrl',label:'Gateway 对外访问地址',help:'例如 https://api-test.company.com；只填写协议、域名和端口'},{key:'gatewayInternalUrl',label:'Gateway 内网访问地址',help:'可选；仅环境编辑者可读取，不是业务上游地址'},{key:'basePath',label:'API 外部路径前缀',help:'例如 /gateway；反向代理必须剥离此前缀，Route 路径保持不变'}];
export function EnvironmentAccessEditor({environment,onSaved,onClose}:{environment:Partial<Resource>&{projectId:string};onSaved:()=>void;onClose:()=>void}){
 const ws=useWorkspace(),session=useSession();const project=ws.tree.projects.find(p=>p.id===environment.projectId);const scope=project?.organizationId?{organizationId:project.organizationId,projectId:project.id,environmentId:environment.id||undefined}:undefined;
 const authorized=!!scope&&session.can('environment.write',scope,true),identity=JSON.stringify([environment.id||environment.projectId,session.user?.id,session.user?.permissions,session.user?.scopes]);
 const[state,dispatch]=useReducer(accessReducer,createAccessState(identity,authorized));const active=useRef(true),originalIdentity=useRef(identity);
 useEffect(()=>{const controller=new AbortController();active.current=true;
  const invalidate=()=>{controller.abort();dispatch({type:'invalidate'});onClose();};window.addEventListener('session-expired',invalidate);window.addEventListener('permission-refresh',invalidate);
  if(authorized){const load=environment.id?apiRequest<Record<string,any>>(`/environments/${environment.id}`,{signal:controller.signal}):Promise.resolve({code:'',name:'',status:'Active',isProduction:false,sortOrder:0,releasePolicyId:null,gatewayPublicUrl:null,gatewayInternalUrl:null,basePath:'/'});void load.then(detail=>{if(active.current&&!controller.signal.aborted)dispatch({type:'loaded',identity,epoch:0,detail});}).catch(error=>{if(active.current&&!controller.signal.aborted)dispatch({type:'failed',status:error instanceof ApiError?error.status:0,message:error.message});});}
  return()=>{active.current=false;controller.abort();window.removeEventListener('session-expired',invalidate);window.removeEventListener('permission-refresh',invalidate);};
 },[]);
 useEffect(()=>{if(!authorized||identity!==originalIdentity.current){dispatch({type:'invalidate'});onClose();}},[authorized,identity]);
 if(!authorized||identity!==originalIdentity.current)return null;
 if(!state.detail)return <div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="读取环境地址"><h2>环境访问地址</h2><p role={state.error?'alert':'status'}>{state.error||'正在读取环境详情…'}</p><button className="btn" onClick={onClose}>关闭</button></section></div>;
 return <Editor explicitSubmitOnly title={environment.id?'编辑环境 · '+environment.name:'新建环境'} allowed={authorized&&state.authorized} fields={fields} initial={state.draft} close={onClose} help="保存地址元数据；DNS、TLS 与负载均衡需另行配置" loadLatest={environment.id?()=>apiRequest(`/environments/${environment.id}`):undefined}
 renderFields={(value,change)=>{let preview:string|null=null,previewError='';try{preview=buildAddressTemplate(value,'/mes/orders/{id}');}catch(e){previewError=(e as Error).message;}
 const update=(key:string,next:unknown)=>{dispatch({type:'edit',key,value:next});change(key,next);};
 return <><div className="environment-access-intro"><strong>{environment.id?`${environment.code} · ${environment.name}`:'当前项目新环境'}</strong><p>每个环境独立入口。业务 API 地址在 Destination 配置，对外域名在此配置。</p></div>{fields.map(f=><label key={f.key}>{f.label}{f.required&&' *'}{f.type==='checkbox'?<input type="checkbox" checked={!!value[f.key]} onChange={e=>update(f.key,e.target.checked)}/>:f.options?<select value={value[f.key]??''} onChange={e=>update(f.key,e.target.value)}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input required={f.required} type={f.type||'text'} value={value[f.key]??''} maxLength={f.key.startsWith('gateway')?2048:f.key==='basePath'?512:undefined} onChange={e=>update(f.key,e.target.value)}/>}<small>{f.help}</small></label>)}<div className="environment-access-preview"><strong>客户端 API 地址预览 · 示例路径</strong><code>{previewError||preview||'尚未配置公开入口'}</code><p>示例路径为 /mes/orders/&#123;id&#125;。实际接口地址请查看 API 详情或路由页面。</p><p>保存不会开通域名，也不会发起网络请求。</p></div></>;}}
 save={async(value,key,fresh)=>{if(!authorized||!active.current)throw Error('当前环境编辑权限已失效');const normalized=normalizeAccessSettings(value,!!value.isProduction);try{await apiRequest(environment.id?`/environments/${environment.id}`:`/projects/${environment.projectId}/environments`,{method:environment.id?'PUT':'POST',body:{...normalized,releasePolicyId:value.releasePolicyId||null,sortOrder:Number(value.sortOrder||0)},etag:environment.id?`"${fresh?.revision??state.detail!.revision}"`:undefined,idempotencyKey:key});if(active.current)onSaved();}catch(e){if(active.current)dispatch({type:'failed',status:e instanceof ApiError?e.status:0,message:(e as Error).message});throw e;}}}/>;
}
