import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {buildRelease} from '../runtime/build.mjs';import {initializeRuntime,operateRuntime,loadRelease} from '../runtime/lifecycle.mjs';import {prepareContext} from '../runtime/context.mjs';import {loadState,writePrivate,safeFile} from '../runtime/state.mjs';import {inspectResources,assertOwnership} from '../runtime/docker.mjs';import {freePorts,cleanupFixture} from '../runtime/acceptance.mjs';import {prepareScenario,until} from '../runtime/acceptance-scenario.mjs';import {coldBackup,restoreColdBackup} from '../runtime/acceptance-backup.mjs';import {resolveOwnedConsoleProxy,synchronizeConsoleProxyTrust} from './proxy-trust.mjs';import {getRuntimeStatus} from '../runtime/status.mjs';import {LocalClient} from '../local-client.mjs';import {validateFixture} from '../runtime/fixture-guard.mjs';
const exec=promisify(execFile),sha=bytes=>createHash('sha256').update(bytes).digest('hex');
export function finalizeSecurityAcceptance(proof){const required=['sharedBudget','audit','redisFailure','proxyRecreation','headerBoundary','backupRestore'];const missing=required.filter(k=>proof.checks?.[k]!==true);if(!/^[a-f0-9]{40}$/.test(proof.sourceRevision??''))missing.push('sourceRevision');if(!/^sha256:[a-f0-9]{64}$/.test(proof.imageId??''))missing.push('imageId');if(!proof.ui?.verified)missing.push('ui');if(!proof.review?.verified)missing.push('review');return{...proof,complete:missing.length===0,missing};}
class AuthProbe{
 constructor(base){this.base=base;this.cookies=new Map();}
 cookie(){return [...this.cookies].map(([k,v])=>k+'='+v).join('; ');}
 capture(response){for(const cookie of response.headers.getSetCookie()){const first=cookie.split(';')[0],i=first.indexOf('=');this.cookies.set(first.slice(0,i),first.slice(i+1));}}
 async initialize(){const response=await fetch(this.base+'/api/v1/auth/csrf',{headers:{Cookie:this.cookie()},signal:AbortSignal.timeout(5000)});assert.equal(response.status,200);this.capture(response);this.csrf=(await response.json()).token;}
 async login(username,password){const response=await fetch(this.base+'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':this.csrf,Cookie:this.cookie(),'X-Forwarded-For':'198.51.100.99'},body:JSON.stringify({username,password}),signal:AbortSignal.timeout(10000)});this.capture(response);const body=await response.json();return{status:response.status,code:body.code,cookieIssued:response.headers.getSetCookie().some(c=>c.includes('.Session=')&&!c.includes('.Session=;')),retryAfter:response.headers.get('Retry-After'),noStore:response.headers.get('Cache-Control')?.includes('no-store')};}
}
async function database(ctx,sql){const result=await ctx.compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',sql);return result.stdout.trim();}
async function headerBoundary(state,credential){for(const port of [state.ports.gatewayA,state.ports.gatewayB]){const response=await fetch('http://127.0.0.1:'+port+'/orders',{headers:{'X-API-Key':credential,'X-WebApi-Fake':'forged','X-WebApi-Subject':'forged','X-WebApi-Application-Id':'forged','X-WebApi-Trace-Id':'forged','X-WebApi-Deployment-Sequence':'999'},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);const body=await response.json();assert.equal(body.receivedApiKey,false);assert.notEqual(body.traceId,'forged');assert.equal(body.deploymentSequence,1);assert.notEqual(response.headers.get('X-WebApi-Trace-Id'),'forged');assert.equal(response.headers.get('X-WebApi-Deployment-Sequence'),'1');assert.equal(response.headers.get('X-WebApi-Fake'),null);}}
async function shadowControlPlane(ctx){const base=JSON.parse(await fs.readFile(path.join(ctx.directory,'artifacts',ctx.release.sourceRevision,'deploy/compose.runtime.yml'),'utf8'));const config=JSON.parse(await fs.readFile(path.join(ctx.directory,'runtime-config.json'),'utf8'));const service=structuredClone(base.services['control-plane']);service.environment={...service.environment,...config.services['control-plane'].environment};service.ports=[{target:8080,published:'0',host_ip:'127.0.0.1'}];const file=path.join(ctx.directory,'security-shadow.json');await writePrivate(file,{services:{'control-plane-b':service}});ctx.files.push('-f',file);await ctx.compose('up','-d','--no-deps','control-plane-b');const endpoint='http://'+(await ctx.compose('port','control-plane-b','8080')).stdout.trim();await until(async()=>{try{return (await fetch(endpoint+'/api/v1/auth/csrf',{signal:AbortSignal.timeout(3000)})).status;}catch{return 0;}},x=>x===200,45);return endpoint;}
async function persistProof(directory,proof){await writePrivate(path.join(directory,'security-proof.json'),finalizeSecurityAcceptance(proof));}
export async function runSecurityAcceptance({revision}){
 if(!/^[a-f0-9]{40}$/.test(revision??''))throw Error('Explicit full immutable source commit required.');
 const definition=JSON.parse((await exec('git',['show',revision+':deploy/compose.runtime.yml'])).stdout);if(!definition.services?.['control-plane']?.environment?.Authentication__LoginProtection__HmacSecretFile)throw Error('Revision does not contain login protection deployment support.');
 const buildDirectory=path.resolve('.runtime/security-build/'+revision);const release=await buildRelease({revision,directory:buildDirectory,nugetSeedVolume:'webapi-enterprise-core-test_nuget-test'});
 const projectName='webapi-enterprise-local-test-'+randomUUID(),directory=path.resolve('.runtime/tests/'+projectName);let ctx;const proof={complete:false,sourceRevision:release.sourceRevision,imageId:release.imageId,projectName,checks:{},ui:{verified:false},review:{verified:false},classification:'isolated-local-security-acceptance',limitations:['Production TLS, real ingress proxies and enterprise infrastructure are not accepted here.']};
 try{
  const state=await initializeRuntime({directory,projectName,ports:await freePorts(),bootstrapUsername:'security-qa-admin',releaseFile:path.join(buildDirectory,'release.json')});
  const scenario=await prepareScenario(directory,state,prepareContext);ctx=await prepareContext(directory,scenario.state,release);const published=await scenario.publish();assert.equal(published.state,'Succeeded');const credential=await fs.readFile(path.join(directory,'credential'),'utf8');await headerBoundary(scenario.state,credential);proof.checks.headerBoundary=true;
  const user=await scenario.admin.request('/users',{method:'POST',body:{username:'security-budget-'+randomUUID(),displayName:'合成限速验收账号',password:scenario.password}}),faultUser=await scenario.admin.request('/users',{method:'POST',body:{username:'security-fault-'+randomUUID(),displayName:'合成故障验收账号',password:scenario.password}});
  const secondUrl=await shadowControlPlane(ctx),probes=[new AuthProbe(scenario.endpoint),new AuthProbe(secondUrl)];await Promise.all(probes.map(p=>p.initialize()));
  const outcomes=await Promise.all(Array.from({length:100},(_,i)=>probes[i%2].login(user.username,'synthetic-wrong-password')));assert.equal(outcomes.filter(r=>r.status===401).length,10);assert.equal(outcomes.filter(r=>r.status===429).length,90);assert.ok(outcomes.filter(r=>r.status===429).every(r=>r.code==='login_rate_limited'&&!r.cookieIssued&&r.noStore&&/^[1-9]\d*$/.test(r.retryAfter??'')));proof.checks.sharedBudget=true;proof.budget={attempts:100,admitted:10,rejected:90,instances:2};
  const audit=JSON.parse(await database(ctx,"select json_build_object('failed',count(*) filter(where action='auth.login.failed'),'throttled',count(*) filter(where action='auth.login.throttled'),'anonymous',bool_and(user_id is null and organization_id is null and project_id is null and environment_id is null)) from audit_logs where action in ('auth.login.failed','auth.login.throttled')"));assert.equal(audit.failed,10);assert.ok(audit.throttled>=1&&audit.throttled<=2);assert.equal(audit.anonymous,true);proof.checks.audit=true;proof.audit=audit;
  const survivor=new LocalClient(scenario.endpoint);await survivor.login(faultUser.username,scenario.password);await ctx.compose('stop','redis');try{const response=await probes[0].login(faultUser.username,scenario.password);assert.equal(response.status,503);assert.equal(response.code,'login_protection_unavailable');assert.equal(response.cookieIssued,false);assert.equal((await survivor.request('/auth/me')).id,faultUser.id);proof.checks.redisFailure=true;}finally{await ctx.compose('up','-d','--wait','redis');}
  const secretFile=path.join(directory,'secrets/login-protection-hmac'),secretHash=sha(await fs.readFile(secretFile)),before=await resolveOwnedConsoleProxy(scenario.state);await ctx.compose('up','-d','--no-deps','--force-recreate','console');const after=await resolveOwnedConsoleProxy(scenario.state);assert.notEqual(before.containerId,after.containerId);assert.notEqual((await getRuntimeStatus(scenario.state,{directory})).loginProtection.state,'Ready');await synchronizeConsoleProxyTrust(ctx);assert.equal((await getRuntimeStatus(scenario.state,{directory})).loginProtection.state,'Ready');proof.checks.proxyRecreation=true;
  // The shadow is stopped before a cold backup so no management writer can remain active.
  await ctx.compose('stop','control-plane-b');const backup=path.join(directory,'security-backup');await coldBackup(ctx,backup);const restoredProject='webapi-enterprise-local-test-'+randomUUID(),restoredDirectory=path.resolve('.runtime/tests/'+restoredProject);const restored=await restoreColdBackup({target:backup,projectName:restoredProject,directory:restoredDirectory,ports:await freePorts(),contextFactory:prepareContext});await operateRuntime('start',restored.state,{directory:restoredDirectory});const restoredClient=new LocalClient('http://127.0.0.1:'+restored.state.ports.console);await restoredClient.login(faultUser.username,scenario.password);assert.equal((await restoredClient.request('/auth/me')).id,faultUser.id);assert.equal(sha(await fs.readFile(path.join(restoredDirectory,'secrets/login-protection-hmac'))),secretHash);assert.equal((await getRuntimeStatus(restored.state,{directory:restoredDirectory})).loginProtection.state,'Ready');await cleanupFixture(restoredDirectory,release);proof.checks.backupRestore=true;
  await writePrivate(path.join(directory,'security-ui-fixture.json'),{sourceRevision:release.sourceRevision,consoleUrl:scenario.endpoint,username:scenario.state.bootstrapUsername,password:scenario.password,throttleUsername:user.username,faultUsername:faultUser.username});await persistProof(directory,proof);return{...finalizeSecurityAcceptance(proof),directory,consoleUrl:scenario.endpoint,retainedForUi:true};
 }catch(error){if(ctx)await persistProof(directory,{...proof,error:'Acceptance stage failed; inspect owned fixture logs.'});throw Object.assign(new Error('Security acceptance failed; owned fixture retained: '+projectName),{cause:error});}
}
async function finalizeDirectory(directory){const state=await loadState(directory);validateFixture(state.projectName,directory);const file=path.join(directory,'security-proof.json');await safeFile(file);const proof=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(proof.projectName,state.projectName);const ui=JSON.parse(await fs.readFile(path.join(directory,'ui-proof.json'),'utf8')),review=JSON.parse(await fs.readFile(path.join(directory,'source-review.json'),'utf8'));assert.equal(ui.sourceRevision,proof.sourceRevision);assert.equal(review.sourceRevision,proof.sourceRevision);const result=finalizeSecurityAcceptance({...proof,ui,review});if(!result.complete)throw Error('Security acceptance evidence incomplete: '+result.missing.join(','));assertOwnership(state,await inspectResources(state));const release=await loadRelease(path.join(directory,'release.json'));result.cleanup=await cleanupFixture(directory,release);await fs.mkdir('docs/evidence/security-hardening',{recursive:true});await fs.writeFile('docs/evidence/security-hardening/verification.json',JSON.stringify(result,null,2)+'\n');return result;}
if(process.argv[1]===fileURLToPath(import.meta.url)){try{const args=process.argv.slice(2);if(args[0]==='--finalize'&&args.length===2){const result=await finalizeDirectory(path.resolve(args[1]));console.log('Security acceptance complete='+result.complete);}else if(args[0]==='--revision'&&args.length===2){const result=await runSecurityAcceptance({revision:args[1]});console.log(JSON.stringify({complete:result.complete,sourceRevision:result.sourceRevision,directory:result.directory,consoleUrl:result.consoleUrl,missing:result.missing}));}else throw Error('Usage: acceptance.mjs --revision <full commit> | --finalize <owned fixture directory>');}catch(error){console.error(error.message);process.exitCode=1;}}
