import fs from 'node:fs/promises';import path from 'node:path';import {randomBytes,createHash} from 'node:crypto';
import {RuntimeError,ownedDirectory,safeFile,loadState,writePrivate} from '../runtime/state.mjs';
export const loginProtectionReceiptName='login-protection-secret-receipt.json';
const hash=raw=>createHash('sha256').update(raw).digest('hex');
async function exists(file){try{await fs.lstat(file);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}}
async function readSecret(file){await safeFile(file);const st=await fs.stat(file);if(st.size>256)throw new RuntimeError('Login protection secret encoding is invalid.',3);const raw=await fs.readFile(file),text=raw.toString('utf8').trim(),key=Buffer.from(text,'base64');if(key.length!==32||key.toString('base64')!==text)throw new RuntimeError('Login protection secret encoding is invalid.',3);return hash(raw);}
function validate(receipt,state){if(!receipt||Object.keys(receipt).sort().join(',')!=='file,ownerId,projectName,schemaVersion,sha256'||receipt.schemaVersion!==1||receipt.ownerId!==state.ownerId||receipt.projectName!==state.projectName||receipt.file!=='secrets/login-protection-hmac'||!/^([a-f0-9]{64})$/.test(receipt.sha256))throw new RuntimeError('Login protection secret receipt owner mismatch.',3);}
async function location(directory,state){directory=await ownedDirectory(directory);const current=await loadState(directory);if(current.ownerId!==state.ownerId||current.projectName!==state.projectName)throw new RuntimeError('Login protection runtime owner mismatch.',3);await ownedDirectory(path.join(directory,'secrets'));return{directory,file:path.join(directory,'secrets/login-protection-hmac'),receiptFile:path.join(directory,loginProtectionReceiptName)};}
export async function assertLoginProtectionSecret(directory,state){const paths=await location(directory,state);await safeFile(paths.receiptFile);if((await fs.stat(paths.receiptFile)).size>1024)throw new RuntimeError('Login protection receipt size invalid.',3);const receipt=JSON.parse(await fs.readFile(paths.receiptFile,'utf8'));validate(receipt,state);if(!await exists(paths.file))throw new RuntimeError('Recorded login protection secret is missing; restore backup.',3);if(await readSecret(paths.file)!==receipt.sha256)throw new RuntimeError('Login protection secret checksum mismatch; refuse rotation.',3);return{file:paths.file,receipt};}
export async function prepareLoginProtectionSecret(directory,state,{allowCreate=false}={}){
 const paths=await location(directory,state),lock=path.join(paths.directory,'login-protection-secret.lock');let handle;
 try{handle=await fs.open(lock,'wx',0o600);}catch(e){if(e.code==='EEXIST')throw new RuntimeError('Login protection preparation is already active.',3);throw e;}
 try{
  if(await exists(paths.receiptFile))return await assertLoginProtectionSecret(directory,state);
  if(!allowCreate)throw new RuntimeError('Login protection secret missing; explicit preparation required.',3);
  if(!await exists(paths.file)){const out=await fs.open(paths.file,'wx',0o600);try{await out.writeFile(randomBytes(32).toString('base64')+'\n');}finally{await out.close();}}
  const receipt={schemaVersion:1,ownerId:state.ownerId,projectName:state.projectName,file:'secrets/login-protection-hmac',sha256:await readSecret(paths.file)};await writePrivate(paths.receiptFile,receipt);return{file:paths.file,receipt};
 }finally{await handle.close();await fs.unlink(lock);}
}
export async function copyLoginProtectionBackup(directory,target,state){if(!await exists(path.join(directory,loginProtectionReceiptName)))return null;const value=await assertLoginProtectionSecret(directory,state);await writePrivate(path.join(target,loginProtectionReceiptName),value.receipt);return value;}
export async function restoreLoginProtectionBackup(target,directory,state){if(!await exists(path.join(target,loginProtectionReceiptName)))return null;const original=JSON.parse(await fs.readFile(path.join(target,'runtime.json'),'utf8'));await safeFile(path.join(target,loginProtectionReceiptName));const receipt=JSON.parse(await fs.readFile(path.join(target,loginProtectionReceiptName),'utf8'));validate(receipt,original);if(await readSecret(path.join(directory,'secrets/login-protection-hmac'))!==receipt.sha256)throw new RuntimeError('Restored login protection secret checksum mismatch.',3);await writePrivate(path.join(directory,loginProtectionReceiptName),{...receipt,ownerId:state.ownerId,projectName:state.projectName});return assertLoginProtectionSecret(directory,state);}
export async function assertLoginProtectionSecretVolume(state,receipt,image,{run}={}){const {docker,assertOwnership}=await import('../runtime/docker.mjs');run??=docker;const name=state.projectName+'_secrets-control-plane';const volumes=JSON.parse((await run(['volume','inspect',name])).stdout);if(volumes.length!==1||volumes[0].Name!==name)throw new RuntimeError('Login protection secret volume missing.',3);assertOwnership(state,volumes);if(!/^.+@sha256:[a-f0-9]{64}$/.test(image??''))throw new RuntimeError('Login secret probe requires pinned SDK image.',3);const result=await run(['run','--rm','--user','10001:10001','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges:true','--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId,'--mount','type=volume,src='+name+',dst=/run/secrets,readonly',image,'sha256sum','/run/secrets/login-protection-hmac']);if(result.stdout.trim().split(/\s+/)[0]!==receipt.sha256)throw new RuntimeError('Login protection mounted secret checksum mismatch.',3);}
