import {test} from 'node:test';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {docker,inspectResources} from '../../../scripts/runtime/docker.mjs';import {pipelineAttemptTimeoutSql} from '../../../scripts/delivery/pipeline-fault-clock.mjs';
const revision=process.env.WEBAPI_PIPELINE_REVISION;
test('actual fixed PostgreSQL schema rejects old stage clock and accepts only its owned current attempt',{skip:process.env.WEBAPI_PIPELINE_DB_PROBE!=='1'},async()=>{assert.match(revision??'',/^[a-f0-9]{40}$/);
const exec=promisify(execFile),images=JSON.parse((await exec('git',['show',revision+':deploy/images.lock.json'])).stdout),state={projectName:'webapi-enterprise-local-test-'+randomUUID(),ownerId:randomUUID()},name=state.projectName+'-postgres-1',ids={attemptId:randomUUID(),stageId:randomUUID(),projectId:randomUUID()},run=randomUUID(),env=randomUUID();
const seed=`CREATE TEMP TABLE release_pipeline_run_stages (LIKE public.release_pipeline_run_stages INCLUDING ALL);CREATE TEMP TABLE release_pipeline_stage_attempts (LIKE public.release_pipeline_stage_attempts INCLUDING ALL);INSERT INTO release_pipeline_run_stages(id,run_id,project_id,stage_order,environment_id,profile_hash,current_attempt_id) VALUES('${ids.stageId}','${run}','${ids.projectId}',2,'${env}',repeat('a',64),'${ids.attemptId}');INSERT INTO release_pipeline_stage_attempts(id,run_stage_id,run_id,project_id,environment_id,attempt_no,activated_at,deadline_at,status) VALUES('${ids.attemptId}','${ids.stageId}','${run}','${ids.projectId}','${env}',1,now()-interval '5 seconds',now()+interval '1 hour','Active');`;
try{
 await docker(['run','-d','--name',name,'--network','none','--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId,'--tmpfs','/var/lib/postgresql:rw,size=268435456','-e','POSTGRES_HOST_AUTH_METHOD=trust','-e','POSTGRES_DB=pipeline_probe',images.postgres]);
 for(let i=0;i<60;i++){const r=await docker(['exec',name,'psql','-U','postgres','-d','pipeline_probe','-At','-v','ON_ERROR_STOP=1','-c','SELECT 1'],{allowFailure:true});if(r.exitCode===0&&r.stdout.trim()==='1')break;if(i===59)throw Error('Probe PostgreSQL startup failed');await new Promise(r=>setTimeout(r,250));}
 await docker(['exec','-i',name,'psql','-U','postgres','-d','pipeline_probe','-v','ON_ERROR_STOP=1'],{input:(await exec('git',['show',revision+':deploy/initial-core.sql'],{maxBuffer:4*1024*1024})).stdout});
 const bad=await docker(['exec','-i',name,'psql','-U','postgres','-d','pipeline_probe','-v','ON_ERROR_STOP=1'],{input:seed+`UPDATE release_pipeline_stage_attempts SET deadline_at=now()-interval '1 second' WHERE id='${ids.attemptId}'; UPDATE release_pipeline_run_stages SET deadline_at=now()-interval '1 second' WHERE id='${ids.stageId}';`,allowFailure:true});assert.notEqual(bad.exitCode,0);assert.match(bad.stderr,/column "deadline_at".*does not exist/);
 const good=await docker(['exec','-i',name,'psql','-U','postgres','-d','pipeline_probe','-At','-v','ON_ERROR_STOP=1'],{input:seed+pipelineAttemptTimeoutSql(ids)+`;SELECT deadline_at>activated_at AND deadline_at<now() FROM release_pipeline_stage_attempts WHERE id='${ids.attemptId}';`});assert.match(good.stdout,/UPDATE 1/);assert.match(good.stdout,/\nt\s*$/);console.log(JSON.stringify({actualDatabase:true,immutableMigrationApplied:true,oldMissingColumnReproduced:true,newCurrentAttemptUpdated:1,deadlineLegalAndPast:true}));
}finally{await docker(['rm','-fv',name],{allowFailure:true});const remaining=await inspectResources(state);assert.equal(remaining.length,0);console.log(JSON.stringify({remainingOwnedResources:remaining.length}));}

});
