using WebApi.Contracts.Releases;
using WebApi.ControlPlane.Governance;
using WebApi.ControlPlane.Security;
using WebApi.Infrastructure.Delivery;
namespace WebApi.ControlPlane.Releases;
public static class DeliveryEndpoints
{
    public static void MapDelivery(this WebApplication app)
    {
        var g=app.MapGroup("/api/v1").RequireAuthorization().AddEndpointFilter<RequestValidationFilter>();
        g.MapGet("/projects/{id:guid}/delivery-policy",async(Guid id,HttpContext ctx,ProjectDeliveryPolicyService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.GetAsync(id,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        g.MapPut("/projects/{id:guid}/delivery-policy",async(Guid id,SaveDeliveryPolicyRequest request,HttpContext ctx,ProjectDeliveryPolicyService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return GovernanceEndpoints.Command(ctx,await service.SaveAsync(id,request,ctx.Request.Headers.IfMatch,ctx.Actor(),ct));});
        g.MapPost("/release-promotions",async(CreatePromotionRequest request,HttpContext ctx,ReleasePromotionService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.CreateAsync(request.ArtifactId,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        g.MapGet("/release-promotions/{id:guid}",async(Guid id,HttpContext ctx,ReleasePromotionService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.GetAsync(id,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        g.MapGet("/release-promotions/{id:guid}/verification-context",async(Guid id,HttpContext ctx,ProductionVerificationService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.ContextAsync(id,ctx.Actor(),ct));});
        g.MapGet("/release-promotions/{id:guid}/verifications",async(Guid id,HttpContext ctx,ProductionVerificationService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.ListAsync(id,ctx.Actor(),ct));});
        g.MapPost("/release-promotions/{id:guid}/verifications",async(Guid id,RecordVerificationRequest request,HttpContext ctx,ProductionVerificationService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.RecordAsync(id,request,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        g.MapPost("/release-promotions/{id:guid}/precheck",async(Guid id,PromotionPrecheckRequest request,HttpContext ctx,PromotionPrecheckService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.PrecheckAsync(id,request,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        foreach(var action in new[]{"submit","cancel"})g.MapPost("/release-promotions/{id:guid}/"+action,async(Guid id,HttpContext ctx,ReleasePromotionService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=action=="submit"?await service.SubmitAsync(id,ctx.Request.Headers.IfMatch,ctx.Actor(),ct):await service.CancelAsync(id,ctx.Request.Headers.IfMatch,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        foreach(var suffix in new[]{"mapping","mappings"})g.MapPut("/release-promotions/{id:guid}/"+suffix,async(Guid id,PromotionMappingRequest request,HttpContext ctx,PromotionMappingService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return GovernanceEndpoints.Command(ctx,await service.SaveAsync(id,request,ctx.Request.Headers.IfMatch,ctx.Actor(),ct));});
        g.MapPost("/releases/{id:guid}/artifacts",async(Guid id,HttpContext ctx,ReleaseArtifactService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.CreateAsync(id,ctx.Actor(),ct));});
        g.MapGet("/release-artifacts/{id:guid}",async(Guid id,HttpContext ctx,ReleaseArtifactService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.GetAsync(id,ctx.Actor(),ct));});
        g.MapPost("/release-artifacts/{id:guid}/verifications",async(Guid id,RecordVerificationRequest request,HttpContext ctx,ReleaseVerificationService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.RecordSourceAsync(id,request,ctx.Actor(),ct));});
        g.MapGet("/release-artifacts/{id:guid}/verifications",async(Guid id,HttpContext ctx,ReleaseVerificationService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.ListSourceAsync(id,ctx.Actor(),ct));});
        g.MapPost("/release-artifacts/{id:guid}/test-acceptances",async(Guid id,RequestTestAcceptanceRequest request,HttpContext ctx,TestAcceptanceService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.RequestAsync(id,request.VerificationIds,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        g.MapGet("/release-artifacts/{id:guid}/test-acceptances",async(Guid id,HttpContext ctx,TestAcceptanceService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";return Results.Ok(await service.ListAsync(id,ctx.Actor(),ct));});
        g.MapGet("/test-acceptances/{id:guid}",async(Guid id,HttpContext ctx,TestAcceptanceService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.GetAsync(id,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
        foreach(var action in new[]{"accept","reject","revoke"})g.MapPost("/test-acceptances/{id:guid}/"+action,async(Guid id,TestAcceptanceActionRequest request,HttpContext ctx,TestAcceptanceService service,CancellationToken ct)=>{ctx.Response.Headers.CacheControl="no-store";var value=await service.ActAsync(id,action,request.Comment,ctx.Request.Headers.IfMatch,ctx.Actor(),ct);ctx.Response.Headers.ETag=WebApi.Contracts.Common.RevisionTag.Format(value.Revision);return Results.Ok(value);});
    }
}
