namespace WebApi.Contracts.Releases;
public sealed record SaveDeliveryPolicyRequest(Guid SourceEnvironmentId,Guid TargetEnvironmentId,string Mode,IReadOnlyList<string> RequiredTestTypes,int VerificationValidityMinutes);
public sealed record DeliveryPolicyDto(Guid? Id,Guid ProjectId,Guid? SourceEnvironmentId,Guid? TargetEnvironmentId,string Mode,IReadOnlyList<string> RequiredTestTypes,int VerificationValidityMinutes,long Revision);
public sealed record ArtifactPolicyTemplate(string Type,string FrozenConfig,IReadOnlyList<string> EnvironmentFields,int Priority=0);
public sealed record ArtifactRoute(string Key,Guid ApiId,Guid VersionId,string Path,IReadOnlyList<string> Methods,int Priority,bool Enabled,int? TimeoutTemplate,IReadOnlyList<ArtifactPolicyTemplate> Policies,string AuthenticationMode="ApiKey");
public sealed record ArtifactApiContract(Guid ApiId,Guid VersionId,string Version,long SourceRevision,IReadOnlyList<WebApi.Contracts.Catalog.ParameterDto> Parameters,IReadOnlyList<WebApi.Contracts.Catalog.SchemaDto> Schemas);
public sealed record ArtifactContent(IReadOnlyList<ArtifactApiContract> Apis,IReadOnlyList<ArtifactRoute> Routes);
public sealed record ReleaseArtifactDto(Guid Id,Guid OrganizationId,Guid ProjectId,Guid SourceEnvironmentId,Guid SourceReleaseId,string ArtifactHash,string SourceSnapshotHash,Guid CreatedBy,DateTimeOffset CreatedAt,ArtifactContent Content);
public sealed record RecordVerificationRequest(string Type,string Result,DateTimeOffset StartedAt,DateTimeOffset FinishedAt,Guid? ReportId=null,string Comment="");
public sealed record ReleaseVerificationDto(Guid Id,Guid ArtifactId,Guid? PromotionId,Guid ReleaseId,Guid EnvironmentId,long ConfigVersion,long DeploymentSequence,string SnapshotHash,long AccessAddressRevision,long PolicyRevision,string Phase,string Type,string Result,bool IsManual,Guid? ReportId,string? ReportHash,string Comment,DateTimeOffset StartedAt,DateTimeOffset FinishedAt,DateTimeOffset ExpiresAt,Guid CreatedBy,DateTimeOffset CreatedAt);
public sealed record VerificationReportDto(Guid Id,Guid? ArtifactId,Guid? PromotionId,string ContentType,long SizeBytes,string Sha256,Guid CreatedBy,DateTimeOffset CreatedAt);
public sealed record RequestTestAcceptanceRequest(IReadOnlyList<Guid> VerificationIds);
public sealed record TestAcceptanceActionRequest(string Comment="");
public sealed record TestAcceptanceDto(Guid Id,Guid ArtifactId,Guid SourceEnvironmentId,string ArtifactHash,IReadOnlyList<Guid> VerificationIds,string EvidenceHash,long PolicyRevision,string Status,long Revision,Guid RequestedBy,Guid? ActedBy,string Comment,DateTimeOffset CreatedAt,DateTimeOffset? ActedAt,DateTimeOffset? ExpiresAt);
public sealed record PromotionPolicyMapping(string Type,int Priority,Guid? TargetPolicyId=null,long? TargetPolicyRevision=null);
public sealed record PromotionRouteMapping(string ArtifactRouteKey,Guid? TargetRouteId,Guid ClusterId,int TimeoutMs,IReadOnlyList<PromotionPolicyMapping> Policies);
public sealed record PromotionApplicationMapping(Guid ApplicationId,IReadOnlyList<Guid> CredentialIds,IReadOnlyList<Guid> AuthorizationIds,bool ConfirmSharedCredentialImpact=false);
public sealed record PromotionMappingRequest(IReadOnlyList<PromotionRouteMapping> Routes,IReadOnlyList<PromotionApplicationMapping> Applications);
public sealed record SharedCredentialImpact(Guid ApplicationId,IReadOnlyList<Guid> RetainedApiIds,IReadOnlyList<Guid> RequiredCredentialIds,bool Acknowledged,bool SharedAcrossEnvironments=false);
public sealed record PromotionDto(Guid Id,Guid OrganizationId,Guid ProjectId,Guid ArtifactId,string ArtifactHash,Guid SourceEnvironmentId,Guid TargetEnvironmentId,Guid SourceReleaseId,Guid? TargetReleaseId,Guid? AcceptanceId,string Status,long BaselineConfigVersion,long MappingRevision,string? CandidateHash,long Revision,Guid RequestedBy,DateTimeOffset CreatedAt,DateTimeOffset? CompletedAt,PromotionMappingRequest? Mapping=null,IReadOnlyList<SharedCredentialImpact>? CredentialImpact=null);
