using WebApi.Contracts.Comparisons;
using WebApi.Contracts.Catalog;
using WebApi.Contracts.Applications;
namespace WebApi.Contracts.Releases;
public sealed record ResourceRevision(string Type,Guid Id,long Revision);
public sealed record CreateReleaseRequest(long BaseConfigVersion,IReadOnlyList<Guid> VersionIds,IReadOnlyList<ResourceRevision> ResourceRevisions,IReadOnlyList<Guid>? RiskReviewIds=null);
public sealed record PreviewReleaseRequest(long BaseConfigVersion,IReadOnlyList<Guid> VersionIds);
public sealed record RefreshReleasePreconditionsRequest(IReadOnlyList<ResourceRevision> ResourceRevisions);
public sealed record ApprovalActionRequest(string Comment="",int? ExpectedStepOrder=null,string? ExpectedCandidateHash=null);
public sealed record CreateRollbackRequest(long TargetConfigVersion);
public sealed record ApprovalRule(int StepOrder,string RoleCode,int RequiredCount);
public sealed record SaveApprovalFlowRequest(string Name,IReadOnlyList<ApprovalRule> Steps,bool Enabled=true);
public sealed record ApprovalFlowDto(Guid Id,Guid OrganizationId,string Name,bool Enabled,long Revision,IReadOnlyList<ApprovalRule> Steps);
public sealed record FrozenApiVersion(ApiDto Api,VersionDto Version,IReadOnlyList<ParameterDto> Parameters,IReadOnlyList<SchemaDto> Schemas);
public sealed record FrozenPolicy(Guid Id,string Type,string Config,bool Enabled,long Revision,Guid? SourcePolicyId=null);
public sealed record FrozenBinding(Guid RouteId,Guid PolicyId,int Priority);
public sealed record FrozenCredential(Guid Id,string AccessKey,string SecretHash,string SecretLast4,string Status,DateTimeOffset ValidFrom,DateTimeOffset ExpiresAt,long Revision);
public sealed record FrozenApplication(ApplicationDto Application,IReadOnlyList<FrozenCredential> Credentials,IReadOnlyList<ApplicationPermissionDto> Permissions);
public sealed record FrozenReleaseCandidate(Guid EnvironmentId,Guid OrganizationId,Guid ProjectId,long BaselineConfigVersion,IReadOnlyList<Guid> VersionIds,IReadOnlyList<FrozenApiVersion> Versions,IReadOnlyList<RouteDto> Routes,IReadOnlyList<ClusterDto> Clusters,IReadOnlyList<FrozenPolicy> Policies,IReadOnlyList<FrozenBinding> Bindings,IReadOnlyList<FrozenApplication> Applications,IReadOnlyList<ResourceRevision> ResourceRevisions,IReadOnlyList<FrozenRiskReviewReference>? RiskReviewReferences=null);
public sealed record FrozenApplicationView(ApplicationDto Application,IReadOnlyList<CredentialDto> Credentials,IReadOnlyList<ApplicationPermissionDto> Permissions);
public sealed record FrozenCandidateView(IReadOnlyList<FrozenApiVersion> Versions,IReadOnlyList<RouteDto> Routes,IReadOnlyList<ClusterDto> Clusters,IReadOnlyList<FrozenApplicationView> Applications,IReadOnlyList<ResourceRevision> ResourceRevisions,IReadOnlyList<FrozenPolicy>? Policies=null,IReadOnlyList<FrozenBinding>? Bindings=null,bool? PreconditionsCurrent=null,IReadOnlyList<RiskReviewSummaryDto>? RiskReviews=null);
public sealed record ApprovalTaskDto(Guid Id,int StepOrder,string RoleCode,string Status,Guid? ActorId,string? Comment,DateTimeOffset? ActedAt);
public sealed record ReleaseTargetDto(Guid NodeId,string InstanceId,bool Acknowledged,long? ConfigVersion,long? DeploymentSequence,string? ErrorCode);
public sealed record ReleaseDto(Guid Id,Guid EnvironmentId,string ReleaseNo,string State,string ReleaseType,Guid RequestedBy,DateTimeOffset CreatedAt,long BaselineConfigVersion,long TargetConfigVersion,long? DeploymentSequence,Guid? RollbackOf,FrozenCandidateView? FrozenCandidate,string? CandidateHash,IReadOnlyList<ApprovalTaskDto> ApprovalSteps,IReadOnlyList<ReleaseTargetDto> Targets,IReadOnlyList<string> Errors,Guid? RecoveryOf=null,ApprovalEligibility? ApprovalEligibility=null,ReleaseAccessContextDto? AccessContext=null,string? CurrentPublicOrigin=null,bool AccessAddressChanged=false,string CurrentBasePath="/");

public sealed record ReleaseAccessContextDto(Guid ReleaseId,Guid EnvironmentId,long AccessAddressRevision,string? PublicOrigin,string BasePath,DateTimeOffset CapturedAt,[property:System.Text.Json.Serialization.JsonIgnore(Condition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)] string? InternalOrigin=null,Guid? RecoveryOf=null);
