import {notificationIntent,validateNotificationIntent} from '../notifications/delivery-state.mjs';
const metrics=['request_rps','error_5xx_ratio','latency_p95_ms','unhealthy_destinations'];
export function newRuleState(definition,rule){return {definition:{...structuredClone(definition),notification:notificationIntent(definition.notification)},dirty:false,revision:rule?.revision,logicRevision:rule?.logicRevision,conflict:false};}
export function ruleEditorReducer(state,event){if(state.invalid)return state;switch(event.type){case 'change':return {...state,definition:{...state.definition,...event.patch},dirty:true,testResult:undefined,preview:undefined};case 'denied':return {...state,definition:{...state.definition,name:'',expression:'',targetId:null,notification:notificationIntent()},dirty:false,conflict:false,latest:undefined,testResult:undefined,preview:undefined,invalid:true};case 'conflict':return {...state,conflict:true};case 'latest':return {...state,latestRevision:event.rule.revision,latestLogicRevision:event.rule.logicRevision,latest:event.rule};case 'adoptRevision':return {...state,revision:state.latestRevision,logicRevision:state.latestLogicRevision,conflict:false};case 'tested':return {...state,testResult:event.result};case 'previewed':return {...state,preview:event.result};default:return state;}}
export function validateRule(d){if(!d.name?.trim()||d.name.trim().length>128)return '规则名称必填且不超过128字符。';const tokens=d.expression.trim().split(/\s+/);const [metric,operator,threshold]=tokens;if(!metrics.includes(d.metric)||d.expression.length>256||tokens.length!==3||metric!==d.metric||!['>=','<=','==','!=','>','<'].includes(operator)||!/^(?:\+)?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?$/.test(threshold)||!Number.isFinite(Number(threshold))||(d.metric==='error_5xx_ratio'&&Number(threshold)>1))return '表达式须为所选指标、比较符和非负数；错误率阈值为0至1。';if(!Number.isInteger(d.forSeconds)||d.forSeconds<0||d.forSeconds>86400||!Number.isInteger(d.windowSeconds)||d.windowSeconds<60||d.windowSeconds>3600)return '持续时间须为0至86400秒，窗口须为60至3600秒。';if(d.targetType!=='Environment'&&!d.targetId)return '请选择实际监控目标。';if(d.metric==='unhealthy_destinations'&&d.targetType==='Api')return '后端健康指标仅支持环境或后端目标。';return validateNotificationIntent(d.notification);}
export function notificationLabel(channel){return channel==='EnterpriseIm'?'企业 IM · 待接入':({Email:'邮件',Webhook:'Webhook'}[channel]||channel)+' · 需显式开启自动通知';}
export function ruleTestLabel(result){return result?.evaluationState==='Known'?(result.condition?'当前条件成立':'当前条件不成立'):'Unknown · 数据不足或源不可用，无法判定';}
export function parseAlertSearch(search){const p=new URLSearchParams(search),result={page:Math.max(1,Math.floor(Number(p.get('page'))||1)),all:p.get('all')==='true'};if(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(p.get('eventId')??'')&&p.get('eventId')!=='00000000-0000-0000-0000-000000000000')result.eventId=p.get('eventId');if(['Open','Ack','Resolved','Silenced'].includes(p.get('status')))result.status=p.get('status');if(['Info','Warning','Critical'].includes(p.get('severity')))result.severity=p.get('severity');return result;}
export function serializeAlertSearch(state){const p=new URLSearchParams();for(const key of ['page','all','status','severity','eventId'])if(state[key]!==undefined&&state[key]!=='')p.set(key,String(state[key]));return '?'+p;}

export function observationFreshLabel(state,value){return state==='Historical'&&value?'历史观测':state==='Disabled'?'已停用':state==='ScopeInactive'?'范围停用':state==='Known'&&value?'有效观测':'Unknown';}

export function resetAlertScopeSearch(search){return serializeAlertSearch({...parseAlertSearch(search),eventId:undefined,page:1});}
