import {tabFocusTarget,recoveryFocusTarget} from '../editor-focus.mjs';
import {editorMaySubmit} from '../editor-state.mjs';import {useEffect,useReducer,useRef,useState,type FormEvent} from 'react';
import {useUnsaved,useRemote,Details} from '../ui';import {useSession} from '../auth/SessionProvider';import {useWorkspace} from '../Shell';import {ApiError,apiRequest} from '../api/client';import {readAllPages} from '../api/paging.mjs';import {loadRule,previewRule,testRule,saveRule,type SaveAlertRuleRequest,type AlertRuleDto} from '../api/alerts';import {newRuleState,ruleEditorReducer,validateRule,notificationLabel,ruleTestLabel} from './alert-state.mjs';import {metricDisplay} from './query-state.mjs';
export const ruleMetricNames:Record<string,string>={request_rps:'请求吞吐 RPS',error_5xx_ratio:'5xx 错误率（0–1）',latency_p95_ms:'P95 延迟（ms）',unhealthy_destinations:'异常后端数量'};
export function RuleEditor({initial,rule,onClose,onSaved}:{initial:SaveAlertRuleRequest;rule?:AlertRuleDto;onClose:()=>void;onSaved:(rule:AlertRuleDto)=>void}){
 const ws=useWorkspace(),session=useSession(),[state,dispatch]=useReducer(ruleEditorReducer,newRuleState(initial,rule)),[error,setError]=useState(''),[busy,setBusy]=useState(''),[discard,setDiscard]=useState(false),[invalid,setInvalid]=useState(false),[destinations,setDestinations]=useState<{id:string;name:string}[]>([]);const root=useRef<HTMLFormElement>(null),key=useRef(crypto.randomUUID()),request=useRef<AbortController|undefined>(undefined),generation=useRef(0),alive=useRef(true);const d=state.definition;const allowed=session.can('alert.rule.manage',{organizationId:d.organizationId,projectId:d.projectId,environmentId:d.environmentId},true)&&!invalid;
 const apis=useRemote<any>(d.projectId&&session.can('api.read',{organizationId:d.organizationId,projectId:d.projectId})?`/projects/${d.projectId}/apis`:null,0,true);
 const focusItems=(scope:HTMLElement)=>[...scope.querySelectorAll<HTMLElement>('input:not(:disabled):not([type=hidden]),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),a[href],summary')].filter(item=>item.tabIndex>=0&&item.getClientRects().length>0);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const form=root.current;if(form)(form.querySelector<HTMLElement>('input:not(:disabled):not([type=hidden])')||focusItems(form)[0]||form).focus();return()=>{alive.current=false;generation.current++;request.current?.abort();if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{const controller=new AbortController();setDestinations([]);if(d.environmentId&&session.can('cluster.read',{organizationId:d.organizationId,projectId:d.projectId,environmentId:d.environmentId}))void readAllPages(apiRequest,`/environments/${d.environmentId}/clusters`,{signal:controller.signal}).then(async(data:any)=>{const clusters=await Promise.all(data.items.map((c:any)=>apiRequest<any>('/clusters/'+c.id,{signal:controller.signal})));if(!controller.signal.aborted)setDestinations(clusters.flatMap(c=>c.destinations));}).catch(()=>{});return()=>controller.abort();},[d.projectId,d.environmentId]);
 useEffect(()=>{const form=root.current;if(!form)return;const trap=form.querySelector<HTMLElement>('[role=alertdialog]')||form,items=focusItems(trap);const next=discard?items[0]||form:recoveryFocusTarget(items,document.activeElement,form);next?.focus();},[discard,busy,invalid,state.conflict,state.latest,allowed]);
 useUnsaved(state.dirty,()=>setError('仍有未保存的修改，请先保存或关闭表单。'));
 function change(patch:Partial<SaveAlertRuleRequest>){request.current?.abort();generation.current++;dispatch({type:'change',patch});key.current=crypto.randomUUID();setBusy('');setError('');}
 async function inspect(kind:'test'|'preview'){const validation=validateRule(d);if(validation){setError(validation);return;}const controller=new AbortController();request.current?.abort();request.current=controller;const run=++generation.current;setBusy(kind);setError('');try{const result=await(kind==='test'?testRule(d,controller.signal):previewRule(d,controller.signal));if(run===generation.current&&!controller.signal.aborted)dispatch({type:kind==='test'?'tested':'previewed',result});}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(run===generation.current)setBusy('');}}
 async function submit(e:FormEvent){e.preventDefault();if(!editorMaySubmit({authorized:allowed,busy:!!busy,conflict:state.conflict,discard}))return;const validation=validateRule(d);if(validation){setError(validation);return;}setBusy('save');setError('');try{const saved=await saveRule(rule?.id||null,d,state.revision?`"${state.revision}"`:null,key.current);if(alive.current)onSaved(saved);}catch(e){if(alive.current){setError((e as Error).message);if(e instanceof ApiError&&e.status===412)dispatch({type:'conflict'});if(e instanceof ApiError&&[401,403,404].includes(e.status))setInvalid(true);}}finally{if(alive.current)setBusy('');}}
 const close=()=>{if(busy==='save')return;if(state.dirty)setDiscard(true);else onClose();};const projects=ws.tree.projects.filter(p=>p.organizationId===d.organizationId),envs=ws.tree.environments.filter(e=>e.projectId===d.projectId),scopeLevel=d.environmentId?'Environment':d.projectId?'Project':'Organization',targets=d.targetType==='Api'?apis.data?.items||[]:destinations;
 return <div className="overlay"><form ref={root} className="dialog alert-editor" role="dialog" tabIndex={-1} aria-modal="true" aria-label={rule?'编辑告警规则':'新建告警规则'} onSubmit={submit} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();if(discard)setDiscard(false);else close();}if(e.key==='Tab'){const trap=e.currentTarget.querySelector<HTMLElement>('[role=alertdialog]')||e.currentTarget;const next=tabFocusTarget(focusItems(trap),document.activeElement,e.shiftKey,e.currentTarget);if(next){e.preventDefault();next.focus();}}}}>
 <header><div><small>ALERT RULE · {rule?'EDIT':'CREATE'}</small><h2>{rule?'编辑告警规则':'新建告警规则'}</h2></div><button type="button" className="btn" disabled={busy==='save'} onClick={close}>关闭</button></header>
 <fieldset disabled={busy==='save'||invalid||discard}><div className="form-grid"><label>规则名称 *<input required maxLength={128} value={d.name} onChange={e=>change({name:e.target.value})}/></label><label>级别<select value={d.severity} onChange={e=>change({severity:e.target.value})}><option value="Info">提示</option><option value="Warning">警告</option><option value="Critical">严重</option></select></label>
 <label>规则范围<select value={scopeLevel} onChange={e=>change({projectId:e.target.value==='Organization'?null:ws.projectId,environmentId:e.target.value==='Environment'?ws.environmentId:null,targetType:'Environment',targetId:null})}><option value="Environment">当前环境</option><option value="Project">项目全部活动环境</option><option value="Organization">组织全部活动环境</option></select></label><label>组织<input disabled value={ws.tree.organizations.find(o=>o.id===d.organizationId)?.name||d.organizationId}/></label>
 {d.projectId&&<label>规则项目<select value={d.projectId} onChange={e=>change({projectId:e.target.value,environmentId:null,targetType:'Environment',targetId:null})}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}{d.environmentId&&<label>规则环境<select value={d.environmentId} onChange={e=>change({environmentId:e.target.value,targetType:'Environment',targetId:null})}>{envs.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>}
 <label>观测指标<select value={d.metric} onChange={e=>change({metric:e.target.value,expression:e.target.value+' > 0',...(e.target.value==='unhealthy_destinations'&&d.targetType==='Api'?{targetType:'Environment',targetId:null}:{})})}>{Object.entries(ruleMetricNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>监控目标<select value={d.targetType} onChange={e=>change({targetType:e.target.value,targetId:null})}><option value="Environment">环境聚合</option>{d.projectId&&d.metric!=='unhealthy_destinations'&&<option value="Api">指定 API</option>}{d.environmentId&&<option value="Destination">指定后端目标</option>}</select></label>
 {d.targetType!=='Environment'&&<label className="span-two">目标资源<select required value={d.targetId||''} onChange={e=>change({targetId:e.target.value||null})}><option value="">请选择目标</option>{d.targetId&&!targets.some((x:any)=>x.id===d.targetId)&&<option value={d.targetId}>{d.targetId}（当前目标）</option>}{targets.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select><small>资源选择受目录读取权限控制；实际目标在保存及测试时由服务端再次验证。</small></label>}
 <label className="span-two">比较表达式 *<input required value={d.expression} onChange={e=>change({expression:e.target.value})}/><small>例：latency_p95_ms &gt; 800。用空格分隔所选指标、比较符和非负阈值。</small></label><label>查询窗口 / 秒<input type="number" required min={60} max={3600} value={d.windowSeconds} onChange={e=>change({windowSeconds:Number(e.target.value)})}/><small>规则使用自身窗口，与监控页面的查询时间独立。</small></label><label>条件持续 / 秒<input type="number" required min={0} max={86400} value={d.forSeconds} onChange={e=>change({forSeconds:Number(e.target.value)})}/><small>0秒立即触发；Unknown会中断Pending持续计时。</small></label><label className="checkline"><input type="checkbox" checked={d.enabled} onChange={e=>change({enabled:e.target.checked})}/>保存后启用规则</label></div>
 <div className="alert-notifications"><strong>通知策略</strong><p>控制台告警已启用。以下渠道仅记录意向，尚未发送外部通知。</p>{['Email','Webhook','EnterpriseIm'].map(channel=><label key={channel}><input type="checkbox" checked={d.notification.requestedChannels.includes(channel)} onChange={e=>change({notification:{inConsole:true,requestedChannels:e.target.checked?[...d.notification.requestedChannels,channel]:d.notification.requestedChannels.filter(c=>c!==channel)}})}/>{notificationLabel(channel)}</label>)}</div></fieldset>
 {!allowed&&<div className="error">当前规则范围缺少完整写入权限，无法保存或测试。</div>}{error&&<div className="error" role="alert">{error}</div>}
 {state.conflict&&<div className="notice" role="alert"><strong>版本冲突：你的输入已保留。</strong><p>查看最新版本后，确认合并方式。采用最新修订将保留当前输入，不会自动覆盖。</p><button type="button" className="btn" disabled={!!busy} onClick={async()=>{try{dispatch({type:'latest',rule:await loadRule(rule!.id)});}catch(e){setError((e as Error).message);}}}>查看服务器最新版本</button>{state.latest&&<><p>服务器修订 {state.latestRevision} · 逻辑修订 {state.latestLogicRevision}</p><Details value={state.latest.definition}/><button type="button" className="btn" onClick={()=>{dispatch({type:'adoptRevision'});key.current=crypto.randomUUID();}}>保持我的输入，采用最新修订</button></>}</div>}
 {state.preview&&<div className="notice"><strong>Scope 预览 · {state.preview.environmentIds.length} 个活动环境</strong><p>{state.preview.environmentIds.map(id=>ws.tree.environments.find(e=>e.id===id)?.name||id).join('、')||'暂无活动环境'}</p><small>{state.preview.includesFutureActiveEnvironments?'包含此范围未来新增的活动环境':'仅当前指定环境'} · 目标变化将按实际资源校验</small></div>}
 {state.testResult&&<div className="notice" role="status"><strong>只读测试：{ruleTestLabel(state.testResult)}</strong>{state.testResult.matches.map(m=><p key={m.key}>{m.name}：{m.values.map(v=>metricDisplay(v)).join('、')}</p>)}<small>此测试未保存规则、未推进持续时间、未创建事件。</small></div>}
 {discard&&<div className="notice" role="alertdialog" aria-label="放弃未保存的修改"><p>放弃后，这些修改不会保存。</p><button type="button" className="btn" onClick={()=>setDiscard(false)}>继续编辑</button><button type="button" className="btn danger" onClick={onClose}>确认放弃</button></div>}
 <footer><div className="actions"><button type="button" className="btn" disabled={!allowed||!!busy||discard} onClick={()=>void inspect('preview')}>预览范围</button><button type="button" className="btn" disabled={!allowed||!!busy||discard} onClick={()=>void inspect('test')}>{busy==='test'?'测试中…':'只读测试'}</button><button className="btn primary" disabled={!allowed||!!busy||state.conflict||discard}>{busy==='save'?'保存中…':'保存规则'}</button></div><small>修订 {state.revision||'新建'} · 逻辑 {state.logicRevision||'新建'} · {state.dirty?'未保存修改':'当前定义'}</small></footer>
 </form></div>;
}
