CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        organization_id uuid,
        project_id uuid,
        environment_id uuid,
        user_id uuid,
        action varchar(128) NOT NULL,
        resource_type varchar(64) NOT NULL,
        resource_id varchar(128) NOT NULL,
        before_json jsonb,
        after_json jsonb,
        ip inet,
        trace_id varchar(64),
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE organizations (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        code varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        status varchar(24) NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_organizations" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE permissions (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        code varchar(128) NOT NULL,
        module varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        description text NOT NULL,
        CONSTRAINT "PK_permissions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE users (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        username varchar(128) NOT NULL,
        display_name varchar(128) NOT NULL,
        email varchar(256),
        password_hash varchar(256),
        status varchar(24) NOT NULL,
        auth_source varchar(24) NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        security_stamp varchar(128) NOT NULL DEFAULT (gen_random_uuid()::text),
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE approval_flows (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid NOT NULL,
        name varchar(128) NOT NULL,
        scope_type varchar(32) NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_approval_flows" PRIMARY KEY (id),
        CONSTRAINT "FK_approval_flows_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE roles (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid,
        code varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        is_system boolean NOT NULL,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_roles" PRIMARY KEY (id),
        CONSTRAINT "FK_roles_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE idempotency_records (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        actor_id uuid NOT NULL,
        scope_key varchar(256) NOT NULL,
        operation varchar(128) NOT NULL,
        key varchar(128) NOT NULL,
        request_hash varchar(128) NOT NULL,
        response_bytes bytea,
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_idempotency_records" PRIMARY KEY (id),
        CONSTRAINT "FK_idempotency_records_users_actor_id" FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE projects (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid NOT NULL,
        code varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        owner_user_id uuid,
        status varchar(24) NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_projects" PRIMARY KEY (id),
        CONSTRAINT "AK_projects_id_organization_id" UNIQUE (id, organization_id),
        CONSTRAINT "FK_projects_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_projects_users_owner_user_id" FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE approval_steps (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        flow_id uuid NOT NULL,
        step_order int NOT NULL,
        role_code varchar(64) NOT NULL,
        required_count int NOT NULL,
        CONSTRAINT "PK_approval_steps" PRIMARY KEY (id),
        CONSTRAINT "FK_approval_steps_approval_flows_flow_id" FOREIGN KEY (flow_id) REFERENCES approval_flows (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE role_permissions (
        role_id uuid NOT NULL,
        permission_id uuid NOT NULL,
        CONSTRAINT "PK_role_permissions" PRIMARY KEY (role_id, permission_id),
        CONSTRAINT "FK_role_permissions_permissions_permission_id" FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_role_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE user_roles (
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        CONSTRAINT "PK_user_roles" PRIMARY KEY (user_id, role_id),
        CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE api_groups (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        project_id uuid NOT NULL,
        name varchar(128) NOT NULL,
        parent_id uuid,
        sort_order int NOT NULL,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_api_groups" PRIMARY KEY (id),
        CONSTRAINT "AK_api_groups_id_project_id" UNIQUE (id, project_id),
        CONSTRAINT "FK_api_groups_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE applications (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid NOT NULL,
        project_id uuid,
        code varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        owner varchar(128) NOT NULL,
        status varchar(24) NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_applications" PRIMARY KEY (id),
        CONSTRAINT "FK_applications_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_applications_projects_project_id_organization_id" FOREIGN KEY (project_id, organization_id) REFERENCES projects (id, organization_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE environments (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        project_id uuid NOT NULL,
        code varchar(32) NOT NULL,
        name varchar(64) NOT NULL,
        is_production boolean NOT NULL,
        sort_order int NOT NULL,
        status varchar(24) NOT NULL,
        release_policy_id uuid,
        desired_config_version bigint,
        deployment_sequence bigint NOT NULL DEFAULT 0,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_environments" PRIMARY KEY (id),
        CONSTRAINT "AK_environments_id_project_id" UNIQUE (id, project_id),
        CONSTRAINT ck_deployment_sequence CHECK (deployment_sequence >= 0),
        CONSTRAINT "FK_environments_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE policies (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid NOT NULL,
        project_id uuid,
        name varchar(128) NOT NULL,
        type varchar(48) NOT NULL,
        config jsonb NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        version_no bigint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        CONSTRAINT "PK_policies" PRIMARY KEY (id),
        CONSTRAINT "FK_policies_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_policies_projects_project_id_organization_id" FOREIGN KEY (project_id, organization_id) REFERENCES projects (id, organization_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE apis (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organization_id uuid NOT NULL,
        project_id uuid NOT NULL,
        group_id uuid,
        code varchar(64) NOT NULL,
        name varchar(128) NOT NULL,
        description text,
        lifecycle_status varchar(24) NOT NULL,
        owner_user_id uuid NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        version_no bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_apis" PRIMARY KEY (id),
        CONSTRAINT "FK_apis_api_groups_group_id_project_id" FOREIGN KEY (group_id, project_id) REFERENCES api_groups (id, project_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_apis_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_apis_projects_project_id_organization_id" FOREIGN KEY (project_id, organization_id) REFERENCES projects (id, organization_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_apis_users_owner_user_id" FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE application_credentials (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        application_id uuid NOT NULL,
        access_key varchar(128) NOT NULL,
        secret_hash varchar(256) NOT NULL,
        secret_last4 varchar(8) NOT NULL,
        status varchar(24) NOT NULL,
        valid_from timestamptz NOT NULL,
        expires_at timestamptz NOT NULL,
        last_used_at timestamptz,
        revoked_at timestamptz,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_application_credentials" PRIMARY KEY (id),
        CONSTRAINT ck_credential_window CHECK (expires_at > valid_from),
        CONSTRAINT "FK_application_credentials_applications_application_id" FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE gateway_config_versions (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        environment_id uuid NOT NULL,
        version_no bigint NOT NULL,
        status varchar(24) NOT NULL,
        snapshot_key varchar(256),
        snapshot_hash varchar(128),
        created_by uuid NOT NULL,
        created_at timestamptz NOT NULL,
        published_at timestamptz,
        CONSTRAINT "PK_gateway_config_versions" PRIMARY KEY (id),
        CONSTRAINT ck_config_version CHECK (version_no > 0),
        CONSTRAINT "FK_gateway_config_versions_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_gateway_config_versions_users_created_by" FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE gateway_nodes (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        environment_id uuid NOT NULL,
        node_name varchar(128) NOT NULL,
        instance_id varchar(128) NOT NULL,
        app_version varchar(64) NOT NULL,
        current_config_version bigint NOT NULL,
        target_config_version bigint,
        status varchar(24) NOT NULL,
        last_heartbeat_at timestamptz,
        metadata jsonb,
        current_deployment_sequence bigint NOT NULL DEFAULT 0,
        identity_hash varchar(256) NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_gateway_nodes" PRIMARY KEY (id),
        CONSTRAINT "FK_gateway_nodes_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE release_records (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        environment_id uuid NOT NULL,
        release_no varchar(64) NOT NULL,
        from_config_version bigint NOT NULL,
        to_config_version bigint NOT NULL,
        release_type varchar(24) NOT NULL,
        status varchar(24) NOT NULL,
        requested_by uuid NOT NULL,
        approved_by uuid,
        created_at timestamptz NOT NULL,
        completed_at timestamptz,
        rollback_of uuid,
        deployment_sequence bigint DEFAULT 0,
        baseline_config_version bigint NOT NULL DEFAULT 0,
        candidate_bytes bytea,
        approval_policy jsonb,
        deadline_at timestamptz,
        failure_code varchar(128),
        CONSTRAINT "PK_release_records" PRIMARY KEY (id),
        CONSTRAINT "FK_release_records_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_release_records_release_records_rollback_of" FOREIGN KEY (rollback_of) REFERENCES release_records (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_release_records_users_approved_by" FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_release_records_users_requested_by" FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE upstream_clusters (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        project_id uuid NOT NULL,
        environment_id uuid NOT NULL,
        name varchar(128) NOT NULL,
        load_balancing_policy varchar(32) NOT NULL,
        health_check_enabled boolean NOT NULL,
        health_check_path varchar(256) NOT NULL,
        health_check_interval_sec int NOT NULL,
        status varchar(24) NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_upstream_clusters" PRIMARY KEY (id),
        CONSTRAINT "AK_upstream_clusters_id_environment_id" UNIQUE (id, environment_id),
        CONSTRAINT "FK_upstream_clusters_environments_environment_id_project_id" FOREIGN KEY (environment_id, project_id) REFERENCES environments (id, project_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_upstream_clusters_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE user_project_scopes (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        user_id uuid NOT NULL,
        organization_id uuid NOT NULL,
        project_id uuid,
        environment_id uuid,
        access_mode varchar(16) NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_user_project_scopes" PRIMARY KEY (id),
        CONSTRAINT ck_scope_environment_requires_project CHECK (environment_id IS NULL OR project_id IS NOT NULL),
        CONSTRAINT "FK_user_project_scopes_environments_environment_id_project_id" FOREIGN KEY (environment_id, project_id) REFERENCES environments (id, project_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_user_project_scopes_organizations_organization_id" FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_user_project_scopes_projects_project_id_organization_id" FOREIGN KEY (project_id, organization_id) REFERENCES projects (id, organization_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_user_project_scopes_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE api_versions (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        api_id uuid NOT NULL,
        version varchar(32) NOT NULL,
        status varchar(24) NOT NULL,
        openapi_document jsonb,
        schema_hash varchar(128),
        change_type varchar(24) NOT NULL,
        created_by uuid NOT NULL,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        openapi_source text,
        source_format varchar(16),
        sealed_at timestamptz,
        CONSTRAINT "PK_api_versions" PRIMARY KEY (id),
        CONSTRAINT "FK_api_versions_apis_api_id" FOREIGN KEY (api_id) REFERENCES apis (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_api_versions_users_created_by" FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE application_api_permissions (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        application_id uuid NOT NULL,
        api_id uuid NOT NULL,
        environment_id uuid NOT NULL,
        valid_from timestamptz NOT NULL,
        expires_at timestamptz,
        created_by uuid NOT NULL,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_application_api_permissions" PRIMARY KEY (id),
        CONSTRAINT ck_grant_window CHECK (expires_at IS NULL OR expires_at > valid_from),
        CONSTRAINT "FK_application_api_permissions_apis_api_id" FOREIGN KEY (api_id) REFERENCES apis (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_application_api_permissions_applications_application_id" FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_application_api_permissions_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_application_api_permissions_users_created_by" FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE gateway_config_snapshots (
        config_version_id uuid NOT NULL,
        payload jsonb NOT NULL,
        size_bytes bigint NOT NULL,
        created_at timestamptz NOT NULL,
        payload_bytes bytea NOT NULL,
        CONSTRAINT "PK_gateway_config_snapshots" PRIMARY KEY (config_version_id),
        CONSTRAINT "FK_gateway_config_snapshots_gateway_config_versions_config_ver~" FOREIGN KEY (config_version_id) REFERENCES gateway_config_versions (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE gateway_node_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        gateway_node_id uuid NOT NULL,
        event_type varchar(64) NOT NULL,
        message text NOT NULL,
        detail jsonb NOT NULL,
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_gateway_node_events" PRIMARY KEY (id),
        CONSTRAINT "FK_gateway_node_events_gateway_nodes_gateway_node_id" FOREIGN KEY (gateway_node_id) REFERENCES gateway_nodes (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE approval_tasks (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        flow_id uuid NOT NULL,
        release_id uuid NOT NULL,
        step_order int NOT NULL,
        assignee_user_id uuid,
        status varchar(24) NOT NULL,
        comment text,
        acted_at timestamptz,
        CONSTRAINT "PK_approval_tasks" PRIMARY KEY (id),
        CONSTRAINT "FK_approval_tasks_approval_flows_flow_id" FOREIGN KEY (flow_id) REFERENCES approval_flows (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_approval_tasks_release_records_release_id" FOREIGN KEY (release_id) REFERENCES release_records (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_approval_tasks_users_assignee_user_id" FOREIGN KEY (assignee_user_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE outbox_messages (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        environment_id uuid NOT NULL,
        release_id uuid NOT NULL,
        deployment_sequence bigint NOT NULL DEFAULT 0,
        event_type varchar(128) NOT NULL,
        payload jsonb NOT NULL,
        created_at timestamptz NOT NULL,
        processed_at timestamptz,
        lease_until timestamptz,
        attempts int NOT NULL DEFAULT 0,
        CONSTRAINT "PK_outbox_messages" PRIMARY KEY (id),
        CONSTRAINT "FK_outbox_messages_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_outbox_messages_release_records_release_id" FOREIGN KEY (release_id) REFERENCES release_records (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE release_items (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        release_id uuid NOT NULL,
        resource_type varchar(32) NOT NULL,
        resource_id uuid NOT NULL,
        change_type varchar(24) NOT NULL,
        before_json jsonb,
        after_json jsonb,
        CONSTRAINT "PK_release_items" PRIMARY KEY (id),
        CONSTRAINT "FK_release_items_release_records_release_id" FOREIGN KEY (release_id) REFERENCES release_records (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE release_targets (
        release_id uuid NOT NULL,
        node_id uuid NOT NULL,
        instance_id varchar(128) NOT NULL,
        created_at timestamptz NOT NULL,
        CONSTRAINT "PK_release_targets" PRIMARY KEY (release_id, node_id),
        CONSTRAINT "FK_release_targets_gateway_nodes_node_id" FOREIGN KEY (node_id) REFERENCES gateway_nodes (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_release_targets_release_records_release_id" FOREIGN KEY (release_id) REFERENCES release_records (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE upstream_destinations (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        cluster_id uuid NOT NULL,
        name varchar(128) NOT NULL,
        address varchar(1024) NOT NULL,
        weight int NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        metadata jsonb,
        created_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_upstream_destinations" PRIMARY KEY (id),
        CONSTRAINT "FK_upstream_destinations_upstream_clusters_cluster_id" FOREIGN KEY (cluster_id) REFERENCES upstream_clusters (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE api_parameters (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        api_version_id uuid NOT NULL,
        location varchar(16) NOT NULL,
        name varchar(128) NOT NULL,
        data_type varchar(32) NOT NULL,
        required boolean NOT NULL,
        schema jsonb,
        description text,
        example_json jsonb,
        CONSTRAINT "PK_api_parameters" PRIMARY KEY (id),
        CONSTRAINT "FK_api_parameters_api_versions_api_version_id" FOREIGN KEY (api_version_id) REFERENCES api_versions (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE api_routes (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        api_version_id uuid NOT NULL,
        environment_id uuid NOT NULL,
        route_name varchar(128) NOT NULL,
        path varchar(512) NOT NULL,
        normalized_path varchar(512) NOT NULL,
        methods varchar[] NOT NULL,
        cluster_id uuid NOT NULL,
        priority int NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        timeout_ms int NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        revision bigint NOT NULL DEFAULT 1,
        CONSTRAINT "PK_api_routes" PRIMARY KEY (id),
        CONSTRAINT "AK_api_routes_id_environment_id" UNIQUE (id, environment_id),
        CONSTRAINT ck_route_methods_timeout CHECK (cardinality(methods) > 0 AND timeout_ms > 0),
        CONSTRAINT "FK_api_routes_api_versions_api_version_id" FOREIGN KEY (api_version_id) REFERENCES api_versions (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_api_routes_environments_environment_id" FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_api_routes_upstream_clusters_cluster_id_environment_id" FOREIGN KEY (cluster_id, environment_id) REFERENCES upstream_clusters (id, environment_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE api_schemas (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        api_version_id uuid NOT NULL,
        schema_type varchar(32) NOT NULL,
        name varchar(128) NOT NULL,
        status_code int,
        content_type varchar(128) NOT NULL,
        schema_json jsonb NOT NULL,
        schema_hash varchar(128),
        example_json jsonb,
        CONSTRAINT "PK_api_schemas" PRIMARY KEY (id),
        CONSTRAINT "FK_api_schemas_api_versions_api_version_id" FOREIGN KEY (api_version_id) REFERENCES api_versions (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE gateway_acks (
        release_id uuid NOT NULL,
        node_id uuid NOT NULL,
        instance_id varchar(128) NOT NULL,
        config_version bigint NOT NULL,
        deployment_sequence bigint NOT NULL DEFAULT 0,
        payload_hash varchar(128) NOT NULL,
        applied_at timestamptz NOT NULL,
        success boolean NOT NULL,
        error_code varchar(128),
        CONSTRAINT "PK_gateway_acks" PRIMARY KEY (release_id, node_id),
        CONSTRAINT "FK_gateway_acks_gateway_nodes_node_id" FOREIGN KEY (node_id) REFERENCES gateway_nodes (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_gateway_acks_release_records_release_id" FOREIGN KEY (release_id) REFERENCES release_records (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_gateway_acks_release_targets_release_id_node_id" FOREIGN KEY (release_id, node_id) REFERENCES release_targets (release_id, node_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE route_methods (
        route_id uuid NOT NULL,
        method varchar(16) NOT NULL,
        environment_id uuid NOT NULL,
        normalized_path varchar(512) NOT NULL,
        CONSTRAINT "PK_route_methods" PRIMARY KEY (route_id, method),
        CONSTRAINT "FK_route_methods_api_routes_route_id_environment_id" FOREIGN KEY (route_id, environment_id) REFERENCES api_routes (id, environment_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE TABLE route_policy_bindings (
        route_id uuid NOT NULL,
        policy_id uuid NOT NULL,
        priority int NOT NULL,
        CONSTRAINT "PK_route_policy_bindings" PRIMARY KEY (route_id, policy_id),
        CONSTRAINT "FK_route_policy_bindings_api_routes_route_id" FOREIGN KEY (route_id) REFERENCES api_routes (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_route_policy_bindings_policies_policy_id" FOREIGN KEY (policy_id) REFERENCES policies (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_groups_project_id" ON api_groups (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_parameters_api_version_id" ON api_parameters (api_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_routes_api_version_id" ON api_routes (api_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_routes_cluster_id_environment_id" ON api_routes (cluster_id, environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_routes_environment_id" ON api_routes (environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_schemas_api_version_id" ON api_schemas (api_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_api_versions_api_id_version" ON api_versions (api_id, version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_api_versions_created_by" ON api_versions (created_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_apis_group_id_project_id" ON apis (group_id, project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_apis_organization_id" ON apis (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_apis_owner_user_id" ON apis (owner_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_apis_project_id_code" ON apis (project_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_apis_project_id_organization_id" ON apis (project_id, organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_application_api_permissions_api_id" ON application_api_permissions (api_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_application_api_permissions_application_id_api_id_environme~" ON application_api_permissions (application_id, api_id, environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_application_api_permissions_created_by" ON application_api_permissions (created_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_application_api_permissions_environment_id" ON application_api_permissions (environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_application_credentials_access_key" ON application_credentials (access_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_application_credentials_application_id" ON application_credentials (application_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_applications_organization_id_code" ON applications (organization_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_applications_project_id_organization_id" ON applications (project_id, organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_approval_flows_organization_id" ON approval_flows (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_approval_steps_flow_id_step_order" ON approval_steps (flow_id, step_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_approval_tasks_assignee_user_id" ON approval_tasks (assignee_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_approval_tasks_flow_id" ON approval_tasks (flow_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_approval_tasks_release_id" ON approval_tasks (release_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_audit_logs_environment_id_created_at" ON audit_logs (environment_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_environments_project_id_code" ON environments (project_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_gateway_acks_node_id" ON gateway_acks (node_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_gateway_config_versions_created_by" ON gateway_config_versions (created_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_gateway_config_versions_environment_id_version_no" ON gateway_config_versions (environment_id, version_no);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_gateway_node_events_gateway_node_id" ON gateway_node_events (gateway_node_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_gateway_nodes_environment_id_enabled" ON gateway_nodes (environment_id, enabled);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_gateway_nodes_node_name" ON gateway_nodes (node_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_idempotency_records_actor_id_scope_key_operation_key" ON idempotency_records (actor_id, scope_key, operation, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_organizations_code" ON organizations (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_outbox_messages_environment_id" ON outbox_messages (environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_outbox_messages_processed_at_lease_until" ON outbox_messages (processed_at, lease_until);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_outbox_messages_release_id" ON outbox_messages (release_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_permissions_code" ON permissions (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_policies_organization_id" ON policies (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_policies_project_id_organization_id" ON policies (project_id, organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_projects_organization_id_code" ON projects (organization_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_projects_owner_user_id" ON projects (owner_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_items_release_id" ON release_items (release_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_records_approved_by" ON release_records (approved_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_records_environment_id_status" ON release_records (environment_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_release_records_release_no" ON release_records (release_no);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_records_requested_by" ON release_records (requested_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_records_rollback_of" ON release_records (rollback_of);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_release_targets_node_id" ON release_targets (node_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_role_permissions_permission_id" ON role_permissions (permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_roles_code" ON roles (code) WHERE organization_id IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_roles_organization_id_code" ON roles (organization_id, code) WHERE organization_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_route_methods_environment_id_method_normalized_path" ON route_methods (environment_id, method, normalized_path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_route_methods_route_id_environment_id" ON route_methods (route_id, environment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_route_policy_bindings_policy_id" ON route_policy_bindings (policy_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_upstream_clusters_environment_id_name" ON upstream_clusters (environment_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_upstream_clusters_environment_id_project_id" ON upstream_clusters (environment_id, project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_upstream_clusters_project_id" ON upstream_clusters (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_upstream_destinations_cluster_id" ON upstream_destinations (cluster_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_user_project_scopes_environment_id_project_id" ON user_project_scopes (environment_id, project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_user_project_scopes_organization_id" ON user_project_scopes (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_user_project_scopes_project_id_organization_id" ON user_project_scopes (project_id, organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_user_project_scopes_user_id" ON user_project_scopes (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    CREATE UNIQUE INDEX "IX_users_username" ON users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003182012_InitialCore') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003182012_InitialCore', '10.0.12');
    END IF;
END $EF$;
COMMIT;

