import {useEffect,useState} from 'react';import {IconBell,IconRefresh,IconArrowUpRight} from '@tabler/icons-react';import {useWorkspace,Link,navigate} from '../Shell';import {useSession} from '../auth/SessionProvider';import {usePaged,useRemote,Feedback,Pagination} from '../ui';import type {AlertEventDto,AlertAction} from '../api/alerts';import {observationQuery} from '../api/observability';import {parseAlertSearch,serializeAlertSearch,observationFreshLabel} from '../observability/alert-state.mjs';import {ObservationDrawer} from '../observability/ObservationDrawer';import {NotificationDeliveryList} from '../notifications/NotificationDeliveryList';import {AlertActionDialog} from '../observability/AlertActionDialog';
export const alertStatusNames:Record<string,string>={Open:'待处理',Ack:'已确认',Resolved:'已解决',Silenced:'静默中'};export const alertSeverityNames:Record<string,string>={Info:'提示',Warning:'警告',Critical:'严重'};
export function AlertBadge({value,severity=false}:{value:string;severity?:boolean}){return <span className={'badge '+(value==='Critical'||value==='Open'?'red':value==='Warning'||value==='Silenced'?'amber':value==='Resolved'?'green':'blue')}>{(severity?alertSeverityNames:alertStatusNames)[value]||value}</span>;}
export function FreshObservation({value,state,historical=false}:{value:string|null;state:string;historical?:boolean}){const age=value?Math.max(0,Math.floor((Date.now()-Date.parse(value))/1000)):null;return <span className="alert-fresh"><span className={'badge '+(historical?'blue':state==='Known'&&value?'green':'amber')}>{observationFreshLabel(historical?'Historical':state,value)}</span><small>{value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'尚无有效观测'}{age!==null&&` · ${age}秒前`}</small></span>;}
export function AlertCenter({search}:{search:string}){
 const ws=useWorkspace(),session=useSession(),query=parseAlertSearch(search),allowed=!!ws.projectId&&!!session.user?.permissions.includes('alert.read'),scope={organizationId:ws.organizationId,projectId:ws.projectId,environmentId:query.all?null:ws.environmentId,allAccessibleEnvironments:query.all};
 const url='/observability/alerts?'+observationQuery(scope,{start:'',end:''},{severity:query.severity,status:query.status,source:'Metrics'}),remote=usePaged(allowed?url:null,15_000);const[selected,setSelected]=useState<string|undefined>(query.eventId),[action,setAction]=useState<{event:AlertEventDto;kind:AlertAction['kind']}>();const detail=useRemote<AlertEventDto>(selected?'/observability/alerts/'+selected:null,15_000),e=selected&&detail.data&&session.can('alert.read',detail.data.scope)?detail.data:undefined;
 useEffect(()=>{setSelected(query.eventId);setAction(undefined);},[query.eventId]);
 useEffect(()=>{if(!e||!query.eventId||!ws.tree.environments.some(v=>v.id===e.scope.environmentId))return;if(ws.organizationId!==e.scope.organizationId||ws.projectId!==e.scope.projectId||ws.environmentId!==e.scope.environmentId)ws.selectScope(e.scope,'/observability/alerts'+serializeAlertSearch(query));},[e?.id,query.eventId,ws.organizationId,ws.projectId,ws.environmentId,ws.tree.environments]);
 function closeDetail(){setSelected(undefined);if(query.eventId)navigate('/observability/alerts'+serializeAlertSearch({...query,eventId:undefined}),true);}
 function update(patch:Partial<typeof query>){setSelected(undefined);navigate('/observability/alerts'+serializeAlertSearch({...query,...patch,page:1,eventId:undefined}));}
 function actions(event:AlertEventDto){const can=event.status!=='Resolved'&&session.can('alert.operate',event.scope,true);return <div className="actions"><button className="text-btn" disabled={!can||!!event.ackedBy} onClick={()=>setAction({event,kind:'Ack'})}>确认</button><button className="text-btn" disabled={!can} onClick={()=>setAction({event,kind:event.status==='Silenced'?'Unsilence':'Silence'})}>{event.status==='Silenced'?'解除静默':'静默'}</button><button className="text-btn" disabled={!can} onClick={()=>setAction({event,kind:'Resolve'})}>解决</button></div>;}
 return <><div className="breadcrumb"><Link to="/observability/metrics">运行监控</Link> / 告警中心</div><div className="page-head"><div><div className="ob-eyebrow">OBSERVABILITY · ALERT INBOX</div><h1>告警中心</h1><p>以事件追踪实际故障、处理状态与恢复事实</p></div><div className="actions">{session.user?.permissions.includes('alert.rule.manage')&&<Link to="/observability/alert-rules">管理规则 <IconArrowUpRight size={14}/></Link>}<button className="btn" disabled={!allowed||remote.loading} onClick={()=>{remote.reload();detail.reload();}}><IconRefresh size={15}/>刷新</button></div></div>
 <div className="ob-toolbar alert-filters"><label>数据范围<select aria-label="告警数据范围" value={query.all?'all':'environment'} onChange={v=>update({all:v.target.value==='all'})}><option value="environment">当前环境</option><option value="all">全部可访问环境</option></select></label><label>级别<select aria-label="告警级别" value={query.severity||''} onChange={v=>update({severity:v.target.value||undefined})}><option value="">全部级别</option>{Object.entries(alertSeverityNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>来源<select aria-label="告警来源" value="Metrics" onChange={()=>{}}><option value="Metrics">指标 Metrics</option></select></label><label>状态<select aria-label="告警状态" value={query.status||''} onChange={v=>update({status:v.target.value||undefined})}><option value="">全部状态</option>{Object.entries(alertStatusNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><span className="muted">每15秒更新 · 外部通知按冻结策略投递</span></div>
 {!allowed?<div className="error">当前范围没有 alert.read 权限。</div>:<section className="card"><div className="ob-card-head"><h3><IconBell size={18}/>告警事件</h3><small>同一故障仅一个活动事件；人工解决后等待实际恢复重新布防</small></div><Feedback {...remote}/><div className="table-wrap"><table><thead><tr><th>级别 / 状态</th><th>事件与规则</th><th>环境 / 来源</th><th>触发时间</th><th>最近有效观测</th><th>操作</th></tr></thead><tbody>{remote.data?.items.map((row:AlertEventDto)=><tr key={row.id}><td><div className="alert-badges"><AlertBadge value={row.severity} severity/><AlertBadge value={row.status}/></div></td><td><button className="text-btn alert-rule-link" onClick={()=>setSelected(row.id)}>{row.ruleSummary}</button><small className="block muted">{row.message} · 第{row.occurrenceNo}次</small></td><td>{ws.tree.environments.find(v=>v.id===row.scope.environmentId)?.name||'授权环境'}<small className="block muted">Metrics · {row.resourceType}</small></td><td>{new Date(row.startedAt).toLocaleString('zh-CN',{hour12:false})}</td><td><FreshObservation value={row.lastObservedAt} state={row.evaluationState} historical={row.status==='Resolved'}/></td><td>{actions(row)}</td></tr>)}</tbody></table>{!remote.loading&&!remote.error&&!remote.data?.items.length&&<div className="empty">当前筛选暂无告警事件</div>}</div><Pagination remote={remote}/></section>}
 {selected&&<ObservationDrawer eyebrow="ALERT EVENT" title="告警事件详情" onClose={closeDetail}><Feedback {...detail}/>{e&&<><div className="alert-detail-head"><div className="alert-badges"><AlertBadge value={e.severity} severity/><AlertBadge value={e.status}/></div><h3>{e.ruleSummary}</h3><p>{e.message}</p>{actions(e)}</div><dl className="ob-detail-grid"><dt>事件 ID</dt><dd className="mono">{e.id}</dd><dt>发生序号</dt><dd>{e.occurrenceNo}</dd><dt>规则 / 逻辑修订</dt><dd>{e.ruleRevision} / {e.logicRevision}</dd><dt>环境</dt><dd>{ws.tree.environments.find(v=>v.id===e.scope.environmentId)?.name||e.scope.environmentId}</dd><dt>条件起始 / 触发</dt><dd>{new Date(e.conditionStartedAt).toLocaleString()} / {new Date(e.startedAt).toLocaleString()}</dd><dt>最近有效观测</dt><dd><FreshObservation value={e.lastObservedAt} state={e.evaluationState} historical={e.status==='Resolved'}/></dd><dt>最近值 / 条件</dt><dd>{e.lastValue??'—'} / {e.lastCondition===null?'Unknown':e.lastCondition?'成立':'不成立'}</dd><dt>首位确认人 / 时间</dt><dd>{e.ackedBy||'—'} / {e.ackedAt?new Date(e.ackedAt).toLocaleString():'—'}</dd><dt>静默截止 / 原因</dt><dd>{e.silencedUntil?new Date(e.silencedUntil).toLocaleString():'—'} / {e.silenceReason||'—'}</dd><dt>解决人 / 原因</dt><dd>{e.resolvedBy||(e.status==='Resolved'?'系统':'—')} / {e.resolveReason||'—'}</dd></dl><div className="notice">人工解决后的持续故障处于抑制状态；实际恢复后重新布防，新故障生成新事件。外部通知记录保留冻结目标及实际尝试；人工解决不表示指标恢复。</div><div className="ob-footer-links">{session.can('metrics.read',e.scope)&&<button className="text-btn" onClick={()=>ws.selectScope(e.scope,(e.resourceType==='Api'?'/observability/apis/'+e.resourceId:'/observability/metrics')+'?range=1h')}>查看关联环境指标 →</button>}{session.can('alert.rule.manage',e.scope,true)&&<Link to={'/observability/alert-rules?edit='+e.ruleId}>查看当前规则 →</Link>}</div><NotificationDeliveryList key={e.id} eventId={e.id} scope={e.scope}/><h3>处理时间线</h3><ol className="alert-timeline">{e.transitions.map(t=><li key={t.id}><time>{new Date(t.occurredAt).toLocaleString('zh-CN',{hour12:false})}</time><strong>{t.fromStatus?alertStatusNames[t.fromStatus]+' → ':''}{alertStatusNames[t.toStatus]}</strong><p>{({Triggered:'阈值满足',Ack:'确认',Unsilenced:'解除静默',SilenceExpired:'静默到期',Recovered:'条件恢复',RuleDisabled:'规则禁用',RuleChanged:'规则逻辑变更',ResourceRetired:'资源已退役'} as Record<string,string>)[t.reason]||t.reason}</p><small>{t.actorId||'系统'} · 关联 {t.correlationId}</small></li>)}</ol></>}</ObservationDrawer>}
 {action&&<AlertActionDialog event={action.event} kind={action.kind} onClose={()=>setAction(undefined)} onSaved={()=>{remote.reload();detail.reload();}}/>}</>;
}
