import {ApiError} from "../api/transport.mjs";import {loginProtectionMessage} from "../auth/login-protection.mjs";
import {useEffect,useState,type FormEvent} from 'react';import {IconShieldCheck} from '@tabler/icons-react';import {useSession} from '../auth/SessionProvider';import {refreshCsrfToken} from '../api/transport.mjs';import {fetchLoginProviders,createSsoStartForm,ssoErrorMessage,loginReturnPath} from '../sso/login.mjs';import type {PublicSsoProvider} from '../sso/contracts';import {navigate} from '../Shell';
export function Login(){const{login}=useSession(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[providers,setProviders]=useState<PublicSsoProvider[]>([]),[providerError,setProviderError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[reauthenticate,setReauthenticate]=useState(false);const search=location.search,params=new URLSearchParams(search),organization=params.get('organizationId')||undefined,returnPath=loginReturnPath(location.pathname,search),oidcError=ssoErrorMessage(search);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setProviderError('');void fetchLoginProviders(organization,controller.signal).then(result=>{if(!controller.signal.aborted)setProviders(result);},e=>{if(!controller.signal.aborted){setProviders([]);setProviderError((e as Error).message);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[organization,retry]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await login(String(f.get('username')),String(f.get('password')));navigate(returnPath);}catch(e){setError(e instanceof ApiError?loginProtectionMessage(e.code,e.retryAfterSeconds)||e.message:(e as Error).message);}finally{setBusy(false);}}
 async function enterprise(id:string){setBusy(true);setError('');try{const csrf=await refreshCsrfToken(),form=createSsoStartForm(id,returnPath,csrf,reauthenticate);form.hidden=true;document.body.appendChild(form);form.submit();}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="login"><div className="login-intro"><div className="brand-mark">W</div><small>WEBAPI PLATFORM ENTERPRISE</small><h1>统一管理 API<br/>连接每一个业务系统</h1><p>从工作草稿到审批发布，以可靠的配置和清晰的运行事实管理企业 API。</p><div className="login-lines"><span>01　配置与版本管理</span><span>02　独立审批与可追溯发布</span><span>03　多节点运行状态</span></div></div><div className="login-form"><small>MANAGEMENT CONSOLE</small><h2>登录管理控制台</h2><p>选择企业身份源，或使用已开通的本地账号</p>{oidcError&&<div className="error" role="alert">{oidcError}</div>}{error&&<div role="alert" className="error">{error}</div>}
 {(providers.length>0||loading||providerError)&&<section className="sso-login-options" aria-label="企业登录"><h3><IconShieldCheck size={17}/> 企业单点登录</h3>{loading&&<p role="status">正在读取企业登录入口…</p>}{providers.map(p=><button type="button" key={p.id} className="btn sso-login-button" disabled={busy} onClick={()=>void enterprise(p.id)}>{p.name}{p.isDefault&&<span className="badge blue">默认</span>}<span>→</span></button>)}{providerError&&<div className="error" role="alert">{providerError}<button type="button" className="text-btn" disabled={busy||loading} onClick={()=>setRetry(n=>n+1)}>重试读取</button></div>}{providers.length>0&&<label className="sso-reauth"><input type="checkbox" checked={reauthenticate} onChange={e=>setReauthenticate(e.target.checked)}/>在身份服务重新验证账号</label>}</section>}
 <form onSubmit={submit}><div className="sso-local-heading">本地账号登录</div><label>用户名<input name="username" autoComplete="username" required maxLength={128}/></label><label>密码<input name="password" type="password" autoComplete="current-password" required/></label><button className="btn primary" disabled={busy}>{busy?'正在验证…':'登录'}</button></form><footer>企业账号与权限由平台管理员显式开通。<br/>平台退出仅结束本平台会话，身份服务会话可能仍然有效。</footer></div></div>;
}
