import {useEffect,useRef,useState} from 'react';import {IconChartLine,IconActivity,IconClock,IconAlertTriangle,IconArrowUpRight,IconRefresh} from '@tabler/icons-react';
import {useWorkspace,Link,navigate} from '../Shell';import {useSession} from '../auth/SessionProvider';import {ApiError} from '../api/client';import {loadMetrics,type MetricsDto,type ObservationEnvelope,type MetricValue} from '../api/observability';
import {parseObservationSearch,serializeObservationSearch,observationRange,createObservationGate,metricDisplay,type ObservationSearch} from '../observability/query-state.mjs';import {TrendChart} from '../observability/TrendChart';import {SourceNotice,sourceNames} from '../observability/SourceNotice';
const metricNames:Record<string,string>={request_count:'请求总数',request_rps:'平均吞吐 RPS',success_ratio:'请求成功率',error_4xx_count:'4xx 请求',error_4xx_ratio:'4xx 占比',error_5xx_count:'5xx 请求',error_5xx_ratio:'5xx 占比',latency_p50_ms:'P50 延迟',latency_p95_ms:'P95 延迟',latency_p99_ms:'P99 延迟',unhealthy_destinations:'异常后端目标',cancelled_count:'客户端取消'};
const tabs:[ObservationSearch['range'],string][]=[['1h','近 1 小时'],['6h','近 6 小时'],['24h','近 24 小时'],['7d','近 7 天']];
const icons=[IconActivity,IconChartLine,IconActivity,IconClock,IconAlertTriangle,IconClock];
const primary=['request_count','request_rps','success_ratio','latency_p95_ms','error_5xx_ratio','unhealthy_destinations'];
export function MetricsOverview({apiId,search}:{apiId?:string;search:string}){
 const ws=useWorkspace(),session=useSession(),query=parseObservationSearch(search),gate=useRef(createObservationGate());
 const scope={organizationId:ws.organizationId,projectId:ws.projectId,environmentId:query.all?null:ws.environmentId,allAccessibleEnvironments:!!query.all};
 const allowed=!!ws.projectId&&!session.error&&(query.all?session.user?.permissions.includes('metrics.read'):session.can('metrics.read',ws.scope));
 const authority=JSON.stringify([session.user?.id,session.user?.permissions,session.user?.scopes,session.error]);const identity=JSON.stringify([scope,query,apiId,authority]);
 const[result,setResult]=useState<{identity:string;data?:ObservationEnvelope<MetricsDto>;error:string;loading:boolean}>({identity:'',error:'',loading:false}),[tick,setTick]=useState(0);
 const path=apiId?`/observability/apis/${apiId}`:'/observability/metrics';
 function update(patch:Partial<ObservationSearch>){navigate(path+serializeObservationSearch({...query,...patch,end:patch.end??query.end??new Date().toISOString(),cursor:undefined,page:patch.page??1}));}
 useEffect(()=>{if(!query.end)navigate(path+serializeObservationSearch({...query,end:new Date().toISOString()}),true);},[search,path]);
 useEffect(()=>{const timer=setInterval(()=>setTick(t=>t+1),30_000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{
  const request=gate.current.begin(JSON.stringify([scope,authority]),query.cursor);setResult({identity,error:'',loading:!!allowed&&!!query.end});
  if(!allowed||!query.end)return()=>request.controller.abort();
  const range=observationRange(query);void loadMetrics(scope,range,{apiId:apiId||query.api,applicationId:query.app,destinationId:query.destination,groupBy:query.group,sortBy:query.sort,page:query.page,pageSize:50},request.signal).then(data=>{if(gate.current.isCurrent(request))setResult({identity,data,error:'',loading:false});}).catch(e=>{if(gate.current.isCurrent(request))setResult({identity,error:e instanceof ApiError&&[401,403,404].includes(e.status)?'数据范围或权限已失效，指标已清除。':(e as Error).message,loading:false});});
  return()=>request.controller.abort();
 },[identity,tick,allowed]);
 const current=result.identity===identity&&allowed?result:undefined,envelope=current?.data,data=envelope?.data;const value=(key:string):MetricValue|undefined=>data?.kpis.find(k=>k.metric===key);
 const healthApplicable=!(apiId||query.api||query.app);
 const range=envelope?.range||observationRange(query),related=serializeObservationSearch({...query,api:apiId||query.api,page:1,cursor:undefined});
 return <><div className="breadcrumb"><Link to="/observability/metrics">运行监控</Link> / {apiId?'API 监控详情':'监控总览'}</div>
 <div className="page-head"><div><div className="ob-eyebrow">OBSERVABILITY · {apiId?'API INSIGHTS':'OVERVIEW'}</div><h1>{apiId?'API 监控详情':'监控总览'}</h1><p>{apiId?'查看当前 API 在授权环境中的调用；后端健康暂不支持 API 维度':'追踪请求流量、服务质量与采集覆盖'}</p></div><div className="actions">{apiId&&session.can('alert.rule.manage',ws.scope,true)&&<Link to={'/observability/alert-rules?create=true&api='+apiId}>创建告警规则</Link>}{apiId&&!!ws.projectId&&session.can('api.read',ws.scope)&&<Link to={'/apis/'+apiId}>API 定义 <IconArrowUpRight size={14}/></Link>}<button className="btn" disabled={!allowed||current?.loading} onClick={()=>update({end:new Date().toISOString()})}><IconRefresh size={15}/> 刷新窗口</button></div></div>
 <div className="ob-toolbar"><div className="ob-range-tabs" role="group" aria-label="查询时间范围">{tabs.map(([key,label])=><button aria-pressed={query.range===key} className={query.range===key?'selected':''} key={key} onClick={()=>update({range:key,end:new Date().toISOString()})}>{label}</button>)}</div><label>数据范围<select aria-label="监控数据范围" value={query.all?'all':'environment'} onChange={e=>update({all:e.target.value==='all'})}><option value="environment">当前环境</option><option value="all">全部可访问环境</option></select></label><small>截止 {new Date(range.end).toLocaleString('zh-CN',{hour12:false})}</small></div>
 {!ws.projectId?<div className="card empty">尚无可访问项目。请先选择组织、项目和环境。</div>:!allowed?<div className="error" role="alert">当前范围没有 metrics.read 权限，指标已清除。</div>:<><SourceNotice value={envelope} error={current?.error} loading={current?.loading} retry={()=>setTick(t=>t+1)}/>
 <div className="ob-kpi-grid">{primary.map((key,i)=>{const k=value(key),Icon=icons[i];return <section className="card ob-kpi" key={key}><div><span>{metricNames[key]}</span><Icon size={17}/></div><strong>{k?metricDisplay(k):'—'}</strong><small>{k?(k.state==='NotApplicable'?'该维度暂不支持':k.value===null?'暂无可用指标':sourceNames[k.state]):'等待查询'} · 样本 {k?.sampleCount.toLocaleString()??'—'}</small></section>;})}</div>
 <div className="ob-toolbar"><label>趋势指标<select aria-label="趋势指标" value={query.trend||'latency_p95_ms'} onChange={e=>update({trend:e.target.value})}>{['request_rps','success_ratio','error_4xx_ratio','error_5xx_ratio','latency_p50_ms','latency_p95_ms','latency_p99_ms'].map(key=><option key={key} value={key}>{metricNames[key]}</option>)}</select></label></div><div className="ob-trend-grid">{[['request_rps','请求吞吐趋势','requests/s'],[query.trend||'latency_p95_ms',metricNames[query.trend||'latency_p95_ms'],(query.trend||'latency_p95_ms').includes('latency')?'ms':query.trend==='request_rps'?'requests/s':'ratio'],['error_5xx_ratio','5xx 错误占比','ratio']].map(([key,label,unit],index)=><TrendChart key={key+index} points={data?.trends[key]||[]} label={label} unit={unit} sampleCount={value(key)?.sampleCount||0}/>)}</div>
 <div className="ob-secondary">{['latency_p50_ms','latency_p99_ms','error_4xx_count','error_4xx_ratio','error_5xx_count','cancelled_count'].map(key=><div key={key}><small>{metricNames[key]}</small><strong>{value(key)?metricDisplay(value(key)!):'—'}</strong></div>)}</div>
 <section className="card"><div className="ob-card-head"><div><h3>调用排行榜</h3><small>{query.sort?.startsWith('latency')?'慢调用排序':'按所选指标降序'} · 授权范围内聚合</small></div><label>排序<select aria-label="指标排序" value={query.sort||'request_count'} onChange={e=>update({sort:e.target.value})}><option value="request_count">请求量</option><option value="latency_p95_ms">慢 API · P95</option><option value="latency_p99_ms">慢 API · P99</option><option value="error_5xx_ratio">5xx 占比</option></select></label><label>分组<select aria-label="指标分组" value={query.group} onChange={e=>update({group:e.target.value as ObservationSearch['group']})}><option value="Api">API</option><option value="Application">应用</option><option value="Destination">后端目标</option><option value="Status">HTTP 状态</option><option value="None">不分组</option></select></label></div><div className="table-wrap"><table><thead><tr><th>资源</th><th>请求量</th><th>平均 RPS</th><th>成功率</th><th>P95 延迟</th><th>5xx 占比</th><th>关联数据</th></tr></thead><tbody>{data?.groups.map(row=>{const rowValue=(key:string)=>{const k=row.values.find(v=>v.metric===key);return k?metricDisplay(k):'—';};const isId=/^[0-9a-f-]{36}$/i.test(row.key),queryFilter=query.group==='Api'?{api:row.key}:query.group==='Application'?{app:row.key}:{destination:row.key};return <tr key={row.key}><td>{isId&&query.group==='Api'?<Link to={'/observability/apis/'+row.key+related}>{row.name}</Link>:isId&&query.group==='Application'&&session.can('app.read',ws.scope)?<Link to={'/applications/'+row.key}>{row.name}</Link>:row.name}</td>{['request_count','request_rps','success_ratio','latency_p95_ms','error_5xx_ratio'].map(key=><td key={key}>{rowValue(key)}</td>)}<td>{session.can('log.read',ws.scope)&&isId?<Link to={'/observability/logs'+serializeObservationSearch({...query,...queryFilter,page:1,cursor:undefined})}>访问日志</Link>:<small>—</small>}</td></tr>;})}</tbody></table>{!data?.groups.length&&<div className="empty">当前窗口暂无可用分组</div>}</div><div className="pagination"><span>共 {data?.totalGroups??0} 个分组 · 每页 50 个</span><div><button disabled={!data||data.page<=1||current?.loading} onClick={()=>update({page:(data?.page||1)-1})}>上一页</button><span>{data?.page??query.page}</span><button disabled={!data||data.page*data.pageSize>=data.totalGroups||current?.loading} onClick={()=>update({page:(data?.page||1)+1})}>下一页</button></div></div></section>
 <section className="card ob-nodes"><div className="ob-card-head"><h3>{healthApplicable?'采集节点与后端健康':'采集节点'}</h3><small>{healthApplicable?'健康状态来源于网关实际探测':'后端健康暂不支持 API / 应用维度，显示 —'}</small></div><div className="table-wrap"><table><thead><tr><th>节点</th><th>环境</th><th>采集</th><th>Healthy</th><th>Unhealthy</th><th>Unknown / Disabled</th></tr></thead><tbody>{data?.nodeHealth.map(node=><tr key={node.environmentId+node.nodeName}><td>{node.nodeName}</td><td>{ws.tree.environments.find(e=>e.id===node.environmentId)?.name||'—'}</td><td><span className={'badge '+(node.health==='Available'?'green':'amber')}>{node.health==='Available'?'新鲜':'缺失 / 过期'}</span></td><td>{healthApplicable?node.destinations.filter(d=>d.health==='Healthy').length:'—'}</td><td>{healthApplicable?node.destinations.filter(d=>d.health==='Unhealthy').length:'—'}</td><td>{healthApplicable?node.destinations.filter(d=>['Unknown','Disabled'].includes(d.health)).length:'—'}</td></tr>)}</tbody></table>{!data?.nodeHealth.length&&<div className="empty">暂无已启用采集节点</div>}</div></section>
 <div className="ob-footer-links">{session.can('log.read',ws.scope)&&<Link to={'/observability/logs'+related}>查看访问日志 →</Link>}{session.can('trace.read',ws.scope)&&<Link to={'/observability/traces'+related}>查找调用链 →</Link>}<span className="muted">请求数与分位延迟为采样估计 · 熔断 / 限流尚未启用</span></div>
 </>}</>;
}
