import {useEffect,useState} from 'react';
import {Link,useWorkspace} from '../Shell';
import {useSession} from '../auth/SessionProvider';
import {apiRequest} from '../api/client';
import {useDeliveryData,deliveryCommand} from '../delivery/api';
import {PipelineDefinitionEditor} from '../delivery/PipelineDefinitionEditor';
import {deliveryAuthorityKey} from '../delivery/delivery-state.mjs';
import {pipelineCanManage,validatePipelineDefinition} from '../delivery/pipeline-state.mjs';
import type {PipelineDefinition} from '../delivery/pipeline-state.mjs';
import {pipelineEnvironments} from './ReleasePipelines';
import {Feedback,Editor} from '../ui';
export function ReleasePipelineDetail({id,search=''}:{id:string;search?:string}){
 const ws=useWorkspace(),{user}=useSession(),[edit,setEdit]=useState(false),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[actionError,setActionError]=useState('');const versionId=new URLSearchParams(search).get('version');useEffect(()=>{setEdit(false);setBusy(false);setSelected('');setActionError('')},[id,search,deliveryAuthorityKey(user)]);
 const remote=useDeliveryData('pipeline:'+id+':'+(versionId||''),async signal=>{const exact=id==='active'&&versionId?await apiRequest<any>(`/release-pipeline-versions/${versionId}`,{signal}):undefined;const row=await apiRequest<any>(`/release-pipelines/${exact?.pipelineId||id}`,{signal});const [versions,policy]=await Promise.all([apiRequest<any[]>(`/release-pipelines/${row.id}/versions`,{signal}),apiRequest<any>(`/projects/${row.projectId}/delivery-policy`,{signal})]);return {row,versions:exact&&!versions.some(v=>v.id===exact.id)?[exact,...versions]:versions,policy};});
 const data=remote.data,row=data?.row,project=ws.tree.projects.find(p=>p.id===row?.projectId),scope=project?{organizationId:project.organizationId,projectId:project.id}:undefined,manage=pipelineCanManage(user,scope)&&row?.status==='Active',envs=pipelineEnvironments(ws.tree,row?.projectId||'');
 const current=data?.versions.find((v:any)=>v.id===(selected||versionId))||data?.versions[0],active=data?.versions.some((v:any)=>v.id===data.policy.activePipelineVersionId);
 async function command(kind:'publish'|'activate'|'archive'){if(!manage||busy)return;const alive=remote.lease();setBusy(true);setActionError('');try{if(kind==='publish')await deliveryCommand(`/release-pipelines/${row.id}/versions`,{},crypto.randomUUID(),row.revision);if(kind==='activate')await deliveryCommand(`/projects/${row.projectId}/delivery-policy/activate-pipeline`,{pipelineVersionId:current.id},crypto.randomUUID(),data.policy.revision);if(kind==='archive')await deliveryCommand(`/release-pipelines/${row.id}/archive`,{},crypto.randomUUID(),row.revision);if(alive()){remote.reload();ws.refresh();}}catch(e:any){if(alive()){setActionError(e.message);remote.fail(e);if([409,412].includes(e.status))remote.reload();}}finally{if(alive())setBusy(false);}}
 return <><div className="page-head"><div><h1>{row?.name||'流水线配置'}</h1><p>草稿可以修改；已发布版本不可修改，激活仅切换项目交付规则。</p></div><Link to="/delivery/pipelines">返回流水线列表</Link></div><Feedback {...remote}/>{data&&<><p>草稿修订 {row.revision} · {row.status==='Active'?'可用':'已归档'} · 当前授权{manage?'可管理':'只读'}</p>{actionError&&<p className="error" role="alert">{actionError}</p>}<section className="card delivery-section"><h2>工作草稿</h2>{row.draft&&<PipelineDefinitionEditor value={row.draft} environments={envs} readOnly onChange={()=>{}}/>}{manage&&<div className="actions"><button disabled={busy} onClick={()=>setEdit(true)}>编辑草稿</button><button disabled={busy} onClick={()=>command('publish')}>发布固定版本</button><button disabled={busy||active} onClick={()=>command('archive')}>归档流水线</button></div>}{active&&<p className="notice">该流水线仍在生效。须先在交付连接配置显式恢复合法连接，再归档。</p>}</section><section className="card delivery-section"><h2>固定版本</h2><label>查看版本<select value={current?.id||''} onChange={e=>setSelected(e.target.value)}>{data.versions.map((v:any)=><option key={v.id} value={v.id}>版本 {v.versionNo}{v.id===data.policy.activePipelineVersionId?' · 生效中':''}</option>)}</select></label>{current?<><p>定义指纹：<code>{current.definitionHash}</code></p><p>发布于 {current.createdAt}</p>{current.content&&<PipelineDefinitionEditor value={current.content.definition} environments={envs} readOnly onChange={()=>{}}/>}{current.content?.profiles.map((p:any)=><p key={p.order}>阶段 {p.order} 审批：{p.approval?`模板 ${p.approval.flowId} · 修订 ${p.approval.flowRevision} · ${p.approval.rules.map((r:any)=>`${r.roleCode} ${r.requiredCount} 人`).join(' → ')}`:'无需审批'}</p>)}{manage&&<button className="btn primary" disabled={busy||current.id===data.policy.activePipelineVersionId} onClick={()=>command('activate')}>激活所选版本的项目门禁</button>}<p className="notice">激活前服务器核对完整环境链、目标写权限、生产入口、审批模板和真实生产基线；不会执行部署。</p></>:<p>尚无固定版本，请先发布版本。</p>}<Link to="/delivery/policy">查看项目交付连接与停用入口</Link></section></>}{edit&&data&&manage&&<Editor title="编辑标准流水线草稿" fields={[]} initial={row.draft} explicitSubmitOnly allowed={manage} conflictStatuses={[409,412]} close={()=>setEdit(false)} help="发布版本与激活门禁分别操作。" loadLatest={async()=>{const alive=remote.lease(),latest=await apiRequest<any>(`/release-pipelines/${row.id}`);if(!alive())throw new Error('访问范围已变化，请重新打开。');return {...latest.draft,revision:latest.revision};}} renderFields={(v,change)=><PipelineDefinitionEditor value={v as PipelineDefinition} environments={envs} readOnly={false} onChange={next=>{for(const [key,value] of Object.entries(next))change(key,value)}}/>} save={async(v,key,fresh)=>{const errors=validatePipelineDefinition(v as PipelineDefinition,envs);if(errors.length)throw new Error(errors.join(' '));const alive=remote.lease();try{await deliveryCommand(`/release-pipelines/${row.id}`,{name:v.name,description:v.description,stages:v.stages},key,fresh?.revision??row.revision,'PUT');if(alive())remote.reload();}catch(e){if(alive())remote.fail(e);throw e;}}}/>}</>;
}
