import {useEffect,useRef,useState,type FormEvent} from 'react';
import {IconShieldCheck,IconPlus,IconCopy,IconKey,IconCheck} from '@tabler/icons-react';
import {apiRequest,ApiError} from '../api/client';
import {useSession} from '../auth/SessionProvider';
import {usePaged,useRemote,useUnsaved,Feedback,Pagination,Details} from '../ui';
import type {Resource,Page} from '../api/types';
import type {SsoState,SsoProvider,SsoDraft} from '../sso/contracts';
import {createSsoState,beginSsoRequest,applySsoResponse,applySsoFailure,invalidateSsoState,ssoAuthorityKey,canEnableSsoProvider,ssoSemanticKey,toSsoCommand,createSsoMutationGate,SSO_SECRET_REFERENCE_PATTERN,SSO_PROVIDER_NAME_MAX} from '../sso/state.mjs';
const base='/settings/sso/providers';
const emptyDraft:SsoDraft={organizationId:null,name:'',issuer:'',clientId:'',secretRef:'file://sso/',scopesText:'openid profile email',displayNameClaim:'name',emailClaim:'email'};
const stageNames:Record<string,string>={secretReference:'部署引用',discovery:'Discovery 与公开签名密钥',code:'授权码流程',pkce:'PKCE S256',clientSecretPost:'客户端认证方式',loginNotVerified:'用户登录验证范围'};
export function SsoProviders(){
 const session=useSession(),[search,setSearch]=useState(''),[organization,setOrganization]=useState(''),[state,setState]=useState<SsoState>(createSsoState),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[discard,setDiscard]=useState(false),[confirmation,setConfirmation]=useState<string|null>(null);
 const authorized=session.can('system.sso.manage'),authority=ssoAuthorityKey(session.user),ref=useRef(state),sessionRef=useRef(session),controller=useRef<AbortController|null>(null),checking=useRef(false),mutation=useRef(createSsoMutationGate()),retry=useRef({semantic:'',key:''}),dialog=useRef<HTMLFormElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 ref.current=state;sessionRef.current=session;
 const list=usePaged(authorized?base+'?'+new URLSearchParams({search,...(organization?{organizationId:organization}:{})}):null),organizations=useRemote<Page<Resource>>(authorized?'/organizations':null,0,true);
 const update=(next:SsoState)=>{ref.current=next;setState(next);};
 function clear(){mutation.current.reset();controller.current?.abort();update(invalidateSsoState(ref.current));retry.current={semantic:'',key:''};setOpen(false);setBusy(false);setLoading(false);setConfirmation(null);setDiscard(false);}
 function invalidate(){clear();setError('会话或 SSO 管理权限已失效，已清空详情与引用草稿。');}
 useUnsaved(state.dirty,()=>setError('仍有未保存的修改，请先保存，或关闭抽屉并明确放弃输入。'));
 useEffect(()=>{if(!authorized)invalidate();return()=>{controller.current?.abort();ref.current=invalidateSsoState(ref.current);};},[authority]);
 useEffect(()=>{const expired=()=>invalidate(),refresh=()=>void recheck();window.addEventListener('session-expired',expired);window.addEventListener('permission-refresh',refresh);return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('permission-refresh',refresh);};},[authority]);
 useEffect(()=>{if(open){previousFocus.current=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLElement>('button')?.focus();return()=>previousFocus.current?.focus();}},[open]);
 useEffect(()=>{if(discard||confirmation)dialog.current?.querySelector<HTMLElement>('[role=alertdialog] button')?.focus();},[discard,confirmation]);
 async function recheck(){if(checking.current)return;checking.current=true;const epoch=ref.current.epoch;try{await apiRequest(base+'?pageSize=1');if(ref.current.epoch!==epoch)return;list.reload();if(ref.current.providerId&&!mutation.current.busy)await read(ref.current.providerId,true);}catch(e){if(ref.current.epoch===epoch&&e instanceof ApiError&&[401,403,404].includes(e.status))invalidate();}finally{checking.current=false;}}
 async function read(id:string,keep=false){controller.current?.abort();const request=new AbortController();controller.current=request;const next=keep?{...ref.current,epoch:ref.current.epoch+1}:beginSsoRequest(ref.current,id);update(next);setOpen(true);setLoading(true);setError('');setMessage('');setConfirmation(null);setDiscard(false);
  try{const result=await apiRequest<SsoProvider>(base+'/'+id,{signal:request.signal});if(!request.signal.aborted)update(applySsoResponse(ref.current,result,next.epoch));}catch(e){if(!request.signal.aborted&&ref.current.epoch===next.epoch){const status=e instanceof ApiError?e.status:0;update(applySsoFailure(ref.current,status,next.epoch));if([401,403,404].includes(status))invalidate();else setError((e as Error).message);}}finally{if(ref.current.epoch===next.epoch)setLoading(false);}
 }
 function create(){clear();update({...beginSsoRequest(ref.current,null),draft:{...emptyDraft,organizationId:organization||null}});setError('');setMessage('');setOpen(true);}
 function change(key:keyof SsoDraft,value:string|null){update({...ref.current,draft:{...ref.current.draft!,[key]:value},dirty:true});setMessage('');}
 async function command(operation:string){const current=ref.current;if(!current.draft||current.conflict||busy||loading||!sessionRef.current.can('system.sso.manage')||sessionRef.current.error)return;
  const token=mutation.current.begin(current.epoch);if(!token)return;
  const epoch=current.epoch,body=operation==='save'?toSsoCommand(current.draft):{},semantic=ssoSemanticKey(operation,{id:current.providerId,body},current.etag);if(retry.current.semantic!==semantic)retry.current={semantic,key:crypto.randomUUID()};setBusy(true);setError('');setMessage('');
  try{const result=await apiRequest<any>(base+(current.providerId?'/'+current.providerId:'')+(operation==='save'?'':'/'+operation),{method:operation==='save'&&current.providerId?'PUT':'POST',body,etag:current.etag||undefined,idempotencyKey:retry.current.key});if(ref.current.epoch!==epoch)return;setConfirmation(null);
   if(operation==='save'&&!current.providerId){const next=beginSsoRequest(ref.current,result.id);update(applySsoResponse(next,result,next.epoch));}else if(operation==='test'){const latest=await apiRequest<SsoProvider>(base+'/'+current.providerId);if(ref.current.epoch!==epoch)return;update(applySsoResponse({...ref.current,dirty:false},latest,epoch));}else update(applySsoResponse({...ref.current,dirty:false,conflict:false},result,epoch));
   retry.current={semantic:'',key:''};list.reload();setMessage(operation==='test'?'连接测试已完成；完整登录仍需使用企业登录入口验证。':operation==='rotate'?'认证修订已更新，旧 SSO 会话将在下一次请求失效。':'操作已保存。');
  }catch(e){if(ref.current.epoch===epoch){const status=e instanceof ApiError?e.status:0;update(applySsoFailure(ref.current,status,epoch));if([401,403,404].includes(status))invalidate();else setError((e as Error).message);}}finally{if(mutation.current.finish(token))setBusy(false);}
 }
 const rows=(list.data?.items||[]) as SsoProvider[],draft=state.draft,provider=state.loaded,blocked=busy||loading||!!session.error||!authorized;
 return <><div className="breadcrumb">审计与设置 / 企业单点登录</div><div className="page-head"><div><h1>SSO 身份源 <span className="badge blue">OIDC</span></h1><p>统一企业身份接入 · 独立平台治理 · 本地管理员保留恢复入口</p></div><button className="btn primary" disabled={!authorized||open} onClick={create}><IconPlus size={16}/> 新增身份源</button></div>
 <div className="sso-overview"><IconShieldCheck size={23}/><div><strong>显式账号绑定与平台权限</strong><p>登录后沿用平台角色和数据范围。企业身份源不会自动创建账号或授予权限。</p></div><span className="badge">服务端修订保护</span><span className="badge">操作可审计</span></div>
 {!authorized&&<div className="error" role="alert">需要平台 SSO 管理权限。</div>}{!open&&error&&<div className="error" role="alert">{error}</div>}
 <section className="card"><div className="sso-list-head"><div><h2>已配置身份源</h2><small>可按名称、Issuer 或所属组织查找</small></div><button className="btn" disabled={list.loading||open} onClick={()=>list.reload()}>刷新列表</button></div><div className="filters sso-filters"><label>搜索<input aria-label="搜索身份源" value={search} placeholder="名称或 Issuer" disabled={open} onChange={e=>setSearch(e.target.value)}/></label><label>治理范围<select aria-label="身份源治理范围" value={organization} disabled={open} onChange={e=>setOrganization(e.target.value)}><option value="">全部平台与组织身份源</option>{organizations.data?.items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><small>筛选独立于顶部业务范围</small></div><Feedback {...list}/><Feedback {...organizations}/>
 <div className="table-wrap"><table className="sso-table"><thead><tr><th>身份源 / Issuer</th><th>范围</th><th>状态</th><th>修订</th><th>最近连接测试</th><th>操作</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><button className="text-btn" disabled={open} onClick={()=>void read(p.id)}>{p.name}</button><small className="policy-sub">{p.issuer}</small></td><td>{p.organizationId?organizations.data?.items.find(o=>o.id===p.organizationId)?.name||'组织身份源':'平台级'}</td><td><span className={'badge '+(p.enabled?'green':'amber')}>{p.enabled?'已启用':'未启用'}</span>{p.isDefault&&<span className="badge blue">默认</span>}</td><td><span className="number">r{p.revision}</span><small className="policy-sub">认证 r{p.authRevision}</small></td><td>{p.lastTest?<><span className={'badge '+(p.lastTest.status==='Passed'?'green':'red')}>{p.lastTest.status==='Passed'?'通过':'失败'}</span><small className="policy-sub">r{p.lastTest.providerRevision} · {new Date(p.lastTest.testedAt).toLocaleString()}</small></>:'尚未测试'}</td><td><button className="text-btn" disabled={open||!authorized} onClick={()=>void read(p.id)}>配置与测试</button></td></tr>)}</tbody></table>{!rows.length&&!list.loading&&!list.error&&<div className="empty">尚无匹配的身份源。新增后完成连接测试，再启用企业登录。</div>}</div><Pagination remote={list}/></section>
 <div className="sso-help"><IconKey size={18}/><span>连接测试检查部署引用、Discovery、JWKS 和协议声明。客户端认证及用户登录需要独立完成登录验收。</span></div>
 {open&&<div className="ob-drawer-overlay"><form ref={dialog} className="ob-drawer sso-drawer" role="dialog" aria-modal="true" aria-label={state.providerId?'身份源配置':'新增身份源'} onSubmit={(e:FormEvent)=>{e.preventDefault();void command('save');}} onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();if(discard)setDiscard(false);else if(confirmation)setConfirmation(null);else if(state.dirty)setDiscard(true);else clear();}if(e.key==='Tab'){const root=e.currentTarget.querySelector('[role=alertdialog]')||e.currentTarget,items=[...root.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}><header><div><small>ENTERPRISE IDENTITY / OIDC</small><h2>{state.providerId?'身份源配置':'新增身份源'}</h2></div><button className="text-btn" type="button" disabled={busy} onClick={()=>state.dirty?setDiscard(true):clear()}>关闭</button></header>
 {provider&&<div className="sso-revisions"><span className={'badge '+(provider.enabled?'green':'amber')}>{provider.enabled?'已启用':'未启用'}</span><span>配置 r{provider.revision}</span><span>认证 r{provider.authRevision}</span>{state.dirty&&<span className="badge amber">未保存修改</span>}</div>}{loading&&<p className="empty" role="status">正在读取身份源…</p>}{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status"><IconCheck size={16}/> {message}</div>}
 {draft&&<fieldset className="sso-fields" disabled={blocked||discard||!!confirmation}><section><h3>基本配置</h3><div className="form-grid"><label>显示名称 *<input required maxLength={SSO_PROVIDER_NAME_MAX} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label>所属范围<select value={draft.organizationId||''} onChange={e=>change('organizationId',e.target.value||null)}><option value="">平台级</option>{organizations.data?.items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="sso-wide">Issuer *<input required type="url" value={draft.issuer} placeholder="https://identity.example.com/realms/enterprise" onChange={e=>change('issuer',e.target.value)}/><small>须与身份服务声明完全一致。有账号绑定后，Issuer、Client ID 与所属范围固定。</small></label><label>Client ID *<input required value={draft.clientId} onChange={e=>change('clientId',e.target.value)}/></label><label>Client Secret 引用 *<input required autoComplete="off" value={draft.secretRef} pattern={SSO_SECRET_REFERENCE_PATTERN} placeholder="file://sso/enterprise" onChange={e=>change('secretRef',e.target.value)}/><small>仅填写部署别名引用，秘密由部署文件管理。</small></label></div></section>
 {provider&&<section><h3>固定回调地址</h3><div className="sso-copy"><code>{provider.callbackUrl}</code><button type="button" className="btn" aria-label="复制回调地址" onClick={()=>void navigator.clipboard.writeText(provider.callbackUrl).then(()=>setMessage('回调地址已复制。'),()=>setError('复制失败，请手动复制回调地址。'))}><IconCopy size={15}/></button></div><small>在身份服务的客户端配置中登记此完整地址。</small></section>}
 <section><h3>授权范围与资料映射</h3><label>Scopes *<input required value={draft.scopesText} onChange={e=>change('scopesText',e.target.value)}/><small>以空格分隔，必须包含 openid。</small></label><div className="form-grid"><label>Display Name Claim<input value={draft.displayNameClaim} onChange={e=>change('displayNameClaim',e.target.value)}/></label><label>Email Claim<input value={draft.emailClaim} onChange={e=>change('emailClaim',e.target.value)}/></label></div><small>仅接受顶层字符串资料字段；角色与数据权限在平台内显式分配。</small></section></fieldset>}
 {provider&&<section className="sso-tests"><div className="sso-section-title"><h3>最近连接测试</h3><span className={'badge '+(provider.lastTest?.status==='Passed'?'green':'amber')}>{provider.lastTest?.status==='Passed'?'通过':provider.lastTest?'失败':'尚未测试'}</span></div>{provider.lastTest?<><small>测试 r{provider.lastTest.providerRevision} · {new Date(provider.lastTest.testedAt).toLocaleString()} · 启用校验有效期 15 分钟</small><ul>{provider.lastTest.stages.map(stage=><li key={stage.code}><span className={'sso-stage '+(stage.passed?'passed':'failed')}>{stage.passed?'✓':'×'}</span><div><strong>{stageNames[stage.code]||'连接检查'}</strong><small>{stage.detail}</small></div></li>)}</ul></>:<p className="empty">保存配置后执行连接测试。</p>}<div className="sso-operations"><button type="button" className="btn" disabled={blocked||state.dirty||state.conflict||discard||!!confirmation} onClick={()=>void command('test')}>测试连接</button><button type="button" className="btn" disabled={blocked||state.dirty||state.conflict||discard||!!confirmation||(!provider.enabled&&!canEnableSsoProvider(provider))} onClick={()=>setConfirmation(provider.enabled?'disable':'enable')}>{provider.enabled?'停用身份源':'启用身份源'}</button><button type="button" className="btn" disabled={blocked||state.dirty||state.conflict||discard||!!confirmation||!provider.enabled||provider.isDefault} onClick={()=>void command('default')}>设为默认</button><button type="button" className="text-btn" disabled={blocked||state.dirty||state.conflict||discard||!!confirmation} onClick={()=>setConfirmation('rotate')}>秘密轮换后更新认证修订</button></div></section>}
 {state.conflict&&<div className="notice" role="alert"><strong>身份源修订冲突，输入已保留。</strong><p>读取最新配置并核对变化，再选择采用最新修订。</p><button type="button" className="btn" disabled={busy||loading} onClick={()=>void read(state.providerId!,true)}>读取最新配置</button>{state.conflictReviewed&&<><Details value={state.loaded}/><button type="button" className="btn" onClick={()=>{update({...ref.current,conflict:false,conflictReviewed:false});setError('');}}>保留输入，采用最新修订</button></>}</div>}
 {discard&&<div className="notice" role="alertdialog" aria-label="放弃身份源修改"><p>确认放弃未保存的身份源输入？</p><button type="button" className="btn" onClick={()=>setDiscard(false)}>继续编辑</button><button type="button" className="btn danger" onClick={clear}>确认放弃</button></div>}
 {confirmation&&<div className="notice" role="alertdialog" aria-label="确认身份源操作"><p>{confirmation==='disable'?'停用后，待完成登录及现有 SSO 会话将失效。':confirmation==='rotate'?'请先完成部署秘密文件轮换。更新认证修订会使已有 SSO 会话失效。':'启用后，已绑定并获授权的账号可使用企业登录。'}</p><button type="button" className="btn" disabled={busy} onClick={()=>setConfirmation(null)}>取消</button><button type="button" className="btn primary" disabled={busy} onClick={()=>void command(confirmation)}>确认{confirmation==='disable'?'停用':confirmation==='rotate'?'更新认证修订':'启用'}</button></div>}
 <footer><button className="btn primary" disabled={blocked||!draft||state.conflict||discard||!!confirmation}>{busy?'处理中…':'保存配置'}</button><small>认证配置变更会撤销现有 SSO 会话</small></footer></form></div>}</>;
}
