import {useEffect,useRef,useState} from 'react';
import {IconSettings,IconShieldCheck,IconCloudUpload,IconServer,IconFileText,IconBell,IconCheck} from '@tabler/icons-react';
import {apiRequest,ApiError} from '../api/client';
import {useSession} from '../auth/SessionProvider';
import {useUnsaved} from '../ui';
import {navigate} from '../navigation.mjs';
import {createSettingsState,applySettingsResponse,invalidateSettingsState,applySettingsFailure,settingsSemanticKey,settingsTestMessage,toSettingsInput,settingsCommandValues,settingsGroupFromSearch} from '../settings/state.mjs';
import {NotificationSettingsPanel} from '../notifications/NotificationSettingsPanel';
import {NotificationTestDialog} from '../notifications/NotificationTestDialog';
import {mayTestNotification} from '../notifications/settings-state.mjs';
import type {NotificationChannel} from '../notifications/api';
import type {SettingsEditorState,SettingsGroupDto,SettingsPreview,SecretReferenceMutation} from '../settings/contracts';
const groups=[{key:'security',name:'安全策略',note:'登录保护、会话与新账号',icon:IconShieldCheck},{key:'release',name:'发布设置',note:'审批与保留目标',icon:IconCloudUpload},{key:'gateway',name:'Gateway 默认参数',note:'新路由与部署意向',icon:IconServer},{key:'audit',name:'审计设置',note:'导出与保留目标',icon:IconFileText},{key:'notification',name:'通知配置',note:'自动启用与真实回执',icon:IconBell}];
const labels:Record<string,string>={loginIpMaxAttempts:'每个来源 IP 的登录次数',loginIpWindowSeconds:'来源 IP 窗口 / 秒',loginAccountMaxAttempts:'每个账号的登录次数',loginAccountWindowSeconds:'账号窗口 / 秒',sessionTtlMinutes:'Session TTL / 分钟',passwordMinLength:'密码最小长度',passwordComplexity:'密码复杂度',allowedOrigins:'Allowed Origins',productionApprovalLevels:'PROD 默认审批',snapshotRetentionCount:'Snapshot 保留数',defaultRouteTimeoutMs:'默认基础超时 / ms',maxRequestBodyMb:'最大请求体 / MB',configRefreshIntervalSeconds:'Config 刷新间隔 / 秒',auditRetentionDays:'审计日志保留 / 天',auditExportEnabled:'允许审计 CSV 导出',smtpHost:'SMTP Host',smtpPort:'SMTP Port',fromEmail:'From Email',smtpSecretRef:'SMTP SecretRef',webhookUrl:'Webhook URL',webhookSecretRef:'Webhook SecretRef',smtpEnabled:'自动 Email 通知',webhookEnabled:'自动 Webhook 通知',smtpSecurity:'SMTP TLS 模式'};
const effects:Record<string,string>={LoginRequest:'下一次本地登录生效；配额变更开启新预算，成功登录仍计入次数',NewLogin:'用于后续新登录，已有票据到期时间保持不变',NewUser:'用于后续创建本地账号，已有密码仍可正常登录',NewRoute:'用于新路由基础超时，显式值优先；仍须审批发布',ExportRequest:'保存后控制新导出请求，仍需 audit.read 与授权范围',DeploymentRequired:'待部署配置；保存不会应用到运行实例',ConfigurationIntent:'配置意向；本期不执行连接、发送、跨域或历史清理',FixedConstraint:'当前固定两级独立审批，单级不可用',AutomaticNotifications:'保存后控制后续自动告警通知；禁用不撤回已经开始的发送',NewChannelProfile:'TLS 模式固定于新渠道档案；旧任务保持原档案，不改投新目标'};
const settingEffect=(effect:string,group:string)=>group==='notification'&&effect==='ConfigurationIntent'?'连接字段及引用固定于渠道档案；旧档案任务不会改投，保存本身不发送':effects[effect];
const sources:Record<string,string>={Saved:'已保存配置',CodeDefault:'兼容默认',PrototypeSuggestion:'原型建议 · 未应用'};
const limits:Record<string,[number,number]>={loginIpMaxAttempts:[1,10000],loginIpWindowSeconds:[1,3600],loginAccountMaxAttempts:[1,10000],loginAccountWindowSeconds:[1,3600],sessionTtlMinutes:[5,1440],passwordMinLength:[16,128],snapshotRetentionCount:[10,10000],defaultRouteTimeoutMs:[1,300000],maxRequestBodyMb:[1,256],configRefreshIntervalSeconds:[1,60],auditRetentionDays:[30,3650],smtpPort:[1,65535]};
export function SystemSettings({search}:{search:string}){
 const session=useSession(),[state,setState]=useState<SettingsEditorState>(()=>({...createSettingsState(),group:settingsGroupFromSearch(search)})),ref=useRef(state),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<SettingsPreview|null>(null);
 const[test,setTest]=useState<{channel:NotificationChannel;revision:number;authority:string;epoch:number}|null>(null);
 const dialogRoot=useRef<HTMLElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(!preview)return;previousFocus.current=document.activeElement as HTMLElement;dialogRoot.current?.querySelector<HTMLElement>('button')?.focus();return()=>previousFocus.current?.focus();},[!!preview]);
 const sessionRef=useRef(session),checking=useRef(false);sessionRef.current=session;
 const retry=useRef({semantic:'',key:''}),authority=JSON.stringify([session.user?.id,session.user?.permissions,session.user?.scopes]);ref.current=state;
 const update=(next:SettingsEditorState)=>{ref.current=next;setState(next);};
 useUnsaved(state.dirty,()=>setError('仍有未保存的修改。请先保存，或点击“放弃当前输入”后再导航。'));
 function invalidate(){setTest(null);update(invalidateSettingsState(ref.current));setPreview(null);retry.current={semantic:'',key:''};setBusy(false);setLoading(false);checking.current=false;setError('会话或管理权限已失效，已清空配置与引用草稿。');}
 useEffect(()=>{const expired=()=>invalidate(),denied=()=>void recheckAuthority();window.addEventListener('session-expired',expired);window.addEventListener('permission-refresh',denied);return()=>{ref.current=invalidateSettingsState(ref.current);window.removeEventListener('session-expired',expired);window.removeEventListener('permission-refresh',denied);};},[session.user?.id]);
 useEffect(()=>{setTest(null);void recheckAuthority(true);},[authority]);
 useEffect(()=>{const group=settingsGroupFromSearch(search);if(group!==ref.current.group){setTest(null);setMessage('');void load(group);}},[search]);
 async function recheckAuthority(force=false){if(!sessionRef.current.user||!sessionRef.current.can('system.manage')){invalidate();return;}if(checking.current&&!force)return;checking.current=true;const next={...ref.current,requestEpoch:ref.current.requestEpoch+1};update(next);setLoading(true);setBusy(false);setPreview(null);try{const response=await apiRequest<SettingsGroupDto>('/settings/system/'+next.group);if(ref.current.requestEpoch!==next.requestEpoch)return;if(!ref.current.loaded)update(applySettingsResponse(ref.current,response,next.requestEpoch));setError('');}catch(e){if(ref.current.requestEpoch===next.requestEpoch){update(applySettingsFailure(ref.current,e instanceof ApiError?e.status:0));if(e instanceof ApiError&&[401,403,404].includes(e.status)){invalidate();}else setError((e as Error).message);}}finally{if(ref.current.requestEpoch===next.requestEpoch){checking.current=false;setLoading(false);}}}
 async function load(group:string,keepDraft=false){checking.current=false;const old=ref.current,next={...(keepDraft?old:invalidateSettingsState(old)),group,requestEpoch:old.requestEpoch+1};update(next);setPreview(null);setLoading(true);setError('');try{const response=await apiRequest<SettingsGroupDto>('/settings/system/'+group);if(ref.current.requestEpoch!==next.requestEpoch)return;update(applySettingsResponse(ref.current,response,next.requestEpoch));}catch(e){if(ref.current.requestEpoch===next.requestEpoch){update(applySettingsFailure(ref.current,e instanceof ApiError?e.status:0));setError((e as Error).message);}}finally{if(ref.current.requestEpoch===next.requestEpoch)setLoading(false);}}
 function change(key:string,value:any){setTest(null);update({...ref.current,values:{...ref.current.values,[key]:value},dirty:true});setPreview(null);setMessage('');}
 function switchGroup(group:string){if(busy||group===state.group)return;if(state.dirty&&!window.confirm('切换分组将放弃未保存的输入，是否继续？'))return;setTest(null);setMessage('');void load(group);navigate('/settings/system?tab='+group,true);}
 async function action(kind:'validate'|'preview'|'save'){
  const current=ref.current;if(!current.values||!current.etag||current.conflict||busy)return;const epoch=current.requestEpoch;setBusy(true);setError('');setMessage('');
  const commandValues=settingsCommandValues(current.group,current.values),semantic=settingsSemanticKey(current.group,commandValues,current.etag);if(semantic!==retry.current.semantic)retry.current={semantic,key:crypto.randomUUID()};
  try{const result=await apiRequest<any>('/settings/system/'+current.group+(kind==='save'?'':'/'+kind),{method:kind==='save'?'PUT':'POST',etag:current.etag,idempotencyKey:retry.current.key,body:{values:commandValues,...(kind==='save'?{confirmationToken:preview?.confirmationToken}:{})}});if(ref.current.requestEpoch!==epoch)return;
   if(kind==='validate')setMessage(settingsTestMessage(result));else if(kind==='preview')setPreview(result);else{update({...applySettingsResponse({...ref.current,dirty:false},result,epoch),dirty:false,conflict:false,conflictReviewed:false});setPreview(null);setMessage('保存成功。请按字段提示核对生效条件。');}
  }catch(e){if(ref.current.requestEpoch===epoch){update(applySettingsFailure(ref.current,e instanceof ApiError?e.status:0));if(e instanceof ApiError&&[401,403,404].includes(e.status))setPreview(null);setError((e as Error).message);}}finally{if(ref.current.requestEpoch===epoch)setBusy(false);}
 }
 const group=groups.find(g=>g.key===state.group)!,fields=state.loaded?.fields||[],values=state.values;
 return <><div className="breadcrumb">审计与设置 / 系统设置</div><div className="page-head"><div><h1>系统设置 <span className="badge blue">平台级</span></h1><p>统一配置治理 · 当前组织与项目选择不会改变设置范围</p></div><button className="btn" disabled={busy||loading} onClick={()=>void load(state.group,state.dirty)}>读取最新配置</button></div>
 <div className="settings-summary"><IconSettings size={21}/><span>5 个配置分组 · 20 个字段</span><span className="badge">{state.loaded?.revision?`已保存修订 ${state.loaded.revision}`:'尚未保存 · 显示默认与建议'}</span><span className="settings-summary-end">服务端权限 · 修订保护 · 操作审计</span></div>
 <div className="settings-layout"><nav className="card settings-nav" aria-label="设置分组">{groups.map(g=><button key={g.key} aria-current={state.group===g.key?'page':undefined} onClick={()=>switchGroup(g.key)}><g.icon size={19}/><span><strong>{g.name}</strong><small>{g.note}</small></span>{state.group===g.key&&<span className="settings-dot"/>}</button>)}<div className="settings-nav-foot">平台级管理<br/>修改需先预览并确认</div></nav>
 <section className="card settings-panel"><header><div><h2>{group.name}</h2><p>{state.group==='notification'?'渠道独立启用 · 强制 TLS · 固定秘密版本 · 实际投递回执':'每个字段显示配置来源与实际生效条件'}</p></div>{state.dirty&&<span className="badge amber">未保存修改</span>}</header>
 {loading&&<div className="empty" role="status">正在读取平台配置…</div>}{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status"><IconCheck size={16}/> {message}</div>}
 {values&&(state.group==='notification'?<NotificationSettingsPanel state={state} onChange={change} disabled={busy||loading} onTest={channel=>{if(mayTestNotification({...ref.current,busy:busy||loading,authorized:session.can('system.manage')}))setTest({channel,revision:ref.current.loaded!.revision,authority,epoch:ref.current.requestEpoch});}}/>:<fieldset className="settings-fields" disabled={busy||loading||!!session.error}>{fields.map(field=>{const key=field.key,value=values[key],isRef=key.endsWith('SecretRef'),bound=limits[key];return <label className={'settings-field '+(key==='allowedOrigins'?'settings-wide':'')} key={key}><span className="settings-label">{labels[key]}<span className="settings-source">{sources[field.source]}</span></span>
 {isRef?<><select aria-label={labels[key]+' 操作'} value={(value as SecretReferenceMutation).operation} onChange={e=>change(key,{operation:e.target.value})}><option value="Keep">保持现有引用</option><option value="Replace">替换引用</option><option value="Clear">清除引用</option></select>{(value as SecretReferenceMutation).operation==='Replace'&&<input aria-label={labels[key]+' 替换值'} type="password" autoComplete="off" placeholder="vault://provider/path" value={(value as SecretReferenceMutation).reference||''} onChange={e=>change(key,{operation:'Replace',reference:e.target.value})}/>}<small>现有引用：{state.loaded?.values[key]?.hasConfiguredReference?`已配置 · ${state.loaded.values[key].provider}`:'未配置'}。清除时须同时满足整组完整性。</small></>:
 key==='passwordComplexity'?<select aria-label={labels[key]} value={String(value)} onChange={e=>change(key,e.target.value)}><option value="LengthOnly">仅长度（兼容默认）</option><option value="LettersAndDigits">字母与数字</option><option value="UpperLowerDigitSpecial">大小写、数字与特殊字符</option></select>:
 key==='productionApprovalLevels'?<select aria-label={labels[key]} value="2" disabled><option value="2">两级独立审批</option><option value="1" disabled>单级审批（当前不可用）</option></select>:
 key==='auditExportEnabled'?<div className="settings-toggle"><input aria-label={labels[key]} type="checkbox" checked={!!value} onChange={e=>change(key,e.target.checked)}/><span>{value?'允许授权用户导出':'已关闭导出'}</span></div>:
 key==='allowedOrigins'?<textarea aria-label={labels[key]} rows={3} placeholder="每行一个精确 origin，如 https://example.com" value={Array.isArray(value)?value.join('\n'):String(value??'')} onChange={e=>change(key,e.target.value)}/>:
 <input aria-label={labels[key]} type={bound?'number':key==='fromEmail'?'email':'text'} min={bound?.[0]} max={bound?.[1]} step={bound?1:undefined} value={value===null?'':String(value??'')} onChange={e=>change(key,bound?(e.target.value===''?null:Number(e.target.value)):(e.target.value||null))}/>}<small className={'settings-effect '+(field.effect==='DeploymentRequired'?'pending':'')}>{settingEffect(field.effect,state.group)}{bound&&` · 范围 ${bound[0]}–${bound[1]}`}</small></label>;})}</fieldset>)}
 {state.conflict&&<div className="notice" role="alert"><strong>配置修订冲突，输入已保留。</strong><p>读取最新配置，核对下方来源和现有引用，再明确采用最新修订。</p><button className="btn" onClick={()=>void load(state.group,true)}>读取最新并重新核对</button>{state.conflictReviewed&&<button className="btn" onClick={()=>{update({...ref.current,conflict:false,conflictReviewed:false});setError('');}}>采用当前读取的修订并重新预览</button>}</div>}
 <footer><div><button className="btn primary" disabled={busy||loading||!values||state.conflict||!session.can('system.manage')} onClick={()=>void action('preview')}>{busy?'处理中…':'预览并保存'}</button><button className="btn" disabled={busy||loading||!values||state.conflict} onClick={()=>void action('validate')}>校验配置结构</button>{state.dirty&&<button className="text-btn" disabled={busy} onClick={()=>{if(window.confirm('确认放弃当前未保存输入？')&&state.loaded){update({...ref.current,values:toSettingsInput(state.loaded),dirty:false,conflict:false,conflictReviewed:false});setPreview(null);setError('');}}}>放弃当前输入</button>}</div><span>保存不会自动部署网关或清理历史数据</span></footer>
 </section></div>{test&&test.authority===authority&&test.epoch===state.requestEpoch&&state.group==='notification'&&session.can('system.manage')&&<NotificationTestDialog key={test.channel+':'+test.revision+':'+test.authority+':'+test.epoch} channel={test.channel} revision={test.revision} onClose={()=>setTest(null)} onDenied={invalidate} onStale={()=>{update(applySettingsFailure(ref.current,412));setPreview(null);}}/>}{preview&&<div className="overlay"><section ref={dialogRoot} className="dialog" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();setPreview(null);}if(e.key==='Tab'){const items=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}} role="dialog" aria-modal="true" aria-label="确认系统设置修改"><header><h2>确认系统设置修改</h2><button className="text-btn" disabled={busy} onClick={()=>setPreview(null)}>取消</button></header><p className="notice">平台级修改 · 确认凭证五分钟有效。保存后的作用以字段生效条件为准。</p><div className="table-wrap"><table><thead><tr><th>字段</th><th>原值</th><th>新值</th></tr></thead><tbody>{preview.differences.map(d=><tr key={d.field}><td>{labels[d.field]}</td><td>{d.before}</td><td>{d.after}</td></tr>)}</tbody></table>{!preview.differences.length&&<div className="empty">与当前默认或保存值一致，保存将明确记录本组配置。</div>}</div><div className="settings-impact">{preview.impacts.map(i=><p key={i}>{settingEffect(i,state.group)}</p>)}</div>{error&&<div className="error" role="alert">{error}</div>}<footer><button className="btn primary" disabled={busy} onClick={()=>void action('save')}>确认保存</button><span>受服务端授权、修订与幂等保护</span></footer></section></div>}</>;
}
