import {copyTraceId} from '../observability/browser-actions.mjs';import {useEffect,useRef,useState} from 'react';import {IconCopy,IconRefresh,IconHierarchy2} from '@tabler/icons-react';import {Link} from '../Shell';import {ApiError} from '../api/client';import {loadTraces,loadTraceDetail,type CursorPage,type TraceSummaryDto,type TraceDetailDto,type ObservationEnvelope} from '../api/observability';import {serializeObservationSearch} from '../observability/query-state.mjs';import {useInvestigation} from '../observability/useInvestigation';import {InvestigationFilters} from '../observability/InvestigationFilters';import {InvestigationToolbar} from '../observability/InvestigationToolbar';import {SourceNotice} from '../observability/SourceNotice';import {CursorPagination} from '../observability/CursorPagination';import {TraceWaterfall} from '../observability/TraceWaterfall';
export function Traces({search}:{search:string}){
 const view=useInvestigation<CursorPage<TraceSummaryDto>>({search,path:'/observability/traces',permission:'trace.read',load:(scope,range,q,signal)=>loadTraces(scope,range,{traceId:q.trace,apiId:q.api,minDurationMs:q.duration,outcome:q.outcome,cursor:q.cursor,limit:50},signal)}),[draft,setDraft]=useState(view.query),[detail,setDetail]=useState<{identity:string;id:string;value?:ObservationEnvelope<TraceDetailDto>;error?:string;notFound?:boolean}>(),[copied,setCopied]=useState('');const abort=useRef<AbortController|null>(null);
 useEffect(()=>{setDraft(view.query);setDetail(undefined);setCopied('');abort.current?.abort();},[view.identity]);useEffect(()=>()=>abort.current?.abort(),[]);
 async function open(id:string){abort.current?.abort();const controller=new AbortController();abort.current=controller;setDetail({identity:view.identity,id});try{const value=await loadTraceDetail(view.scope,view.range,id,controller.signal);if(!controller.signal.aborted)setDetail({identity:view.identity,id,value});}catch(e){if(!controller.signal.aborted)setDetail({identity:view.identity,id,error:(e as Error).message,notFound:e instanceof ApiError&&e.status===404});}}
 useEffect(()=>{if(view.error){setDetail(undefined);abort.current?.abort();setCopied('');}},[view.error]);
 useEffect(()=>{if(view.query.trace&&view.allowed&&view.query.end)void open(view.query.trace);},[view.identity,view.allowed]);
 async function copy(id:string){setCopied(await copyTraceId(id)?'已复制 TraceId':'复制未完成，请选中 TraceId 手动复制。');}
 const rows=view.envelope?.data?.items||[],current=detail?.identity===view.identity&&view.allowed&&!view.error?detail:undefined,related=(trace:string)=>serializeObservationSearch({...view.query,trace,cursor:undefined,page:1,outcome:undefined});
 return <><div className="breadcrumb"><Link to="/observability/metrics">运行监控</Link> / Trace 查询</div><div className="page-head"><div><div className="ob-eyebrow">OBSERVABILITY · DISTRIBUTED TRACING</div><h1>Trace 查询</h1><p>从授权请求定位真实 server / client 调用及耗时</p></div><button className="btn" disabled={!view.allowed||view.loading} onClick={()=>view.update({end:new Date().toISOString()})}><IconRefresh size={15}/>刷新窗口</button></div><InvestigationToolbar query={view.query} update={view.update} end={view.range.end}/>
 {!view.ws.projectId?<div className="card empty">尚无可访问项目。请先选择组织、项目和环境。</div>:!view.allowed?<div className="error" role="alert">当前范围没有 trace.read 权限，链路及详情已清除。</div>:<><form className="card" onSubmit={e=>{e.preventDefault();view.update(draft);}}><div className="ob-card-head"><h3>链路条件</h3><small>TraceId 不作为访问权限证明</small></div><InvestigationFilters kind="traces" value={draft} onChange={setDraft}/><div className="investigation-filter-actions"><button className="btn primary" disabled={view.loading}>查询链路</button><button type="button" className="btn" onClick={()=>view.update({api:undefined,trace:undefined,duration:undefined,outcome:undefined})}>重置筛选</button>{view.envelope?.sampling&&<small>当前配置采样率 {(view.envelope.sampling.ratio*100).toFixed(0)}% · 未命中可能未采样或超过保留期</small>}</div></form><SourceNotice value={view.envelope} error={view.error} errorStatus={view.errorStatus} loading={view.loading} noun="链路" retry={view.reload}/><section className="card"><div className="ob-card-head"><div><h3>调用链列表</h3><small>起止时间与耗时由当前可见 span 计算</small></div><IconHierarchy2 size={18}/></div><div className="table-wrap"><table><thead><tr><th>TraceId</th><th>开始时间</th><th>总耗时</th><th>调用结果</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.traceId}><td><button className="text-btn trace-id" onClick={()=>void open(row.traceId)}>{row.traceId}</button></td><td>{new Date(row.start).toLocaleString('zh-CN',{hour12:false})}</td><td className="number">{row.durationMs.toFixed(2)} ms</td><td><span className={'badge '+(row.outcome==='Error'?'red':'green')}>{row.outcome==='Error'?'错误':'成功'}</span></td><td className="row-actions"><button className="text-btn" aria-label={`复制 TraceId ${row.traceId}`} onClick={()=>void copy(row.traceId)}><IconCopy size={13}/>复制</button><button className="text-btn" onClick={()=>void open(row.traceId)}>查看链路</button>{view.session.can('log.read',view.ws.scope)&&<Link to={'/observability/logs'+related(row.traceId)}>访问日志</Link>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">{view.loading?'正在查询…':view.error?'本次查询未完成，请重试。':'NoTrace · 当前范围未找到调用链，可能未采样或超过保留期'}</div>}</div><CursorPagination count={rows.length} nextCursor={view.envelope?.data?.nextCursor} truncated={!!view.envelope?.coverage.truncated} previous={view.hasPrevious} loading={view.loading} onNext={()=>view.envelope?.data?.nextCursor&&view.next(view.envelope.data.nextCursor)} onPrevious={view.previous}/></section>{copied&&<p className="notice" role="status">{copied}</p>}
 {current&&<>{current.error?<div className={current.notFound?'notice':'error'} role={current.notFound?'status':'alert'}><strong>{current.notFound?'NoTrace · 未找到当前范围的链路':'链路查询不可用'}</strong><p>{current.error}</p><button className="btn" onClick={()=>void open(current.id)}>重新查询详情</button></div>:!current.value?.data?<div className="empty">正在读取链路详情…</div>:<><div className="trace-detail-head"><div><small>TRACE DETAIL</small><h3 className="trace-id">{current.value.data.traceId}</h3></div><div className="actions"><button className="btn" onClick={()=>void copy(current.id)}><IconCopy size={14}/>复制 TraceId</button>{view.session.can('log.read',view.ws.scope)&&<Link to={'/observability/logs'+related(current.id)}>关联日志 →</Link>}<button className="btn" onClick={()=>{abort.current?.abort();setDetail(undefined);}}>关闭链路</button></div></div><SourceNotice value={current.value} noun="链路" retry={()=>void open(current.id)}/><TraceWaterfall key={current.id} detail={current.value.data}/></>}</>}
 </>}</>;
}
