import {useEffect,useRef,useState} from 'react';import {Link,useWorkspace} from '../Shell';import {useSession} from '../auth/SessionProvider';import {apiRequest} from '../api/client';import {VersionCompareView} from '../comparisons/VersionCompareView';import {RiskReviewDialog} from '../comparisons/RiskReviewDialog';import {comparisonQueryState,comparisonRead,loadComparison,reviewRetryState,timedComparison} from '../comparisons/model.mjs';import type {ComparisonView,RiskReview} from '../comparisons/types';
export function VersionComparePage({id,search}:{id:string;search:string}){const ws=useWorkspace(),session=useSession(),key=JSON.stringify([id,ws.organizationId,ws.projectId,session.user?.id,session.user?.permissions,session.user?.scopes,session.error]);return <ComparisonPage key={key} id={id} search={search} scopeKey={key}/>;}
function ComparisonPage({id,search,scopeKey}:{id:string;search:string;scopeKey:string}){
 const ws=useWorkspace(),{can}=useSession(),[data,setData]=useState<any>(),[value,setValue]=useState<ComparisonView>(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filters,setFilters]=useState({}),[history,setHistory]=useState<any[]>([]),[cursor,setCursor]=useState<string>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dialog,setDialog]=useState(false),[reviewNote,setReviewNote]=useState(''),controller=useRef(new AbortController()),retry=useRef<any>(undefined);
 const scope=data?{organizationId:data.api.organizationId,projectId:data.api.projectId}:undefined,allowed=!!scope&&['api.read','api.version.read','api.schema.read'].every(code=>can(code,scope)),canReview=allowed&&can('api.approve',scope,true),versions=data?.versions||[];
 const current=()=>!controller.current.signal.aborted;
 async function loadHistory(next?:string){const page=await comparisonRead<any>(`/apis/${id}/version-comparisons${next?'?cursor='+encodeURIComponent(next):''}`,apiRequest,controller.current.signal);if(current()){setHistory(rows=>next?[...rows,...page.items]:page.items);setCursor(page.nextCursor);}}
 async function openReport(reportId:string){setBusy(true);setError('');try{await loadComparison(signal=>comparisonRead(`/version-comparisons/${reportId}`,apiRequest,signal),scopeKey,controller.current.signal,v=>{setValue(v);setFrom(v.from.id);setTo(v.to.id);setFilters({});});}catch(e){if(current())setError((e as Error).message);}finally{if(current())setBusy(false);}}
 useEffect(()=>{const signal=controller.current.signal;void loadComparison(async()=>{const d=await comparisonRead<any>(`/apis/${id}`,apiRequest,signal);if(ws.organizationId&&d.api.organizationId!==ws.organizationId||ws.projectId&&d.api.projectId!==ws.projectId)throw Error('该 API 不属于当前 Workspace，请选择对应组织和项目。');return d;},scopeKey,signal,d=>{setData(d);setFrom(d.versions[1]?.id||'');setTo(d.versions[0]?.id||'');}).catch(e=>{if(current())setError(e.message);}).finally(()=>{if(current())setLoading(false);});return()=>controller.current.abort();},[]);
 useEffect(()=>{if(!allowed)return;void loadHistory().catch(e=>{if(current())setError(e.message);});const selected=comparisonQueryState(search).comparisonId;if(selected)void openReport(selected);},[allowed,search]);
 async function refreshVersions(){setBusy(true);setError('');try{const d=await timedComparison(signal=>apiRequest<any>(`/apis/${id}`,{signal}),controller.current.signal);if(current()){if(d.api.organizationId!==ws.organizationId||d.api.projectId!==ws.projectId)throw Error('API 范围已变化，请重新选择 Workspace。');setData(d);setValue(undefined);setDialog(false);if(!d.versions.some((v:any)=>v.id===from))setFrom('');if(!d.versions.some((v:any)=>v.id===to))setTo('');}}catch(e){if(current())setError((e as Error).message);}finally{if(current())setBusy(false);}}
 async function create(){const a=versions.find((v:any)=>v.id===from),b=versions.find((v:any)=>v.id===to);if(!a||!b)return;setBusy(true);setError('');const body={fromVersionId:from,toVersionId:to,expectedFromRevision:a.revision,expectedToRevision:b.revision};retry.current=reviewRetryState(retry.current,body);try{const result=await timedComparison(signal=>apiRequest<ComparisonView>(`/apis/${id}/version-comparisons`,{method:'POST',body,idempotencyKey:retry.current.key,signal}),controller.current.signal);if(current()){setValue(result);setFilters({});void loadHistory().catch(e=>{if(current())setError(e.message);});}}catch(e){if(current())setError((e as Error).message);}finally{if(current())setBusy(false);}}
 async function review(body:any,key:string){try{const result=await timedComparison(signal=>apiRequest<RiskReview>(`/version-comparisons/${value!.id}/reviews`,{method:'POST',body,idempotencyKey:key,signal}),controller.current.signal);if(!current())throw Error('Workspace 已切换');setValue(v=>v?{...v,latestReview:result}:v);return result;}catch(e){if(current()&&[409,412].includes((e as any).status))setValue(v=>v?{...v,freshness:'Stale',latestReview:undefined}:v);throw e;}}
 async function exportReport(format:string){if(!value)return;setBusy(true);try{const response=await timedComparison(signal=>apiRequest<Response>(`/version-comparisons/${value.id}/export?format=${format}`,{signal,responseType:'response'}),controller.current.signal);const blob=await response.blob();if(current()){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`version-comparison-${value.id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){if(current())setError((e as Error).message);}finally{if(current())setBusy(false);}}
 return <><div className="breadcrumb"><Link to={'/apis/'+id}>API 详情</Link> / 版本比较</div><div className="page-head"><div><h1>版本比较与风险评审</h1><p>{data?.api.name||'契约比较'} · 不可变报告与可追溯评审</p></div>{value?.latestReview&&value.freshness==='Current'&&value.report.coverage!=='Invalid'&&<Link to={`/apis/${id}/wizard?reviewId=${value.latestReview.id}`}>携带评审进入发布向导 →</Link>}</div>{loading&&<div className="notice">正在读取版本与权限…</div>}{error&&<div className="error" role="alert">{error}</div>}{allowed&&<div className="card filter-bar comparison-selection"><label>比较基线 <select aria-label="比较基线" disabled={busy} value={from} onChange={e=>{setFrom(e.target.value);setValue(undefined);setDialog(false);}}><option value="">选择基线</option>{versions.map((v:any)=><option key={v.id} value={v.id}>{v.version} · {v.status} · R{v.revision}</option>)}</select></label><span aria-hidden="true">→</span><label>目标版本 <select aria-label="目标版本" disabled={busy} value={to} onChange={e=>{setTo(e.target.value);setValue(undefined);setDialog(false);}}><option value="">选择目标</option>{versions.map((v:any)=><option key={v.id} value={v.id}>{v.version} · {v.status} · R{v.revision}</option>)}</select></label><button className="btn primary" disabled={busy||!from||!to||from===to} onClick={()=>void create()}>{busy?'处理中…':'生成契约比较'}</button><button className="btn" disabled={busy} onClick={()=>void refreshVersions()}>刷新版本与修订</button></div>}<VersionCompareView value={value} versions={versions} allowed={allowed} canReview={canReview} busy={busy} filters={filters} onFilter={setFilters} onReview={()=>setDialog(true)} onExport={format=>void exportReport(format)}/>{value?.latestReview&&<div className="card"><h3>最近风险评审 · {value.latestReview.decision}</h3><p>{value.latestReview.comment||'无备注'}</p><p className="muted">{value.latestReview.createdAt} · {value.latestReview.actorId}</p></div>}{allowed&&<div className="card"><h3 className="section-title">历史比较报告</h3>{history.length?history.map(row=><div className="comparison-history-row" key={row.id}><div><strong>{row.fromVersion} → {row.toVersion}</strong><small>{row.createdAt} · {row.coverage}</small></div><span>破坏性 {row.counts.breaking} · 未知 {row.counts.unknown}</span><button className="btn" disabled={busy} onClick={()=>void openReport(row.id)}>打开报告</button></div>):<p className="empty">暂无比较报告</p>}{cursor&&<button className="btn" disabled={busy} onClick={()=>void loadHistory(cursor).catch(e=>{if(current())setError(e.message);})}>加载更多</button>}</div>}{dialog&&value&&<RiskReviewDialog value={value} allowed={canReview} onClose={()=>setDialog(false)} onSubmit={review} initialComment={reviewNote} onNote={setReviewNote}/>}</>;
}
