import test from'node:test';import assert from'node:assert/strict';import{validateFixture,validateAcceptance,finalizeAcceptance,validateCleanupResources}from'../../scripts/runtime/acceptance.mjs';
import{restoreColdBackup,coldBackup,createBackup}from'../../scripts/runtime/acceptance-backup.mjs';
const project='webapi-enterprise-local-test-11111111-1111-4111-8111-111111111111',ownerId='22222222-2222-4222-8222-222222222222';
test('fixtureCannotTargetPersistentProject',()=>{assert.throws(()=>validateFixture('webapi-enterprise-local','/tmp/webapi-enterprise-local'),/disposable/i);assert.throws(()=>validateFixture(project,'/tmp/another'),/directory/i);assert.doesNotThrow(()=>validateFixture(project,'/tmp/'+project));});
test('readinessAloneCannotPassAcceptance',()=>{assert.throws(()=>validateAcceptance({ready:true,cleanup:{containersRemaining:0,volumesRemaining:0,secretFilesRemaining:0}}),/chain|proof/i);});
test('cleanupRejectsForeignOwner',()=>{const state={projectName:project,ownerId};assert.throws(()=>validateCleanupResources(state,[{Kind:'volume',Name:project+'_pg',Labels:{'com.docker.compose.project':project,'com.webapi.runtime.owner':'other'}}]),/owner/i);assert.throws(()=>validateCleanupResources(state,[{Kind:'volume',Name:project+'_unrelated',Labels:{'com.docker.compose.project':project,'com.webapi.runtime.owner':ownerId}}]),/volume/i);});
test('cleanupFailureMakesAcceptanceFail',()=>{const proof={chain:{passed:true},restart:{passed:true},failure:{passed:true},backupRestore:{passed:true},ui:{verified:true},preservedOldEnvironment:{unchanged:true},cleanup:{containersRemaining:0,volumesRemaining:1,secretFilesRemaining:0}};assert.equal(finalizeAcceptance(proof).complete,false);assert.throws(()=>validateAcceptance(proof),/cleanup/i);});
test('restoreAndBackupCannotTargetPersistentProject',async()=>{await assert.rejects(restoreColdBackup({target:'/nonexistent-backup',directory:'/tmp/webapi-enterprise-local',projectName:'webapi-enterprise-local'}),/disposable/i);await assert.rejects(coldBackup({directory:'/tmp/webapi-enterprise-local',state:{projectName:'webapi-enterprise-local'}},'/nonexistent-parent/backup'),/disposable/i);});
test('manualBackupRequiresOwnedDirectoryBeforeWriting',async()=>{await assert.rejects(createBackup({directory:'/nonexistent-owned-runtime',state:{}},'/nonexistent-parent/backup'),/ENOENT|owner/i);});
