import test from'node:test';import assert from'node:assert/strict';import{backupStopServices}from'../../scripts/runtime/acceptance-backup.mjs';
test('backupStopsOnlyDeclaredServicesForUnboundAndNonDemoDeployments',()=>{const unbound=backupStopServices({binding:null,demoEnabled:false});assert.ok(!unbound.includes('gateway-a')&&!unbound.includes('backend-a'));assert.ok(unbound.includes('worker')&&unbound.includes('tempo'));const bound=backupStopServices({binding:{},demoEnabled:false});assert.ok(bound.includes('gateway-a')&&!bound.includes('backend-a'));assert.ok(backupStopServices({binding:{},demoEnabled:true}).includes('backend-a'));});
test('cacheBackupVolumeSelectionRetainsOldDeploymentCompatibility',async()=>{const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.ok(backupVolumeNames({cacheSupported:true}).includes('secrets-cache'));assert.ok(!backupVolumeNames({cacheSupported:false}).includes('secrets-cache'));});
test('backupFailureRestartsAllOriginalServicesEvenAfterPartialStop',async()=>{const{withBackupServicesPaused}=await import('../../scripts/runtime/acceptance-backup.mjs');for(const stopFails of [false,true]){const calls=[],ctx={state:{binding:{},demoEnabled:true},compose:async(...args)=>{calls.push(args);if(stopFails&&args[0]==='stop')throw Error('partial-stop');}};await assert.rejects(withBackupServicesPaused(ctx,async()=>{throw Error('backup-copy');},{wait:async()=>{}}),/partial-stop|backup-copy/);assert.ok(calls.some(args=>args[0]==='up'&&args.includes('gateway-a')&&args.includes('postgres')&&args.includes('backend-b')));}});

test('verificationReportsAreControlPlaneOnlyAndBackedUpWhenSupported',async()=>{const fs=await import('node:fs/promises');const deployment=JSON.parse(await fs.readFile(new URL('../../deploy/compose.runtime.yml',import.meta.url),'utf8'));assert.ok(deployment.services['control-plane'].volumes.includes('verification-reports:/var/lib/webapi/verification-reports'));assert.ok(!deployment.services.worker.volumes.some(v=>v.startsWith('verification-reports:')));const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.ok(backupVolumeNames({reportsSupported:true}).includes('verification-reports'));assert.ok(!backupVolumeNames({reportsSupported:false}).includes('verification-reports'));});

test('delivery gateway backup pauses both target nodes and restores them after copy failure',async()=>{const{withBackupServicesPaused,backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');const delivery={services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']};assert.ok(backupVolumeNames({delivery}).includes('delivery-secrets'));const calls=[];await assert.rejects(withBackupServicesPaused({delivery,state:{binding:{},demoEnabled:true},compose:async(...a)=>calls.push(a)},async()=>{throw Error('copy failed');},{wait:async()=>{}}),/copy failed/);assert.ok(calls.find(a=>a[0]==='stop').includes('prod-gateway-b'));assert.ok(calls.find(a=>a[0]==='up').includes('prod-gateway-a'));});
test('delivery backup refuses arbitrary additional volumes or services',async()=>{const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.throws(()=>backupVolumeNames({delivery:{services:['foreign-service'],volumes:['foreign-volume']}}),/delivery|scope|Unexpected/i);});
test('cleanup accepts only owned notification fixture volumes and rejects foreign ones',async()=>{const {validateCleanupResources}=await import('../../scripts/runtime/acceptance.mjs');const state={projectName:'webapi-enterprise-local-test-00000000-0000-4000-8000-000000000000',ownerId:'owned'};const volume=n=>({Kind:'volume',Name:state.projectName+'_'+n,Labels:{'com.docker.compose.project':state.projectName,'com.webapi.runtime.owner':state.ownerId}});assert.doesNotThrow(()=>validateCleanupResources(state,['notification-secrets','notification-fixture-secrets','notification-fixture-data'].map(volume)));assert.throws(()=>validateCleanupResources(state,[volume('foreign')]),/Unexpected/);assert.throws(()=>validateCleanupResources(state,[{...volume('notification-secrets'),Labels:{}}]),/owner|project/i);});
test('profile-qualified cleanup stays read-only while run and up retain secret validation',async()=>{const{needsRuntimeSecretValidation}=await import('../../scripts/runtime/context.mjs');assert.equal(needsRuntimeSecretValidation(['--profile','tools','down','--volumes']),false);assert.equal(needsRuntimeSecretValidation(['--profile','tools','run','--rm','worker']),true);assert.equal(needsRuntimeSecretValidation(['--profile','tools','up','-d']),true);assert.equal(needsRuntimeSecretValidation(['stop','prod-gateway-a']),false);});
test('fresh restore initializes native private volumes before delivery volume operations',async()=>{const{initializeRestoreVolumes}=await import('../../scripts/runtime/acceptance-backup.mjs');const calls=[];const ctx={delivery:{services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']},compose:async(...a)=>{calls.push(a);if(a.includes('init-delivery-storage'))assert(calls.some(c=>c.includes('init-volumes')),'native private secrets must exist first');}};await initializeRestoreVolumes(ctx,{delivery:ctx.delivery},null);assert.equal(calls.length,2);});
