import test from'node:test';import assert from'node:assert/strict';import{backupStopServices}from'../../scripts/runtime/acceptance-backup.mjs';
test('backupStopsOnlyDeclaredServicesForUnboundAndNonDemoDeployments',()=>{const unbound=backupStopServices({binding:null,demoEnabled:false});assert.ok(!unbound.includes('gateway-a')&&!unbound.includes('backend-a'));assert.ok(unbound.includes('worker')&&unbound.includes('tempo'));const bound=backupStopServices({binding:{},demoEnabled:false});assert.ok(bound.includes('gateway-a')&&!bound.includes('backend-a'));assert.ok(backupStopServices({binding:{},demoEnabled:true}).includes('backend-a'));});
test('cacheBackupVolumeSelectionRetainsOldDeploymentCompatibility',async()=>{const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.ok(backupVolumeNames({cacheSupported:true}).includes('secrets-cache'));assert.ok(!backupVolumeNames({cacheSupported:false}).includes('secrets-cache'));});
test('backupFailureRestartsAllOriginalServicesEvenAfterPartialStop',async()=>{const{withBackupServicesPaused}=await import('../../scripts/runtime/acceptance-backup.mjs');for(const stopFails of [false,true]){const calls=[],ctx={state:{binding:{},demoEnabled:true},compose:async(...args)=>{calls.push(args);if(stopFails&&args[0]==='stop')throw Error('partial-stop');}};await assert.rejects(withBackupServicesPaused(ctx,async()=>{throw Error('backup-copy');},{wait:async()=>{}}),/partial-stop|backup-copy/);assert.ok(calls.some(args=>args[0]==='up'&&args.includes('gateway-a')&&args.includes('postgres')&&args.includes('backend-b')));}});

test('verificationReportsAreControlPlaneOnlyAndBackedUpWhenSupported',async()=>{const fs=await import('node:fs/promises');const deployment=JSON.parse(await fs.readFile(new URL('../../deploy/compose.runtime.yml',import.meta.url),'utf8'));assert.ok(deployment.services['control-plane'].volumes.includes('verification-reports:/var/lib/webapi/verification-reports'));assert.ok(!deployment.services.worker.volumes.some(v=>v.startsWith('verification-reports:')));const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.ok(backupVolumeNames({reportsSupported:true}).includes('verification-reports'));assert.ok(!backupVolumeNames({reportsSupported:false}).includes('verification-reports'));});

test('delivery gateway backup pauses both target nodes and restores them after copy failure',async()=>{const{withBackupServicesPaused,backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');const delivery={services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']};assert.ok(backupVolumeNames({delivery}).includes('delivery-secrets'));const calls=[];await assert.rejects(withBackupServicesPaused({delivery,state:{binding:{},demoEnabled:true},compose:async(...a)=>calls.push(a)},async()=>{throw Error('copy failed');},{wait:async()=>{}}),/copy failed/);assert.ok(calls.find(a=>a[0]==='stop').includes('prod-gateway-b'));assert.ok(calls.find(a=>a[0]==='up').includes('prod-gateway-a'));});
test('delivery backup refuses arbitrary additional volumes or services',async()=>{const{backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');assert.throws(()=>backupVolumeNames({delivery:{services:['foreign-service'],volumes:['foreign-volume']}}),/delivery|scope|Unexpected/i);});
test('cleanup accepts only owned notification fixture volumes and rejects foreign ones',async()=>{const {validateCleanupResources}=await import('../../scripts/runtime/acceptance.mjs');const state={projectName:'webapi-enterprise-local-test-00000000-0000-4000-8000-000000000000',ownerId:'owned'};const volume=n=>({Kind:'volume',Name:state.projectName+'_'+n,Labels:{'com.docker.compose.project':state.projectName,'com.webapi.runtime.owner':state.ownerId}});assert.doesNotThrow(()=>validateCleanupResources(state,['notification-secrets','notification-fixture-secrets','notification-fixture-data'].map(volume)));assert.throws(()=>validateCleanupResources(state,[volume('foreign')]),/Unexpected/);assert.throws(()=>validateCleanupResources(state,[{...volume('notification-secrets'),Labels:{}}]),/owner|project/i);});
test('profile-qualified cleanup stays read-only while run and up retain secret validation',async()=>{const{needsRuntimeSecretValidation}=await import('../../scripts/runtime/context.mjs');assert.equal(needsRuntimeSecretValidation(['--profile','tools','down','--volumes']),false);assert.equal(needsRuntimeSecretValidation(['--profile','tools','run','--rm','worker']),true);assert.equal(needsRuntimeSecretValidation(['--profile','tools','up','-d']),true);assert.equal(needsRuntimeSecretValidation(['stop','prod-gateway-a']),false);});
test('fresh restore initializes native private volumes before delivery volume operations',async()=>{const{initializeRestoreVolumes}=await import('../../scripts/runtime/acceptance-backup.mjs');const calls=[];const ctx={delivery:{services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']},compose:async(...a)=>{calls.push(a);if(a.includes('init-delivery-storage'))assert(calls.some(c=>c.includes('init-volumes')),'native private secrets must exist first');}};await initializeRestoreVolumes(ctx,{delivery:ctx.delivery},null);assert.equal(calls.length,2);});

test('pipeline backup includes every ordered typed gateway group and protected reports',async()=>{const {backupVolumeNames}=await import('../../scripts/runtime/acceptance-backup.mjs');const pipeline={stageGroups:[{type:'PipelineStageGroup',order:1,environmentId:'env1',kind:'Source',services:['gateway-a','gateway-b'],volumes:['lkg-a','lkg-b']},{type:'PipelineStageGroup',order:2,environmentId:'env2',kind:'Middle',services:['pipeline-stage-2-gateway-a','pipeline-stage-2-gateway-b'],volumes:['pipeline-stage-2-secrets','pipeline-stage-2-lkg-a','pipeline-stage-2-lkg-b']},{type:'PipelineStageGroup',order:3,environmentId:'env3',kind:'Production',services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']}]};const names=backupVolumeNames({pipeline,reportsSupported:true});assert.ok(names.includes('pipeline-stage-2-secrets'));assert.ok(names.includes('verification-reports'));assert.equal(new Set(names).size,names.length);const bad=structuredClone(pipeline);bad.stageGroups[1].volumes[0]='foreign-volume';assert.throws(()=>backupVolumeNames({pipeline:bad,reportsSupported:true}),/pipeline|scope|Unexpected/i);});
test('typed pipeline backup rejects missing report support and foreign owner',async()=>{const {backupVolumeNames,validatePipelineContext}=await import('../../scripts/runtime/acceptance-backup.mjs');const pipeline={ownerId:'one',stageGroups:[{type:'PipelineStageGroup',order:1,environmentId:'source',kind:'Source',services:['gateway-a','gateway-b'],volumes:['lkg-a','lkg-b']},{type:'PipelineStageGroup',order:2,environmentId:'prod',kind:'Production',services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b']}]};assert.throws(()=>backupVolumeNames({pipeline,reportsSupported:false}),/report/);assert.throws(()=>validatePipelineContext({state:{ownerId:'other'},pipeline}),/owner/);});
test('pipeline restore allows fresh host ports while retaining exact stage and environment topology',async()=>{const {initializeRestoreVolumes}=await import('../../scripts/runtime/acceptance-backup.mjs');const groups=[{type:'PipelineStageGroup',order:1,environmentId:'source',kind:'Source',services:['gateway-a','gateway-b'],volumes:['lkg-a','lkg-b'],ports:{gatewayA:9000,gatewayB:9001}},{type:'PipelineStageGroup',order:2,environmentId:'prod',kind:'Production',services:['prod-gateway-a','prod-gateway-b'],volumes:['delivery-secrets','delivery-lkg-a','delivery-lkg-b'],ports:{gatewayA:9002,gatewayB:9003}}],ctx={state:{ownerId:'clone'},pipeline:{ownerId:'clone',stageGroups:groups.map(g=>({...g,ports:{gatewayA:g.ports.gatewayA+10,gatewayB:g.ports.gatewayB+10}}))},compose:async()=>{}};await initializeRestoreVolumes(ctx,{pipeline:{ownerId:'source-owner',stageGroups:groups}},null);const wrong={...ctx,pipeline:structuredClone(ctx.pipeline)};wrong.pipeline.stageGroups[1].environmentId='other';await assert.rejects(initializeRestoreVolumes(wrong,{pipeline:{ownerId:'source-owner',stageGroups:groups}},null),/context mismatch/);});
