import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import{randomUUID}from'node:crypto';import{initializeState,saveState,loadState}from'../../scripts/runtime/state.mjs';import{configureRuntime}from'../../scripts/runtime/configure.mjs';
async function fixture(t){const parent=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-bind-'));t.after(()=>fs.rm(parent,{recursive:true,force:true}));const directory=path.join(parent,'local');let state=await initializeState(directory,{bootstrapUsername:'test-admin'});state={...state,initialized:true,releaseId:'a'.repeat(40)};await saveState(directory,state);const calls=[],environmentId=randomUUID();return{directory,state,options:{environmentId,allowedOrigins:['http://backend-a:8080','http://backend-b:8080'],username:'test-admin',demoEnabled:true},calls,deps:{directory,authenticate:async()=>({request:async()=>({id:environmentId,status:'Active'})}),loadRelease:async()=>({}),prepareContext:async()=>({compose:async(...args)=>calls.push(args)}),wait:async()=>{},getStatus:async()=>({phase:'Registered',nodes:[{name:'local-gateway-a',instanceId:'a',enabled:true,fresh:true,lastHeartbeatAt:new Date().toISOString()},{name:'local-gateway-b',instanceId:'b',enabled:true,fresh:true,lastHeartbeatAt:new Date().toISOString()}],environmentStatus:'Active'})}};}
test('inactiveOrUnauthorizedEnvironmentLeavesBindingUnchanged',async t=>{for(const denied of [false,true]){const f=await fixture(t);f.deps.authenticate=async()=>({request:async()=>{if(denied)throw Error('403');return{status:'Disabled'};}});await assert.rejects(configureRuntime(f.state,f.options,f.deps));assert.equal((await loadState(f.directory)).binding,null);assert.equal(f.calls.length,0);}});
test('differentEnvironmentRejectedBeforeRecreate',async t=>{const f=await fixture(t);await configureRuntime(f.state,f.options,f.deps);f.calls.length=0;await assert.rejects(configureRuntime(await loadState(f.directory),{...f.options,environmentId:randomUUID()},f.deps),/another environment/i);assert.equal(f.calls.length,0);});
test('sameBindingDoesNotRotateSecrets',async t=>{const f=await fixture(t);await fs.mkdir(path.join(f.directory,'secrets'),{mode:0o700});await fs.writeFile(path.join(f.directory,'secrets/node-a'),'existing-secret',{mode:0o600});await configureRuntime(f.state,f.options,f.deps);await configureRuntime(await loadState(f.directory),f.options,f.deps);assert.equal(await fs.readFile(path.join(f.directory,'secrets/node-a'),'utf8'),'existing-secret');assert.equal((await loadState(f.directory)).bindingPhase,'Applied');});
test('environmentDisabledAfterValidationNeverReportsReady',async t=>{const f=await fixture(t);f.deps.getStatus=async()=>({phase:'Degraded',environmentStatus:'Disabled',nodes:[]});await assert.rejects(configureRuntime(f.state,f.options,f.deps),/environment|register/i);assert.equal((await loadState(f.directory)).bindingPhase,'Validated');});
test('recreateFailurePreservesRetryableBinding',async t=>{const f=await fixture(t);f.deps.prepareContext=async()=>({compose:async()=>{throw Error('recreate failed');}});await assert.rejects(configureRuntime(f.state,f.options,f.deps),/recreate/);const saved=await loadState(f.directory);assert.equal(saved.binding,null);assert.equal(saved.pendingConfiguration.binding.environmentId,f.options.environmentId);assert.equal(saved.bindingPhase,'Validated');});
test('disabledExistingNodeDoesNotCountAsRegistration',async t=>{const f=await fixture(t);f.deps.getStatus=async()=>({phase:'Degraded',environmentStatus:'Active',nodes:[{name:'local-gateway-a',instanceId:'old-a',enabled:false},{name:'local-gateway-b',instanceId:'old-b',enabled:false}]});await assert.rejects(configureRuntime(f.state,f.options,f.deps),/disabled|register/i);assert.equal((await loadState(f.directory)).bindingPhase,'Validated');});
test('failedReconfigurePreservesAppliedBindingAndStoresPendingProposal',async t=>{const f=await fixture(t);const applied=await configureRuntime(f.state,f.options,f.deps);f.deps.prepareContext=async()=>{throw Error('recreate failed');};const proposal={...f.options,allowedOrigins:['https://new-upstream.example'],demoEnabled:false};await assert.rejects(configureRuntime(applied,proposal,f.deps),/recreate/);const saved=await loadState(f.directory);assert.deepEqual(saved.binding,applied.binding);assert.equal(saved.demoEnabled,true);assert.deepEqual(saved.pendingConfiguration.binding.allowedOrigins,proposal.allowedOrigins);assert.equal(saved.pendingConfiguration.demoEnabled,false);assert.equal(saved.bindingPhase,'Validated');});
