import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import net from'node:net';import{randomUUID,createHash}from'node:crypto';
import{initializeRuntime,operateRuntime,completeBootstrap,assertPorts}from'../../scripts/runtime/lifecycle.mjs';import{loadState}from'../../scripts/runtime/state.mjs';
async function fixture(t){const parent=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-life-'));t.after(()=>fs.rm(parent,{recursive:true,force:true}));const calls=[],release={schemaVersion:1,sourceRevision:'a'.repeat(40),imageId:'sha256:'+'b'.repeat(64),configVersion:1};return{options:{directory:path.join(parent,'local'),projectName:'webapi-enterprise-local-test-'+randomUUID(),bootstrapUsername:'test-admin'},calls,deps:{assertPorts:async()=>{},loadRelease:async()=>release,prepareContext:async()=>({compose:async(...args)=>{calls.push(args);return{stdout:'',exitCode:0};}}),wait:async()=>{},removeBootstrapVolume:async()=>{}}};}
async function fingerprints(directory){const result={};for(const file of await fs.readdir(path.join(directory,'secrets')))result[file]=createHash('sha256').update(await fs.readFile(path.join(directory,'secrets',file))).digest('hex');return result;}
test('repeatedInitDoesNotRotateSecretsOrCreateAnotherAdmin',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);const first=await fingerprints(f.options.directory);await initializeRuntime(f.options,f.deps);assert.deepEqual(await fingerprints(f.options.directory),first);assert.equal(f.calls.filter(a=>a.includes('--bootstrap')).length,1);await assert.rejects(initializeRuntime({...f.options,bootstrapUsername:'another-admin'},f.deps),/administrator/i);});
test('deletedBootstrapFileDoesNotRebootstrap',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);await fs.unlink(path.join(f.options.directory,'secrets/bootstrap-password'));await initializeRuntime(f.options,f.deps);assert.equal(f.calls.filter(a=>a.includes('--bootstrap')).length,1);assert.equal((await loadState(f.options.directory)).initialized,true);});
test('foreignPortFailsBeforeMutation',async t=>{const f=await fixture(t),server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));f.options.ports={console:server.address().port,gatewayA:4196,gatewayB:4197};f.deps.assertPorts=state=>assertPorts(state,{inspect:async()=>[]});await assert.rejects(initializeRuntime(f.options,f.deps),/port/i);assert.equal(f.calls.length,0);});
test('ownPortsAllowRepeatedUp',async t=>{const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const state={projectName:'webapi-enterprise-local',ownerId:randomUUID(),ports:{console:server.address().port,gatewayA:4196,gatewayB:4197}};const resource={Config:{Labels:{'com.docker.compose.project':state.projectName,'com.webapi.runtime.owner':state.ownerId}},NetworkSettings:{Ports:{'8080/tcp':[{HostIp:'127.0.0.1',HostPort:String(state.ports.console)}]}}};await assertPorts(state,{inspect:async()=>[resource]});});
test('stopNeverDeletesVolumes',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);f.calls.length=0;const before=await fingerprints(f.options.directory);await operateRuntime('stop',await loadState(f.options.directory),{...f.deps,directory:f.options.directory});assert.deepEqual(f.calls,[['stop']]);assert.deepEqual(await fingerprints(f.options.directory),before);});
test('failedMigrationDoesNotStartApplication',async t=>{const f=await fixture(t);f.deps.prepareContext=async()=>({compose:async(...args)=>{f.calls.push(args);if(args.includes('migrator'))throw Error('migration failed');return{stdout:'',exitCode:0};}});await assert.rejects(initializeRuntime(f.options,f.deps),/migration/);assert.ok(!f.calls.some(a=>a.includes('control-plane')));assert.equal((await loadState(f.options.directory)).initialized,false);});
test('completeBootstrapDeletesOnlyOwnedPasswordFile',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);await assert.rejects(completeBootstrap(await loadState(f.options.directory),{directory:f.options.directory,credentialsSaved:false}),/saved/i);await completeBootstrap(await loadState(f.options.directory),{directory:f.options.directory,credentialsSaved:true});const names=await fs.readdir(path.join(f.options.directory,'secrets'));assert.ok(!names.includes('bootstrap-password'));assert.ok(names.includes('postgres-password'));});
test('invalidPasswordFileDoesNotLeaveIncompleteSecretSet',async t=>{const f=await fixture(t);const passwordFile=path.join(path.dirname(f.options.directory),'input-password');await fs.writeFile(passwordFile,'short',{mode:0o600});await assert.rejects(initializeRuntime({...f.options,passwordFile},f.deps),/password/i);await assert.rejects(fs.access(path.join(f.options.directory,'secrets')));await fs.writeFile(passwordFile,'valid-password-123456789',{mode:0o600});await initializeRuntime({...f.options,passwordFile},f.deps);assert.equal((await loadState(f.options.directory)).initialized,true);});
