import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import net from'node:net';import{randomUUID,createHash}from'node:crypto';
import{initializeRuntime,operateRuntime,completeBootstrap,assertPorts}from'../../scripts/runtime/lifecycle.mjs';import{loadState}from'../../scripts/runtime/state.mjs';
async function fixture(t){const parent=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-life-'));t.after(()=>fs.rm(parent,{recursive:true,force:true}));const calls=[],release={schemaVersion:1,sourceRevision:'a'.repeat(40),imageId:'sha256:'+'b'.repeat(64),configVersion:1};return{options:{directory:path.join(parent,'local'),projectName:'webapi-enterprise-local-test-'+randomUUID(),bootstrapUsername:'test-admin'},calls,deps:{assertPorts:async()=>{},loadRelease:async()=>release,prepareContext:async()=>({compose:async(...args)=>{calls.push(args);return{stdout:'',exitCode:0};}}),wait:async()=>{},removeBootstrapVolume:async()=>{}}};}
async function fingerprints(directory){const result={};for(const file of await fs.readdir(path.join(directory,'secrets')))result[file]=createHash('sha256').update(await fs.readFile(path.join(directory,'secrets',file))).digest('hex');return result;}
test('repeatedInitDoesNotRotateSecretsOrCreateAnotherAdmin',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);const first=await fingerprints(f.options.directory);await initializeRuntime(f.options,f.deps);assert.deepEqual(await fingerprints(f.options.directory),first);assert.equal(f.calls.filter(a=>a.includes('--bootstrap')).length,1);await assert.rejects(initializeRuntime({...f.options,bootstrapUsername:'another-admin'},f.deps),/administrator/i);});
test('deletedBootstrapFileDoesNotRebootstrap',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);await fs.unlink(path.join(f.options.directory,'secrets/bootstrap-password'));await initializeRuntime(f.options,f.deps);assert.equal(f.calls.filter(a=>a.includes('--bootstrap')).length,1);assert.equal((await loadState(f.options.directory)).initialized,true);});
test('foreignPortFailsBeforeMutation',async t=>{const f=await fixture(t),server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));f.options.ports={console:server.address().port,gatewayA:4196,gatewayB:4197};f.deps.assertPorts=state=>assertPorts(state,{inspect:async()=>[]});await assert.rejects(initializeRuntime(f.options,f.deps),/port/i);assert.equal(f.calls.length,0);});
test('ownPortsAllowRepeatedUp',async t=>{
 const servers=[];
 t.after(()=>Promise.all(servers.map(server=>new Promise(resolve=>server.close(resolve)))));
 for(let i=0;i<3;i++){const server=net.createServer();servers.push(server);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));}
 const state={projectName:'webapi-enterprise-local-test-owned',ownerId:randomUUID(),ports:{console:servers[0].address().port,gatewayA:servers[1].address().port,gatewayB:servers[2].address().port}};
 const resources=Object.values(state.ports).map(port=>({Config:{Labels:{'com.docker.compose.project':state.projectName,'com.webapi.runtime.owner':state.ownerId}},NetworkSettings:{Ports:{'8080/tcp':[{HostIp:'127.0.0.1',HostPort:String(port)}]}}}));
 await assertPorts(state,{inspect:async()=>resources});
});
test('stopNeverDeletesVolumes',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);f.calls.length=0;const before=await fingerprints(f.options.directory);await operateRuntime('stop',await loadState(f.options.directory),{...f.deps,directory:f.options.directory});assert.deepEqual(f.calls,[['stop']]);assert.deepEqual(await fingerprints(f.options.directory),before);});
test('failedMigrationDoesNotStartApplication',async t=>{const f=await fixture(t);f.deps.prepareContext=async()=>({compose:async(...args)=>{f.calls.push(args);if(args.includes('migrator'))throw Error('migration failed');return{stdout:'',exitCode:0};}});await assert.rejects(initializeRuntime(f.options,f.deps),/migration/);assert.ok(!f.calls.some(a=>a.includes('control-plane')));assert.equal((await loadState(f.options.directory)).initialized,false);});
test('completeBootstrapDeletesOnlyOwnedPasswordFile',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);await assert.rejects(completeBootstrap(await loadState(f.options.directory),{directory:f.options.directory,credentialsSaved:false}),/saved/i);await completeBootstrap(await loadState(f.options.directory),{directory:f.options.directory,credentialsSaved:true});const names=await fs.readdir(path.join(f.options.directory,'secrets'));assert.ok(!names.includes('bootstrap-password'));assert.ok(names.includes('postgres-password'));});
test('invalidPasswordFileDoesNotLeaveIncompleteSecretSet',async t=>{const f=await fixture(t);const passwordFile=path.join(path.dirname(f.options.directory),'input-password');await fs.writeFile(passwordFile,'short',{mode:0o600});await assert.rejects(initializeRuntime({...f.options,passwordFile},f.deps),/password/i);await assert.rejects(fs.access(path.join(f.options.directory,'secrets')));await fs.writeFile(passwordFile,'valid-password-123456789',{mode:0o600});await initializeRuntime({...f.options,passwordFile},f.deps);assert.equal((await loadState(f.options.directory)).initialized,true);});
test('missingWholeInitializedSecretDirectoryNeverRegenerates',async t=>{const f=await fixture(t);await initializeRuntime(f.options,f.deps);await fs.rm(path.join(f.options.directory,'secrets'),{recursive:true});f.calls.length=0;await assert.rejects(initializeRuntime(f.options,f.deps),/secret|restore/i);await assert.rejects(fs.access(path.join(f.options.directory,'secrets')));assert.equal(f.calls.length,0);});
test('portConflictCanBeRetriedWithExplicitPortsBeforeResourcesExist',async t=>{const f=await fixture(t);const checked=[];f.deps.inspectResources=async()=>[];f.deps.assertPorts=async s=>{checked.push(s.ports.console);if(s.ports.console===4192)throw Error('occupied');};await assert.rejects(initializeRuntime(f.options,f.deps),/occupied/);const newPorts={console:14190,gatewayA:14196,gatewayB:14197};await initializeRuntime({...f.options,ports:newPorts},f.deps);assert.deepEqual(checked,[4192,14190]);assert.deepEqual((await loadState(f.options.directory)).ports,newPorts);await assert.rejects(initializeRuntime({...f.options,ports:{...newPorts,console:14191}},f.deps),/port.*change|change.*port/i);});
test('startReportsObservedFailureRatherThanConfiguredRegistration',async t=>{const f=await fixture(t);let state=await initializeRuntime(f.options,f.deps);const {saveState}=await import('../../scripts/runtime/state.mjs');state={...state,binding:{environmentId:randomUUID(),nodeNames:['local-gateway-a','local-gateway-b'],allowedOrigins:[]},bindingPhase:'Applied'};await saveState(f.options.directory,state);const observed={phase:'Degraded',services:[{name:'gateway-a',state:'Restarting'}],nodes:[]};const result=await operateRuntime('start',state,{...f.deps,directory:f.options.directory,getStatus:async()=>observed});assert.deepEqual(result,observed);});
test('cache volume preparation on start removes the transient bootstrap volume',async t=>{const f=await fixture(t);let removed=0;f.deps.removeBootstrapVolume=async()=>{removed++;};f.deps.prepareContext=async()=>({cacheSupported:true,compose:async(...args)=>{f.calls.push(args);return{stdout:'',exitCode:0};}});const state=await initializeRuntime(f.options,f.deps);assert.equal(removed,1);await operateRuntime('start',state,{...f.deps,directory:f.options.directory,getStatus:async()=>({phase:'Unconfigured'})});assert.equal(removed,2);assert.equal(f.calls.filter(a=>a.includes('--bootstrap')).length,1);});
test('supportedSecuritySynchronizesProxyAfterConsoleStartBeforeReadiness',async t=>{const f=await fixture(t);f.deps.prepareContext=async()=>({securitySupported:true,compose:async(...args)=>{f.calls.push(args);return{stdout:'',exitCode:0};}});f.deps.synchronizeProxy=async()=>f.calls.push(['security-proxy-sync']);f.deps.wait=async()=>f.calls.push(['readiness']);const state=await initializeRuntime(f.options,f.deps);let sync=f.calls.findIndex(a=>a[0]==='security-proxy-sync');assert.ok(sync>f.calls.findIndex(a=>a[0]==='up'&&a.includes('console')));assert.ok(sync<f.calls.findIndex(a=>a[0]==='readiness'));f.calls.length=0;await operateRuntime('restart',state,{...f.deps,directory:f.options.directory,getStatus:async()=>({phase:'Unconfigured'})});sync=f.calls.findIndex(a=>a[0]==='security-proxy-sync');assert.ok(sync>f.calls.findIndex(a=>a[0]==='restart'&&a.includes('console')));assert.ok(sync<f.calls.findIndex(a=>a[0]==='readiness'));});
