import {fileURLToPath} from 'node:url';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {validateOwnedResources,createPrivateWorkspace} from '../../scripts/settings/evidence.mjs';
const wrapper=fs.readFileSync(new URL('../../scripts/check-settings.sh',import.meta.url));
test('delegate preserves locked restore arguments and backend failure without touching local runtime',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'settings-wrapper-'));try{fs.mkdirSync(path.join(dir,'scripts'));fs.writeFileSync(path.join(dir,'scripts/check-settings.sh'),wrapper);fs.writeFileSync(path.join(dir,'scripts/check-policies.sh'),'#!/bin/bash\nprintf "%s\\n" "$@"\nexit 7\n');const r=spawnSync('bash',[path.join(dir,'scripts/check-settings.sh'),'domain','--filter','boundary'],{encoding:'utf8'});assert.equal(r.status,7);assert.deepEqual(r.stdout.trim().split('\n'),['domain','-p:RestoreLockedMode=true','--filter','boundary']);assert.equal(fs.existsSync(path.join(dir,'.runtime')),false);}finally{fs.rmSync(dir,{recursive:true});}});
test('unsupported mode fails instead of reporting acceptance',()=>{const r=spawnSync('bash',[fileURLToPath(new URL('../../scripts/check-settings.sh',import.meta.url)),'unknown'],{encoding:'utf8'});assert.notEqual(r.status,0);});
test('SettingsRunnerOwnsOnlyItsResources',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'settings-owned-'));try{const a=await createPrivateWorkspace(root),b=await createPrivateWorkspace(root);assert.notEqual(a.owner,b.owner);assert.notEqual(a.project,b.project);assert.equal(fs.statSync(a.directory).mode&0o777,0o700);assert.equal(fs.statSync(path.join(a.directory,'password')).mode&0o777,0o600);const own={'com.docker.compose.project':a.project,'com.webapi.settings.owner':a.owner};assert.doesNotThrow(()=>validateOwnedResources(a,[own]));assert.throws(()=>validateOwnedResources(a,[{...own,'com.webapi.settings.owner':b.owner}]));assert.throws(()=>validateOwnedResources({...a,project:'webapi-local'},[own]));assert.throws(()=>validateOwnedResources(a,[{...own,'com.docker.compose.project':'webapi-local'}]));}finally{fs.rmSync(root,{recursive:true});}});
import {createHash} from 'node:crypto';const digest=b=>createHash('sha256').update(b).digest('hex'),packageScript=fileURLToPath(new URL('../../scripts/package-settings.py',import.meta.url));
function packageFixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'settings-package-'));for(const d of ['src','scripts','docs/evidence/settings/ui','.runtime/local','console/node_modules'])fs.mkdirSync(path.join(root,d),{recursive:true});fs.writeFileSync(path.join(root,'src/example.cs'),'valid actual source');const evidence=path.join(root,'docs/evidence/settings'),source={schemaVersion:1,baseCommit:'0'.repeat(40),classification:'actual-uncommitted-build-source',files:{'src/example.cs':digest('valid actual source')}};const write=(name,value)=>fs.writeFileSync(path.join(evidence,name),JSON.stringify(value,null,2)+'\n');write('source-manifest.json',source);const sourceManifestHash=digest(fs.readFileSync(path.join(evidence,'source-manifest.json'))),tool={schemaVersion:1,files:{},sha256:digest('{}')};write('tool-manifest.json',tool);write('verification.json',{complete:true,sourceManifestHash,toolManifestHash:tool.sha256,checks:['settings-persistence','snapshot-unchanged-before-publish','both-gateways-ack','old-route-still-works','audit-export-disabled'].map(name=>({name,pass:true,evidence:{verified:true}})),finalRelease:{targets:[{acknowledged:true},{acknowledged:true}]}});const pixels=fs.readFileSync(new URL('../../docs/evidence/settings/ui/01-security.png',import.meta.url));const screenshots=Array.from({length:10},(_,i)=>{const file='ui/'+i+'.png';fs.writeFileSync(path.join(evidence,file),pixels);return{file,sha256:digest(pixels),width:1440,height:1100};});write('ui/qa.json',{complete:true,sourceManifestHash,visualReviewComplete:true,toolManifestHash:tool.sha256,checks:[{name:'actual flow',pass:true}],screenshots});write('regression.json',{complete:true,sourceManifestHash,toolManifestHash:tool.sha256,suites:{domain:{pass:true,total:1},integration:{pass:true,total:1},gateway:{pass:true,total:1},console:{pass:true,total:1},runner:{pass:true,total:1}}});fs.writeFileSync(path.join(root,'.runtime/local/password'),'PRIVATE-DO-NOT-PACK');fs.writeFileSync(path.join(root,'console/node_modules/private'),'PRIVATE-DO-NOT-PACK');return {root,evidence,write};}
function pack(f){return spawnSync('python3',[packageScript,'--root',f.root,'--evidence',f.evidence],{encoding:'utf8'});}
test('VerifyFailsOnStaleSourceOrFailedCheck',()=>{const f=packageFixture();try{fs.writeFileSync(path.join(f.root,'src/example.cs'),'stale change');assert.notEqual(pack(f).status,0);fs.writeFileSync(path.join(f.root,'src/example.cs'),'valid actual source');const v=JSON.parse(fs.readFileSync(path.join(f.evidence,'verification.json')));v.checks[0].pass=false;f.write('verification.json',v);assert.notEqual(pack(f).status,0);v.checks[0].pass=true;f.write('verification.json',v);fs.rmSync(path.join(f.evidence,'ui/qa.json'));assert.notEqual(pack(f).status,0);}finally{fs.rmSync(f.root,{recursive:true});}});
test('PackageExcludesSecretsAndOldRuntimeData',()=>{const f=packageFixture();try{const r=pack(f);assert.equal(r.status,0,r.stderr);const manifest=JSON.parse(fs.readFileSync(path.join(f.root,'deliverables/WebAPI_Enterprise_系统设置源码及验收_20261005.manifest.json')));assert(manifest.files['src/example.cs']);assert(Object.keys(manifest.files).every(n=>!n.includes('.runtime')&&!n.includes('node_modules')));const check=spawnSync('python3',['-c','import sys,zipfile;z=zipfile.ZipFile(sys.argv[1]);assert z.testzip() is None;assert all(b"PRIVATE-DO-NOT-PACK" not in z.read(n) for n in z.namelist())',path.join(f.root,'deliverables',manifest.package)],{encoding:'utf8'});assert.equal(check.status,0,check.stderr);}finally{fs.rmSync(f.root,{recursive:true});}});
test('PackageGatesRemainActiveUnderOptimizedPython',()=>{const f=packageFixture();try{fs.writeFileSync(path.join(f.root,'src/example.cs'),'unaccepted source');const r=spawnSync('python3',[packageScript,'--root',f.root,'--evidence',f.evidence],{encoding:'utf8',env:{...process.env,PYTHONOPTIMIZE:'1'}});assert.notEqual(r.status,0);}finally{fs.rmSync(f.root,{recursive:true});}});
test('OldBrowserEvidenceCannotPassNewToolIdentity',()=>{const f=packageFixture();try{const q=JSON.parse(fs.readFileSync(path.join(f.evidence,'ui/qa.json')));q.toolManifestHash='previous-browser-tool';f.write('ui/qa.json',q);assert.notEqual(pack(f).status,0);}finally{fs.rmSync(f.root,{recursive:true});}});
