import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ApiError} from '../api/client';
import {useSession} from '../auth/SessionProvider';
import {tabFocusTarget,recoveryFocusTarget} from '../editor-focus.mjs';
import {useUnsaved} from '../ui';
import {approvalApi,type ApprovalItem} from './api';
import {approvalMayAct,approvalOperationMatches} from './inbox-state.mjs';

export function ApprovalActionDialog({item,action,comment,operationKey,error,conflict,onComment,onError,onLostRead,onResult,onClose}:{item:ApprovalItem;action:string;comment:string;operationKey:string;error:string;conflict:boolean;onComment:(comment:string,key:string)=>void;onError:(status:number,message:string)=>void;onLostRead:()=>void;onResult:()=>void;onClose:()=>void}){
 const opened=useRef({stepOrder:item.approvalEligibility.currentStepOrder,candidateHash:null as string|null}),[stale,setStale]=useState(false);
 const session=useSession(),[detail,setDetail]=useState<any>(),[busy,setBusy]=useState(false),[discard,setDiscard]=useState(false),[loading,setLoading]=useState(true),root=useRef<HTMLFormElement>(null),controller=useRef(new AbortController());
 useUnsaved(!!comment,()=>onError(0,'仍有未提交批注，请先提交或关闭审批弹窗。'));
 useEffect(()=>{const previous=document.activeElement as HTMLElement;root.current?.querySelector<HTMLTextAreaElement>('textarea')?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{const form=root.current;if(!form)return;const trap=form.querySelector<HTMLElement>('[role=alertdialog]')||form,items=[...trap.querySelectorAll<HTMLElement>('textarea:not(:disabled),button:not(:disabled)')].filter(item=>item.getClientRects().length>0);const next=discard?items[0]:recoveryFocusTarget(items,document.activeElement,form);next?.focus();},[discard,busy,conflict,loading,session.error]);
 useEffect(()=>{const abort=controller.current;const read=async()=>{if(document.hidden)return;try{const result=await approvalApi.read(item.id,abort.signal);if(!abort.signal.aborted){if(opened.current.candidateHash===null&&result.approvalEligibility?.currentStepOrder===opened.current.stepOrder)opened.current.candidateHash=result.candidateHash;if(!approvalOperationMatches(opened.current,result))setStale(true);setDetail(result);setLoading(false);}}catch(e){if(abort.signal.aborted)return;if(e instanceof ApiError&&[401,403,404].includes(e.status)){setDetail(undefined);onLostRead();}else onError(e instanceof ApiError?e.status:0,(e as Error).message);setLoading(false);}};void read();const timer=setInterval(()=>void read(),5000);document.addEventListener('visibilitychange',read);return()=>{abort.abort();clearInterval(timer);document.removeEventListener('visibilitychange',read);};},[item.id]);
 async function submit(e:FormEvent){e.preventDefault();if(busy||loading||conflict||stale||!approvalOperationMatches(opened.current,detail)||!operationKey||session.error||action==='reject'&&!comment.trim())return;setBusy(true);try{await approvalApi.act(item.id,action,comment,operationKey,controller.current.signal,{stepOrder:opened.current.stepOrder!,candidateHash:opened.current.candidateHash!});if(!controller.current.signal.aborted)onResult();}catch(e){if(controller.current.signal.aborted)return;const status=e instanceof ApiError?e.status:0;onError(status,(e as Error).message);if([403,404].includes(status)){try{setDetail(await approvalApi.read(item.id,controller.current.signal));}catch(read){if(read instanceof ApiError&&[401,403,404].includes(read.status))onLostRead();}}}finally{if(!controller.current.signal.aborted)setBusy(false);}}
 return <div className="overlay"><form ref={root} className="dialog approval-dialog" role="dialog" tabIndex={-1} aria-modal="true" aria-label={action==='approve'?'批准当前步骤':'拒绝审批申请'} onSubmit={submit} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();if(!busy){if(discard)setDiscard(false);else if(comment)setDiscard(true);else onClose();}}if(e.key==='Tab'){const trap=root.current?.querySelector<HTMLElement>('[role=alertdialog]')||root.current;if(!trap)return;const items=[...trap.querySelectorAll<HTMLElement>('textarea:not(:disabled),button:not(:disabled),a[href]')].filter(e=>e.getClientRects().length>0);const next=tabFocusTarget(items,document.activeElement,e.shiftKey,trap);if(next){e.preventDefault();next.focus();}}}}><header><h2>{action==='approve'?'批准当前步骤':'拒绝审批申请'}</h2><button type="button" className="text-btn" disabled={busy} onClick={()=>comment?setDiscard(true):onClose()}>关闭</button></header><div className="approval-summary"><strong>{item.releaseNo}</strong><span>{item.organization.name} / {item.project.name} / {item.environment.name}</span><span>申请人 {item.applicantDisplayName} · 当前步骤 {detail?.approvalEligibility?.currentStepOrder??item.approvalEligibility.currentStepOrder??'—'}</span><span>冻结候选 {detail?.candidateHash?.slice(0,16)||'读取中…'}</span><span>{item.risk.visibility==='Restricted'?'风险资料受限':item.risk.counts?`破坏性 ${item.risk.counts.breaking} · 未知 ${item.risk.counts.unknown}`:'未关联风险评审'}</span></div><label>审批意见{action==='reject'?' *':''}<textarea rows={5} maxLength={10000} value={comment} required={action==='reject'} disabled={busy||discard} onChange={e=>onComment(e.target.value,crypto.randomUUID())}/><small>{comment.length} / 10000</small></label>{loading&&<p role="status">正在重新核对服务端资格…</p>}{detail&&(stale||!approvalOperationMatches(opened.current,detail))&&<div className="notice">当前步骤已变化或你已不具备办理资格。批注已保留，可关闭后刷新列表。</div>}{error&&<div className="error" role="alert">{error}</div>}{conflict&&<div className="notice">申请已变化，批注已保留。请关闭并重新核对当前步骤，再发起新的操作。</div>}{discard&&<div className="notice" role="alertdialog" aria-label="放弃未提交批注"><p>关闭将放弃未提交批注。</p><button type="button" className="btn" onClick={()=>setDiscard(false)}>继续编辑</button><button type="button" className="btn danger" onClick={onClose}>确认放弃</button></div>}<footer><button className={'btn '+(action==='approve'?'primary':'danger')} disabled={busy||loading||discard||conflict||stale||!approvalOperationMatches(opened.current,detail)||!!session.error}>{busy?'提交中…':action==='approve'?'确认批准':'确认拒绝'}</button><span>按冻结规则占用当前步骤的一个席位</span></footer></form></div>;
}
