import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {loadState,writePrivate} from '../runtime/state.mjs';import {loadRelease,waitForRuntime} from '../runtime/lifecycle.mjs';import {prepareContext} from '../runtime/context.mjs';import {inspectResources,assertOwnership,docker} from '../runtime/docker.mjs';import {validateCloneOwnership,assertReleaseIdentity} from '../contracts/evidence.mjs';import {ContractClient} from '../contracts/scenario.mjs';import {fixtureRequest} from './fixture.mjs';import {loadNotificationRuntime,loadNotificationSecrets} from './runtime-secrets.mjs';import {until,pause} from '../runtime/acceptance-scenario.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
// Scenario inputs simulate an owned metric evaluation; production planner, API, workers,
// database fencing and wire receivers perform all resulting behavior. Never uses original4192.
export async function runNotificationScenario({revision,imageId,cloneDirectory,fixtureDirectory}){
 const state=await loadState(cloneDirectory),release=await loadRelease(path.join(cloneDirectory,'release.json')),resources=await inspectResources(state);validateCloneOwnership(state,resources,cloneDirectory);assert.equal(release.imageId,imageId);assertReleaseIdentity({revision,release,actualImages:await Promise.all(resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b','notification-fixture'].includes(r.Config?.Labels?.['com.docker.compose.service'])).map(async app=>{const image=JSON.parse((await docker(['image','inspect',app.Image])).stdout)[0];return {imageId:image.Id,sourceRevision:image.Config.Labels['org.opencontainers.image.revision']};}))});
 assert.equal(path.resolve(fixtureDirectory),path.join(path.resolve(cloneDirectory),'notification-evidence'));await fs.mkdir(fixtureDirectory,{mode:0o700,recursive:true});
 assert(resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b','notification-fixture'].includes(r.Config?.Labels?.['com.docker.compose.service'])).every(r=>r.State.Running));
 const n=await loadNotificationRuntime(cloneDirectory,state);assert(n?.fixtureEnabled);const secretDirectory=path.join(cloneDirectory,'notification-secrets');await loadNotificationSecrets(secretDirectory,state.ownerId,state.projectName);let ctx=await prepareContext(cloneDirectory,state,release);const endpoint='http://127.0.0.1:'+state.ports.console,admin=new ContractClient(endpoint),password=(await fs.readFile(path.join(cloneDirectory,'secrets/bootstrap-password'),'utf8')).trimEnd();await admin.login(state.bootstrapUsername,password);
 const tag=randomUUID().slice(0,8),organizationCode='NOTIFY_'+state.ownerId.replaceAll('-','').toUpperCase();let organization=(await admin.request('/organizations')).items?.find(o=>o.code===organizationCode);organization??=await admin.request('/organizations',{method:'POST',body:{code:organizationCode,name:'独立通知协议验收组织'}});const project=await admin.request('/organizations/'+organization.id+'/projects',{method:'POST',body:{code:'NOTIFY_'+tag.toUpperCase(),name:'独立通知验收 '+tag}}),environment=await admin.request('/projects/'+project.id+'/environments',{method:'POST',body:{code:'FIXTURE',name:'独立 SMTP HTTPS',isProduction:false}}),scope={organizationId:organization.id,projectId:project.id,environmentId:environment.id};
 const role=await admin.request('/roles',{method:'POST',body:{code:'Notify_'+tag,organizationId:organization.id,name:'通知验收角色'}});await admin.request('/roles/'+role.id+'/permissions',{method:'PUT',headers:{'If-Match':'"'+role.revision+'"'},body:{permissions:['alert.read','alert.operate','alert.rule.manage','organization.read','project.read','environment.read']}});
 const platformRole=(await admin.request('/roles')).find(r=>r.isSystem&&r.code==='PlatformAdmin');const actors={};
 async function actor(suffix,accessMode='read_write',platform=false){const username='notify-'+tag+'-'+suffix,secret=randomBytes(24).toString('base64');let user=await admin.request('/users',{method:'POST',body:{username,displayName:'通知验收 '+suffix,password:secret}});user=await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{roleIds:[platform?platformRole.id:role.id]}});await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{scopes:[{scope:{organizationId:organization.id},accessMode}]}});const client=new ContractClient(endpoint);await client.login(username,secret);return actors[suffix]={id:user.id,username,password:secret,client};}
 const writer=await actor('operator'),reader=await actor('reader','read'),revoked=await actor('revoked'),tester=await actor('tester','read_write',true),checks=[];const identity={sourceRevision:revision,imageId};
 const note=async(id,actual,expected)=>{assert.deepEqual(actual,expected);const observation=id+'.json';await writePrivate(path.join(fixtureDirectory,observation),{...identity,id,source:'actual-clone',serviceResponse:true,actual,expected});checks.push({id,passed:true,...identity,observation});await writePrivate(path.join(cloneDirectory,'notification-checkpoint-'+tag+'.json'),{...identity,checks});console.log('Verified '+id);};
 const reject=async(action,status)=>{try{await action();assert.fail('Expected '+status);}catch(e){assert.equal(e.status,status);return status;}};
 const mode=(smtp='Accept',webhook='Accept',retryAfter='1')=>fixtureRequest(cloneDirectory,state,'/owner/mode',{method:'POST',body:{smtp,webhook,retryAfter}});
 const receipts=()=>fixtureRequest(cloneDirectory,state,'/owner/observations');
 const pg=resources.find(r=>r.Kind==='container'&&r.Config?.Labels?.['com.docker.compose.service']==='postgres');assert(pg);const sql=async(text)=>{assertOwnership(state,[pg]);const response=await docker(['exec',pg.Id,'psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1'],{input:text});return response.stdout.trim();};
 const idlist=ids=>{assert(ids.length&&ids.every(id=>/^[a-f0-9-]{36}$/.test(id)));return ids.map(id=>"'"+id+"'::uuid").join(',');};
 async function save({enabled=true,security='StartTlsRequired',replace=false}={}){const saved=await tester.client.request('/settings/system/notification'),values={smtpHost:'notification-fixture',smtpPort:2525,fromEmail:'sender@example.test',smtpSecretRef:{operation:replace?'Replace':'Keep',...(replace?{reference:'vault://local-notification/smtp'}:{})},webhookUrl:'https://notification-fixture:9443/notify',webhookSecretRef:{operation:replace?'Replace':'Keep',...(replace?{reference:'vault://local-notification/webhook'}:{})},smtpEnabled:enabled,webhookEnabled:enabled,smtpSecurity:security};const tag='"'+saved.revision+'"',preview=await tester.client.request('/settings/system/notification/preview',{method:'POST',headers:{'If-Match':tag},body:{values}});return tester.client.request('/settings/system/notification',{method:'PUT',headers:{'If-Match':tag},body:{values,confirmationToken:preview.confirmationToken}});}
 const saved=await save({replace:true});
 async function rule(channels=['Email','Webhook'],baseDelaySeconds=1){return writer.client.request('/observability/alert-rules',{method:'POST',body:{...scope,name:'通知协议 '+tag+' '+randomUUID().slice(0,8),metric:'request_rps',expression:'request_rps > 1000000000',severity:'Warning',enabled:true,forSeconds:0,targetType:'Environment',targetId:null,windowSeconds:60,notification:{inConsole:true,requestedChannels:channels,externalEnabled:true,emailRecipients:channels.includes('Email')?['recipient@example.test']:[],notifyRecovery:true,retryPolicy:{maxAttempts:3,baseDelaySeconds,maxDelaySeconds:900,expiresAfterMinutes:5}}}});}
 async function seed(r){const response=await ctx.compose('run','--rm','--no-deps','-e','WEBAPI_RUNTIME_PROJECT='+state.projectName,'-e','WEBAPI_RUNTIME_OWNER='+state.ownerId,'-e','WEBAPI_NOTIFICATION_QA_ENABLED=true','--entrypoint','dotnet','worker','/app/notification-fixture/WebApi.NotificationFixtureHost.dll','seed-notification-event',r.id);return JSON.parse(response.stdout.trim());}
 const list=e=>writer.client.request('/alerts/'+e.eventId+'/notifications?pageSize=100');const done=(e,predicate)=>until(()=>list(e),p=>predicate(p.items),45);const attempt=d=>writer.client.request('/notification-deliveries/'+d.id+'/attempts?pageSize=100');
 async function act(e,kind){const detail=await writer.client.request('/observability/alerts/'+e.eventId);return writer.client.request('/observability/alerts/'+e.eventId+'/'+kind.toLowerCase(),{method:'POST',headers:{'If-Match':'"'+detail.revision+'"'},body:{kind,reason:kind==='Unsilence'?null:'Owned fixture action',...(kind==='Silence'?{durationSeconds:900}:{})}});}
 const workerOverride=path.join(cloneDirectory,'notification-scenario-workers.json');await writePrivate(workerOverride,{services:{worker:{environment:{Notifications__Concurrency:'1'}}}});const refresh=async()=>{ctx=await prepareContext(cloneDirectory,state,release);ctx.files.push('-f',workerOverride);};await refresh();
 const start=()=>ctx.compose('up','-d','--scale','worker=2','worker');const stop=()=>ctx.compose('stop','worker');
 await start();await mode();
 const first=await seed(await rule()),accepted=await done(first,rows=>rows.length===2&&rows.every(r=>r.status==='Accepted'));let observed=await receipts();const email=accepted.items.find(r=>r.channel==='Email'),hook=accepted.items.find(r=>r.channel==='Webhook'),smtp=observed.protocol.smtp.filter(r=>r.deliveryId===email.id),hooks=observed.protocol.webhook.filter(r=>r.deliveryId===hook.id);
 await note('smtp-single-recipient',smtp.map(r=>[r.recipientCount,r.ccCount,r.bccCount,r.tls,r.authenticated,r.accepted,r.replyCode]),[[1,0,0,true,true,true,250]]);await note('webhook-signature',hooks.map(r=>[r.signatureValid,r.tls,r.remoteAccepted,r.replyCode]),[[true,true,true,202]]);
 await mode('Accept','Temporary');const transient=await seed(await rule(['Webhook'])),pending=await done(transient,rows=>rows[0]?.status==='RetryScheduled');await mode();const retried=await done(transient,rows=>rows[0]?.status==='Accepted');const fiveAttempts=await attempt(retried.items[0]);await note('webhook-5xx-retry',fiveAttempts.items.map(a=>[a.attemptNo,a.protocolStatus,a.outcome]).sort((a,b)=>a[0]-b[0]),[[1,500,'TransientFailure'],[2,202,'Accepted']]);
 await mode('Accept','RateLimited','7200');const limited=await seed(await rule(['Webhook'])),exhausted=await done(limited,rows=>rows[0]?.status==='Failed');await note('webhook-429-budget',[exhausted.items[0].attemptCount,exhausted.items[0].reason,(await attempt(exhausted.items[0])).items[0].protocolStatus],[1,'RetryAfterExceedsBudget',429]);
 await mode('Accept','Disconnect');const unclear=await seed(await rule(['Webhook'],30)),unknown=await done(unclear,rows=>rows[0]?.status==='RetryScheduled');assert.equal((await attempt(unknown.items[0])).items[0].outcome,'OutcomeUnknown');await mode();await sql('UPDATE notification_deliveries SET next_attempt_at=now() WHERE id IN ('+idlist([unknown.items[0].id])+');');const later=await done(unclear,rows=>rows[0]?.status==='Accepted');observed=await receipts();const repeat=observed.protocol.webhook.filter(r=>r.deliveryId===later.items[0].id);await note('unknown-disconnect',[repeat.length,repeat[0].remoteAccepted,repeat[1].duplicate,new Set(repeat.map(r=>r.bodyHash)).size,later.items[0].attemptCount],[2,true,true,1,2]);
 await stop();const quiet=await seed(await rule(['Email']));await act(quiet,'Silence');await start();const quietRows=(await list(quiet)).items;await pause(1500);observed=await receipts();await note('silence-before-start',[quietRows[0].status,quietRows[0].attemptCount,observed.protocol.smtp.filter(r=>r.deliveryId===quietRows[0].id).length],['Paused',0,0]);
 await mode('Accept','Delay');const inFlight=await seed(await rule(['Webhook']));const sending=await done(inFlight,rows=>rows[0]?.status==='Sending');await until(receipts,r=>r.protocol.webhook.some(r=>r.deliveryId===sending.items[0].id&&r.remoteAccepted),15);await act(inFlight,'Silence');const paused=await done(inFlight,rows=>rows[0]?.status==='Paused');await note('silence-in-flight',[paused.items[0].attemptCount,paused.items[0].status,(await attempt(paused.items[0])).items[0].outcome],[1,'Paused','OutcomeUnknown']);await mode();
 await act(first,'Resolve');const recovered=await done(first,rows=>rows.length===4&&rows.every(r=>r.status==='Accepted'));const parentIds=accepted.items.map(r=>r.id);const pairs=JSON.parse(await sql('SELECT json_agg(json_build_object(\'parent\',triggered_delivery_id,\'channel\',channel,\'status\',status)) FROM notification_deliveries WHERE event_id='+idlist([first.eventId])+' AND triggered_delivery_id IS NOT NULL;'));await note('paired-recovery',[pairs.length,pairs.every(p=>parentIds.includes(p.parent)&&p.status==='Accepted'),new Set(pairs.map(p=>p.parent)).size],[2,true,2]);
 // Both actual workers begin wire attempts, then are killed. Only own persisted lease time is advanced.
 await mode('Delay','Delay');const race=await seed(await rule()),leases=await until(async()=>JSON.parse(await sql('SELECT json_agg(json_build_object(\'id\',id,\'token\',lease_token,\'owner\',lease_owner,\'count\',attempt_count,\'expires\',expires_at)) FROM notification_deliveries WHERE event_id='+idlist([race.eventId])+" AND status='Sending';")),rows=>rows?.length===2,15);await stop();await sql('UPDATE notification_deliveries SET lease_until=now()-interval \'1 second\' WHERE id IN ('+idlist(leases.map(r=>r.id))+');');await mode();await start();const resumed=await done(race,rows=>rows.length===2&&rows.every(r=>r.status==='Accepted'));const after=JSON.parse(await sql('SELECT json_agg(json_build_object(\'id\',id,\'token\',lease_token,\'count\',attempt_count,\'expires\',expires_at)) FROM notification_deliveries WHERE id IN ('+idlist(leases.map(r=>r.id))+');'));assert.equal(new Set(leases.map(l=>l.owner)).size,2);await note('lease-fencing',[after.every(a=>a.token>leases.find(b=>b.id===a.id).token),after.every(a=>a.count===2&&a.expires===leases.find(b=>b.id===a.id).expires)],[true,true]);await note('worker-restart',[resumed.items.length,(await Promise.all(resumed.items.map(attempt))).every(p=>p.items.some(a=>a.code==='LeaseExpired'&&a.outcome==='OutcomeUnknown'))],[2,true]);
 // Saved explicit test while automatic switches remain off, plus real required TLS failure.
 const disabled=await save({enabled:false});await stop();const explicit=await tester.client.request('/settings/system/notification/tests',{method:'POST',headers:{'If-Match':'"'+disabled.revision+'"'},body:{channel:'Email',email:'recipient@example.test'}});assert.equal(explicit.status,'Queued');await start();const testDone=await until(()=>tester.client.request('/settings/system/notification/tests/'+explicit.id),r=>r.status==='Accepted',30);const same=await tester.client.request('/settings/system/notification');await note('explicit-test-disabled',[explicit.maxAttempts,explicit.status,testDone.status,same.values.smtpEnabled,same.values.webhookEnabled],[1,'Queued','Accepted',false,false]);await note('saved-revision-conflict',await reject(()=>tester.client.request('/settings/system/notification/tests',{method:'POST',headers:{'If-Match':'"0"'},body:{channel:'Webhook'}}),412),412);
 const tls=await save({enabled:false,security:'TlsOnConnect'}),tlsActor=await actor('tls-negative','read_write',true),negative=await tlsActor.client.request('/settings/system/notification/tests',{method:'POST',headers:{'If-Match':'"'+tls.revision+'"'},body:{channel:'Email',email:'recipient@example.test'}}),failedTls=await until(()=>tlsActor.client.request('/settings/system/notification/tests/'+negative.id),r=>['Failed','Suppressed','Expired'].includes(r.status),30);observed=await receipts();await note('smtp-required-tls',[failedTls.status,observed.protocol.smtp.filter(r=>r.deliveryId===negative.id&&r.accepted).length,smtp[0].tls],['Failed',0,true]);await save({enabled:true});
 // Pause and replace a private SMTP file explicitly in this own clone, verify stale pin rejection.
 await stop();const changed=await seed(await rule(['Email'])),changedRow=(await list(changed)).items[0],file=path.join(secretDirectory,'sender/smtp.json'),original=await fs.readFile(file),credential=JSON.parse(original);credential.password=randomBytes(32).toString('base64');await writePrivate(file,credential);
 const receiptFile=path.join(secretDirectory,'receipt.json'),receipt=JSON.parse(await fs.readFile(receiptFile));receipt.files['sender/smtp.json']=hash(await fs.readFile(file));await writePrivate(receiptFile,receipt);const senderVolume=state.projectName+'_notification-secrets';assertOwnership(state,JSON.parse((await docker(['volume','inspect',senderVolume])).stdout));await docker(['run','--rm','--user','0:0','--mount','type=bind,src='+path.join(secretDirectory,'sender')+',dst=/input,readonly','--mount','type=volume,src='+senderVolume+',dst=/out',release.dependencyImages.sdk,'bash','-c','cp /input/smtp.json /out/smtp.json; chown 10001:10001 /out/smtp.json; chmod 600 /out/smtp.json']);await refresh();await start();const stale=await done(changed,rows=>rows[0]?.status==='Suppressed');await note('secret-version-change',[stale.items[0].reason,stale.items[0].attemptCount],['SecretVersionChanged',0]);await stop();await writePrivate(file,original.toString());receipt.files['sender/smtp.json']=hash(original);await writePrivate(receiptFile,receipt);await docker(['run','--rm','--user','0:0','--mount','type=bind,src='+path.join(secretDirectory,'sender')+',dst=/input,readonly','--mount','type=volume,src='+senderVolume+',dst=/out',release.dependencyImages.sdk,'bash','-c','cp /input/smtp.json /out/smtp.json; chown 10001:10001 /out/smtp.json; chmod 600 /out/smtp.json']);await refresh();await start();
 await note('retry-write-denied',await reject(()=>reader.client.request('/notification-deliveries/'+changedRow.id+'/retry',{method:'POST',headers:{'If-Match':'"'+stale.items[0].revision+'"'},body:{}}),403),403);
 let user=(await admin.request('/users?pageSize=100')).items.find(u=>u.id===revoked.id);assert(user);await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{scopes:[]}});await note('scope-read-denied',await reject(()=>revoked.client.request('/alerts/'+first.eventId+'/notifications'),404),404);
 const actual=await receipts();assert.equal(actual.sourceRevision,revision);assert.equal(actual.binaryHash,release.applications['notification-fixture/WebApi.NotificationFixtureHost.dll']);assert(actual.binaryVerified);await writePrivate(path.join(fixtureDirectory,'fixture.json'),{...actual,imageId});
 const runtime={...identity,ownerId:state.ownerId,projectName:state.projectName,imageLabel:revision,originalConsolePort:4192,staticFiles:release.staticFiles,backupVolumes:['dp-keys','notification-secrets','notification-fixture-secrets','notification-fixture-data']};await writePrivate(path.join(fixtureDirectory,'runtime.json'),runtime);
 const result={schemaVersion:1,...identity,clone:{actual:true,ownerVerified:true,ownerId:state.ownerId,projectName:state.projectName,consolePort:state.ports.console},fixture:{actual:true,ownerVerified:true,...identity,host:'notification-fixture',tls:true,observation:'fixture.json'},checks,protocol:actual.protocol,runtime:{observation:'runtime.json',backupVolumes:runtime.backupVolumes,oldToolsUnchanged:true},ui:null,manifest:[],originalInstallation:'not-upgraded'};
 const browserActors=Object.fromEntries(Object.entries(actors).map(([key,{client,...actor}])=>[key,actor]));await writePrivate(path.join(cloneDirectory,'notification-browser-context.json'),{...identity,endpoint,scope,organization,project,environment,actors:browserActors,firstEventId:first.eventId,quietEventId:quiet.eventId,inFlightEventId:inFlight.eventId,testDeliveryId:explicit.id,retryEventId:transient.eventId,admin:{username:state.bootstrapUsername,password}});await writePrivate(path.join(cloneDirectory,'notification-scenario-result.json'),result);return result;
}
