import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {LocalClient} from '../local-client.mjs';import {sha} from './evidence.mjs';
const require=createRequire('/Users/leo.cui/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'),{chromium}=require('playwright'),root=path.resolve(import.meta.dirname,'../..'),info=JSON.parse(await fs.readFile(path.join(root,'.runtime/policy-review.json'))),ctx=JSON.parse(await fs.readFile(info.directory+'/review-context.json')),verification=JSON.parse(await fs.readFile(path.join(root,'docs/evidence/policies/verification.json'))),password=await fs.readFile(info.directory+'/password','utf8'),output=path.join(root,'docs/evidence/policies/ui');await fs.mkdir(output,{recursive:true});const admin=new LocalClient(ctx.endpoints.control_plane);await admin.login('e2e-admin',password);
const browser=await chromium.launch({headless:true,executablePath:process.env.WEBAPI_BROWSER_EXECUTABLE||'/Users/leo.cui/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'}),context=await browser.newContext({viewport:{width:1440,height:1100}});let page=await context.newPage();const screenshots=[],checks=[];
async function login(name='e2e-admin'){await page.goto(info.url);await page.getByLabel('用户名').fill(name);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByLabel('当前组织').waitFor();}
async function snap(name){await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});const bytes=await fs.readFile(path.join(output,name+'.png'));assert.equal(bytes.readUInt32BE(16),1440);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false,name+' horizontal overflow');screenshots.push({name,file:'ui/'+name+'.png',width:1440,height:1100,sha256:sha(bytes)});}
async function go(url){await page.goto(info.url+url);await page.waitForLoadState('networkidle');}
try{
 await login();await go('/policies');await page.getByRole('heading',{name:'策略中心',exact:true}).waitFor();await page.getByRole('link',{name:'订单共享额度',exact:true}).waitFor();await snap('01-policy-center');checks.push({name:'策略中心与导航',passed:true});
 await go('/policies/'+verification.policies.rateId);await page.getByLabel('策略名称',{exact:false}).fill('浏览器保留的配置输入');const p=await admin.request('/policies/'+verification.policies.rateId);await admin.request('/policies/'+p.id,{method:'PUT',headers:{'If-Match':`"${p.versionNo}"`},body:{name:p.name,type:p.type,config:p.config,enabled:p.enabled}});await page.getByRole('button',{name:'保存工作配置',exact:true}).click();await page.getByRole('heading',{name:'服务器修订已更新 · 你的输入已保留'}).waitFor();assert.equal(await page.getByLabel('策略名称',{exact:false}).inputValue(),'浏览器保留的配置输入');await snap('02-policy-editor-conflict');await page.getByRole('button',{name:'查看服务器最新配置'}).click();await page.getByRole('button',{name:'保持我的输入，采用最新修订'}).click();assert.equal(await page.getByLabel('策略名称',{exact:false}).inputValue(),'浏览器保留的配置输入');await page.getByRole('button',{name:'放弃未保存修改'}).click();await page.getByRole('button',{name:'确认放弃',exact:true}).click();checks.push({name:'真实412保留输入与显式合并',passed:true});
 await go('/policies/'+verification.policies.circuitId);await snap('03-circuit-editor-references');assert(await page.locator('fieldset input,fieldset select').evaluateAll(els=>els.every(el=>el.closest('label'))));await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement?.tagName),'BODY');checks.push({name:'动态字段标签与键盘',passed:true});
 const longPolicy=await admin.request('/projects/'+verification.scope.projectId+'/policies',{method:'POST',body:{name:'名称'+ '长'.repeat(110),type:'circuit_breaker',config:JSON.stringify({samplingWindowMs:30000,minimumRequests:20,failureRatio:0.5,openDurationMs:30000,halfOpenMaxRequests:1,halfOpenSuccesses:3,failureStatusCodes:Array.from({length:100},(_,i)=>500+i),countTimeouts:true,countConnectionFailures:true}),enabled:true}});await go('/policies/'+longPolicy.id);await page.getByLabel('策略名称',{exact:false}).fill('名称'+ '长'.repeat(109));await snap('04-new-rate-policy-long-json');await page.getByRole('button',{name:'放弃未保存修改'}).click();await page.getByRole('button',{name:'确认放弃',exact:true}).click();checks.push({name:'长名称与JSON布局',passed:true});
 await go('/routes');await page.getByRole('button',{name:'策略绑定',exact:true}).first().click();await page.getByRole('dialog').waitFor();await snap('05-route-policy-bindings');await page.getByRole('button',{name:'关闭',exact:true}).click();checks.push({name:'路由整组绑定可操作',passed:true});
 await go('/policies/'+verification.policies.rateId);await page.getByRole('button',{name:'提交发布',exact:true}).click();await page.unrouteAll({behavior:'wait'});await page.getByRole('button',{name:'加载受影响 API 版本'}).click();await page.getByRole('button',{name:'读取完整发布 Review'}).click();await page.getByRole('button',{name:'确认 Review，创建发布草稿'}).waitFor();await snap('06-policy-release-review');checks.push({name:'目标环境版本预填与完整Review',passed:true});
 const env=await admin.request('/environments/'+verification.scope.environmentId),versionIds=[(await admin.request('/apis/'+verification.apiIds[0]+'/versions'))[0].id],candidate=await admin.request(`/environments/${env.id}/releases/preview`,{method:'POST',body:{baseConfigVersion:env.desiredConfigVersion,versionIds}}),draft=await admin.request(`/environments/${env.id}/releases`,{method:'POST',body:{baseConfigVersion:env.desiredConfigVersion,versionIds,resourceRevisions:candidate.resourceRevisions}});const current=await admin.request('/policies/'+verification.policies.rateId);await admin.request('/policies/'+current.id,{method:'PUT',headers:{'If-Match':`"${current.versionNo}"`},body:{name:current.name,type:current.type,config:current.config,enabled:current.enabled}});await go('/releases/'+draft.id);await page.getByRole('heading',{name:'Review 修订已过期 · 需要显式刷新'}).waitFor();await snap('07-draft-explicit-refresh');await page.getByRole('button',{name:'确认当前候选，刷新 Review'}).click();await page.getByRole('heading',{name:'Review 修订已过期 · 需要显式刷新'}).waitFor({state:'hidden'});checks.push({name:'过期Draft显式刷新',passed:true});
 await go('/nodes');await snap('08-node-capabilities');await go('/observability/logs?policy='+verification.policies.rateId+'&decision=Exceeded');await snap('09-policy-access-logs');await go('/observability/traces?trace='+verification.signals.traceId+'&end='+encodeURIComponent(new Date().toISOString()));await page.getByRole('button',{name:/查看 .* Server span/}).first().click();await page.getByRole('heading',{name:'策略决策',exact:true}).scrollIntoViewIfNeeded();await page.locator('.trace-span-details').filter({hasText:'OpenRejected'}).waitFor();await snap('10-policy-trace');checks.push({name:'节点能力与实际决策筛选',passed:true});
 await go('/policies');await page.getByPlaceholder('策略名称',{exact:true}).fill('绝不会匹配-'+crypto.randomUUID());await page.getByText('暂无策略，可按业务需要创建工作配置').waitFor();await snap('11-policy-empty');
 await page.route('**/api/v1/projects/*/policies*',async route=>{await new Promise(r=>setTimeout(r,1800));try{await route.continue();}catch{}});await page.getByPlaceholder('策略名称',{exact:true}).fill('');await page.getByText('正在读取服务端数据…').first().waitFor();await snap('12-policy-loading');await page.waitForLoadState('networkidle');await page.unrouteAll({behavior:'wait'});await page.close();page=await context.newPage();let failureHits=0;await page.route('**/*',route=>{if(/\/projects\/[^/]+\/policies/.test(new URL(route.request().url()).pathname)&&route.request().method()==='GET'){failureHits++;return route.fulfill({status:503,contentType:'application/problem+json',body:JSON.stringify({detail:'查询服务暂不可用，请重试'})});}return route.continue();});await go('/policies');assert(failureHits>0,'Controlled GET failure must hit actual list request');await page.getByRole('alert').filter({hasText:'查询服务暂不可用，请重试'}).waitFor();await snap('13-policy-read-error');await page.unrouteAll({behavior:'wait'});checks.push({name:'空加载错误状态',passed:true,readFailureInjection:'browser-only GET 503'});
 const otherOrg=await admin.request('/organizations',{method:'POST',body:{code:'QA_SCOPE',name:'页面隔离验收组织'}});await admin.request(`/organizations/${otherOrg.id}/projects`,{method:'POST',body:{code:'QA_SCOPE',name:'页面隔离验收项目'}});await go('/policies/'+verification.policies.rateId);const originalOrg=await page.getByLabel('当前组织').inputValue();await page.getByLabel('策略名称',{exact:false}).fill('范围切换前保留的输入');await page.getByLabel('当前组织').selectOption(otherOrg.id);assert.equal(await page.getByLabel('当前组织').inputValue(),originalOrg);assert.equal(await page.getByLabel('策略名称',{exact:false}).inputValue(),'范围切换前保留的输入');await page.getByRole('button',{name:'放弃未保存修改'}).click();await page.getByRole('button',{name:'确认放弃',exact:true}).click();await go('/policies');await page.getByLabel('当前组织').selectOption(otherOrg.id);await page.getByText('暂无策略，可按业务需要创建工作配置').waitFor();await snap('15-policy-cross-scope');checks.push({name:'真实范围切换与脏输入保护',passed:true});await page.getByLabel('当前组织').selectOption(originalOrg);
 await context.clearCookies();await go('/policies');await login('e2e-reader');await go('/policies');assert(await page.getByRole('button',{name:'＋ 新建策略',exact:true}).isDisabled());await go('/policies/'+verification.policies.rateId);assert(await page.getByRole('button',{name:'保存工作配置',exact:true}).isDisabled());await snap('14-policy-read-only');checks.push({name:'真实只读账号禁止写入',passed:true});
 await fs.writeFile(path.join(output,'qa.json'),JSON.stringify({complete:!info.preview,viewport:{width:1440,height:1100},classification:'real-isolated-server-browser-qa',project:info.project,sourceManifestHash:ctx.image.sourceManifestHash,screenshots,checks,defects:[],visualReviewComplete:false},null,2)+'\n');console.log('Browser interaction checks passed; pixel review still required.');
}catch(error){await page.screenshot({path:path.join(root,'.superpowers/sdd/2026-10-05-traffic-policies-implementation/ui-failure.png')});throw error;}finally{await browser.close();}
