import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {LocalClient} from '../local-client.mjs';import {sha,assertNoSecrets} from './evidence.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function wait(action,predicate,seconds=90){const until=Date.now()+seconds*1000;let error;while(Date.now()<until){try{const v=await action();if(predicate(v))return v;}catch(e){if(e.message?.startsWith('Release failed:'))throw e;error=e;}await sleep(400);}throw error||Error('Real policy scenario did not converge');}
export async function runTrafficPolicyScenario(c){
 const {context:s,endpoints:e,directory,compose}=c,password=await fs.readFile(directory+'/password','utf8'),credential=await fs.readFile(directory+'/credential','utf8'),clients=[];for(const name of ['e2e-admin','e2e-approver','e2e-security']){const client=new LocalClient(e.control_plane);await client.login(name,password);clients.push(client);}const [admin,reviewer,security]=clients,checks=[],traces=[];
 const check=(name,facts)=>{checks.push({name,passed:true,...facts});console.log('Verified '+name);};const write=(url,body,etag,method='POST')=>admin.request(url,{method,body,headers:etag?{'If-Match':`"${etag}"`}:undefined});
 const scope={organizationId:s.organizationId,projectId:s.projectId,environmentId:s.environmentId};async function approve(id){await write(`/releases/${id}/submit`);await reviewer.request(`/releases/${id}/approve`,{method:'POST',body:{comment:'流量策略独立审批'}});await security.request(`/releases/${id}/approve`,{method:'POST',body:{comment:'独立安全复核'}});}
 async function done(id){return wait(()=>admin.request(`/releases/${id}`),r=>{if(r.state==='Failed')throw Error('Release failed: '+r.errors.join(';'));return r.state==='Succeeded'&&r.targets.length===2&&r.targets.every(t=>t.acknowledged);});}
 const env=()=>admin.request(`/environments/${s.environmentId}`);const nodes=async()=> (await admin.request(`/environments/${s.environmentId}/gateway-nodes`)).items;
 async function release(versionIds){const current=await env(),request={baseConfigVersion:current.desiredConfigVersion||0,versionIds},preview=await write(`/environments/${s.environmentId}/releases/preview`,request),r=await write(`/environments/${s.environmentId}/releases`,{...request,resourceRevisions:preview.resourceRevisions});await approve(r.id);await write(`/releases/${r.id}/publish`);return done(r.id);}
 async function request(node=0,path='/orders',key=credential){const trace=randomBytes(16).toString('hex'),response=await fetch((node===0?e.gateway_a:e.gateway_b)+path,{headers:{'X-API-Key':key,traceparent:`00-${trace}-0123456789abcdef-01`},signal:AbortSignal.timeout(15000)});let body;try{body=await response.json();}catch{}traces.push({traceId:trace,status:response.status});return {status:response.status,body,retryAfter:response.headers.get('retry-after'),traceId:trace};}
 const backend=async(path,method='POST')=>{const r=await fetch(e.backend_a+path,{method,signal:AbortSignal.timeout(5000)});assert(r.ok);const text=await r.text();return text?JSON.parse(text):null;};
 async function bind(routeId,policies){const b=await admin.request(`/routes/${routeId}/policies`);return write(`/routes/${routeId}/policies`,{bindings:policies.map((p,i)=>({policyId:p.id,priority:100+i}))},b.revision,'PUT');}
 const save=(p,config)=>write('/policies/'+p.id,{name:p.name,type:p.type,enabled:true,config:JSON.stringify(config)},p.versionNo,'PUT');
 const policy=(name,type,config)=>write(`/projects/${s.projectId}/policies`,{name,type,enabled:true,config:JSON.stringify(config)});
 const rateConfig={algorithm:'TokenBucket',keyBy:'ApplicationRoute',refillTokens:1,windowMs:600000,burst:3,redisFailureMode:'Reject'},circuitConfig={samplingWindowMs:30000,minimumRequests:2,failureRatio:0.5,openDurationMs:1500,halfOpenMaxRequests:1,halfOpenSuccesses:2,failureStatusCodes:[503],countTimeouts:true,countConnectionFailures:true};
 const version=await write('/apis/'+s.apiId+'/versions',{version:'1.0.0'}),route=await write(`/environments/${s.environmentId}/routes`,{apiVersionId:version.id,routeName:'Orders',path:'/orders/{*rest}',methods:['GET'],clusterId:s.clusterId,priority:100,enabled:true,requireApiKey:true,timeoutMs:30000});
 const plain=await release([version.id]);assert.equal((await request()).status,200);const p=await policy('订单共享额度','rate_limit',rateConfig);await bind(route.id,[p]);assert.equal((await request(1)).status,200);const advanced=await release([version.id]);
 let all=await nodes();const nodeB=all.find(n=>n.nodeName==='gateway-b');assert(nodeB);await compose('stop','gateway-b');const secretB=await fs.readFile(directory+'/node-b','utf8');const nodeCall=async(path,body)=>fetch(e.control_plane+'/internal/v1/nodes/'+nodeB.id+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secretB},body:JSON.stringify(body)});
 assert((await nodeCall('/heartbeat',{instanceId:nodeB.instanceId,configVersion:advanced.targetConfigVersion,deploymentSequence:advanced.deploymentSequence,status:'Ready',supportedSnapshotSchemas:['2.0']})).ok);const before=await env(),preview=await write(`/environments/${s.environmentId}/releases/preview`,{baseConfigVersion:before.desiredConfigVersion,versionIds:[version.id]}),gated=await write(`/environments/${s.environmentId}/releases`,{baseConfigVersion:before.desiredConfigVersion,versionIds:[version.id],resourceRevisions:preview.resourceRevisions});await approve(gated.id);await assert.rejects(write(`/releases/${gated.id}/publish`),x=>x.status===409);const after=await env();assert.equal(after.desiredConfigVersion,before.desiredConfigVersion);assert.equal(after.deploymentSequence,before.deploymentSequence);await compose('start','gateway-b');e.gateway_b='http://'+await compose('port','gateway-b','8080');await wait(nodes,x=>x.find(n=>n.id===nodeB.id)?.supportedSnapshotSchemas?.includes('2.1'));await write(`/releases/${gated.id}/publish`);const gateDone=await done(gated.id);const replaced=(await nodes()).find(n=>n.id===nodeB.id);assert.notEqual(replaced.instanceId,nodeB.instanceId);const stale=await nodeCall('/ack',{instanceId:nodeB.instanceId,releaseId:gateDone.id,configVersion:gateDone.targetConfigVersion,deploymentSequence:gateDone.deploymentSequence,payloadHash:'0'.repeat(64),appliedAt:new Date().toISOString(),success:true,errorCode:null});assert.equal(stale.status,409);check('CurrentInstanceCapabilityGate',{desiredUnchanged:true,sequenceUnchanged:true,oldInstance:nodeB.instanceId,currentInstance:replaced.instanceId,staleAckStatus:stale.status});
 const start=performance.now(),responses=await Promise.all(Array.from({length:20},(_,i)=>request(i%2))),elapsedMs=performance.now()-start,accepted=responses.filter(r=>r.status===200).length,rejected=responses.filter(r=>r.status===429).length;assert.equal(accepted+rejected,20);assert(accepted<=rateConfig.burst+Math.floor(elapsedMs/rateConfig.windowMs));assert.equal(accepted,3);assert(responses.filter(r=>r.status===429).every(r=>Number(r.retryAfter)>=1));check('SharedRateLimit',{policyId:p.id,routeId:route.id,accepted,rejected,elapsedMs,burst:3,refillTokens:1,windowMs:600000,nodes:2});
 let generous=await save(p,{...rateConfig,refillTokens:1000,windowMs:1000,burst:1500});const cb=await policy('订单后端熔断','circuit_breaker',circuitConfig);await bind(route.id,[generous,cb]);let both=await release([version.id]);const failures=[await request(0,'/orders/__test/5xx'),await request(0,'/orders/__test/5xx')];assert(failures.every(r=>r.status===503));const open=await request(0);assert.equal(open.status,503);assert.equal(open.body.code,'circuit_open');assert.equal((await request(1)).status,200);await sleep(1700);assert.equal((await request(0)).status,200);assert.equal((await request(0)).status,200);assert.equal((await request(0)).status,200);check('ActualCircuitRecovery',{policyId:cb.id,failedCalls:2,openedNode:'gateway-a',otherNodeStatus:200,recoveredStatus:200,traceId:open.traceId});
 const api2=await write(`/projects/${s.projectId}/apis`,{code:'OTHER_ORDERS',name:'第二路由验收'}),v2=await write(`/apis/${api2.id}/versions`,{version:'1.0.0'}),r2=await write(`/environments/${s.environmentId}/routes`,{apiVersionId:v2.id,routeName:'OtherOrders',path:'/other',methods:['GET'],clusterId:s.clusterId,priority:100,enabled:true,timeoutMs:30000,requireApiKey:true});await write(`/applications/${s.applicationId}/permissions`,{apiId:api2.id,environmentId:s.environmentId,validFrom:new Date(Date.now()-60000).toISOString()});await bind(r2.id,[generous]);both=await release([version.id,v2.id]);const originalVersion=both.targetConfigVersion;
 const sql=q=>compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-At','-v','ON_ERROR_STOP=1','-c',q);async function payload(v){const b=await sql(`SELECT encode(s.payload_bytes,'base64') FROM gateway_config_snapshots s JOIN gateway_config_versions v ON v.id=s.config_version_id WHERE v.environment_id='${s.environmentId}' AND v.version_no=${Number(v)}`);return Buffer.from(b.replaceAll('\n',''),'base64');}const original=await payload(originalVersion);await fs.writeFile(directory+'/original.snapshot',original,{mode:0o600});
 generous=await save(generous,{...rateConfig,refillTokens:1000,windowMs:1000,burst:1600});const partial=await release([version.id]),json=JSON.parse(await payload(partial.targetConfigVersion)),byRoute=new Map(json.routes.map(r=>[r.id,r])),policyIds=new Map(json.policies.map(p=>[p.id,p]));const firstRate=byRoute.get(route.id).policyBindings.map(b=>policyIds.get(b.policyId)).find(p=>p.type==='rate_limit'),otherRate=byRoute.get(r2.id).policyBindings.map(b=>policyIds.get(b.policyId)).find(p=>p.type==='rate_limit');assert.notEqual(firstRate.id,otherRate.id);assert.equal(firstRate.sourceRevision,3);assert.equal(otherRate.sourceRevision,2);assert.equal((await request(1,'/other')).status,200);check('FrozenPolicyPartialRelease',{sourcePolicyId:p.id,selectedRuntimeId:firstRate.id,retainedRuntimeId:otherRate.id,selectedRevision:firstRate.sourceRevision,retainedRevision:otherRate.sourceRevision});
 await compose('stop','redis');let redisRejected;try{redisRejected=await wait(()=>request(0),r=>r.status===503&&r.body?.code==='rate_limit_store_unavailable',15);generous=await save(generous,{...rateConfig,refillTokens:1000,windowMs:1000,burst:1600,redisFailureMode:'Allow'});await release([version.id]);assert.equal((await request(1)).status,200);}finally{await compose('start','redis');}await wait(()=>request(0),r=>r.status===200,20);check('RedisFailureModes',{rejectStatus:redisRejected.status,rejectCode:redisRejected.body.code,allowStatus:200,recoveredStatus:200,traceId:redisRejected.traceId});
 await backend('/__test/hold-next');const oldRequest=request(0);await wait(()=>backend('/__test/hold-state','GET'),r=>r.started,10);const cluster=await admin.request(`/clusters/${s.clusterId}`),dest=cluster.destinations[0];await write('/destinations/'+dest.id,{name:dest.name,address:'http://backend-b:8080/',weight:1,enabled:true},dest.revision,'PUT');const swapped=await release([version.id]);assert.equal((await request(1)).body.backendId,'B');await backend('/__test/release');const old=await oldRequest;assert.equal(old.body.backendId,'A');assert(old.body.deploymentSequence<swapped.deploymentSequence);check('OldGenerationInFlight',{oldSequence:old.body.deploymentSequence,newSequence:swapped.deploymentSequence,oldBackend:'A',newBackend:'B'});
 async function rollback(from,target){const r=await write(`/releases/${from.id}/rollback`,{targetConfigVersion:target});await approve(r.id);await write(`/releases/${r.id}/publish`);return done(r.id);}
 const rollback21=await rollback(swapped,originalVersion),rolledBytes=await payload(rollback21.targetConfigVersion);assert.deepEqual(rolledBytes,original);await fs.writeFile(directory+'/rollback.snapshot',rolledBytes,{mode:0o600});assert.equal((await request(0)).body.backendId,'A');const rollback20=await rollback(rollback21,plain.targetConfigVersion);assert.equal(JSON.parse(await payload(rollback20.targetConfigVersion)).schemaVersion,'2.0');assert.equal((await request(1)).status,200);const restored=await rollback(rollback20,originalVersion);assert(restored.deploymentSequence>rollback21.deploymentSequence);await compose('restart','gateway-a','gateway-b');e.gateway_a='http://'+await compose('port','gateway-a','8080');e.gateway_b='http://'+await compose('port','gateway-b','8080');await wait(async()=>Promise.all([request(0),request(1)]),rs=>rs.every(r=>r.status===200),45);check('TwoPointZeroAndTwoPointOneRollback',{originalVersion,originalHash:sha(original),rollbackHash:sha(rolledBytes),twoPointZeroVersion:plain.targetConfigVersion,restoredVersion:restored.targetConfigVersion,sequence:restored.deploymentSequence,lkgRestartStatus:200});
 // Regression: ordinary editor round-trip must not persist a timeout policy override.
 const timeoutPolicy=await policy('基础超时保护验收','timeout',{timeoutMs:1000});await bind(r2.id,[generous,timeoutPolicy]);const editedRoute=await admin.request('/routes/'+r2.id);assert.equal(editedRoute.timeoutMs,30000);assert.equal(editedRoute.effectiveTimeoutMs,1000);await write('/routes/'+r2.id,{id:r2.id,apiVersionId:editedRoute.apiVersionId,routeName:editedRoute.routeName,path:'/other-edited',methods:editedRoute.methods,clusterId:editedRoute.clusterId,priority:editedRoute.priority,enabled:editedRoute.enabled,timeoutMs:editedRoute.timeoutMs,requireApiKey:editedRoute.requireApiKey},editedRoute.revision,'PUT');await bind(r2.id,[generous]);
 // Create a fresh, normally approved rollback record whose target cohort is the restarted instances.
 const finalRelease=await release([version.id,v2.id]);const finalStatus=(await request(0)).status;assert.equal(finalStatus,200);const finalSnapshot=JSON.parse(await payload(finalRelease.targetConfigVersion));assert.equal(finalSnapshot.routes.find(r=>r.id===r2.id).timeoutMs,30000);assert.equal((await request(1,'/other-edited')).status,200);check('PathEditTimeoutUnbindAndPublish',{baseTimeoutMs:30000,effectivePolicyTimeoutMs:1000,publishedTimeoutMs:30000,gatewayStatus:200});const finalNodes=await nodes();assert(finalRelease.targets.every(t=>finalNodes.some(n=>n.id===t.nodeId&&n.instanceId===t.instanceId)));
 await sleep(6000);const range={...scope,start:new Date(Date.now()-3600000).toISOString(),end:new Date().toISOString()},query=(kind,filter={})=>admin.request('/observability/'+kind+'?'+new URLSearchParams({...range,...filter}));const logs=await wait(()=>query('logs',{policyId:p.id,policyDecision:'Exceeded'}),x=>x.data?.items.some(r=>r.status===429),45),circuitLogs=await wait(()=>query('logs',{policyId:cb.id,policyDecision:'OpenRejected'}),x=>x.data?.items.some(r=>r.status===503),45),storeLogs=await wait(()=>query('logs',{policyId:p.id,policyDecision:'StoreRejected'}),x=>x.data?.items.some(r=>r.status===503),45),bypass=await wait(()=>query('logs',{policyId:p.id,policyDecision:'Bypass'}),x=>x.data?.items.some(r=>r.status===200),45);const traceId=circuitLogs.data.items[0].traceId,trace=await wait(()=>query('traces/'+traceId),x=>x.data?.spans.some(s=>s.kind==='Server'&&s.policyDecisions?.some(p=>p.decision==='OpenRejected')),45);
 const prometheusQuery=`webapi_gateway_policy_decisions_total{webapi_environment_id="${s.environmentId}"}`;const metrics=await wait(async()=>{const r=await fetch(e.prometheus+'/api/v1/query?'+new URLSearchParams({query:prometheusQuery}));assert(r.ok);return (await r.json()).data.result;},rows=>['Exceeded','OpenRejected','StoreRejected','Bypass'].every(d=>rows.some(r=>r.metric.webapi_policy_decision===d&&Number(r.value[1])>0)),45);const foreign=randomUUID();await assert.rejects(query('logs',{policyId:foreign}),x=>x.status===404);const metricEnvelope=await query('metrics',{groupBy:'None'});assert.equal(metricEnvelope.coverage.complete,false);assert.equal(metricEnvelope.sourceState,'Partial');assertNoSecrets({logs,circuitLogs,storeLogs,bypass,trace,metrics},[password,credential,secretB,await fs.readFile(directory+'/node-a','utf8')]);
 check('ObservationScopeAndSecretExclusion',{ratePolicyId:p.id,circuitPolicyId:cb.id,rateLimitLogCount:logs.data.items.length,circuitLogCount:circuitLogs.data.items.length,redisRejectLogCount:storeLogs.data.items.length,bypassLogCount:bypass.data.items.length,traceId,rootSpanFound:true,metricDecisions:[...new Set(metrics.map(r=>r.metric.webapi_policy_decision))],metricsSourceState:metricEnvelope.sourceState,coverageReason:metricEnvelope.coverage.reason,foreignPolicyStatus:404,secretsExcluded:true});
 return {schemaVersion:1,complete:false,classification:'real-isolated-double-gateway-three-source',project:c.project,image:c.image,scope,checks,finalStatus,finalRelease:{id:finalRelease.id,targetConfigVersion:finalRelease.targetConfigVersion,deploymentSequence:finalRelease.deploymentSequence,targets:finalRelease.targets.map(t=>({nodeId:t.nodeId,instanceId:t.instanceId,acknowledged:t.acknowledged}))},policies:{rateId:p.id,circuitId:cb.id},routeIds:[route.id,r2.id],apiIds:[s.apiId,api2.id],startedAt:new Date().toISOString(),limitations:['生产性能与外部企业集成未执行','一小时时窗不足，指标包络为 Partial，不将缺失样本显示为 0','4192 保持原版本，新功能仅在独立环境'],signals:{logIds:[logs.data.items[0].id,circuitLogs.data.items[0].id,storeLogs.data.items[0].id,bypass.data.items[0].id],traceId,metrics:metrics.map(r=>({labels:r.metric,value:r.value[1]}))}};
}
