// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Infrastructure.Persistence;

#nullable disable

namespace WebApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    [Migration("20261003182012_InitialCore")]
    partial class InitialCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Api", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionNo")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("GroupId", "ProjectId");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique();

                    b.HasIndex("ProjectId", "OrganizationId");

                    b.ToTable("apis", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("api_groups", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_version_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExampleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("example_json");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Schema")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId");

                    b.ToTable("api_parameters", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_version_id");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.PrimitiveCollection<string[]>("Methods")
                        .IsRequired()
                        .HasColumnType("varchar[]")
                        .HasColumnName("methods");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("normalized_path");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("path");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("route_name");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("timeout_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ClusterId", "EnvironmentId");

                    b.ToTable("api_routes", null, t =>
                        {
                            t.HasCheckConstraint("ck_route_methods_timeout", "cardinality(methods) > 0 AND timeout_ms > 0");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_version_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("ExampleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("example_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaHash")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("schema_hash");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("schema_type");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId");

                    b.ToTable("api_schemas", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("OpenapiDocument")
                        .HasColumnType("jsonb")
                        .HasColumnName("openapi_document");

                    b.Property<string>("OpenapiSource")
                        .HasColumnType("text")
                        .HasColumnName("openapi_source");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("SchemaHash")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("schema_hash");

                    b.Property<DateTimeOffset?>("SealedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sealed_at");

                    b.Property<string>("SourceFormat")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("source_format");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ApiId", "Version")
                        .IsUnique();

                    b.ToTable("api_versions", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationApiPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.HasKey("Id");

                    b.HasIndex("ApiId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ApplicationId", "ApiId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("application_api_permissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_grant_window", "expires_at IS NULL OR expires_at > valid_from");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("access_key");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("SecretLast4")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("secret_last4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey")
                        .IsUnique();

                    b.HasIndex("ApplicationId");

                    b.ToTable("application_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_credential_window", "expires_at > valid_from");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("owner");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.HasIndex("ProjectId", "OrganizationId");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("scope_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("approval_flows", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int")
                        .HasColumnName("required_count");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("role_code");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("FlowId", "StepOrder")
                        .IsUnique();

                    b.ToTable("approval_steps", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ActedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acted_at");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("FlowId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("approval_tasks", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resource_type");

                    b.Property<string>("TraceId")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<long>("DeploymentSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("deployment_sequence");

                    b.Property<long?>("DesiredConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("desired_config_version");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_production");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ReleasePolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_policy_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique();

                    b.ToTable("environments", null, t =>
                        {
                            t.HasCheckConstraint("ck_deployment_sequence", "deployment_sequence >= 0");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayAck", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("config_version");

                    b.Property<long>("DeploymentSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("deployment_sequence");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("instance_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("payload_hash");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("ReleaseId", "NodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("gateway_acks", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayConfigSnapshot", b =>
                {
                    b.Property<Guid>("ConfigVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<byte[]>("PayloadBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_bytes");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("ConfigVersionId");

                    b.ToTable("gateway_config_snapshots", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayConfigVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("SnapshotHash")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("snapshot_hash");

                    b.Property<string>("SnapshotKey")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("snapshot_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<long>("VersionNo")
                        .HasColumnType("bigint")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EnvironmentId", "VersionNo")
                        .IsUnique();

                    b.ToTable("gateway_config_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_config_version", "version_no > 0");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_version");

                    b.Property<long>("CurrentConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("current_config_version");

                    b.Property<long>("CurrentDeploymentSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("current_deployment_sequence");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("identity_hash");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("node_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<long?>("TargetConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("target_config_version");

                    b.HasKey("Id");

                    b.HasIndex("NodeName")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "Enabled");

                    b.ToTable("gateway_nodes", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayNodeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("GatewayNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("gateway_node_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("GatewayNodeId");

                    b.ToTable("gateway_node_events", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("request_hash");

                    b.Property<byte[]>("ResponseBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("response_bytes");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("scope_key");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "ScopeKey", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("DeploymentSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("deployment_sequence");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("ProcessedAt", "LeaseUntil");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionNo")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId", "OrganizationId");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("change_type");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("release_items", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("approval_policy");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<long>("BaselineConfigVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("baseline_config_version");

                    b.Property<byte[]>("CandidateBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("candidate_bytes");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deadline_at");

                    b.Property<long?>("DeploymentSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("deployment_sequence");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("FailureCode")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("failure_code");

                    b.Property<long>("FromConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("from_config_version");

                    b.Property<string>("ReleaseNo")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("release_no");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("release_type");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<Guid?>("RollbackOf")
                        .HasColumnType("uuid")
                        .HasColumnName("rollback_of");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<long>("ToConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("to_config_version");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ReleaseNo")
                        .IsUnique();

                    b.HasIndex("RequestedBy");

                    b.HasIndex("RollbackOf");

                    b.HasIndex("EnvironmentId", "Status");

                    b.ToTable("release_records", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseTarget", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("instance_id");

                    b.HasKey("ReleaseId", "NodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("release_targets", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("organization_id IS NULL");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasFilter("organization_id IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RouteMethod", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("Method")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("method");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("normalized_path");

                    b.HasKey("RouteId", "Method");

                    b.HasIndex("RouteId", "EnvironmentId");

                    b.HasIndex("EnvironmentId", "Method", "NormalizedPath")
                        .IsUnique();

                    b.ToTable("route_methods", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RoutePolicyBinding", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.HasKey("RouteId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("route_policy_bindings", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UpstreamCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("HealthCheckEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("health_check_enabled");

                    b.Property<int>("HealthCheckIntervalSec")
                        .HasColumnType("int")
                        .HasColumnName("health_check_interval_sec");

                    b.Property<string>("HealthCheckPath")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("health_check_path");

                    b.Property<string>("LoadBalancingPolicy")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("load_balancing_policy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "ProjectId");

                    b.ToTable("upstream_clusters", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UpstreamDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("address");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("upstream_destinations", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UserProjectScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("access_mode");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.HasIndex("EnvironmentId", "ProjectId");

                    b.HasIndex("ProjectId", "OrganizationId");

                    b.ToTable("user_project_scopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_scope_environment_requires_project", "environment_id IS NULL OR project_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthSource")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("auth_source");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("security_stamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Api", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiGroup", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiParameter", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiVersion", null)
                        .WithMany()
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiRoute", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiVersion", null)
                        .WithMany()
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UpstreamCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "EnvironmentId")
                        .HasPrincipalKey("Id", "EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiSchema", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiVersion", null)
                        .WithMany()
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApiVersion", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationApiPermission", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Api", null)
                        .WithMany()
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApplicationRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationCredential", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApplicationRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApplicationRecord", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalFlow", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalStep", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApprovalFlow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ApprovalTask", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApprovalFlow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayAck", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.GatewayNode", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseTarget", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayConfigSnapshot", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.GatewayConfigVersion", null)
                        .WithMany()
                        .HasForeignKey("ConfigVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayConfigVersion", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayNode", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.GatewayNodeEvent", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.GatewayNode", null)
                        .WithMany()
                        .HasForeignKey("GatewayNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Policy", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Project", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseItem", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("RollbackOf")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.ReleaseTarget", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.GatewayNode", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ReleaseRecord", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RouteMethod", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId", "EnvironmentId")
                        .HasPrincipalKey("Id", "EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.RoutePolicyBinding", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.ApiRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UpstreamCluster", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UpstreamDestination", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UpstreamCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UserProjectScope", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.EnvironmentRecord", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApi.Infrastructure.Persistence.Entities.UserRole", b =>
                {
                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApi.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
