import {useEffect,useRef,useState} from 'react';import {apiRequest} from '../api/client';import {useSession} from '../auth/SessionProvider';import {exampleOptions,validationMatches,validationContextMatches} from './schema-state.mjs';
export function SchemaDiagnostics({result,onSelect}:{result:any;onSelect:(pointer:string)=>void}){
 return <div className="schema-diagnostics" aria-live="polite"><strong>{result.status==='Valid'?'验证通过':result.status==='Invalid'?'验证不通过':'验证未完成'}</strong>{result.issues?.map((item:any,i:number)=><div className="schema-issue" key={i}><p>{item.message}</p><code>实例 {item.instancePointer||'/'} · {item.keyword}</code><button type="button" className="text-btn" aria-label={`定位 Schema ${item.schemaPointer||'/'}`} onClick={()=>onSelect(item.schemaPointer)}>Schema {item.schemaPointer||'/'}{item.line?` · ${item.line}:${item.column??1}`:''}</button></div>)}{result.coverageIssues?.map((item:any,i:number)=><p className="notice" key={i}>{item.code} · {item.message} <code>{item.pointer}</code></p>)}</div>;
}
export function ContractIssues({issues,onSelect}:{issues:any[];onSelect:(pointer:string)=>void}){
 return <div className="schema-diagnostics" aria-live="polite">{issues.map((item,i)=><div className="schema-issue" key={i}><p>{item.message}</p><code>{item.code}</code><button type="button" className="text-btn" aria-label={`定位受影响位置 ${item.pointer||'/'}`} onClick={()=>onSelect(item.pointer??'')}>{item.pointer||'/'}{item.line?` · ${item.line}:${item.column??1}`:''}</button></div>)}</div>;
}
const hash=async(text:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');
export function ExampleValidation({version,definition,rawSchema,onSelect}:{version:any;definition:any;rawSchema:string;onSelect:(pointer:string)=>void}){
 const session=useSession(),authority=JSON.stringify([session.user?.id,session.user?.permissions,session.user?.scopes,session.error]);const[example,setExample]=useState<string>(definition.exampleJson??'null'),[formatMode,setMode]=useState('Annotation'),[direction,setDirection]=useState(definition.schemaType==='response'?'response':'request'),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(),[error,setError]=useState('');const sequence=useRef(0),controller=useRef<AbortController|undefined>(undefined);
 const media=(definition.contentType??'application/json').split(';')[0].toLowerCase(),jsonMedia=media==='application/json'||media==='text/json'||media.endsWith('+json');const options=exampleOptions(definition);const context={versionId:version.id,definitionId:definition.id??'draft',revision:version.revision,rawSchema,example,formatMode,direction,authority,contentType:definition.contentType,schemaType:definition.schemaType};const currentContext=useRef(context);currentContext.current=context;const visibleResult=validationContextMatches(result?.context,context)?result?.result:undefined;
 useEffect(()=>{sequence.current++;controller.current?.abort();setResult(undefined);setError('');setBusy(false);return()=>{sequence.current++;controller.current?.abort();};},[version.id,version.revision,definition.id,rawSchema,example,formatMode,direction,authority,definition.contentType,definition.schemaType]);
 async function validate(){
  if(busy||session.error||!jsonMedia)return;controller.current?.abort();const request=new AbortController();controller.current=request;const token=++sequence.current,capturedContext=context;setBusy(true);setError('');setResult(undefined);
  try{
   if(new TextEncoder().encode(example).length>256*1024)throw new Error('示例超过 256 KiB。');JSON.parse(example);
   const identity={versionId:version.id,definitionId:definition.id??'draft',revision:version.revision,schemaHash:await hash(rawSchema),exampleHash:await hash(example),formatMode,direction,sequence:token};if(sequence.current!==token||request.signal.aborted||!validationContextMatches(capturedContext,currentContext.current))return;
   const parameter=definition.kind==='parameters'||Object.hasOwn(definition,'location');const response=await apiRequest<any>(`/versions/${version.id}/schema-validation`,{method:'POST',signal:request.signal,body:{expectedVersionRevision:version.revision,schemaId:parameter?null:definition.id??null,parameterId:parameter?definition.id??null:null,draft:true,draftSchemaJson:rawSchema,exampleJson:example,direction,formatMode}});
   if(sequence.current===token&&!request.signal.aborted&&validationContextMatches(capturedContext,currentContext.current)&&validationMatches({...response,identity},identity))setResult({context:capturedContext,result:response.result});
  }catch(e){if(sequence.current===token&&!request.signal.aborted)setError((e as Error).message);}
  finally{if(sequence.current===token&&!request.signal.aborted)setBusy(false);}
 }
 return <section className="schema-validation" aria-label="示例验证"><h3>示例验证</h3><p className="muted">临时验证不保存业务数据，示例不匹配不新增发布门禁。</p>{!jsonMedia&&<p className="notice">当前示例验证仅覆盖 JSON，{definition.contentType} 示例未验证。</p>}{options.length>0&&<label>来源示例<select defaultValue="" onChange={e=>{if(e.target.value==='')return;const entry=options[Number(e.target.value)];sequence.current++;controller.current?.abort();setBusy(false);setResult(undefined);if(entry?.json!==undefined){setExample(entry.json);setError('');}else if(entry)setError(entry.unverifiedReason??'外部示例未验证，不自动获取。');}}><option value="">选择维护或 OpenAPI 示例</option>{options.map((entry,i)=><option key={i} value={i}>{entry.name}{entry.unverified?' · 未验证':''}</option>)}</select></label>}<div className="schema-validation-options"><label>校验方向<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="request">请求</option><option value="response">响应</option></select></label><label>Format 模式<select value={formatMode} onChange={e=>setMode(e.target.value)}><option value="Annotation">Annotation · 格式仅作注解</option><option value="Strict">Strict · 校验登记格式</option></select></label></div><label>示例 JSON<textarea rows={6} value={example} onChange={e=>setExample(e.target.value)} spellCheck={false}/></label><button type="button" className="btn" disabled={busy||!!session.error||!jsonMedia} onClick={()=>void validate()}>{busy?'验证中…':'验证示例'}</button>{busy&&<button type="button" className="text-btn" onClick={()=>{sequence.current++;controller.current?.abort();setBusy(false);}}>取消验证</button>}{error&&<p className="error" role="alert">{error}</p>}{visibleResult&&<><p className="muted">{visibleResult.dialect} · {visibleResult.formatMode} · 修订 {version.revision}</p><SchemaDiagnostics result={visibleResult} onSelect={onSelect}/></>}</section>;
}
