import {useEffect,useRef,useState} from 'react';
import {apiRequest,ApiError} from '../api/client';
import {readAllPages} from '../api/paging.mjs';
import {useSession} from '../auth/SessionProvider';
import {Feedback,useRemote,useUnsaved} from '../ui';
import type {ScopeTree} from '../api/types';
import {loadScopeSnapshot,newRule,payload,toDraft,updateRule,validate,type Rule,type Snapshot,type Grant} from './scope-state.mjs';
import {ScopeRules,ScopeSummary,GrantList} from './ScopeRules';
const emptyTree:ScopeTree={organizations:[],projects:[],environments:[]};
export function ScopeEditor({user,onClose,onSaved}:{user:{id:string;displayName:string;username:string};onClose:()=>void;onSaved:()=>void}){
 const session=useSession(),resources=useRemote<ScopeTree>('/scope-tree');
 const [baseline,setBaseline]=useState<Snapshot>(),[rows,setRows]=useState<Rule[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[discard,setDiscard]=useState(false),[review,setReview]=useState(false),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<Snapshot>();
 const root=useRef<HTMLFormElement>(null),active=useRef(true),controller=useRef<AbortController>(new AbortController()),key=useRef(crypto.randomUUID()),lock=useRef(false);
 const authority=JSON.stringify([session.user?.id,session.user?.permissions,session.user?.scopes]);const originalAuthority=useRef(authority);
 const tree=resources.data||emptyTree,grants=payload(rows).scopes,dirty=!!baseline&&JSON.stringify(grants)!==JSON.stringify(baseline.grants),errors=validate(rows,tree),authorized=session.can('scope.manage');
 const blocked=busy||loading||!baseline||!authorized||resources.loading||!!resources.error||discard||review||conflict;
 useUnsaved(dirty||busy,()=>setError('仍有未保存的修改，请先完成保存或关闭编辑器。'));
 async function readSnapshot(signal=controller.current.signal){const options={signal};return loadScopeSnapshot(async()=> (await readAllPages(apiRequest,'/users',options)).items.find((u:any)=>u.id===user.id),()=>apiRequest<Grant[]>(`/users/${user.id}/scopes`,options));}
 async function load(){if(lock.current)return;const requestController=controller.current;lock.current=true;setLoading(true);setError('');try{const s=await readSnapshot(requestController.signal);if(active.current&&!requestController.signal.aborted){setBaseline(s);setRows(toDraft(s.grants));}}catch(e){if(active.current&&!requestController.signal.aborted)setError((e as Error).message);}finally{if(controller.current===requestController)lock.current=false;if(active.current&&!requestController.signal.aborted)setLoading(false);}}
 useEffect(()=>{active.current=true;controller.current=new AbortController();lock.current=false;void load();const focus=document.activeElement as HTMLElement|null;root.current?.querySelector<HTMLElement>('button')?.focus();return()=>{active.current=false;controller.current.abort();focus?.focus();};},[]);
 useEffect(()=>{if(authority!==originalAuthority.current||!authorized){controller.current.abort();onClose();}},[authority,authorized]);
 useEffect(()=>{const dialog=root.current;if(!dialog)return;const trap=dialog.querySelector<HTMLElement>('[role=alertdialog]')||dialog;const first=trap.querySelector<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled)');const focus=document.activeElement;if(discard||review||!dialog.contains(focus)||focus===dialog||(focus instanceof HTMLElement&&focus.matches(':disabled'))){(first||dialog).focus();}},[discard,review,busy,conflict,latest,loading]);
 function change(next:Rule[]){setRows(next);setError('');key.current=crypto.randomUUID();}
 function close(){if(busy)return;if(dirty)setDiscard(true);else onClose();}
 async function save(){if(lock.current||!review||discard||conflict||!authorized||!baseline||errors.length||resources.loading||resources.error)return;lock.current=true;setBusy(true);setError('');try{await apiRequest(`/users/${user.id}/scopes`,{method:'PUT',etag:`"${baseline.revision}"`,body:payload(rows),idempotencyKey:key.current,signal:controller.current.signal});if(active.current)onSaved();}catch(e){if(!active.current)return;setReview(false);if(e instanceof ApiError&&[401,403,404].includes(e.status)){onClose();return;}setError(e instanceof ApiError&&e.status===412?'其他操作已更新此用户。你的草稿已保留；读取最新数据后再决定如何合并。':(e as Error).message);setConflict(e instanceof ApiError&&e.status===412);setLatest(undefined);}finally{lock.current=false;if(active.current)setBusy(false);}}
 async function readLatest(){if(lock.current||!authorized)return;lock.current=true;setBusy(true);try{const s=await readSnapshot();if(active.current){setLatest(s);setError('');}}catch(e){if(active.current)setError((e as Error).message);}finally{lock.current=false;if(active.current)setBusy(false);}}
 return <div className="overlay"><form ref={root} className="dialog scope-editor" role="dialog" tabIndex={-1} aria-modal="true" aria-labelledby="scope-editor-title" onSubmit={e=>{e.preventDefault();if(!blocked&&!errors.length)setReview(true);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();if(!busy){if(discard)setDiscard(false);else if(review)setReview(false);else close();}}if(e.key==='Tab'){const trap=e.currentTarget.querySelector('[role=alertdialog]')||e.currentTarget,items=[...trap.querySelectorAll<HTMLElement>('input:not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),a[href]')];if(!items.length){e.preventDefault();root.current?.focus();}else if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(items.length&&!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}>
  <header><div><div className="scope-eyebrow">资源治理 / 数据权限</div><h2 id="scope-editor-title">配置数据范围</h2><p>{baseline?.displayName||user.displayName} <span className="scope-user">@{user.username}</span> · {baseline?'修订 '+baseline.revision:'正在读取'}</p></div><button type="button" className="text-btn" disabled={busy} onClick={close}>关闭</button></header>
  <div className="notice">规则按并集生效。角色决定可执行的功能，数据范围决定可访问的资源；读写范围不会新增角色权限。</div>
  {loading&&<p className="empty" role="status">正在读取用户修订与数据范围…</p>}
  {!loading&&!baseline&&<button type="button" className="btn" onClick={()=>void load()}>重新读取用户范围</button>}
  <Feedback loading={resources.loading} error={resources.error}/>{resources.error&&<button type="button" className="btn" onClick={resources.reload}>重新读取资源</button>}
  {baseline&&<><div className="scope-toolbar"><div><strong>范围规则</strong><span className="badge blue">{rows.length} 条</span></div><button type="button" className="btn" disabled={blocked} onClick={()=>change([...rows,newRule(crypto.randomUUID())])}>＋ 添加范围</button></div><ScopeRules rows={rows} tree={tree} disabled={blocked} onChange={(id,field,value)=>change(rows.map(r=>r.key===id?updateRule(r,field,value):r))} onRemove={id=>change(rows.filter(r=>r.key!==id))}/><ScopeSummary before={baseline.grants} after={grants}/></>}
  {errors.length>0&&!loading&&!conflict&&<div className="error" role="alert"><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}
  {error&&<div className="error" role="alert">{error}</div>}
  {conflict&&<section className="notice scope-conflict" aria-label="并发冲突"><strong>草稿已保留，尚未保存</strong><p>最新内容仅用于比较，读取操作不会覆盖你的输入。</p><button type="button" className="btn" disabled={busy||discard} onClick={()=>void readLatest()}>{busy?'读取中…':'查看最新范围'}</button>{latest&&<><p>服务器修订 {latest.revision} · 以下为服务器当前范围</p><GrantList grants={latest.grants} tree={tree}/><p>保留当前草稿后，相对服务器最新内容的变更：</p><ScopeSummary before={latest.grants} after={grants}/><button type="button" className="btn" disabled={busy||discard} onClick={()=>{setBaseline(latest);setConflict(false);setLatest(undefined);key.current=crypto.randomUUID();}}>保持我的草稿，采用最新修订</button></>}</section>}
  {review&&<section className="notice scope-review" role="alertdialog" aria-modal="true" aria-label="确认数据范围变更"><h3>{grants.length?'确认数据范围变更':'确认撤销全部数据范围'}</h3><p>即将更新 {user.displayName} 的数据范围。请核对保存后生效的规则。</p><ScopeSummary before={baseline!.grants} after={grants}/><GrantList grants={grants} tree={tree}/>{!grants.length&&<p className="scope-warning">此操作将撤销全部业务资源访问范围。请确认目标用户及影响。</p>}<div className="scope-buttons"><button type="button" className="btn" disabled={busy} onClick={()=>setReview(false)}>返回编辑</button><button type="button" className={'btn '+(grants.length?'primary':'danger')} disabled={busy||!authorized||!!errors.length} onClick={()=>void save()}>{busy?'保存中…':grants.length?'确认保存':'确认撤销全部范围'}</button></div></section>}
  {discard&&<section className="notice" role="alertdialog" aria-modal="true" aria-label="放弃未保存的数据范围"><p>这些修改尚未保存。关闭后将放弃当前草稿。</p><button type="button" className="btn" onClick={()=>setDiscard(false)}>继续编辑</button><button type="button" className="btn danger" onClick={onClose}>确认放弃</button></section>}
  <footer><button className="btn primary" disabled={blocked||!!errors.length}>{conflict?'待处理并发冲突':'检查变更并保存'}</button><span>保存前需确认 · 已有不可见范围保留原始 ID</span></footer>
 </form></div>;
}
