import type {Resource,ScopeTree} from '../api/types';
import {summarize,type Rule,type Grant} from './scope-state.mjs';
const levels:Record<string,string>={organization:'整个组织',project:'整个项目',environment:'单个环境'};
export function ScopeSummary({before,after}:{before:Grant[];after:Grant[]}){const s=summarize(before,after);return <div className="scope-summary"><span>新增 <strong>{s.added}</strong></span><span>移除 <strong>{s.removed}</strong></span><span>权限调整 <strong>{s.changed}</strong></span><span>保存后 <strong>{after.length}</strong> 条</span></div>;}
function Options({items,value}:{items:Resource[];value?:string|null}){return <><option value="">请选择</option>{value&&!items.some(x=>x.id===value)&&<option value={value}>不可见 / 已停用 · {value}</option>}{items.map(x=><option key={x.id} value={x.id}>{x.name} · {x.code}</option>)}</>;}
export function GrantList({grants,tree}:{grants:Grant[];tree:ScopeTree}){return <ul className="scope-grant-list">{grants.map((g,i)=><li key={i}><strong>{tree.organizations.find(x=>x.id===g.scope.organizationId)?.name||g.scope.organizationId}</strong> / {g.scope.projectId?(tree.projects.find(x=>x.id===g.scope.projectId)?.name||g.scope.projectId):'全部项目'} / {g.scope.environmentId?(tree.environments.find(x=>x.id===g.scope.environmentId)?.name||g.scope.environmentId):'全部环境'} <span className="badge blue">{g.accessMode==='read_write'?'读写':'只读'}</span></li>)}{!grants.length&&<li>无数据范围；业务资源访问将被撤销。</li>}</ul>;}
export function ScopeRules({rows,tree,disabled,onChange,onRemove}:{rows:Rule[];tree:ScopeTree;disabled:boolean;onChange:(key:string,field:string,value:string)=>void;onRemove:(key:string)=>void}){
 return <fieldset className="scope-rules" disabled={disabled}><legend className="sr-only">数据范围规则</legend>{rows.map((r,i)=>{const n=i+1,projects=tree.projects.filter(p=>p.organizationId===r.scope.organizationId),environments=tree.environments.filter(e=>e.projectId===r.scope.projectId);const hidden=!!r.original&&[r.scope.organizationId,r.scope.projectId,r.scope.environmentId].some((id,index)=>id&&!([tree.organizations,tree.projects,tree.environments][index]).some(x=>x.id===id));return <section className="scope-rule" key={r.key} aria-label={'规则 '+n}><div className="scope-rule-top"><strong>规则 {String(n).padStart(2,'0')}</strong><span>{levels[r.level]}</span><button type="button" className="text-btn scope-remove" aria-label={'移除规则 '+n} onClick={()=>onRemove(r.key)}>移除</button></div><div className="scope-fields"><label>范围层级<select aria-label={'规则 '+n+'范围层级'} value={r.level} onChange={e=>onChange(r.key,'level',e.target.value)}>{Object.entries(levels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>组织<select aria-label={'规则 '+n+'组织'} value={r.scope.organizationId||''} onChange={e=>onChange(r.key,'organizationId',e.target.value)}><Options items={tree.organizations} value={r.scope.organizationId}/></select></label><label>项目<select aria-label={'规则 '+n+'项目'} disabled={disabled||r.level==='organization'||!r.scope.organizationId} value={r.scope.projectId||''} onChange={e=>onChange(r.key,'projectId',e.target.value)}>{r.level==='organization'?<option value="">全部项目</option>:<Options items={projects} value={r.scope.projectId}/>}</select></label><label>环境<select aria-label={'规则 '+n+'环境'} disabled={disabled||r.level!=='environment'||!r.scope.projectId} value={r.scope.environmentId||''} onChange={e=>onChange(r.key,'environmentId',e.target.value)}>{r.level!=='environment'?<option value="">全部环境</option>:<Options items={environments} value={r.scope.environmentId}/>}</select></label><label>访问方式<select aria-label={'规则 '+n+'访问方式'} value={r.accessMode} onChange={e=>onChange(r.key,'accessMode',e.target.value)}><option value="read">只读</option><option value="read_write">读写</option></select></label></div>{r.level!=='environment'&&<p className="scope-hint">{r.level==='organization'?'覆盖该组织全部项目与环境，包括今后新增的资源。':'覆盖该项目全部环境，包括今后新增的环境。'}</p>}{hidden&&<p className="scope-hint">部分资源不可见或已停用。原始 ID 已保留；保存其他规则不会删除此范围。</p>}</section>})}{!rows.length&&<div className="scope-empty">当前草稿无数据范围。保存后，该用户将无法访问业务资源。<br/>角色权限与平台管理权限仍按原有规则生效。</div>}</fieldset>;
}
