export const COMPARISON_TIMEOUT_MS=15000;
export function apiRoute(path){const parts=path.split('/').filter(Boolean),id=parts[1];return {kind:!id?'catalog':parts[2]==='versions'&&parts[3]==='compare'?'compare':parts[2]==='wizard'?'wizard':'detail',id};}
export function comparisonQueryState(query){return {comparisonId:new URLSearchParams(query).get('comparisonId')||undefined};}
export function filterComparison(report,filters={}){return(report?.findings||[]).filter(f=>(!filters.risk||f.risk===filters.risk)&&(!filters.change||f.changeKind===filters.change)&&(!filters.source||f.source===filters.source)&&(!filters.query||[f.operation,f.pointer,f.reason].join(' ').toLowerCase().includes(filters.query.toLowerCase())));}
export function selectComparisonVersion(state,side,id){return {...state,[side]:id,report:undefined,review:undefined};}
export function reviewCommand(report,decision,comment,confirmRisk){const note=(comment||'').trim(),count=[...note].length;if(!report||report.coverage==='Invalid')throw Error('无效报告不能评审');const risk=report.coverage!=='Complete'||report.counts.breaking>0||report.counts.unknown>0;if(!['Reviewed','AcceptedRisk'].includes(decision)||count>2000||decision==='Reviewed'&&risk||decision==='AcceptedRisk'&&(!confirmRisk||count<10))throw Error('请确认全量风险并填写 10–2,000 字说明');return{decision,comment:note||null,confirmRisk};}
export function reviewRetryState(previous,body,makeKey=()=>crypto.randomUUID()){const signature=JSON.stringify(body);return previous?.signature===signature?previous:{signature,key:makeKey(),body};}
export async function loadComparison(request,scopeKey,signal,onResult){try{const value=await request(signal);if(!signal?.aborted){onResult(value,scopeKey);return value;}}catch(e){if(!signal?.aborted)throw e;}}
export async function timedComparison(request,signal,timeout=COMPARISON_TIMEOUT_MS){const controller=new AbortController();let timer,abort;const deadline=new Promise((_,reject)=>{abort=()=>{controller.abort();reject(Error('请求已取消'));};if(signal?.aborted){abort();return;}signal?.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>{controller.abort();reject(Error('比较操作超时，请重试；使用原命令标识核对结果。'));},timeout);});try{return await Promise.race([request(controller.signal),deadline]);}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
export function comparisonRead(path,request,signal,timeout=COMPARISON_TIMEOUT_MS){return timedComparison(controllerSignal=>request(path,{signal:controllerSignal}),signal,timeout);}
export async function resolveReviewHandoff(apiId,reviewId,request,signal,timeout=COMPARISON_TIMEOUT_MS){const page=await comparisonRead(`/apis/${encodeURIComponent(apiId)}/version-comparisons?reviewId=${encodeURIComponent(reviewId)}`,request,signal,timeout);if(signal?.aborted)throw Error('请求已取消');if(page.items?.length!==1)throw Error('评审不可用或已无读取权限');const id=page.items[0].id;const view=await comparisonRead(`/version-comparisons/${id}`,request,signal,timeout);let cursor,review;do{const reviews=await comparisonRead(`/version-comparisons/${id}/reviews${cursor?'?cursor='+encodeURIComponent(cursor):''}`,request,signal,timeout);review=reviews.items?.find(x=>x.id===reviewId);cursor=reviews.nextCursor;}while(!review&&cursor&&!signal?.aborted);if(signal?.aborted)throw Error('请求已取消');if(!review||view.id!==id||view.apiId!==apiId||view.freshness!=='Current'||view.report.coverage==='Invalid'||review.comparisonId!==id||review.apiId!==apiId||review.reportHash!==view.reportHash||review.inputFingerprint!==view.report.inputFingerprint)throw Error('评审已过期或不可用，请重新比较');return{reviewId,comparisonId:id,targetVersionId:view.to.id,locked:true,view,review};}
export function releaseReviewIds(handoff,targetVersionId){if(!handoff)return undefined;if(handoff.targetVersionId!==targetVersionId)throw Error('目标版本变化，请重新比较并评审');return [handoff.reviewId];}

export function reviewDraftState(previous,event){const draft=previous||{comment:'',confirm:false};if(event.type==='open')return{...draft,reportHash:event.reportHash,comment:event.comment??draft.comment,confirm:false};if(event.type==='edit')return{...draft,comment:event.comment};if(event.type==='confirm')return{...draft,confirm:event.confirm};return draft;}
