import fs from 'node:fs';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';import {LocalClient} from './local-client.mjs';const info=JSON.parse(fs.readFileSync('.runtime/browser-e2e.json')),context=JSON.parse(fs.readFileSync(info.directory+'/context.json')),password=fs.readFileSync(info.directory+'/password','utf8');if(!info.project.startsWith('webapi-enterprise-e2e-'))throw new Error('Disposable fixture only');const c=new LocalClient('http://127.0.0.1:5092');await c.login('e2e-admin',password);const action=process.argv[2];
if(action==='revoke-reader'||action==='restore-reader'){const u=(await c.request('/users')).items.find(u=>u.username==='e2e-reader');await c.request(`/users/${u.id}/scopes`,{method:'PUT',headers:{'If-Match':`"${u.revision}"`},body:{scopes:action==='revoke-reader'?[]:[{scope:{organizationId:context.organizationId},accessMode:'read'}]}});console.log('Temporary reader scope '+action);}
if(action==='reader-write'){const reader=new LocalClient(c.base);await reader.login('e2e-reader',password);await assert.rejects(reader.request('/organizations/'+context.organizationId,{method:'PUT',body:{code:'E2E',name:'unauthorized'},headers:{'If-Match':'"1"'}}),e=>e.status===403);console.log('Real direct write denied 403');}
if(action==='concurrent-edit'){const org=await c.request('/organizations/'+context.organizationId);await c.request('/organizations/'+org.id,{method:'PUT',body:{code:org.code,name:'服务器并发保存名称',status:org.status},headers:{'If-Match':`"${org.revision}"`}});console.log('Another real cookie session updated the organization revision');}
if(action==='prepare-publish'){const apiId=context.apiId;const existing=await c.request(`/apis/${apiId}/versions`),n=Math.max(0,...existing.map(v=>Number(v.version.split('.')[0])||0))+1;const v=await c.request(`/apis/${apiId}/versions`,{method:'POST',body:{version:n+'.0.0'}});const routes=await c.request(`/environments/${context.environmentId}/routes`);if(!routes.items.some(r=>r.path==='/orders'))await c.request(`/environments/${context.environmentId}/routes`,{method:'POST',body:{apiVersionId:v.id,routeName:'Orders',path:'/orders',methods:['GET'],clusterId:context.clusterId}});else{const r=routes.items.find(r=>r.path==='/orders');await c.request('/routes/'+r.id,{method:'PUT',body:{...r,apiVersionId:v.id},headers:{'If-Match':`"${r.revision}"`}});}const env=await c.request('/environments/'+context.environmentId),release=await c.request(`/environments/${context.environmentId}/releases`,{method:'POST',body:{baseConfigVersion:env.desiredConfigVersion||0,versionIds:[v.id],resourceRevisions:[{type:'version',id:v.id,revision:v.revision}]}});await c.request(`/releases/${release.id}/submit`,{method:'POST'});fs.writeFileSync('.runtime/browser-release.json',JSON.stringify({id:release.id,versionId:v.id},null,2));console.log('Real submitted release prepared: '+release.id);}
if(action==='self-approve'){const r=JSON.parse(fs.readFileSync('.runtime/browser-release.json'));await assert.rejects(c.request(`/releases/${r.id}/approve`,{method:'POST',body:{comment:'self'}}),e=>e.status===403);console.log('Applicant direct self approval denied 403');}
if(action==='traffic'){const key=fs.readFileSync(info.directory+'/credential','utf8');for(const port of [4186,4187]){const response=await fetch('http://127.0.0.1:'+port+'/orders',{headers:{'X-API-Key':key}}),value=await response.json();assert.equal(response.status,200);assert.equal(value.receivedApiKey,false);console.log(JSON.stringify({port,backendId:value.backendId,deploymentSequence:value.deploymentSequence}));}}
if(action==='publish-next'){const r=JSON.parse(fs.readFileSync('.runtime/browser-release.json'));for(const username of ['e2e-approver','e2e-security']){const reviewer=new LocalClient(c.base);await reviewer.login(username,password);await reviewer.request(`/releases/${r.id}/approve`,{method:'POST',body:{comment:'临时浏览器回滚场景前置审核'}});}await c.request(`/releases/${r.id}/publish`,{method:'POST'});for(let i=0;i<160;i++){const d=await c.request('/releases/'+r.id);if(d.state==='Succeeded'){console.log(JSON.stringify({id:d.id,targetConfigVersion:d.targetConfigVersion,deploymentSequence:d.deploymentSequence}));break;}if(d.state==='Failed')throw new Error('Temporary precondition publish failed');await new Promise(r=>setTimeout(r,200));}}

if(['pause-worker','stop-node-b','resume-worker','resume-node-b'].includes(action)){const env={...process.env,WEBAPI_E2E_PROJECT:info.project,WEBAPI_E2E_DIRECTORY:info.directory,WEBAPI_E2E_RELATIVE_DIR:'.runtime/e2e/'+info.project,WEBAPI_ENVIRONMENT_ID:context.environmentId};const command=action.startsWith('pause')||action.startsWith('stop')?'stop':'start',service=action.includes('worker')?'worker':'gateway-b';execFileSync('docker',['compose','-f','deploy/compose.e2e.yml',command,service],{env,stdio:['ignore','pipe','pipe']});console.log('Temporary '+service+' '+command);}
if(action==='approve-only'){const r=JSON.parse(fs.readFileSync('.runtime/browser-release.json'));for(const username of ['e2e-approver','e2e-security']){const reviewer=new LocalClient(c.base);await reviewer.login(username,password);await reviewer.request(`/releases/${r.id}/approve`,{method:'POST',body:{comment:'临时部分确认场景审核'}});}console.log('Temporary independent approvals ready');}
if(action==='seed-paging'){for(let i=1;i<=51;i++){await c.request(`/projects/${context.projectId}/apis`,{method:'POST',body:{code:'PAGED_'+i,name:'分页 API '+String(i).padStart(3,'0')}});}for(let i=1;i<=50;i++)await c.request(`/environments/${context.environmentId}/clusters`,{method:'POST',body:{name:'分页集群 '+String(i).padStart(3,'0'),loadBalancingPolicy:'RoundRobin',healthCheckEnabled:false,healthCheckPath:'/health',healthCheckIntervalSec:30}});for(let i=1;i<=51;i++)await c.request('/users',{method:'POST',body:{username:'page-user-'+String(i).padStart(3,'0'),displayName:'分页用户 '+i,password}});const apis=await c.request(`/projects/${context.projectId}/apis?page=2`),clusters=await c.request(`/environments/${context.environmentId}/clusters?page=2`),users=await c.request('/users?page=2');fs.writeFileSync('.runtime/review-fixture.json',JSON.stringify({lastApi:apis.items.at(-1),lastCluster:clusters.items.at(-1),lastUser:users.items.at(-1)},null,2));console.log('Disposable >50 API, Cluster and User fixtures created without business grants');}
if(action==='concurrent-user'){const f=JSON.parse(fs.readFileSync('.runtime/review-fixture.json'));const all=await c.request('/users?page=2'),u=all.items.find(u=>u.id===f.lastUser.id);await c.request('/users/'+u.id,{method:'PUT',headers:{'If-Match':`"${u.revision}"`},body:{displayName:'另一会话修改用户',email:u.email,status:u.status}});console.log('Temporary second-page user revision changed');}
