import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {LocalClient} from './local-client.mjs';
const dir=process.env.WEBAPI_E2E_DIRECTORY,project=process.env.WEBAPI_E2E_PROJECT;
if(!project?.startsWith('webapi-enterprise-e2e-')||!dir?.includes(project))throw new Error('Only a disposable named E2E project may be faulted');
const context=JSON.parse(fs.readFileSync(dir+'/context.json')),password=fs.readFileSync(dir+'/password','utf8'),key=fs.readFileSync(dir+'/credential','utf8'),clients=[];for(const name of ['e2e-admin','e2e-approver','e2e-security']){const c=new LocalClient('http://127.0.0.1:5092');await c.login(name,password);clients.push(c);}const[admin,approver,security]=clients,checks=[];
const compose=(...args)=>execFileSync('docker',['compose','-f','deploy/compose.e2e.yml',...args],{env:process.env,encoding:'utf8',stdio:['pipe','pipe','pipe']});
const sql=text=>compose('exec','-T','postgres','psql','-U','webapi','-d','webapi','-v','ON_ERROR_STOP=1','-c',text);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async(fn,seconds=35)=>{const until=Date.now()+seconds*1000;let last;while(Date.now()<until){try{const v=await fn();if(v)return v;}catch(e){last=e;}await sleep(200);}throw last||new Error('Condition did not converge');};
const readRelease=id=>admin.request('/releases/'+id);
const request=async(i=0,path='/orders',credential=key)=>{const r=await fetch(`http://127.0.0.1:${4186+i}${path}`,{headers:{'X-API-Key':credential},signal:AbortSignal.timeout(5000)});return{status:r.status,value:await r.json()};};
const all=async(expected,sequence)=>{for(let i=0;i<2;i++){const r=await request(i);assert.equal(r.status,200);assert.equal(r.value.backendId,expected);if(sequence)assert.equal(r.value.deploymentSequence,sequence);assert.equal(r.value.receivedApiKey,false);}};
async function draft(backend,extra=[]){const versions=await admin.request(`/apis/${context.apiId}/versions`),n=Math.max(0,...versions.map(v=>Number(v.version.split('.')[0])||0))+1,v=await admin.request(`/apis/${context.apiId}/versions`,{method:'POST',body:{version:n+'.0.0'}}),cluster=await admin.request('/clusters/'+context.clusterId),dst=cluster.destinations[0];await admin.request('/destinations/'+dst.id,{method:'PUT',body:{name:dst.name,address:`http://backend-${backend.toLowerCase()}:8080/`,weight:1,enabled:true},headers:{'If-Match':`"${dst.revision}"`}});const routes=await admin.request(`/environments/${context.environmentId}/routes`),route=routes.items.find(r=>r.path==='/orders');await admin.request('/routes/'+route.id,{method:'PUT',body:{...route,apiVersionId:v.id},headers:{'If-Match':`"${route.revision}"`}});const env=await admin.request('/environments/'+context.environmentId),r=await admin.request(`/environments/${context.environmentId}/releases`,{method:'POST',body:{baseConfigVersion:env.desiredConfigVersion||0,versionIds:[v.id,...extra.map(x=>x.id)],resourceRevisions:[v,...extra].map(x=>({type:'version',id:x.id,revision:x.revision}))}});await approve(r.id);return r;}
async function approve(id){await admin.request(`/releases/${id}/submit`,{method:'POST'});await approver.request(`/releases/${id}/approve`,{method:'POST',body:{comment:'临时故障验收审核'}});await security.request(`/releases/${id}/approve`,{method:'POST',body:{comment:'独立安全审核'}});}
async function publish(backend,extra=[]){const r=await draft(backend,extra);await admin.request(`/releases/${r.id}/publish`,{method:'POST'});return wait(async()=>{const d=await readRelease(r.id);if(d.state==='Failed')throw new Error('Unexpected failed release');return d.state==='Succeeded'&&d;});}
try{
 const start=(await admin.request(`/environments/${context.environmentId}/releases`)).items.find(r=>r.state==='Succeeded');assert(start);await all('B',start.deploymentSequence);
 // Kill the notification connection; node B is configured without Redis notifications, so polling is authoritative there.
 compose('exec','-T','redis','redis-cli','CLIENT','KILL','TYPE','pubsub');const polled=await publish('A');await all('A',polled.deploymentSequence);checks.push({name:'NotificationLossRecoveredByPoll',result:'passed',sequence:polled.deploymentSequence});
 // Non-transactional nextval drops the first ACK insert only. Retry must apply no fake node event.
 sql("CREATE SEQUENCE e2e_ack_attempt; CREATE FUNCTION e2e_drop_ack() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF nextval('e2e_ack_attempt')=1 THEN RAISE EXCEPTION 'deliberate lost ACK'; END IF; RETURN NEW; END; $$; CREATE TRIGGER e2e_drop_ack BEFORE INSERT ON gateway_acks FOR EACH ROW EXECUTE FUNCTION e2e_drop_ack();");const ackRetry=await publish('B');sql('DROP TRIGGER e2e_drop_ack ON gateway_acks; DROP FUNCTION e2e_drop_ack(); DROP SEQUENCE e2e_ack_attempt;');assert.equal(ackRetry.targets.filter(t=>t.acknowledged).length,2);checks.push({name:'LostAckRetriedExactlyOncePerNodeFact',result:'passed',sequence:ackRetry.deploymentSequence});
 compose('exec','-T','gateway-a','chmod','555','/lkg');const denied=await draft('A');await admin.request(`/releases/${denied.id}/publish`,{method:'POST'});const failed=await wait(async()=>{const r=await readRelease(denied.id);return r.state==='Failed'&&r;});assert.equal((await request(0)).value.backendId,'B');assert(failed.errors.length);assert(failed.targets.some(t=>t.errorCode==='lkg_write_denied'));compose('exec','-T','gateway-a','chmod','700','/lkg');const recovery=await admin.request(`/releases/${failed.id}/retry`,{method:'POST'}),recovered=await wait(async()=>{const r=await readRelease(recovery.id);return r.state==='Succeeded'&&r;});assert.equal((await readRelease(failed.id)).state,'Failed');assert(recovered.deploymentSequence>failed.deploymentSequence);await all('A',recovered.deploymentSequence);checks.push({name:'ReadOnlyLkgKeepsOldTrafficAndIndependentRetryRecovers',result:'passed',failedSequence:failed.deploymentSequence,recoverySequence:recovered.deploymentSequence});
 // Add a routed API without a consumer grant, and a short-lived credential to the real runtime artifact.
 const other=await admin.request(`/projects/${context.projectId}/apis`,{method:'POST',body:{code:'UNGRANTED',name:'未授权验收 API'}}),otherV=await admin.request(`/apis/${other.id}/versions`,{method:'POST',body:{version:'1.0.0'}});await admin.request(`/environments/${context.environmentId}/routes`,{method:'POST',body:{apiVersionId:otherV.id,routeName:'ungranted',path:'/ungranted',methods:['GET'],clusterId:context.clusterId}});const expires=Date.now()+10000,short=await admin.request(`/applications/${context.applicationId}/credentials`,{method:'POST',body:{validFrom:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(expires).toISOString()}});const auth=await publish('B',[otherV]);assert.equal((await request(0,'/ungranted')).status,403);await sleep(Math.max(0,expires-Date.now()+100));assert.equal((await request(0,'/orders',short.apiKey)).status,401);await all('B',auth.deploymentSequence);checks.push({name:'RealPublishedKeyExpiryAndCrossApiDenial',result:'passed'});
 // Cache poisoning while authoritative services are stopped: neither bad bytes nor a foreign environment may replace LKG.
 const nodes=(await admin.request(`/environments/${context.environmentId}/gateway-nodes`)).items;const internal=await fetch(`http://127.0.0.1:5092/internal/v1/nodes/${nodes.find(n=>n.nodeName==='gateway-a').id}/desired`,{headers:{Authorization:'Bearer '+fs.readFileSync(dir+'/node-a','utf8')}});assert.equal(internal.status,200);const desired=await internal.json(),redisKey=`webapi:runtime:{${context.environmentId}}:desired`;compose('stop','worker','control-plane');
 const poison=(env,payload)=>{const envelope={...desired.envelope,deploymentSequence:desired.envelope.deploymentSequence+10,payloadHash:env==='hash'?'0'.repeat(64):crypto.createHash('sha256').update(payload).digest('hex'),sizeBytes:payload.length};compose('exec','-T','redis','redis-cli','HSET',redisKey,'sequence',String(envelope.deploymentSequence),'envelope',JSON.stringify(envelope));execFileSync('docker',['compose','-f','deploy/compose.e2e.yml','exec','-T','redis','redis-cli','-x','HSET',redisKey,'payload'],{env:process.env,input:payload,stdio:['pipe','pipe','pipe']});};poison('hash',Buffer.from(desired.payload,'base64'));await sleep(3500);await all('B',auth.deploymentSequence);const foreign=JSON.parse(Buffer.from(desired.payload,'base64'));foreign.environmentId=crypto.randomUUID();poison('foreign',Buffer.from(JSON.stringify(foreign)));await sleep(3500);await all('B',auth.deploymentSequence);checks.push({name:'BadHashAndForeignEnvironmentKeepOldRuntime',result:'passed'});
 compose('stop','redis');await all('B',auth.deploymentSequence);compose('restart','gateway-a');await wait(async()=>{const r=await request(0);return r.status===200&&r.value.backendId==='B'&&r.value.deploymentSequence===auth.deploymentSequence;},20);await all('B',auth.deploymentSequence);checks.push({name:'ActualGatewayProcessRestartWhileControlPlaneAndRedisDownRestoresLkg',result:'passed',sequence:auth.deploymentSequence});compose('start','redis');compose('exec','-T','redis','redis-cli','DEL',redisKey);compose('start','control-plane','worker');await wait(async()=>{const r=await fetch('http://127.0.0.1:5092/health/live');return r.ok;});await wait(async()=>{const n=(await admin.request(`/environments/${context.environmentId}/gateway-nodes`)).items;return n.every(x=>!x.offline&&x.currentDeploymentSequence===auth.deploymentSequence);},20);
 const ready=await draft('A'),rollback=await admin.request(`/releases/${auth.id}/rollback`,{method:'POST',body:{targetConfigVersion:1}});await approve(rollback.id);const raced=await Promise.allSettled([admin.request(`/releases/${ready.id}/publish`,{method:'POST'}),admin.request(`/releases/${rollback.id}/publish`,{method:'POST'})]);assert.equal(raced.filter(r=>r.status==='fulfilled').length,1);assert.equal(raced.find(r=>r.status==='rejected').reason.status,409);const winner=raced.find(r=>r.status==='fulfilled').value;const result=await wait(async()=>{const r=await readRelease(winner.id);return r.state==='Succeeded'&&r;});checks.push({name:'ConcurrentPublishRollbackOnlyOneWinsDesired',result:'passed',sequence:result.deploymentSequence});
}catch(e){fs.mkdirSync('docs/evidence/core-loop',{recursive:true});fs.writeFileSync('docs/evidence/core-loop/faults.json',JSON.stringify({project,checks,failure:e.message,complete:false},null,2));throw e;}finally{try{compose('exec','-T','gateway-a','chmod','700','/lkg');compose('start','redis','control-plane','worker');}catch{}}
fs.mkdirSync('docs/evidence/core-loop',{recursive:true});fs.writeFileSync('docs/evidence/core-loop/faults.json',JSON.stringify({architecture:'Linux '+compose('exec','-T','gateway-a','uname','-m').trim(),checks,complete:true},null,2));console.log('Real container fault checks passed: '+checks.length);
