import {useEffect,useState} from 'react';
import {parsePublicJwksFile} from './advanced-policy-state.mjs';
type Props={config:any;change:(config:any)=>void;disabled:boolean;applications?:any[];onValidityChange?:(valid:boolean)=>void;input?:{raw:string;valid:boolean;error:string};onInputChange?:(input:{raw:string;valid:boolean;error:string},jwks?:any)=>void};
export function JwtPolicyFields({config,change,disabled,applications=[],onValidityChange,input,onInputChange}:Props){
 const [local,setLocal]=useState<any>();const raw=input?.raw??local?.raw??JSON.stringify(config.jwks,null,2),error=input?.error??local?.error??'';
 useEffect(()=>{onValidityChange?.(input?.valid??local?.valid??true);},[input?.valid,local?.valid,onValidityChange]);
 const record=(value:{raw:string;valid:boolean;error:string},jwks?:any)=>{if(onInputChange)onInputChange(value,jwks);else{setLocal(value);if(jwks)update('jwks',jwks);}};
 const update=(key:string,value:any)=>change({...config,[key]:value});
 function parse(value:string){try{const jwks=parsePublicJwksFile(value,config.allowedAlgorithms);record({raw:value,valid:true,error:''},jwks);}catch(e){record({raw:value,valid:false,error:(e as Error).message});}}
 const toggle=(key:string,value:string,checked:boolean)=>update(key,checked?[...config[key],value]:config[key].filter((x:string)=>x!==value));
 return <div className="advanced-policy-fields"><p className="notice">固定公钥校验 · 网关离线验证签名，不访问 Issuer 或远程取钥地址。浏览器只检查结构；保存后仍须审批发布。</p><fieldset className="form-grid" disabled={disabled}>
 <label>Issuer *<input value={config.issuer} maxLength={512} onChange={e=>update('issuer',e.target.value)}/><small>精确匹配；开发环境的 HTTP 发行方由服务端白名单校验</small></label>
 <label>Audience *<textarea value={config.audiences.join('\n')} rows={3} onChange={e=>update('audiences',e.target.value.split('\n'))}/><small>每行一个精确值，最多 8 项</small></label>
 <label>允许算法<div>{['RS256','ES256'].map(v=><label key={v}><input type="checkbox" checked={config.allowedAlgorithms.includes(v)} onChange={e=>toggle('allowedAlgorithms',v,e.target.checked)}/>{v}</label>)}</div></label>
 <label>允许令牌类型<div>{['JWT','at+jwt'].map(v=><label key={v}><input type="checkbox" checked={config.allowedTokenTypes.includes(v)} onChange={e=>toggle('allowedTokenTypes',v,e.target.checked)}/>{v}</label>)}</div></label>
 <label>时钟容差 / 秒<input type="number" min={0} max={120} value={config.clockSkewSeconds} onChange={e=>update('clockSkewSeconds',Number(e.target.value))}/></label>
 <label>最大令牌有效期 / 秒<input type="number" min={60} max={86400} value={config.maxTokenLifetimeSeconds} onChange={e=>update('maxTokenLifetimeSeconds',Number(e.target.value))}/></label>
 <label>应用 Claim<input value={config.applicationClaim} maxLength={64} onChange={e=>update('applicationClaim',e.target.value)}/></label>
 <label>转发 Bearer<input type="checkbox" checked={config.forwardBearer} onChange={e=>update('forwardBearer',e.target.checked)}/><small>仅明确启用后将原令牌交给后端；默认移除。需要确认后端可信。</small></label>
 </fieldset><fieldset disabled={disabled}><legend>公开 JWKS</legend><label>公开 JWKS JSON<textarea aria-label="公开 JWKS JSON" className="code" rows={9} value={raw} aria-invalid={!!error} onChange={e=>parse(e.target.value)}/></label><label>导入本地公钥文件<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>32768)throw Error('公开 JWKS 文件不得超过 32KiB');const value=await file.text();const jwks=parsePublicJwksFile(value,config.allowedAlgorithms);record({raw:JSON.stringify(jwks,null,2),valid:true,error:''},jwks);}catch(error){record({raw,valid:false,error:(error as Error).message});}e.target.value='';}}/></label><small>仅接收 1–8 个公开签名密钥。kid：{config.jwks.keys.map((k:any)=>k.kid).join('、')||'尚未配置'}</small>{error&&<p className="error" role="alert">{error}</p>}</fieldset>
 <fieldset disabled={disabled}><legend>应用映射</legend><p>只列出当前组织 / 项目可读应用；精确 Claim 值映射到受授权的应用。</p>{config.applicationMappings.map((m:any,i:number)=><div className="form-grid" key={i}><label>Claim 值 {i+1}<input maxLength={256} value={m.claimValue} onChange={e=>update('applicationMappings',config.applicationMappings.map((x:any,n:number)=>n===i?{...x,claimValue:e.target.value}:x))}/></label><label>应用 {i+1}<select value={m.applicationId} onChange={e=>update('applicationMappings',config.applicationMappings.map((x:any,n:number)=>n===i?{...x,applicationId:e.target.value}:x))}><option value="">请选择可读应用</option>{!applications.some(a=>a.id===m.applicationId)&&m.applicationId&&<option value={m.applicationId}>不可读取映射应用 · {m.applicationId}</option>}{applications.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button type="button" className="text-btn" onClick={()=>update('applicationMappings',config.applicationMappings.filter((_:any,n:number)=>n!==i))}>移除映射 {i+1}</button></div>)}<button type="button" className="btn" disabled={config.applicationMappings.length>=128} onClick={()=>update('applicationMappings',[...config.applicationMappings,{claimValue:'',applicationId:''}])}>添加应用映射</button></fieldset></div>;
}
