import {advancedPolicyReview} from './advanced-policy-state.mjs';
import {useState,useRef,useEffect} from 'react';import {useWorkspace,navigate} from '../Shell';import {useSession} from '../auth/SessionProvider';import {useRemote,Feedback,Details} from '../ui';import {apiRequest} from '../api/client';import {readAllPages} from '../api/paging.mjs';
export function PolicyReleaseReview({policyId}:{policyId:string}){
 const ws=useWorkspace(),{can,user}=useSession(),refs=useRemote<any>(`/policies/${policyId}/references`,0,true),[environmentId,setEnvironment]=useState(ws.environmentId),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<any>(),[baseline,setBaseline]=useState<any[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[options,setOptions]=useState<any[]>([]);
 const env=ws.tree.environments.find(e=>e.id===environmentId),project=ws.tree.projects.find(p=>p.id===env?.projectId),scope=project?{organizationId:project.organizationId!,projectId:project.id,environmentId}:undefined,allowed=!!scope&&can('release.create',scope,true);
 const epoch=useRef(0),mounted=useRef(true),previous=useRef('');const identity=JSON.stringify([policyId,environmentId,user?.id,user?.permissions,user?.scopes]);if(previous.current!==identity){previous.current=identity;epoch.current++;}useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;epoch.current++;};},[]);useEffect(()=>{setPreview(undefined);setBaseline(null);setReady(false);setOptions([]);setSelected([]);setBusy(false);},[identity]);const current=(generation:number)=>mounted.current&&generation===epoch.current;
 function invalidate(){epoch.current++;setPreview(undefined);setBaseline(null);setBusy(false);setError('');}
 async function prepare(){if(!allowed)return;const generation=++epoch.current;setBusy(true);setError('');setPreview(undefined);setReady(false);try{const apiIds=[...new Set<string>((refs.data?.items||[]).filter((r:any)=>r.referenceKind==='Working'&&r.environmentId===environmentId&&r.apiId).map((r:any)=>r.apiId))],routes=await readAllPages(apiRequest,`/environments/${environmentId}/routes`),all=(await Promise.all(apiIds.map(id=>apiRequest<any[]>(`/apis/${id}/versions`)))).flat(),ids=new Set(routes.items.map((r:any)=>r.apiVersionId)),candidates=all.filter(v=>ids.has(v.id));if(current(generation)){setOptions(candidates);setSelected(candidates.map(v=>v.id));setReady(true);}}catch(e){if(current(generation))setError((e as Error).message);}finally{if(current(generation))setBusy(false);}}
 async function readPreview(){if(!allowed||!selected.length)return;const generation=++epoch.current;setBusy(true);setError('');setPreview(undefined);setBaseline(null);try{const versionIds=[...selected],environment=await apiRequest<any>(`/environments/${environmentId}`),base=environment.desiredConfigVersion||0,result=await apiRequest<any>(`/environments/${environmentId}/releases/preview`,{method:'POST',body:{baseConfigVersion:base,versionIds}});let baselinePolicies:any[]|null=null;if(base&&scope&&can('gateway.config.read',scope)){try{const snapshot=await apiRequest<any>(`/environments/${environmentId}/snapshots/${base}`);baselinePolicies=snapshot.policies;}catch{ /* an unreadable baseline is explicitly unknown */ }}else if(!base)baselinePolicies=[];if(current(generation)){setBaseline(baselinePolicies);setPreview({base,versionIds,candidate:result});}}catch(e){if(current(generation))setError((e as Error).message);}finally{if(current(generation))setBusy(false);}}
 async function create(){if(!allowed||!preview||busy)return;const generation=++epoch.current;setBusy(true);setError('');try{const r=await apiRequest<any>(`/environments/${environmentId}/releases`,{method:'POST',body:{baseConfigVersion:preview.base,versionIds:preview.versionIds,resourceRevisions:preview.candidate.resourceRevisions},idempotencyKey:crypto.randomUUID()});if(current(generation))navigate('/releases/'+r.id);}catch(e){if(current(generation))setError((e as Error).message);}finally{if(current(generation))setBusy(false);}}
 return <div className="card details"><h3>提交发布 · 目标环境</h3><p className="notice">只发布勾选的 API 版本。未选引用继续运行旧修订；新限流修订重建额度，新的熔断修订或后端集群重建节点状态。审批和运行结果由既有发布流程确认。</p><Feedback {...refs}/><div className="filter-bar"><label>目标环境<select value={environmentId} onChange={e=>{invalidate();setEnvironment(e.target.value);setReady(false);setOptions([]);setSelected([]);}}>{ws.tree.environments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{allowed&&<button type="button" className="btn" disabled={busy||refs.loading||!!refs.error||!refs.data||!env} onClick={()=>void prepare()}>加载受影响 API 版本</button>}</div>{!allowed&&<p className="notice">目标环境无 release.create 权限。</p>}{ready&&allowed&&<><div className="form-grid">{options.map(v=><label key={v.id}><input type="checkbox" checked={selected.includes(v.id)} onChange={e=>{invalidate();setSelected(s=>e.target.checked?[...s,v.id]:s.filter(id=>id!==v.id));}}/>{v.version} · {v.status} · {v.id}</label>)}</div><p>当前环境未选版本 {options.filter(v=>!selected.includes(v.id)).length} 个；其他环境可见引用 {(refs.data?.items||[]).filter((r:any)=>r.environmentId!==environmentId).length} 条。</p><button type="button" className="btn" disabled={busy||!selected.length} onClick={()=>void readPreview()}>读取完整发布 Review</button></>}{preview&&allowed&&<><AdvancedPolicyReview policies={preview.candidate.policies||[]} baselinePolicies={baseline}/><Details value={preview.candidate}/><button type="button" className="btn primary" disabled={busy} onClick={()=>void create()}>确认 Review，创建发布草稿</button></>}{error&&<div className="error" role="alert">{error}</div>}</div>;
}

export function AdvancedPolicyReview({policies,baselinePolicies=null}:{policies:any[];baselinePolicies?:any[]|null}){const rows=advancedPolicyReview(policies,{baselinePolicies});return <section className="advanced-policy-review"><h4>高级流量策略 Review</h4><p className="notice">创建发布草稿后仍须按目标环境的审批流程提交、审批并发布。结构检查不等于签名验证或运行生效。</p>{rows.length?rows.map(r=><div key={r.id} className="details">{r.error?<p className="error">{r.error}</p>:r.type==='authentication'?<><strong>JWT · 固定公钥</strong><p>kid：{r.kids.join('、')||'无'} · 应用映射 {r.mappingCount} 项</p><p>{r.addedKids===null?'基线不可读取，密钥增删尚未确认':`新增 kid：${r.addedKids.join('、')||'无'}；移除 kid：${r.removedKids.join('、')||'无'}`}</p><p>转发 Bearer：{r.forwardBearer?'启用，需确认后端信任与令牌暴露风险':'关闭'}</p></>:r.type==='retry'?<p>重试：最多 {r.maxAttempts} 次物理尝试（包含首次），受路由总超时和安全重放条件约束。</p>:<p>缓存：TTL 上限 {r.ttlSeconds} 秒；本次发布 / 回滚将缓存冷启动，不保证业务即时一致。</p>}</div>):<p>候选配置无启用的 JWT / 重试 / 缓存策略。</p>}</section>;}
