import {validateAdvancedPolicyDraft,changeAuthenticationMode} from './advanced-policy-state.mjs';
export const policyTypes={authentication:'认证',timeout:'超时',rate_limit:'限流',circuit_breaker:'熔断',retry:'重试',cache:'缓存'};
export function initialPolicyDraft(type){return structuredClone({authentication:{mode:'ApiKey'},retry:{maxAttempts:3,perAttemptTimeoutMs:1000,baseDelayMs:100,maxDelayMs:1000,jitterPercent:20,retryStatusCodes:[502,503,504],retryConnectionFailures:true},cache:{ttlSeconds:60,maxEntryBytes:262144,varyHeaders:['Accept','Accept-Language','Accept-Encoding'],identityPartition:'VerifiedIdentity',redisFailureMode:'Bypass'},timeout:{timeoutMs:30000},rate_limit:{algorithm:'TokenBucket',keyBy:'ApplicationRoute',refillTokens:1000,windowMs:1000,burst:1500,redisFailureMode:'Reject'},circuit_breaker:{samplingWindowMs:30000,minimumRequests:20,failureRatio:0.5,openDurationMs:30000,halfOpenMaxRequests:1,halfOpenSuccesses:3,failureStatusCodes:Array.from({length:100},(_,i)=>500+i),countTimeouts:true,countConnectionFailures:true}}[type]??{});}
export function validatePolicyDraft(draft,scope){
 if(!policyTypes[draft.type])return '该类型尚未开放';const name=draft.name?.trim();if(!name||name.length>128||!draft.id&&name.startsWith('RouteAuth-'))return '名称应为 1–128 字符，不能使用 RouteAuth- 系统前缀';const c=draft.config;if(!c||typeof c!=='object'||Array.isArray(c))return '配置必须是对象';if(new TextEncoder().encode(JSON.stringify(c)).length>32768)return '配置不能超过 32KiB';
 if(['retry','cache'].includes(draft.type)||draft.type==='authentication'&&c.mode==='JWT')return validateAdvancedPolicyDraft(draft,scope);
 const defaults=initialPolicyDraft(draft.type);if(Object.keys(c).some(k=>!(k in defaults))||Object.keys(defaults).some(k=>!(k in c)))return '配置包含未知或缺失字段';
 const int=(key,min,max)=>Number.isInteger(c[key])&&c[key]>=min&&c[key]<=max;
 if(draft.type==='authentication'&&!['ApiKey','Anonymous'].includes(c.mode))return '请选择 ApiKey 或 Anonymous';
 if(draft.type==='timeout'&&!int('timeoutMs',1,300000))return '超时范围 1–300000ms';
 if(draft.type==='rate_limit'&&(c.algorithm!=='TokenBucket'||!['Route','ApplicationRoute'].includes(c.keyBy)||!['Reject','Allow'].includes(c.redisFailureMode)||!int('refillTokens',1,1000000)||!int('windowMs',10,600000)||!int('burst',1,1000000)||c.burst<c.refillTokens||c.burst*c.windowMs>c.refillTokens*3600000))return '限流配置无效：容量不少于补充量，满桶补充不超过 1 小时';
 if(draft.type==='circuit_breaker'&&(!int('samplingWindowMs',1000,300000)||c.samplingWindowMs%1000!==0||!int('minimumRequests',1,1000000)||!Number.isFinite(c.failureRatio)||c.failureRatio<=0||c.failureRatio>1||!int('openDurationMs',1000,300000)||!int('halfOpenMaxRequests',1,10)||!int('halfOpenSuccesses',1,100)||!Array.isArray(c.failureStatusCodes)||c.failureStatusCodes.length>100||new Set(c.failureStatusCodes).size!==c.failureStatusCodes.length||c.failureStatusCodes.some(x=>!Number.isInteger(x)||x<500||x>599)||typeof c.countTimeouts!=='boolean'||typeof c.countConnectionFailures!=='boolean'||!c.failureStatusCodes.length&&!c.countTimeouts&&!c.countConnectionFailures))return '熔断配置无效：检查窗口、比例、探测数与故障来源';return null;
}
export function policyEditorReducer(state,event){switch(event.type){case 'loaded':return event.scope===state.scope&&!state.dirty?{...state,draft:event.draft,dirty:false,conflict:false}:state;case 'authenticationMode':return changeAuthenticationMode(state,event.mode,event.confirmed);case 'cancelMode':return {...state,pendingMode:null};case 'change':return {...state,draft:{...state.draft,...event.value},dirty:true};case 'conflict':return {...state,conflict:true};case 'merge':return {...state,draft:{...state.draft,versionNo:event.versionNo},conflict:false};case 'saved':return {...state,draft:event.draft,dirty:false,conflict:false};default:return state;}}
export function copyDraft(source){return {name:source.name+' 副本',type:source.type,config:structuredClone(source.config),enabled:source.enabled};}
export function refreshReview(review,revisions,confirmed){return confirmed?{...review,resourceRevisions:revisions,preconditionsCurrent:true}:review;}
export function policyFieldErrors(type,c){const errors={},bounds=type==='timeout'?{timeoutMs:[1,300000]}:type==='rate_limit'?{refillTokens:[1,1000000],windowMs:[10,600000],burst:[1,1000000]}:type==='circuit_breaker'?{samplingWindowMs:[1000,300000],minimumRequests:[1,1000000],openDurationMs:[1000,300000],halfOpenMaxRequests:[1,10],halfOpenSuccesses:[1,100]}:{};for(const [key,[min,max]]of Object.entries(bounds))if(!Number.isInteger(c[key])||c[key]<min||c[key]>max)errors[key]=`须为 ${min}–${max} 的整数`;if(type==='rate_limit'){if(c.burst<c.refillTokens)errors.burst='容量不得小于窗口补充令牌数';else if(c.burst*c.windowMs>c.refillTokens*3600000)errors.burst='满桶补充时间不得超过一小时';}if(type==='circuit_breaker'){if(c.samplingWindowMs%1000!==0)errors.samplingWindowMs='窗口须为 1000ms 的整数倍';if(!Number.isFinite(c.failureRatio)||c.failureRatio<=0||c.failureRatio>1)errors.failureRatio='失败比例须大于 0 且不超过 1';if(!Array.isArray(c.failureStatusCodes)||c.failureStatusCodes.length>100||new Set(c.failureStatusCodes).size!==c.failureStatusCodes.length||c.failureStatusCodes.some(x=>!Number.isInteger(x)||x<500||x>599))errors.failureStatusCodes='最多 100 个不重复的 500–599 状态码';else if(!c.failureStatusCodes.length&&!c.countTimeouts&&!c.countConnectionFailures)errors.failureStatusCodes='至少开启一种失败来源';}return errors;}
export function policyListQuery(filters){return new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==''&&value!==null&&value!==undefined));}
