<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../WebApi.HttpSecurity/WebApi.HttpSecurity.csproj"/><PackageReference Include="Yarp.ReverseProxy"/><PackageReference Include="Microsoft.IdentityModel.JsonWebTokens"/><PackageReference Include="Microsoft.IdentityModel.Tokens"/><PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/><PackageReference Include="OpenTelemetry.Instrumentation.Http"/><ProjectReference Include="../WebApi.Infrastructure/WebApi.Infrastructure.csproj"/></ItemGroup></Project>
