<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><PackageReference Include="Yarp.ReverseProxy"/><PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/><PackageReference Include="OpenTelemetry.Instrumentation.Http"/><ProjectReference Include="../WebApi.Infrastructure/WebApi.Infrastructure.csproj"/></ItemGroup></Project>
