import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {loadState,ownedDirectory,safeFile} from '../runtime/state.mjs';import {loadRelease} from '../runtime/lifecycle.mjs';import {docker,inspectResources} from '../runtime/docker.mjs';import {validateCloneOwnership} from '../contracts/evidence.mjs';import {validateGatewayPolicyEvidence} from './evidence.mjs';
export async function runGatewayPolicyAcceptance({revision,imageId,directory,cloneDirectory,privateValues=[]}){
 await ownedDirectory(directory);const state=await loadState(cloneDirectory),resources=await inspectResources(state);validateCloneOwnership(state,resources,cloneDirectory);const release=await loadRelease(path.join(cloneDirectory,'release.json'));assert.equal(release.sourceRevision,revision);assert.equal(release.imageId,imageId);const apps=resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b'].includes(r.Config?.Labels?.['com.docker.compose.service']));assert.equal(apps.length,5);
 for(const app of apps){assert.equal(app.Image,imageId);assert.equal(app.State.Running,true);const image=JSON.parse((await docker(['image','inspect',app.Image])).stdout)[0];assert.equal(image.Config.Labels['org.opencontainers.image.revision'],revision);}
 await safeFile(path.join(directory,'acceptance-input.json'));const proof=JSON.parse(await fs.readFile(path.join(directory,'acceptance-input.json'),'utf8')),files=[];
 for(const artifact of proof.artifacts){const parts=artifact.path.split('/');assert(!parts.some(p=>!p||p==='..'||p==='.')&&!path.isAbsolute(artifact.path));for(let n=0;n<parts.length;n++)assert(!(await fs.lstat(path.join(directory,'public',...parts.slice(0,n+1)))).isSymbolicLink());files.push({path:artifact.path,type:'file',content:await fs.readFile(path.join(directory,'public',...parts))});}
 const image=JSON.parse(String(files.find(f=>f.path===proof.materialArtifacts.images).content));assert.deepEqual(image.resources.map(r=>r.Id).sort(),apps.map(r=>r.Id).sort());return validateGatewayPolicyEvidence(proof,files,{revision,imageId,privateValues});
}
if(process.argv[1]===import.meta.filename){const[revision,imageId,directory,cloneDirectory]=process.argv.slice(2);console.log(JSON.stringify(await runGatewayPolicyAcceptance({revision,imageId,directory,cloneDirectory}),null,2));}
