import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {assertPublicFiles,validateCloneOwnership} from '../contracts/evidence.mjs';import {isPrivateRuntimeArtifact} from './protection.mjs';
export const digest=value=>createHash('sha256').update(value).digest('hex');
export const requiredScenarioChecks=['jwt-negative','identity-partition','retry-actual-calls','uncertain-send-not-retried','rate-once','half-open-once','scope-isolation','redis-fault','two-level-publish','rollback','downgrade-gate'];
export const requiredUiActions=['create','edit','jwks-file','mapping','six-bindings','dirty-escape-focus','explicit-enter','scope-late','revision-412','readonly','release-review','logs-trace'];
export function parseSuiteLog(name,log){if(['console','runtime'].includes(name)){const read=label=>{const m=log.match(new RegExp('^ℹ '+label+' (\\d+)\\s*$','m'));assert(m,'缺少 Node 测试统计：'+label);return Number(m[1]);};return {passed:read('pass'),failed:read('fail'),skipped:read('skipped')};}const matches=[...log.matchAll(/Passed!\s*-\s*Failed:\s*(\d+),\s*Passed:\s*(\d+),\s*Skipped:\s*(\d+),\s*Total:\s*(\d+)/g)];assert.equal(matches.length,1,'需要单个 .NET 测试汇总');const [,failed,passed,skipped,total]=matches[0].map(Number);assert.equal(failed+passed+skipped,total);assert.equal(log.split('\n').filter(line=>/^\s*Passed\s+WebApi\./.test(line)).length,passed,'缺少每项真实 .NET 通过记录');return{passed,failed,skipped};}
export function validateGatewayPolicyEvidence(proof,files,{revision,imageId,privateValues=[]}={}){
 assert.match(revision??'',/^[a-f0-9]{40}$/);assert.match(imageId??'',/^sha256:[a-f0-9]{64}$/);assert.equal(proof.sourceRevision,revision);assert.equal(proof.imageId,imageId);assert.equal(proof.stage,'pre-install');assertPublicFiles(files,{secrets:privateValues});assert(files.every(f=>!isPrivateRuntimeArtifact(f.path)),'私有运行材料不可公开');const indexed=new Map(files.map(f=>[f.path,f]));assert.equal(indexed.size,files.length);assert.equal(proof.artifacts?.length,files.length);for(const a of proof.artifacts){assert(indexed.has(a.path));assert.equal(digest(indexed.get(a.path).content),a.sha256,'证据 SHA 不一致');const text=String(indexed.get(a.path).content);assert(!/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/.test(text),'公开材料疑似包含原始 JWT');}const read=file=>{assert(indexed.has(file),'缺少材料 '+file);return JSON.parse(String(indexed.get(file).content));};const identity=value=>{assert.equal(value.sourceRevision,revision,'材料来自旧提交');assert.equal(value.imageId,imageId,'材料来自旧镜像');};
 assert.equal(proof.suites?.length,5);assert.equal(new Set(proof.suites.map(s=>s.name)).size,5);for(const name of ['domain','integration','gateway','console','runtime']){const wrapper=proof.suites.find(s=>s.name===name);assert(wrapper);const actual=read(wrapper.artifact);for(const key of ['name','sourceRevision','passed','failed','skipped','exitCode','originalLogSha256','log'])assert.deepEqual(actual[key],wrapper[key]);assert.equal(actual.sourceRevision,revision);assert.equal(actual.exitCode,0);assert.equal(actual.failed,0);assert.equal(actual.skipped,0);assert(actual.passed>0);assert(indexed.has(actual.log));const log=String(indexed.get(actual.log).content);assert.equal(digest(log),actual.originalLogSha256);assert(log.startsWith('WEBAPI_FIXED_SOURCE '+revision+'\n'));assert(log.trimEnd().endsWith('WEBAPI_EXIT 0'));assert.deepEqual(parseSuiteLog(name,log),{passed:actual.passed,failed:0,skipped:0});}
 const refs=proof.materialArtifacts;assert(refs);const image=read(refs.images);identity(image);validateCloneOwnership(proof.clone.state,image.resources,proof.clone.directory);assert.equal(proof.clone.restored,true);const apps=image.resources.filter(r=>r.Kind==='container'&&['control-plane','worker','console','gateway-a','gateway-b'].includes(r.Config?.Labels?.['com.docker.compose.service']));assert.equal(apps.length,5);assert.equal(new Set(apps.map(r=>r.Config.Labels['com.docker.compose.service'])).size,5);assert(apps.every(r=>r.Image===imageId&&r.State.Running));assert(image.images?.length>0&&image.images.every(i=>i.Id===imageId&&i.Config?.Labels?.['org.opencontainers.image.revision']===revision));const staticProof=read(refs.static);identity(staticProof);assert(Object.keys(staticProof.expected??{}).length>0);assert.deepEqual(staticProof.actual,staticProof.expected,'实际容器静态文件不是本次构建');
 const scenario=read(refs.scenario);identity(scenario);assert.equal(scenario.actual,true);assert.equal(scenario.complete,true);for(const id of requiredScenarioChecks){const check=scenario.checks?.find(c=>c.id===id);assert(check?.passed===true&&check.evidence&&Object.keys(check.evidence).length>0,'场景尚未执行：'+id);}const protection=read(refs.protection);identity(protection);assert.equal(protection.originalPreserved,true);for(const key of ['complete','hashReadback','originalServicesRestored'])assert.equal(protection.backup?.[key],true);for(const key of ['actual','restored','ownerVerified'])assert.equal(protection.restore?.[key],true);assert.equal(protection.software?.upgradeDowngradeUpgrade,true);assert.equal(protection.software?.preservedNewWorkData,true);
 const ui=read(refs.ui);identity(ui);assert.equal(ui.kind,'cua');assert.equal(ui.actual,true);assert([1440,1280].every(w=>ui.widths?.includes(w)));assert(ui.screenshots?.length>0);for(const id of requiredUiActions){const action=ui.actions?.find(a=>a.id===id);assert.equal(action?.passed,true,'缺少实际 CUA 操作：'+id);identity(action);assert(ui.screenshots.includes(action.screenshot)&&indexed.has(action.screenshot));const bytes=indexed.get(action.screenshot).content;assert(Buffer.isBuffer(bytes)&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'截图不是 PNG');}
 return{passed:true,sourceRevision:revision,imageId,stage:'pre-install',originalInstallation:'not-upgraded',suites:proof.suites.map(s=>({name:s.name,passed:s.passed,failed:s.failed,skipped:s.skipped})),scenarioChecks:requiredScenarioChecks,uiActions:requiredUiActions};
}
