import fs from 'node:fs/promises';import path from 'node:path';import {randomBytes,createHash} from 'node:crypto';
import {RuntimeError,ownedDirectory,safeFile,loadState,writePrivate as defaultWrite} from '../runtime/state.mjs';import {docker,assertOwnership} from '../runtime/docker.mjs';
export const cacheReceiptName='cache-secret-receipt.json';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
async function exists(file){try{await fs.lstat(file);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}}
async function readKey(file){await safeFile(file);const stat=await fs.stat(file);if(stat.size!==45)throw new RuntimeError('Invalid private cache key size.',3);const raw=await fs.readFile(file);const text=raw.toString('utf8'),key=Buffer.from(text.trim(),'base64');if(key.length!==32||key.toString('base64')+'\n'!==text)throw new RuntimeError('Invalid private cache key encoding.',3);return sha(raw);}
function validateReceipt(receipt,state){if(!receipt||Object.keys(receipt).sort().join(',')!=='file,ownerId,projectName,schemaVersion,sha256'||receipt.schemaVersion!==1||receipt.file!=='secrets/cache-hmac'||!/^([a-f0-9]{64})$/.test(receipt.sha256)||receipt.ownerId!==state.ownerId||receipt.projectName!==state.projectName)throw new RuntimeError('Cache receipt owner or schema mismatch.',3);}
export async function ensureCacheSecret(directory,state,{readRandom=randomBytes,writePrivate=defaultWrite}={}){
 directory=await ownedDirectory(directory);const current=await loadState(directory);if(current.ownerId!==state.ownerId||current.projectName!==state.projectName)throw new RuntimeError('Cache runtime owner mismatch.',3);const secrets=await ownedDirectory(path.join(directory,'secrets')),file=path.join(secrets,'cache-hmac'),receiptFile=path.join(directory,cacheReceiptName),lock=path.join(directory,'cache-secret.lock');
 let handle;try{handle=await fs.open(lock,'wx',0o600);}catch(e){if(e.code==='EEXIST')throw new RuntimeError('Another cache secret operation is active; inspect before retry.',3);throw e;}
 try{if(await exists(receiptFile)){await safeFile(receiptFile);if((await fs.stat(receiptFile)).size>1024)throw new RuntimeError('Cache receipt exceeds bounded schema.',3);const receipt=JSON.parse(await fs.readFile(receiptFile,'utf8'));validateReceipt(receipt,state);if(!await exists(file))throw new RuntimeError('Recorded cache key is missing; restore the owned backup.',3);if(await readKey(file)!==receipt.sha256)throw new RuntimeError('Cache secret checksum mismatch; refuse rotation.',3);return{file,receipt};}
 if(!await exists(file)){const key=await readRandom(32);if(!Buffer.isBuffer(key)||key.length!==32)throw new RuntimeError('Cache randomness must contain 32 bytes.',3);await writePrivate(file,key.toString('base64')+'\n');}
 const receipt={schemaVersion:1,ownerId:state.ownerId,projectName:state.projectName,file:'secrets/cache-hmac',sha256:await readKey(file)};await writePrivate(receiptFile,receipt);return{file,receipt};
 }finally{await handle.close();await fs.unlink(lock);}
}
export async function copyCacheBackup(directory,target,state){const file=path.join(directory,cacheReceiptName);if(!await exists(file))return null;const value=await ensureCacheSecret(directory,state);await defaultWrite(path.join(target,cacheReceiptName),value.receipt);return value;}
export async function restoreCacheBackup(target,directory,state){const file=path.join(target,cacheReceiptName);if(!await exists(file))return null;await safeFile(file);const receipt=JSON.parse(await fs.readFile(file,'utf8')),original=JSON.parse(await fs.readFile(path.join(target,'runtime.json'),'utf8'));validateReceipt(receipt,original);if(await readKey(path.join(directory,'secrets/cache-hmac'))!==receipt.sha256)throw new RuntimeError('Restored cache secret checksum mismatch.',3);await defaultWrite(path.join(directory,cacheReceiptName),{...receipt,ownerId:state.ownerId,projectName:state.projectName});return ensureCacheSecret(directory,state);}
export async function assertCacheSecretVolume(state,receipt,image,{run=docker}={}){const name=state.projectName+'_secrets-cache',result=await run(['volume','inspect',name]);const volumes=JSON.parse(result.stdout);if(volumes.length!==1||volumes[0].Name!==name)throw new RuntimeError('Private cache volume is missing.',3);assertOwnership(state,volumes);if(!/^.+@sha256:[a-f0-9]{64}$/.test(image??''))throw new RuntimeError('Cache volume probe requires pinned SDK image.',3);const read=await run(['run','--rm','--user','10001:10001','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges:true','--label','com.docker.compose.project='+state.projectName,'--label','com.webapi.runtime.owner='+state.ownerId,'--mount','type=volume,src='+name+',dst=/run/cache,readonly',image,'sha256sum','/run/cache/cache-hmac']);if(read.stdout.trim().split(/\s+/)[0]!==receipt.sha256)throw new RuntimeError('Private cache volume checksum mismatch.',3);}
