import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {loadState,writePrivate} from '../runtime/state.mjs';import {loadRelease} from '../runtime/lifecycle.mjs';import {prepareContext} from '../runtime/context.mjs';import {ContractClient} from '../contracts/scenario.mjs';import {until,pause} from '../runtime/acceptance-scenario.mjs';import {createGatewayPolicyFixture} from './fixture.mjs';import {canRestoreSoftware} from './recovery.mjs';
export async function runGatewayPolicyScenario({revision,imageId,cloneDirectory,fixtureDirectory}){
 const fixture=await createGatewayPolicyFixture({revision,imageId,cloneDirectory,fixtureDirectory}),state=await loadState(cloneDirectory),release=await loadRelease(path.join(cloneDirectory,'release.json')),ctx=await prepareContext(cloneDirectory,state,release),endpoint='http://127.0.0.1:'+state.ports.console,admin=new ContractClient(endpoint),password=(await fs.readFile(path.join(cloneDirectory,'secrets/bootstrap-password'),'utf8')).trimEnd();
 const overlayFile=path.join(cloneDirectory,'runtime-config.json'),overlay=JSON.parse(await fs.readFile(overlayFile,'utf8'));for(const name of ['control-plane','worker','gateway-a','gateway-b']){const environment=overlay.services[name].environment;let index=0;while(environment['Upstream__AllowedOrigins__'+index])index++;environment['Upstream__AllowedOrigins__'+index]=fixture.backendOrigin;environment['Upstream__AllowedOrigins__'+(index+1)]=fixture.backendOriginB;if(['control-plane','worker'].includes(name)){environment.GatewayPolicies__FixtureEnabled='true';environment.GatewayPolicies__Jwt__HttpFixtureOrigins__0=new URL(fixture.issuer).origin;}if(name.startsWith('gateway'))environment.Observability__TraceSampleRatio='1';}await writePrivate(overlayFile,overlay);await ctx.compose('up','-d','--force-recreate','control-plane','worker','gateway-a','gateway-b');await until(()=>admin.login(state.bootstrapUsername,password),()=>true,90);
 const environment=await admin.request('/environments/'+state.binding.environmentId),project=await admin.request('/projects/'+environment.projectId),scope={organizationId:project.organizationId,projectId:project.id,environmentId:environment.id},tag=randomUUID().slice(0,8),flow=await admin.request('/organizations/'+scope.organizationId+'/approval-flows',{method:'POST',body:{name:'网关策略两级验收 '+tag,enabled:true,steps:[{stepOrder:1,roleCode:'ApiApprover',requiredCount:1},{stepOrder:2,roleCode:'SecurityReviewer',requiredCount:1}]}});await admin.request('/environments/'+environment.id,{method:'PUT',headers:{'If-Match':'"'+environment.revision+'"'},body:{code:environment.code,name:environment.name,status:environment.status,sortOrder:environment.sortOrder,isProduction:true,releasePolicyId:flow.id}});
 const roles=await admin.request('/roles'),users=[],reviewers=[];for(const [suffix,roleCode,accessMode]of [['approver','ApiApprover','read_write'],['security','SecurityReviewer','read_write'],['readonly','PlatformAdmin','read']]){const username='gateway-'+tag+'-'+suffix,userPassword=randomBytes(24).toString('base64');let user=await admin.request('/users',{method:'POST',body:{username,displayName:'网关验收 '+suffix,password:userPassword}});const role=roles.find(r=>r.isSystem&&r.code===roleCode)||roles.find(r=>r.isSystem&&r.code==='Admin');assert(role,'缺少系统角色 '+roleCode);user=await admin.request('/users/'+user.id+'/roles',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{roleIds:[role.id]}});await admin.request('/users/'+user.id+'/scopes',{method:'PUT',headers:{'If-Match':'"'+user.revision+'"'},body:{scopes:[{scope:{organizationId:scope.organizationId},accessMode}]}});const client=new ContractClient(endpoint);await client.login(username,userPassword);reviewers.push(client);users.push({id:user.id,username,password:userPassword});}
 const api=await admin.request('/projects/'+scope.projectId+'/apis',{method:'POST',body:{code:'GATEWAY_QA_'+tag,name:'JWT 重试缓存验收'}}),version=await admin.request('/apis/'+api.id+'/versions',{method:'POST',body:{version:'1.0.0'}}),cluster=await admin.request('/environments/'+scope.environmentId+'/clusters',{method:'POST',body:{name:'计数上游 '+tag,loadBalancingPolicy:'RoundRobin',healthCheckEnabled:false}});for(const [i,address]of [fixture.backendOrigin,fixture.backendOriginB].entries())await admin.request('/clusters/'+cluster.id+'/destinations',{method:'POST',body:{name:'fixture-'+i,address:address+'/',weight:1,enabled:true}});
 const applications=[];for(const suffix of ['allowed','denied'])applications.push(await admin.request('/applications',{method:'POST',body:{organizationId:scope.organizationId,projectId:scope.projectId,code:'GW_'+tag+'_'+suffix,name:'网关验收应用 '+suffix,owner:'独立验收'}}));await admin.request('/applications/'+applications[0].id+'/permissions',{method:'POST',body:{apiId:api.id,environmentId:scope.environmentId,validFrom:new Date(Date.now()-60000).toISOString()}});
 const route=await admin.request('/environments/'+scope.environmentId+'/routes',{method:'POST',body:{apiVersionId:version.id,routeName:'GatewayPolicy-'+tag,path:'/gateway-'+tag+'/{**path}',methods:['GET','HEAD','POST'],clusterId:cluster.id,priority:100,enabled:true,timeoutMs:10000,requireApiKey:true}}),routePath='/gateway-'+tag;
 const claims=JSON.parse(Buffer.from(fixture.tokens.a.split('.')[1],'base64url').toString()),audiences=Array.isArray(claims.aud)?claims.aud:[claims.aud];const jwtConfig={mode:'JWT',issuer:fixture.issuer,audiences,allowedAlgorithms:['RS256'],allowedTokenTypes:['JWT'],clockSkewSeconds:30,maxTokenLifetimeSeconds:3600,applicationClaim:'azp',applicationMappings:[{claimValue:'gateway-qa',applicationId:applications[0].id},{claimValue:'gateway-denied',applicationId:applications[1].id}],jwks:fixture.jwks,forwardBearer:false};
 let policies=[];const add=async(type,config)=>{const p=await admin.request('/projects/'+scope.projectId+'/policies',{method:'POST',body:{name:'验收 '+tag+' '+type,type,config:JSON.stringify(config),enabled:true}});policies.push(p);return p;};const configs={authentication:jwtConfig,timeout:{timeoutMs:10000},rate_limit:{algorithm:'TokenBucket',keyBy:'ApplicationRoute',refillTokens:1000,windowMs:1000,burst:1500,redisFailureMode:'Allow'},circuit_breaker:{samplingWindowMs:30000,minimumRequests:1,failureRatio:.5,openDurationMs:1000,halfOpenMaxRequests:1,halfOpenSuccesses:2,failureStatusCodes:[503],countTimeouts:true,countConnectionFailures:true},retry:{maxAttempts:3,perAttemptTimeoutMs:2000,baseDelayMs:10,maxDelayMs:20,jitterPercent:0,retryStatusCodes:[502,503,504],retryConnectionFailures:true},cache:{ttlSeconds:120,maxEntryBytes:262144,varyHeaders:['Accept'],identityPartition:'VerifiedIdentity',redisFailureMode:'Bypass'}};for(const [type,config]of Object.entries(configs))await add(type,config);
 const bind=async()=>{const b=await admin.request('/routes/'+route.id+'/policies');return admin.request('/routes/'+route.id+'/policies',{method:'PUT',headers:{'If-Match':'"'+b.revision+'"'},body:{bindings:policies.map(p=>({policyId:p.id,priority:100}))}});};await bind();
 const originalRoutes=(await admin.request('/environments/'+scope.environmentId+'/routes?pageSize=100')).items.filter(r=>r.enabled&&r.apiVersionId!==version.id),versionIds=[...new Set([...originalRoutes.map(r=>r.apiVersionId),version.id])],checks=[];const note=(id,evidence)=>{checks.push({id,passed:true,evidence});console.log('Verified '+id);};
 async function complete(r){await admin.request('/releases/'+r.id+'/submit',{method:'POST'});for(const reviewer of reviewers.slice(0,2))await reviewer.request('/releases/'+r.id+'/approve',{method:'POST',body:{comment:'仅独立恢复克隆的真实网关策略验收'}});await admin.request('/releases/'+r.id+'/publish',{method:'POST'});return until(()=>admin.request('/releases/'+r.id),x=>{if(x.state==='Failed')throw Object.assign(Error('发布失败'),{fatal:true});return x.state==='Succeeded'&&x.targets.length===2&&x.targets.every(t=>t.acknowledged);},120);}
 async function publish(){const env=await admin.request('/environments/'+scope.environmentId),selection={baseConfigVersion:env.desiredConfigVersion,versionIds},candidate=await admin.request('/environments/'+scope.environmentId+'/releases/preview',{method:'POST',body:selection});return complete(await admin.request('/environments/'+scope.environmentId+'/releases',{method:'POST',body:{...selection,resourceRevisions:candidate.resourceRevisions}}));}
 async function save(type,config){const p=policies.find(p=>p.type===type),updated=await admin.request('/policies/'+p.id,{method:'PUT',headers:{'If-Match':'"'+p.versionNo+'"'},body:{name:p.name,type,config:JSON.stringify(config),enabled:true}});policies=policies.map(x=>x.id===p.id?updated:x);return updated;}
 const backend='http://127.0.0.1:'+fixture.ports.backend,setup=async(failures=0,cacheable=true)=>{const r=await fetch(backend+'/__fixture/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({failures,cacheable})});assert.equal(r.status,200);},count=async url=>(await(await fetch(backend+'/__fixture/stats')).json())[url]??0;
 async function request(node,url,token=fixture.tokens.a){const traceId=randomBytes(16).toString('hex'),r=await fetch('http://127.0.0.1:'+(node===0?state.ports.gatewayA:state.ports.gatewayB)+url,{headers:{Host:'gateway.fixture.test',Authorization:'Bearer '+token,traceparent:'00-'+traceId+'-0123456789abcdef-01'},signal:AbortSignal.timeout(15000)}),text=await r.text();let body;try{body=JSON.parse(text);}catch{}return{status:r.status,text,body,traceId};}
 const firstRelease=await publish(),snapshot=await admin.request('/environments/'+scope.environmentId+'/snapshots/'+firstRelease.targetConfigVersion);assert.equal(snapshot.schemaVersion,'2.2');note('two-level-publish',{releaseId:firstRelease.id,dualAck:true,targetConfigVersion:firstRelease.targetConfigVersion,deploymentSequence:firstRelease.deploymentSequence,approvers:users.slice(0,2).map(u=>u.id)});
 const shared=routePath+'/shared',a=await request(0,shared),b=await request(1,shared);assert.equal(a.status,200);assert.equal(b.text,a.text);assert.equal(await count(shared),1);assert.equal(a.body.receivedBearer,false);assert.equal(a.body.receivedApiKey,false);const secondIdentity=await request(1,shared,fixture.tokens.b);assert.equal(secondIdentity.status,200);assert.equal(await count(shared),2);note('identity-partition',{nodes:2,sharedFirstCalls:1,otherIdentityCalls:2,firstTraceId:a.traceId,hitTraceId:b.traceId});
 const signature=fixture.tokens.a.split('.');signature[2]=(signature[2][0]==='A'?'B':'A')+signature[2].slice(1);for(const token of ['malformed',signature.join('.')])assert.equal((await request(1,shared,token)).status,401);assert.equal((await request(1,shared,fixture.tokens.denied)).status,403);assert.equal(await count(shared),2);note('jwt-negative',{invalidStatus:401,ungrantedStatus:403,noUpstream:true});
 const retry=routePath+'/retry';await setup(2);const retryResult=await request(0,retry);assert.equal(retryResult.status,200);assert.equal(await count(retry),3);await request(1,retry);assert.equal(await count(retry),3);note('retry-actual-calls',{physicalCalls:3,hitPhysicalCalls:0,traceId:retryResult.traceId});
 const abort=routePath+'/__abort';await setup(0,false);const uncertain=await request(0,abort);assert.equal(uncertain.status,502);assert.equal(await count(abort),1);note('uncertain-send-not-retried',{status:502,physicalCalls:1});
 await save('rate_limit',{...configs.rate_limit,refillTokens:1,windowMs:60000,burst:1});await save('circuit_breaker',{...configs.circuit_breaker,minimumRequests:100});await publish();await setup(2);const rateUrl=routePath+'/rate';assert.equal((await request(0,rateUrl)).status,200);assert.equal(await count(rateUrl),3);assert.equal((await request(1,rateUrl)).status,429);assert.equal(await count(rateUrl),3);note('rate-once',{firstPhysicalCalls:3,secondStatus:429,secondPhysicalCalls:0});
 await save('rate_limit',configs.rate_limit);await save('circuit_breaker',configs.circuit_breaker);await publish();await setup(100,false);const probe=routePath+'/probe';assert.equal((await request(0,probe)).status,503);assert.equal(await count(probe),3);assert.equal((await request(0,probe)).status,503);assert.equal(await count(probe),3);await pause(1100);assert.equal((await request(0,probe)).status,503);assert.equal(await count(probe),4);note('half-open-once',{initialPhysicalCalls:3,openPhysicalCalls:0,probePhysicalCalls:1});
 await save('circuit_breaker',{...configs.circuit_breaker,minimumRequests:100});await publish();await setup(0);await ctx.compose('stop','redis');try{const noRedis=routePath+'/redis';await until(()=>request(0,noRedis),r=>r.status===200,20);const before=await count(noRedis);assert.equal((await request(1,noRedis)).status,200);assert.equal(await count(noRedis),before+1);note('redis-fault',{bypassStatus:200,secondRequestCalls:1});}finally{await ctx.compose('up','-d','redis');}
 const foreignProject=await admin.request('/organizations/'+scope.organizationId+'/projects',{method:'POST',body:{code:'GW_FOREIGN_'+tag,name:'其他范围验收'}}),foreignApp=await admin.request('/applications',{method:'POST',body:{organizationId:scope.organizationId,projectId:foreignProject.id,code:'FOREIGN_'+tag,name:'不可跨项目映射',owner:'验收'}});await assert.rejects(()=>admin.request('/projects/'+scope.projectId+'/policies',{method:'POST',body:{name:'拒绝跨范围 '+tag,type:'authentication',config:JSON.stringify({...jwtConfig,applicationMappings:[{claimValue:'gateway-qa',applicationId:foreignApp.id}]}),enabled:true}}),e=>[403,404,422].includes(e.status));await assert.rejects(()=>reviewers[2].request('/projects/'+scope.projectId+'/policies',{method:'POST',body:{name:'拒绝只读 '+tag,type:'timeout',config:'{"timeoutMs":1000}',enabled:true}}),e=>e.status===403);note('scope-isolation',{foreignMappingRejected:true,readonlyWriteStatus:403});
 const current=await admin.request('/environments/'+scope.environmentId),currentSnapshot=await admin.request('/environments/'+scope.environmentId+'/snapshots/'+current.desiredConfigVersion);assert.equal(canRestoreSoftware({targetSchema:'2.1',currentSnapshots:[currentSnapshot],newWorkData:true}).allowed,false);note('downgrade-gate',{currentSchema:currentSnapshot.schemaVersion,oldSoftwareRejected:true,databaseRestoreForbidden:true});
 const rollback=await complete(await admin.request('/releases/'+firstRelease.id+'/rollback',{method:'POST',body:{targetConfigVersion:firstRelease.targetConfigVersion}}));await setup(0);const rollbackBefore=await count(shared);assert.equal((await request(0,shared)).status,200);assert.equal(await count(shared),rollbackBefore+1);note('rollback',{releaseId:rollback.id,dualAck:true,targetConfigVersion:rollback.targetConfigVersion,newDeploymentSequence:rollback.deploymentSequence,coldCache:true});
 const range={...scope,start:new Date(Date.now()-600000).toISOString(),end:new Date().toISOString()};const logs=await until(()=>admin.request('/observability/logs?'+new URLSearchParams({...range,traceId:b.traceId})),v=>v.data?.items?.some(x=>x.traceId===b.traceId),90);const hitLog=logs.data.items.find(x=>x.traceId===b.traceId);assert.equal(hitLog.attemptCount,0);assert.equal(hitLog.cacheDisposition,'Hit');assert.equal(hitLog.policyDecisions.length,5);const trace=await until(()=>admin.request('/observability/traces/'+retryResult.traceId+'?'+new URLSearchParams(range)),v=>v.data?.spans?.filter(x=>x.kind==='Client').length===3,90);await writePrivate(path.join(fixtureDirectory,'observation-result.json'),{logs,trace});await writePrivate(path.join(fixtureDirectory,'browser-context.json'),{endpoint,sourceRevision:revision,imageId,scope,admin:{username:state.bootstrapUsername,password},users,routeId:route.id,apiId:api.id,versionId:version.id,policies:policies.map(p=>({id:p.id,type:p.type})),publicJwksFile:path.join(fixtureDirectory,'public-jwks.json'),applicationId:applications[0].id,firstReleaseId:firstRelease.id,hitTraceId:b.traceId,retryTraceId:retryResult.traceId});
 const result={sourceRevision:revision,imageId,actual:true,complete:true,scope,checks,observations:{hitAttemptCount:0,hitPolicyDecisions:5,retryClientSpans:3},fixture:{owner:fixture.owner,project:fixture.project,ports:fixture.ports},originalInstallation:'not-upgraded'};await writePrivate(path.join(fixtureDirectory,'scenario-result.json'),result);return result;
}
