import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {loadState,writePrivate,ownedDirectory,withRuntimeLock,safeFile} from '../runtime/state.mjs';
import {loadRelease,initializeRuntime,operateRuntime} from '../runtime/lifecycle.mjs';import {prepareContext} from '../runtime/context.mjs';import {getRuntimeStatus} from '../runtime/status.mjs';import {createBackup,backupVolumeNames} from '../runtime/acceptance-backup.mjs';import {backupIdp} from '../runtime/keycloak-demo.mjs';
import {deliverySql,snapshotDeliveryFiles,verifyDeliveryBackup,waitDeliveryReady} from '../gateway-policies/delivery.mjs';import {captureHistoricalToolHashes,initializeNotificationFixture,assertNotificationSecretVolumes} from '../notifications/fixture.mjs';import {loadNotificationSecrets,loadNotificationRuntime,assertNotificationPorts} from '../notifications/runtime-secrets.mjs';import {ContractClient} from '../contracts/scenario.mjs';import {validateDataPreservingRecovery} from './recovery.mjs';
const exec=promisify(execFile),sha=b=>createHash('sha256').update(b).digest('hex'),json=async p=>JSON.parse(await fs.readFile(p,'utf8')),git=async(root,args)=>(await exec('git',args,{cwd:root,maxBuffer:32*1024*1024})).stdout.trim();
const dynamic={gateway_nodes:['instance_id','app_version','status','last_heartbeat_at','metadata'],alert_evaluation_states:['phase','pending_since','last_evaluated_slot','last_success_at','last_condition','last_event_id','next_occurrence_no','evaluation_state','suppressed_at','lease_owner','lease_until','lease_token','revision'],alert_events:['status','message','resolved_at','last_observed_at','last_value','last_condition','evaluation_state','revision'],outbox_messages:['processed_at','lease_until','attempts']};
const append=new Set(['audit_logs','gateway_node_events','alert_event_transitions','alert_events','alert_evaluation_states','sso_provider_tests','__EFMigrationsHistory']);
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value;}
export async function captureNotificationTables(state,before=null){
 const names=(await deliverySql(state,"SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename;")).split('\n'),tables={},primaryKeys=JSON.parse(await deliverySql(state,"SELECT COALESCE(json_object_agg(table_name,columns),'{}'::json) FROM (SELECT tc.table_name,array_agg(kcu.column_name ORDER BY kcu.ordinal_position) AS columns FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema AND tc.table_name=kcu.table_name WHERE tc.table_schema='public' AND tc.constraint_type='PRIMARY KEY' GROUP BY tc.table_name) p;"));
 for(const table of names){assert.match(table,/^[a-zA-Z0-9_]+$/);const current=JSON.parse(await deliverySql(state,'SELECT COALESCE(jsonb_agg(to_jsonb(t)),\'[]\'::jsonb) FROM "'+table+'" t;')),columns=(await deliverySql(state,"SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='"+table+"' ORDER BY ordinal_position;")).split('\n'),fields=before?.[table]?.columns??columns,rows={};
 for(const original of current){const row={...original};if(before?.[table]){if(table==='system_settings'&&row.key==='system.notification'&&Object.keys(row.value).length===9){assertMigratedNotificationValues(Object.fromEntries(Object.entries(row.value).filter(([k])=>!['smtpEnabled','webhookEnabled','smtpSecurity'].includes(k))),row.value);row.value=Object.fromEntries(Object.entries(row.value).filter(([k])=>!['smtpEnabled','webhookEnabled','smtpSecurity'].includes(k)));}if(table==='alert_rules'){assert.equal(row.notification.externalEnabled,false);assert.deepEqual(row.notification.emailRecipients,[]);assert.equal(row.notification.notifyRecovery,true);assert.deepEqual(row.notification.retryPolicy,{maxAttempts:5,baseDelaySeconds:30,maxDelaySeconds:900,expiresAfterMinutes:1440});row.notification=Object.fromEntries(Object.entries(row.notification).filter(([k])=>['inConsole','requestedChannels'].includes(k)));}}
 const selected=Object.fromEntries(fields.filter(k=>!dynamic[table]?.includes(k)).map(k=>[k,row[k]]));assert(primaryKeys[table]?.length,'Protected table lacks a primary key');const key=JSON.stringify(primaryKeys[table].map(k=>{assert(row[k]!==undefined);return row[k];}));if(table==='alert_events'&&before?.[table]?.rows[key])assertLegacyFrozenNotification(row.frozen_notification);assert(!Object.hasOwn(rows,key),'Duplicate protected row');rows[key]=sha(JSON.stringify(canonical(selected)));}
 tables[table]={columns:fields,count:current.length,mode:table==='sso_login_attempts'?'ephemeral':append.has(table)?'append-preserve':'exact',ignoredColumns:dynamic[table]??[],rows};
 }return tables;
}
export async function captureNotificationApprovalBaseline({main,originalDirectory,directory}){
 await ownedDirectory(directory);assert.equal(await git(main,['branch','--show-current']),'feature/core-loop');const state=await loadState(originalDirectory),release=await loadRelease(originalDirectory+'/release.json');assert.equal(state.projectName,'webapi-enterprise-local');assert.deepEqual(state.ports,{console:4192,gatewayA:4196,gatewayB:4197});const status=await getRuntimeStatus(state,{directory:originalDirectory}),baseline={createdAt:new Date().toISOString(),mainRevision:await git(main,['rev-parse','HEAD']),state,release,status,tables:await captureNotificationTables(state),files:await snapshotDeliveryFiles(main,originalDirectory),historicalTools:await captureHistoricalToolHashes(originalDirectory)};await checkMaintenanceWindow(originalDirectory,baseline);await writePrivate(directory+'/baseline.json',baseline);return baseline;
}
export async function checkMaintenanceWindow(directory,baseline){
 const state=await loadState(directory),status=await getRuntimeStatus(state,{directory});assert.equal(state.ownerId,baseline.state.ownerId);const uncompletedReleases=Number(await deliverySql(state,"SELECT count(*) FROM release_records WHERE status IN ('Building','Publishing');")),unprocessedPublishOutbox=Number(await deliverySql(state,"SELECT count(*) FROM outbox_messages WHERE processed_at IS NULL;"));assertMaintenanceWindow({...state,phase:status.phase,uncompletedReleases,unprocessedPublishOutbox});return status;
}
export async function assertOriginalProtection({baseline,main,originalDirectory,migrated=false}){
 const state=await loadState(originalDirectory);for(const key of ['ownerId','projectName','ports','binding','bootstrapUsername','demoEnabled'])assert.deepEqual(state[key],baseline.state[key]);assert.deepEqual(await snapshotDeliveryFiles(main,originalDirectory,baseline.files),baseline.files,'Original file changed');assert.deepEqual(await captureHistoricalToolHashes(originalDirectory),baseline.historicalTools,'Old fixed tooling changed');const after=await captureNotificationTables(state,migrated?baseline.tables:null);if(migrated)assertNotificationTablePreservation(baseline.tables,after);else{assert.deepEqual(Object.keys(after),Object.keys(baseline.tables));for(const[t,b]of Object.entries(baseline.tables)){if(b.mode==='ephemeral')continue;if(b.mode==='exact')assert.deepEqual(after[t].rows,b.rows,'Old business changed: '+t);else for(const[k,v]of Object.entries(b.rows))assert.equal(after[t].rows[k],v,'Old row changed: '+t);}}return state;
}
export async function installNotificationTooling({root,toolRevision,softwareRevision,directory,nodePath=process.execPath}){
 await ownedDirectory(directory);assert.match(toolRevision,/^[a-f0-9]{40}$/);assert.match(softwareRevision,/^[a-f0-9]{40}$/);const base=directory+'/notification-tooling',fixed=base+'/'+toolRevision;for(const name of ['manage-notifications.sh','notification-tooling.json'])assert(!(await fs.lstat(directory+'/'+name).catch(e=>{if(e.code==='ENOENT')return null;throw e;})),'New maintenance entry already exists');await fs.mkdir(base,{recursive:true,mode:0o700});await fs.mkdir(fixed,{mode:0o700});const archive=fixed+'/source.tar';await exec('git',['archive','--output',archive,toolRevision,'scripts','deploy'],{cwd:root});await exec('tar',['-xf',archive,'-C',fixed]);await fs.unlink(archive);const files={};async function walk(dir,prefix=''){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const n=prefix+entry.name;if(entry.isDirectory())await walk(dir+'/'+entry.name,n+'/');else{assert(entry.isFile());await fs.chmod(dir+'/'+entry.name,0o600);files[n]=sha(await fs.readFile(dir+'/'+entry.name));}}}await walk(fixed);
 const runner=directory+'/notification-tooling/runner.mjs';await writePrivate(runner,`import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';const directory=${JSON.stringify(directory)},m=JSON.parse(await fs.readFile(directory+'/notification-tooling.json'));const action=process.argv[2]??'status';if(!['status','start','stop','restart','up'].includes(action))throw Error('Unsupported lifecycle action');for(const[n,h]of Object.entries(m.files)){const p=path.join(m.fixedDirectory,n),s=await fs.lstat(p);if(s.isSymbolicLink()||!s.isFile()||createHash('sha256').update(await fs.readFile(p)).digest('hex')!==h)throw Error('Fixed tooling checksum mismatch');}const child=spawn(process.execPath,[m.fixedDirectory+'/scripts/notification-approval/manage.mjs',action,directory],{stdio:'inherit'});child.on('close',code=>process.exitCode=code??1);\n`);
 const quote=s=>"'"+s.replaceAll("'","'\\''")+"'",entry=directory+'/manage-notifications.sh';await writePrivate(directory+'/notification-tooling.json',{schemaVersion:1,toolRevision,softwareRevision,fixedDirectory:fixed,files,runnerSha256:sha(await fs.readFile(runner)),entry});await writePrivate(entry,'#!/usr/bin/env bash\nset -euo pipefail\nexec '+quote(nodePath)+' '+quote(runner)+' "${1:-status}"\n');await fs.chmod(entry,0o700);return {toolRevision,softwareRevision,files:Object.keys(files).length,originalEntriesUnchanged:true};
}
export async function runNotificationApprovalDelivery(options){
 const {approvedRevision,bridge,baseline,verification,originalDirectory,main,directory,releaseFile,integrationRevision,toolRevision,phase,recovery,root,nodePath}=options;await ownedDirectory(directory);const candidate=await loadRelease(releaseFile),state=await loadState(originalDirectory),modified=(await git(main,['diff','--name-only'])).split('\n').filter(Boolean),staged=(await git(main,['diff','--cached','--name-only'])).split('\n').filter(Boolean),changed=(await git(main,['diff','--name-only',baseline.mainRevision,integrationRevision])).split('\n').filter(Boolean);assertDeliveryAuthorization({approvedRevision,candidate,verification,state,baselineOwner:baseline.state.ownerId,modified,changed,staged});const recoveryGate=validateDataPreservingRecovery(recovery,{candidateRevision:approvedRevision,candidateImageId:candidate.imageId,bridgeRevision:bridge.bridgeRevision,bridgeImageId:bridge.imageId,baselineRevision:bridge.baselineRevision,patchSha256:bridge.patchSha256,lockFiles:bridge.lockFiles});assert(recoveryGate.passed,recoveryGate.errors.join('; '));
 if(phase==='merge'){await assertOriginalProtection({baseline,main,originalDirectory});assert.equal(await git(main,['rev-parse','HEAD']),baseline.mainRevision);const untracked=(await git(main,['ls-files','--others','--exclude-standard'])).split('\n').filter(Boolean);assert(!changed.some(n=>untracked.includes(n)),'Merge overlaps preserved untracked files');await git(main,['merge','--ff-only',integrationRevision]);await assertOriginalProtection({baseline,main,originalDirectory});return{complete:true,mainRevision:integrationRevision,softwareRevision:approvedRevision,pushed:false};}
 if(phase==='backup'){await checkMaintenanceWindow(originalDirectory,baseline);await assertOriginalProtection({baseline,main,originalDirectory});const ctx=await prepareContext(originalDirectory,state,baseline.release),target=directory+'/platform-before';await createBackup(ctx,target);const platform=await verifyDeliveryBackup(target);assert.equal(platform.volumes,backupVolumeNames(ctx).length);await backupIdp({runtimeDirectory:originalDirectory,directory:originalDirectory+'/idp',target:directory+'/idp-before'});const idp=await verifyDeliveryBackup(directory+'/idp-before');assert.equal(idp.volumes,4);await waitDeliveryReady(originalDirectory,baseline);await assertOriginalProtection({baseline,main,originalDirectory});return{complete:true,platform,idp,finallyReady:true};}
 if(phase==='upgrade'){assert((await json(directory+'/backup.json')).complete);await checkMaintenanceWindow(originalDirectory,baseline);await assertOriginalProtection({baseline,main,originalDirectory});await assertNotificationPorts({schemaVersion:1,ownerId:state.ownerId,projectName:state.projectName,enabled:true,fixtureEnabled:true,ports:{smtp:4198,https:4199,management:4200},secretReceipt:'notification-secrets/receipt.json'},state);let started=false;try{const old=await prepareContext(originalDirectory,state,baseline.release);await withRuntimeLock(originalDirectory,async()=>{await old.compose('stop','console','control-plane');const current=await loadState(originalDirectory),unfinished=Number(await deliverySql(current,"SELECT count(*) FROM release_records WHERE status IN ('Building','Publishing');"));assert.equal(unfinished,0);assert.equal(Number(await deliverySql(current,"SELECT count(*) FROM outbox_messages WHERE processed_at IS NULL;")),0);await old.compose('stop','worker','gateway-a','gateway-b');await assertOriginalProtection({baseline,main,originalDirectory});});
 await installNotificationTooling({root,toolRevision,softwareRevision:approvedRevision,directory:originalDirectory,nodePath});started=true;await initializeRuntime({directory:originalDirectory,bootstrapUsername:state.bootstrapUsername,releaseFile});await initializeNotificationFixture({directory:originalDirectory,ports:{smtp:4198,https:4199,management:4200}});const status=await waitDeliveryReady(originalDirectory,baseline);assert.equal(status.notifications.fixture,'Available');await assertOriginalProtection({baseline,main,originalDirectory,migrated:true});const ctx=await prepareContext(originalDirectory,await loadState(originalDirectory),candidate),receipt=await loadNotificationSecrets(originalDirectory+'/notification-secrets',state.ownerId,state.projectName);await assertNotificationSecretVolumes(state,receipt,candidate.dependencyImages.sdk);const target=directory+'/platform-after';await createBackup(ctx,target);const platformAfter=await verifyDeliveryBackup(target);assert.equal(platformAfter.volumes,backupVolumeNames(ctx).length);await backupIdp({runtimeDirectory:originalDirectory,directory:originalDirectory+'/idp',target:directory+'/idp-after'});const idpAfter=await verifyDeliveryBackup(directory+'/idp-after');assert.equal(idpAfter.volumes,4);await waitDeliveryReady(originalDirectory,baseline);await assertOriginalProtection({baseline,main,originalDirectory,migrated:true});return{complete:true,sourceRevision:approvedRevision,imageId:candidate.imageId,platformAfter,idpAfter,newNotificationVolumes:3,sourceDatabaseRestored:false,originalAccountsPreserved:true,originalToolsPreserved:true};
 }finally{if(started)await initializeRuntime({directory:originalDirectory,bootstrapUsername:state.bootstrapUsername,releaseFile});else await operateRuntime('up',await loadState(originalDirectory),{directory:originalDirectory});}}
 throw Error('Unsupported notification delivery phase');
}
export const notificationTableNames=['notification_channel_profiles','notification_channel_states','notification_deliveries','notification_delivery_attempts'];
export function assertMaintenanceWindow(window){
 assert(window.initialized&&window.phase==='Ready'&&window.bindingPhase==='Applied'&&window.pendingConfiguration===null,'Runtime is not in a stable maintenance window');
 assert.equal(window.uncompletedReleases,0,'Building/Publishing releases must finish before maintenance');assert.equal(window.unprocessedPublishOutbox,0,'Pending publication must finish before maintenance');return true;
}
export function assertDeliveryAuthorization({approvedRevision,candidate,verification,state,baselineOwner,modified,changed,staged}){
 assert.match(approvedRevision,/^[a-f0-9]{40}$/);assert.equal(candidate.sourceRevision,approvedRevision);assert.match(candidate.imageId,/^sha256:[a-f0-9]{64}$/);assert.equal(verification.passed,true);assert.equal(verification.sourceRevision,approvedRevision);assert.equal(verification.imageId,candidate.imageId);assert.equal(verification.stage,'pre-install');assert.equal(verification.reviewStatus,'complete-four-important-fixed');
 assert.equal(state.projectName,'webapi-enterprise-local');assert.equal(state.ownerId,baselineOwner);assert.deepEqual(state.ports,{console:4192,gatewayA:4196,gatewayB:4197});assert.equal(staged.length,0,'Existing staged changes must be preserved');
 assert(modified.every(p=>p==='.gitignore'||p==='README.md'||p.startsWith('docs/')),'Local product source modification blocks delivery');assert(!changed.some(p=>modified.includes(p)),'Merge would overwrite protected local edits');return true;
}
export function assertMigratedNotificationValues(before,after){
 const keys=['fromEmail','smtpHost','smtpPort','smtpSecretRef','webhookSecretRef','webhookUrl'];assert.deepEqual(Object.keys(before).sort(),keys);assert.deepEqual(Object.keys(after).sort(),[...keys,'smtpEnabled','webhookEnabled','smtpSecurity'].sort());for(const key of keys)assert.deepEqual(after[key],before[key],'Legacy notification value changed: '+key);assert.equal(after.smtpEnabled,false);assert.equal(after.webhookEnabled,false);assert.equal(after.smtpSecurity,'StartTlsRequired');return true;
}
export function assertNotificationTablePreservation(before,after){
 const additional=Object.keys(after).filter(t=>!Object.hasOwn(before,t)).sort(),expected=notificationTableNames.filter(t=>!Object.hasOwn(before,t)).sort();assert.deepEqual(additional,expected,'Unexpected database schema change');
 for(const[table,b]of Object.entries(before)){const a=after[table];assert(a,'Old table lost: '+table);if(b.mode==='ephemeral')continue;if(b.mode==='exact')assert.deepEqual(a.rows,b.rows,'Protected business rows changed: '+table);else for(const[key,hash]of Object.entries(b.rows))assert.equal(a.rows[key],hash,'Existing row changed: '+table);}return true;
}

export function assertLegacyFrozenNotification(value){assert.equal(value?.policy?.externalEnabled,false,'Legacy event must not send externally');assert.deepEqual(value.policy.emailRecipients,[]);assert.equal(value.emailProfileId,null);assert.equal(value.webhookProfileId,null);return true;}
