import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validateNotificationEvidence} from '../notifications/evidence.mjs';import {validateApprovalEvidence,screenshotSize,requiredApprovalUiActions} from '../approvals/evidence.mjs';
import {validateDataPreservingRecovery,assertRecoveredNotificationWire} from './recovery.mjs';import {verifySuiteLogs} from './verify-suites.mjs';import {assertPublicFiles} from '../contracts/evidence.mjs';import {validGuid} from '../runtime/state.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
export function validateNotificationApprovalEvidence(proof,files,{revision,imageId,bridgeRevision,bridgeImageId,baselineRevision,patchSha256,lockFiles,privateValues=[]}){
 try{
  assert(/^[a-f0-9]{40}$/.test(revision)&&/^sha256:[a-f0-9]{64}$/.test(imageId));const identity=value=>assert(value?.sourceRevision===revision&&value?.imageId===imageId,'Joint evidence source/image mismatch');identity(proof);assert(proof.schemaVersion===1&&proof.stage==='pre-install'&&proof.originalInstallation==='not-upgraded');
  assertPublicFiles([{path:'joint-evidence.json',type:'file',content:Buffer.from(JSON.stringify(proof))},...files],{secrets:privateValues});assert(files.length===proof.manifest?.length);const indexed=new Map();for(const file of files){assert(Buffer.isBuffer(file.content)&&!indexed.has(file.path));assert.equal(sha(file.content),file.sha256);assert(proof.manifest.some(m=>m.path===file.path&&m.sha256===file.sha256));const text=file.content.toString();assert(!/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(text)&&!/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/.test(text),'Private key/JWT in public evidence');
   if(file.path.endsWith('.json'))for(const match of text.matchAll(/"([^"\n]*@[A-Za-z0-9.-]+\.[A-Za-z]{2,}[^"\n]*)"/g)){const value=match[1];assert(value.includes('*')||['recipient@example.test','sender@example.test'].includes(value)||/^[a-f0-9-]{36}@webapi\.invalid$/.test(value),'Raw email in public evidence');}indexed.set(file.path,file);}
  const read=name=>{assert(typeof name==='string'&&indexed.has(name),'Missing evidence '+name);return JSON.parse(indexed.get(name).content);};
  const refs=proof.references;assert(refs);const notifications=read(refs.notifications),approval=read(refs.approvals),recovery=read(refs.recovery);identity(notifications);identity(approval);identity(recovery);
  const nested=(prefix,material)=>{assert(Array.isArray(material.manifest));return material.manifest.map(m=>{const file=indexed.get(prefix+'/'+m.path);assert(file&&file.sha256===m.sha256);return{...file,path:m.path};});};
  const notificationFiles=nested('notifications',notifications),notificationGate=validateNotificationEvidence(notifications,notificationFiles,{revision,imageId,privateValues});assert(notificationGate.passed,notificationGate.errors.join('; '));
  validateApprovalEvidence(approval,nested('approvals',approval),{revision,imageId});
  assert(approval.environments.every(validGuid)&&new Set(approval.environments).size===2);const actionable=approval.pagination.actionableId;assert(validGuid(actionable));const expectations={'cross-environment':[...approval.environments].sort(),'mixed-scope':[2,1,approval.environments[0]],'read-only':[2,0,403],'self-approval':403,'second-page':[51,50,1,actionable,1],'independent-seats':[403,403,2,'Ready',3],'revocation':[0,404]};
  for(const[id,expected]of Object.entries(expectations)){const check=approval.checks.find(c=>c.id===id);assert(check?.evidence?.serviceResponse);const actual=JSON.parse(check.evidence.actual),declared=JSON.parse(check.evidence.expected);if(id==='cross-environment'){assert.deepEqual([...actual].sort(),expected);assert.deepEqual([...declared].sort(),expected);}else if(id==='mixed-scope'){assert.deepEqual(actual.slice(0,2),[2,1]);assert.deepEqual(actual,declared);assert(approval.environments.includes(actual[2]));}else{assert.deepEqual(actual,expected);assert.deepEqual(declared,expected);}}
  const runtime=read('notifications/'+notifications.runtime.observation),staticProof=read(refs.static);identity(staticProof);assert(staticProof.expected?.['console/dist/index.html']&&Object.values(staticProof.expected).every(h=>/^[a-f0-9]{64}$/.test(h)));assert.deepEqual(staticProof.actual,staticProof.expected);assert.deepEqual(runtime.staticFiles,staticProof.expected);
  for(const id of requiredApprovalUiActions){const action=approval.ui.actions.find(a=>a.id===id),observation=read('approvals/'+action.observation),screenshot=indexed.get('approvals/'+action.screenshot);identity(observation);assert(observation.id===id&&observation.source==='cua'&&observation.actual===true&&observation.consolePort===approval.clone.consolePort&&observation.viewport===action.viewport&&observation.screenshotSha256===screenshot.sha256);assert.equal(screenshotSize(screenshot.content).width,action.viewport);assert.deepEqual(observation.staticFiles,staticProof.expected);}
  assert(approval.clone.consolePort===notifications.clone.consolePort&&Number.isInteger(approval.clone.consolePort)&&approval.clone.consolePort>1024&&approval.clone.consolePort<=65535,'Joint UI clone port mismatch');const captureHashes=[...notifications.ui.actions.map(a=>indexed.get('notifications/'+a.screenshot).sha256),...approval.ui.actions.map(a=>indexed.get('approvals/'+a.screenshot).sha256)];assert.equal(new Set(captureHashes).size,captureHashes.length,'Different UI actions reused the same capture');
  const expected={candidateRevision:revision,candidateImageId:imageId,bridgeRevision,bridgeImageId,baselineRevision,patchSha256,lockFiles},recoveryGate=validateDataPreservingRecovery(recovery,expected);assert(recoveryGate.passed,recoveryGate.errors.join('; '));assertRecoveredNotificationWire(recovery.fresh.deliveries,recovery.fresh.smtp,recovery.fresh.webhook);const final=read(refs.finally);identity(final);assert(final.candidateRestored&&final.proofComplete);
  const notificationBackup=read('notifications/'+notifications.backup.observation);assert.equal(recovery.clone.ownerId,notificationBackup.restore.ownerId);assert.equal(recovery.clone.projectName,notificationBackup.restore.projectName);assert.equal(recovery.protectedBefore.dpKeys,sha(JSON.stringify(notificationBackup.restore.dpKeysAfter)));
  const images=read(refs.images);identity(images);assert(images.ownerId===notifications.clone.ownerId&&images.projectName===notifications.clone.projectName&&validGuid(images.ownerId)&&validGuid(images.projectName.replace('webapi-enterprise-local-test-','')));assert(approval.clone.ownerId===images.ownerId&&approval.clone.projectName===images.projectName);
  const services=['control-plane','worker','console','gateway-a','gateway-b'],apps=images.resources?.filter(r=>r.Kind==='container'&&services.includes(r.Config?.Labels?.['com.docker.compose.service']));assert(apps?.length===5&&new Set(apps.map(r=>r.Config.Labels['com.docker.compose.service'])).size===5);for(const app of apps)assert(app.Image===imageId&&app.State?.Running&&app.Config.Labels['com.docker.compose.project']===images.projectName&&app.Config.Labels['com.webapi.runtime.owner']===images.ownerId);assert(images.images?.length&&images.images.every(i=>i.Id===imageId&&i.Config?.User==='10001:10001'&&i.Config.Labels?.['org.opencontainers.image.revision']===revision));
  const regression=read(refs.regression);identity(regression);assert(regression.actual&&regression.dualAck&&regression.keycloakLogin&&regression.csrfRejected&&regression.readOnlyRejected&&regression.logoutRejected&&regression.jwtRetryCache);assert.deepEqual(regression.gatewayStatuses,[200,200]);for(const name of ['prometheus','loki','tempo'])assert(regression.sources.some(s=>s.name===name&&s.state==='Available'));
  const gateway=read(refs.gatewayRegression);identity(gateway);assert(gateway.actual&&gateway.complete);const gatewayExpected={'jwt-negative':{invalidStatus:401,ungrantedStatus:403,noUpstream:true},'identity-partition':{nodes:2,sharedFirstCalls:1,otherIdentityCalls:2},'retry-actual-calls':{physicalCalls:3,hitPhysicalCalls:0},'uncertain-send-not-retried':{status:502,physicalCalls:1},'rate-once':{firstPhysicalCalls:3,secondStatus:429,secondPhysicalCalls:0},'half-open-once':{initialPhysicalCalls:3,openPhysicalCalls:0,probePhysicalCalls:1},'scope-isolation':{foreignMappingRejected:true,readonlyWriteStatus:403},'redis-fault':{bypassStatus:200,secondRequestCalls:1}};
  for(const[id,expectedValues]of Object.entries(gatewayExpected)){const check=gateway.checks?.find(c=>c.id===id);assert(check?.passed);for(const[key,value]of Object.entries(expectedValues))assert.deepEqual(check.evidence?.[key],value,'Missing gateway actual '+id+'/'+key);}
  const publish=gateway.checks?.find(c=>c.id==='two-level-publish'),rollback=gateway.checks?.find(c=>c.id==='rollback'),downgrade=gateway.checks?.find(c=>c.id==='downgrade-gate');assert(publish?.passed&&publish.evidence?.dualAck&&validGuid(publish.evidence.releaseId)&&publish.evidence.approvers?.length===2&&new Set(publish.evidence.approvers).size===2&&publish.evidence.approvers.every(validGuid));assert(rollback?.passed&&rollback.evidence?.dualAck&&rollback.evidence.coldCache&&validGuid(rollback.evidence.releaseId)&&rollback.evidence.newDeploymentSequence>publish.evidence.deploymentSequence);assert(downgrade?.passed&&downgrade.evidence?.oldSoftwareRejected&&downgrade.evidence.databaseRestoreForbidden&&downgrade.evidence.currentSchema==='2.2'&&downgrade.evidence.nodeLkgSchemas?.length===2&&downgrade.evidence.nodeLkgSchemas.every(s=>s==='2.2'));
  const sso=read(refs.ssoRegression);identity(sso);assert(sso.actual&&sso.fixtureOwnerVerified&&validGuid(sso.providerId)&&validGuid(sso.externalIdentityId)&&sso.authSource==='sso'&&sso.callbackStatus===302&&sso.authenticated&&sso.cookieAfterRestart&&Number.isInteger(sso.loginAuditCountDelta)&&sso.loginAuditCountDelta>=1,'Missing actual current-image OIDC login/restart proof');
  const logs=proof.suites.map(wrapper=>{const summary=read(wrapper.artifact);assert.deepEqual(summary,Object.fromEntries(Object.entries(wrapper).filter(([key])=>key!=='artifact')));const file=indexed.get(wrapper.log);assert(file);return {...summary,content:file.content};});verifySuiteLogs(logs,{revision});return {passed:true,errors:[]};
 }catch(error){return {passed:false,errors:[error instanceof Error?error.message:'Invalid joint evidence']};}
}
