import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createWriteStream} from 'node:fs';import path from 'node:path';import {spawn,execFile} from 'node:child_process';import {promisify} from 'node:util';
import {parseSuiteLog,digest} from '../gateway-policies/evidence.mjs';import {assertFrozenDependencies} from '../runtime/build.mjs';import {ownedDirectory,writePrivate} from '../runtime/state.mjs';import {loadRelease} from '../runtime/lifecycle.mjs';import {docker} from '../runtime/docker.mjs';
const exec=promisify(execFile),required=['domain','integration','gateway','console','runtime','features'];
export function validateSuiteRelease(release,revision){assert(release?.schemaVersion===1&&release.configVersion===1&&release.sourceRevision===revision&&/^sha256:[a-f0-9]{64}$/.test(release.imageId),'Built suite release must match the archived source');assert(/^[a-f0-9]{64}$/.test(release.staticFiles?.['console/dist/index.html']??'')&&/^[a-f0-9]{64}$/.test(release.applications?.['notification-fixture/WebApi.NotificationFixtureHost.dll']??''),'Suite release lacks current console/fixture');return true;}
export function verifySuiteLogs(logs,{revision}){
 assert(/^[a-f0-9]{40}$/.test(revision));assert(logs.length===required.length&&new Set(logs.map(s=>s.name)).size===required.length,'Five suites and separate feature Node tests are required');
 const summaries=[];for(const name of required){const entry=logs.find(s=>s.name===name);assert(entry&&entry.sourceRevision===revision);const text=Buffer.isBuffer(entry.content)?entry.content.toString():entry.content;assert(typeof text==='string'&&text.startsWith('WEBAPI_FIXED_SOURCE '+revision+'\n')&&text.trimEnd().endsWith('WEBAPI_EXIT 0'),'Suite log source/exit mismatch');assert.equal(digest(text),entry.originalLogSha256);const counts=parseSuiteLog(name==='features'?'runtime':name,text);assert(counts.passed>0&&counts.failed===0&&counts.skipped===0);for(const[key,value]of Object.entries(counts))assert.equal(entry[key],value,'Suite reported '+key+' differs from log');assert.equal(entry.exitCode,0);
  if(['console','runtime','features'].includes(name)){const totals=[...text.matchAll(/^ℹ tests (\d+)\s*$/gm)];assert.equal(totals.length,1);assert.equal(Number(totals[0][1]),counts.passed);for(const key of ['cancelled','todo']){const field=[...text.matchAll(new RegExp('^ℹ '+key+' (\\d+)\\s*$','gm'))];assert(field.length<=1&&(!field.length||Number(field[0][1])===0));}}
  const{content,...summary}=entry;summaries.push(summary);
 }
 return {sourceRevision:revision,suites:summaries.filter(s=>s.name!=='features'),features:summaries.find(s=>s.name==='features')};
}
// All suites run against the same immutable archive. Existing dependencies must
// match the archived lock; runtime and feature tests are counted separately.
export async function runNotificationApprovalSuites({revision,directory,root=path.resolve(import.meta.dirname,'../..'),node=process.execPath,pnpm,releaseFile}){
 assert(/^[a-f0-9]{40}$/.test(revision));assert(releaseFile,'Build the fixed candidate before full runtime suites');const release=await loadRelease(releaseFile);validateSuiteRelease(release,revision);const image=JSON.parse((await docker(['image','inspect',release.imageId])).stdout)[0];assert(image.Id===release.imageId&&image.Config?.Labels?.['org.opencontainers.image.revision']===revision&&image.Config.User==='10001:10001');await ownedDirectory(directory);assert.equal((await exec('git',['rev-parse',revision+'^{commit}'],{cwd:root})).stdout.trim(),revision);
 const source=path.join(directory,'fixed-source'),archive=path.join(directory,'fixed-source.tar'),publicDirectory=path.join(directory,'public');await fs.mkdir(source,{mode:0o700});await fs.mkdir(publicDirectory,{mode:0o700});await exec('git',['archive','--output',archive,revision],{cwd:root});await exec('tar',['-xf',archive,'-C',source]);await assertFrozenDependencies(path.join(source,'console'),path.join(root,'console'));await fs.symlink(path.join(root,'console/node_modules'),path.join(source,'console/node_modules'),'dir');
 const runtimeReleaseDirectory=path.join(source,'.runtime/local-build');await fs.mkdir(runtimeReleaseDirectory,{recursive:true,mode:0o700});const runtimeReleaseFile=path.join(runtimeReleaseDirectory,'release.json');await writePrivate(runtimeReleaseFile,release);
 const logs=[];async function run(name,binary,args){const file=path.join(publicDirectory,name+'.log');await fs.writeFile(file,'WEBAPI_FIXED_SOURCE '+revision+'\n');const stream=createWriteStream(file,{flags:'a'}),env={...process.env,WEBAPI_NODE:node,WEBAPI_PNPM:pnpm,WEBAPI_RUNTIME_TEST_RELEASE:runtimeReleaseFile,pnpm_config_verify_deps_before_run:'ignore',PATH:path.dirname(node)+path.delimiter+process.env.PATH};
  const exitCode=await new Promise((resolve,reject)=>{const child=spawn(binary,args,{cwd:source,env,stdio:['ignore','pipe','pipe']});child.stdout.pipe(stream,{end:false});child.stderr.pipe(stream,{end:false});child.once('error',reject);child.once('close',resolve);});await new Promise(resolve=>stream.end(resolve));await fs.appendFile(file,'\nWEBAPI_EXIT '+exitCode+'\n');assert.equal(exitCode,0,name+' suite failed');const content=await fs.readFile(file,'utf8'),counts=parseSuiteLog(name==='features'?'runtime':name,content),summary={name,sourceRevision:revision,...counts,exitCode,originalLogSha256:digest(content),log:'suites/'+name+'.log',artifact:'suites/'+name+'.json'};logs.push({...summary,content});await fs.writeFile(path.join(publicDirectory,name+'.json'),JSON.stringify(Object.fromEntries(Object.entries(summary).filter(([key])=>key!=='artifact')),null,2)+'\n');console.log(JSON.stringify({suite:name,...counts,exitCode}));}
 async function nodeTests(directory,relative='tests'){const result=[];for(const entry of await fs.readdir(directory,{withFileTypes:true})){const name=relative+'/'+entry.name;if(entry.isDirectory())result.push(...await nodeTests(path.join(directory,entry.name),name));else if(entry.isFile()&&entry.name.endsWith('.test.mjs'))result.push(name);}return result.sort();}
 const allNode=await nodeTests(path.join(source,'tests')),runtime=allNode.filter(f=>f.startsWith('tests/runtime/')),features=allNode.filter(f=>!f.startsWith('tests/runtime/'));assert(runtime.length&&features.length);
 const independent=await Promise.allSettled([run('console','bash',['./scripts/check-console.sh']),run('runtime',node,['--test','--test-concurrency=1',...runtime]),run('features',node,['--test',...features])]);for(const result of independent)if(result.status==='rejected')throw result.reason;
 for(const name of ['domain','integration','gateway'])await run(name,'bash',['./scripts/check-contracts.sh',name,'--logger','console;verbosity=detailed']);
 const receipt=verifySuiteLogs(logs,{revision});await writePrivate(path.join(directory,'suites-result.json'),receipt);return receipt;
}
