using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WebApi.Infrastructure.Persistence.Entities;
namespace WebApi.Infrastructure.Persistence;
internal static class CoreConstraints
{
    public static void Apply(ModelBuilder model)
    {
        var gateway_node_events = model.Entity<GatewayNodeEvent>();
        var environments = model.Entity<EnvironmentRecord>();
        var application_api_permissions = model.Entity<ApplicationApiPermission>();
        var gateway_acks = model.Entity<GatewayAck>();
        var route_policy_bindings = model.Entity<RoutePolicyBinding>();
        var audit_logs = model.Entity<AuditLog>();
        var release_items = model.Entity<ReleaseItem>();
        var roles = model.Entity<Role>();
        var apis = model.Entity<Api>();
        var api_routes = model.Entity<ApiRoute>();
        var projects = model.Entity<Project>();
        var user_project_scopes = model.Entity<UserProjectScope>();
        var application_credentials = model.Entity<ApplicationCredential>();
        var approval_steps = model.Entity<ApprovalStep>();
        var applications = model.Entity<ApplicationRecord>();
        var policies = model.Entity<Policy>();
        var release_targets = model.Entity<ReleaseTarget>();
        var api_groups = model.Entity<ApiGroup>();
        var role_permissions = model.Entity<RolePermission>();
        var approval_tasks = model.Entity<ApprovalTask>();
        var gateway_config_snapshots = model.Entity<GatewayConfigSnapshot>();
        var upstream_clusters = model.Entity<UpstreamCluster>();
        var approval_flows = model.Entity<ApprovalFlow>();
        var api_parameters = model.Entity<ApiParameter>();
        var gateway_config_versions = model.Entity<GatewayConfigVersion>();
        var permissions = model.Entity<Permission>();
        var gateway_nodes = model.Entity<GatewayNode>();
        var api_schemas = model.Entity<ApiSchema>();
        var upstream_destinations = model.Entity<UpstreamDestination>();
        var idempotency_records = model.Entity<IdempotencyRecord>();
        var organizations = model.Entity<Organization>();
        var release_records = model.Entity<ReleaseRecord>();
        var user_roles = model.Entity<UserRole>();
        var api_versions = model.Entity<ApiVersion>();
        var route_methods = model.Entity<RouteMethod>();
        var outbox_messages = model.Entity<OutboxMessage>();
        var users = model.Entity<UserRecord>();
        projects.HasAlternateKey("Id", "OrganizationId");
        environments.HasAlternateKey("Id", "ProjectId");
        api_groups.HasAlternateKey("Id", "ProjectId");
        upstream_clusters.HasAlternateKey("Id", "EnvironmentId");
        api_routes.HasAlternateKey("Id", "EnvironmentId");
        organizations.HasIndex("Code").IsUnique();
        projects.HasIndex("OrganizationId", "Code").IsUnique();
        environments.HasIndex("ProjectId", "Code").IsUnique();
        apis.HasIndex("ProjectId", "Code").IsUnique();
        api_versions.HasIndex("ApiId", "Version").IsUnique();
        upstream_clusters.HasIndex("EnvironmentId", "Name").IsUnique();
        applications.HasIndex("OrganizationId", "Code").IsUnique();
        application_credentials.HasIndex("AccessKey").IsUnique();
        application_api_permissions.HasIndex("ApplicationId", "ApiId", "EnvironmentId").IsUnique();
        users.HasIndex("Username").IsUnique();
        users.HasIndex("Email").IsUnique();
        permissions.HasIndex("Code").IsUnique();
        release_records.HasIndex("ReleaseNo").IsUnique();
        gateway_config_versions.HasIndex("EnvironmentId", "VersionNo").IsUnique();
        gateway_nodes.HasIndex("NodeName").IsUnique();
        approval_steps.HasIndex("FlowId", "StepOrder").IsUnique();
        route_methods.HasIndex("EnvironmentId", "Method", "NormalizedPath").IsUnique();
        idempotency_records.HasIndex("ActorId", "ScopeKey", "Operation", "Key").IsUnique();
        roles.HasIndex("OrganizationId", "Code").IsUnique().HasFilter("organization_id IS NOT NULL");
        roles.HasIndex("Code").IsUnique().HasFilter("organization_id IS NULL");
        projects.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        projects.HasOne<UserRecord>().WithMany().HasForeignKey("OwnerUserId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        environments.HasOne<Project>().WithMany().HasForeignKey("ProjectId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_groups.HasOne<Project>().WithMany().HasForeignKey("ProjectId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        apis.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        apis.HasOne<UserRecord>().WithMany().HasForeignKey("OwnerUserId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_versions.HasOne<Api>().WithMany().HasForeignKey("ApiId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_versions.HasOne<UserRecord>().WithMany().HasForeignKey("CreatedBy").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_routes.HasOne<ApiVersion>().WithMany().HasForeignKey("ApiVersionId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_routes.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_parameters.HasOne<ApiVersion>().WithMany().HasForeignKey("ApiVersionId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        api_schemas.HasOne<ApiVersion>().WithMany().HasForeignKey("ApiVersionId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        upstream_clusters.HasOne<Project>().WithMany().HasForeignKey("ProjectId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        upstream_destinations.HasOne<UpstreamCluster>().WithMany().HasForeignKey("ClusterId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        policies.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        route_policy_bindings.HasOne<ApiRoute>().WithMany().HasForeignKey("RouteId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        route_policy_bindings.HasOne<Policy>().WithMany().HasForeignKey("PolicyId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        applications.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        application_credentials.HasOne<ApplicationRecord>().WithMany().HasForeignKey("ApplicationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        application_api_permissions.HasOne<ApplicationRecord>().WithMany().HasForeignKey("ApplicationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        application_api_permissions.HasOne<Api>().WithMany().HasForeignKey("ApiId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        application_api_permissions.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        application_api_permissions.HasOne<UserRecord>().WithMany().HasForeignKey("CreatedBy").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        roles.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        user_roles.HasOne<UserRecord>().WithMany().HasForeignKey("UserId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        user_roles.HasOne<Role>().WithMany().HasForeignKey("RoleId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        role_permissions.HasOne<Role>().WithMany().HasForeignKey("RoleId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        role_permissions.HasOne<Permission>().WithMany().HasForeignKey("PermissionId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        user_project_scopes.HasOne<UserRecord>().WithMany().HasForeignKey("UserId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        user_project_scopes.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        approval_flows.HasOne<Organization>().WithMany().HasForeignKey("OrganizationId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        approval_steps.HasOne<ApprovalFlow>().WithMany().HasForeignKey("FlowId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        approval_tasks.HasOne<ApprovalFlow>().WithMany().HasForeignKey("FlowId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        approval_tasks.HasOne<ReleaseRecord>().WithMany().HasForeignKey("ReleaseId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        approval_tasks.HasOne<UserRecord>().WithMany().HasForeignKey("AssigneeUserId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_records.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_records.HasOne<UserRecord>().WithMany().HasForeignKey("RequestedBy").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_records.HasOne<UserRecord>().WithMany().HasForeignKey("PublishRequestedBy").OnDelete(DeleteBehavior.Restrict);
        release_records.HasIndex(x => new {x.EnvironmentId,x.DeploymentSequence}).IsUnique().HasFilter("deployment_sequence > 0");
        release_records.HasOne<UserRecord>().WithMany().HasForeignKey("ApprovedBy").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_records.HasOne<ReleaseRecord>().WithMany().HasForeignKey("RollbackOf").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_items.HasOne<ReleaseRecord>().WithMany().HasForeignKey("ReleaseId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_config_versions.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_config_versions.HasOne<UserRecord>().WithMany().HasForeignKey("CreatedBy").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_nodes.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_node_events.HasOne<GatewayNode>().WithMany().HasForeignKey("GatewayNodeId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_targets.HasOne<ReleaseRecord>().WithMany().HasForeignKey("ReleaseId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        release_targets.HasOne<GatewayNode>().WithMany().HasForeignKey("NodeId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_acks.HasOne<ReleaseRecord>().WithMany().HasForeignKey("ReleaseId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_acks.HasOne<GatewayNode>().WithMany().HasForeignKey("NodeId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        outbox_messages.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        outbox_messages.HasOne<ReleaseRecord>().WithMany().HasForeignKey("ReleaseId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        idempotency_records.HasOne<UserRecord>().WithMany().HasForeignKey("ActorId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        gateway_config_snapshots.HasOne<GatewayConfigVersion>().WithMany().HasForeignKey("ConfigVersionId").HasPrincipalKey("Id").OnDelete(DeleteBehavior.Restrict);
        apis.HasOne<Project>().WithMany().HasForeignKey("ProjectId", "OrganizationId").HasPrincipalKey("Id", "OrganizationId").OnDelete(DeleteBehavior.Restrict);
        apis.HasOne<ApiGroup>().WithMany().HasForeignKey("GroupId", "ProjectId").HasPrincipalKey("Id", "ProjectId").OnDelete(DeleteBehavior.Restrict);
        upstream_clusters.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId", "ProjectId").HasPrincipalKey("Id", "ProjectId").OnDelete(DeleteBehavior.Restrict);
        api_routes.HasOne<UpstreamCluster>().WithMany().HasForeignKey("ClusterId", "EnvironmentId").HasPrincipalKey("Id", "EnvironmentId").OnDelete(DeleteBehavior.Restrict);
        user_project_scopes.HasOne<Project>().WithMany().HasForeignKey("ProjectId", "OrganizationId").HasPrincipalKey("Id", "OrganizationId").OnDelete(DeleteBehavior.Restrict);
        policies.HasOne<Project>().WithMany().HasForeignKey("ProjectId", "OrganizationId").HasPrincipalKey("Id", "OrganizationId").OnDelete(DeleteBehavior.Restrict);
        applications.HasOne<Project>().WithMany().HasForeignKey("ProjectId", "OrganizationId").HasPrincipalKey("Id", "OrganizationId").OnDelete(DeleteBehavior.Restrict);
        user_project_scopes.HasOne<EnvironmentRecord>().WithMany().HasForeignKey("EnvironmentId", "ProjectId").HasPrincipalKey("Id", "ProjectId").OnDelete(DeleteBehavior.Restrict);
        route_methods.HasOne<ApiRoute>().WithMany().HasForeignKey("RouteId", "EnvironmentId").HasPrincipalKey("Id", "EnvironmentId").OnDelete(DeleteBehavior.Restrict);
        gateway_acks.HasOne<ReleaseTarget>().WithMany().HasForeignKey("ReleaseId", "NodeId").HasPrincipalKey("ReleaseId", "NodeId").OnDelete(DeleteBehavior.Restrict);
        user_project_scopes.ToTable(t => t.HasCheckConstraint("ck_scope_environment_requires_project", "environment_id IS NULL OR project_id IS NOT NULL"));
        api_routes.ToTable(t => t.HasCheckConstraint("ck_route_methods_timeout", "cardinality(methods) > 0 AND timeout_ms > 0"));
        application_credentials.ToTable(t => t.HasCheckConstraint("ck_credential_window", "expires_at > valid_from"));
        application_api_permissions.ToTable(t => t.HasCheckConstraint("ck_grant_window", "expires_at IS NULL OR expires_at > valid_from"));
        environments.ToTable(t => t.HasCheckConstraint("ck_deployment_sequence", "deployment_sequence >= 0"));
        gateway_config_versions.ToTable(t => t.HasCheckConstraint("ck_config_version", "version_no > 0"));
        audit_logs.HasIndex("EnvironmentId", "CreatedAt");
        outbox_messages.HasIndex("ProcessedAt", "LeaseUntil");
        gateway_nodes.HasIndex("EnvironmentId", "Enabled");
        release_records.HasIndex("EnvironmentId", "Status");
    }
}
