import {tabFocusTarget,recoveryFocusTarget} from './editor-focus.mjs';
import {editorMaySubmit,editorMayImplicitlySubmit} from './editor-state.mjs';import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';import {apiRequest,ApiError} from './api/client';import {useSession} from './auth/SessionProvider';import {readAllPages,withPage} from './api/paging.mjs';
export function useRemote<T>(path:string|null,interval=0,allPages=false){
 const {user}=useSession();const authority=user?user.id+JSON.stringify(user.permissions)+JSON.stringify(user.scopes):'anonymous';
 const[data,setData]=useState<T>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[updated,setUpdated]=useState<Date>(),[tick,setTick]=useState(0);
 const previous=useRef<string|undefined>(undefined);
 useEffect(()=>{
  const identity=JSON.stringify([path,authority]);const controller=new AbortController();
  if(previous.current!==identity){setData(undefined);setUpdated(undefined);previous.current=identity;}
  setError('');setLoading(true);if(!path){setLoading(false);return;}
  const load=async()=>{try{const result=await (allPages?readAllPages(apiRequest,path,{signal:controller.signal}):apiRequest<T>(path,{signal:controller.signal}));if(!controller.signal.aborted){setData(result);setError('');setUpdated(new Date());}}
   catch(e){if(!controller.signal.aborted){if(e instanceof ApiError&&[401,403,404].includes(e.status)){setData(undefined);setUpdated(undefined);}setError((e as Error).message);}}
   finally{if(!controller.signal.aborted)setLoading(false);}};
  void load();const timer=interval?setInterval(load,interval):undefined;
  return()=>{controller.abort();if(timer)clearInterval(timer);};
 },[path,tick,interval,authority,allPages]);return{data,error,loading,updated,reload:()=>setTick(t=>t+1)};
}
export function usePaged(path:string|null,interval=0){
 const[page,setPage]=useState(1);useEffect(()=>setPage(1),[path]);
 const remote=useRemote<any>(path?withPage(path,page):null,interval);
 useEffect(()=>{if(remote.data&&page>1&&page>Math.max(1,Math.ceil(remote.data.total/remote.data.pageSize)))setPage(1);},[remote.data,page]);
 return {...remote,page,setPage};
}
export function Pagination({remote}:{remote:{data?:any;page:number;setPage:(page:number)=>void;loading:boolean}}){const size=remote.data?.pageSize||50,total=remote.data?.total||0;return <div className="pagination"><span>共 {total} 条 · 每页 {size} 条</span><div><button disabled={remote.loading||remote.page<=1} onClick={()=>remote.setPage(remote.page-1)}>上一页</button><span>{remote.page}</span><button disabled={remote.loading||remote.page*size>=total} onClick={()=>remote.setPage(remote.page+1)}>下一页</button></div></div>;}
export function useUnsaved(dirty:boolean,blocked?:()=>void){
 const callback=useRef(blocked);callback.current=blocked;
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};const navigation=(e:Event)=>{if(dirty){e.preventDefault();callback.current?.();}};window.addEventListener('beforeunload',guard);window.addEventListener('app-navigation',navigation);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('app-navigation',navigation);};},[dirty]);
}
export function Status({value}:{value:unknown}){const text=String(value??'—');return <span className={'badge '+(['Active','Published','Succeeded','Applied','Ready'].includes(text)?'green':['Failed','Disabled','Rejected','Offline'].includes(text)?'red':['WaitingApproval','PendingApproval','Publishing','Building','Draft'].includes(text)?'amber':'blue')}>{text}</span>;}
export function Feedback({loading,error,updated}:{loading:boolean;error:string;updated?:Date}){return <>{loading&&<p className="empty" role="status">正在读取服务端数据…</p>}{error&&<div className="error" role="alert">{error}{updated&&'　最后读取：'+updated.toLocaleTimeString()+'，当前数据可能已过时。'}</div>}</>;}
export function Table({rows,columns,actions}:{rows:Record<string,any>[];columns:[string,string][];actions?:(row:any)=>ReactNode}){return <div className="table-wrap"><table><thead><tr>{columns.map(([key,title])=><th key={key}>{title}</th>)}{actions&&<th>操作</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||row.configVersion||i}>{columns.map(([key])=><td key={key}>{key==='status'?<Status value={row[key]}/>:typeof row[key]==='boolean'?(row[key]?'是':'否'):Array.isArray(row[key])?row[key].join('、'):String(row[key]??'—')}</td>)}{actions&&<td className="row-actions">{actions(row)}</td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">暂无记录</div>}</div>;}
export type Field={key:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[];help?:string};
export function Editor({title,fields,initial={},save,close,loadLatest,help='保存至工作配置，发布后才影响网关',renderFields,explicitSubmitOnly=false,allowed=true,conflictStatuses=[412]}:{conflictStatuses?:number[];explicitSubmitOnly?:boolean;allowed?:boolean;renderFields?:(value:Record<string,any>,change:(key:string,value:any)=>void)=>ReactNode;help?:string;title:string;fields:Field[];initial?:Record<string,any>;save:(value:Record<string,any>,key:string,fresh?:{revision?:number;eTag?:string})=>Promise<unknown>;close:()=>void;loadLatest?:()=>Promise<Record<string,any>>}){
 const[value,setValue]=useState(initial),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[latest,setLatest]=useState<Record<string,any>>(),[fresh,setFresh]=useState<{revision?:number;eTag?:string}>(),[invalid,setInvalid]=useState(false),[discard,setDiscard]=useState(false);const session=useSession();const key=useRef(crypto.randomUUID());const oldFocus=useRef<HTMLElement|null>(null);const editorRoot=useRef<HTMLFormElement>(null);
 const focusItems=(root:HTMLElement)=>[...root.querySelectorAll<HTMLElement>('input:not(:disabled):not([type=hidden]),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),a[href]')].filter(item=>item.tabIndex>=0&&item.getClientRects().length>0);
 useEffect(()=>{oldFocus.current=document.activeElement as HTMLElement;const root=editorRoot.current;if(root)(root.querySelector<HTMLElement>('input:not(:disabled):not([type=hidden]),select:not(:disabled),textarea:not(:disabled)')||focusItems(root)[0]||root).focus();return()=>{if(oldFocus.current?.isConnected)oldFocus.current.focus();};},[]);
 useEffect(()=>{const root=editorRoot.current;if(!root)return;const trap=root.querySelector<HTMLElement>('[role=alertdialog]')||root,items=focusItems(trap);const next=discard?items[0]||root:recoveryFocusTarget(items,document.activeElement,root);next?.focus();},[discard,busy,invalid,conflict,latest,session.error]);
 useUnsaved(dirty,()=>setError('仍有未保存的修改，请先保存或关闭表单。'));
 const change=(f:Field,v:any)=>{setValue(old=>({...old,[f.key]:v}));setDirty(true);key.current=crypto.randomUUID();};
 async function submit(e:FormEvent){e.preventDefault();if(!editorMaySubmit({authorized:allowed&&!session.error,invalid,busy,conflict,discard}))return;setBusy(true);setError('');try{const body={...value};for(const f of fields){if(f.type==='json')body[f.key]=JSON.parse(value[f.key]||'null');if(f.type==='number')body[f.key]=Number(value[f.key]||0);if(f.type==='datetime-local'&&value[f.key])body[f.key]=new Date(value[f.key]).toISOString();}await save(body,key.current,fresh);setDirty(false);close();}catch(e){setError((e as Error).message);setConflict(e instanceof ApiError&&conflictStatuses.includes(e.status));if(e instanceof ApiError&&[403,404].includes(e.status)){setInvalid(true);setDirty(false);setError('资源或权限已失效，已停止提交。请刷新会话后重新打开。');}}finally{setBusy(false);}}
 return <div className="overlay"><form ref={editorRoot} className={renderFields?"dialog permission-dialog":"dialog"} role="dialog" tabIndex={-1} aria-modal="true" aria-label={title} onSubmit={submit} onKeyDown={e=>{if(!editorMayImplicitlySubmit({explicitSubmitOnly,key:e.key,tag:(e.target as HTMLElement).tagName})){e.preventDefault();return;}if(e.key==='Escape'){e.preventDefault();if(!busy){if(discard)setDiscard(false);else if(dirty)setDiscard(true);else close();}}if(e.key==='Tab'){const trap=e.currentTarget.querySelector<HTMLElement>('[role=alertdialog]')||e.currentTarget;const next=tabFocusTarget(focusItems(trap),document.activeElement,e.shiftKey,e.currentTarget);if(next){e.preventDefault();next.focus();}}}}><header><h2>{title}</h2><button type="button" className="text-btn" disabled={busy} onClick={()=>{if(dirty)setDiscard(true);else close();}}>关闭</button></header><fieldset className="form-grid" disabled={!allowed||busy||invalid||discard}>{renderFields?renderFields(value,(key,v)=>change({key,label:key},v)):fields.map(f=><label key={f.key}>{f.label}{f.required&&' *'}{f.type==='checkbox'?<input type="checkbox" checked={!!value[f.key]} onChange={e=>change(f,e.target.checked)}/>:f.options?<select required={f.required} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}><option value="">请选择</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:['json','textarea'].includes(f.type||'')?<textarea required={f.required} rows={f.type==='json'?9:4} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}/>:<input required={f.required} type={f.type||'text'} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}/>}<small>{f.help}</small></label>)}</fieldset>{discard&&<div className="notice" role="alertdialog" aria-label="放弃未保存的修改"><p>放弃后，这些修改不会保存。</p><button type="button" className="btn" onClick={()=>setDiscard(false)}>继续编辑</button><button type="button" className="btn danger" onClick={()=>{setDirty(false);close();}}>确认放弃</button></div>}{error&&<div role="alert" className="error">{error}</div>}{conflict&&<div className="notice">你的输入已保留。先查看服务器最新内容，再决定如何合并。{loadLatest&&<button type="button" className="text-btn" onClick={async()=>{try{const result=await loadLatest();setLatest(result);setError('');}catch(e){setError((e as Error).message);}}}>查看最新内容</button>}{latest&&<><Details value={latest}/><button type="button" className="btn" disabled={!latest.revision&&!latest.workingRevision&&!latest.application?.revision&&!latest.eTag} onClick={()=>{setFresh({revision:latest.revision??latest.workingRevision??latest.application?.revision,eTag:latest.eTag});setConflict(false);key.current=crypto.randomUUID();}}>保持我的输入，采用最新修订</button></>}</div>}<footer>{allowed&&<button className="btn primary" disabled={busy||invalid||!!session.error||discard||conflict}>{busy?'保存中…':'保存'}</button>}<span>{help}</span></footer></form></div>;
}
export function Details({value}:{value:unknown}){return <pre className="code">{JSON.stringify(value,null,2)}</pre>;}
