import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';import {apiRequest,ApiError} from './api/client';import {useSession} from './auth/SessionProvider';
export function useRemote<T>(path:string|null,interval=0){
 const {user}=useSession();const authority=user?user.id+JSON.stringify(user.permissions)+JSON.stringify(user.scopes):'anonymous';
 const[data,setData]=useState<T>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[updated,setUpdated]=useState<Date>(),[tick,setTick]=useState(0);
 const previous=useRef<string|undefined>(undefined);
 useEffect(()=>{
  const identity=JSON.stringify([path,authority]);const controller=new AbortController();
  if(previous.current!==identity){setData(undefined);setUpdated(undefined);previous.current=identity;}
  setError('');setLoading(true);if(!path){setLoading(false);return;}
  const load=async()=>{try{const result=await apiRequest<T>(path,{signal:controller.signal});if(!controller.signal.aborted){setData(result);setError('');setUpdated(new Date());}}
   catch(e){if(!controller.signal.aborted){if(e instanceof ApiError&&[401,403].includes(e.status)){setData(undefined);setUpdated(undefined);}setError((e as Error).message);}}
   finally{if(!controller.signal.aborted)setLoading(false);}};
  void load();const timer=interval?setInterval(load,interval):undefined;
  return()=>{controller.abort();if(timer)clearInterval(timer);};
 },[path,tick,interval,authority]);return{data,error,loading,updated,reload:()=>setTick(t=>t+1)};
}
export function Status({value}:{value:unknown}){const text=String(value??'—');return <span className={'badge '+(['Active','Published','Succeeded','Applied','Ready'].includes(text)?'green':['Failed','Disabled','Rejected','Offline'].includes(text)?'red':['WaitingApproval','PendingApproval','Publishing','Building','Draft'].includes(text)?'amber':'blue')}>{text}</span>;}
export function Feedback({loading,error,updated}:{loading:boolean;error:string;updated?:Date}){return <>{loading&&<p className="empty" role="status">正在读取服务端数据…</p>}{error&&<div className="error" role="alert">{error}{updated&&'　最后读取：'+updated.toLocaleTimeString()+'，当前数据可能已过时。'}</div>}</>;}
export function Table({rows,columns,actions}:{rows:Record<string,any>[];columns:[string,string][];actions?:(row:any)=>ReactNode}){return <div className="table-wrap"><table><thead><tr>{columns.map(([key,title])=><th key={key}>{title}</th>)}{actions&&<th>操作</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||row.configVersion||i}>{columns.map(([key])=><td key={key}>{key==='status'?<Status value={row[key]}/>:typeof row[key]==='boolean'?(row[key]?'是':'否'):Array.isArray(row[key])?row[key].join('、'):String(row[key]??'—')}</td>)}{actions&&<td className="row-actions">{actions(row)}</td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">暂无记录</div>}</div>;}
export type Field={key:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[];help?:string};
export function Editor({title,fields,initial={},save,close,loadLatest,help='保存至工作配置，发布后才影响网关'}:{help?:string;title:string;fields:Field[];initial?:Record<string,any>;save:(value:Record<string,any>,key:string,fresh?:{revision?:number;eTag?:string})=>Promise<unknown>;close:()=>void;loadLatest?:()=>Promise<Record<string,any>>}){
 const[value,setValue]=useState(initial),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[latest,setLatest]=useState<Record<string,any>>(),[fresh,setFresh]=useState<{revision?:number;eTag?:string}>();const key=useRef(crypto.randomUUID());const oldFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{oldFocus.current=document.activeElement as HTMLElement;document.querySelector<HTMLElement>('.dialog input,.dialog select,.dialog textarea')?.focus();const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};const navigation=(e:Event)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',guard);window.addEventListener('app-navigation',navigation);return()=>{window.removeEventListener('beforeunload',guard);window.removeEventListener('app-navigation',navigation);oldFocus.current?.focus();};},[dirty]);
 const change=(f:Field,v:any)=>{setValue(old=>({...old,[f.key]:v}));setDirty(true);key.current=crypto.randomUUID();};
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={...value};for(const f of fields){if(f.type==='json')body[f.key]=JSON.parse(value[f.key]||'null');if(f.type==='number')body[f.key]=Number(value[f.key]||0);if(f.type==='datetime-local'&&value[f.key])body[f.key]=new Date(value[f.key]).toISOString();}await save(body,key.current,fresh);setDirty(false);close();}catch(e){setError((e as Error).message);setConflict(e instanceof ApiError&&e.status===412);}finally{setBusy(false);}}
 return <div className="overlay"><form className="dialog" role="dialog" aria-modal="true" aria-label={title} onSubmit={submit} onKeyDown={e=>{if(e.key==='Tab'){const items=[...e.currentTarget.querySelectorAll<HTMLElement>('input,select,textarea,button:not(:disabled)')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}><header><h2>{title}</h2><button type="button" className="text-btn" onClick={()=>{if(!dirty||window.confirm('放弃未保存的修改？'))close();}}>关闭</button></header><div className="form-grid">{fields.map(f=><label key={f.key}>{f.label}{f.required&&' *'}{f.type==='checkbox'?<input type="checkbox" checked={!!value[f.key]} onChange={e=>change(f,e.target.checked)}/>:f.options?<select required={f.required} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}><option value="">请选择</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:['json','textarea'].includes(f.type||'')?<textarea required={f.required} rows={f.type==='json'?9:4} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}/>:<input required={f.required} type={f.type||'text'} value={value[f.key]??''} onChange={e=>change(f,e.target.value)}/>}<small>{f.help}</small></label>)}</div>{error&&<div role="alert" className="error">{error}</div>}{conflict&&<div className="notice">你的输入已保留。先查看服务器最新内容，再决定如何合并。{loadLatest&&<button type="button" className="text-btn" onClick={async()=>{try{const result=await loadLatest();setLatest(result);setError('');}catch(e){setError((e as Error).message);}}}>查看最新内容</button>}{latest&&<><Details value={latest}/><button type="button" className="btn" disabled={!latest.revision&&!latest.workingRevision&&!latest.application?.revision&&!latest.eTag} onClick={()=>{setFresh({revision:latest.revision??latest.workingRevision??latest.application?.revision,eTag:latest.eTag});setConflict(false);key.current=crypto.randomUUID();}}>保持我的输入，采用最新修订</button></>}</div>}<footer><button className="btn primary" disabled={busy}>{busy?'保存中…':'保存'}</button><span>{help}</span></footer></form></div>;
}
export function Details({value}:{value:unknown}){return <pre className="code">{JSON.stringify(value,null,2)}</pre>;}
