using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApi.Gateway.Configuration;
using WebApi.Gateway;
using WebApi.Gateway.Workers;
using WebApi.Gateway.Tests.Support;
using WebApi.Infrastructure.Persistence.Entities;
using WebApi.TestBackend;
using WebApi.Gateway.Storage;
using WebApi.Contracts.Runtime;
using Yarp.ReverseProxy.Configuration;
using System.Text.Json;
using Xunit;
namespace WebApi.Gateway.Tests;
public sealed class GatewayRuntimeTests
{
    [Fact] public async Task RunningEntryRemainsConfirmedAfterRealDualGatewayRestart()
    {
        await using var s=new GatewayFixture();await s.InitializeAsync();var config=await s.PublishAsync();await s.ApplyBothAsync(config);
        using(var detail=await s.Control.Client.GetAsync($"/api/v1/environments/{s.Control.Environment.Id}"))
        {
            var e=await detail.Content.ReadFromJsonAsync<JsonElement>();using var saved=await s.Control.WriteAsync(HttpMethod.Put,$"/api/v1/environments/{s.Control.Environment.Id}",new {code=e.GetProperty("code").GetString(),name=e.GetProperty("name").GetString(),status="Active",isProduction=e.GetProperty("isProduction").GetBoolean(),releasePolicyId=e.GetProperty("releasePolicyId").ValueKind==JsonValueKind.Null?(Guid?)null:e.GetProperty("releasePolicyId").GetGuid(),sortOrder=0,gatewayPublicUrl="https://api.test",basePath="/gateway"},detail.Headers.ETag!.ToString());saved.EnsureSuccessStatusCode();
        }
        var endpoint=$"/api/v1/environments/{s.Control.Environment.Id}/apis/{s.Control.Api.Id}/access-addresses?view=running";
        using(var before=await s.Control.Client.GetAsync(endpoint))before.EnsureSuccessStatusCode();
        for(var i=0;i<2;i++){await s.RestartAsync(i);await WaitReadyAsync(s);var applied=await s.Gateways[i].Services.GetRequiredService<ConfigWatcher>().AcceptAsync(config);Assert.True(applied.Applied);}
        using(var running=await s.Control.Client.GetAsync(endpoint)){running.EnsureSuccessStatusCode();Assert.Contains("https://api.test/gateway/orders",await running.Content.ReadAsStringAsync());}
        await using var db=s.Control.Context();Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync());Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());
        var node=await db.Set<GatewayNode>().FirstAsync();var metadata=System.Text.Json.Nodes.JsonNode.Parse(node.Metadata!)!;metadata["runtimeApplication"]!["payloadHash"]="wrong-hash";node.Metadata=metadata.ToJsonString();await db.SaveChangesAsync();
        using var invalid=await s.Control.Client.GetAsync(endpoint);Assert.Equal(HttpStatusCode.Conflict,invalid.StatusCode);
    }
    [Fact] public async Task RealDoubleGatewayRestartConfirmsLkgWithoutRepublishing()
    {
        await using var s=new GatewayFixture();await s.InitializeAsync();var config=await s.PublishAsync();await s.ApplyBothAsync(config);
        var oldInstances=s.Gateways.Select(g=>g.Services.GetRequiredService<GatewaySettings>().InstanceId).ToArray();
        for(var i=0;i<2;i++) {await s.RestartAsync(i);var until=DateTimeOffset.UtcNow.AddSeconds(12);while(s.Gateways[i].Services.GetRequiredService<RuntimeGenerationStore>().Current is null&&DateTimeOffset.UtcNow<until) await Task.Delay(50);var gateway=s.Gateways[i];Assert.NotEqual(oldInstances[i],gateway.Services.GetRequiredService<GatewaySettings>().InstanceId);Assert.Equal(config.Envelope,gateway.Services.GetRequiredService<RuntimeGenerationStore>().Current!.Envelope);var result=await gateway.Services.GetRequiredService<ConfigWatcher>().AcceptAsync(config);Assert.True(result.Applied);using var traffic=await s.RequestAsync(i);traffic.EnsureSuccessStatusCode();Assert.Equal("A",(await traffic.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);}
        await using var db=s.Control.Context();Assert.Equal(1,await db.Set<ReleaseRecord>().CountAsync());Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());Assert.Equal(2,await db.Set<GatewayNodeEvent>().CountAsync(e=>e.EventType=="runtime_applied"));foreach(var node in await db.Set<GatewayNode>().ToArrayAsync()) {using var metadata=JsonDocument.Parse(node.Metadata!);Assert.Equal(node.InstanceId,metadata.RootElement.GetProperty("runtimeApplication").GetProperty("instanceId").GetString());}
    }
    [Fact] public async Task ActualRequestUsesPublishedDestination()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var config=await s.PublishAsync();await s.ApplyBothAsync(config);for(var i=0;i<2;i++) {using var response=await s.RequestAsync(i);response.EnsureSuccessStatusCode();var body=await response.Content.ReadFromJsonAsync<BackendResponse>();Assert.Equal("A",body!.BackendId);Assert.Equal("GET",body.Method);Assert.Equal("/orders",body.Path);Assert.False(body.ReceivedApiKey);}await using var db=s.Control.Context();Assert.Equal("Succeeded",(await db.Set<ReleaseRecord>().SingleAsync()).Status);Assert.Equal(2,await db.Set<GatewayAck>().CountAsync());}
    [Fact] public async Task RequestUsesOneRoutingAndAuthGeneration()
    {await using var s=new GatewayFixture();await s.InitializeAsync();await s.ApplyBothAsync(await s.PublishAsync());var oldKey=s.Credential;var probe=s.BackendA.Services.GetRequiredService<BackendProbe>();probe.HoldNext();var old=s.RequestAsync();await probe.Started.WaitAsync(TimeSpan.FromSeconds(5));await s.RotateCredentialAsync();var next=await s.PublishAsync(1);await s.ApplyBothAsync(next);using var current=await s.RequestAsync();current.EnsureSuccessStatusCode();var body=(await current.Content.ReadFromJsonAsync<BackendResponse>())!;Assert.Equal("B",body.BackendId);Assert.Equal(next.Envelope.DeploymentSequence,body.DeploymentSequence);using var rejected=await s.RequestAsync(key:oldKey);Assert.Equal(HttpStatusCode.Unauthorized,rejected.StatusCode);probe.Release();using var previous=await old;previous.EnsureSuccessStatusCode();var previousBody=(await previous.Content.ReadFromJsonAsync<BackendResponse>())!;Assert.Equal("A",previousBody.BackendId);Assert.Equal(1,previousBody.DeploymentSequence);Assert.Equal(next.Envelope.DeploymentSequence,s.Gateways[0].Services.GetRequiredService<RuntimeGenerationStore>().Current!.Envelope.DeploymentSequence);}
    [Fact] public async Task BadHashKeepsOldGenerationAndNoAck()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);var second=await s.PublishAsync(1);var corrupt=second.Payload.ToArray();corrupt[^1]^=1;await s.Gateways[0].Services.GetRequiredService<ConfigWatcher>().AcceptAsync(second with {Payload=corrupt});Assert.Equal(first.Envelope,s.Gateways[0].Services.GetRequiredService<RuntimeGenerationStore>().Current!.Envelope);using var traffic=await s.RequestAsync();traffic.EnsureSuccessStatusCode();Assert.Equal("A",(await traffic.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);await using var db=s.Control.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync(a=>a.ReleaseId==second.Envelope.ReleaseId&&a.Success));}
    [Fact] public async Task LkgWriteDeniedKeepsOldTraffic()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);var second=await s.PublishAsync(1);var directory=Path.GetDirectoryName(s.Gateways[0].Services.GetRequiredService<LkgStore>().FilePath)!;if(!OperatingSystem.IsWindows()) File.SetUnixFileMode(directory,UnixFileMode.UserRead|UnixFileMode.UserExecute);var result=await s.Gateways[0].Services.GetRequiredService<ConfigWatcher>().AcceptAsync(second);Assert.False(result.Applied);Assert.Equal("lkg_write_denied",result.ErrorCode);Assert.Equal(first.Envelope,(await s.Gateways[0].Services.GetRequiredService<LkgStore>().ReadAsync())!.Envelope);using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();Assert.Equal("A",(await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);await using var db=s.Control.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync(a=>a.ReleaseId==second.Envelope.ReleaseId&&a.Success));}
    private sealed class RejectSequenceFilter : IProxyConfigFilter
    {
        public long Sequence {get;set;}=2;
        public ValueTask<ClusterConfig> ConfigureClusterAsync(ClusterConfig cluster,CancellationToken ct)=>ValueTask.FromResult(cluster);
        public ValueTask<RouteConfig> ConfigureRouteAsync(RouteConfig route,ClusterConfig? cluster,CancellationToken ct) {if(route.Metadata?["deploymentSequence"]==Sequence.ToString()) throw new InvalidOperationException("Injected YARP config filter rejection.");return ValueTask.FromResult(route);}
    }
    [Fact] public async Task YarpRejectedConfigDoesNotAck()
    {var filter=new RejectSequenceFilter();await using var s=new GatewayFixture {ConfigureGateway=b=>b.Services.AddSingleton<IProxyConfigFilter>(filter)};await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);var second=await s.PublishAsync(1);var result=await s.Gateways[0].Services.GetRequiredService<ConfigWatcher>().AcceptAsync(second);Assert.False(result.Applied);Assert.Equal("yarp_rejected_config",result.ErrorCode);Assert.Equal(first.Envelope,(await s.Gateways[0].Services.GetRequiredService<LkgStore>().ReadAsync())!.Envelope);using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();Assert.Equal("A",(await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);await using var db=s.Control.Context();Assert.False(await db.Set<GatewayAck>().AnyAsync(a=>a.ReleaseId==second.Envelope.ReleaseId&&a.Success));}
    [Fact] public async Task CredentialExpiresAtAdmission()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var expires=DateTimeOffset.UtcNow.AddSeconds(5);await using(var db=s.Control.Context()) {var key=await db.Set<ApplicationCredential>().SingleAsync();key.ExpiresAt=expires;await db.SaveChangesAsync();}await s.ApplyBothAsync(await s.PublishAsync());using var gate=await s.Gateways[0].Services.GetRequiredService<AdmissionGate>().EnterAsync(CancellationToken.None);var waiting=s.RequestAsync();var delay=expires-DateTimeOffset.UtcNow+TimeSpan.FromMilliseconds(30);if(delay>TimeSpan.Zero) await Task.Delay(delay);gate.Dispose();using var response=await waiting;Assert.Equal(HttpStatusCode.Unauthorized,response.StatusCode);}
    [Fact] public async Task ControlPlaneAndRedisDownStillProxyFromLkg()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);await s.Control.StopServerAsync();s.ConfigureGateway=b=>{b.Configuration["Gateway:AutomaticUpdates"]="true";b.Configuration["Redis:Connection"]="127.0.0.1:1,abortConnect=false,connectTimeout=200,asyncTimeout=200";};await s.RestartAsync(0,false);await WaitReadyAsync(s);using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();Assert.Equal("A",(await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);Assert.Equal(first.Envelope,s.Gateways[0].Services.GetRequiredService<RuntimeGenerationStore>().Current!.Envelope);}
    [Fact] public async Task NoLkgNoRemoteNotReady()
    {await using var s=new GatewayFixture();await s.InitializeAsync();await s.Control.StopServerAsync();s.ConfigureGateway=b=>{b.Configuration["Gateway:AutomaticUpdates"]="true";b.Configuration["Redis:Connection"]="127.0.0.1:1,abortConnect=false,connectTimeout=200,asyncTimeout=200";};await s.RestartAsync(0,false);using var ready=await s.Clients[0].GetAsync("/health/ready");Assert.Equal(HttpStatusCode.ServiceUnavailable,ready.StatusCode);using var traffic=await s.RequestAsync();Assert.Equal(HttpStatusCode.ServiceUnavailable,traffic.StatusCode);using var healthPrefixBusiness=await s.RequestAsync(path:"/health/orders");Assert.Equal(HttpStatusCode.ServiceUnavailable,healthPrefixBusiness.StatusCode);}
    private static async Task WaitReadyAsync(GatewayFixture s)
    {var until=DateTimeOffset.UtcNow.AddSeconds(12);while(DateTimeOffset.UtcNow<until) {using var ready=await s.Clients[0].GetAsync("/health/ready");if(ready.IsSuccessStatusCode) return;await Task.Delay(50);}throw new TimeoutException("LKG gateway did not become ready.");}
    [Fact] public async Task RestartRejectsNewLkgButRestoresPriorUsableCopy()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);var second=await s.PublishAsync(1);await s.ApplyBothAsync(second);s.ConfigureGateway=b=>b.Services.AddSingleton<IProxyConfigFilter>(new RejectSequenceFilter());await s.RestartAsync(0);await WaitReadyAsync(s);using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();Assert.Equal("A",(await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);Assert.Equal(first.Envelope,s.Gateways[0].Services.GetRequiredService<RuntimeGenerationStore>().Current!.Envelope);}
    [Fact] public async Task RuntimeCollectionsCannotMutateAfterActivation()
    {await using var s=new GatewayFixture();await s.InitializeAsync();await s.ApplyBothAsync(await s.PublishAsync());var current=s.Gateways[0].Services.GetRequiredService<RuntimeGenerationStore>().Current!;Assert.Throws<NotSupportedException>(()=>((IList<RuntimeRoute>)current.Snapshot.Routes).Clear());Assert.Throws<NotSupportedException>(()=>((IList<string>)current.Snapshot.Routes[0].Methods).Clear());Assert.Throws<NotSupportedException>(()=>((IList<RuntimeCredential>)current.Snapshot.Applications[0].Credentials).Clear());using var traffic=await s.RequestAsync();traffic.EnsureSuccessStatusCode();}
    [Fact] public async Task RoundRobinActuallyUsesDestinationWeights()
    {await using var s=new GatewayFixture();await s.InitializeAsync();using var created=await s.Control.WriteAsync(HttpMethod.Post,$"/api/v1/clusters/{s.Control.Cluster.Id}/destinations",new {name="weighted-B",address=s.BackendUrls[1]+"/",weight=3,enabled=true});created.EnsureSuccessStatusCode();await s.ApplyBothAsync(await s.PublishAsync());var names=new List<string>();for(var i=0;i<8;i++) {using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();names.Add((await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);}Assert.Equal(2,names.Count(x=>x=="A"));Assert.Equal(6,names.Count(x=>x=="B"));}
    [Fact] public async Task CorruptLatestFileRestoresPreviousLkg()
    {await using var s=new GatewayFixture();await s.InitializeAsync();var first=await s.PublishAsync();await s.ApplyBothAsync(first);await s.ApplyBothAsync(await s.PublishAsync(1));await File.WriteAllTextAsync(s.Gateways[0].Services.GetRequiredService<LkgStore>().FilePath,"truncated snapshot");await s.RestartAsync(0);await WaitReadyAsync(s);using var response=await s.RequestAsync();response.EnsureSuccessStatusCode();Assert.Equal("A",(await response.Content.ReadFromJsonAsync<BackendResponse>())!.BackendId);}
}
