import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {assertMaintenanceWindow,assertDeliveryAuthorization,assertMigratedNotificationValues,assertNotificationTablePreservation,assertLegacyFrozenNotification} from '../../scripts/notification-approval/delivery.mjs';
const revision='a'.repeat(40),imageId='sha256:'+'b'.repeat(64),owner='00000000-0000-4000-8000-000000000001';
const authorization=()=>({approvedRevision:revision,candidate:{sourceRevision:revision,imageId},verification:{passed:true,sourceRevision:revision,imageId,stage:'pre-install',reviewStatus:'complete-four-important-fixed'},state:{projectName:'webapi-enterprise-local',ownerId:owner,ports:{console:4192,gatewayA:4196,gatewayB:4197}},baselineOwner:owner,modified:['.gitignore','README.md','docs/acceptance.md'],changed:['scripts/notification-approval/delivery.mjs'],staged:[]});
test('exact approved original installation may proceed',()=>assert.equal(assertDeliveryAuthorization(authorization()),true));
for(const[name,change]of [['foreign owner',a=>a.baselineOwner='00000000-0000-4000-8000-000000000002'],['foreign project',a=>a.state.projectName+='-test'],['different port',a=>a.state.ports.console=57531],['unverified candidate',a=>a.verification.passed=false],['different image',a=>a.verification.imageId='sha256:'+'c'.repeat(64)],['mutable approved source',a=>a.approvedRevision='HEAD'],['pending review',a=>a.verification.reviewStatus='pending'],['local source edit',a=>a.modified.push('src/WebApi.Worker/WorkerApp.cs')],['protected path overwritten',a=>a.changed.push('README.md')],['preexisting stage',a=>a.staged.push('docs/acceptance.md')]])test('delivery rejects '+name,()=>{const a=authorization();change(a);assert.throws(()=>assertDeliveryAuthorization(a));});
const window=()=>({initialized:true,pendingConfiguration:null,bindingPhase:'Applied',phase:'Ready',uncompletedReleases:0,unprocessedPublishOutbox:0});
test('stable maintenance window allowed',()=>assert.equal(assertMaintenanceWindow(window()),true));
for(const[name,change]of [['building release',w=>w.uncompletedReleases=1],['pending publish',w=>w.unprocessedPublishOutbox=1],['pending configuration',w=>w.pendingConfiguration={}],['unregistered state',w=>w.phase='Registered']])test('maintenance refuses '+name,()=>{const w=window();change(w);assert.throws(()=>assertMaintenanceWindow(w));});
const old={smtpHost:null,smtpPort:2525,fromEmail:null,smtpSecretRef:null,webhookUrl:null,webhookSecretRef:null};const next=()=>({...old,smtpEnabled:false,webhookEnabled:false,smtpSecurity:'StartTlsRequired'});
test('migration preserves six fields and disables external channels',()=>assert.equal(assertMigratedNotificationValues(old,next()),true));
for(const[name,change]of [['automatic send',v=>v.webhookEnabled=true],['changed host',v=>v.smtpHost='other'],['unknown extension',v=>v.extra=1]])test('migration refuses '+name,()=>{const v=next();change(v);assert.throws(()=>assertMigratedNotificationValues(old,v));});
const baseline=()=>({users:{mode:'exact',rows:{u:'hash'}},alert_events:{mode:'append-preserve',rows:{e:'hash'}}});const after=()=>({...baseline(),notification_channel_profiles:{mode:'append-preserve',rows:{}},notification_channel_states:{mode:'exact',rows:{}},notification_deliveries:{mode:'append-preserve',rows:{}},notification_delivery_attempts:{mode:'append-preserve',rows:{}}});
test('only declared notification tables may be added',()=>assert.equal(assertNotificationTablePreservation(baseline(),after()),true));
test('changed old account refuses installation receipt',()=>{const a=after();a.users.rows.u='changed';assert.throws(()=>assertNotificationTablePreservation(baseline(),a));});
test('missing notification table refuses installation receipt',()=>{const a=after();delete a.notification_deliveries;assert.throws(()=>assertNotificationTablePreservation(baseline(),a));});
test('unrelated schema addition refuses installation receipt',()=>{const a=after();a.unreviewed={rows:{}};assert.throws(()=>assertNotificationTablePreservation(baseline(),a));});

async function missingSecretRuntime(run){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-delivery-secret-'));await fs.chmod(dir,0o700);const write=(name,value)=>fs.writeFile(dir+'/'+name,typeof value==='string'?value:JSON.stringify(value),{mode:0o600});const project='webapi-enterprise-local-test-00000000-0000-4000-8000-000000000002',state={schemaVersion:1,projectName:project,ownerId:owner,ports:{console:57541,gatewayA:57542,gatewayB:57543},bootstrapUsername:'test-admin',binding:null,demoEnabled:false,releaseId:revision,initialized:true,bindingPhase:null,pendingConfiguration:null};await write('owner.json',{schemaVersion:1,projectName:project,ownerId:owner});await write('runtime.json',state);await write('release.json',{schemaVersion:1,sourceRevision:revision,imageId,configVersion:1,dependencyImages:{sdk:'sdk@sha256:'+'c'.repeat(64)}});await fs.mkdir(dir+'/notification-tooling',{mode:0o700});await write('notification-tooling/runner.mjs','// intact private runner\n');await write('notification-tooling.json',{softwareRevision:revision,runnerSha256:createHash('sha256').update(await fs.readFile(dir+'/notification-tooling/runner.mjs')).digest('hex')});await write('notification-runtime.json',{schemaVersion:1,ownerId:owner,projectName:project,enabled:true,fixtureEnabled:true,ports:{smtp:57544,https:57545,management:57546},secretReceipt:'notification-secrets/receipt.json'});try{await run(dir);}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('new maintenance entry fails closed on missing notification secrets without creating any replacement',async()=>missingSecretRuntime(async dir=>{const r=spawnSync(process.execPath,[path.resolve('scripts/notification-approval/manage.mjs'),'up',dir],{encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/ENOENT/);assert.equal(await fs.access(dir+'/notification-secrets').then(()=>true,()=>false),false);}));
test('new maintenance entry refuses changed software identity before starting services',async()=>missingSecretRuntime(async dir=>{await fs.writeFile(dir+'/notification-tooling.json',JSON.stringify({softwareRevision:'d'.repeat(40),runnerSha256:'e'.repeat(64)}),{mode:0o600});const r=spawnSync(process.execPath,[path.resolve('scripts/notification-approval/manage.mjs'),'start',dir],{encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/AssertionError/);assert.equal(await fs.access(dir+'/notification-secrets').then(()=>true,()=>false),false);}));

test('legacy event remains externally disabled without channel profile',()=>assert.equal(assertLegacyFrozenNotification({policy:{externalEnabled:false,emailRecipients:[]},emailProfileId:null,webhookProfileId:null}),true));
test('legacy event cannot acquire automatic sending',()=>assert.throws(()=>assertLegacyFrozenNotification({policy:{externalEnabled:true,emailRecipients:[]},emailProfileId:null,webhookProfileId:null})));
test('legacy event cannot acquire a frozen channel profile',()=>assert.throws(()=>assertLegacyFrozenNotification({policy:{externalEnabled:false,emailRecipients:[]},emailProfileId:owner,webhookProfileId:null})));
