// Synthetic unit vectors exercise the joint gate only. These are never published
// as actual browser/protocol acceptance or relabelled historical evidence.
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {validVector,rewrite as rewriteNotification} from '../notifications/evidence-vector.mjs';
import {requiredApprovalUiActions} from '../../scripts/approvals/evidence.mjs';
import {validateNotificationApprovalEvidence} from '../../scripts/notification-approval/evidence.mjs';
import {verifySuiteLogs} from '../../scripts/notification-approval/verify-suites.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),bridgeRevision='c'.repeat(40),bridgeImageId='sha256:'+'d'.repeat(64);
function vector(){
 const n=validVector(),{revision,imageId}=n.options,identity={sourceRevision:revision,imageId},staticFiles={'console/dist/index.html':'e'.repeat(64),'console/dist/assets/unit.js':'f'.repeat(64)};
 rewriteNotification(n,'runtime.json',o=>o.staticFiles=staticFiles);for(const action of n.proof.ui.actions)rewriteNotification(n,action.observation,o=>o.staticFiles=staticFiles);
 const files=n.files.map(f=>({...f,type:'file',path:'notifications/'+f.path}));
 const add=(name,value)=>{const content=Buffer.isBuffer(value)?value:Buffer.from(JSON.stringify(value));const file={path:name,type:'file',content,sha256:sha(content)};files.push(file);return file;};
 add('notifications/evidence.json',n.proof);
 const environments=['10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002'],releaseId='20000000-0000-4000-8000-000000000001';
 const expectations={'cross-environment':environments,'mixed-scope':[2,1,environments[0]],'read-only':[2,0,403],'self-approval':403,'second-page':[51,50,1,releaseId,1],'independent-seats':[403,403,2,'Ready',3],'revocation':[0,404]};
 const a={...identity,clone:{...n.proof.clone},environments,pagination:{...identity,total:51,pageSize:50,pendingMine:1,actionableId:releaseId,secondPageId:releaseId,countsFromService:true},checks:Object.entries(expectations).map(([id,value])=>({id,passed:true,...identity,evidence:{actual:JSON.stringify(value),expected:JSON.stringify(value),serviceResponse:{unit:true}}})),ui:{...identity,viewports:[1440,1280],actions:[],screenshots:[]},manifest:[]};
 for(const[id,index]of requiredApprovalUiActions.map((id,index)=>[id,index])){const viewport=index===1?1280:1440,pixels=readFileSync(new URL('../../docs/evidence/approvals/65a656f/'+id+'.jpg',import.meta.url)),f=add('approvals/'+id+'.jpg',pixels),observation=id+'-ui.json';add('approvals/'+observation,{...identity,id,source:'cua',actual:true,consolePort:n.proof.clone.consolePort,viewport,screenshotSha256:f.sha256,staticFiles});a.ui.actions.push({...identity,id,passed:true,viewport,screenshot:id+'.jpg',observation});a.ui.screenshots.push(id+'.jpg');a.manifest.push({path:id+'.jpg',sha256:f.sha256},{path:observation,sha256:files.at(-1).sha256});}
 add('approvals/evidence.json',a);
 const r=JSON.parse(readFileSync(new URL('../../docs/evidence/notification-approval/d1-cf2b470/recovery-receipt.json',import.meta.url)));Object.assign(r,identity);r.bridge.bridgeRevision=bridgeRevision;r.bridge.imageId=bridgeImageId;r.bridge.imageLabel=bridgeRevision;r.phases=[{revision,imageId},{revision:bridgeRevision,imageId:bridgeImageId,mode:'ReadOnly'},{revision,imageId}];
 const restore=JSON.parse(n.files.find(f=>f.path==='cold-recovery.json').content).restore;r.clone={ownerVerified:true,ownerId:restore.ownerId,projectName:restore.projectName,consolePort:restore.consolePort};r.protectedBefore.dpKeys=r.protectedAfter.dpKeys=sha(JSON.stringify(restore.dpKeysAfter));add('recovery/receipt.json',r);add('recovery/finally.json',{...identity,candidateRestored:true,proofComplete:true});
 const resources=['control-plane','worker','console','gateway-a','gateway-b'].map(service=>({Kind:'container',Id:'unit-'+service,Image:imageId,State:{Running:true},Config:{Labels:{'com.docker.compose.service':service,'com.docker.compose.project':n.proof.clone.projectName,'com.webapi.runtime.owner':n.proof.clone.ownerId}}}));
 add('images.json',{...identity,ownerId:n.proof.clone.ownerId,projectName:n.proof.clone.projectName,resources,images:[{Id:imageId,Config:{User:'10001:10001',Labels:{'org.opencontainers.image.revision':revision}}}]});add('static.json',{...identity,expected:staticFiles,actual:staticFiles});
 const gatewayChecks={ 'jwt-negative':{invalidStatus:401,ungrantedStatus:403,noUpstream:true},'identity-partition':{nodes:2,sharedFirstCalls:1,otherIdentityCalls:2},'retry-actual-calls':{physicalCalls:3,hitPhysicalCalls:0},'uncertain-send-not-retried':{status:502,physicalCalls:1},'rate-once':{firstPhysicalCalls:3,secondStatus:429,secondPhysicalCalls:0},'half-open-once':{initialPhysicalCalls:3,openPhysicalCalls:0,probePhysicalCalls:1},'scope-isolation':{foreignMappingRejected:true,readonlyWriteStatus:403},'redis-fault':{bypassStatus:200,secondRequestCalls:1},'two-level-publish':{releaseId,dualAck:true,targetConfigVersion:5,deploymentSequence:5,approvers:['30000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000002']},'rollback':{releaseId,dualAck:true,targetConfigVersion:5,newDeploymentSequence:6,coldCache:true},'downgrade-gate':{currentSchema:'2.2',nodeLkgSchemas:['2.2','2.2'],oldSoftwareRejected:true,databaseRestoreForbidden:true}};
 add('gateway-regression.json',{...identity,actual:true,complete:true,checks:Object.entries(gatewayChecks).map(([id,evidence])=>({id,passed:true,evidence}))});
 add('sso-regression.json',{...identity,actual:true,fixtureOwnerVerified:true,providerId:'40000000-0000-4000-8000-000000000001',externalIdentityId:'40000000-0000-4000-8000-000000000002',authSource:'sso',callbackStatus:302,authenticated:true,cookieAfterRestart:true,loginAuditCountDelta:1});
 add('regression.json',{...identity,actual:true,dualAck:true,gatewayStatuses:[200,200],sources:['prometheus','loki','tempo'].map(name=>({name,state:'Available'})),keycloakLogin:true,csrfRejected:true,readOnlyRejected:true,logoutRejected:true,jwtRetryCache:true});
 const logs=['domain','integration','gateway','console','runtime','features'].map(name=>{const node=['console','runtime','features'].includes(name),content='WEBAPI_FIXED_SOURCE '+revision+'\n'+(node?'ℹ tests 2\nℹ pass 2\nℹ fail 0\nℹ skipped 0\n':'  Passed WebApi.Unit.First\n  Passed WebApi.Unit.Second\nPassed! - Failed: 0, Passed: 2, Skipped: 0, Total: 2\n')+'WEBAPI_EXIT 0\n';return {name,sourceRevision:revision,passed:2,failed:0,skipped:0,exitCode:0,originalLogSha256:sha(content),log:'suites/'+name+'.log',content};});for(const{log,content,...summary}of logs){add(log,Buffer.from(content));add('suites/'+summary.name+'.json',{...summary,log});}
 const proof={schemaVersion:1,...identity,stage:'pre-install',originalInstallation:'not-upgraded',references:{notifications:'notifications/evidence.json',approvals:'approvals/evidence.json',recovery:'recovery/receipt.json',finally:'recovery/finally.json',images:'images.json',static:'static.json',regression:'regression.json',gatewayRegression:'gateway-regression.json',ssoRegression:'sso-regression.json'},suites:logs.map(({content,...summary})=>({...summary,artifact:'suites/'+summary.name+'.json'})),manifest:files.map(({path,sha256})=>({path,sha256}))};
 const options={revision,imageId,bridgeRevision,bridgeImageId,baselineRevision:r.bridge.baselineRevision,patchSha256:r.bridge.patchSha256,lockFiles:r.bridge.lockFiles,privateValues:['private-credential-canary']};
 return{proof,files,options,logs};
}
function mutate(v,name,change){const f=v.files.find(f=>f.path===name),value=JSON.parse(f.content);change(value);f.content=Buffer.from(JSON.stringify(value));f.sha256=sha(f.content);v.proof.manifest.find(m=>m.path===name).sha256=f.sha256;for(const prefix of ['notifications','approvals'])if(name.startsWith(prefix+'/')&&name!==prefix+'/evidence.json'){const wrapper=v.files.find(f=>f.path===prefix+'/evidence.json'),material=JSON.parse(wrapper.content),entry=material.manifest.find(m=>m.path===name.slice(prefix.length+1));if(entry){entry.sha256=f.sha256;wrapper.content=Buffer.from(JSON.stringify(material));wrapper.sha256=sha(wrapper.content);v.proof.manifest.find(m=>m.path===wrapper.path).sha256=wrapper.sha256;}}}
test('complete synthetic joint evidence is accepted',()=>{const v=vector();assert.deepEqual(validateNotificationApprovalEvidence(v.proof,v.files,v.options),{passed:true,errors:[]});});
for(const[name,change]of [
 ['missing recovery',v=>delete v.proof.references.recovery],['wrong candidate',v=>v.proof.sourceRevision='e'.repeat(40)],['wrong bridge',v=>mutate(v,'recovery/receipt.json',o=>o.bridge.bridgeRevision='e'.repeat(40))],['missing mixed Scope',v=>mutate(v,'approvals/evidence.json',o=>o.checks=o.checks.filter(c=>c.id!=='mixed-scope'))],['meaningless mixed Scope',v=>mutate(v,'approvals/evidence.json',o=>{const c=o.checks.find(c=>c.id==='mixed-scope');c.evidence.actual=c.evidence.expected='true';})],['fake 5xx physical calls',v=>mutate(v,'notifications/webhook-5xx-retry.json',o=>o.actual=o.expected=[[1,500,'TransientFailure']])],['missing silence race',v=>mutate(v,'notifications/evidence.json',o=>o.checks=o.checks.filter(c=>c.id!=='silence-in-flight'))],['relabelled internal source',v=>mutate(v,'notifications/runtime.json',o=>o.sourceRevision='e'.repeat(40))],['fake HMAC signature',v=>mutate(v,'notifications/fixture.json',o=>o.protocol.webhook[0].signatureValid=false)],['wrong container image',v=>mutate(v,'images.json',o=>o.resources[0].Image='sha256:'+'e'.repeat(64))],['wrong static bytes',v=>mutate(v,'static.json',o=>o.actual['console/dist/index.html']='a'.repeat(64))],['no actual UI action',v=>mutate(v,'approvals/conflict-comment-ui.json',o=>o.actual=false)],['nonUUID clone',v=>mutate(v,'images.json',o=>o.projectName='webapi-enterprise-local')],['private canary',v=>mutate(v,'regression.json',o=>o.annotation='private-credential-canary')],['raw email',v=>mutate(v,'regression.json',o=>o.annotation='person@enterprise.example')],['retagged old suite counts',v=>{v.proof.suites[0].passed=1629;}],['not actually restored',v=>mutate(v,'recovery/finally.json',o=>o.proofComplete=false)],['no live SSO',v=>mutate(v,'regression.json',o=>o.keycloakLogin=false)],['no old capabilities regression',v=>mutate(v,'regression.json',o=>o.jwtRetryCache=false)]])test(name,()=>{const v=vector();change(v);assert.equal(validateNotificationApprovalEvidence(v.proof,v.files,v.options).passed,false);});
test('suite receipt reads current log totals',()=>{const v=vector(),r=verifySuiteLogs(v.logs,{revision:v.options.revision});assert.equal(r.suites.length,5);assert.equal(r.features.passed,2);assert(r.suites.every(s=>s.passed===2));});
for(const[name,change]of [['stale header',v=>v.logs[0].content=v.logs[0].content.replace(v.options.revision,'f'.repeat(40))],['nonzero exit',v=>v.logs[0].content=v.logs[0].content.replace('WEBAPI_EXIT 0','WEBAPI_EXIT 1')],['filtered suite',v=>v.logs.pop()],['wrong reported total',v=>v.logs[0].passed=1629],['skip',v=>v.logs[3].content=v.logs[3].content.replace('ℹ skipped 0','ℹ skipped 1')]])test('suite gate rejects '+name,()=>{const v=vector();change(v);assert.throws(()=>verifySuiteLogs(v.logs,{revision:v.options.revision}));});

for(const[name,change]of [['fake cached shared counts',v=>mutate(v,'gateway-regression.json',o=>o.checks.find(c=>c.id==='identity-partition').evidence.sharedFirstCalls=2)],['fake physical retry count',v=>mutate(v,'gateway-regression.json',o=>o.checks.find(c=>c.id==='retry-actual-calls').evidence.physicalCalls=1)],['borrowed approval identity',v=>mutate(v,'gateway-regression.json',o=>{const e=o.checks.find(c=>c.id==='two-level-publish').evidence;e.approvers[1]=e.approvers[0];})],['boolean SSO without callback',v=>mutate(v,'sso-regression.json',o=>delete o.callbackStatus)],['SSO source drift',v=>mutate(v,'sso-regression.json',o=>o.sourceRevision='f'.repeat(40))]])test(name,()=>{const v=vector();change(v);assert.equal(validateNotificationApprovalEvidence(v.proof,v.files,v.options).passed,false);});

test('approval and notification actions cannot reuse the same capture',()=>{const v=vector(),source=v.files.find(f=>f.path==='notifications/settings-1440.png'),target=v.files.find(f=>f.path==='approvals/inbox-1440.jpg');target.content=source.content;target.sha256=source.sha256;v.proof.manifest.find(m=>m.path===target.path).sha256=target.sha256;mutate(v,'approvals/evidence.json',o=>o.manifest.find(m=>m.path==='inbox-1440.jpg').sha256=target.sha256);mutate(v,'approvals/inbox-1440-ui.json',o=>o.screenshotSha256=target.sha256);assert.equal(validateNotificationApprovalEvidence(v.proof,v.files,v.options).passed,false);});

test('parent metadata cannot publish a private canary',()=>{const v=vector();v.proof.annotation=v.options.privateValues[0];assert.equal(validateNotificationApprovalEvidence(v.proof,v.files,v.options).passed,false);});

import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {readEvidenceFile,sealNotificationApprovalEvidence} from '../../scripts/notification-approval/acceptance.mjs';
test('seal verifies all bytes and never replaces existing evidence',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-joint-gate-'));try{const v=vector(),directory=root+'/sealed';assert.deepEqual(await sealNotificationApprovalEvidence({...v,directory}),{passed:true,errors:[]});const manifest=JSON.parse(await fs.readFile(directory+'/manifest.json'));assert(manifest.complete&&manifest.originalInstallation==='not-upgraded');for(const file of manifest.files)assert.equal((await readEvidenceFile(directory,file.path)).sha256,file.sha256);await assert.rejects(()=>sealNotificationApprovalEvidence({...v,directory}),e=>e.code==='EEXIST');}finally{await fs.rm(root,{recursive:true});}});
test('failed seal leaves no complete artifact',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-joint-gate-'));try{const v=vector(),directory=root+'/failed';v.proof.annotation=v.options.privateValues[0];await assert.rejects(()=>sealNotificationApprovalEvidence({...v,directory}));await assert.rejects(()=>fs.stat(directory),e=>e.code==='ENOENT');}finally{await fs.rm(root,{recursive:true});}});
test('manifest reads reject traversal and symlink inputs',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'webapi-joint-gate-'));try{await fs.writeFile(root+'/real.json','{}');await fs.symlink(root+'/real.json',root+'/link.json');await fs.symlink(root,root+'-link');for(const name of ['../real.json','/real.json','./real.json','link.json'])await assert.rejects(()=>readEvidenceFile(root,name));await assert.rejects(()=>readEvidenceFile(root+'-link','real.json'));assert.equal((await readEvidenceFile(root,'real.json')).content.toString(),'{}');}finally{await fs.rm(root+'-link',{force:true});await fs.rm(root,{recursive:true});}});

import * as suiteDriver from '../../scripts/notification-approval/verify-suites.mjs';
test('full runtime suites require the built candidate release identity',()=>{const revision='a'.repeat(40),release={schemaVersion:1,configVersion:1,sourceRevision:revision,imageId:'sha256:'+'b'.repeat(64),staticFiles:{'console/dist/index.html':'c'.repeat(64)},applications:{'notification-fixture/WebApi.NotificationFixtureHost.dll':'d'.repeat(64)}};assert.equal(suiteDriver.validateSuiteRelease(release,revision),true);assert.throws(()=>suiteDriver.validateSuiteRelease({...release,sourceRevision:'e'.repeat(40)},revision));assert.throws(()=>suiteDriver.validateSuiteRelease({...release,applications:{}},revision));});
