import test from 'node:test';import assert from 'node:assert/strict';import {validateBridgeReceipt,buildNotificationBridge} from '../../scripts/notification-approval/bridge.mjs';import {validateDataPreservingRecovery,assertOldWorkerFrozenOff,assertRecoveredNotificationWire} from '../../scripts/notification-approval/recovery.mjs';
const baseline='c1c271555e3a125d22184697c17320c94a4db07c',bridge='a'.repeat(40),candidate='b'.repeat(40),bridgeImage='sha256:'+'1'.repeat(64),candidateImage='sha256:'+'2'.repeat(64),patch='3'.repeat(64),lock='4'.repeat(64);
const options={baselineRevision:baseline,bridgeRevision:bridge,bridgeImageId:bridgeImage,candidateRevision:candidate,candidateImageId:candidateImage,patchSha256:patch,lockFiles:{'Directory.Packages.props':lock,'console/pnpm-lock.yaml':lock}};
test('old worker default freeze is read from nested persisted policy',()=>assert.equal(assertOldWorkerFrozenOff({policy:{externalEnabled:false,requestedChannels:[]},emailProfileId:null,webhookProfileId:null}),true));
test('top level flag cannot conceal enabled policy',()=>assert.throws(()=>assertOldWorkerFrozenOff({externalEnabled:false,policy:{externalEnabled:true,requestedChannels:['Webhook']},emailProfileId:null,webhookProfileId:null})));
test('missing frozen policy fails closed',()=>assert.throws(()=>assertOldWorkerFrozenOff({externalEnabled:false})));
const wireTasks=[{id:'email-task',channel:'Email',status:'Accepted'},{id:'hook-task',channel:'Webhook',status:'Accepted'}];
const smtpWire=()=>[{deliveryId:'email-task',accepted:true,tls:true,authenticated:true,recipientCount:1,ccCount:0,bccCount:0,replyCode:250}],hookWire=()=>[{deliveryId:'hook-task',remoteAccepted:true,tls:true,signatureValid:true,replyCode:202}];
test('recovered SMTP and Webhook use their actual distinct acceptance fields',()=>assert.equal(assertRecoveredNotificationWire(wireTasks,smtpWire(),hookWire()),true));
test('SMTP remoteAccepted alias cannot conceal a rejected DATA receipt',()=>assert.throws(()=>assertRecoveredNotificationWire(wireTasks,[{...smtpWire()[0],accepted:false,remoteAccepted:true}],hookWire())));
test('Webhook without verified HMAC cannot pass recovery',()=>assert.throws(()=>assertRecoveredNotificationWire(wireTasks,smtpWire(),[{...hookWire()[0],signatureValid:false}])));
test('unrelated wire delivery cannot prove accepted tasks',()=>assert.throws(()=>assertRecoveredNotificationWire(wireTasks,[{...smtpWire()[0],deliveryId:'different'}],hookWire())));
for(const [name,fields] of [['different baseline',{baselineRevision:candidate}],['missing owner',{owner:null}],['mutable ref',{bridgeRevision:'HEAD'}],['unchanged baseline',{bridgeRevision:baseline}]])test('bridge builder rejects '+name+' before any build',async()=>{await assert.rejects(()=>buildNotificationBridge({baselineRevision:baseline,owner:'00000000-0000-0000-0000-000000000003',bridgeRevision:bridge,...fields}));});
test('bridge builder refuses original local runtime as build storage',async()=>assert.rejects(()=>buildNotificationBridge({baselineRevision:baseline,bridgeRevision:bridge,owner:'00000000-0000-0000-0000-000000000003',directory:'/workspace/.runtime/local',root:'/missing'}),/separate private build storage/));
const bridgeReceipt=()=>({schemaVersion:1,baselineRevision:baseline,bridgeRevision:bridge,imageId:bridgeImage,imageLabel:bridge,patchSha256:patch,lockFiles:options.lockFiles,changedFiles:['src/WebApi.Infrastructure/Settings/SettingsValues.cs','src/WebApi.Infrastructure/Notifications/CompatibilityNotificationMode.cs','tests/WebApi.Integration.Tests/NotificationCompatibilityBridgeTests.cs'],readonlyMode:'ReadOnly',notificationsWritable:false,rulesWritable:false,buildSource:'git-archive',dirtyCheckoutIncluded:false});
const recovery=()=>({schemaVersion:1,sourceRevision:candidate,imageId:candidateImage,actual:true,clone:{projectName:'webapi-enterprise-local-test-00000000-0000-0000-0000-000000000002',ownerId:'00000000-0000-0000-0000-000000000003',consolePort:57541,ownerVerified:true},bridge:bridgeReceipt(),phases:[{revision:candidate,imageId:candidateImage},{revision:bridge,imageId:bridgeImage,mode:'ReadOnly'},{revision:candidate,imageId:candidateImage}],drained:true,maintenanceDrain:{initial:{workersStopped:true,incompleteAttempts:1,unknownAttempts:1,automaticRetryFrozen:true,originalBudgetRetained:true,noNewAttempts:true},afterBackup:{workersStopped:true,incompleteAttempts:0,unknownAttempts:0,automaticRetryFrozen:true,originalBudgetRetained:true,noNewAttempts:true}},sendingBeforeSwitch:0,sourceDatabaseRestored:false,oldImageRejectsNine:true,protectedBefore:{business:lock,accounts:lock,attachments:lock,notificationDefinitions:lock,notificationHistory:lock,dpKeys:lock,sso:lock},protectedAfter:{business:lock,accounts:lock,attachments:lock,notificationDefinitions:lock,notificationHistory:lock,dpKeys:lock,sso:lock},backup:{actual:true,manifestVerified:true,volumes:['pg','lkg-a','lkg-b','dp-keys','prometheus-data','loki-data','tempo-data','secrets-cache','notification-secrets','notification-fixture-secrets','notification-fixture-data'],manifestFilesVerified:20},bridgeChecks:{settingsGroups:5,notificationSave:423,ruleCreate:423,ruleUpdate:423,ruleEnable:423,ruleDisable:423,notificationTest:423,notificationRetry:423,otherBusinessWrite:true,oldWorkerFrozenOff:true},candidateRestored:{ready:true,dpRetained:true,ssoRetained:true,noRetrospectiveSends:true,smtpAccepted:true,webhookAccepted:true}});
test('valid pinned bridge receipt passes',()=>assert.deepEqual(validateBridgeReceipt(bridgeReceipt(),options),{passed:true,errors:[]}));
for(const [name,change]of [['wrong bridge identity',r=>r.bridgeRevision='f'.repeat(40)],['wrong baseline',r=>r.baselineRevision='e'.repeat(40)],['wrong image',r=>r.imageId=candidateImage],['archive pollution',r=>r.dirtyCheckoutIncluded=true],['changed lock',r=>r.lockFiles={'console/pnpm-lock.yaml':'5'.repeat(64)}],['unreviewed source',r=>r.changedFiles.push('src/WebApi.Infrastructure/Releases/ReleaseService.cs')],['writable rule bridge',r=>r.rulesWritable=true],['patch mismatch',r=>r.patchSha256='6'.repeat(64)]])test(name,()=>{const r=bridgeReceipt();change(r);assert.equal(validateBridgeReceipt(r,options).passed,false);});
test('newBusinessRowsAndNotificationDefinitionsSurvive',()=>assert.equal(validateDataPreservingRecovery(recovery(),options).passed,true));
for(const [name,change]of [['lost business',r=>r.protectedAfter.business='7'.repeat(64)],['lost notification definitions',r=>r.protectedAfter.notificationDefinitions='7'.repeat(64)],['lost DP',r=>delete r.protectedAfter.dpKeys],['lost secret backup',r=>r.backup.volumes=r.backup.volumes.filter(x=>x!=='notification-secrets')],['old DB overwrite',r=>r.sourceDatabaseRestored=true],['sending switch',r=>r.sendingBeforeSwitch=1],['wrong candidate',r=>r.phases[2].revision=bridge],['nonUUID original',r=>r.clone.projectName='webapi-enterprise-local'],['original port',r=>r.clone.consolePort=4192],['bridgeRejectsUnknownJsonAndRuleWrites',r=>r.bridgeChecks.ruleUpdate=200],['silent old worker sends',r=>r.bridgeChecks.oldWorkerFrozenOff=false],['unverified backup',r=>r.backup.manifestVerified=false],['no real recovery',r=>r.actual=false]])test(name,()=>{const r=recovery();change(r);assert.equal(validateDataPreservingRecovery(r,options).passed,false);});

for(const [name,change]of [['invalid owner UUID',r=>r.clone.ownerId='-'.repeat(36)],['invalid clone UUID',r=>r.clone.projectName='webapi-enterprise-local-test-'+'f'.repeat(36)],['out of range port',r=>r.clone.consolePort=65536],['missing observation archive',r=>r.backup.volumes=r.backup.volumes.filter(x=>x!=='loki-data')],['duplicate archive',r=>r.backup.volumes.push('pg')]])test(name,()=>{const r=recovery();change(r);assert.equal(validateDataPreservingRecovery(r,options).passed,false);});

import * as recoveryModule from '../../scripts/notification-approval/recovery.mjs';
const drainState={projectName:'webapi-enterprise-local-test-00000000-0000-4000-8000-000000000002',ownerId:'00000000-0000-4000-8000-000000000003'};
const drainResource=(owner,running)=>({Kind:'container',Config:{Labels:{'com.docker.compose.project':drainState.projectName,'com.webapi.runtime.owner':owner,'com.docker.compose.service':'worker'}},State:{Running:running}});
test('maintenance refuses a worker which remains running after stop',async()=>{assert.equal(typeof recoveryModule.drainStoppedNotificationAttempts,'function');const ctx={state:drainState,compose:async()=>{}},sql=async()=>{throw Error('Unexpected database access');};await assert.rejects(()=>recoveryModule.drainStoppedNotificationAttempts(ctx,sql,{inspect:async()=>[drainResource(drainState.ownerId,true)]}),/Worker.*stopped/);});
test('maintenance rejects foreign resources before stopping anything',async()=>{assert.equal(typeof recoveryModule.drainStoppedNotificationAttempts,'function');const ctx={state:drainState,compose:async()=>{throw Error('Unexpected stop');}},sql=async()=>{throw Error('Unexpected database access');};await assert.rejects(()=>recoveryModule.drainStoppedNotificationAttempts(ctx,sql,{inspect:async()=>[drainResource('foreign',false)]}),/owner mismatch/);});

test('recovery evidence cannot conceal missing stopped-worker maintenance recovery',()=>{const receipt=recovery();delete receipt.maintenanceDrain;assert.equal(validateDataPreservingRecovery(receipt,options).passed,false);});

test('an idle-only recovery cannot prove interrupted send maintenance',()=>{const receipt=recovery();receipt.maintenanceDrain.initial.incompleteAttempts=0;receipt.maintenanceDrain.initial.unknownAttempts=0;assert.equal(validateDataPreservingRecovery(receipt,options).passed,false);});
